In [1]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from biochatter_utility import return_biochatter_answer

In [2]:



model = "BioChatter"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [3]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3

/home/abhishekh/anaconda3/envs/biochirp/lib/python3.11/site-packages/biochatter/llm_connect/conversation.py:34: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  from biochatter.selector_agent import RagAgentSelector

Entries retrieved: 8

  disease_name gene_name
0     Melanoma      BRAF

 Run 1 completed | rows=8 | latency=29.629s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 11

  disease_name gene_name
0     Melanoma      BRAF

 Run 2 completed | rows=11 | latency=33.585s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     Melanoma      BRAF

 Run 3 completed | rows=9 | latency=19.494s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 6

  disease_name gene_name
0     Melanoma      BRAF

 Run 4 completed | rows=6 | latency=17.480s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     Melanoma      BRAF

 Run 5 completed | rows=10 | latency=27.013s
------------------------------------------------------------


## Question 2

**Which genes are associated with amyotrophic lateral sclerosis?**

In [4]:

question = 'Which genes are associated with amyotrophic lateral sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 15

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 1 completed | rows=15 | latency=37.396s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 17

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 2 completed | rows=17 | latency=33.592s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 17

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 3 completed | rows=17 | latency=32.656s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 17

                    disease_name gene_name
0  Amyotrophic lateral sclerosis      SOD1

 Run 4 completed | rows=17 | latency=23.256s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 16

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 5 completed | rows=16 | latency=28.362s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [5]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0     Melanoma      CDK4

 Run 1 completed | rows=2 | latency=22.862s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

                      disease_name gene_name
0  well-differentiated liposarcoma      CDK4

 Run 2 completed | rows=4 | latency=24.443s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

                      disease_name gene_name
0  Well-differentiated liposarcoma      CDK4

 Run 3 completed | rows=3 | latency=24.999s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

   disease_name gene_name
0  Glioblastoma      CDK4

 Run 4 completed | rows=4 | latency=33.447s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Liposarcoma      CDK4

 Run 5 completed | rows=2 | latency=24.936s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [6]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 1 completed | rows=1 | latency=19.546s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 2 completed | rows=1 | latency=28.444s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 3 completed | rows=1 | latency=23.189s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 29.738s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 4 completed | rows=1 | latency=23.991s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 5 completed | rows=1 | latency=20.536s
------------------------------------------------------------


## Question 5

**Which drugs are used to treat rheumatoid arthritis?**

In [7]:

question = 'Which drugs are used to treat rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  Methotrexate  Rheumatoid arthritis

 Run 1 completed | rows=17 | latency=34.939s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  methotrexate  Rheumatoid arthritis

 Run 2 completed | rows=17 | latency=29.817s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  methotrexate  Rheumatoid arthritis

 Run 3 completed | rows=17 | latency=24.138s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  Methotrexate  Rheumatoid arthritis

 Run 4 completed | rows=17 | latency=23.553s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 16

      drug_name          disease_name
0  Methotrexate  Rheumatoid arthritis

 Run 5 completed | rows=16 | latency=22.115s
------------------------------------------------------------


## Question 6

**Which genes are associated with ovarian cancer?**

In [8]:

question = 'Which genes are associated with ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 12

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 1 completed | rows=12 | latency=24.290s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 11

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 2 completed | rows=11 | latency=22.768s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 11

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 3 completed | rows=11 | latency=28.716s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 4 completed | rows=10 | latency=29.388s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 5 completed | rows=10 | latency=23.422s
------------------------------------------------------------


## Question 7

**What are the known targets of regorafenib?**

In [9]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

     drug_name gene_name
0  regorafenib       KDR

 Run 1 completed | rows=12 | latency=35.586s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  regorafenib       KDR

 Run 2 completed | rows=11 | latency=28.607s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  regorafenib       KDR

 Run 3 completed | rows=11 | latency=24.216s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

     drug_name gene_name
0  regorafenib       KDR

 Run 4 completed | rows=12 | latency=24.955s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

     drug_name gene_name
0  regorafenib       KDR

 Run 5 completed | rows=12 | latency=30.817s
------------------------------------------------------------


## Question 8

**Which pathways are associated with the STAT3 gene?**

In [10]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 1 completed | rows=1 | latency=30.103s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 2 completed | rows=1 | latency=24.229s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 3 completed | rows=1 | latency=17.367s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 4 completed | rows=1 | latency=16.467s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 5 completed | rows=1 | latency=29.906s
------------------------------------------------------------


## Question 9

**Which genes are associated with fever (pyrexia)?**

In [11]:

question = 'Which genes are associated with fever (pyrexia)?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0        Fever      MEFV

 Run 1 completed | rows=7 | latency=20.519s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [disease_name, gene_name]
Index: []

 Attempt 1 failed after 20.941s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 4

  disease_name gene_name
0        Fever      IL1B

 Run 2 completed | rows=4 | latency=24.074s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

                   disease_name gene_name
0  Familial Mediterranean Fever      MEFV

 Run 3 completed | rows=4 | latency=26.199s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0        Fever      IL1B

 Run 4 completed | rows=3 | latency=21.971s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0        Fever      IL1B

 Run 5 completed | rows=4 | latency=18.190s
------------------------------------------------------------


## Question 10

**Which diseases are treated with bevacizumab?**

In [12]:

question = 'Which diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 1 completed | rows=6 | latency=23.787s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  bevacizumab  Colorectal cancer

 Run 2 completed | rows=6 | latency=29.163s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 8

     drug_name                  disease_name
0  bevacizumab  metastatic colorectal cancer

 Run 3 completed | rows=8 | latency=23.703s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 8

     drug_name                  disease_name
0  bevacizumab  Metastatic colorectal cancer

 Run 4 completed | rows=8 | latency=36.953s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name                  disease_name
0  bevacizumab  Metastatic colorectal cancer

 Run 5 completed | rows=6 | latency=26.264s
------------------------------------------------------------


## Question 11

**What are the known targets of cabozantinib?**

In [13]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       MET

 Run 1 completed | rows=5 | latency=19.665s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       MET

 Run 2 completed | rows=5 | latency=13.286s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       MET

 Run 3 completed | rows=5 | latency=14.189s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       MET

 Run 4 completed | rows=5 | latency=13.519s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       MET

 Run 5 completed | rows=5 | latency=15.038s
------------------------------------------------------------


## Question 12

**Which pathways are associated with the TNF gene?**

In [14]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0       TNF  TNF signaling pathway

 Run 1 completed | rows=4 | latency=31.586s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 7

  gene_name           pathway_name
0       TNF  TNF signaling pathway

  Attempt 2/3
Entries retrieved: 4

  gene_name           pathway_name
0       TNF  TNF signaling pathway

 Run 2 completed | rows=4 | latency=30.156s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0       TNF  TNF signaling pathway

 Run 3 completed | rows=4 | latency=32.366s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 4 completed | rows=4 | latency=21.499s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0       TNF  TNF signaling pathway

 Run 5 completed | rows=1 | latency=26.052s
------------------------------------------------------------


## Question 13

**Which diseases are associated with the NPM1 gene?**

In [15]:

question = 'Which diseases are associated with the NPM1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 1 completed | rows=1 | latency=23.490s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 2 completed | rows=1 | latency=17.759s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 3 completed | rows=1 | latency=30.943s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 4 completed | rows=1 | latency=19.773s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 5 completed | rows=1 | latency=16.602s
------------------------------------------------------------


## Question 14

**Which pathways are associated with the CD19 gene?**

In [16]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 1 completed | rows=2 | latency=21.564s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 2 completed | rows=2 | latency=24.353s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 3 completed | rows=1 | latency=27.037s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 4 completed | rows=2 | latency=23.331s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 5 completed | rows=2 | latency=17.836s
------------------------------------------------------------


## Question 15

**Which drugs are used to treat migraine?**

In [17]:

question = 'Which drugs are used to treat migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 19

     drug_name disease_name
0  sumatriptan     Migraine

  Attempt 2/3
Entries retrieved: 16

     drug_name disease_name
0  sumatriptan     Migraine

  Attempt 3/3
Entries retrieved: 12

     drug_name disease_name
0  sumatriptan     Migraine

 Run 1 completed | rows=12 | latency=30.860s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 15

     drug_name disease_name
0  sumatriptan     migraine

 Run 2 completed | rows=15 | latency=37.587s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 22

     drug_name disease_name
0  sumatriptan     Migraine

  Attempt 2/3
Entries retrieved: 15

     drug_name disease_name
0  sumatriptan     migraine

 Run 3 completed | rows=15 | latency=31.733s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 23

     drug_name disease_name
0  sumatriptan     Migraine

  Attempt 2/3
Entries retrieved: 16

     drug_name disease_name
0  sumatriptan     migraine

  Attempt 3/3
Entries retrieved: 16

     drug_name disease_name
0  sumatriptan     migraine

------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 14

     drug_name disease_name
0  sumatriptan     Migraine

 Run 5 completed | rows=14 | latency=34.307s
------------------------------------------------------------


## Question 16

**What drugs or supplements are used to treat rickets?**

In [18]:

question = 'What drugs or supplements are used to treat rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs or supplements are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

         drug_name disease_name
0  Cholecalciferol      Rickets

 Run 1 completed | rows=3 | latency=22.614s
------------------------------------------------------------

 Starting run 2 for query: What drugs or supplements are used to treat rickets?
  Attempt 1/3
Entries retrieved: 4

         drug_name disease_name
0  cholecalciferol      rickets

 Run 2 completed | rows=4 | latency=19.888s
------------------------------------------------------------

 Starting run 3 for query: What drugs or supplements are used to treat rickets?
  Attempt 1/3
Entries retrieved: 7

         drug_name disease_name
0  Cholecalciferol      Rickets

 Run 3 completed | rows=7 | latency=39.934s
------------------------------------------------------------

 Starting run 4 for query: What drugs or supplements are used to treat rickets?
  Attempt 1/3
Entries retrieved: 6

         drug_name disease_name
0  cholecalciferol      rickets

 Run 4 completed | rows=6 | latency=26.665s
------------------------------------------------------------

 Starting run 5 for query: What drugs or supplements are used to treat rickets?
  Attempt 1/3
Entries retrieved: 6

         drug_name disease_name
0  cholecalciferol      rickets

 Run 5 completed | rows=6 | latency=26.278s
------------------------------------------------------------


## Question 17

**Which genes are associated with epilepsy?**

In [19]:

question = 'Which genes are associated with epilepsy?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 17

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 1 completed | rows=17 | latency=32.532s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 19

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 2 completed | rows=19 | latency=33.064s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 16

  disease_name gene_name
0     epilepsy     SCN1A

 Run 3 completed | rows=16 | latency=26.022s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 18

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 4 completed | rows=18 | latency=30.317s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 15

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 5 completed | rows=15 | latency=15.135s
------------------------------------------------------------


## Question 18

**Which diseases are treated with trastuzumab deruxtecan?**

In [20]:

question = 'Which diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                            disease_name
0  trastuzumab deruxtecan  HER2-positive metastatic breast cancer

 Run 1 completed | rows=2 | latency=29.101s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name                 disease_name
0  trastuzumab deruxtecan  HER2-positive breast cancer

 Run 2 completed | rows=3 | latency=20.651s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name   disease_name
0  trastuzumab deruxtecan  Breast cancer

 Run 3 completed | rows=3 | latency=21.463s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                 disease_name
0  trastuzumab deruxtecan  HER2-positive breast cancer

 Run 4 completed | rows=2 | latency=21.251s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  trastuzumab deruxtecan  Breast cancer

 Run 5 completed | rows=2 | latency=20.000s
------------------------------------------------------------


## Question 19

**Which genes are associated with Alzheimer’s disease?**

In [21]:

question = 'Which genes are associated with Alzheimer’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 15

          disease_name gene_name
0  Alzheimer's disease      APOE

 Run 1 completed | rows=15 | latency=27.126s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 11

          disease_name gene_name
0  Alzheimer's disease      APOE

 Run 2 completed | rows=11 | latency=27.466s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 12

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 3 completed | rows=12 | latency=22.972s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 10

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 4 completed | rows=10 | latency=12.883s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 13

          disease_name gene_name
0  Alzheimer's disease      APOE

 Run 5 completed | rows=13 | latency=29.088s
------------------------------------------------------------


## Question 20

**For which diseases is darolutamide used?**

In [22]:

question = 'For which diseases is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  Non-metastatic castration-resistant prostate c...

 Run 1 completed | rows=1 | latency=13.151s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  Non-metastatic castration-resistant prostate c...

 Run 2 completed | rows=1 | latency=13.930s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  Non-metastatic castration-resistant prostate c...

 Run 3 completed | rows=1 | latency=14.190s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  Non-metastatic castration-resistant prostate c...

 Run 4 completed | rows=1 | latency=17.759s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  Non-metastatic castration-resistant prostate c...

 Run 5 completed | rows=1 | latency=11.869s
------------------------------------------------------------


## Question 21

**Which genes are associated with renal cell carcinoma?**

In [23]:

question = 'Which genes are associated with renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 7

           disease_name gene_name
0  Renal cell carcinoma       VHL

 Run 1 completed | rows=7 | latency=22.962s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 10

           disease_name gene_name
0  Renal cell carcinoma       VHL

 Run 2 completed | rows=10 | latency=29.079s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 11

           disease_name gene_name
0  Renal cell carcinoma       VHL

 Run 3 completed | rows=11 | latency=24.918s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 9

           disease_name gene_name
0  Renal cell carcinoma       VHL

 Run 4 completed | rows=9 | latency=20.780s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 4

           disease_name gene_name
0  Renal cell carcinoma       VHL

 Run 5 completed | rows=4 | latency=17.531s
------------------------------------------------------------


## Question 22

**Which diseases are associated with the KRAS gene?**

In [24]:

question = 'Which diseases are associated with the KRAS gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 5

                       disease_name gene_name
0  Pancreatic ductal adenocarcinoma      KRAS

 Run 1 completed | rows=5 | latency=25.913s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 5

      disease_name gene_name
0  Noonan syndrome      KRAS

 Run 2 completed | rows=5 | latency=20.698s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 6

      disease_name gene_name
0  Noonan syndrome      KRAS

 Run 3 completed | rows=6 | latency=23.024s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 5

                       disease_name gene_name
0  Pancreatic ductal adenocarcinoma      KRAS

 Run 4 completed | rows=5 | latency=24.519s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 6

                       disease_name gene_name
0  Pancreatic ductal adenocarcinoma      KRAS

 Run 5 completed | rows=6 | latency=22.900s
------------------------------------------------------------


## Question 23

**Which pathways are associated with the APP gene?**

In [25]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 14.002s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 13.120s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 1

  gene_name                 pathway_name
0       APP  Alzheimer's disease pathway

 Run 1 completed | rows=1 | latency=26.953s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 26.999s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name       pathway_name
0       APP  Alzheimer disease

 Run 2 completed | rows=1 | latency=20.370s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name         pathway_name
0       APP  Alzheimer's disease

 Run 3 completed | rows=1 | latency=21.384s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

                pathway_name gene_name
0  Alzheimer disease pathway       APP

 Run 4 completed | rows=1 | latency=33.838s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name               pathway_name
0       APP  Alzheimer disease pathway

 Run 5 completed | rows=1 | latency=28.830s
------------------------------------------------------------


## Question 24

**Which genes are associated with schizophrenia?**

In [26]:

question = 'Which genes are associated with schizophrenia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 8

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 1 completed | rows=8 | latency=21.840s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 13

    disease_name gene_name
0  Schizophrenia      BDNF

 Run 2 completed | rows=13 | latency=31.724s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 7

    disease_name gene_name
0  schizophrenia      DRD2

 Run 3 completed | rows=7 | latency=26.503s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 13

    disease_name gene_name
0  Schizophrenia     DISC1

 Run 4 completed | rows=13 | latency=29.202s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 8

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 5 completed | rows=8 | latency=26.066s
------------------------------------------------------------


## Question 25

**Which diseases are treated with valdecoxib?**

In [27]:

question = 'Which diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 1

    drug_name    disease_name
0  valdecoxib  Osteoarthritis

 Run 1 completed | rows=1 | latency=21.367s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  Osteoarthritis

 Run 2 completed | rows=2 | latency=24.119s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 1

    drug_name        disease_name
0  valdecoxib  postoperative pain

 Run 3 completed | rows=1 | latency=26.299s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  Osteoarthritis

 Run 4 completed | rows=2 | latency=20.346s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name]
Index: []

 Attempt 1 failed after 16.349s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  osteoarthritis

 Run 5 completed | rows=2 | latency=22.043s
------------------------------------------------------------


## Question 26

**What are the known targets of vandetanib?**

In [28]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       KDR

 Run 1 completed | rows=4 | latency=18.649s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       KDR

 Run 2 completed | rows=4 | latency=18.238s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       KDR

 Run 3 completed | rows=4 | latency=16.530s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib      EGFR

 Run 4 completed | rows=3 | latency=19.531s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       KDR

 Run 5 completed | rows=4 | latency=12.301s
------------------------------------------------------------


## Question 27

**Which pathways are associated with the CFTR gene?**

In [29]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 1 completed | rows=1 | latency=29.912s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 23.370s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 2 completed | rows=1 | latency=21.935s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 20.637s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 3 completed | rows=1 | latency=35.847s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name            pathway_name
0      CFTR  Chloride ion transport

 Run 4 completed | rows=1 | latency=32.154s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 16.541s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 21.016s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 1

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 5 completed | rows=1 | latency=18.426s
------------------------------------------------------------


## Question 28

**Which drugs are used to treat tuberculosis?**

In [30]:

question = 'Which drugs are used to treat tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name
0  isoniazid  Tuberculosis

 Run 1 completed | rows=5 | latency=17.762s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

    drug_name  disease_name
0  rifampicin  tuberculosis

 Run 2 completed | rows=4 | latency=13.622s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 3 completed | rows=4 | latency=20.141s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name
0  isoniazid  Tuberculosis

 Run 4 completed | rows=5 | latency=16.137s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 20

   drug_name  disease_name
0  isoniazid  Tuberculosis

 Run 5 completed | rows=20 | latency=31.409s
------------------------------------------------------------


## Question 29

**Which drugs are used to treat pancreatic adenocarcinoma?**

In [31]:

question = 'Which drugs are used to treat pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 7

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 1 completed | rows=7 | latency=39.659s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 9

     drug_name               disease_name
0  gemcitabine  Pancreatic adenocarcinoma

 Run 2 completed | rows=9 | latency=38.009s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 8

     drug_name               disease_name
0  Gemcitabine  Pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 3 completed | rows=8 | latency=34.568s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 3/3
Entries retrieved: 7

     drug_name               disease_name
0  Gemcitabine  Pancreatic adenocarcinoma

------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 7

     drug_name               disease_name
0  gemcitabine  Pancreatic adenocarcinoma

  Attempt 3/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 5 completed | rows=6 | latency=27.682s
------------------------------------------------------------


## Question 30

**Which drugs are used to treat chronic myeloid leukemia?**

In [32]:

question = 'Which drugs are used to treat chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  Chronic myeloid leukemia

 Run 1 completed | rows=6 | latency=24.434s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  Chronic myeloid leukemia

 Run 2 completed | rows=6 | latency=25.498s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  Chronic myeloid leukemia

 Run 3 completed | rows=6 | latency=19.466s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 4 completed | rows=5 | latency=15.644s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 5 completed | rows=5 | latency=17.026s
------------------------------------------------------------


## Question 31

**Which drugs are used to treat Parkinson’s disease?**

In [33]:

question = 'Which drugs are used to treat Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 1 completed | rows=15 | latency=24.743s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

  drug_name         disease_name
0  levodopa  Parkinson's disease

 Run 2 completed | rows=15 | latency=39.305s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 14

  drug_name         disease_name
0  Levodopa  Parkinson's disease

  Attempt 2/3
Entries retrieved: 17

  drug_name         disease_name
0  levodopa  Parkinson's disease

  Attempt 3/3
Entries retrieved: 16

  drug_name         disease_name
0  levodopa  Parkinson's disease

------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 16

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 4 completed | rows=16 | latency=35.341s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 14

  drug_name         disease_name
0  levodopa  Parkinson's disease

 Run 5 completed | rows=14 | latency=25.914s
------------------------------------------------------------


## Question 32

**Which drugs are used to treat inflammatory bowel disease?**

In [34]:

question = 'Which drugs are used to treat inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 17

       drug_name                disease_name
0  sulfasalazine  inflammatory bowel disease

  Attempt 2/3
Entries retrieved: 16

    drug_name                disease_name
0  Mesalamine  Inflammatory bowel disease

 Run 1 completed | rows=16 | latency=38.400s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 12

    drug_name                disease_name
0  infliximab  Inflammatory bowel disease

  Attempt 2/3
Entries retrieved: 19

       drug_name                disease_name
0  sulfasalazine  Inflammatory bowel disease

 Run 2 completed | rows=19 | latency=31.060s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 17

       drug_name                disease_name
0  sulfasalazine  Inflammatory bowel disease

  Attempt 2/3
Entries retrieved: 19

    drug_name                disease_name
0  mesalamine  Inflammatory bowel disease

 Run 3 completed | rows=19 | latency=31.838s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 16

    drug_name                disease_name
0  mesalamine  Inflammatory bowel disease

 Run 4 completed | rows=16 | latency=35.250s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 13

       drug_name                disease_name
0  sulfasalazine  Inflammatory bowel disease

 Run 5 completed | rows=13 | latency=24.914s
------------------------------------------------------------


## Question 33

**Which targets are acted on by imatinib?**

In [35]:

question = 'Which targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 6

  drug_name gene_name
0  imatinib      ABL1

 Run 1 completed | rows=6 | latency=17.661s
------------------------------------------------------------

 Starting run 2 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 5

  drug_name gene_name
0  imatinib      ABL1

 Run 2 completed | rows=5 | latency=14.155s
------------------------------------------------------------

 Starting run 3 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      ABL1

 Run 3 completed | rows=4 | latency=25.186s
------------------------------------------------------------

 Starting run 4 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  Imatinib      ABL1

 Run 4 completed | rows=4 | latency=13.963s
------------------------------------------------------------

 Starting run 5 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 5

  drug_name gene_name
0  imatinib      ABL1

 Run 5 completed | rows=5 | latency=21.033s
------------------------------------------------------------


## Question 34

**Which biological targets does sorafenib interact with?**

In [36]:

question = 'Which biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

        drug_name  gene_name
0  sorafenib RAF1        NaN

 Run 1 completed | rows=8 | latency=20.541s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      BRAF

 Run 2 completed | rows=8 | latency=26.273s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      BRAF

 Run 3 completed | rows=8 | latency=28.930s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      BRAF

 Run 4 completed | rows=8 | latency=17.159s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      BRAF

 Run 5 completed | rows=8 | latency=19.066s
------------------------------------------------------------


## Question 35

**Which biological targets does tofacitinib interact with?**

In [37]:

question = 'Which biological targets does tofacitinib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  tofacitinib      JAK1

 Run 1 completed | rows=3 | latency=14.608s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  tofacitinib      JAK1

 Run 2 completed | rows=3 | latency=13.853s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  tofacitinib      JAK1

 Run 3 completed | rows=2 | latency=20.235s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  tofacitinib      JAK1

 Run 4 completed | rows=2 | latency=12.624s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  tofacitinib      JAK1

 Run 5 completed | rows=3 | latency=9.828s
------------------------------------------------------------


## Question 36

**Which drugs target EGFR?**

In [38]:

question = 'Which drugs target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 11

   drug_name gene_name
0  Gefitinib      EGFR

 Run 1 completed | rows=11 | latency=27.657s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 11

   drug_name gene_name
0  Gefitinib      EGFR

 Run 2 completed | rows=11 | latency=27.860s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  Gefitinib      EGFR

 Run 3 completed | rows=10 | latency=21.962s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 13

   drug_name gene_name
0  gefitinib      EGFR

  Attempt 2/3
Entries retrieved: 12

   drug_name gene_name
0  cetuximab      EGFR

 Run 4 completed | rows=12 | latency=29.789s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 12

   drug_name gene_name
0  Gefitinib      EGFR

 Run 5 completed | rows=12 | latency=30.987s
------------------------------------------------------------


## Question 37

**Which diseases are associated with TP53?**

In [39]:

question = 'Which diseases are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 1 completed | rows=1 | latency=20.540s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 13

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 2 completed | rows=13 | latency=35.343s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 11

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 3 completed | rows=11 | latency=38.678s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 11

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 4 completed | rows=11 | latency=30.750s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 5 completed | rows=6 | latency=36.130s
------------------------------------------------------------


## Question 38

**Which diseases are associated with FGFR2?**

In [40]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

       disease_name gene_name
0  Crouzon syndrome     FGFR2

  Attempt 2/3
Entries retrieved: 4

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 1 completed | rows=4 | latency=32.738s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 7

     disease_name gene_name
0  Apert syndrome     FGFR2

  Attempt 2/3
Entries retrieved: 7

       disease_name gene_name
0  Crouzon syndrome     FGFR2

 Run 2 completed | rows=7 | latency=32.808s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 3 completed | rows=9 | latency=36.943s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 7

         disease_name gene_name
0  Cholangiocarcinoma     FGFR2

 Run 4 completed | rows=7 | latency=29.106s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 5 completed | rows=9 | latency=27.061s
------------------------------------------------------------


## Question 39

**Which diseases are associated with HTT?**

In [41]:

question = 'Which diseases are associated with HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 1 completed | rows=1 | latency=17.940s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 2 completed | rows=1 | latency=15.871s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 3 completed | rows=1 | latency=16.141s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 4 completed | rows=1 | latency=12.998s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 5 completed | rows=1 | latency=13.438s
------------------------------------------------------------


## Question 40

**Which genes are associated with breast cancer?**

In [42]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 7

    disease_name gene_name
0  breast cancer     BRCA1

 Run 1 completed | rows=7 | latency=29.030s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 12

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 2 completed | rows=12 | latency=28.262s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 15

    disease_name gene_name
0  breast cancer     BRCA1

 Run 3 completed | rows=15 | latency=22.824s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 16

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 4 completed | rows=16 | latency=29.559s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 18

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 5 completed | rows=18 | latency=26.581s
------------------------------------------------------------


## Question 41

**Which genes are associated with colorectal cancer?**

In [43]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 13

        disease_name gene_name
0  Colorectal cancer       APC

 Run 1 completed | rows=13 | latency=21.182s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  Colorectal cancer       APC

 Run 2 completed | rows=14 | latency=23.850s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 18

        disease_name gene_name
0  Colorectal cancer       APC

 Run 3 completed | rows=18 | latency=25.655s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 11

        disease_name gene_name
0  Colorectal cancer       APC

 Run 4 completed | rows=11 | latency=28.205s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  Colorectal cancer       APC

 Run 5 completed | rows=14 | latency=23.547s
------------------------------------------------------------


## Question 42

**Which genes are associated with cystic fibrosis?**

In [44]:

question = 'Which genes are associated with cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      CFTR

 Run 1 completed | rows=1 | latency=9.521s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 2 completed | rows=1 | latency=15.884s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 3 completed | rows=1 | latency=11.658s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 4 completed | rows=1 | latency=9.820s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 5 completed | rows=1 | latency=11.421s
------------------------------------------------------------


## Question 43

**Which drugs are used to treat TNBC?**

In [45]:

question = 'Which drugs are used to treat TNBC?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 13

    drug_name                   disease_name
0  paclitaxel  Triple-negative breast cancer

 Run 1 completed | rows=13 | latency=34.270s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 8

    drug_name                   disease_name
0  paclitaxel  Triple-negative breast cancer

 Run 2 completed | rows=8 | latency=39.554s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 9

    drug_name                   disease_name
0  paclitaxel  Triple-negative breast cancer

  Attempt 2/3
Entries retrieved: 12

     drug_name                   disease_name
0  doxorubicin  Triple-negative breast cancer

 Run 3 completed | rows=12 | latency=35.460s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 9

    drug_name                   disease_name
0  paclitaxel  Triple-negative breast cancer

  Attempt 2/3
Entries retrieved: 11

    drug_name disease_name
0  paclitaxel         TNBC

 Run 4 completed | rows=11 | latency=31.974s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 12

     drug_name                   disease_name
0  doxorubicin  Triple-negative breast cancer

  Attempt 2/3
Entries retrieved: 9

     drug_name                   disease_name
0  doxorubicin  Triple-negative breast cancer

  Attempt 3/3
Entries retrieved: 11

     drug_name                   disease_name
0  doxorubicin  Triple-negative breast cancer

------------------------------------------------------------


## Question 44

**Which diseases are treated with metformin?**

In [46]:

question = 'Which diseases are treated with metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  Type 2 diabetes mellitus

 Run 1 completed | rows=2 | latency=12.537s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  Type 2 diabetes mellitus

 Run 2 completed | rows=2 | latency=18.425s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  Type 2 diabetes mellitus

 Run 3 completed | rows=2 | latency=24.350s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  Type 2 diabetes mellitus

 Run 4 completed | rows=2 | latency=18.494s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  Type 2 diabetes mellitus

 Run 5 completed | rows=2 | latency=18.614s
------------------------------------------------------------


## Question 45

**Which diseases are treated with adalimumab?**

In [47]:

question = 'Which diseases are treated with adalimumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 1 completed | rows=9 | latency=27.864s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 2 completed | rows=9 | latency=32.203s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 3 completed | rows=9 | latency=30.688s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 4 completed | rows=9 | latency=22.763s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 5 completed | rows=9 | latency=28.166s
------------------------------------------------------------


## Question 46

**For which diseases is pembrolizumab used?**

In [48]:

question = 'For which diseases is pembrolizumab used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 7

       drug_name disease_name
0  pembrolizumab     Melanoma

 Run 1 completed | rows=7 | latency=37.780s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 10

       drug_name disease_name
0  pembrolizumab     Melanoma

 Run 2 completed | rows=10 | latency=38.754s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name
0  pembrolizumab     Melanoma

  Attempt 2/3
Entries retrieved: 8

       drug_name disease_name
0  pembrolizumab     Melanoma

 Run 3 completed | rows=8 | latency=27.064s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 8

       drug_name disease_name
0  pembrolizumab     melanoma

  Attempt 2/3
Entries retrieved: 12

       drug_name disease_name
0  pembrolizumab     Melanoma

  Attempt 3/3
Entries retrieved: 7

       drug_name disease_name
0  pembrolizumab     Melanoma

 Run 4 completed | rows=7 | latency=25.181s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 7

       drug_name disease_name
0  pembrolizumab     melanoma

  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name]
Index: []

 Attempt 2 failed after 36.614s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 11

       drug_name disease_name
0  pembrolizumab     Melanoma

------------------------------------------------------------


## Question 47

**Which diseases are treated with sorafenib?**

In [49]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  hepatocellular carcinoma

 Run 1 completed | rows=3 | latency=21.300s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  Hepatocellular carcinoma

 Run 2 completed | rows=3 | latency=22.697s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  Hepatocellular carcinoma

 Run 3 completed | rows=3 | latency=16.267s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  hepatocellular carcinoma

 Run 4 completed | rows=3 | latency=16.645s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  Hepatocellular carcinoma

 Run 5 completed | rows=3 | latency=12.582s
------------------------------------------------------------


## Question 48

**Which diseases are treated with nivolumab?**

In [50]:

question = 'Which diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     Melanoma

 Run 1 completed | rows=7 | latency=32.002s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     Melanoma

  Attempt 2/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     Melanoma

 Run 2 completed | rows=6 | latency=26.242s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     Melanoma

 Run 3 completed | rows=7 | latency=30.303s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     Melanoma

  Attempt 2/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 4 completed | rows=7 | latency=28.680s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     Melanoma

  Attempt 2/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 5 completed | rows=7 | latency=29.815s
------------------------------------------------------------


## Question 49

**Which genes are associated with multiple sclerosis?**

In [51]:

question = 'Which genes are associated with multiple sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 1 completed | rows=4 | latency=17.185s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 7

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 2 completed | rows=7 | latency=29.021s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 6

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 3 completed | rows=6 | latency=28.926s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 4 completed | rows=4 | latency=24.136s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 3

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 5 completed | rows=3 | latency=19.698s
------------------------------------------------------------


## Question 50

**Which genes are associated with rheumatoid arthritis?**

In [52]:

question = 'Which genes are associated with rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 7

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 1 completed | rows=7 | latency=22.891s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 2 completed | rows=10 | latency=35.762s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 3 completed | rows=8 | latency=34.101s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 9

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 4 completed | rows=9 | latency=34.545s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 9

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 5 completed | rows=9 | latency=24.726s
------------------------------------------------------------


## Question 51

**What are the known targets of abatacept?**

In [53]:

question = 'What are the known targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 1 completed | rows=2 | latency=11.087s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 2 completed | rows=2 | latency=12.155s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 3 completed | rows=2 | latency=12.733s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 4 completed | rows=2 | latency=8.996s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 5 completed | rows=2 | latency=10.631s
------------------------------------------------------------


## Question 52

**Which genes are associated with lung cancer?**

In [54]:

question = 'Which genes are associated with lung cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0  Lung cancer       ALK

 Run 1 completed | rows=9 | latency=20.339s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 11

  gene_name disease_name
0      EGFR  Lung cancer

 Run 2 completed | rows=11 | latency=20.075s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 11

  disease_name gene_name
0  Lung cancer      EGFR

 Run 3 completed | rows=11 | latency=29.031s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 13

  disease_name gene_name
0  Lung cancer      TP53

 Run 4 completed | rows=13 | latency=26.777s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 15

  disease_name gene_name
0  Lung cancer      EGFR

 Run 5 completed | rows=15 | latency=30.764s
------------------------------------------------------------


## Question 53

**What are the known targets of ponatinib?**

In [55]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 14

   drug_name gene_name
0  ponatinib      ABL1

 Run 1 completed | rows=14 | latency=25.558s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 12

   drug_name gene_name
0  ponatinib      ABL1

 Run 2 completed | rows=12 | latency=21.728s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 15

   drug_name gene_name
0  ponatinib      ABL1

 Run 3 completed | rows=15 | latency=28.889s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  ponatinib      ABL1

 Run 4 completed | rows=10 | latency=25.867s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 13

   drug_name gene_name
0  ponatinib      ABL1

 Run 5 completed | rows=13 | latency=28.635s
------------------------------------------------------------


## Question 54

**Which drugs are used to treat systemic lupus erythematosus?**

In [56]:

question = 'Which drugs are used to treat systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 1 completed | rows=7 | latency=29.615s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

            drug_name                  disease_name
0  hydroxychloroquine  Systemic lupus erythematosus

 Run 2 completed | rows=8 | latency=26.466s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 14

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 3 completed | rows=14 | latency=34.357s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 4 completed | rows=7 | latency=30.608s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

            drug_name                  disease_name
0  hydroxychloroquine  Systemic lupus erythematosus

 Run 5 completed | rows=8 | latency=27.799s
------------------------------------------------------------


## Question 55

**Which genes are associated with autism spectrum disorder?**

In [57]:

question = 'Which genes are associated with autism spectrum disorder?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 14

               disease_name gene_name
0  Autism spectrum disorder      CHD8

 Run 1 completed | rows=14 | latency=30.052s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 17

               disease_name gene_name
0  autism spectrum disorder      CHD8

 Run 2 completed | rows=17 | latency=34.255s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 19

               disease_name gene_name
0  Autism spectrum disorder      CHD8

 Run 3 completed | rows=19 | latency=31.591s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 18

               disease_name gene_name
0  Autism spectrum disorder      CHD8

 Run 4 completed | rows=18 | latency=39.227s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 22

               disease_name gene_name
0  Autism spectrum disorder      CHD8

  Attempt 2/3
Entries retrieved: 18

               disease_name gene_name
0  Autism spectrum disorder      CHD8

 Run 5 completed | rows=18 | latency=25.418s
------------------------------------------------------------


## Question 56

**Which diseases are associated with the ROS1 gene?**

In [58]:

question = 'Which diseases are associated with the ROS1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 3

                    disease_name gene_name
0  Non-small cell lung carcinoma      ROS1

 Run 1 completed | rows=3 | latency=26.794s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

  Attempt 2/3
Entries retrieved: 2

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 2 completed | rows=2 | latency=25.410s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

  Attempt 2/3
Entries retrieved: 3

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

  Attempt 3/3
Entries retrieved: 3

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 3 completed | rows=3 | latency=30.162s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

  Attempt 2/3
Entries retrieved: 2

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 4 completed | rows=2 | latency=34.332s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 5 completed | rows=2 | latency=35.586s
------------------------------------------------------------


## Question 57

**Which diseases are associated with the ALK gene?**

In [59]:

question = 'Which diseases are associated with the ALK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 1 completed | rows=4 | latency=33.558s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 2 completed | rows=4 | latency=37.040s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 3 completed | rows=4 | latency=31.285s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 5

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 4 completed | rows=5 | latency=25.582s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer       ALK

 Run 5 completed | rows=4 | latency=20.508s
------------------------------------------------------------


## Question 58

**Which diseases are associated with the EGFR gene?**

In [60]:

question = 'Which diseases are associated with the EGFR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 6

                 disease_name gene_name
0  Non-small cell lung cancer      EGFR

 Run 1 completed | rows=6 | latency=33.517s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma      EGFR

 Run 2 completed | rows=4 | latency=25.738s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer      EGFR

 Run 3 completed | rows=4 | latency=32.352s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer      EGFR

 Run 4 completed | rows=4 | latency=37.192s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

   disease_name gene_name
0  Glioblastoma      EGFR

 Run 5 completed | rows=5 | latency=36.215s
------------------------------------------------------------


## Question 59

**Which genes are associated with psoriasis?**

In [61]:

question = 'Which genes are associated with psoriasis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0    Psoriasis     HLA-C

  Attempt 2/3
Entries retrieved: 9

  disease_name gene_name
0    Psoriasis     HLA-C

 Run 1 completed | rows=9 | latency=32.451s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 6

  disease_name gene_name
0    Psoriasis     HLA-C

 Run 2 completed | rows=6 | latency=33.703s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 8

  disease_name gene_name
0    Psoriasis     HLA-C

 Run 3 completed | rows=8 | latency=38.063s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 13

  disease_name gene_name
0    psoriasis     HLA-C

 Run 4 completed | rows=13 | latency=30.757s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0    psoriasis     HLA-C

 Run 5 completed | rows=9 | latency=24.605s
------------------------------------------------------------


## Question 60

**Which genes are associated with ulcerative colitis?**

In [62]:

question = 'Which genes are associated with ulcerative colitis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [disease_name, gene_name]
Index: []

 Attempt 1 failed after 18.047s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 8

         disease_name gene_name
0  Ulcerative colitis     IL23R

  Attempt 3/3
Entries retrieved: 9

         disease_name gene_name
0  Ulcerative colitis     IL23R

------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 3

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 2 completed | rows=3 | latency=35.011s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 10

         disease_name gene_name
0  Ulcerative colitis     IL23R

  Attempt 2/3
Entries retrieved: 1

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 3 completed | rows=1 | latency=35.250s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 2

         disease_name gene_name
0  ulcerative colitis     IL23R

 Run 4 completed | rows=2 | latency=26.347s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 15

         disease_name gene_name
0  Ulcerative colitis     IL23R

  Attempt 2/3
Entries retrieved: 10

         disease_name gene_name
0  Ulcerative colitis     IL23R

  Attempt 3/3
Entries retrieved: 5

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 5 completed | rows=5 | latency=39.819s
------------------------------------------------------------


## Question 61

**Which human genes are associated with tuberculosis?**

In [63]:

question = 'Which human genes are associated with tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which human genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 9

   disease_name gene_name
0  Tuberculosis   SLC11A1

 Run 1 completed | rows=9 | latency=28.719s
------------------------------------------------------------

 Starting run 2 for query: Which human genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 9

   disease_name gene_name
0  Tuberculosis   SLC11A1

 Run 2 completed | rows=9 | latency=32.224s
------------------------------------------------------------

 Starting run 3 for query: Which human genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [disease_name, gene_name]
Index: []

 Attempt 1 failed after 20.330s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 8

   disease_name gene_name
0  Tuberculosis      IFNG

 Run 3 completed | rows=8 | latency=34.471s
------------------------------------------------------------

 Starting run 4 for query: Which human genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 7

   disease_name gene_name
0  Tuberculosis   SLC11A1

 Run 4 completed | rows=7 | latency=36.040s
------------------------------------------------------------

 Starting run 5 for query: Which human genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 8

   disease_name gene_name
0  Tuberculosis   SLC11A1

 Run 5 completed | rows=8 | latency=37.514s
------------------------------------------------------------


## Question 62

**Which genes are associated with hepatitis C?**

In [64]:

question = 'Which genes are associated with hepatitis C?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Hepatitis C     IFNL3

 Run 1 completed | rows=2 | latency=24.428s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Hepatitis C     IFNL3

 Run 2 completed | rows=2 | latency=21.601s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Hepatitis C     IFNL3

 Run 3 completed | rows=2 | latency=30.108s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Hepatitis C     IFNL3

 Run 4 completed | rows=2 | latency=25.345s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Hepatitis C     IFNL3

 Run 5 completed | rows=2 | latency=29.538s
------------------------------------------------------------


## Question 63

**Which genes are associated with Hodgkin lymphoma?**

In [65]:

question = 'Which genes are associated with Hodgkin lymphoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 6

       disease_name gene_name
0  Hodgkin lymphoma      JAK2

 Run 1 completed | rows=6 | latency=30.807s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 7

       disease_name gene_name
0  Hodgkin lymphoma       REL

 Run 2 completed | rows=7 | latency=37.807s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 9

       disease_name gene_name
0  Hodgkin lymphoma       REL

 Run 3 completed | rows=9 | latency=35.799s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 10

       disease_name gene_name
0  Hodgkin lymphoma      JAK2

 Run 4 completed | rows=10 | latency=38.934s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 7

       disease_name gene_name
0  Hodgkin lymphoma       REL

  Attempt 2/3
Entries retrieved: 6

       disease_name gene_name
0  Hodgkin lymphoma       REL

 Run 5 completed | rows=6 | latency=34.739s
------------------------------------------------------------


## Question 64

**Which pathways are associated with TP53?**

In [66]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 1 completed | rows=3 | latency=32.741s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [pathway_name, gene_name]
Index: []

 Attempt 1 failed after 32.725s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 4

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 2 completed | rows=4 | latency=36.079s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      TP53  p53 signaling pathway

  Attempt 2/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 3 completed | rows=3 | latency=37.534s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 22.961s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 4 completed | rows=3 | latency=35.713s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 5 completed | rows=4 | latency=33.030s
------------------------------------------------------------


## Question 65

**Which drugs target ERBB2?**

In [67]:

question = 'Which drugs target ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 9

     drug_name gene_name
0  trastuzumab     ERBB2

 Run 1 completed | rows=9 | latency=34.418s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 9

     drug_name gene_name
0  trastuzumab     ERBB2

 Run 2 completed | rows=9 | latency=36.722s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  trastuzumab     ERBB2

  Attempt 2/3
Entries retrieved: 10

     drug_name gene_name
0  trastuzumab     ERBB2

 Run 3 completed | rows=10 | latency=39.695s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  trastuzumab     ERBB2

  Attempt 2/3
Entries retrieved: 10

     drug_name gene_name
0  trastuzumab     ERBB2

  Attempt 3/3
Entries retrieved: 9

     drug_name gene_name
0  trastuzumab     ERBB2

------------------------------------------------------------

 Starting run 5 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 13

     drug_name gene_name
0  trastuzumab     ERBB2

 Run 5 completed | rows=13 | latency=29.057s
------------------------------------------------------------


## Question 66

**Which pathways are associated with the ADRB1 gene?**

In [68]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  GPCR signaling pathway

 Run 1 completed | rows=3 | latency=32.608s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 2 completed | rows=2 | latency=23.694s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                       pathway_name
0     ADRB1  Beta-adrenergic signaling pathway

 Run 3 completed | rows=4 | latency=34.666s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 4

                        pathway_name gene_name
0  Beta-adrenergic signaling pathway     ADRB1

 Run 4 completed | rows=4 | latency=33.011s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

                             pathway_name gene_name
0  Adrenergic signaling in cardiomyocytes     ADRB1

 Run 5 completed | rows=3 | latency=29.396s
------------------------------------------------------------


## Question 67

**Which pathways are associated with the DRD2 gene?**

In [69]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

           pathway_name gene_name
0  Dopaminergic synapse      DRD2

 Run 1 completed | rows=2 | latency=31.236s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0      DRD2  Dopaminergic synapse

 Run 2 completed | rows=2 | latency=25.501s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0      DRD2  Dopaminergic synapse

 Run 3 completed | rows=2 | latency=24.689s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0      DRD2  Dopaminergic synapse

 Run 4 completed | rows=2 | latency=30.377s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name, gene_name, pathway_name]
Index: []

 Attempt 1 failed after 22.492s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 2

  gene_name          pathway_name
0      DRD2  Dopaminergic synapse

 Run 5 completed | rows=2 | latency=17.223s
------------------------------------------------------------


## Question 68

**Which pathways are associated with the HTR2A gene?**

In [70]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name          pathway_name
0     HTR2A  Serotonergic synapse

  Attempt 2/3
Entries retrieved: 2

                           pathway_name gene_name
0  Serotonin receptor signaling pathway     HTR2A

 Run 1 completed | rows=2 | latency=32.210s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 2 completed | rows=2 | latency=35.132s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

                       pathway_name gene_name
0  Signaling by Serotonin Receptors     HTR2A

  Attempt 2/3
Entries retrieved: 2

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [pathway_name, gene_name]
Index: []

 Attempt 3 failed after 38.332s: Returned DataFrame is empty
 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 4 completed | rows=4 | latency=34.145s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0     HTR2A  Serotonergic synapse

 Run 5 completed | rows=2 | latency=38.822s
------------------------------------------------------------


## Question 69

**Which drugs target CD19?**

In [71]:

question = 'Which drugs target CD19?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 8

      drug_name gene_name
0  blinatumomab      CD19

 Run 1 completed | rows=8 | latency=36.260s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

          drug_name gene_name
0  tisagenlecleucel      CD19

 Run 2 completed | rows=6 | latency=26.568s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 8

          drug_name gene_name
0  tisagenlecleucel      CD19

 Run 3 completed | rows=8 | latency=36.496s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

      drug_name gene_name
0  blinatumomab      CD19

 Run 4 completed | rows=6 | latency=26.679s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name
0  blinatumomab      CD19

  Attempt 2/3
Entries retrieved: 7

          drug_name gene_name
0  tisagenlecleucel      CD19

 Run 5 completed | rows=7 | latency=29.948s
------------------------------------------------------------


## Question 70

**Which drugs target CTLA4?**

In [72]:

question = 'Which drugs target CTLA4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time
            
            if latency>40:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     CTLA4

 Run 1 completed | rows=2 | latency=15.403s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     CTLA4

 Run 2 completed | rows=2 | latency=14.028s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     CTLA4

 Run 3 completed | rows=2 | latency=12.238s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     CTLA4

 Run 4 completed | rows=2 | latency=16.653s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     CTLA4

 Run 5 completed | rows=2 | latency=17.893s
------------------------------------------------------------

In [73]:
import json
import pandas as pd

import pickle
with open("Biochatter_same_question_response.pkl", "wb") as f:
    pickle.dump(dct_result, f)

def make_json_safe(obj):
    if isinstance(obj, pd.DataFrame):
        return {
            "__type__": "dataframe",
            "columns": obj.columns.tolist(),
            "rows": obj.to_dict(orient="records")
        }
    elif isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    else:
        return obj


json_safe_result = make_json_safe(dct_result)

with open("Biochatter_same_question_response.json", "w", encoding="utf-8") as f:
    json.dump(
        json_safe_result,
        f,
        indent=2,
        ensure_ascii=False
    )