In [1]:
import sys
sys.path.append("../")

##### import library

In [2]:
from typing import List, Optional
import requests
import pandas as pd
import mygene
import utility
import importlib
importlib.reload(utility)
from utility import resolve_ensembl_ids_with_fallback, get_chembl_ids_fast,  get_disease_ids_fast, validate_id_dataframe
import pickle

In [3]:
dct_result = dict()

##### Read pickle

In [4]:
with open("HCDT_same_question_response_final.pkl", "rb") as f:
    HCDT_same_question_response = pickle.load(f)

In [5]:
for model in ['llama-3.3-70b-versatile', 'gpt-5-nano', 'grok-4-1-fast-non-reasoning-latest', "gemini-2.5-flash-lite", "OpenTarget", "BioChatter", "ctd", "ttd", "hcdt"]:

    
    # if model=="llama-3.3-70b-versatile":
    #     dct_result[model] = Llama_same_question_response[model]

    # if model=="gpt-5-nano":
    #     dct_result[model] = OpenAI_same_question_response[model]

    # if model=='grok-4-1-fast-non-reasoning-latest':
    #     dct_result[model] = Grok_same_question_response[model]

    # if model=="gemini-2.5-flash-lite":
    #     dct_result[model] = Gemini_same_question_response[model]

    # if model=="OpenTarget":
    #     dct_result[model] = Opentarget_same_question_response[model]

    # if model=="BioChatter":
    #     dct_result[model] = Biochatter_same_question_response[model]

    # if model=="ctd":
    #     dct_result[model] = CTD_same_question_response[model]

    if model=="hcdt":
        dct_result[model] = HCDT_same_question_response[model]

##### Verify if only valid columns are present

In [6]:
allowed = {"gene_name", "drug_name", "disease_name", "pathway_name"}

missing_df = []
not_dataframe = []
empty_df = []
bad_columns = []

total_payloads = 0

for model, queries in dct_result.items():
    if not isinstance(queries, dict):
        continue

    for question, runs in queries.items():
        if not isinstance(runs, dict):
            continue

        for run_id, payload in runs.items():
            total_payloads += 1

            if not isinstance(payload, dict) or "dataframe" not in payload:
                missing_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "payload_type": type(payload).__name__
                })
                continue

            df = payload.get("dataframe")

            if not isinstance(df, pd.DataFrame):
                not_dataframe.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "df_type": type(df).__name__
                })
                continue

            if df.empty:
                empty_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns)
                })

            cols = {str(c) for c in df.columns}
            extra = sorted(cols - allowed)

            if extra:
                bad_columns.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns),
                    "extra_columns": extra
                })

print(f"Total payloads checked: {total_payloads}")
print(f"Missing dataframe key: {len(missing_df)}")
print(f"Dataframe is not pd.DataFrame: {len(not_dataframe)}")
print(f"Empty dataframes: {len(empty_df)}")
print(f"Dataframes with disallowed columns: {len(bad_columns)}")

bad_columns_df = pd.DataFrame(bad_columns)
missing_df_df = pd.DataFrame(missing_df)
not_dataframe_df = pd.DataFrame(not_dataframe)
empty_df_df = pd.DataFrame(empty_df)

display(bad_columns_df)
display(missing_df_df)
display(not_dataframe_df)
display(empty_df_df)

Total payloads checked: 295
Missing dataframe key: 0
Dataframe is not pd.DataFrame: 0
Empty dataframes: 0
Dataframes with disallowed columns: 0

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [7]:
dct_jaccard = dict()

question_entities = {
    "gene_name": set(),
    "drug_name": set(),
    "disease_name": set(),
}

allowed_cols = {"gene_name", "drug_name", "disease_name"}

for model, queries in dct_result.items():
    dct_jaccard[model] = {}
    print(f"\nWorking for model: {model}")

    for question, runs in queries.items():

        for run_id, payload in runs.items():
            df = payload.get("dataframe")

            # ---- validation ----
            if not isinstance(df, pd.DataFrame) or df.empty:
                continue

            # ---- skip pathway outputs ----
            if "pathway_name" in df.columns:
                continue

            # ---- column sanity ----
            if not set(df.columns).issubset(allowed_cols):
                continue

            # ---- collect entities globally ----
            for col in allowed_cols:
                if col in df.columns:
                    values = (
                        df[col]
                        .dropna()
                        .astype(str)
                        .str.strip()
                        .tolist()
                    )
                    question_entities[col].update(values)

# ---- finalize (sets → sorted lists) ----
for k in question_entities:
    question_entities[k] = sorted(question_entities[k])

Working for model: hcdt

##### Associate id with all gene entry

In [8]:
# Resolve unique gene symbols to IDs (MyGene -> OpenTargets fallback).
df_gene = resolve_ensembl_ids_with_fallback(
    list(question_entities["gene_name"]),
    use_opentargets_fallback=True,
)
df_gene = df_gene.drop_duplicates(subset=["gene_name", "gene_id"]).reset_index(drop=True)
df_gene

2026-02-27 18:16:33,911 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:16:33,912 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:16:33,912 [INFO] querying 1-1000 ...
2026-02-27 18:16:36,375 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 18:16:37,382 [INFO] querying 1001-2000 ...
2026-02-27 18:16:38,722 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 18:16:39,728 [INFO] querying 2001-2987 ...
2026-02-27 18:16:41,049 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 18:16:42,054 [INFO] Finished.
2026-02-27 18:16:42,197 [WARNING] 6 input query terms found dup hits:	[('CAST', 2), ('GLUD1P3', 2), ('GNRHR2', 2), ('ORAI1', 2), ('TEC', 2), ('ZNF542P', 2)]

     gene_name          gene_id  source
0         A1BG  ENSG00000121410  mygene
1          A2M  ENSG00000175899  mygene
2        AADAC  ENSG00000114771  mygene
3        AADAT  ENSG00000109576  mygene
4         AAK1  ENSG00000115977  mygene
...        ...              ...     ...
2982  ZMPSTE24  ENSG00000084073  mygene
2983    ZNF423  ENSG00000102935  mygene
2984   ZNF542P  ENSG00000290720  mygene
2985    ZNF613  ENSG00000176024  mygene
2986   ZSCAN25  ENSG00000197037  mygene

[2987 rows x 3 columns]

In [9]:
df_gene[df_gene.isna().any(axis=1)]

Empty DataFrame
Columns: [gene_name, gene_id, source]
Index: []

##### Associate id with all drug entry

In [10]:
# Resolve unique drug surface forms to IDs.
# This keeps original raw names as rows and writes mapped ID + source.
df_drug = await get_chembl_ids_fast(list(question_entities["drug_name"]))
df_drug = df_drug.drop_duplicates(subset=["drug_name", "drug_id"]).reset_index(drop=True)
df_drug

2026-02-27 18:19:02,222 [INFO] [LLM] Total 10296 names split into 167 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:19:02,226 [INFO] [LLM] Batch size: 43
2026-02-27 18:19:02,259 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,264 [INFO] [LLM] Batch size: 56
2026-02-27 18:19:02,267 [INFO] [LLM] Batch size: 46
2026-02-27 18:19:02,268 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,268 [INFO] [LLM] Batch size: 56
2026-02-27 18:19:02,269 [INFO] [LLM] Batch size: 52
2026-02-27 18:19:02,269 [INFO] [LLM] Batch size: 40
2026-02-27 18:19:02,270 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,270 [INFO] [LLM] Batch size: 73
2026-02-27 18:19:02,271 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,271 [INFO] [LLM] Batch size: 46
2026-02-27 18:19:02,271 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,272 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,272 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,273 [INFO] [LLM] Batch size: 55
2026-02-27 18:19:02,274 [INFO] [LLM] Batch size: 54
2026-02-27 18:19:02,274 [INFO] [LLM] Batch size: 57
2026-02-27 18:19:02,274 [INFO] [LLM] Batch size: 51
2026-02-27 18:19:02,275 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,275 [INFO] [LLM] Batch size: 56
2026-02-27 18:19:02,276 [INFO] [LLM] Batch size: 52
2026-02-27 18:19:02,277 [INFO] [LLM] Batch size: 38
2026-02-27 18:19:02,277 [INFO] [LLM] Batch size: 51
2026-02-27 18:19:02,277 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,278 [INFO] [LLM] Batch size: 67
2026-02-27 18:19:02,278 [INFO] [LLM] Batch size: 70
2026-02-27 18:19:02,278 [INFO] [LLM] Batch size: 69
2026-02-27 18:19:02,279 [INFO] [LLM] Batch size: 64
2026-02-27 18:19:02,280 [INFO] [LLM] Batch size: 49
2026-02-27 18:19:02,280 [INFO] [LLM] Batch size: 56
2026-02-27 18:19:02,281 [INFO] [LLM] Batch size: 59
2026-02-27 18:19:02,281 [INFO] [LLM] Batch size: 72
2026-02-27 18:19:02,282 [INFO] [LLM] Batch size: 59
2026-02-27 18:19:02,282 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,283 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,283 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,283 [INFO] [LLM] Batch size: 68
2026-02-27 18:19:02,284 [INFO] [LLM] Batch size: 66
2026-02-27 18:19:02,284 [INFO] [LLM] Batch size: 62
2026-02-27 18:19:02,285 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,286 [INFO] [LLM] Batch size: 70
2026-02-27 18:19:02,286 [INFO] [LLM] Batch size: 57
2026-02-27 18:19:02,286 [INFO] [LLM] Batch size: 61
2026-02-27 18:19:02,287 [INFO] [LLM] Batch size: 48
2026-02-27 18:19:02,287 [INFO] [LLM] Batch size: 59
2026-02-27 18:19:02,287 [INFO] [LLM] Batch size: 58
2026-02-27 18:19:02,288 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,288 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,288 [INFO] [LLM] Batch size: 56
2026-02-27 18:19:02,288 [INFO] [LLM] Batch size: 63
2026-02-27 18:19:02,289 [INFO] [LLM] Batch size: 62
2026-02-27 18:19:02,289 [INFO] [LLM] Batch size: 54
2026-02-27 18:19:02,289 [INFO] [LLM] Batch size: 71
2026-02-27 18:19:02,290 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,290 [INFO] [LLM] Batch size: 64
2026-02-27 18:19:02,292 [INFO] [LLM] Batch size: 58
2026-02-27 18:19:02,293 [INFO] [LLM] Batch size: 63
2026-02-27 18:19:02,293 [INFO] [LLM] Batch size: 55
2026-02-27 18:19:02,294 [INFO] [LLM] Batch size: 74
2026-02-27 18:19:02,294 [INFO] [LLM] Batch size: 74
2026-02-27 18:19:02,295 [INFO] [LLM] Batch size: 69
2026-02-27 18:19:02,295 [INFO] [LLM] Batch size: 79
2026-02-27 18:19:02,295 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,296 [INFO] [LLM] Batch size: 66
2026-02-27 18:19:02,296 [INFO] [LLM] Batch size: 78
2026-02-27 18:19:02,296 [INFO] [LLM] Batch size: 78
2026-02-27 18:19:02,297 [INFO] [LLM] Batch size: 71
2026-02-27 18:19:02,297 [INFO] [LLM] Batch size: 67
2026-02-27 18:19:02,298 [INFO] [LLM] Batch size: 62
2026-02-27 18:19:02,298 [INFO] [LLM] Batch size: 62
2026-02-27 18:19:02,300 [INFO] [LLM] Batch size: 52
2026-02-27 18:19:02,300 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,301 [INFO] [LLM] Batch size: 74
2026-02-27 18:19:02,301 [INFO] [LLM] Batch size: 71
2026-02-27 18:19:02,301 [INFO] [LLM] Batch size: 70
2026-02-27 18:19:02,302 [INFO] [LLM] Batch size: 54
2026-02-27 18:19:02,302 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,302 [INFO] [LLM] Batch size: 40
2026-02-27 18:19:02,303 [INFO] [LLM] Batch size: 48
2026-02-27 18:19:02,303 [INFO] [LLM] Batch size: 78
2026-02-27 18:19:02,303 [INFO] [LLM] Batch size: 67
2026-02-27 18:19:02,304 [INFO] [LLM] Batch size: 68
2026-02-27 18:19:02,304 [INFO] [LLM] Batch size: 73
2026-02-27 18:19:02,304 [INFO] [LLM] Batch size: 66
2026-02-27 18:19:02,305 [INFO] [LLM] Batch size: 65
2026-02-27 18:19:02,305 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,305 [INFO] [LLM] Batch size: 66
2026-02-27 18:19:02,306 [INFO] [LLM] Batch size: 48
2026-02-27 18:19:02,306 [INFO] [LLM] Batch size: 45
2026-02-27 18:19:02,306 [INFO] [LLM] Batch size: 67
2026-02-27 18:19:02,307 [INFO] [LLM] Batch size: 55
2026-02-27 18:19:02,307 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,309 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,309 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,310 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,310 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,310 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,311 [INFO] [LLM] Batch size: 65
2026-02-27 18:19:02,311 [INFO] [LLM] Batch size: 51
2026-02-27 18:19:02,311 [INFO] [LLM] Batch size: 63
2026-02-27 18:19:02,312 [INFO] [LLM] Batch size: 59
2026-02-27 18:19:02,312 [INFO] [LLM] Batch size: 70
2026-02-27 18:19:02,312 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,313 [INFO] [LLM] Batch size: 65
2026-02-27 18:19:02,313 [INFO] [LLM] Batch size: 64
2026-02-27 18:19:02,314 [INFO] [LLM] Batch size: 76
2026-02-27 18:19:02,314 [INFO] [LLM] Batch size: 66
2026-02-27 18:19:02,314 [INFO] [LLM] Batch size: 70
2026-02-27 18:19:02,315 [INFO] [LLM] Batch size: 74
2026-02-27 18:19:02,315 [INFO] [LLM] Batch size: 69
2026-02-27 18:19:02,316 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,316 [INFO] [LLM] Batch size: 46
2026-02-27 18:19:02,317 [INFO] [LLM] Batch size: 64
2026-02-27 18:19:02,317 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,317 [INFO] [LLM] Batch size: 49
2026-02-27 18:19:02,321 [INFO] [LLM] Batch size: 45
2026-02-27 18:19:02,321 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,322 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,323 [INFO] [LLM] Batch size: 52
2026-02-27 18:19:02,323 [INFO] [LLM] Batch size: 65
2026-02-27 18:19:02,323 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,324 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,324 [INFO] [LLM] Batch size: 51
2026-02-27 18:19:02,325 [INFO] [LLM] Batch size: 54
2026-02-27 18:19:02,325 [INFO] [LLM] Batch size: 53
2026-02-27 18:19:02,327 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,328 [INFO] [LLM] Batch size: 52
2026-02-27 18:19:02,329 [INFO] [LLM] Batch size: 49
2026-02-27 18:19:02,330 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,330 [INFO] [LLM] Batch size: 58
2026-02-27 18:19:02,331 [INFO] [LLM] Batch size: 51
2026-02-27 18:19:02,332 [INFO] [LLM] Batch size: 52
2026-02-27 18:19:02,333 [INFO] [LLM] Batch size: 73
2026-02-27 18:19:02,333 [INFO] [LLM] Batch size: 57
2026-02-27 18:19:02,334 [INFO] [LLM] Batch size: 62
2026-02-27 18:19:02,335 [INFO] [LLM] Batch size: 57
2026-02-27 18:19:02,335 [INFO] [LLM] Batch size: 69
2026-02-27 18:19:02,336 [INFO] [LLM] Batch size: 61
2026-02-27 18:19:02,336 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,336 [INFO] [LLM] Batch size: 50
2026-02-27 18:19:02,337 [INFO] [LLM] Batch size: 43
2026-02-27 18:19:02,337 [INFO] [LLM] Batch size: 44
2026-02-27 18:19:02,338 [INFO] [LLM] Batch size: 60
2026-02-27 18:19:02,338 [INFO] [LLM] Batch size: 74
2026-02-27 18:19:02,339 [INFO] [LLM] Batch size: 63
2026-02-27 18:19:02,339 [INFO] [LLM] Batch size: 64
2026-02-27 18:19:02,340 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,340 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,341 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,341 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,341 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,342 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,342 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,343 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,343 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,343 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,344 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,344 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,344 [INFO] [LLM] Batch size: 77
2026-02-27 18:19:02,345 [INFO] [LLM] Batch size: 57
2026-02-27 18:19:02,345 [INFO] [LLM] Batch size: 64
2026-02-27 18:19:02,345 [INFO] [LLM] Batch size: 61
2026-02-27 18:19:02,346 [INFO] [LLM] Batch size: 80
2026-02-27 18:19:02,346 [INFO] [LLM] Batch size: 57
2026-02-27 18:19:02,346 [INFO] [LLM] Batch size: 55
2026-02-27 18:19:02,347 [INFO] [LLM] Batch size: 11

[map][drug][OpenTargets] raw='A-623' -> id='CHEMBL2107877'
[map][drug][OpenTargets] raw='AC-1204' -> id='CHEMBL1406148'
[map][drug][OpenTargets] raw='ADL-5859' -> id='CHEMBL494480'
[map][drug][OpenTargets] raw='AMANTADINE' -> id='CHEMBL660'
[map][drug][OpenTargets] raw='AMINOSALICYLIC ACID' -> id='CHEMBL1169'
[map][drug][OpenTargets] raw='AMPICILLIN' -> id='CHEMBL174'
[map][drug][OpenTargets] raw='AV-412' -> id='CHEMBL6067986'
[map][drug][OpenTargets] raw='AV-412 free base' -> id='CHEMBL2138625'
[map][drug][OpenTargets] raw='Abemaciclib' -> id='CHEMBL3301610'
[map][drug][OpenTargets] raw='Abivertinib' -> id='CHEMBL4297865'
[map][drug][OpenTargets] raw='Acalabrutinib' -> id='CHEMBL3707348'
[map][drug][OpenTargets] raw='Acetaminophen' -> id='CHEMBL112'
[map][drug][OpenTargets] raw='Afatinib' -> id='CHEMBL1173655'
[map][drug][OpenTargets] raw='Afatinib Dimaleate' -> id='CHEMBL2105712'
[map][drug][OpenTargets] raw='Agerafenib' -> id='CHEMBL2029988'
[map][drug][OpenTargets] raw='Ajulemic acid' -> id='CHEMBL456341'
[map][drug][OpenTargets] raw='Alclofenac' -> id='CHEMBL94081'
[map][drug][OpenTargets] raw='Alflutinib' -> id='CHEMBL4297258'
[map][drug][OpenTargets] raw='Alicaforsen' -> id='CHEMBL2108326'
[map][drug][OpenTargets] raw='Alisertib' -> id='CHEMBL483158'
[map][drug][OpenTargets] raw='Alitretinoin' -> id='CHEMBL705'
[map][drug][OpenTargets] raw='Allitinib' -> id='CHEMBL1947204'
[map][drug][OpenTargets] raw='Almotriptan' -> id='CHEMBL1505'
[map][drug][OpenTargets] raw='Alpelisib' -> id='CHEMBL2396661'
[map][drug][OpenTargets] raw='Alpha-Tocopherol' -> id='CHEMBL47'
[map][drug][OpenTargets] raw='Alvocidib' -> id='CHEMBL428690'
[map][drug][OpenTargets] raw='Amantadine Hydrochloride' -> id='CHEMBL1569'
[map][drug][OpenTargets] raw='Amikacin' -> id='CHEMBL177'
[map][drug][OpenTargets] raw='Amiodarone' -> id='CHEMBL633'
[map][drug][OpenTargets] raw='Anastrozole' -> id='CHEMBL1399'
[map][drug][OpenTargets] raw='Andolast' -> id='CHEMBL119549'
[map][drug][OpenTargets] raw='Apilimod' -> id='CHEMBL4297643'
[map][drug][OpenTargets] raw='Apitolisib' -> id='CHEMBL1922094'
[map][drug][OpenTargets] raw='Apomorphine' -> id='CHEMBL53'
[map][drug][OpenTargets] raw='Apomorphine Hydrochloride' -> id='CHEMBL3187985'
[map][drug][OpenTargets] raw='Apratastat' -> id='CHEMBL206815'
[map][drug][OpenTargets] raw='Apricoxib' -> id='CHEMBL1835207'
[map][drug][OpenTargets] raw='Arbaclofen' -> id='CHEMBL301742'
[map][drug][OpenTargets] raw='Arecoline' -> id='CHEMBL7303'
[map][drug][OpenTargets] raw='Asandeutertinib' -> id='CHEMBL6068008'
[map][drug][OpenTargets] raw='Asciminib hydrochloride' -> id='CHEMBL4297220'
[map][drug][OpenTargets] raw='Aspirin' -> id='CHEMBL25'
[map][drug][OpenTargets] raw='Ast-487' -> id='CHEMBL574738'
[map][drug][OpenTargets] raw='Astemizole' -> id='CHEMBL296419'
[map][drug][OpenTargets] raw='Atuzabrutinib' -> id='CHEMBL4114766'
[map][drug][OpenTargets] raw='Aumolertinib' -> id='CHEMBL4761468'
[map][drug][OpenTargets] raw='Axitinib' -> id='CHEMBL1289926'
[map][drug][OpenTargets] raw='Azathioprine' -> id='CHEMBL1542'
[map][drug][OpenTargets] raw='Azd-1152hqpa' -> id='CHEMBL215152'
[map][drug][OpenTargets] raw='Azd-3759' -> id='CHEMBL3623290'
[map][drug][OpenTargets] raw='Azd6703' -> id='CHEMBL2031465'
[map][drug][OpenTargets] raw='Aztreonam' -> id='CHEMBL158'
[map][drug][OpenTargets] raw='BL-7040' -> id='CHEMBL6068601'
[map][drug][OpenTargets] raw='BUDESONIDE' -> id='CHEMBL1370'
[map][drug][OpenTargets] raw='Baciguent' -> id='CHEMBL1200558'
[map][drug][OpenTargets] raw='Balsalazide' -> id='CHEMBL1201346'
[map][drug][OpenTargets] raw='Balsalazide disodium' -> id='CHEMBL1200760'
[map][drug][OpenTargets] raw='Barasertib' -> id='CHEMBL415049'
[map][drug][OpenTargets] raw='Baricitinib' -> id='CHEMBL2105759'
[map][drug][OpenTargets] raw='Bedaquiline' -> id='CHEMBL376488'
[map][drug][OpenTargets] raw='Bedaquiline fumarate' -> id='CHEMBL2105700'
[map][drug][OpenTargets] raw='Befotertinib' -> id='CHEMBL5095167'
[map][drug][OpenTargets] raw='Beigene-283' -> id='CHEMBL4209157'
[map][drug][OpenTargets] raw='Bemcentinib' -> id='CHEMBL3809489'
[map][drug][OpenTargets] raw='Benorilate' -> id='CHEMBL162036'
[map][drug][OpenTargets] raw='Benserazide' -> id='CHEMBL1096979'
[map][drug][OpenTargets] raw='Bentiromide' -> id='CHEMBL1200368'
[map][drug][OpenTargets] raw='Benztropine' -> id='CHEMBL1201203'
[map][drug][OpenTargets] raw='Bfh-772' -> id='CHEMBL4080062'
[map][drug][OpenTargets] raw='Biperiden' -> id='CHEMBL1101'
[map][drug][OpenTargets] raw='Bithionol' -> id='CHEMBL290106'
[map][drug][OpenTargets] raw='Blarcamesine' -> id='CHEMBL4297224'
[map][drug][OpenTargets] raw='Bleomycin' -> id='CHEMBL6067492'
[map][drug][OpenTargets] raw='Bms-599626' -> id='CHEMBL1645462'
[map][drug][OpenTargets] raw='Bms-777607' -> id='CHEMBL460702'
[map][drug][OpenTargets] raw='Bornaprine' -> id='CHEMBL4297087'
[map][drug][OpenTargets] raw='Bosutinib' -> id='CHEMBL288441'
[map][drug][OpenTargets] raw='Bosutinib hydrate' -> id='CHEMBL2095206'
[map][drug][OpenTargets] raw='Branebrutinib' -> id='CHEMBL4297674'
[map][drug][OpenTargets] raw='Brasofensine' -> id='CHEMBL2104184'
[map][drug][OpenTargets] raw='Brigatinib' -> id='CHEMBL3545311'
[map][drug][OpenTargets] raw='Brivanib' -> id='CHEMBL377300'
[map][drug][OpenTargets] raw='Brivudine' -> id='CHEMBL31634'
[map][drug][OpenTargets] raw='Bromocriptine' -> id='CHEMBL493'
[map][drug][OpenTargets] raw='Bromocriptine Mesylate' -> id='CHEMBL1200503'
[map][drug][OpenTargets] raw='Buprenorphine' -> id='CHEMBL511142'
[map][drug][OpenTargets] raw='Busulfan' -> id='CHEMBL820'
[map][drug][OpenTargets] raw='CC-220' -> id='CHEMBL3989912'
[map][drug][OpenTargets] raw='CO-101' -> id='CHEMBL3039516'
[map][drug][OpenTargets] raw='CORTISONE ACETATE' -> id='CHEMBL1650'
[map][drug][OpenTargets] raw='CYCLOSERINE' -> id='CHEMBL771'
[map][drug][OpenTargets] raw='Cabergoline' -> id='CHEMBL1201087'
[map][drug][OpenTargets] raw='Cabozantinib' -> id='CHEMBL2105717'
[map][drug][OpenTargets] raw='Cabozantinib s-malate' -> id='CHEMBL2103868'
[map][drug][OpenTargets] raw='Caffeine' -> id='CHEMBL113'
[map][drug][OpenTargets] raw='Calcitriol' -> id='CHEMBL846'
[map][drug][OpenTargets] raw='Candesartan' -> id='CHEMBL1016'
[map][drug][OpenTargets] raw='Canertinib' -> id='CHEMBL31965'
[map][drug][OpenTargets] raw='Canertinib dihydrochloride' -> id='CHEMBL545315'
[map][drug][OpenTargets] raw='Capecitabine' -> id='CHEMBL1773'
[map][drug][OpenTargets] raw='Capeserod' -> id='CHEMBL2027925'
[map][drug][OpenTargets] raw='Capivasertib' -> id='CHEMBL2325741'
[map][drug][OpenTargets] raw='Capreomycin' -> id='CHEMBL2221250'
[map][drug][OpenTargets] raw='Capreomycin sulfate' -> id='CHEMBL2218913'
[map][drug][OpenTargets] raw='Carbidopa Monohydrate' -> id='CHEMBL1200748'
[map][drug][OpenTargets] raw='Cdc-801' -> id='CHEMBL88153'
[map][drug][OpenTargets] raw='Cediranib' -> id='CHEMBL491473'
[map][drug][OpenTargets] raw='Celecoxib' -> id='CHEMBL118'
[map][drug][OpenTargets] raw='Cenisertib' -> id='CHEMBL1967878'
[map][drug][OpenTargets] raw='Cep-11981' -> id='CHEMBL2010872'
[map][drug][OpenTargets] raw='Ceritinib' -> id='CHEMBL2403108'
[map][drug][OpenTargets] raw='Chenodiol' -> id='CHEMBL240597'
[map][drug][OpenTargets] raw='Chlorambucil' -> id='CHEMBL515'
[map][drug][OpenTargets] raw='Chlorpromazine' -> id='CHEMBL71'
[map][drug][OpenTargets] raw='Cholecalciferol' -> id='CHEMBL1042'
[map][drug][OpenTargets] raw='Cilengitide' -> id='CHEMBL429876'
[map][drug][OpenTargets] raw='Ciprofloxacin' -> id='CHEMBL8'
[map][drug][OpenTargets] raw='Clofazimine' -> id='CHEMBL1292'
[map][drug][OpenTargets] raw='Clonazepam' -> id='CHEMBL452'
[map][drug][OpenTargets] raw='Clozapine' -> id='CHEMBL42'
[map][drug][OpenTargets] raw='Combretastatin A4' -> id='CHEMBL67'
[map][drug][OpenTargets] raw='Corticotropin-zinc Hydroxide' -> id='CHEMBL1201609'
[map][drug][OpenTargets] raw='Cp-195543' -> id='CHEMBL301829'
[map][drug][OpenTargets] raw='Crizotinib' -> id='CHEMBL601719'
[map][drug][OpenTargets] raw='Cudc-101' -> id='CHEMBL598797'
[map][drug][OpenTargets] raw='Cudc-305' -> id='CHEMBL2419346'
[map][drug][OpenTargets] raw='Curcumin' -> id='CHEMBL140'
[map][drug][OpenTargets] raw='Cyclophosphamide' -> id='CHEMBL1200796'
[map][drug][OpenTargets] raw='Cyclosporine' -> id='CHEMBL160'
[map][drug][OpenTargets] raw='Cycrimine' -> id='CHEMBL1201227'
[map][drug][OpenTargets] raw='Cyproheptadine' -> id='CHEMBL516'
[map][drug][OpenTargets] raw='Cytarabine' -> id='CHEMBL803'
[map][drug][OpenTargets] raw='DAROLUTAMIDE' -> id='CHEMBL4297185'
[map][drug][OpenTargets] raw='DECLOPRAMIDE' -> id='CHEMBL1618378'
[map][drug][OpenTargets] raw='DIHYDROERGOTAMINE' -> id='CHEMBL1732'
[map][drug][OpenTargets] raw='DOTARIZINE' -> id='CHEMBL2106316'
[map][drug][OpenTargets] raw='Dabrafenib' -> id='CHEMBL2028663'
[map][drug][OpenTargets] raw='Dacomitinib' -> id='CHEMBL2105719'
[map][drug][OpenTargets] raw='Dacomitinib monohydrate' -> id='CHEMBL2105719'
[map][drug][OpenTargets] raw='Daidzein' -> id='CHEMBL8145'
[map][drug][OpenTargets] raw='Dalmelitinib' -> id='CHEMBL3818247'
[map][drug][OpenTargets] raw='Dasatinib' -> id='CHEMBL5416410'
[map][drug][OpenTargets] raw='Decernotinib' -> id='CHEMBL3039513'
[map][drug][OpenTargets] raw='Defactinib' -> id='CHEMBL3137331'
[map][drug][OpenTargets] raw='Delamanid' -> id='CHEMBL218650'
[map][drug][OpenTargets] raw='Denintuzumab mafodotin' -> id='CHEMBL3545371'
[map][drug][OpenTargets] raw='Dersalazine' -> id='CHEMBL2106406'
[map][drug][OpenTargets] raw='Desipramine' -> id='CHEMBL72'
[map][drug][OpenTargets] raw='Dexamethasone' -> id='CHEMBL384467'
[map][drug][OpenTargets] raw='Dexamethasone Sodium Phosphate' -> id='CHEMBL2021430'
[map][drug][OpenTargets] raw='Dexchlorpheniramine Maleate' -> id='CHEMBL1200927'
[map][drug][OpenTargets] raw='Dexpropranolol' -> id='CHEMBL275742'
[map][drug][OpenTargets] raw='Diazepam' -> id='CHEMBL12'
[map][drug][OpenTargets] raw='Diethylpropion' -> id='CHEMBL1194666'
[map][drug][OpenTargets] raw='Diethylstilbestrol' -> id='CHEMBL411'
[map][drug][OpenTargets] raw='Dimethyl Sulfoxide' -> id='CHEMBL504'
[map][drug][OpenTargets] raw='Dimethylcurcumin' -> id='CHEMBL128748'
[map][drug][OpenTargets] raw='Dipraglurant' -> id='CHEMBL2346738'
[map][drug][OpenTargets] raw='Dobutamine' -> id='CHEMBL926'
[map][drug][OpenTargets] raw='Docetaxel' -> id='CHEMBL3545252'
[map][drug][OpenTargets] raw='Docetaxel trihydrate' -> id='CHEMBL3545252'
[map][drug][OpenTargets] raw='Donitriptan' -> id='CHEMBL1742428'
[map][drug][OpenTargets] raw='Dopamine' -> id='CHEMBL59'
[map][drug][OpenTargets] raw='Doramapimod' -> id='CHEMBL103667'
[map][drug][OpenTargets] raw='Dovitinib' -> id='CHEMBL522892'
[map][drug][OpenTargets] raw='Doxorubicin' -> id='CHEMBL53463'
[map][drug][OpenTargets] raw='Droxidopa' -> id='CHEMBL2103827'
[map][drug][OpenTargets] raw='Duvelisib' -> id='CHEMBL3039502'
[map][drug][OpenTargets] raw='ETIPREDNOL DICLOACETATE' -> id='CHEMBL2107614'
[map][drug][OpenTargets] raw='Ebastine' -> id='CHEMBL305660'
[map][drug][OpenTargets] raw='Elacestrant' -> id='CHEMBL4297509'
[map][drug][OpenTargets] raw='Eletriptan' -> id='CHEMBL1510'
[map][drug][OpenTargets] raw='Ellagic Acid' -> id='CHEMBL6246'
[map][drug][OpenTargets] raw='Eltoprazine' -> id='CHEMBL282614'
[map][drug][OpenTargets] raw='Emodin' -> id='CHEMBL289277'
[map][drug][OpenTargets] raw='Enclomiphene' -> id='CHEMBL954'
[map][drug][OpenTargets] raw='Entacapone' -> id='CHEMBL953'
[map][drug][OpenTargets] raw='Enzastaurin' -> id='CHEMBL300138'
[map][drug][OpenTargets] raw='Epirubicin' -> id='CHEMBL417'
[map][drug][OpenTargets] raw='Eribulin Mesylate' -> id='CHEMBL1683544'
[map][drug][OpenTargets] raw='Erlotinib' -> id='CHEMBL553'
[map][drug][OpenTargets] raw='Erlotinib Hydrochloride' -> id='CHEMBL1079742'
[map][drug][OpenTargets] raw='Estradiol' -> id='CHEMBL135'
[map][drug][OpenTargets] raw='Etalocib' -> id='CHEMBL329123'
[map][drug][OpenTargets] raw='Ethambutol' -> id='CHEMBL44884'
[map][drug][OpenTargets] raw='Ethambutol hydrochloride' -> id='CHEMBL3140361'
[map][drug][OpenTargets] raw='Ethanol' -> id='CHEMBL545'
[map][drug][OpenTargets] raw='Ethionamide' -> id='CHEMBL1441'
[map][drug][OpenTargets] raw='Ethylenediamine' -> id='CHEMBL816'
[map][drug][OpenTargets] raw='Etilevodopa' -> id='CHEMBL1823681'
[map][drug][OpenTargets] raw='Etofenamate' -> id='CHEMBL1451633'
[map][drug][OpenTargets] raw='Etoricoxib' -> id='CHEMBL416146'
[map][drug][OpenTargets] raw='Eugenol' -> id='CHEMBL42710'
[map][drug][OpenTargets] raw='Everolimus' -> id='CHEMBL1908360'
[map][drug][OpenTargets] raw='Evobrutinib' -> id='CHEMBL4072833'
[map][drug][OpenTargets] raw='Evofosfamide' -> id='CHEMBL260046'
[map][drug][OpenTargets] raw='Exemestane' -> id='CHEMBL1200374'
[map][drug][OpenTargets] raw='FLUDROCORTISONE' -> id='CHEMBL1201388'
[map][drug][OpenTargets] raw='Falnidamol' -> id='CHEMBL258940'
[map][drug][OpenTargets] raw='Fedratinib' -> id='CHEMBL1287853'
[map][drug][OpenTargets] raw='Felbinac' -> id='CHEMBL413965'
[map][drug][OpenTargets] raw='Fenbufen' -> id='CHEMBL277522'
[map][drug][OpenTargets] raw='Fenoprofen' -> id='CHEMBL1297'
[map][drug][OpenTargets] raw='Fenoprofen calcium' -> id='CHEMBL2103736'
[map][drug][OpenTargets] raw='Filgotinib' -> id='CHEMBL3301607'
[map][drug][OpenTargets] raw='Floctafenine' -> id='CHEMBL2105075'
[map][drug][OpenTargets] raw='Floxuridine' -> id='CHEMBL917'
[map][drug][OpenTargets] raw='Flumatinib' -> id='CHEMBL3545413'
[map][drug][OpenTargets] raw='Flunarizine' -> id='CHEMBL30008'
[map][drug][OpenTargets] raw='Fluorouracil' -> id='CHEMBL185'
[map][drug][OpenTargets] raw='Fluphenazine' -> id='CHEMBL726'
[map][drug][OpenTargets] raw='Flurbiprofen' -> id='CHEMBL563'
[map][drug][OpenTargets] raw='Foretinib' -> id='CHEMBL1230609'
[map][drug][OpenTargets] raw='Forigerimod' -> id='CHEMBL3989409'
[map][drug][OpenTargets] raw='Forodesine' -> id='CHEMBL218291'
[map][drug][OpenTargets] raw='Fosbretabulin' -> id='CHEMBL1206232'
[map][drug][OpenTargets] raw='Fosdagrocorat' -> id='CHEMBL3137316'
[map][drug][OpenTargets] raw='Fostamatinib' -> id='CHEMBL2103830'
[map][drug][OpenTargets] raw='Frovatriptan' -> id='CHEMBL1279'
[map][drug][OpenTargets] raw='Fulvestrant' -> id='CHEMBL1358'
[map][drug][OpenTargets] raw='Futibatinib' -> id='CHEMBL3701238'
[map][drug][OpenTargets] raw='GPI-1485' -> id='CHEMBL4297382'
[map][drug][OpenTargets] raw='GTS-21' -> id='CHEMBL134713'
[map][drug][OpenTargets] raw='GV1001' -> id='CHEMBL2108308'
[map][drug][OpenTargets] raw='Gabapentin' -> id='CHEMBL940'
[map][drug][OpenTargets] raw='Galunisertib' -> id='CHEMBL2364611'
[map][drug][OpenTargets] raw='Gamma-Aminobutyric Acid' -> id='CHEMBL96'
[map][drug][OpenTargets] raw='Ganciclovir' -> id='CHEMBL182'
[map][drug][OpenTargets] raw='Gandotinib' -> id='CHEMBL2107823'
[map][drug][OpenTargets] raw='Gefitinib' -> id='CHEMBL939'
[map][drug][OpenTargets] raw='Gemcitabine' -> id='CHEMBL888'
[map][drug][OpenTargets] raw='Gemcitabine Hydrochloride' -> id='CHEMBL1637'
[map][drug][OpenTargets] raw='Genistein' -> id='CHEMBL44'
[map][drug][OpenTargets] raw='Gentian Violet' -> id='CHEMBL64894'
[map][drug][OpenTargets] raw='Gilteritinib' -> id='CHEMBL3301622'
[map][drug][OpenTargets] raw='Glufosfamide' -> id='CHEMBL2107143'
[map][drug][OpenTargets] raw='Gsk-690693' -> id='CHEMBL494089'
[map][drug][OpenTargets] raw='HYDROCORTISONE ACETATE' -> id='CHEMBL1091'
[map][drug][OpenTargets] raw='Hexachlorophene' -> id='CHEMBL496'
[map][drug][OpenTargets] raw='Hki-357' -> id='CHEMBL178654'
[map][drug][OpenTargets] raw='Hmn-214' -> id='CHEMBL3991927'
[map][drug][OpenTargets] raw='Hydrocortisone' -> id='CHEMBL389621'
[map][drug][OpenTargets] raw='Hydrocortisone Butyrate' -> id='CHEMBL1683'
[map][drug][OpenTargets] raw='Hydrocortisone Sodium Succinate' -> id='CHEMBL1200495'
[map][drug][OpenTargets] raw='Hydroxychloroquine Sulfate' -> id='CHEMBL1690'
[map][drug][OpenTargets] raw='Hydroxyurea' -> id='CHEMBL467'
[map][drug][OpenTargets] raw='IB-Meca' -> id='CHEMBL3989873'
[map][drug][OpenTargets] raw='IXABEPILONE' -> id='CHEMBL1201752'
[map][drug][OpenTargets] raw='Ibrutinib' -> id='CHEMBL1873475'
[map][drug][OpenTargets] raw='Ibuprofen' -> id='CHEMBL521'
[map][drug][OpenTargets] raw='Icotinib' -> id='CHEMBL2087361'
[map][drug][OpenTargets] raw='Iguratimod' -> id='CHEMBL2107455'
[map][drug][OpenTargets] raw='Ilorasertib' -> id='CHEMBL1980297'
[map][drug][OpenTargets] raw='Imatinib' -> id='CHEMBL941'
[map][drug][OpenTargets] raw='Imatinib Mesylate' -> id='CHEMBL1642'
[map][drug][OpenTargets] raw='Indomethacin' -> id='CHEMBL6'
[map][drug][OpenTargets] raw='Indoximod' -> id='CHEMBL571209'
[map][drug][OpenTargets] raw='Infigratinib' -> id='CHEMBL1852688'
[map][drug][OpenTargets] raw='Inosine pranobex' -> id='CHEMBL3833327'
[map][drug][OpenTargets] raw='Iodoquinol' -> id='CHEMBL86754'
[map][drug][OpenTargets] raw='Ioflupane i-123' -> id='CHEMBL3989517'
[map][drug][OpenTargets] raw='Irbesartan' -> id='CHEMBL1513'
[map][drug][OpenTargets] raw='Irinotecan Hydrochloride Hydrate' -> id='CHEMBL3989514'
[map][drug][OpenTargets] raw='Iruplinalkib' -> id='CHEMBL5095068'
[map][drug][OpenTargets] raw='Isoniazid' -> id='CHEMBL64'
[map][drug][OpenTargets] raw='Istradefylline' -> id='CHEMBL431770'
[map][drug][OpenTargets] raw='Janex-1' -> id='CHEMBL405130'
[map][drug][OpenTargets] raw='Jnj-26483327' -> id='CHEMBL3109738'
[map][drug][OpenTargets] raw='KRP-203' -> id='CHEMBL2137148'
[map][drug][OpenTargets] raw='Kadcyla' -> id='CHEMBL1201585'
[map][drug][OpenTargets] raw='Kanamycin' -> id='CHEMBL1384'
[map][drug][OpenTargets] raw='Ketoconazole' -> id='CHEMBL157101'
[map][drug][OpenTargets] raw='Ketoprofen' -> id='CHEMBL571'
[map][drug][OpenTargets] raw='Kw-2449' -> id='CHEMBL1908397'
[map][drug][OpenTargets] raw='LX2931' -> id='CHEMBL1852164'
[map][drug][OpenTargets] raw='Lapatinib' -> id='CHEMBL554'
[map][drug][OpenTargets] raw='Lapatinib Ditosylate' -> id='CHEMBL1201179'
[map][drug][OpenTargets] raw='Larotaxel' -> id='CHEMBL4279455'
[map][drug][OpenTargets] raw='Lasmiditan' -> id='CHEMBL3039520'
[map][drug][OpenTargets] raw='Lazertinib' -> id='CHEMBL4558324'
[map][drug][OpenTargets] raw='Leflunomide' -> id='CHEMBL960'
[map][drug][OpenTargets] raw='Lestaurtinib' -> id='CHEMBL603469'
[map][drug][OpenTargets] raw='Letrozole' -> id='CHEMBL1444'
[map][drug][OpenTargets] raw='Leucovorin' -> id='CHEMBL1679'
[map][drug][OpenTargets] raw='Levodopa' -> id='CHEMBL1009'
[map][drug][OpenTargets] raw='Lgh-447' -> id='CHEMBL3651966'
[map][drug][OpenTargets] raw='Lidocaine' -> id='CHEMBL79'
[map][drug][OpenTargets] raw='Linezolid' -> id='CHEMBL126'
[map][drug][OpenTargets] raw='Linifanib' -> id='CHEMBL223360'
[map][drug][OpenTargets] raw='Linsitinib' -> id='CHEMBL1091644'
[map][drug][OpenTargets] raw='Lintitript' -> id='CHEMBL249973'
[map][drug][OpenTargets] raw='Lisuride' -> id='CHEMBL157138'
[map][drug][OpenTargets] raw='Lorlatinib' -> id='CHEMBL3286830'
[map][drug][OpenTargets] raw='Marimastat' -> id='CHEMBL279785'
[map][drug][OpenTargets] raw='Masitinib' -> id='CHEMBL1908391'
[map][drug][OpenTargets] raw='Masoprocol' -> id='CHEMBL313972'
[map][drug][OpenTargets] raw='Mavelertinib' -> id='CHEMBL3989970'
[map][drug][OpenTargets] raw='Mechlorethamine' -> id='CHEMBL427'
[map][drug][OpenTargets] raw='Meclinertant' -> id='CHEMBL506981'
[map][drug][OpenTargets] raw='Meclofenamate sodium' -> id='CHEMBL1562610'
[map][drug][OpenTargets] raw='Meclomen' -> id='CHEMBL1562610'
[map][drug][OpenTargets] raw='Melevodopa' -> id='CHEMBL1328898'
[map][drug][OpenTargets] raw='Meloxicam' -> id='CHEMBL599'
[map][drug][OpenTargets] raw='Mercaptopurine' -> id='CHEMBL1200751'
[map][drug][OpenTargets] raw='Mesalamine' -> id='CHEMBL704'
[map][drug][OpenTargets] raw='Metformin' -> id='CHEMBL1431'
[map][drug][OpenTargets] raw='Metformin Hydrochloride' -> id='CHEMBL1703'
[map][drug][OpenTargets] raw='Metformin glycinate' -> id='CHEMBL2108299'
[map][drug][OpenTargets] raw='Methimazole' -> id='CHEMBL1515'
[map][drug][OpenTargets] raw='Methotrexate' -> id='CHEMBL34259'

2026-02-27 18:19:07,564 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:07,588 [INFO] [LLM] Batch done in 5.33s
2026-02-27 18:19:07,614 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:07,616 [INFO] [LLM] Batch done in 5.35s
2026-02-27 18:19:07,847 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:07,850 [INFO] [LLM] Batch done in 5.62s
2026-02-27 18:19:13,111 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:13,114 [INFO] [LLM] Batch done in 10.85s
2026-02-27 18:19:15,371 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:15,373 [INFO] [LLM] Batch done in 13.10s
2026-02-27 18:19:18,149 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:18,151 [INFO] [LLM] Batch done in 15.88s
2026-02-27 18:19:18,152 [ERROR] [LLM] JSON parse failed: Unterminated string starting at: line 60 column 5 (char 7866) | raw='{\n    "(2R,3S)-N-(4-(3-Bromoanilino)quinazolin-6-yl)-3-(piperidin-1-ylmethyl)oxirane-2-carboxamide": null,\n    "(2R,3S,4S,6S)-3-methoxy-2-methyl-4-(methylamino)-29-oxa-1,7,17-triazaoctacyclo[12.12.2.12,6.07,28.08,13.015,19.020,27.021,26]nonacosa-8,10,12,14,19,21,23,25,27-nonaene-16,18-dione": null,\n    "(2R,3S,4S,6S)-4-[2-hydroxyhexyl(methyl)amino]-3-methoxy-2-methyl-29-oxa-1,7,17-triazaoctacyclo[12.12.2.12,6.07,28.08,13.015,19.020,27.021,26]nonacosa-8,10,12,14,19,21,23,25,27-nonaen-16-one": null,\n    "(2R,3S,4S,6S)-4-[benzyl(methyl)amino]-3-methoxy-2-methyl-29-oxa-1,7,17-triazaoctacyclo[12.12.2.12,6.07,28.08,13.015,19.020,27.021,26]nonacosa-8,10,12,14,19,21,23,25,27-nonaen-16-one": null,\n    "(2R,3S,4S,6S)-4-[ethyl(methyl)amino]-3-methoxy-2-methyl-29-oxa-1,7,17-triazaoctacyclo[12.12.2.12,6.07,28.08,13.015,19.020,27.021,26]nonacosa-8,10,12,14,19,21,23,25,27-nonaen-16-one": null,\n    "(2R,4R)-1-((4-(3-chloro-2-fluorophenylamino)-7-methoxyquinazolin-6-yl)methyl)-4-methoxypyrrolidine-2-carboxamide": null,\n    "(2R,4R)-4-[4-(3-chloro-2,4-difluoroanilino)-7-methoxyquinazolin-6-yl]oxy-1-prop-2-enoylpiperidine-2-carboxamide": null,\n    "(2R,4R)-4-[4-(3-chloro-2,4-difluoroanilino)-7-methoxyquinazolin-6-yl]oxy-N-methyl-1-prop-2-enoylpiperidine-2-carboxamide": null,\n    "(2R,4R)-methyl 1-acryloyl-4-(4-(3-chloro-2,4-difluorophenylamino)-7-methoxyquinazolin-6-yloxy)piperidin-2-carboxylate": null,\n    "(2R,4S)-1-[(2S)-2-[[11-[4-[3-[4-(3-chloro-4-fluoroanilino)-7-methoxyquinazolin-6-yl]oxypropyl]piperazin-1-yl]-11-oxoundecanoyl]amino]-3,3-dimethylbutanoyl]-4-hydroxy-N-[[4-(4-methyl-1,3-thiazol-5-yl)phenyl]methyl]pyrrolidine-2-carboxamide": null,\n    "(2S)-1-(tert-butylamino)-3-(dicyclopropylmethylideneamino)oxypropan-2-ol": null,\n    "(2S)-1-[(5E)-5-[(6-bromopyridin-2-yl)methylidene]-4-oxo-1,3-thiazol-2-yl]-N-[4-(3-chloroanilino)quinazolin-6-yl]pyrrolidine-2-carboxamide": null,\n    "(2S)-1-[2-[2-[2-[4-(1,3-benzothiazol-2-yl)-2-methoxyphenoxy]acetyl]hydrazinyl]-2-oxoethyl]pyrrolidine-2-carboxylic acid": null,\n    "(2S)-1-[4-(3-chloro-4-fluoroanilino)-7-methoxyquinazolin-6-yl]oxy-3-morpholin-4-ylpropan-2-ol": null,\n    "(2S)-2-[(11-ethenylsulfonyl-8-thia-4,6,11-triazatricyclo[7.4.0.02,7]trideca-1(9),2,4,6-tetraen-3-yl)amino]-2-phenylethanol": null,\n    "(2S)-2-[(4-{[3-Chloro-4-(pyridin-2-ylmethoxy)phenyl]amino}quinazolin-5-yl)oxy]-N-(2-hydroxyethyl)-N-methylpropanamide": null,\n    "(2S)-2-[(5-bromo-6-phenylfuro[2,3-d]pyrimidin-4-yl)amino]-2-phenylethanol": null,\n    "(2S)-2-[(5-chloro-6-phenylfuro[2,3-d]pyrimidin-4-yl)amino]-2-phenylethanol": null,\n    "(2S)-2-[(6-bromothieno[2,3-d]pyrimidin-4-yl)amino]-2-phenylethanol": null,\n    "(2S)-2-[(7-methyl-6-phenylpyrrolo[2,3-d]pyrimidin-4-yl)amino]-2-phenylethanol": null,\n    "(2S)-2-[4-[3-chloro-4-(pyridin-2-ylmethoxy)anilino]quinazolin-5-yl]oxy-N,N-dimethylpropanamide": null,\n    "(2S)-2-[[2-[2-[2-[4-(1,3-benzothiazol-2-yl)-2-methoxyphenoxy]acetyl]hydrazinyl]-2-oxoethyl]amino]propanoic acid": null,\n    "(2S)-2-[[2-[2-[2-[4-(1,3-benzothiazol-2-yl)-2-methoxyphenoxy]acetyl]hydrazinyl]-2-oxoethyl]amino]-3-(1H-imidazol-5-yl)propanoic acid": null,\n    "(2S)-2-[[2-[2-[2-[4-(1,3-benzothiazol-2-yl)-2-methoxyphenoxy]acetyl]hydrazinyl]-2-oxoethyl]amino]-3-(1H-indol-3-yl)propanoic acid": null,\n    "(2S)-2-[[4-(3-chloro-4-fluoroanilino)-7-methoxyquinazolin-6-yl]methyl-propan-2-ylamino]propanamide": null,\n    "(2S)-2-[[5-(1,3-benzodioxol-5-yl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(3-aminophenyl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(3-nitrophenyl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(furan-2-yl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(furan-3-yl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2,6-dimethoxyphenyl)thieno[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2-ethoxyphenyl)-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2-methoxyphenyl)-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2-methoxyphenyl)thieno[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(3-methoxypyridin-4-yl)-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(4-methoxyphenyl)furo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(4-methoxyphenyl)furo[2,3-d]pyrimidin-4-yl]amino]propan-1-ol": null,\n    "(2S)-2-[[6-(4-methylsulfonylphenyl)-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-[2-methoxy-4-[(2-methylsulfonylethylamino)methyl]phenyl]-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-[2-methoxy-4-[(2-morpholin-4-ylethylamino)methyl]phenyl]-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-[2-methoxy-4-[(2-piperazin-1-ylethylamino)methyl]phenyl]-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-[2-methoxy-4-[(2-piperidin-1-ylethylamino)methyl]phenyl]-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-[3-(hydroxymethyl)phenyl]thieno[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[(11-ethenylsulfonyl-8-thia-4,6,11-triazatricyclo[7.4.0.02,7]trideca-1(9),2,4,6-tetraen-3-yl)amino]-2-phenylethanol": null,\n    "(2S)-2-[[(2S)-2-[[4-(3-chloro-4-fluoroanilino)-7-methoxyquinazolin-6-yl]oxypropyl]piperazin-1-yl]-11-oxoundecanoyl]amino]-3,3-dimethylbutanoyl]-4-hydroxy-N-[[4-(4-methyl-1,3-thiazol-5-yl)phenyl]methyl]pyrrolidine-2-carboxamide": null,\n    "(2S)-2-[[(2S,3R)-2-[[(2S)-1-[(2S)-2-[[(2S,3S)-2-[[(2S)-2-[[(2S)-2-acetamidopropanoyl]amino]-5-carbamimidamidopentanoyl]amino]-3-methylpentanoyl]amino]-3-(4-hydroxyphenyl)propanoyl]pyrrolidine-2-carbonyl]amino]-3-hydroxybutanoyl]amino]-N-[2-[[(2S)-1-[[(2S,3R)-1-[[(2S)-1-[[(2S)-1-amino-3-(4-hydroxyphenyl)-1-oxopropan-2-yl]amino]-5-carbamimidamido-1-oxopentan-2-yl]amino]-3-hydroxy-1-oxobutan-2-yl]amino]-3-(4-hydroxyphenyl)-1-oxopropan-2-yl]amino]-2-oxoethyl]butanediamide": null,\n    "(2S)-2-[[(2S,3R)-2-[[(2S)-2-[[(2S)-2-[[(2S)-4-amino-2-[[(2S)-2-[[(2S)-2-[[(2S)-2-[[(2S)-2,6-diaminohexanoyl]amino]propanoyl]amino]-3-methylbutanoyl]amino]-3-(4-hydroxyphenyl)propanoyl]amino]-4-oxobutanoyl]amino]-3-phenylpropanoyl]amino]propanoyl]amino]-3-hydroxybutanoyl]amino]-4-methylsulfanylbutanoic acid": null,\n    "(2S)-2-[[(3S)-3-[[(2S)-5-(diaminomethylideneamino)-2-[[5-[[(2S,3S,4S,6R)-3-hydroxy-2-methyl-6-[[(1S,3S)-3,5,12-trihydroxy-3-(2-hydroxyacetyl)-10-methoxy-6,11-dioxo-2,4-dihydro-1H-tetracen-1-yl]oxy]oxan-4-yl]amino]-5-oxopentanoyl]amino]pentanoyl]amino]-3-naphthalen-1-ylpropanoyl]amino]-3-phenylpropanoic acid": null,\n    "(2S)-2-[[2-[2-[2-[4-(1,3-benzothiazol-2-yl)-2-methoxyphenoxy]acetyl]hydrazinyl]-2-oxoethyl]amino]-3-(1H-imidazol-5-yl)propanoic acid": null,\n    "(2S)-2-[[2-[2-[2-[4-(1,3-benzothiazol-2-yl)-2-methoxyphenoxy]acetyl]hydrazinyl]-2-oxoethyl]amino]-3-(1H-indol-3-yl)propanoic acid": null,\n    "(2S)-2-[[4-(3-chloro-4-fluoroanilino)-7-methoxyquinazolin-6-yl]methyl-propan-2-ylamino]propanamide": null,\n    "(2S)-2-[[5-(1,3-benzodioxol-5-yl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(3-aminophenyl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(3-nitrophenyl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(furan-2-yl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[5-(furan-3-yl)-6-phenylfuro[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2,6-dimethoxyphenyl)thieno[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2-ethoxyphenyl)-7H-pyrrolo[2,3-d]pyrimidin-4-yl]amino]-2-phenylethanol": null,\n    "(2S)-2-[[6-(2-methoxyphenyl)-7H-pyrrolo[2,3-d]pyrim'
2026-02-27 18:19:18,153 [WARNING] [LLM] Retrying drug batch by splitting 46 -> 23 + 23
2026-02-27 18:19:18,153 [INFO] [LLM] Batch size: 23
2026-02-27 18:19:18,156 [INFO] [LLM] Batch size: 23
2026-02-27 18:19:19,538 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:19,541 [INFO] [LLM] Batch done in 17.27s
2026-02-27 18:19:21,718 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:21,720 [INFO] [LLM] Batch done in 19.45s
2026-02-27 18:19:23,292 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:23,295 [INFO] [LLM] Batch done in 21.02s
2026-02-27 18:19:24,716 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:24,719 [INFO] [LLM] Batch done in 22.45s
2026-02-27 18:19:30,006 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:30,009 [INFO] [LLM] Batch done in 27.74s
2026-02-27 18:19:31,350 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:31,352 [INFO] [LLM] Batch done in 29.08s
2026-02-27 18:19:33,460 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:33,463 [INFO] [LLM] Batch done in 31.19s
2026-02-27 18:19:35,570 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:35,572 [INFO] [LLM] Batch done in 33.30s
2026-02-27 18:19:37,094 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:37,096 [INFO] [LLM] Batch done in 34.82s
2026-02-27 18:19:39,180 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:39,182 [INFO] [LLM] Batch done in 36.91s
2026-02-27 18:19:40,998 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:41,001 [INFO] [LLM] Batch done in 38.73s
2026-02-27 18:19:42,388 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:42,390 [INFO] [LLM] Batch done in 40.12s
2026-02-27 18:19:44,370 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:44,372 [INFO] [LLM] Batch done in 42.10s
2026-02-27 18:19:46,283 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:46,285 [INFO] [LLM] Batch done in 44.01s
2026-02-27 18:19:48,115 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:48,117 [INFO] [LLM] Batch done in 45.84s
2026-02-27 18:19:49,716 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:49,718 [INFO] [LLM] Batch done in 47.44s
2026-02-27 18:19:51,566 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:51,568 [INFO] [LLM] Batch done in 49.29s
2026-02-27 18:19:53,744 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:53,747 [INFO] [LLM] Batch done in 51.47s
2026-02-27 18:19:54,873 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:54,875 [INFO] [LLM] Batch done in 52.60s
2026-02-27 18:19:56,979 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:19:56,982 [INFO] [LLM] Batch done in 54.70s
2026-02-27 18:20:00,276 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:00,278 [INFO] [LLM] Batch done in 58.00s
2026-02-27 18:20:01,389 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:01,392 [INFO] [LLM] Batch done in 59.11s
2026-02-27 18:20:03,422 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:03,425 [INFO] [LLM] Batch done in 61.15s
2026-02-27 18:20:05,835 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:05,838 [INFO] [LLM] Batch done in 63.56s
2026-02-27 18:20:07,744 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:07,746 [INFO] [LLM] Batch done in 65.47s
2026-02-27 18:20:08,753 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:08,755 [INFO] [LLM] Batch done in 66.47s
2026-02-27 18:20:12,386 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:12,388 [INFO] [LLM] Batch done in 70.11s
2026-02-27 18:20:13,965 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:13,968 [INFO] [LLM] Batch done in 71.69s
2026-02-27 18:20:14,288 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:14,291 [INFO] [LLM] Batch done in 72.01s
2026-02-27 18:20:17,917 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:17,919 [INFO] [LLM] Batch done in 75.64s
2026-02-27 18:20:20,108 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:20,110 [INFO] [LLM] Batch done in 77.83s
2026-02-27 18:20:20,498 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:20,500 [INFO] [LLM] Batch done in 78.22s
2026-02-27 18:20:23,037 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:23,040 [INFO] [LLM] Batch done in 80.76s
2026-02-27 18:20:25,990 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:25,992 [INFO] [LLM] Batch done in 83.71s
2026-02-27 18:20:26,121 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:26,123 [INFO] [LLM] Batch done in 83.84s
2026-02-27 18:20:28,447 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:28,449 [INFO] [LLM] Batch done in 86.16s
2026-02-27 18:20:31,651 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:31,653 [INFO] [LLM] Batch done in 89.37s
2026-02-27 18:20:32,710 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:32,712 [INFO] [LLM] Batch done in 90.43s
2026-02-27 18:20:33,780 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:33,783 [INFO] [LLM] Batch done in 91.50s
2026-02-27 18:20:37,125 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:37,127 [INFO] [LLM] Batch done in 94.84s
2026-02-27 18:20:38,149 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:38,151 [INFO] [LLM] Batch done in 95.86s
2026-02-27 18:20:39,541 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:39,543 [INFO] [LLM] Batch done in 97.26s
2026-02-27 18:20:43,153 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:43,156 [INFO] [LLM] Batch done in 100.87s
2026-02-27 18:20:43,594 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:43,596 [INFO] [LLM] Batch done in 101.31s
2026-02-27 18:20:45,180 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:45,183 [INFO] [LLM] Batch done in 102.89s
2026-02-27 18:20:48,979 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:48,982 [INFO] [LLM] Batch done in 106.69s
2026-02-27 18:20:49,190 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:49,192 [INFO] [LLM] Batch done in 106.90s
2026-02-27 18:20:50,642 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:50,644 [INFO] [LLM] Batch done in 108.35s
2026-02-27 18:20:53,984 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:53,986 [INFO] [LLM] Batch done in 111.70s
2026-02-27 18:20:54,627 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:54,629 [INFO] [LLM] Batch done in 112.34s
2026-02-27 18:20:55,945 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:55,947 [INFO] [LLM] Batch done in 113.65s
2026-02-27 18:20:59,931 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:20:59,934 [INFO] [LLM] Batch done in 117.64s
2026-02-27 18:21:00,464 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:00,467 [INFO] [LLM] Batch done in 118.17s
2026-02-27 18:21:01,703 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:01,705 [INFO] [LLM] Batch done in 119.41s
2026-02-27 18:21:05,115 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:05,117 [INFO] [LLM] Batch done in 122.82s
2026-02-27 18:21:06,772 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:06,774 [INFO] [LLM] Batch done in 124.48s
2026-02-27 18:21:07,103 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:07,106 [INFO] [LLM] Batch done in 124.81s
2026-02-27 18:21:08,135 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:08,137 [INFO] [LLM] Batch done in 125.84s
2026-02-27 18:21:11,703 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:11,705 [INFO] [LLM] Batch done in 129.41s
2026-02-27 18:21:12,576 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:12,579 [INFO] [LLM] Batch done in 130.28s
2026-02-27 18:21:13,642 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:21:13,644 [INFO] [LLM] Batch done in 131.35s

[map][drug][Llama] raw='(S)-Ibrutinib' -> canonical='IBRUTINIB' -> id='CHEMBL1873475'
[map][drug][Llama] raw='Vandetanib hydrochloride' -> canonical='VANDETANIB' -> id='CHEMBL24828'
[map][drug][Llama] raw='diammine[cyclobutane-1,1-dicarboxylato(2-)-k2O1,O1]platinum' -> canonical='CARBOPLATIN' -> id='CHEMBL1351'

                                               drug_name drug_id source
0                                ((plusmn))-Zanubrutinib    None   None
1      (+)-(1R,3R)-1-(3-hydroxy-cyclopentyl)-3-(4-met...    None   None
2                                    (+)-Interiotherin B    None   None
3      (+/-)-trans-3,4,4a,5,6,10b-Hexahydro-9-carbamo...    None   None
4      (-)-(1S,3S)-1-(3-hydroxy-cyclopentyl)-3-(4-met...    None   None
...                                                  ...     ...    ...
10865  {N}-[4-[({E})-3-(3,4,5-trimethoxyphenyl)prop-2...    None   None
10866  {N}-[4-[({E})-3-(3,4-dimethoxyphenyl)prop-2-en...    None   None
10867  {N}-[4-[({E})-3-(3,4-dimethoxyphenyl)prop-2-en...    None   None
10868  {N}-[4-[({E})-3-(3,4-dimethoxyphenyl)prop-2-en...    None   None
10869  {N}-[4-[({E})-3-(3-methoxyphenyl)prop-2-enoyl]...    None   None

[10870 rows x 3 columns]

In [11]:
df_drug["source"].value_counts()

source
OpenTargets    574
Llama            3
Name: count, dtype: int64

In [12]:
# df_drug[df_drug["source"]=="Llama"]

In [13]:
df_drug[df_drug.isna().any(axis=1)]

                                               drug_name drug_id source
0                                ((plusmn))-Zanubrutinib    None   None
1      (+)-(1R,3R)-1-(3-hydroxy-cyclopentyl)-3-(4-met...    None   None
2                                    (+)-Interiotherin B    None   None
3      (+/-)-trans-3,4,4a,5,6,10b-Hexahydro-9-carbamo...    None   None
4      (-)-(1S,3S)-1-(3-hydroxy-cyclopentyl)-3-(4-met...    None   None
...                                                  ...     ...    ...
10865  {N}-[4-[({E})-3-(3,4,5-trimethoxyphenyl)prop-2...    None   None
10866  {N}-[4-[({E})-3-(3,4-dimethoxyphenyl)prop-2-en...    None   None
10867  {N}-[4-[({E})-3-(3,4-dimethoxyphenyl)prop-2-en...    None   None
10868  {N}-[4-[({E})-3-(3,4-dimethoxyphenyl)prop-2-en...    None   None
10869  {N}-[4-[({E})-3-(3-methoxyphenyl)prop-2-enoyl]...    None   None

[10293 rows x 3 columns]

##### Associate id with all disease entry

In [14]:
# Resolve unique disease surface forms to IDs.
# Canonical fallback is internal; returned rows remain keyed by raw input disease_name.
df_disease = await get_disease_ids_fast(list(question_entities["disease_name"]))
df_disease = df_disease.drop_duplicates(subset=["disease_name", "disease_id"]).reset_index(drop=True)
df_disease

2026-02-27 18:24:13,427 [INFO] [LLM] Total 95 names split into 2 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:24:13,428 [INFO] [LLM] Batch size: 80
2026-02-27 18:24:13,429 [INFO] [LLM] Batch size: 15

[map][disease][OpenTargets] raw='5q- syndrome' -> id='MONDO_0007925'
[map][disease][OpenTargets] raw='Absence seizure' -> id='MONDO_0010826'
[map][disease][OpenTargets] raw='Acidosis' -> id='EFO_1000014'
[map][disease][OpenTargets] raw='Acne vulgaris' -> id='EFO_0003894'
[map][disease][OpenTargets] raw='Acquired methemoglobinemia' -> id='MONDO_0018740'
[map][disease][OpenTargets] raw='Acquired pure red cell aplasia' -> id='MONDO_0020338'
[map][disease][OpenTargets] raw='Acromegaly' -> id='EFO_1001485'
[map][disease][OpenTargets] raw='Acute Coronary Syndrome' -> id='EFO_0005672'
[map][disease][OpenTargets] raw='Acute Kidney Injury' -> id='MONDO_0002492'
[map][disease][OpenTargets] raw='Acute Lung Injury' -> id='EFO_1000637'
[map][disease][OpenTargets] raw='Acute myelogenous leukaemia' -> id='EFO_0000222'
[map][disease][OpenTargets] raw='Acute myeloid leukaemia' -> id='MONDO_0015667'
[map][disease][OpenTargets] raw='Acute myeloid leukemia' -> id='EFO_0000222'
[map][disease][OpenTargets] raw='Adrenal carcinoma' -> id='MONDO_0002814'
[map][disease][OpenTargets] raw='Adrenocortical Carcinoma' -> id='EFO_1000796'
[map][disease][OpenTargets] raw='Adrenocortical carcinoma' -> id='EFO_1000796'
[map][disease][OpenTargets] raw='Age-related macular degeneration' -> id='EFO_0001365'
[map][disease][OpenTargets] raw='Alcohol dependence' -> id='MONDO_0002046'
[map][disease][OpenTargets] raw='Allergic contact dermatitis' -> id='EFO_1000668'
[map][disease][OpenTargets] raw='Allergic rhinitis' -> id='EFO_0005854'
[map][disease][OpenTargets] raw='Allergy' -> id='MONDO_0005271'
[map][disease][OpenTargets] raw='Alopecia' -> id='MONDO_0004907'
[map][disease][OpenTargets] raw='Alzheimer disease' -> id='MONDO_0007088'
[map][disease][OpenTargets] raw='Amnesia' -> id='EFO_1001454'
[map][disease][OpenTargets] raw='Amoebiasis' -> id='EFO_0007144'
[map][disease][OpenTargets] raw='Amyloidosis' -> id='EFO_1001875'
[map][disease][OpenTargets] raw='Amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][OpenTargets] raw='Anaphylaxis' -> id='MONDO_0100053'
[map][disease][OpenTargets] raw='Anemia' -> id='MONDO_0002280'
[map][disease][OpenTargets] raw='Aneurysm' -> id='EFO_0009659'
[map][disease][OpenTargets] raw='Angina pectoris' -> id='EFO_0003913'
[map][disease][OpenTargets] raw='Angioedema' -> id='EFO_0005532'
[map][disease][OpenTargets] raw='Ankylosing spondylitis' -> id='EFO_0003898'
[map][disease][OpenTargets] raw='Anxiety disorder' -> id='EFO_0006788'
[map][disease][OpenTargets] raw='Aphasia' -> id='HP_0002381'
[map][disease][OpenTargets] raw='Apnea' -> id='HP_0002104'
[map][disease][OpenTargets] raw='Arteritis' -> id='EFO_0009011'
[map][disease][OpenTargets] raw='Arthralgia' -> id='HP_0002829'
[map][disease][OpenTargets] raw='Arthritis' -> id='EFO_0005856'
[map][disease][OpenTargets] raw='Ascariasis' -> id='EFO_0007154'
[map][disease][OpenTargets] raw='Aspergillosis' -> id='EFO_0007157'
[map][disease][OpenTargets] raw='Asthma' -> id='MONDO_0004979'
[map][disease][OpenTargets] raw='Ataxia' -> id='MONDO_0100308'
[map][disease][OpenTargets] raw='Atherosclerosis' -> id='EFO_0003914'
[map][disease][OpenTargets] raw='Athetosis' -> id='HP_0002305'
[map][disease][OpenTargets] raw='Atopic dermatitis' -> id='EFO_0000274'
[map][disease][OpenTargets] raw='Atrial Fibrillation' -> id='EFO_0000275'
[map][disease][OpenTargets] raw='Atrial fibrillation' -> id='EFO_0000275'
[map][disease][OpenTargets] raw='Atrophic vaginitis' -> id='EFO_1001271'
[map][disease][OpenTargets] raw='Atrophy' -> id='EFO_1000096'
[map][disease][OpenTargets] raw='Attention deficit hyperactivity disorder' -> id='EFO_0003888'
[map][disease][OpenTargets] raw='Autism Spectrum Disorder' -> id='EFO_0003756'
[map][disease][OpenTargets] raw='Autism spectrum disorder' -> id='EFO_0003756'
[map][disease][OpenTargets] raw='Autoimmune hemolytic anemia' -> id='EFO_1001264'
[map][disease][OpenTargets] raw='B-cell acute lymphoblastic leukemia' -> id='EFO_0000094'
[map][disease][OpenTargets] raw='Back Pain' -> id='HP_0003418'
[map][disease][OpenTargets] raw='Bacterial infection' -> id='EFO_0000771'
[map][disease][OpenTargets] raw='Basal cell carcinoma' -> id='EFO_0004193'
[map][disease][OpenTargets] raw='Benign prostatic hyperplasia' -> id='EFO_0000284'
[map][disease][OpenTargets] raw='Bipolar disorder' -> id='MONDO_0004985'
[map][disease][OpenTargets] raw='Bladder cancer' -> id='MONDO_0004986'
[map][disease][OpenTargets] raw='Blastomycosis' -> id='EFO_0007174'
[map][disease][OpenTargets] raw='Bleeding disorder' -> id='MONDO_0002243'
[map][disease][OpenTargets] raw='Blepharospasm' -> id='MONDO_0011728'
[map][disease][OpenTargets] raw='Bone Resorption' -> id='GO_0045453'
[map][disease][OpenTargets] raw='Bone disease' -> id='EFO_0004260'
[map][disease][OpenTargets] raw='Bradycardia' -> id='HP_0001662'
[map][disease][OpenTargets] raw='Brain injury' -> id='MONDO_0043510'
[map][disease][OpenTargets] raw='Breast cancer' -> id='EFO_0000305'
[map][disease][OpenTargets] raw='Bronchial Hyperreactivity' -> id='MONDO_0004979'
[map][disease][OpenTargets] raw='Bronchitis' -> id='EFO_0009661'
[map][disease][OpenTargets] raw='Brucellosis' -> id='EFO_0007185'
[map][disease][OpenTargets] raw='Bulimia Nervosa' -> id='EFO_0005204'
[map][disease][OpenTargets] raw='Bulimia nervosa' -> id='EFO_0005204'
[map][disease][OpenTargets] raw='Burkitt lymphoma' -> id='EFO_0000309'
[map][disease][OpenTargets] raw='Burning Mouth Syndrome' -> id='EFO_1000850'
[map][disease][OpenTargets] raw='Cachexia' -> id='HP_0004326'
[map][disease][OpenTargets] raw='Candidiasis' -> id='MONDO_0002026'
[map][disease][OpenTargets] raw='Carcinoma' -> id='EFO_0000313'
[map][disease][OpenTargets] raw='Cardiac arrhythmias' -> id='EFO_0004269'
[map][disease][OpenTargets] raw='Cardiac failure' -> id='EFO_0003144'
[map][disease][OpenTargets] raw='Cardiovascular disease' -> id='EFO_0000319'
[map][disease][OpenTargets] raw='Cataract' -> id='MONDO_0005129'
[map][disease][OpenTargets] raw='Central nervous system disease' -> id='EFO_0009386'
[map][disease][OpenTargets] raw='Cerebellar Ataxia' -> id='MONDO_0011426'
[map][disease][OpenTargets] raw='Cerebral Infarction' -> id='EFO_0000712'
[map][disease][OpenTargets] raw='Cervical cancer' -> id='EFO_0001061'
[map][disease][OpenTargets] raw='Cholangiocarcinoma' -> id='EFO_0005221'
[map][disease][OpenTargets] raw='Chondrosarcoma' -> id='EFO_0000333'
[map][disease][OpenTargets] raw='Chorea' -> id='EFO_0004152'
[map][disease][OpenTargets] raw='Choroidal Neovascularization' -> id='EFO_0004683'
[map][disease][OpenTargets] raw='Chronic lymphocytic leukaemia' -> id='EFO_0000095'
[map][disease][OpenTargets] raw='Chronic lymphocytic leukemia' -> id='EFO_0000095'
[map][disease][OpenTargets] raw='Chronic myelogenous leukaemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='Chronic myeloid leukaemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='Chronic myeloid leukemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='Chronic myelomonocytic leukaemia' -> id='EFO_1000309'
[map][disease][OpenTargets] raw='Chronic obstructive pulmonary disease (COPD)' -> id='EFO_0000341'
[map][disease][OpenTargets] raw='Chronic pain' -> id='HP_0012532'
[map][disease][OpenTargets] raw='Cluster headache' -> id='HP_0012199'
[map][disease][OpenTargets] raw='Coagulation defect' -> id='EFO_0009314'
[map][disease][OpenTargets] raw='Cocaine addiction' -> id='EFO_0002610'
[map][disease][OpenTargets] raw='Colitis' -> id='EFO_0003872'
[map][disease][OpenTargets] raw='Colon cancer' -> id='EFO_1001950'
[map][disease][OpenTargets] raw='Colorectal cancer' -> id='EFO_1001951'
[map][disease][OpenTargets] raw='Coma' -> id='MONDO_0009764'
[map][disease][OpenTargets] raw='Common Cold' -> id='EFO_0007214'
[map][disease][OpenTargets] raw='Complex partial seizure' -> id='HP_0002384'
[map][disease][OpenTargets] raw='Congenital adrenal hyperplasia' -> id='MONDO_0018479'
[map][disease][OpenTargets] raw='Congestive heart failure' -> id='EFO_0000373'
[map][disease][OpenTargets] raw='Constipation' -> id='MONDO_0002203'
[map][disease][OpenTargets] raw='Contraception' -> id='EFO_0009520'
[map][disease][OpenTargets] raw='Coronary artery disease' -> id='EFO_0001645'
[map][disease][OpenTargets] raw='Cough' -> id='HP_0012735'
[map][disease][OpenTargets] raw='Crohn disease' -> id='EFO_0000384'
[map][disease][OpenTargets] raw='Cryptorchidism' -> id='EFO_0004562'
[map][disease][OpenTargets] raw='Cryptosporidiosis' -> id='MONDO_0015474'
[map][disease][OpenTargets] raw='Cushing syndrome' -> id='EFO_0003099'
[map][disease][OpenTargets] raw='Cutaneous T-cell lymphoma' -> id='EFO_0002913'
[map][disease][OpenTargets] raw='Cutaneous candidiasis' -> id='MONDO_0000879'
[map][disease][OpenTargets] raw='Cutaneous lupus erythematosus' -> id='EFO_0003834'
[map][disease][OpenTargets] raw='Cystic fibrosis' -> id='MONDO_0009061'
[map][disease][OpenTargets] raw='Cysticercosis' -> id='EFO_0007231'
[map][disease][OpenTargets] raw='Cystitis' -> id='EFO_1000025'
[map][disease][OpenTargets] raw='Deep vein thrombosis' -> id='EFO_0003907'
[map][disease][OpenTargets] raw='Delirium' -> id='EFO_0009267'
[map][disease][OpenTargets] raw='Dementia' -> id='MONDO_0001627'
[map][disease][OpenTargets] raw='Depression' -> id='MONDO_0002050'
[map][disease][OpenTargets] raw='Dermatitis' -> id='MONDO_0002406'
[map][disease][OpenTargets] raw='Dermatitis herpetiformis' -> id='EFO_1000684'
[map][disease][OpenTargets] raw='Dermatophytosis' -> id='MONDO_0004678'
[map][disease][OpenTargets] raw='Diabetes Insipidus' -> id='MONDO_0004782'
[map][disease][OpenTargets] raw='Diabetic Retinopathy' -> id='EFO_0003770'
[map][disease][OpenTargets] raw='Diabetic neuropathy' -> id='EFO_1000783'
[map][disease][OpenTargets] raw='Diamond-Blackfan anemia' -> id='MONDO_0015253'
[map][disease][OpenTargets] raw='Diarrhea' -> id='MONDO_0001673'
[map][disease][OpenTargets] raw='Diffuse large B-cell lymphoma' -> id='EFO_0000403'
[map][disease][OpenTargets] raw='Discoid lupus erythematosus' -> id='MONDO_0019558'
[map][disease][OpenTargets] raw='Dizziness' -> id='EFO_0009847'
[map][disease][OpenTargets] raw='Dravet syndrome' -> id='MONDO_0100135'
[map][disease][OpenTargets] raw='Drug abuse' -> id='EFO_0003890'
[map][disease][OpenTargets] raw='Ductal carcinoma' -> id='EFO_0006318'
[map][disease][OpenTargets] raw='Duodenal Ulcer' -> id='EFO_0004607'
[map][disease][OpenTargets] raw='Dysbetalipoproteinemia' -> id='MONDO_0018473'
[map][disease][OpenTargets] raw='Dysmenorrhea' -> id='HP_0100607'
[map][disease][OpenTargets] raw='Dyspareunia' -> id='HP_0030016'
[map][disease][OpenTargets] raw='Dyspepsia' -> id='EFO_0008533'
[map][disease][OpenTargets] raw='Dystonia' -> id='MONDO_0003441'
[map][disease][OpenTargets] raw='Dysuria' -> id='EFO_0003901'
[map][disease][OpenTargets] raw='Early myoclonic encephalopathy' -> id='MONDO_0800491'
[map][disease][OpenTargets] raw='Eating disorder' -> id='EFO_0005203'
[map][disease][OpenTargets] raw='Eczema' -> id='EFO_0000274'
[map][disease][OpenTargets] raw='Edema' -> id='EFO_0009373'
[map][disease][OpenTargets] raw='Emphysema' -> id='EFO_0000464'
[map][disease][OpenTargets] raw='Endocarditis' -> id='EFO_0000465'
[map][disease][OpenTargets] raw='Endometrial cancer' -> id='EFO_0007532'
[map][disease][OpenTargets] raw='Endometriosis' -> id='EFO_0001065'
[map][disease][OpenTargets] raw='Endophthalmitis' -> id='MONDO_0016047'
[map][disease][OpenTargets] raw='Enterobiasis' -> id='EFO_0007254'
[map][disease][OpenTargets] raw='Enuresis' -> id='MONDO_0024290'
[map][disease][OpenTargets] raw='Epilepsy' -> id='EFO_0000474'
[map][disease][OpenTargets] raw='Epileptic seizures' -> id='EFO_0000474'
[map][disease][OpenTargets] raw='Epithelial ovarian cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='Erdheim-Chester disease' -> id='EFO_1000926'
[map][disease][OpenTargets] raw='Erectile Dysfunction' -> id='EFO_0004234'
[map][disease][OpenTargets] raw='Erectile dysfunction' -> id='EFO_0004234'
[map][disease][OpenTargets] raw='Erythema' -> id='HP_0010783'
[map][disease][OpenTargets] raw='Erythema multiforme' -> id='EFO_1000694'
[map][disease][OpenTargets] raw='Esophageal cancer' -> id='EFO_0002916'
[map][disease][OpenTargets] raw='Essential Hypertension' -> id='MONDO_0001134'
[map][disease][OpenTargets] raw='Essential thrombocythemia' -> id='EFO_0000479'
[map][disease][OpenTargets] raw='Essential tremor' -> id='EFO_0003108'
[map][disease][OpenTargets] raw='Familial hypercholesterolemia' -> id='EFO_0004911'
[map][disease][OpenTargets] raw='Fever' -> id='HP_0001945'
[map][disease][OpenTargets] raw='Fibromyalgia' -> id='EFO_0005687'
[map][disease][OpenTargets] raw='Fibrosis' -> id='EFO_0006890'
[map][disease][OpenTargets] raw='Follicular lymphoma' -> id='MONDO_0018906'
[map][disease][OpenTargets] raw='Friedreich ataxia' -> id='MONDO_0100339'
[map][disease][OpenTargets] raw='Frontotemporal Dementia' -> id='MONDO_0010857'
[map][disease][OpenTargets] raw='Fungal infection' -> id='MONDO_0002041'
[map][disease][OpenTargets] raw='Gastric adenocarcinoma' -> id='EFO_0000503'
[map][disease][OpenTargets] raw='Gastric cancer' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='Gastritis' -> id='EFO_0000217'
[map][disease][OpenTargets] raw='Gastroesophageal reflux disease' -> id='EFO_0003948'
[map][disease][OpenTargets] raw='Gastrointestinal disease' -> id='EFO_0010282'
[map][disease][OpenTargets] raw='Gastroparesis' -> id='EFO_1000948'
[map][disease][OpenTargets] raw='Gaucher disease' -> id='MONDO_0018150'
[map][disease][OpenTargets] raw='Generalized anxiety disorder' -> id='EFO_1001892'
[map][disease][OpenTargets] raw='Giant cell arteritis' -> id='EFO_1001209'
[map][disease][OpenTargets] raw='Giardiasis' -> id='DOID_10718'
[map][disease][OpenTargets] raw='Glioma' -> id='EFO_0005543'
[map][disease][OpenTargets] raw='Gout' -> id='EFO_0004274'
[map][disease][OpenTargets] raw='Grade IV astrocytoma' -> id='EFO_0000519'
[map][disease][OpenTargets] raw='Graft-versus-host disease' -> id='MONDO_0013730'
[map][disease][OpenTargets] raw='Gram-positive bacterial infection' -> id='MONDO_0021679'
[map][disease][OpenTargets] raw='Granuloma' -> id='HP_0032252'
[map][disease][OpenTargets] raw='Graves disease' -> id='EFO_0004237'
[map][disease][OpenTargets] raw='Hairy cell leukemia' -> id='EFO_1000956'
[map][disease][OpenTargets] raw='Head and neck cancer' -> id='EFO_0006859'
[map][disease][OpenTargets] raw='Headache' -> id='HP_0002315'
[map][disease][OpenTargets] raw='Heart Block' -> id='HP_0012722'
[map][disease][OpenTargets] raw='Heart disease' -> id='EFO_0003777'
[map][disease][OpenTargets] raw='Hemorrhage' -> id='MP_0001914'
[map][disease][OpenTargets] raw='Hepatic porphyria' -> id='MONDO_0002520'
[map][disease][OpenTargets] raw='Hepatitis C' -> id='EFO_0003047'
[map][disease][OpenTargets] raw='Hepatitis C virus infection' -> id='EFO_0003047'
[map][disease][OpenTargets] raw='Hepatitis D virus infection' -> id='EFO_0007304'
[map][disease][OpenTargets] raw='Hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Hereditary angioedema' -> id='MONDO_0019623'
[map][disease][OpenTargets] raw='High blood pressure' -> id='EFO_0000537'
[map][disease][OpenTargets] raw='Hodgkin lymphoma' -> id='EFO_0000183'
[map][disease][OpenTargets] raw='Human immunodeficiency virus infection' -> id='EFO_0000764'
[map][disease][OpenTargets] raw='Huntington disease' -> id='MONDO_0007739'
[map][disease][OpenTargets] raw='Hutchinson-Gilford progeria syndrome' -> id='MONDO_0008310'
[map][disease][OpenTargets] raw='Hypercalcaemia' -> id='HP_0003072'
[map][disease][OpenTargets] raw='Hypereosinophilic syndrome' -> id='EFO_1001467'
[map][disease][OpenTargets] raw='Hyperhidrosis' -> id='HP_0000975'
[map][disease][OpenTargets] raw='Hyperlipidemia' -> id='MONDO_0021187'
[map][disease][OpenTargets] raw='Hyperprolactinaemia' -> id='EFO_0007319'
[map][disease][OpenTargets] raw='Hyperprolactinemia' -> id='EFO_0007319'
[map][disease][OpenTargets] raw='Hypersensitivity' -> id='EFO_1002003'
[map][disease][OpenTargets] raw='Hypertension' -> id='EFO_0000537'
[map][disease][OpenTargets] raw='Hypertensive Encephalopathy' -> id='EFO_1000976'
[map][disease][OpenTargets] raw='Hyperthyroidism' -> id='EFO_0009189'
[map][disease][OpenTargets] raw='Hypertriglyceridemia' -> id='EFO_0004211'
[map][disease][OpenTargets] raw='Hypocalcemia' -> id='MONDO_0018543'
[map][disease][OpenTargets] raw='Hypoglycemia' -> id='HP_0001943'
[map][disease][OpenTargets] raw='Hypogonadotropic hypogonadism' -> id='EFO_1001006'
[map][disease][OpenTargets] raw='Hypohidrosis' -> id='EFO_1000712'
[map][disease][OpenTargets] raw='Hypokalemia' -> id='MONDO_0003019'
[map][disease][OpenTargets] raw='Hypokalemic periodic paralysis' -> id='MONDO_0008223'
[map][disease][OpenTargets] raw='Hypotension' -> id='EFO_0005251'
[map][disease][OpenTargets] raw='Hypothyroidism' -> id='EFO_0004705'
[map][disease][OpenTargets] raw='Idiopathic Pulmonary Fibrosis' -> id='EFO_0000768'
[map][disease][OpenTargets] raw='Idiopathic pulmonary fibrosis' -> id='EFO_0000768'
[map][disease][OpenTargets] raw='Immune System disease' -> id='EFO_0000540'
[map][disease][OpenTargets] raw='Immune thrombocytopenic purpura' -> id='EFO_0007160'
[map][disease][OpenTargets] raw='Infantile hemangioma' -> id='MONDO_0002407'
[map][disease][OpenTargets] raw='Infantile spasm' -> id='MONDO_0100620'
[map][disease][OpenTargets] raw='Infarction' -> id='EFO_0009463'
[map][disease][OpenTargets] raw='Infertility' -> id='EFO_0000545'
[map][disease][OpenTargets] raw='Inflammation' -> id='GO_0006954'
[map][disease][OpenTargets] raw='Inflammatory bowel disease' -> id='EFO_0003767'
[map][disease][OpenTargets] raw='Influenza virus infection' -> id='EFO_0007328'
[map][disease][OpenTargets] raw='Insomnia' -> id='EFO_0004698'
[map][disease][OpenTargets] raw='Intervertebral Disc Degeneration' -> id='EFO_0004994'
[map][disease][OpenTargets] raw='Intestinal cancer' -> id='EFO_0007330'
[map][disease][OpenTargets] raw='Irritable bowel syndrome' -> id='EFO_0000555'
[map][disease][OpenTargets] raw='Ischemia' -> id='EFO_0000556'
[map][disease][OpenTargets] raw='Ischemic Stroke' -> id='EFO_0000712'
[map][disease][OpenTargets] raw='Juvenile idiopathic arthritis' -> id='EFO_0002609'
[map][disease][OpenTargets] raw='Kaposi sarcoma' -> id='EFO_0000558'
[map][disease][OpenTargets] raw='Keratitis' -> id='EFO_0009449'
[map][disease][OpenTargets] raw='Keratosis' -> id='EFO_1000720'
[map][disease][OpenTargets] raw='Leiomyosarcoma' -> id='EFO_0000564'
[map][disease][OpenTargets] raw='Lennox-Gastaut syndrome' -> id='MONDO_0016532'
[map][disease][OpenTargets] raw='Lewy Body Disease' -> id='EFO_0006792'
[map][disease][OpenTargets] raw='Lewy body dementia' -> id='EFO_0006792'
[map][disease][OpenTargets] raw='Lichen planus' -> id='EFO_1000726'
[map][disease][OpenTargets] raw='Liposarcoma' -> id='EFO_0000569'
[map][disease][OpenTargets] raw='Liver Cirrhosis' -> id='EFO_0001422'
[map][disease][OpenTargets] raw='Liver cancer' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Long QT Syndrome' -> id='MONDO_0019171'
[map][disease][OpenTargets] raw='Lung cancer' -> id='EFO_0001071'
[map][disease][OpenTargets] raw='Lupus nephritis' -> id='EFO_0005761'
[map][disease][OpenTargets] raw='Lymphoma' -> id='EFO_0000574'
[map][disease][OpenTargets] raw='Lymphoplasmacytic lymphoma' -> id='MONDO_0000432'
[map][disease][OpenTargets] raw='Macular degeneration' -> id='EFO_0001365'
[map][disease][OpenTargets] raw='Macular edema' -> id='MONDO_0003005'
[map][disease][OpenTargets] raw='Major depressive disorder' -> id='MONDO_0002009'
[map][disease][OpenTargets] raw='Malaria' -> id='EFO_0001068'
[map][disease][OpenTargets] raw='Malignant pleural mesothelioma' -> id='EFO_0000770'
[map][disease][OpenTargets] raw='Mantle cell lymphoma' -> id='EFO_1001469'
[map][disease][OpenTargets] raw='Mast-cell leukemia' -> id='EFO_0007359'
[map][disease][OpenTargets] raw='Medullary thyroid cancer' -> id='MONDO_0015277'
[map][disease][OpenTargets] raw='Medulloblastoma' -> id='EFO_0002939'

2026-02-27 18:24:14,273 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:24:14,275 [INFO] [LLM] Batch done in 0.84s
2026-02-27 18:24:16,964 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:24:16,966 [INFO] [LLM] Batch done in 3.54s
2026-02-27 18:24:16,967 [INFO] [LLM] 'Acid-reflux disorder' → 'gastroesophageal reflux disease'
2026-02-27 18:24:16,968 [INFO] [LLM] 'Acute heart failure' → 'heart failure'
2026-02-27 18:24:16,968 [INFO] [LLM] 'Acute lymphoblastic leukaemia' → 'acute lymphoblastic leukemia'
2026-02-27 18:24:16,969 [INFO] [LLM] 'Acute pain' → None
2026-02-27 18:24:16,970 [INFO] [LLM] 'Allograft rejection' → 'allograft rejection'
2026-02-27 18:24:16,970 [INFO] [LLM] 'Amaurosis Fugax' → 'amaurosis fugax'
2026-02-27 18:24:16,971 [INFO] [LLM] 'Amyotrophic lateral sclerosis (ALS)' → 'amyotrophic lateral sclerosis'
2026-02-27 18:24:16,971 [INFO] [LLM] 'Anabolic metabolism' → None
2026-02-27 18:24:16,972 [INFO] [LLM] 'Anaesthesia' → None
2026-02-27 18:24:16,973 [INFO] [LLM] 'Anaplastic large-cell lymphoma' → 'anaplastic large cell lymphoma'
2026-02-27 18:24:16,973 [INFO] [LLM] 'Anomia' → None
2026-02-27 18:24:16,973 [INFO] [LLM] 'Attention deficit hyperactivity disorder (ADHD)' → 'attention deficit hyperactivity disorder'
2026-02-27 18:24:16,975 [INFO] [LLM] 'Bone metastases' → None
2026-02-27 18:24:16,975 [INFO] [LLM] 'Cestodes infection' → None
2026-02-27 18:24:16,976 [INFO] [LLM] 'Chronic low back pain' → None
2026-02-27 18:24:16,976 [INFO] [LLM] 'Congestive cardiac insufficiency' → 'heart failure'
2026-02-27 18:24:16,977 [INFO] [LLM] 'Death' → None
2026-02-27 18:24:16,977 [INFO] [LLM] 'Dental plaque' → None
2026-02-27 18:24:16,978 [INFO] [LLM] 'Diabetic complication' → None
2026-02-27 18:24:16,978 [INFO] [LLM] 'Eating Disorders' → None
2026-02-27 18:24:16,979 [INFO] [LLM] 'Embolism' → None
2026-02-27 18:24:16,979 [INFO] [LLM] 'Erythema nodosum leprosum' → 'erythema nodosum leprosum'
2026-02-27 18:24:16,980 [INFO] [LLM] 'Erythropoietic porphyrias' → 'porphyria'
2026-02-27 18:24:16,980 [INFO] [LLM] 'Female hypogonadism' → 'hypogonadism'
2026-02-27 18:24:16,981 [INFO] [LLM] 'Gastrointestinal cancer' → 'gastrointestinal neoplasms'
2026-02-27 18:24:16,984 [INFO] [LLM] 'Gastrointestinal stromal tumour' → 'gastrointestinal stromal tumor'
2026-02-27 18:24:16,984 [INFO] [LLM] 'Gastrotintestinal stromal tumor' → 'gastrointestinal stromal tumor'
2026-02-27 18:24:16,984 [INFO] [LLM] 'Genetic epileptic syndromes with variable age of onset' → None
2026-02-27 18:24:16,985 [INFO] [LLM] 'Glaucoma/ocular hypertension' → 'glaucoma'
2026-02-27 18:24:16,986 [INFO] [LLM] 'Gonorrheal vaginitis' → 'gonorrhea'
2026-02-27 18:24:16,986 [INFO] [LLM] 'HCV 1-6 infection' → 'hepatitis c'
2026-02-27 18:24:16,986 [INFO] [LLM] 'Haematological malignancy' → 'hematologic neoplasms'
2026-02-27 18:24:16,987 [INFO] [LLM] 'Hairy cell leukaemia' → 'hairy cell leukemia'
2026-02-27 18:24:16,987 [INFO] [LLM] 'Headache Disorders' → None
2026-02-27 18:24:16,988 [INFO] [LLM] 'Hemifacial Spasm' → 'hemifacial spasm'
2026-02-27 18:24:16,988 [INFO] [LLM] 'Herpes simplex virus infection' → 'herpes simplex'
2026-02-27 18:24:16,988 [INFO] [LLM] 'Hiccup' → None
2026-02-27 18:24:16,989 [INFO] [LLM] 'Hookworm disease' → 'hookworm infection'
2026-02-27 18:24:16,989 [INFO] [LLM] 'Hormone deficiency' → None
2026-02-27 18:24:16,991 [INFO] [LLM] 'Human echinococcosis' → 'echinococcosis'
2026-02-27 18:24:16,991 [INFO] [LLM] 'Hypercholesterolaemia' → 'hypercholesterolemia'
2026-02-27 18:24:16,991 [INFO] [LLM] 'Idiopathic generalized epilepsies' → 'epilepsy'
2026-02-27 18:24:16,992 [INFO] [LLM] 'Idiopathic parkinson disease' → 'parkinson disease'
2026-02-27 18:24:16,993 [INFO] [LLM] 'LennoxGastaut syndrome' → 'lennox-gastaut syndrome'
2026-02-27 18:24:16,993 [INFO] [LLM] 'Lung Injury' → None
2026-02-27 18:24:16,994 [INFO] [LLM] 'Malignant essential hypertension' → 'hypertension'
2026-02-27 18:24:16,995 [INFO] [LLM] 'Mammary analogue secretory carcinoma' → 'mammary analogue secretory carcinoma'
2026-02-27 18:24:16,995 [INFO] [LLM] 'Meningioma metastases' → None
2026-02-27 18:24:16,996 [INFO] [LLM] 'Menopausal and postmenopausal disorder' → 'menopause'
2026-02-27 18:24:16,996 [INFO] [LLM] 'Menopause symptom' → None
2026-02-27 18:24:16,996 [INFO] [LLM] 'Metastatic biliary tract neoplasms' → None
2026-02-27 18:24:16,997 [INFO] [LLM] 'Metastatic gastric or gastroesophageal junction cancer' → None
2026-02-27 18:24:16,997 [INFO] [LLM] 'Mononeuropathies' → None
2026-02-27 18:24:16,998 [INFO] [LLM] 'Morning Sickness' → 'morning sickness'
2026-02-27 18:24:17,000 [INFO] [LLM] 'Multi-drug resistant tuberculosis' → 'tuberculosis'
2026-02-27 18:24:17,000 [INFO] [LLM] 'Myeloid leukaemia' → 'myeloid leukemia'
2026-02-27 18:24:17,001 [INFO] [LLM] 'Neoplasms' → None
2026-02-27 18:24:17,001 [INFO] [LLM] 'Neoplastic meningitis' → 'neoplastic meningitis'
2026-02-27 18:24:17,002 [INFO] [LLM] 'Non-small-cell lung cancer' → 'non-small cell lung cancer'
2026-02-27 18:24:17,002 [INFO] [LLM] 'Ocular allergy' → None
2026-02-27 18:24:17,003 [INFO] [LLM] 'Paresis' → None
2026-02-27 18:24:17,004 [INFO] [LLM] 'Parkinsonian syndrome' → 'parkinson disease'
2026-02-27 18:24:17,004 [INFO] [LLM] 'Peripheral T cell lymphoma' → 'peripheral t-cell lymphoma'
2026-02-27 18:24:17,004 [INFO] [LLM] 'Pica' → 'pica'
2026-02-27 18:24:17,005 [INFO] [LLM] 'Polymyositis and dermatomyositis' → 'polymyositis'
2026-02-27 18:24:17,005 [INFO] [LLM] 'Premature labour' → 'premature birth'
2026-02-27 18:24:17,006 [INFO] [LLM] 'Premenstrual Syndrome' → 'premenstrual syndrome'
2026-02-27 18:24:17,006 [INFO] [LLM] 'Prion Diseases' → 'prion diseases'
2026-02-27 18:24:17,006 [INFO] [LLM] 'Psoriatic disorder' → 'psoriasis'
2026-02-27 18:24:17,007 [INFO] [LLM] 'Radioactive tracer' → None
2026-02-27 18:24:17,007 [INFO] [LLM] 'Recurrent glioblastoma' → 'glioblastoma'
2026-02-27 18:24:17,008 [INFO] [LLM] 'Reperfusion Injury' → 'reperfusion injury'
2026-02-27 18:24:17,008 [INFO] [LLM] 'Rift Valley Fever' → 'rift valley fever'
2026-02-27 18:24:17,009 [INFO] [LLM] 'Ringworm infection' → 'ringworm'
2026-02-27 18:24:17,009 [INFO] [LLM] 'Senile dementia' → 'alzheimer disease'
2026-02-27 18:24:17,012 [INFO] [LLM] 'Seronegative arthritis' → 'arthritis'
2026-02-27 18:24:17,013 [INFO] [LLM] 'Skin imperfections' → None
2026-02-27 18:24:17,013 [INFO] [LLM] 'Small-cell lung cancer' → 'small cell lung cancer'
2026-02-27 18:24:17,014 [INFO] [LLM] 'Smoking dependence' → 'tobacco use disorder'
2026-02-27 18:24:17,015 [INFO] [LLM] 'Soft tissue sarcomas' → 'soft tissue sarcoma'
2026-02-27 18:24:17,015 [INFO] [LLM] 'Solid tumour/cancer' → 'cancer'
2026-02-27 18:24:17,016 [INFO] [LLM] 'Squamous head and neck cell carcinom' → None
2026-02-27 18:24:17,016 [INFO] [LLM] 'Status epilepticus seizure' → None
2026-02-27 18:24:17,016 [INFO] [LLM] 'Stomach Ulcer' → 'peptic ulcer disease'
2026-02-27 18:24:17,017 [INFO] [LLM] 'Testosterone deficiency' → None
2026-02-27 18:24:17,018 [INFO] [LLM] 'Thrombocytopenia (THC)' → 'thrombocytopenia'
2026-02-27 18:24:17,018 [INFO] [LLM] 'Thymic cancer' → 'thymoma'
2026-02-27 18:24:17,018 [INFO] [LLM] 'Tic Disorders' → 'tic disorder'
2026-02-27 18:24:17,019 [INFO] [LLM] 'Tinea corporis' → 'tinea corporis'
2026-02-27 18:24:17,021 [INFO] [LLM] 'Tinea cruris' → 'tinea cruris'
2026-02-27 18:24:17,022 [INFO] [LLM] 'Trematode infection' → None
2026-02-27 18:24:17,022 [INFO] [LLM] 'Type-1 diabetes' → 'type 1 diabetes mellitus'
2026-02-27 18:24:17,023 [INFO] [LLM] 'Type-2 diabetes' → 'type 2 diabetes mellitus'
2026-02-27 18:24:17,023 [INFO] [LLM] 'Vertigo meniere disease' → None
2026-02-27 18:24:17,024 [INFO] [LLM] 'Vitamin K deficiency' → 'vitamin K deficiency'
2026-02-27 18:24:17,024 [INFO] [OT] Verifying 60 unique suggestions...
2026-02-27 18:24:17,567 [INFO] [OT] 'anaplastic large cell lymphoma' → 'anaplastic large cell lymphoma' (EFO_0003032)
2026-02-27 18:24:17,567 [INFO] [OT] 'glioblastoma' → 'glioblastoma multiforme' (EFO_0000519)
2026-02-27 18:24:17,568 [INFO] [OT] 'heart failure' → 'heart failure' (EFO_0003144)
2026-02-27 18:24:17,568 [INFO] [OT] 'lennox-gastaut syndrome' → 'Lennox-Gastaut syndrome' (MONDO_0016532)
2026-02-27 18:24:17,569 [INFO] [OT] 'polymyositis' → 'polymyositis' (EFO_0003063)
2026-02-27 18:24:17,569 [INFO] [OT] 'ringworm' → 'tinea' (EFO_0007510)
2026-02-27 18:24:17,570 [INFO] [OT] 'type 2 diabetes mellitus' → 'type 2 diabetes mellitus' (MONDO_0005148)
2026-02-27 18:24:17,570 [INFO] [OT] 'hairy cell leukemia' → 'hairy cell leukemia' (EFO_1000956)
2026-02-27 18:24:17,570 [INFO] [OT] 'cancer' → 'cancer' (MONDO_0004992)
2026-02-27 18:24:17,571 [INFO] [OT] 'acute lymphoblastic leukemia' → 'acute lymphoblastic leukemia' (EFO_0000220)
2026-02-27 18:24:17,571 [INFO] [OT] 'attention deficit hyperactivity disorder' → 'attention deficit hyperactivity disorder' (EFO_0003888)
2026-02-27 18:24:17,571 [INFO] [OT] 'premature birth' → 'premature birth' (EFO_0003917)
2026-02-27 18:24:17,572 [INFO] [OT] 'gastrointestinal stromal tumor' → 'GIST-plus syndrome' (EFO_0010279)
2026-02-27 18:24:17,572 [INFO] [OT] 'thymoma' → 'Thymoma' (EFO_1000581)
2026-02-27 18:24:17,574 [INFO] [OT] 'hookworm infection' → 'hookworm infectious disease' (EFO_0007314)
2026-02-27 18:24:17,575 [INFO] [OT] 'echinococcosis' → 'echinococcosis' (EFO_0007245)
2026-02-27 18:24:17,575 [INFO] [OT] 'epilepsy' → 'epilepsy' (EFO_0000474)
2026-02-27 18:24:17,576 [INFO] [OT] 'type 1 diabetes mellitus' → 'type 1 diabetes mellitus' (MONDO_0005147)
2026-02-27 18:24:17,576 [INFO] [OT] 'amyotrophic lateral sclerosis' → 'amyotrophic lateral sclerosis' (MONDO_0004976)
2026-02-27 18:24:17,577 [INFO] [OT] 'alzheimer disease' → 'Alzheimer disease type 1' (MONDO_0007088)
2026-02-27 18:24:17,577 [INFO] [OT] 'tic disorder' → 'tic disorder' (MONDO_0002420)
2026-02-27 18:24:17,578 [INFO] [OT] 'glaucoma' → 'glaucoma' (MONDO_0005041)
2026-02-27 18:24:17,578 [INFO] [OT] 'hypogonadism' → 'hypogonadism' (MONDO_0002146)
2026-02-27 18:24:17,579 [INFO] [OT] 'psoriasis' → 'psoriasis' (EFO_0000676)
2026-02-27 18:24:17,579 [INFO] [OT] 'gonorrhea' → 'gonorrhea' (DOID_7551)
2026-02-27 18:24:17,580 [INFO] [OT] 'hypertension' → 'hypertension' (EFO_0000537)
2026-02-27 18:24:17,580 [INFO] [OT] 'tobacco use disorder' → 'nicotine dependence' (EFO_0003768)
2026-02-27 18:24:17,580 [INFO] [OT] 'soft tissue sarcoma' → 'soft tissue sarcoma' (EFO_1001968)
2026-02-27 18:24:17,581 [INFO] [OT] 'gastroesophageal reflux disease' → 'gastroesophageal reflux disease' (EFO_0003948)
2026-02-27 18:24:17,581 [INFO] [OT] 'porphyria' → 'porphyria' (MONDO_0037939)
2026-02-27 18:24:17,582 [INFO] [OT] 'parkinson disease' → 'Parkinson disease' (MONDO_0005180)
2026-02-27 18:24:17,582 [INFO] [OT] 'non-small cell lung cancer' → 'non-small cell lung carcinoma' (EFO_0003060)
2026-02-27 18:24:17,583 [INFO] [OT] 'myeloid leukemia' → 'myeloid leukemia' (MONDO_0004643)
2026-02-27 18:24:17,583 [INFO] [OT] 'small cell lung cancer' → 'small cell lung carcinoma' (EFO_0000702)
2026-02-27 18:24:17,583 [INFO] [OT] 'peptic ulcer disease' → 'peptic ulcer disease' (MONDO_0004247)
2026-02-27 18:24:17,584 [INFO] [OT] 'hepatitis c' → 'hepatitis C virus infection' (EFO_0003047)
2026-02-27 18:24:17,584 [INFO] [OT] 'hypercholesterolemia' → 'Hypercholesterolemia' (HP_0003124)
2026-02-27 18:24:17,584 [INFO] [OT] 'menopause' → 'menopause' (GO_0042697)
2026-02-27 18:24:17,585 [INFO] [OT] 'arthritis' → 'arthritis' (EFO_0005856)
2026-02-27 18:24:17,585 [INFO] [OT] 'tuberculosis' → 'tuberculosis' (MONDO_0018076)
2026-02-27 18:24:17,585 [INFO] [OT] 'peripheral t-cell lymphoma' → 'mature T-cell and NK-cell non-Hodgkin lymphoma' (MONDO_0000430)
2026-02-27 18:24:17,586 [INFO] [OT] 'thrombocytopenia' → 'Thrombocytopenia' (HP_0001873)
2026-02-27 18:24:17,586 [INFO] [OT] 'herpes simplex' → 'Herpes simplex infection' (EFO_1002022)
2026-02-27 18:24:17,588 [INFO] Done: 46 / 95 confirmed | 49 → None

[map][disease][Llama] raw='Acid-reflux disorder' -> canonical='gastroesophageal reflux disease' -> id='EFO_0003948'
[map][disease][Llama] raw='Acute heart failure' -> canonical='heart failure' -> id='EFO_0003144'
[map][disease][Llama] raw='Acute lymphoblastic leukaemia' -> canonical='acute lymphoblastic leukemia' -> id='EFO_0000220'
[map][disease][Llama] raw='Amyotrophic lateral sclerosis (ALS)' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Anaplastic large-cell lymphoma' -> canonical='anaplastic large cell lymphoma' -> id='EFO_0003032'
[map][disease][Llama] raw='Attention deficit hyperactivity disorder (ADHD)' -> canonical='attention deficit hyperactivity disorder' -> id='EFO_0003888'
[map][disease][Llama] raw='Congestive cardiac insufficiency' -> canonical='heart failure' -> id='EFO_0003144'
[map][disease][Llama] raw='Erythropoietic porphyrias' -> canonical='porphyria' -> id='MONDO_0037939'
[map][disease][Llama] raw='Female hypogonadism' -> canonical='hypogonadism' -> id='MONDO_0002146'
[map][disease][Llama] raw='Gastrointestinal stromal tumour' -> canonical='GIST-plus syndrome' -> id='EFO_0010279'
[map][disease][Llama] raw='Gastrotintestinal stromal tumor' -> canonical='GIST-plus syndrome' -> id='EFO_0010279'
[map][disease][Llama] raw='Glaucoma/ocular hypertension' -> canonical='glaucoma' -> id='MONDO_0005041'
[map][disease][Llama] raw='Gonorrheal vaginitis' -> canonical='gonorrhea' -> id='DOID_7551'
[map][disease][Llama] raw='HCV 1-6 infection' -> canonical='hepatitis C virus infection' -> id='EFO_0003047'
[map][disease][Llama] raw='Hairy cell leukaemia' -> canonical='hairy cell leukemia' -> id='EFO_1000956'
[map][disease][Llama] raw='Herpes simplex virus infection' -> canonical='Herpes simplex infection' -> id='EFO_1002022'
[map][disease][Llama] raw='Hookworm disease' -> canonical='hookworm infectious disease' -> id='EFO_0007314'
[map][disease][Llama] raw='Human echinococcosis' -> canonical='echinococcosis' -> id='EFO_0007245'
[map][disease][Llama] raw='Hypercholesterolaemia' -> canonical='Hypercholesterolemia' -> id='HP_0003124'
[map][disease][Llama] raw='Idiopathic generalized epilepsies' -> canonical='epilepsy' -> id='EFO_0000474'
[map][disease][Llama] raw='Idiopathic parkinson disease' -> canonical='Parkinson disease' -> id='MONDO_0005180'
[map][disease][Llama] raw='LennoxGastaut syndrome' -> canonical='Lennox-Gastaut syndrome' -> id='MONDO_0016532'
[map][disease][Llama] raw='Malignant essential hypertension' -> canonical='hypertension' -> id='EFO_0000537'
[map][disease][Llama] raw='Menopausal and postmenopausal disorder' -> canonical='menopause' -> id='GO_0042697'
[map][disease][Llama] raw='Multi-drug resistant tuberculosis' -> canonical='tuberculosis' -> id='MONDO_0018076'
[map][disease][Llama] raw='Myeloid leukaemia' -> canonical='myeloid leukemia' -> id='MONDO_0004643'
[map][disease][Llama] raw='Non-small-cell lung cancer' -> canonical='non-small cell lung carcinoma' -> id='EFO_0003060'
[map][disease][Llama] raw='Parkinsonian syndrome' -> canonical='Parkinson disease' -> id='MONDO_0005180'
[map][disease][Llama] raw='Peripheral T cell lymphoma' -> canonical='mature T-cell and NK-cell non-Hodgkin lymphoma' -> id='MONDO_0000430'
[map][disease][Llama] raw='Polymyositis and dermatomyositis' -> canonical='polymyositis' -> id='EFO_0003063'
[map][disease][Llama] raw='Premature labour' -> canonical='premature birth' -> id='EFO_0003917'
[map][disease][Llama] raw='Psoriatic disorder' -> canonical='psoriasis' -> id='EFO_0000676'
[map][disease][Llama] raw='Recurrent glioblastoma' -> canonical='glioblastoma multiforme' -> id='EFO_0000519'
[map][disease][Llama] raw='Ringworm infection' -> canonical='tinea' -> id='EFO_0007510'
[map][disease][Llama] raw='Senile dementia' -> canonical='Alzheimer disease type 1' -> id='MONDO_0007088'
[map][disease][Llama] raw='Seronegative arthritis' -> canonical='arthritis' -> id='EFO_0005856'
[map][disease][Llama] raw='Small-cell lung cancer' -> canonical='small cell lung carcinoma' -> id='EFO_0000702'
[map][disease][Llama] raw='Smoking dependence' -> canonical='nicotine dependence' -> id='EFO_0003768'
[map][disease][Llama] raw='Soft tissue sarcomas' -> canonical='soft tissue sarcoma' -> id='EFO_1001968'
[map][disease][Llama] raw='Solid tumour/cancer' -> canonical='cancer' -> id='MONDO_0004992'
[map][disease][Llama] raw='Stomach Ulcer' -> canonical='peptic ulcer disease' -> id='MONDO_0004247'
[map][disease][Llama] raw='Thrombocytopenia (THC)' -> canonical='Thrombocytopenia' -> id='HP_0001873'
[map][disease][Llama] raw='Thymic cancer' -> canonical='Thymoma' -> id='EFO_1000581'
[map][disease][Llama] raw='Tic Disorders' -> canonical='tic disorder' -> id='MONDO_0002420'
[map][disease][Llama] raw='Type-1 diabetes' -> canonical='type 1 diabetes mellitus' -> id='MONDO_0005147'
[map][disease][Llama] raw='Type-2 diabetes' -> canonical='type 2 diabetes mellitus' -> id='MONDO_0005148'
[warn] Unresolved diseases after OpenTargets/Llama/OLS: ['Acute pain', 'Allograft rejection', 'Amaurosis Fugax', 'Anabolic metabolism', 'Anaesthesia', 'Anomia', 'Bone metastases', 'Cestodes infection', 'Chronic low back pain', 'Death', 'Dental plaque', 'Diabetic complication', 'Eating Disorders', 'Embolism', 'Erythema nodosum leprosum', 'Gastrointestinal cancer', 'Genetic epileptic syndromes with variable age of onset', 'Haematological malignancy', 'Headache Disorders', 'Hemifacial Spasm', 'Hiccup', 'Hormone deficiency', 'Lung Injury', 'Mammary analogue secretory carcinoma', 'Meningioma metastases', 'Menopause symptom', 'Metastatic biliary tract neoplasms', 'Metastatic gastric or gastroesophageal junction cancer', 'Mononeuropathies', 'Morning Sickness', 'Neoplasms', 'Neoplastic meningitis', 'Ocular allergy', 'Paresis', 'Pica', 'Premenstrual Syndrome', 'Prion Diseases', 'Radioactive tracer', 'Reperfusion Injury', 'Rift Valley Fever', 'Skin imperfections', 'Squamous head and neck cell carcinom', 'Status epilepticus seizure', 'Testosterone deficiency', 'Tinea corporis', 'Tinea cruris', 'Trematode infection', 'Vertigo meniere disease', 'Vitamin K deficiency']

             disease_name     disease_id       source
0            5q- syndrome  MONDO_0007925  OpenTargets
1         Absence seizure  MONDO_0010826  OpenTargets
2    Acid-reflux disorder    EFO_0003948        Llama
3                Acidosis    EFO_1000014  OpenTargets
4           Acne vulgaris    EFO_0003894  OpenTargets
..                    ...            ...          ...
556         West syndrome  MONDO_0018097  OpenTargets
557        Wilson disease  MONDO_0010200  OpenTargets
558        Worm infection    EFO_1001342  OpenTargets
559            Xerostomia    EFO_0009869  OpenTargets
560             leukaemia  MONDO_0004355  OpenTargets

[561 rows x 3 columns]

In [15]:
df_disease["source"].value_counts()

source
OpenTargets    466
Llama           46
Name: count, dtype: int64

In [16]:
df_disease[df_disease.isna().any(axis=1)]

                                          disease_name disease_id source
16                                          Acute pain       None   None
25                                 Allograft rejection       None   None
28                                     Amaurosis Fugax       None   None
34                                 Anabolic metabolism       None   None
35                                         Anaesthesia       None   None
43                                              Anomia       None   None
78                                     Bone metastases       None   None
100                                 Cestodes infection       None   None
105                              Chronic low back pain       None   None
140                                              Death       None   None
144                                      Dental plaque       None   None
151                              Diabetic complication       None   None
169                                   Eating Disorders       None   None
173                                           Embolism       None   None
189                          Erythema nodosum leprosum       None   None
208                            Gastrointestinal cancer       None   None
215  Genetic epileptic syndromes with variable age ...       None   None
228                          Haematological malignancy       None   None
233                                 Headache Disorders       None   None
236                                   Hemifacial Spasm       None   None
245                                             Hiccup       None   None
249                                 Hormone deficiency       None   None
307                                        Lung Injury       None   None
318               Mammary analogue secretory carcinoma       None   None
325                              Meningioma metastases       None   None
327                                  Menopause symptom       None   None
332                 Metastatic biliary tract neoplasms       None   None
334  Metastatic gastric or gastroesophageal junctio...       None   None
339                                   Mononeuropathies       None   None
341                                   Morning Sickness       None   None
371                                          Neoplasms       None   None
372                              Neoplastic meningitis       None   None
390                                     Ocular allergy       None   None
404                                            Paresis       None   None
416                                               Pica       None   None
431                              Premenstrual Syndrome       None   None
436                                     Prion Diseases       None   None
453                                 Radioactive tracer       None   None
459                                 Reperfusion Injury       None   None
470                                  Rift Valley Fever       None   None
484                                 Skin imperfections       None   None
495               Squamous head and neck cell carcinom       None   None
497                         Status epilepticus seizure       None   None
510                            Testosterone deficiency       None   None
523                                     Tinea corporis       None   None
524                                       Tinea cruris       None   None
529                                Trematode infection       None   None
548                            Vertigo meniere disease       None   None
551                               Vitamin K deficiency       None   None

In [17]:
# ------------------------------------------------------------------
# Disease canonical audit (OpenTargets-strict IDs only)
# ------------------------------------------------------------------
# IMPORTANT:
# - This cell runs an additional Llama canonicalization pass over unresolved rows.
# - IDs are still resolved ONLY via OpenTargets mapIds (score==1).
# - To avoid changing the baseline resolver output, writeback is OFF by default.
APPLY_AUDIT_MAPPINGS = False

# 1) Rows unresolved after primary resolver
unresolved_rows = df_disease[df_disease["disease_id"].isna()].reset_index(drop=True)
unresolved_raw_names = list(
    dict.fromkeys(
        str(name).strip()
        for name in unresolved_rows["disease_name"].dropna().astype(str).tolist()
        if str(name).strip()
    )
)

# 2) Llama canonicalization suggestions
disease_input_map = {name: None for name in unresolved_raw_names}
canonicalisation_map = await utility.canonicalise_disease_dict(disease_input_map)

# 3) OpenTargets strict verification (score==1 only)
canonical_terms_norm = list(
    dict.fromkeys(
        utility._normalize_disease_term(v)
        for v in canonicalisation_map.values()
        if isinstance(v, str) and v.strip()
    )
)
canonical_to_id = utility.resolve_diseases_opentargets_bulk(
    canonical_terms_norm,
    strict_score_one=True,
)

# 4) Build persistent audit table
audit_rows = []
applied_count = 0
candidate_count = 0

for raw_disease_name in unresolved_raw_names:
    canonical_name = canonicalisation_map.get(raw_disease_name)
    if isinstance(canonical_name, str) and canonical_name.strip():
        canonical_name = canonical_name.strip()
        canonical_norm = utility._normalize_disease_term(canonical_name)
        resolved_id = canonical_to_id.get(canonical_norm)
    else:
        canonical_name = None
        canonical_norm = None
        resolved_id = None

    can_apply = bool(resolved_id)
    if can_apply:
        candidate_count += 1
        print(f"[audit][disease][Llama->OT] raw='{raw_disease_name}' -> canonical='{canonical_name}' -> id='{resolved_id}'")

    if can_apply and APPLY_AUDIT_MAPPINGS:
        mask = df_disease["disease_name"].astype(str).str.strip() == raw_disease_name
        df_disease.loc[mask, "disease_id"] = resolved_id
        df_disease.loc[mask, "source"] = "Llama"
        applied_count += 1

    status = (
        "mappable_ot_exact" if can_apply else
        ("no_canonical" if canonical_name is None else "canonical_not_in_ot")
    )
    audit_rows.append({
        "raw_disease_name": raw_disease_name,
        "canonical_name": canonical_name,
        "canonical_norm": canonical_norm,
        "resolved_disease_id": resolved_id,
        "status": status,
        "can_apply": can_apply,
        "applied": bool(can_apply and APPLY_AUDIT_MAPPINGS),
    })

disease_canonical_audit_df = pd.DataFrame(audit_rows)
if not disease_canonical_audit_df.empty:
    disease_canonical_audit_df = disease_canonical_audit_df.sort_values(
        ["status", "raw_disease_name"],
        ascending=[True, True],
    ).reset_index(drop=True)

print(f"[summary][disease][audit] OT-mappable candidates: {candidate_count}")
print(f"[summary][disease][audit] applied to df_disease: {applied_count} (APPLY_AUDIT_MAPPINGS={APPLY_AUDIT_MAPPINGS})")
if not disease_canonical_audit_df.empty:
    print("[summary][disease][audit] status counts:")
    print(disease_canonical_audit_df["status"].value_counts(dropna=False))

disease_canonical_audit_df

2026-02-27 18:24:18,185 [INFO] [LLM] Total 49 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:24:18,186 [INFO] [LLM] Batch size: 49
2026-02-27 18:24:19,350 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:24:19,352 [INFO] [LLM] Batch done in 1.17s
2026-02-27 18:24:19,353 [INFO] [LLM] 'Acute pain' → None
2026-02-27 18:24:19,354 [INFO] [LLM] 'Allograft rejection' → 'allograft rejection'
2026-02-27 18:24:19,354 [INFO] [LLM] 'Amaurosis Fugax' → 'amaurosis fugax'
2026-02-27 18:24:19,355 [INFO] [LLM] 'Anabolic metabolism' → None
2026-02-27 18:24:19,355 [INFO] [LLM] 'Anaesthesia' → None
2026-02-27 18:24:19,356 [INFO] [LLM] 'Anomia' → None
2026-02-27 18:24:19,356 [INFO] [LLM] 'Bone metastases' → None
2026-02-27 18:24:19,357 [INFO] [LLM] 'Cestodes infection' → None
2026-02-27 18:24:19,357 [INFO] [LLM] 'Chronic low back pain' → None
2026-02-27 18:24:19,358 [INFO] [LLM] 'Death' → None
2026-02-27 18:24:19,358 [INFO] [LLM] 'Dental plaque' → None
2026-02-27 18:24:19,359 [INFO] [LLM] 'Diabetic complication' → None
2026-02-27 18:24:19,359 [INFO] [LLM] 'Eating Disorders' → None
2026-02-27 18:24:19,360 [INFO] [LLM] 'Embolism' → None
2026-02-27 18:24:19,360 [INFO] [LLM] 'Erythema nodosum leprosum' → 'erythema nodosum leprosum'
2026-02-27 18:24:19,360 [INFO] [LLM] 'Gastrointestinal cancer' → None
2026-02-27 18:24:19,361 [INFO] [LLM] 'Genetic epileptic syndromes with variable age of onset' → None
2026-02-27 18:24:19,361 [INFO] [LLM] 'Haematological malignancy' → None
2026-02-27 18:24:19,361 [INFO] [LLM] 'Headache Disorders' → None
2026-02-27 18:24:19,362 [INFO] [LLM] 'Hemifacial Spasm' → 'hemifacial spasm'
2026-02-27 18:24:19,362 [INFO] [LLM] 'Hiccup' → None
2026-02-27 18:24:19,364 [INFO] [LLM] 'Hormone deficiency' → None
2026-02-27 18:24:19,364 [INFO] [LLM] 'Lung Injury' → None
2026-02-27 18:24:19,364 [INFO] [LLM] 'Mammary analogue secretory carcinoma' → 'mammary analogue secretory carcinoma'
2026-02-27 18:24:19,365 [INFO] [LLM] 'Meningioma metastases' → None
2026-02-27 18:24:19,365 [INFO] [LLM] 'Menopause symptom' → None
2026-02-27 18:24:19,366 [INFO] [LLM] 'Metastatic biliary tract neoplasms' → None
2026-02-27 18:24:19,366 [INFO] [LLM] 'Metastatic gastric or gastroesophageal junction cancer' → None
2026-02-27 18:24:19,366 [INFO] [LLM] 'Mononeuropathies' → None
2026-02-27 18:24:19,367 [INFO] [LLM] 'Morning Sickness' → None
2026-02-27 18:24:19,367 [INFO] [LLM] 'Neoplasms' → None
2026-02-27 18:24:19,368 [INFO] [LLM] 'Neoplastic meningitis' → 'neoplastic meningitis'
2026-02-27 18:24:19,368 [INFO] [LLM] 'Ocular allergy' → None
2026-02-27 18:24:19,368 [INFO] [LLM] 'Paresis' → None
2026-02-27 18:24:19,369 [INFO] [LLM] 'Pica' → 'pica'
2026-02-27 18:24:19,369 [INFO] [LLM] 'Premenstrual Syndrome' → 'premenstrual syndrome'
2026-02-27 18:24:19,369 [INFO] [LLM] 'Prion Diseases' → 'prion disease'
2026-02-27 18:24:19,370 [INFO] [LLM] 'Radioactive tracer' → None
2026-02-27 18:24:19,370 [INFO] [LLM] 'Reperfusion Injury' → 'reperfusion injury'
2026-02-27 18:24:19,370 [INFO] [LLM] 'Rift Valley Fever' → 'rift valley fever'
2026-02-27 18:24:19,371 [INFO] [LLM] 'Skin imperfections' → None
2026-02-27 18:24:19,371 [INFO] [LLM] 'Squamous head and neck cell carcinom' → 'squamous cell carcinoma of head and neck'
2026-02-27 18:24:19,372 [INFO] [LLM] 'Status epilepticus seizure' → 'status epilepticus'
2026-02-27 18:24:19,373 [INFO] [LLM] 'Testosterone deficiency' → None
2026-02-27 18:24:19,373 [INFO] [LLM] 'Tinea corporis' → 'tinea corporis'
2026-02-27 18:24:19,374 [INFO] [LLM] 'Tinea cruris' → 'tinea cruris'
2026-02-27 18:24:19,374 [INFO] [LLM] 'Trematode infection' → None
2026-02-27 18:24:19,375 [INFO] [LLM] 'Vertigo meniere disease' → 'meniere disease'
2026-02-27 18:24:19,376 [INFO] [LLM] 'Vitamin K deficiency' → None
2026-02-27 18:24:19,376 [INFO] [OT] Verifying 16 unique suggestions...
2026-02-27 18:24:19,782 [INFO] [OT] 'prion disease' → 'prion disease' (EFO_0004720)
2026-02-27 18:24:19,783 [INFO] [OT] 'squamous cell carcinoma of head and neck' → 'head and neck squamous cell carcinoma' (EFO_0000181)
2026-02-27 18:24:19,783 [INFO] [OT] 'status epilepticus' → 'status epilepticus' (EFO_0008526)
2026-02-27 18:24:19,784 [INFO] [OT] 'meniere disease' → 'Meniere disease' (EFO_0006862)
2026-02-27 18:24:19,785 [INFO] Done: 4 / 49 confirmed | 45 → None

[audit][disease][Llama->OT] raw='Prion Diseases' -> canonical='prion disease' -> id='EFO_0004720'
[audit][disease][Llama->OT] raw='Squamous head and neck cell carcinom' -> canonical='head and neck squamous cell carcinoma' -> id='EFO_0000181'
[audit][disease][Llama->OT] raw='Status epilepticus seizure' -> canonical='status epilepticus' -> id='EFO_0008526'
[audit][disease][Llama->OT] raw='Vertigo meniere disease' -> canonical='Meniere disease' -> id='EFO_0006862'
[summary][disease][audit] OT-mappable candidates: 4
[summary][disease][audit] applied to df_disease: 0 (APPLY_AUDIT_MAPPINGS=False)
[summary][disease][audit] status counts:
status
no_canonical         45
mappable_ot_exact     4
Name: count, dtype: int64

,raw_disease_name,canonical_name,canonical_norm,resolved_disease_id,status,can_apply,applied
0,Prion Diseases,prion disease,prion disease,EFO_0004720,mappable_ot_exact,True,False
1,Squamous head and neck cell carcinom,head and neck squamous cell carcinoma,head and neck squamous cell carcinoma,EFO_0000181,mappable_ot_exact,True,False
2,Status epilepticus seizure,status epilepticus,status epilepticus,EFO_0008526,mappable_ot_exact,True,False
3,Vertigo meniere disease,Meniere disease,meniere disease,EFO_0006862,mappable_ot_exact,True,False
4,Acute pain,None,None,None,no_canonical,False,False
5,Allograft rejection,None,None,None,no_canonical,False,False
6,Amaurosis Fugax,None,None,None,no_canonical,False,False
7,Anabolic metabolism,None,None,None,no_canonical,False,False
8,Anaesthesia,None,None,None,no_canonical,False,False
9,Anomia,None,None,None,no_canonical,False,False
10,Bone metastases,None,None,None,no_canonical,False,False
11,Cestodes infection,None,None,None,no_canonical,False,False
12,Chronic low back pain,None,None,None,no_canonical,False,False
13,Death,None,None,None,no_canonical,False,False
14,Dental plaque,None,None,None,no_canonical,False,False
15,Diabetic complication,None,None,None,no_canonical,False,False
16,Eating Disorders,None,None,None,no_canonical,False,False
17,Embolism,None,None,None,no_canonical,False,False
18,Erythema nodosum leprosum,None,None,None,no_canonical,False,False
19,Gastrointestinal cancer,None,None,None,no_canonical,False,False
20,Genetic epileptic syndromes with variable age ...,None,None,None,no_canonical,False,False
21,Haematological malignancy,None,None,None,no_canonical,False,False
22,Headache Disorders,None,None,None,no_canonical,False,False
23,Hemifacial Spasm,None,None,None,no_canonical,False,False
24,Hiccup,None,None,None,no_canonical,False,False
25,Hormone deficiency,None,None,None,no_canonical,False,False
26,Lung Injury,None,None,None,no_canonical,False,False
27,Mammary analogue secretory carcinoma,None,None,None,no_canonical,False,False
28,Meningioma metastases,None,None,None,no_canonical,False,False
29,Menopause symptom,None,None,None,no_canonical,False,False
30,Metastatic biliary tract neoplasms,None,None,None,no_canonical,False,False
31,Metastatic gastric or gastroesophageal junctio...,None,None,None,no_canonical,False,False
32,Mononeuropathies,None,None,None,no_canonical,False,False
33,Morning Sickness,None,None,None,no_canonical,False,False
34,Neoplasms,None,None,None,no_canonical,False,False
35,Neoplastic meningitis,None,None,None,no_canonical,False,False
36,Ocular allergy,None,None,None,no_canonical,False,False
37,Paresis,None,None,None,no_canonical,False,False
38,Pica,None,None,None,no_canonical,False,False
39,Premenstrual Syndrome,None,None,None,no_canonical,False,False
40,Radioactive tracer,None,None,None,no_canonical,False,False
41,Reperfusion Injury,None,None,None,no_canonical,False,False
42,Rift Valley Fever,None,None,None,no_canonical,False,False
43,Skin imperfections,None,None,None,no_canonical,False,False
44,Testosterone deficiency,None,None,None,no_canonical,False,False
45,Tinea corporis,None,None,None,no_canonical,False,False
46,Tinea cruris,None,None,None,no_canonical,False,False
47,Trematode infection,None,None,None,no_canonical,False,False
48,Vitamin K deficiency,None,None,None,no_canonical,False,False

In [18]:
# disease_canonical_audit_df

In [19]:
df_disease[df_disease["source"]=='Llama']

                                        disease_name     disease_id source
2                               Acid-reflux disorder    EFO_0003948  Llama
11                               Acute heart failure    EFO_0003144  Llama
12                     Acute lymphoblastic leukaemia    EFO_0000220  Llama
33               Amyotrophic lateral sclerosis (ALS)  MONDO_0004976  Llama
37                    Anaplastic large-cell lymphoma    EFO_0003032  Llama
62   Attention deficit hyperactivity disorder (ADHD)    EFO_0003888  Llama
124                 Congestive cardiac insufficiency    EFO_0003144  Llama
190                        Erythropoietic porphyrias  MONDO_0037939  Llama
196                              Female hypogonadism  MONDO_0002146  Llama
210                  Gastrointestinal stromal tumour    EFO_0010279  Llama
212                  Gastrotintestinal stromal tumor    EFO_0010279  Llama
218                     Glaucoma/ocular hypertension  MONDO_0005041  Llama
220                             Gonorrheal vaginitis      DOID_7551  Llama
227                                HCV 1-6 infection    EFO_0003047  Llama
229                             Hairy cell leukaemia    EFO_1000956  Llama
244                   Herpes simplex virus infection    EFO_1002022  Llama
248                                 Hookworm disease    EFO_0007314  Llama
250                             Human echinococcosis    EFO_0007245  Llama
255                            Hypercholesterolaemia     HP_0003124  Llama
275                Idiopathic generalized epilepsies    EFO_0000474  Llama
276                     Idiopathic parkinson disease  MONDO_0005180  Llama
299                           LennoxGastaut syndrome  MONDO_0016532  Llama
316                 Malignant essential hypertension    EFO_0000537  Llama
326           Menopausal and postmenopausal disorder     GO_0042697  Llama
344                Multi-drug resistant tuberculosis  MONDO_0018076  Llama
357                                Myeloid leukaemia  MONDO_0004643  Llama
386                       Non-small-cell lung cancer    EFO_0003060  Llama
406                            Parkinsonian syndrome  MONDO_0005180  Llama
412                       Peripheral T cell lymphoma  MONDO_0000430  Llama
424                 Polymyositis and dermatomyositis    EFO_0003063  Llama
429                                 Premature labour    EFO_0003917  Llama
442                               Psoriatic disorder    EFO_0000676  Llama
456                           Recurrent glioblastoma    EFO_0000519  Llama
471                               Ringworm infection    EFO_0007510  Llama
480                                  Senile dementia  MONDO_0007088  Llama
482                           Seronegative arthritis    EFO_0005856  Llama
487                           Small-cell lung cancer    EFO_0000702  Llama
488                               Smoking dependence    EFO_0003768  Llama
490                             Soft tissue sarcomas    EFO_1001968  Llama
491                              Solid tumour/cancer  MONDO_0004992  Llama
499                                    Stomach Ulcer  MONDO_0004247  Llama
515                           Thrombocytopenia (THC)     HP_0001873  Llama
517                                    Thymic cancer    EFO_1000581  Llama
520                                    Tic Disorders  MONDO_0002420  Llama
535                                  Type-1 diabetes  MONDO_0005147  Llama
536                                  Type-2 diabetes  MONDO_0005148  Llama

In [20]:
df_disease["source"].value_counts()

source
OpenTargets    466
Llama           46
Name: count, dtype: int64

In [21]:
df_disease

             disease_name     disease_id       source
0            5q- syndrome  MONDO_0007925  OpenTargets
1         Absence seizure  MONDO_0010826  OpenTargets
2    Acid-reflux disorder    EFO_0003948        Llama
3                Acidosis    EFO_1000014  OpenTargets
4           Acne vulgaris    EFO_0003894  OpenTargets
..                    ...            ...          ...
556         West syndrome  MONDO_0018097  OpenTargets
557        Wilson disease  MONDO_0010200  OpenTargets
558        Worm infection    EFO_1001342  OpenTargets
559            Xerostomia    EFO_0009869  OpenTargets
560             leukaemia  MONDO_0004355  OpenTargets

[561 rows x 3 columns]

In [22]:
df_disease[df_disease["source"]=="Llama"]

                                        disease_name     disease_id source
2                               Acid-reflux disorder    EFO_0003948  Llama
11                               Acute heart failure    EFO_0003144  Llama
12                     Acute lymphoblastic leukaemia    EFO_0000220  Llama
33               Amyotrophic lateral sclerosis (ALS)  MONDO_0004976  Llama
37                    Anaplastic large-cell lymphoma    EFO_0003032  Llama
62   Attention deficit hyperactivity disorder (ADHD)    EFO_0003888  Llama
124                 Congestive cardiac insufficiency    EFO_0003144  Llama
190                        Erythropoietic porphyrias  MONDO_0037939  Llama
196                              Female hypogonadism  MONDO_0002146  Llama
210                  Gastrointestinal stromal tumour    EFO_0010279  Llama
212                  Gastrotintestinal stromal tumor    EFO_0010279  Llama
218                     Glaucoma/ocular hypertension  MONDO_0005041  Llama
220                             Gonorrheal vaginitis      DOID_7551  Llama
227                                HCV 1-6 infection    EFO_0003047  Llama
229                             Hairy cell leukaemia    EFO_1000956  Llama
244                   Herpes simplex virus infection    EFO_1002022  Llama
248                                 Hookworm disease    EFO_0007314  Llama
250                             Human echinococcosis    EFO_0007245  Llama
255                            Hypercholesterolaemia     HP_0003124  Llama
275                Idiopathic generalized epilepsies    EFO_0000474  Llama
276                     Idiopathic parkinson disease  MONDO_0005180  Llama
299                           LennoxGastaut syndrome  MONDO_0016532  Llama
316                 Malignant essential hypertension    EFO_0000537  Llama
326           Menopausal and postmenopausal disorder     GO_0042697  Llama
344                Multi-drug resistant tuberculosis  MONDO_0018076  Llama
357                                Myeloid leukaemia  MONDO_0004643  Llama
386                       Non-small-cell lung cancer    EFO_0003060  Llama
406                            Parkinsonian syndrome  MONDO_0005180  Llama
412                       Peripheral T cell lymphoma  MONDO_0000430  Llama
424                 Polymyositis and dermatomyositis    EFO_0003063  Llama
429                                 Premature labour    EFO_0003917  Llama
442                               Psoriatic disorder    EFO_0000676  Llama
456                           Recurrent glioblastoma    EFO_0000519  Llama
471                               Ringworm infection    EFO_0007510  Llama
480                                  Senile dementia  MONDO_0007088  Llama
482                           Seronegative arthritis    EFO_0005856  Llama
487                           Small-cell lung cancer    EFO_0000702  Llama
488                               Smoking dependence    EFO_0003768  Llama
490                             Soft tissue sarcomas    EFO_1001968  Llama
491                              Solid tumour/cancer  MONDO_0004992  Llama
499                                    Stomach Ulcer  MONDO_0004247  Llama
515                           Thrombocytopenia (THC)     HP_0001873  Llama
517                                    Thymic cancer    EFO_1000581  Llama
520                                    Tic Disorders  MONDO_0002420  Llama
535                                  Type-1 diabetes  MONDO_0005147  Llama
536                                  Type-2 diabetes  MONDO_0005148  Llama

In [23]:
def compute_jaccard_from_run_dataframes(dct_result, df_gene, df_disease, df_drug):
    """
    Compute per-question cross-run Jaccard consistency after mapping entities to IDs.

    For each (model, question):
    - intersection: entries present in ALL valid runs
    - union: entries present in ANY valid run
    - jaccard = |intersection| / |union|

    All comparisons are CASE-INDEPENDENT and ID-based.

    Side effects:
    - Stores per-run mapped dataframe in:
        dct_result[model][question][run]['dataframe_id']

    Returns:
    - dct_jaccard[model][question] = {
          'jaccard': float,
          'n_valid_runs': int,
          'intersection': set[tuple],
          'union': set[tuple],
      }
    """

    dct_jaccard = {}

    # ------------------------------------------------------------------
    # Build deterministic one-to-one mapping tables
    # ------------------------------------------------------------------
    gene_map = (
        df_gene.assign(_gene_norm=df_gene["gene_name"].astype(str).str.strip().str.upper())
        [["_gene_norm", "gene_id"]]
        .dropna(subset=["gene_id"])
        .drop_duplicates("_gene_norm", keep="first")
    )

    disease_map = (
        df_disease.assign(_disease_norm=df_disease["disease_name"].astype(str).str.strip().str.upper())
        [["_disease_norm", "disease_id"]]
        .dropna(subset=["disease_id"])
        .drop_duplicates("_disease_norm", keep="first")
    )

    drug_map = (
        df_drug.assign(_drug_norm=df_drug["drug_name"].astype(str).str.strip().str.upper())
        [["_drug_norm", "drug_id"]]
        .dropna(subset=["drug_id"])
        .drop_duplicates("_drug_norm", keep="first")
    )

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    for model, model_payload in dct_result.items():
        dct_jaccard[model] = {}
        print(f"\nWorking for model: {model}")

        for question_key, runs_dict in model_payload.items():
            run_sets = {}

            for run_number, run_payload in runs_dict.items():
                df = run_payload.get("dataframe")

                # ---- basic validity ----
                if not isinstance(df, pd.DataFrame) or df.empty:
                    continue

                if "pathway_name" in df.columns:
                    continue

                work_df = df.copy()

                # print(work_df.head())

                final_cols = []

                # ---- gene ----
                if "gene_name" in work_df.columns:
                    work_df["_gene_norm"] = (
                        work_df["gene_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(gene_map, on="_gene_norm", how="left")
                    final_cols.append("gene_id")

                # ---- disease ----
                if "disease_name" in work_df.columns:
                    work_df["_disease_norm"] = (
                        work_df["disease_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(disease_map, on="_disease_norm", how="left")
                    final_cols.append("disease_id")

                # ---- drug ----
                if "drug_name" in work_df.columns:
                    work_df["_drug_norm"] = (
                        work_df["drug_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(drug_map, on="_drug_norm", how="left")
                    final_cols.append("drug_id")

                if not final_cols:
                    continue

                # ---- canonical ID dataframe ----
                id_df = (
                    work_df[final_cols]
                    .dropna(how="any")
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

                dct_result[model][question_key][run_number]["dataframe_id"] = id_df

                if id_df.empty:
                    continue

                # ---- CASE-INDEPENDENT tuple set ----
                run_set = {
                    tuple(str(v).strip().upper() for v in row)
                    for row in id_df.itertuples(index=False, name=None)
                }

                if run_set:
                    run_sets[run_number] = run_set

            # ------------------------------------------------------------------
            # Compute intersection / union
            # ------------------------------------------------------------------
            n_valid_runs = len(run_sets)

            if n_valid_runs < 2:
                print(
                    f"Not enough valid runs for '{question_key}' "
                    f"({n_valid_runs}/{len(runs_dict)}). Skipping."
                )
                continue

            sets = list(run_sets.values())
            intersection = set.intersection(*sets)
            union = set.union(*sets)

            if not union:
                print(f"Empty union for '{question_key}', skipping.")
                continue

            jaccard = len(intersection) / len(union)

            dct_jaccard[model][question_key] = {
                "jaccard": jaccard,
                "n_valid_runs": n_valid_runs,
                "intersection": intersection,
                "union": union,
            }

            print(
                f"'{question_key}': "
                f"J={jaccard:.4f}, "
                f"|∩|={len(intersection)}, "
                f"|∪|={len(union)}, "
                f"runs={n_valid_runs}"
            )

    return dct_jaccard


dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

Working for model: hcdt
'Which diseases are associated with BRAF?': J=1.0000, |∩|=145, |∪|=145, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=1.0000, |∩|=797, |∪|=797, runs=5
'Which diseases are associated with CDK4?': J=1.0000, |∩|=140, |∪|=140, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=1.0000, |∩|=102, |∪|=102, runs=5
'Which genes are associated with ovarian cancer?': J=1.0000, |∩|=803, |∪|=803, runs=5
'What are the known targets of regorafenib?': J=1.0000, |∩|=69, |∪|=69, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
Not enough valid runs for 'Which genes are associated with fever (pyrexia)?' (0/0). Skipping.
Not enough valid runs for 'Which diseases are treated with bevacizumab?' (0/0). Skipping.
'What are the known targets of cabozantinib?': J=1.0000, |∩|=89, |∪|=89, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=1.0000, |∩|=14, |∪|=14, runs=5
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/0). Skipping.
'Which drugs are used to treat migraine?': J=1.0000, |∩|=34, |∪|=34, runs=5
'What drugs are used to treat rickets?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which genes are associated with epilepsy?': J=0.5114, |∩|=1638, |∪|=3203, runs=5
Not enough valid runs for 'Which diseases are treated with trastuzumab deruxtecan?' (0/0). Skipping.
'Which genes are associated with Alzheimer’s disease?': J=0.9981, |∩|=1060, |∪|=1062, runs=5
'For which diseases is darolutamide used?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with renal cell carcinoma?': J=1.0000, |∩|=581, |∪|=581, runs=5
'Which diseases are associated with the KRAS gene?': J=1.0000, |∩|=64, |∪|=64, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=1.0000, |∩|=868, |∪|=868, runs=5
'Which diseases are treated with valdecoxib?': J=1.0000, |∩|=1, |∪|=1, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=362, |∪|=362, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=1.0000, |∩|=46, |∪|=46, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=1.0000, |∩|=38, |∪|=38, runs=2
'Which drugs are used to treat chronic myeloid leukemia?': J=1.0000, |∩|=18, |∪|=18, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=1.0000, |∩|=84, |∪|=84, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=1.0000, |∩|=61, |∪|=61, runs=5
'Which targets are acted on by imatinib?': J=1.0000, |∩|=411, |∪|=411, runs=5
'Which biological targets does sorafenib interact with?': J=1.0000, |∩|=430, |∪|=430, runs=5
'Which biological targets does tofacitinib interact with?': J=1.0000, |∩|=332, |∪|=332, runs=5
'Which drugs target EGFR?': J=1.0000, |∩|=203, |∪|=203, runs=5
'Which diseases are associated with TP53?': J=1.0000, |∩|=327, |∪|=327, runs=5
'Which diseases are associated with FGFR2?': J=1.0000, |∩|=90, |∪|=90, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=356, |∪|=356, runs=4
'Which genes are associated with breast cancer?': J=1.0000, |∩|=1104, |∪|=1104, runs=5
'Which genes are associated with colorectal cancer?': J=0.9826, |∩|=1188, |∪|=1209, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=423, |∪|=423, runs=5
Not enough valid runs for 'Which drugs are used to treat TNBC?' (0/0). Skipping.
'Which diseases are treated with metformin?': J=1.0000, |∩|=18, |∪|=18, runs=5
Not enough valid runs for 'Which diseases are treated with adalimumab?' (0/0). Skipping.
Not enough valid runs for 'For which diseases is pembrolizumab used?' (0/0). Skipping.
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=6, |∪|=6, runs=5
Not enough valid runs for 'Which diseases are treated with nivolumab?' (0/0). Skipping.
'Which genes are associated with multiple sclerosis?': J=1.0000, |∩|=802, |∪|=802, runs=5
'Which genes are associated with rheumatoid arthritis?': J=1.0000, |∩|=1057, |∪|=1057, runs=5
Not enough valid runs for 'What are the known targets of abatacept?' (0/0). Skipping.
'Which genes are associated with lung cancer?': J=1.0000, |∩|=1794, |∪|=1794, runs=5
'What are the known targets of ponatinib?': J=1.0000, |∩|=124, |∪|=124, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.8333, |∩|=30, |∪|=36, runs=5
'Which genes are associated with autism spectrum disorder?': J=1.0000, |∩|=127, |∪|=127, runs=5
'Which diseases are associated with the ROS1 gene?': J=1.0000, |∩|=69, |∪|=69, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=208, |∪|=208, runs=5
'Which diseases are associated with the EGFR gene?': J=1.0000, |∩|=225, |∪|=225, runs=5
'Which genes are associated with psoriasis?': J=0.6403, |∩|=648, |∪|=1012, runs=5
'Which genes are associated with ulcerative colitis?': J=1.0000, |∩|=223, |∪|=223, runs=5
'Which genes are associated with tuberculosis?': J=1.0000, |∩|=396, |∪|=396, runs=5
'Which genes are associated with hepatitis C?': J=1.0000, |∩|=141, |∪|=141, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=1.0000, |∩|=224, |∪|=224, runs=4
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=1.0000, |∩|=120, |∪|=120, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
Not enough valid runs for 'Which drugs target CD19?' (0/0). Skipping.
'Which drugs target CTLA4?': J=1.0000, |∩|=10, |∪|=10, runs=5

In [24]:
# Run Jaccard consistency computation across runs after ID grounding.
dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

# Flatten into a quick summary table for inspection.
rows = [
    {
        "model": model,
        "question": question,
        "jaccard": payload["jaccard"],
        "n_valid_runs": payload["n_valid_runs"],
        "intersection_size": len(payload["intersection"]),
        "union_size": len(payload["union"]),
    }
    for model, qmap in dct_jaccard.items()
    for question, payload in qmap.items()
]

jaccard_summary = pd.DataFrame(rows)
if jaccard_summary.empty:
    print("No valid Jaccard entries were produced. Check input runs and validation filters.")
else:
    display(jaccard_summary.sort_values(["model", "jaccard"], ascending=[True, False]).head(20))

Working for model: hcdt
'Which diseases are associated with BRAF?': J=1.0000, |∩|=145, |∪|=145, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=1.0000, |∩|=797, |∪|=797, runs=5
'Which diseases are associated with CDK4?': J=1.0000, |∩|=140, |∪|=140, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=1.0000, |∩|=102, |∪|=102, runs=5
'Which genes are associated with ovarian cancer?': J=1.0000, |∩|=803, |∪|=803, runs=5
'What are the known targets of regorafenib?': J=1.0000, |∩|=69, |∪|=69, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
Not enough valid runs for 'Which genes are associated with fever (pyrexia)?' (0/0). Skipping.
Not enough valid runs for 'Which diseases are treated with bevacizumab?' (0/0). Skipping.
'What are the known targets of cabozantinib?': J=1.0000, |∩|=89, |∪|=89, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=1.0000, |∩|=14, |∪|=14, runs=5
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/0). Skipping.
'Which drugs are used to treat migraine?': J=1.0000, |∩|=34, |∪|=34, runs=5
'What drugs are used to treat rickets?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which genes are associated with epilepsy?': J=0.5114, |∩|=1638, |∪|=3203, runs=5
Not enough valid runs for 'Which diseases are treated with trastuzumab deruxtecan?' (0/0). Skipping.
'Which genes are associated with Alzheimer’s disease?': J=0.9981, |∩|=1060, |∪|=1062, runs=5
'For which diseases is darolutamide used?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with renal cell carcinoma?': J=1.0000, |∩|=581, |∪|=581, runs=5
'Which diseases are associated with the KRAS gene?': J=1.0000, |∩|=64, |∪|=64, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=1.0000, |∩|=868, |∪|=868, runs=5
'Which diseases are treated with valdecoxib?': J=1.0000, |∩|=1, |∪|=1, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=362, |∪|=362, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=1.0000, |∩|=46, |∪|=46, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=1.0000, |∩|=38, |∪|=38, runs=2
'Which drugs are used to treat chronic myeloid leukemia?': J=1.0000, |∩|=18, |∪|=18, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=1.0000, |∩|=84, |∪|=84, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=1.0000, |∩|=61, |∪|=61, runs=5
'Which targets are acted on by imatinib?': J=1.0000, |∩|=411, |∪|=411, runs=5
'Which biological targets does sorafenib interact with?': J=1.0000, |∩|=430, |∪|=430, runs=5
'Which biological targets does tofacitinib interact with?': J=1.0000, |∩|=332, |∪|=332, runs=5
'Which drugs target EGFR?': J=1.0000, |∩|=203, |∪|=203, runs=5
'Which diseases are associated with TP53?': J=1.0000, |∩|=327, |∪|=327, runs=5
'Which diseases are associated with FGFR2?': J=1.0000, |∩|=90, |∪|=90, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=356, |∪|=356, runs=4
'Which genes are associated with breast cancer?': J=1.0000, |∩|=1104, |∪|=1104, runs=5
'Which genes are associated with colorectal cancer?': J=0.9826, |∩|=1188, |∪|=1209, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=423, |∪|=423, runs=5
Not enough valid runs for 'Which drugs are used to treat TNBC?' (0/0). Skipping.
'Which diseases are treated with metformin?': J=1.0000, |∩|=18, |∪|=18, runs=5
Not enough valid runs for 'Which diseases are treated with adalimumab?' (0/0). Skipping.
Not enough valid runs for 'For which diseases is pembrolizumab used?' (0/0). Skipping.
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=6, |∪|=6, runs=5
Not enough valid runs for 'Which diseases are treated with nivolumab?' (0/0). Skipping.
'Which genes are associated with multiple sclerosis?': J=1.0000, |∩|=802, |∪|=802, runs=5
'Which genes are associated with rheumatoid arthritis?': J=1.0000, |∩|=1057, |∪|=1057, runs=5
Not enough valid runs for 'What are the known targets of abatacept?' (0/0). Skipping.
'Which genes are associated with lung cancer?': J=1.0000, |∩|=1794, |∪|=1794, runs=5
'What are the known targets of ponatinib?': J=1.0000, |∩|=124, |∪|=124, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.8333, |∩|=30, |∪|=36, runs=5
'Which genes are associated with autism spectrum disorder?': J=1.0000, |∩|=127, |∪|=127, runs=5
'Which diseases are associated with the ROS1 gene?': J=1.0000, |∩|=69, |∪|=69, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=208, |∪|=208, runs=5
'Which diseases are associated with the EGFR gene?': J=1.0000, |∩|=225, |∪|=225, runs=5
'Which genes are associated with psoriasis?': J=0.6403, |∩|=648, |∪|=1012, runs=5
'Which genes are associated with ulcerative colitis?': J=1.0000, |∩|=223, |∪|=223, runs=5
'Which genes are associated with tuberculosis?': J=1.0000, |∩|=396, |∪|=396, runs=5
'Which genes are associated with hepatitis C?': J=1.0000, |∩|=141, |∪|=141, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=1.0000, |∩|=224, |∪|=224, runs=4
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=1.0000, |∩|=120, |∪|=120, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
Not enough valid runs for 'Which drugs target CD19?' (0/0). Skipping.
'Which drugs target CTLA4?': J=1.0000, |∩|=10, |∪|=10, runs=5

,model,question,jaccard,n_valid_runs,intersection_size,union_size
0,hcdt,Which diseases are associated with BRAF?,1.0,5,145,145
1,hcdt,Which genes are associated with amyotrophic la...,1.0,5,797,797
2,hcdt,Which diseases are associated with CDK4?,1.0,5,140,140
3,hcdt,Which drugs are used to treat rheumatoid arthr...,1.0,5,102,102
4,hcdt,Which genes are associated with ovarian cancer?,1.0,5,803,803
5,hcdt,What are the known targets of regorafenib?,1.0,5,69,69
6,hcdt,What are the known targets of cabozantinib?,1.0,5,89,89
7,hcdt,Which diseases are associated with the NPM1 gene?,1.0,5,14,14
8,hcdt,Which drugs are used to treat migraine?,1.0,5,34,34
9,hcdt,What drugs are used to treat rickets?,1.0,5,2,2
12,hcdt,For which diseases is darolutamide used?,1.0,5,1,1
13,hcdt,Which genes are associated with renal cell car...,1.0,5,581,581
14,hcdt,Which diseases are associated with the KRAS gene?,1.0,5,64,64
15,hcdt,Which genes are associated with schizophrenia?,1.0,5,868,868
16,hcdt,Which diseases are treated with valdecoxib?,1.0,5,1,1
17,hcdt,What are the known targets of vandetanib?,1.0,5,362,362
18,hcdt,Which drugs are used to treat tuberculosis?,1.0,5,46,46
19,hcdt,Which drugs are used to treat pancreatic adeno...,1.0,2,38,38
20,hcdt,Which drugs are used to treat chronic myeloid ...,1.0,5,18,18
21,hcdt,Which drugs are used to treat Parkinson’s dise...,1.0,5,84,84

In [25]:
# Persist enriched run payloads with dataframe_id attached for each run.
with open("HCDT_same_question_response_with_id.pkl", "wb") as f:
    pickle.dump(dct_result, f)