In [1]:
import sys
sys.path.append("../")

##### import library

In [2]:
from typing import List, Optional
import requests
import pandas as pd
import mygene
import utility
import importlib
importlib.reload(utility)
from utility import resolve_ensembl_ids_with_fallback, get_chembl_ids_fast,  get_disease_ids_fast, validate_id_dataframe
import pickle

In [3]:
dct_result = dict()

##### Read pickle

In [4]:
with open("CTD_same_question_response_final.pkl", "rb") as f:
    CTD_same_question_response = pickle.load(f)

In [5]:
for model in ['llama-3.3-70b-versatile', 'gpt-5-nano', 'grok-4-1-fast-non-reasoning-latest', "gemini-2.5-flash-lite", "OpenTarget", "BioChatter", "ctd", "ttd", "hcdt"]:

    
    # if model=="llama-3.3-70b-versatile":
    #     dct_result[model] = Llama_same_question_response[model]

    # if model=="gpt-5-nano":
    #     dct_result[model] = OpenAI_same_question_response[model]

    # if model=='grok-4-1-fast-non-reasoning-latest':
    #     dct_result[model] = Grok_same_question_response[model]

    # if model=="gemini-2.5-flash-lite":
    #     dct_result[model] = Gemini_same_question_response[model]

    # if model=="OpenTarget":
    #     dct_result[model] = Opentarget_same_question_response[model]

    # if model=="BioChatter":
    #     dct_result[model] = Biochatter_same_question_response[model]

    if model=="ctd":
        dct_result[model] = CTD_same_question_response[model]

    # if model=="hcdt":
    #     dct_result[model] = HCDT_same_question_response[model]

##### Verify if only valid columns are present

In [6]:
allowed = {"gene_name", "drug_name", "disease_name", "pathway_name"}

missing_df = []
not_dataframe = []
empty_df = []
bad_columns = []

total_payloads = 0

for model, queries in dct_result.items():
    if not isinstance(queries, dict):
        continue

    for question, runs in queries.items():
        if not isinstance(runs, dict):
            continue

        for run_id, payload in runs.items():
            total_payloads += 1

            if not isinstance(payload, dict) or "dataframe" not in payload:
                missing_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "payload_type": type(payload).__name__
                })
                continue

            df = payload.get("dataframe")

            if not isinstance(df, pd.DataFrame):
                not_dataframe.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "df_type": type(df).__name__
                })
                continue

            if df.empty:
                empty_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns)
                })

            cols = {str(c) for c in df.columns}
            extra = sorted(cols - allowed)

            if extra:
                bad_columns.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns),
                    "extra_columns": extra
                })

print(f"Total payloads checked: {total_payloads}")
print(f"Missing dataframe key: {len(missing_df)}")
print(f"Dataframe is not pd.DataFrame: {len(not_dataframe)}")
print(f"Empty dataframes: {len(empty_df)}")
print(f"Dataframes with disallowed columns: {len(bad_columns)}")

bad_columns_df = pd.DataFrame(bad_columns)
missing_df_df = pd.DataFrame(missing_df)
not_dataframe_df = pd.DataFrame(not_dataframe)
empty_df_df = pd.DataFrame(empty_df)

display(bad_columns_df)
display(missing_df_df)
display(not_dataframe_df)
display(empty_df_df)

Total payloads checked: 309
Missing dataframe key: 0
Dataframe is not pd.DataFrame: 0
Empty dataframes: 0
Dataframes with disallowed columns: 0

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [7]:
dct_jaccard = dict()

question_entities = {
    "gene_name": set(),
    "drug_name": set(),
    "disease_name": set(),
}

allowed_cols = {"gene_name", "drug_name", "disease_name"}

for model, queries in dct_result.items():
    dct_jaccard[model] = {}
    print(f"\nWorking for model: {model}")

    for question, runs in queries.items():

        for run_id, payload in runs.items():
            df = payload.get("dataframe")

            # ---- validation ----
            if not isinstance(df, pd.DataFrame) or df.empty:
                continue

            # ---- skip pathway outputs ----
            if "pathway_name" in df.columns:
                continue

            # ---- column sanity ----
            if not set(df.columns).issubset(allowed_cols):
                continue

            # ---- collect entities globally ----
            for col in allowed_cols:
                if col in df.columns:
                    values = (
                        df[col]
                        .dropna()
                        .astype(str)
                        .str.strip()
                        .tolist()
                    )
                    question_entities[col].update(values)

# ---- finalize (sets → sorted lists) ----
for k in question_entities:
    question_entities[k] = sorted(question_entities[k])

Working for model: ctd

##### Associate id with all gene entry

In [8]:
# Resolve unique gene symbols to IDs (MyGene -> OpenTargets fallback).
df_gene = resolve_ensembl_ids_with_fallback(
    list(question_entities["gene_name"]),
    use_opentargets_fallback=True,
)
df_gene = df_gene.drop_duplicates(subset=["gene_name", "gene_id"]).reset_index(drop=True)
df_gene

2026-02-27 17:43:28,757 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 17:43:28,758 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 17:43:28,759 [INFO] querying 1-1000 ...
2026-02-27 17:43:31,202 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 17:43:32,209 [INFO] querying 1001-2000 ...
2026-02-27 17:43:33,560 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 17:43:34,566 [INFO] querying 2001-2047 ...
2026-02-27 17:43:34,876 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 17:43:35,879 [INFO] Finished.
2026-02-27 17:43:36,011 [WARNING] 5 input query terms found dup hits:	[('CMAHP', 2), ('CTSLP8', 2), ('MNX1-AS1', 2), ('SNHG14', 2), ('VNN3P', 2)]
2026-02-27 17:43:36,012 [WARNING] 29 input query terms found no hit:	['ABCB1A', 'ABCB1B', 'ABL', 'ARSE', 'ATP6', 'ATP7', 'COX1', 'COX3', 'CTR1B', 'CTR1C', 'CYP2B1', 'GPI

[warn] Could not resolve 'ABCB1A' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ABCB1B' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ATP7' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'CTR1B' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'CTR1C' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'CYP2B1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'DISC2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'H1F10' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MIR124A-3' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MIR181B-1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'RETNLG' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SERPINA3M' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SERPINA3N' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SLCO1A5' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SNAR-I' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'TIMM8A1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.

     gene_name          gene_id  source
0         A1BG  ENSG00000121410  mygene
1          A2M  ENSG00000175899  mygene
2        AARS1  ENSG00000090861  mygene
3         ABAT  ENSG00000183044  mygene
4        ABCA2  ENSG00000107331  mygene
...        ...              ...     ...
2042    ZNF565  ENSG00000196357  mygene
2043    ZNF765  ENSG00000196417  mygene
2044   ZNF804A  ENSG00000170396  mygene
2045    ZNF816  ENSG00000180257  mygene
2046   ZSCAN31  ENSG00000235109  mygene

[2047 rows x 3 columns]

In [9]:
df_gene[df_gene.isna().any(axis=1)]

      gene_name gene_id source
9        ABCB1A     NaN   None
10       ABCB1B     NaN   None
182        ATP7     NaN   None
462       CTR1B     NaN   None
463       CTR1C     NaN   None
498      CYP2B1     NaN   None
562       DISC2     NaN   None
847       H1F10     NaN   None
1180  MIR124A-3     NaN   None
1188  MIR181B-1     NaN   None
1587     RETNLG     NaN   None
1671  SERPINA3M     NaN   None
1672  SERPINA3N     NaN   None
1750    SLCO1A5     NaN   None
1764     SNAR-I     NaN   None
1876    TIMM8A1     NaN   None

##### Associate id with all drug entry

In [10]:
# Resolve unique drug surface forms to IDs.
# This keeps original raw names as rows and writes mapped ID + source.
df_drug = await get_chembl_ids_fast(list(question_entities["drug_name"]))
df_drug = df_drug.drop_duplicates(subset=["drug_name", "drug_id"]).reset_index(drop=True)
df_drug

2026-02-27 17:45:02,983 [INFO] [LLM] Total 573 names split into 8 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 17:45:02,987 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,032 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,036 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,039 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,040 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,040 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,041 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:03,041 [INFO] [LLM] Batch size: 13

[map][drug][OpenTargets] raw='10-nitro-oleic acid' -> id='CHEMBL561371'
[map][drug][OpenTargets] raw='2-Methoxyestradiol' -> id='CHEMBL299613'
[map][drug][OpenTargets] raw='3-methyladenine' -> id='CHEMBL292268'
[map][drug][OpenTargets] raw='Acetaminophen' -> id='CHEMBL112'
[map][drug][OpenTargets] raw='Acetazolamide' -> id='CHEMBL20'
[map][drug][OpenTargets] raw='Acetic Acid' -> id='CHEMBL539'
[map][drug][OpenTargets] raw='Acetylcysteine' -> id='CHEMBL600'
[map][drug][OpenTargets] raw='Adenosine Triphosphate' -> id='CHEMBL14249'
[map][drug][OpenTargets] raw='Ado-Trastuzumab Emtansine' -> id='CHEMBL1743082'
[map][drug][OpenTargets] raw='Adrenocorticotropic Hormone' -> id='CHEMBL1201610'
[map][drug][OpenTargets] raw='Afatinib' -> id='CHEMBL1173655'
[map][drug][OpenTargets] raw='Alitretinoin' -> id='CHEMBL705'
[map][drug][OpenTargets] raw='Allopurinol' -> id='CHEMBL1467'
[map][drug][OpenTargets] raw='Alprenolol' -> id='CHEMBL266195'
[map][drug][OpenTargets] raw='Aluminum Oxide' -> id='CHEMBL4594252'
[map][drug][OpenTargets] raw='Amantadine' -> id='CHEMBL660'
[map][drug][OpenTargets] raw='Amikacin' -> id='CHEMBL177'
[map][drug][OpenTargets] raw='Amiloride' -> id='CHEMBL945'
[map][drug][OpenTargets] raw='Aminosalicylic Acid' -> id='CHEMBL1169'
[map][drug][OpenTargets] raw='Amiodarone' -> id='CHEMBL633'
[map][drug][OpenTargets] raw='Amisulpride' -> id='CHEMBL243712'
[map][drug][OpenTargets] raw='Amitriptyline' -> id='CHEMBL629'
[map][drug][OpenTargets] raw='Amlodipine' -> id='CHEMBL1491'
[map][drug][OpenTargets] raw='Amphetamine' -> id='CHEMBL405'
[map][drug][OpenTargets] raw='Ampicillin' -> id='CHEMBL174'
[map][drug][OpenTargets] raw='Antimony' -> id='CHEMBL4297652'
[map][drug][OpenTargets] raw='Apigenin' -> id='CHEMBL28'
[map][drug][OpenTargets] raw='Apomorphine' -> id='CHEMBL53'
[map][drug][OpenTargets] raw='Aprepitant' -> id='CHEMBL1471'
[map][drug][OpenTargets] raw='Arsenic Trioxide' -> id='CHEMBL5483015'
[map][drug][OpenTargets] raw='Ascorbic Acid' -> id='CHEMBL196'
[map][drug][OpenTargets] raw='Aspartame' -> id='CHEMBL171679'
[map][drug][OpenTargets] raw='Aspirin' -> id='CHEMBL25'
[map][drug][OpenTargets] raw='Astemizole' -> id='CHEMBL296419'
[map][drug][OpenTargets] raw='Atenolol' -> id='CHEMBL24'
[map][drug][OpenTargets] raw='Atorvastatin' -> id='CHEMBL1487'
[map][drug][OpenTargets] raw='Atrazine' -> id='CHEMBL15063'
[map][drug][OpenTargets] raw='Atropine' -> id='CHEMBL517712'
[map][drug][OpenTargets] raw='Auranofin' -> id='CHEMBL1366'
[map][drug][OpenTargets] raw='Aurothioglucose' -> id='CHEMBL1697725'
[map][drug][OpenTargets] raw='Azathioprine' -> id='CHEMBL1542'
[map][drug][OpenTargets] raw='Aztreonam' -> id='CHEMBL158'
[map][drug][OpenTargets] raw='Benserazide' -> id='CHEMBL1096979'
[map][drug][OpenTargets] raw='Benztropine' -> id='CHEMBL1201203'
[map][drug][OpenTargets] raw='Berberine' -> id='CHEMBL295124'
[map][drug][OpenTargets] raw='Betamethasone' -> id='CHEMBL632'
[map][drug][OpenTargets] raw='Betulinic Acid' -> id='CHEMBL269277'
[map][drug][OpenTargets] raw='Biperiden' -> id='CHEMBL1101'
[map][drug][OpenTargets] raw='Bisoprolol' -> id='CHEMBL645'
[map][drug][OpenTargets] raw='Bleomycin' -> id='CHEMBL6067492'
[map][drug][OpenTargets] raw='Bortezomib' -> id='CHEMBL325041'
[map][drug][OpenTargets] raw='Bromazepam' -> id='CHEMBL277062'
[map][drug][OpenTargets] raw='Bromocriptine' -> id='CHEMBL493'
[map][drug][OpenTargets] raw='Budesonide' -> id='CHEMBL1370'
[map][drug][OpenTargets] raw='Buspirone' -> id='CHEMBL49'
[map][drug][OpenTargets] raw='Busulfan' -> id='CHEMBL820'
[map][drug][OpenTargets] raw='CB-839' -> id='CHEMBL3639788'
[map][drug][OpenTargets] raw='Cabergoline' -> id='CHEMBL1201087'
[map][drug][OpenTargets] raw='Caffeine' -> id='CHEMBL113'
[map][drug][OpenTargets] raw='Calcitriol' -> id='CHEMBL846'
[map][drug][OpenTargets] raw='Calcium' -> id='CHEMBL1200496'
[map][drug][OpenTargets] raw='Canertinib' -> id='CHEMBL31965'
[map][drug][OpenTargets] raw='Cannabidiol' -> id='CHEMBL190461'
[map][drug][OpenTargets] raw='Cannabinoids' -> id='CHEMBL3833333'
[map][drug][OpenTargets] raw='Capreomycin' -> id='CHEMBL2221250'
[map][drug][OpenTargets] raw='Capsaicin' -> id='CHEMBL294199'
[map][drug][OpenTargets] raw='Carbamazepine' -> id='CHEMBL108'
[map][drug][OpenTargets] raw='Carbidopa' -> id='CHEMBL1200748'
[map][drug][OpenTargets] raw='Carbon Monoxide' -> id='CHEMBL1231840'
[map][drug][OpenTargets] raw='Carboplatin' -> id='CHEMBL1351'
[map][drug][OpenTargets] raw='Carvedilol' -> id='CHEMBL723'
[map][drug][OpenTargets] raw='Catechin' -> id='CHEMBL311498'
[map][drug][OpenTargets] raw='Celecoxib' -> id='CHEMBL118'
[map][drug][OpenTargets] raw='Chenodeoxycholic Acid' -> id='CHEMBL240597'
[map][drug][OpenTargets] raw='Chlorambucil' -> id='CHEMBL515'
[map][drug][OpenTargets] raw='Chlordiazepoxide' -> id='CHEMBL451'
[map][drug][OpenTargets] raw='Chlormezanone' -> id='CHEMBL1200714'
[map][drug][OpenTargets] raw='Chloroquine' -> id='CHEMBL76'
[map][drug][OpenTargets] raw='Chlorpromazine' -> id='CHEMBL71'
[map][drug][OpenTargets] raw='Chlorprothixene' -> id='CHEMBL908'
[map][drug][OpenTargets] raw='Cholecalciferol' -> id='CHEMBL1042'
[map][drug][OpenTargets] raw='Cilostazol' -> id='CHEMBL799'
[map][drug][OpenTargets] raw='Cimetidine' -> id='CHEMBL30'
[map][drug][OpenTargets] raw='Cinnarizine' -> id='CHEMBL43064'
[map][drug][OpenTargets] raw='Ciprofloxacin' -> id='CHEMBL8'
[map][drug][OpenTargets] raw='Cisapride' -> id='CHEMBL1729'
[map][drug][OpenTargets] raw='Cisplatin' -> id='CHEMBL11359'
[map][drug][OpenTargets] raw='Clarithromycin' -> id='CHEMBL1741'
[map][drug][OpenTargets] raw='Clioquinol' -> id='CHEMBL497'
[map][drug][OpenTargets] raw='Clofibrate' -> id='CHEMBL565'
[map][drug][OpenTargets] raw='Clonazepam' -> id='CHEMBL452'
[map][drug][OpenTargets] raw='Clopenthixol' -> id='CHEMBL3989892'
[map][drug][OpenTargets] raw='Clozapine' -> id='CHEMBL42'
[map][drug][OpenTargets] raw='Cocaine' -> id='CHEMBL370805'
[map][drug][OpenTargets] raw='Copper' -> id='CHEMBL55643'
[map][drug][OpenTargets] raw='Copper Sulfate' -> id='CHEMBL604'
[map][drug][OpenTargets] raw='Crizotinib' -> id='CHEMBL601719'
[map][drug][OpenTargets] raw='Curcumin' -> id='CHEMBL140'
[map][drug][OpenTargets] raw='Cycloheximide' -> id='CHEMBL123292'
[map][drug][OpenTargets] raw='Cyclophosphamide' -> id='CHEMBL1200796'
[map][drug][OpenTargets] raw='Cycloserine' -> id='CHEMBL771'
[map][drug][OpenTargets] raw='Cyclosporine' -> id='CHEMBL160'
[map][drug][OpenTargets] raw='Cytarabine' -> id='CHEMBL803'
[map][drug][OpenTargets] raw='DDT' -> id='CHEMBL416898'
[map][drug][OpenTargets] raw='Dasatinib' -> id='CHEMBL5416410'
[map][drug][OpenTargets] raw='Decitabine' -> id='CHEMBL1201129'
[map][drug][OpenTargets] raw='Deferoxamine' -> id='CHEMBL556'
[map][drug][OpenTargets] raw='Dehydroepiandrosterone' -> id='CHEMBL90593'
[map][drug][OpenTargets] raw='Deoxycholic Acid' -> id='CHEMBL406393'
[map][drug][OpenTargets] raw='Deoxyglucose' -> id='CHEMBL2074932'
[map][drug][OpenTargets] raw='Desipramine' -> id='CHEMBL72'
[map][drug][OpenTargets] raw='Dexamethasone' -> id='CHEMBL384467'
[map][drug][OpenTargets] raw='Dexfenfluramine' -> id='CHEMBL248702'
[map][drug][OpenTargets] raw='Diazepam' -> id='CHEMBL12'
[map][drug][OpenTargets] raw='Dibutyl Phthalate' -> id='CHEMBL272485'
[map][drug][OpenTargets] raw='Dichlorvos' -> id='CHEMBL167911'
[map][drug][OpenTargets] raw='Diclofenac' -> id='CHEMBL139'
[map][drug][OpenTargets] raw='Diethylstilbestrol' -> id='CHEMBL411'
[map][drug][OpenTargets] raw='Dihydroergotamine' -> id='CHEMBL1732'
[map][drug][OpenTargets] raw='Dihydrostreptomycin Sulfate' -> id='CHEMBL3188576'
[map][drug][OpenTargets] raw='Dihydrotestosterone' -> id='CHEMBL27769'
[map][drug][OpenTargets] raw='Diltiazem' -> id='CHEMBL23'
[map][drug][OpenTargets] raw='Dinitrochlorobenzene' -> id='CHEMBL292687'
[map][drug][OpenTargets] raw='Dinoprostone' -> id='CHEMBL548'
[map][drug][OpenTargets] raw='Diosmin' -> id='CHEMBL231884'
[map][drug][OpenTargets] raw='Diphenhydramine' -> id='CHEMBL657'
[map][drug][OpenTargets] raw='Dipyridamole' -> id='CHEMBL932'
[map][drug][OpenTargets] raw='Ditiocarb' -> id='CHEMBL961'
[map][drug][OpenTargets] raw='Dobutamine' -> id='CHEMBL926'
[map][drug][OpenTargets] raw='Docetaxel' -> id='CHEMBL3545252'
[map][drug][OpenTargets] raw='Domperidone' -> id='CHEMBL219916'
[map][drug][OpenTargets] raw='Dopamine' -> id='CHEMBL59'
[map][drug][OpenTargets] raw='Doxorubicin' -> id='CHEMBL53463'
[map][drug][OpenTargets] raw='Dronabinol' -> id='CHEMBL465'
[map][drug][OpenTargets] raw='Droperidol' -> id='CHEMBL1108'
[map][drug][OpenTargets] raw='Dutasteride' -> id='CHEMBL1200969'
[map][drug][OpenTargets] raw='Edaravone' -> id='CHEMBL290916'
[map][drug][OpenTargets] raw='Eicosapentaenoic Acid' -> id='CHEMBL460026'
[map][drug][OpenTargets] raw='Enalapril' -> id='CHEMBL578'
[map][drug][OpenTargets] raw='Enalaprilat' -> id='CHEMBL3989406'
[map][drug][OpenTargets] raw='Epirubicin' -> id='CHEMBL417'
[map][drug][OpenTargets] raw='Ergotamine' -> id='CHEMBL442'
[map][drug][OpenTargets] raw='Erlotinib Hydrochloride' -> id='CHEMBL1079742'
[map][drug][OpenTargets] raw='Estradiol' -> id='CHEMBL135'
[map][drug][OpenTargets] raw='Ethambutol' -> id='CHEMBL44884'
[map][drug][OpenTargets] raw='Ethanol' -> id='CHEMBL545'
[map][drug][OpenTargets] raw='Ethionamide' -> id='CHEMBL1441'
[map][drug][OpenTargets] raw='Ethosuximide' -> id='CHEMBL696'
[map][drug][OpenTargets] raw='Etoposide' -> id='CHEMBL44657'
[map][drug][OpenTargets] raw='Etoricoxib' -> id='CHEMBL416146'
[map][drug][OpenTargets] raw='Eugenol' -> id='CHEMBL42710'
[map][drug][OpenTargets] raw='Everolimus' -> id='CHEMBL1908360'
[map][drug][OpenTargets] raw='Exenatide' -> id='CHEMBL414357'
[map][drug][OpenTargets] raw='Famotidine' -> id='CHEMBL902'
[map][drug][OpenTargets] raw='Fenoprofen' -> id='CHEMBL1297'
[map][drug][OpenTargets] raw='Fenretinide' -> id='CHEMBL7301'
[map][drug][OpenTargets] raw='Fentanyl' -> id='CHEMBL596'
[map][drug][OpenTargets] raw='Fingolimod Hydrochloride' -> id='CHEMBL544665'
[map][drug][OpenTargets] raw='Fludrocortisone' -> id='CHEMBL1201388'
[map][drug][OpenTargets] raw='Flunarizine' -> id='CHEMBL30008'
[map][drug][OpenTargets] raw='Fluorouracil' -> id='CHEMBL185'
[map][drug][OpenTargets] raw='Fluoxetine' -> id='CHEMBL41'
[map][drug][OpenTargets] raw='Flupenthixol' -> id='CHEMBL6066864'
[map][drug][OpenTargets] raw='Fluphenazine' -> id='CHEMBL726'
[map][drug][OpenTargets] raw='Flurbiprofen' -> id='CHEMBL563'
[map][drug][OpenTargets] raw='Fluspirilene' -> id='CHEMBL46516'
[map][drug][OpenTargets] raw='Folic Acid' -> id='CHEMBL1622'
[map][drug][OpenTargets] raw='Formaldehyde' -> id='CHEMBL1255'
[map][drug][OpenTargets] raw='Fulvestrant' -> id='CHEMBL1358'
[map][drug][OpenTargets] raw='Fusidic Acid' -> id='CHEMBL374975'
[map][drug][OpenTargets] raw='Gabapentin' -> id='CHEMBL940'
[map][drug][OpenTargets] raw='Gatifloxacin' -> id='CHEMBL31'
[map][drug][OpenTargets] raw='Gefitinib' -> id='CHEMBL939'
[map][drug][OpenTargets] raw='Gemcitabine' -> id='CHEMBL888'
[map][drug][OpenTargets] raw='Genistein' -> id='CHEMBL44'
[map][drug][OpenTargets] raw='Gliclazide' -> id='CHEMBL427216'
[map][drug][OpenTargets] raw='Glucosamine' -> id='CHEMBL493287'
[map][drug][OpenTargets] raw='Glucose' -> id='CHEMBL1222250'
[map][drug][OpenTargets] raw='Glutathione' -> id='CHEMBL1543'
[map][drug][OpenTargets] raw='Glutathione Disulfide' -> id='CHEMBL1372'
[map][drug][OpenTargets] raw='Gold' -> id='CHEMBL3137693'
[map][drug][OpenTargets] raw='Gold Sodium Thiomalate' -> id='CHEMBL306043'
[map][drug][OpenTargets] raw='Griseofulvin' -> id='CHEMBL562'
[map][drug][OpenTargets] raw='Haloperidol' -> id='CHEMBL54'
[map][drug][OpenTargets] raw='Heparin' -> id='CHEMBL4650299'
[map][drug][OpenTargets] raw='Histamine' -> id='CHEMBL90'
[map][drug][OpenTargets] raw='Hyaluronic Acid' -> id='CHEMBL5314376'
[map][drug][OpenTargets] raw='Hydralazine' -> id='CHEMBL276832'
[map][drug][OpenTargets] raw='Hydrocortisone' -> id='CHEMBL389621'
[map][drug][OpenTargets] raw='Hydrogen Peroxide' -> id='CHEMBL71595'
[map][drug][OpenTargets] raw='Hydroxychloroquine' -> id='CHEMBL1535'
[map][drug][OpenTargets] raw='Hydroxyurea' -> id='CHEMBL467'
[map][drug][OpenTargets] raw='Hypochlorous Acid' -> id='CHEMBL1616046'
[map][drug][OpenTargets] raw='Ibuprofen' -> id='CHEMBL521'
[map][drug][OpenTargets] raw='Idazoxan' -> id='CHEMBL10316'
[map][drug][OpenTargets] raw='Ifosfamide' -> id='CHEMBL1024'
[map][drug][OpenTargets] raw='Imatinib Mesylate' -> id='CHEMBL1642'
[map][drug][OpenTargets] raw='Imipramine' -> id='CHEMBL11'
[map][drug][OpenTargets] raw='Indinavir' -> id='CHEMBL5483011'
[map][drug][OpenTargets] raw='Indomethacin' -> id='CHEMBL6'
[map][drug][OpenTargets] raw='Irbesartan' -> id='CHEMBL1513'
[map][drug][OpenTargets] raw='Irinotecan' -> id='CHEMBL481'
[map][drug][OpenTargets] raw='Isocarboxazid' -> id='CHEMBL1201168'
[map][drug][OpenTargets] raw='Isoniazid' -> id='CHEMBL64'
[map][drug][OpenTargets] raw='Isoproterenol' -> id='CHEMBL434'
[map][drug][OpenTargets] raw='Isosorbide Dinitrate' -> id='CHEMBL6622'
[map][drug][OpenTargets] raw='Isotretinoin' -> id='CHEMBL547'
[map][drug][OpenTargets] raw='Ivermectin' -> id='CHEMBL6067487'
[map][drug][OpenTargets] raw='Kanamycin' -> id='CHEMBL1384'
[map][drug][OpenTargets] raw='Ketoconazole' -> id='CHEMBL157101'
[map][drug][OpenTargets] raw='Ketoprofen' -> id='CHEMBL571'
[map][drug][OpenTargets] raw='Ketorolac' -> id='CHEMBL469'
[map][drug][OpenTargets] raw='Kynurenic Acid' -> id='CHEMBL299155'
[map][drug][OpenTargets] raw='Lactic Acid' -> id='CHEMBL1200559'
[map][drug][OpenTargets] raw='Lamotrigine' -> id='CHEMBL741'
[map][drug][OpenTargets] raw='Lansoprazole' -> id='CHEMBL480'
[map][drug][OpenTargets] raw='Lapatinib' -> id='CHEMBL554'
[map][drug][OpenTargets] raw='Leflunomide' -> id='CHEMBL960'
[map][drug][OpenTargets] raw='Levamisole' -> id='CHEMBL1454'
[map][drug][OpenTargets] raw='Levodopa' -> id='CHEMBL1009'
[map][drug][OpenTargets] raw='Linezolid' -> id='CHEMBL126'
[map][drug][OpenTargets] raw='Lisuride' -> id='CHEMBL157138'
[map][drug][OpenTargets] raw='Lithium' -> id='CHEMBL1201333'
[map][drug][OpenTargets] raw='Lithium Carbonate' -> id='CHEMBL1200826'
[map][drug][OpenTargets] raw='Loperamide' -> id='CHEMBL841'
[map][drug][OpenTargets] raw='Losartan' -> id='CHEMBL191'
[map][drug][OpenTargets] raw='Lovastatin' -> id='CHEMBL503'
[map][drug][OpenTargets] raw='Luteolin' -> id='CHEMBL151'
[map][drug][OpenTargets] raw='Magnesium' -> id='CHEMBL1201230'
[map][drug][OpenTargets] raw='Magnesium Chloride' -> id='CHEMBL3185229'
[map][drug][OpenTargets] raw='Masoprocol' -> id='CHEMBL313972'
[map][drug][OpenTargets] raw='Mechlorethamine' -> id='CHEMBL427'
[map][drug][OpenTargets] raw='Mefenamic Acid' -> id='CHEMBL686'
[map][drug][OpenTargets] raw='Melatonin' -> id='CHEMBL45'
[map][drug][OpenTargets] raw='Meloxicam' -> id='CHEMBL599'
[map][drug][OpenTargets] raw='Memantine' -> id='CHEMBL807'
[map][drug][OpenTargets] raw='Meperidine' -> id='CHEMBL607'
[map][drug][OpenTargets] raw='Mercaptopurine' -> id='CHEMBL1200751'
[map][drug][OpenTargets] raw='Mesalamine' -> id='CHEMBL704'
[map][drug][OpenTargets] raw='Metformin' -> id='CHEMBL1431'
[map][drug][OpenTargets] raw='Methamphetamine' -> id='CHEMBL1201201'
[map][drug][OpenTargets] raw='Methionine' -> id='CHEMBL42336'
[map][drug][OpenTargets] raw='Methotrexate' -> id='CHEMBL34259'
[map][drug][OpenTargets] raw='Methotrimeprazine' -> id='CHEMBL1764'
[map][drug][OpenTargets] raw='Methoxsalen' -> id='CHEMBL416'
[map][drug][OpenTargets] raw='Methyldopa' -> id='CHEMBL459'
[map][drug][OpenTargets] raw='Methylene Blue' -> id='CHEMBL550495'
[map][drug][OpenTargets] raw='Methylprednisolone' -> id='CHEMBL650'
[map][drug][OpenTargets] raw='Methylprednisolone Acetate' -> id='CHEMBL1364144'
[map][drug][OpenTargets] raw='Methylprednisolone Hemisuccinate' -> id='CHEMBL1201265'
[map][drug][OpenTargets] raw='Methysergide' -> id='CHEMBL1065'
[map][drug][OpenTargets] raw='Metoclopramide' -> id='CHEMBL86'
[map][drug][OpenTargets] raw='Metoprolol' -> id='CHEMBL13'
[map][drug][OpenTargets] raw='Metronidazole' -> id='CHEMBL137'
[map][drug][OpenTargets] raw='Mianserin' -> id='CHEMBL6437'
[map][drug][OpenTargets] raw='Mifepristone' -> id='CHEMBL1276308'
[map][drug][OpenTargets] raw='Migril' -> id='CHEMBL2448612'
[map][drug][OpenTargets] raw='Minocycline' -> id='CHEMBL1434'
[map][drug][OpenTargets] raw='Mirtazapine' -> id='CHEMBL654'
[map][drug][OpenTargets] raw='Misoprostol' -> id='CHEMBL606'
[map][drug][OpenTargets] raw='Mitoxantrone' -> id='CHEMBL58'
[map][drug][OpenTargets] raw='Motival' -> id='CHEMBL445'
[map][drug][OpenTargets] raw='Mycophenolic Acid' -> id='CHEMBL866'
[map][drug][OpenTargets] raw='NVP-AEW541' -> id='CHEMBL551064'
[map][drug][OpenTargets] raw='Nabumetone' -> id='CHEMBL1070'
[map][drug][OpenTargets] raw='Naloxone' -> id='CHEMBL80'
[map][drug][OpenTargets] raw='Naproxen' -> id='CHEMBL154'
[map][drug][OpenTargets] raw='Nevirapine' -> id='CHEMBL57'
[map][drug][OpenTargets] raw='Niacin' -> id='CHEMBL573'
[map][drug][OpenTargets] raw='Niclosamide' -> id='CHEMBL1448'
[map][drug][OpenTargets] raw='Nicotine' -> id='CHEMBL3'
[map][drug][OpenTargets] raw='Nifedipine' -> id='CHEMBL193'
[map][drug][OpenTargets] raw='Nimodipine' -> id='CHEMBL1428'
[map][drug][OpenTargets] raw='Nitric Oxide' -> id='CHEMBL1200689'
[map][drug][OpenTargets] raw='Nitrofurantoin' -> id='CHEMBL572'
[map][drug][OpenTargets] raw='Nitroglycerin' -> id='CHEMBL730'
[map][drug][OpenTargets] raw='Nizatidine' -> id='CHEMBL3183075'
[map][drug][OpenTargets] raw='Nortriptyline' -> id='CHEMBL445'
[map][drug][OpenTargets] raw='ON 01910' -> id='CHEMBL1241855'
[map][drug][OpenTargets] raw='OPC-67683' -> id='CHEMBL218650'
[map][drug][OpenTargets] raw='Octopamine' -> id='CHEMBL53929'
[map][drug][OpenTargets] raw='Octreotide' -> id='CHEMBL1680'
[map][drug][OpenTargets] raw='Ofloxacin' -> id='CHEMBL4'
[map][drug][OpenTargets] raw='Okadaic Acid' -> id='CHEMBL280487'
[map][drug][OpenTargets] raw='Olanzapine' -> id='CHEMBL715'
[map][drug][OpenTargets] raw='Oleic Acid' -> id='CHEMBL8659'
[map][drug][OpenTargets] raw='Olmesartan Medoxomil' -> id='CHEMBL1200692'
[map][drug][OpenTargets] raw='Omeprazole' -> id='CHEMBL1503'
[map][drug][OpenTargets] raw='Ondansetron' -> id='CHEMBL46'
[map][drug][OpenTargets] raw='Orlistat' -> id='CHEMBL175247'
[map][drug][OpenTargets] raw='Orphenadrine' -> id='CHEMBL900'
[map][drug][OpenTargets] raw='Ouabain' -> id='CHEMBL222863'
[map][drug][OpenTargets] raw='Oxaliplatin' -> id='CHEMBL414804'
[map][drug][OpenTargets] raw='Oxcarbazepine' -> id='CHEMBL1068'
[map][drug][OpenTargets] raw='Oxygen' -> id='CHEMBL1234886'
[map][drug][OpenTargets] raw='Oxyphenbutazone' -> id='CHEMBL3989676'
[map][drug][OpenTargets] raw='Oxyquinoline' -> id='CHEMBL310555'
[map][drug][OpenTargets] raw='Ozone' -> id='CHEMBL2447938'
[map][drug][OpenTargets] raw='PKI 166' -> id='CHEMBL1963502'
[map][drug][OpenTargets] raw='Paclitaxel' -> id='CHEMBL428647'
[map][drug][OpenTargets] raw='Paliperidone Palmitate' -> id='CHEMBL2107360'
[map][drug][OpenTargets] raw='Palmitic Acid' -> id='CHEMBL82293'
[map][drug][OpenTargets] raw='Pamidronate' -> id='CHEMBL834'
[map][drug][OpenTargets] raw='Pargyline' -> id='CHEMBL673'
[map][drug][OpenTargets] raw='Paroxetine' -> id='CHEMBL490'
[map][drug][OpenTargets] raw='Pefloxacin' -> id='CHEMBL267648'
[map][drug][OpenTargets] raw='Penicillamine' -> id='CHEMBL1430'
[map][drug][OpenTargets] raw='Pentoxifylline' -> id='CHEMBL628'
[map][drug][OpenTargets] raw='Pergolide' -> id='CHEMBL531'
[map][drug][OpenTargets] raw='Permethrin' -> id='CHEMBL1525'
[map][drug][OpenTargets] raw='Perphenazine' -> id='CHEMBL567'
[map][drug][OpenTargets] raw='Phenelzine' -> id='CHEMBL1089'
[map][drug][OpenTargets] raw='Phenobarbital' -> id='CHEMBL40'
[map][drug][OpenTargets] raw='Phentermine' -> id='CHEMBL1574'
[map][drug][OpenTargets] raw='Phenylbutazone' -> id='CHEMBL101'
[map][drug][OpenTargets] raw='Phenytoin' -> id='CHEMBL16'
[map][drug][OpenTargets] raw='Phloretin' -> id='CHEMBL45068'

2026-02-27 17:45:04,890 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:04,918 [INFO] [LLM] Batch done in 1.88s
2026-02-27 17:45:04,971 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:04,974 [INFO] [LLM] Batch done in 1.94s
2026-02-27 17:45:06,578 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:06,581 [INFO] [LLM] Batch done in 3.54s
2026-02-27 17:45:07,769 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:07,771 [INFO] [LLM] Batch done in 4.73s
2026-02-27 17:45:08,229 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:08,231 [INFO] [LLM] Batch done in 5.19s
2026-02-27 17:45:08,716 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:08,719 [INFO] [LLM] Batch done in 5.73s
2026-02-27 17:45:08,743 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:08,745 [INFO] [LLM] Batch done in 5.70s
2026-02-27 17:45:09,479 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:09,482 [INFO] [LLM] Batch done in 6.44s
2026-02-27 17:45:09,483 [WARNING] [LLM] Model skipped "2,2',4,6,6'-pentachlorobiphenyl" — defaulting to None
2026-02-27 17:45:09,484 [INFO] [OT] Verifying 56 unique drug suggestions...
2026-02-27 17:45:09,900 [INFO] [OT] 'calcitriol' → 'CALCITRIOL' (CHEMBL846)
2026-02-27 17:45:09,901 [INFO] [OT] 'pentoxifylline' → 'PENTOXIFYLLINE' (CHEMBL628)
2026-02-27 17:45:09,902 [INFO] [OT] 'insulin aspart' → 'INSULIN ASPART' (CHEMBL1201496)
2026-02-27 17:45:09,902 [INFO] [OT] 'flupenthixol' → 'FLUPENTIXOL' (CHEMBL6066864)
2026-02-27 17:45:09,903 [INFO] [OT] 'lindane' → 'LINDANE' (CHEMBL15891)
2026-02-27 17:45:09,903 [INFO] [OT] 'MK-2206' → 'MK-2206' (CHEMBL1079175)
2026-02-27 17:45:09,903 [INFO] [OT] 'fluphenazine' → 'FLUPHENAZINE' (CHEMBL726)
2026-02-27 17:45:09,906 [INFO] Done: 7 / 573 confirmed | 566 → None

[map][drug][Llama] raw='1,25-dihydroxyvitamin D' -> canonical='CALCITRIOL' -> id='CHEMBL846'
[map][drug][Llama] raw='1-Methyl-3-isobutylxanthine' -> canonical='PENTOXIFYLLINE' -> id='CHEMBL628'
[map][drug][Llama] raw='MK 2206' -> canonical='MK-2206' -> id='CHEMBL1079175'
[map][drug][Llama] raw='beta-hexachlorocyclohexane' -> canonical='LINDANE' -> id='CHEMBL15891'
[map][drug][Llama] raw='flupenthixol decanoate' -> canonical='FLUPENTIXOL' -> id='CHEMBL6066864'
[map][drug][Llama] raw='fluphenazine depot' -> canonical='FLUPHENAZINE' -> id='CHEMBL726'
[map][drug][Llama] raw='insulin, Asp(B10)-' -> canonical='INSULIN ASPART' -> id='CHEMBL1201496'

,drug_name,drug_id,source
0,((1-ethylpyrrolidin-2-yl) methyl)-4-hydroxy-7-...,None,None
1,(+)-JQ1 compound,None,None
2,"(3R)-((2,3-dihydro-5-methyl-3-((4-morpholinyl)...",None,None
3,"(6,7-dimethoxyquinolin-4-yl)(5-methoxy-2,2-dim...",None,None
4,"1,1-bis(3'-indolyl)-1-(4-hydroxyphenyl)methane",None,None
...,...,...,...
1142,zafirlukast,CHEMBL603,OpenTargets
1143,zhenwu decoction,None,None
1144,zileuton,CHEMBL93,OpenTargets
1145,zinc chloride,CHEMBL1200679,OpenTargets
1146,zolmitriptan,CHEMBL1185,OpenTargets

In [11]:
df_drug["source"].value_counts()

source
OpenTargets    574
Llama            7
Name: count, dtype: int64

In [12]:
# df_drug[df_drug["source"]=="Llama"]

In [13]:
df_drug[df_drug.isna().any(axis=1)]

                                              drug_name drug_id source
0     ((1-ethylpyrrolidin-2-yl) methyl)-4-hydroxy-7-...    None   None
1                                      (+)-JQ1 compound    None   None
2     (3R)-((2,3-dihydro-5-methyl-3-((4-morpholinyl)...    None   None
3     (6,7-dimethoxyquinolin-4-yl)(5-methoxy-2,2-dim...    None   None
4        1,1-bis(3'-indolyl)-1-(4-hydroxyphenyl)methane    None   None
...                                                 ...     ...    ...
1133                                   tyrphostin AG825    None   None
1136                                    vanadyl sulfate    None   None
1140                                     xianglian pill    None   None
1141                                      yufengningxin    None   None
1143                                   zhenwu decoction    None   None

[566 rows x 3 columns]

##### Associate id with all disease entry

In [14]:
# Resolve unique disease surface forms to IDs.
# Canonical fallback is internal; returned rows remain keyed by raw input disease_name.
df_disease = await get_disease_ids_fast(list(question_entities["disease_name"]))
df_disease = df_disease.drop_duplicates(subset=["disease_name", "disease_id"]).reset_index(drop=True)
df_disease

2026-02-27 17:45:12,755 [INFO] [LLM] Total 236 names split into 3 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 17:45:12,756 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:12,757 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:12,759 [INFO] [LLM] Batch size: 76

[map][disease][OpenTargets] raw='AMYOTROPHIC LATERAL SCLEROSIS 15 WITH OR WITHOUT FRONTOTEMPORAL DEMENTIA' -> id='MONDO_0010459'
[map][disease][OpenTargets] raw='AMYOTROPHIC LATERAL SCLEROSIS 18' -> id='MONDO_0013891'
[map][disease][OpenTargets] raw='AMYOTROPHIC LATERAL SCLEROSIS 20' -> id='MONDO_0014181'
[map][disease][OpenTargets] raw='AMYOTROPHIC LATERAL SCLEROSIS-PARKINSONISM/DEMENTIA COMPLEX 1' -> id='MONDO_0007104'
[map][disease][OpenTargets] raw='ANTLEY-BIXLER SYNDROME WITHOUT GENITAL ANOMALIES OR DISORDERED STEROIDOGENESIS' -> id='MONDO_0020667'
[map][disease][OpenTargets] raw='Abdominal Pain' -> id='HP_0002027'
[map][disease][OpenTargets] raw='Acquired Hyperostosis Syndrome' -> id='EFO_1001164'
[map][disease][OpenTargets] raw='Acrocephalosyndactylia' -> id='MONDO_0019796'
[map][disease][OpenTargets] raw='Acute Kidney Injury' -> id='MONDO_0002492'
[map][disease][OpenTargets] raw='Acute erythroleukemia' -> id='EFO_0000218'
[map][disease][OpenTargets] raw='Adenocarcinoma' -> id='EFO_0000228'
[map][disease][OpenTargets] raw='Adenocarcinoma Of Esophagus' -> id='EFO_0000280'
[map][disease][OpenTargets] raw='Adenocarcinoma of Lung' -> id='EFO_0000571'
[map][disease][OpenTargets] raw='Adenoma' -> id='EFO_0000232'
[map][disease][OpenTargets] raw='Adenomatous Polyposis Coli' -> id='MONDO_0021056'
[map][disease][OpenTargets] raw='Adrenal Gland Neoplasms' -> id='EFO_0003850'
[map][disease][OpenTargets] raw='Adrenocortical Carcinoma' -> id='EFO_1000796'
[map][disease][OpenTargets] raw='Albuminuria' -> id='EFO_0004285'
[map][disease][OpenTargets] raw='Alcoholism' -> id='MONDO_0002046'
[map][disease][OpenTargets] raw='Alstrom Syndrome' -> id='MONDO_0008763'
[map][disease][OpenTargets] raw='Alzheimer Disease' -> id='MONDO_0007088'
[map][disease][OpenTargets] raw='Ameloblastoma' -> id='MONDO_0017795'
[map][disease][OpenTargets] raw='Amphetamine-Related Disorders' -> id='EFO_0004701'
[map][disease][OpenTargets] raw='Amyloidosis' -> id='EFO_1001875'
[map][disease][OpenTargets] raw='Amyotrophic Lateral Sclerosis' -> id='MONDO_0004976'
[map][disease][OpenTargets] raw='Amyotrophic Lateral Sclerosis 11' -> id='MONDO_0012945'
[map][disease][OpenTargets] raw='Amyotrophic Lateral Sclerosis 5' -> id='MONDO_0011196'
[map][disease][OpenTargets] raw='Amyotrophic Lateral Sclerosis 8' -> id='MONDO_0012077'
[map][disease][OpenTargets] raw='Anemia' -> id='MONDO_0002280'
[map][disease][OpenTargets] raw='Ankylosis' -> id='MONDO_0002257'
[map][disease][OpenTargets] raw='Anorexia' -> id='HP_0002039'
[map][disease][OpenTargets] raw='Anuria' -> id='EFO_0009530'
[map][disease][OpenTargets] raw='Anxiety Disorders' -> id='EFO_0006788'
[map][disease][OpenTargets] raw='Asperger Syndrome' -> id='EFO_0003757'
[map][disease][OpenTargets] raw='Astrocytoma' -> id='EFO_0000272'
[map][disease][OpenTargets] raw='Atrial Fibrillation' -> id='EFO_0000275'
[map][disease][OpenTargets] raw='Atrophy' -> id='EFO_1000096'
[map][disease][OpenTargets] raw='Autism Spectrum Disorder' -> id='EFO_0003756'
[map][disease][OpenTargets] raw='Autistic Disorder' -> id='EFO_0003758'
[map][disease][OpenTargets] raw='BENT BONE DYSPLASIA SYNDROME 1' -> id='MONDO_0013815'
[map][disease][OpenTargets] raw='Balkan Nephropathy' -> id='EFO_0007164'
[map][disease][OpenTargets] raw='Bipolar Disorder' -> id='MONDO_0004985'
[map][disease][OpenTargets] raw='Blindness' -> id='MONDO_0001941'
[map][disease][OpenTargets] raw='Brain Ischemia' -> id='MONDO_0005299'
[map][disease][OpenTargets] raw='Brain Neoplasms' -> id='EFO_0003833'
[map][disease][OpenTargets] raw='Brain Stem Neoplasms' -> id='EFO_1001767'
[map][disease][OpenTargets] raw='Breast Neoplasms' -> id='EFO_0003869'
[map][disease][OpenTargets] raw='Cadmium Poisoning' -> id='EFO_1001768'
[map][disease][OpenTargets] raw='Calcinosis' -> id='EFO_0003837'
[map][disease][OpenTargets] raw='Carcinoma' -> id='EFO_0000313'
[map][disease][OpenTargets] raw='Cardiofaciocutaneous syndrome' -> id='MONDO_0015280'
[map][disease][OpenTargets] raw='Cardiomegaly' -> id='EFO_0002503'
[map][disease][OpenTargets] raw='Cardiomyopathies' -> id='EFO_0000318'
[map][disease][OpenTargets] raw='Cardiotoxicity' -> id='EFO_1001482'
[map][disease][OpenTargets] raw='Cardiovascular Diseases' -> id='EFO_0000319'
[map][disease][OpenTargets] raw='Carotid Artery Diseases' -> id='EFO_0003781'
[map][disease][OpenTargets] raw='Cataract' -> id='MONDO_0005129'
[map][disease][OpenTargets] raw='Chloracne' -> id='EFO_1001777'
[map][disease][OpenTargets] raw='Cholangiocarcinoma' -> id='EFO_0005221'
[map][disease][OpenTargets] raw='Cholestasis' -> id='MONDO_0001751'
[map][disease][OpenTargets] raw='Clear-cell metastatic renal cell carcinoma' -> id='EFO_0000349'
[map][disease][OpenTargets] raw='Cleft Lip' -> id='EFO_0003959'
[map][disease][OpenTargets] raw='Cleft Palate' -> id='MONDO_0016064'
[map][disease][OpenTargets] raw='Confusion' -> id='HP_0001289'
[map][disease][OpenTargets] raw='Conjunctivitis' -> id='EFO_0009450'
[map][disease][OpenTargets] raw='Coronary Vasospasm' -> id='EFO_0004225'
[map][disease][OpenTargets] raw='Costello Syndrome' -> id='MONDO_0009026'
[map][disease][OpenTargets] raw='Craniofacial Dysostosis' -> id='MONDO_0007405'
[map][disease][OpenTargets] raw='Craniopharyngioma' -> id='EFO_1000209'
[map][disease][OpenTargets] raw='Crohn Disease' -> id='EFO_0000384'
[map][disease][OpenTargets] raw='Cutis Gyrata Syndrome of Beare And Stevenson' -> id='MONDO_0007412'
[map][disease][OpenTargets] raw='Cystic Fibrosis' -> id='MONDO_0009061'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 11' -> id='MONDO_0013388'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 12' -> id='MONDO_0013389'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 13' -> id='MONDO_0013801'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 14' -> id='MONDO_0013989'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 17' -> id='MONDO_0014199'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 18' -> id='MONDO_0014201'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 19' -> id='MONDO_0014328'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 27' -> id='MONDO_0014505'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 28' -> id='MONDO_0014533'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 29' -> id='MONDO_0014593'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 31A' -> id='MONDO_0014598'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 33' -> id='MONDO_0014625'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 35' -> id='MONDO_0014719'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 36' -> id='MONDO_0010472'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 41' -> id='MONDO_0014916'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 42' -> id='MONDO_0014917'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 43' -> id='MONDO_0014921'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 44' -> id='MONDO_0014933'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 45' -> id='MONDO_0014942'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 46' -> id='MONDO_0014947'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 48' -> id='MONDO_0015000'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 5' -> id='MONDO_0013277'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 51' -> id='MONDO_0015025'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 52' -> id='MONDO_0033361'
[map][disease][OpenTargets] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 54' -> id='MONDO_0033363'
[map][disease][OpenTargets] raw='Depressive Disorder' -> id='MONDO_0002050'
[map][disease][OpenTargets] raw='Dermatitis' -> id='MONDO_0002406'
[map][disease][OpenTargets] raw='Desbuquois syndrome' -> id='MONDO_0009629'
[map][disease][OpenTargets] raw='Diabetes Mellitus' -> id='EFO_0000400'
[map][disease][OpenTargets] raw='Diabetic Angiopathies' -> id='EFO_1000896'
[map][disease][OpenTargets] raw='Diabetic Nephropathies' -> id='EFO_0000401'
[map][disease][OpenTargets] raw='Diarrhea' -> id='MONDO_0001673'
[map][disease][OpenTargets] raw='Drug Hypersensitivity' -> id='EFO_0009482'
[map][disease][OpenTargets] raw='Dysarthria' -> id='HP_0001260'
[map][disease][OpenTargets] raw='Dyskeratosis Congenita' -> id='MONDO_0015780'
[map][disease][OpenTargets] raw='Dyskinesias' -> id='HP_0100660'
[map][disease][OpenTargets] raw='Edema' -> id='EFO_0009373'
[map][disease][OpenTargets] raw='Emphysema' -> id='EFO_0000464'
[map][disease][OpenTargets] raw='Endometrial Neoplasms' -> id='EFO_0004230'
[map][disease][OpenTargets] raw='Endometriosis' -> id='EFO_0001065'
[map][disease][OpenTargets] raw='Endomyocardial Fibrosis' -> id='EFO_1000921'
[map][disease][OpenTargets] raw='Epilepsy' -> id='EFO_0000474'
[map][disease][OpenTargets] raw='Esophageal Squamous Cell Carcinoma' -> id='EFO_0005922'
[map][disease][OpenTargets] raw='Exanthema' -> id='EFO_1000697'
[map][disease][OpenTargets] raw='Fatigue' -> id='HP_0012378'
[map][disease][OpenTargets] raw='Fatty Liver' -> id='MONDO_0004790'
[map][disease][OpenTargets] raw='Fibrosis' -> id='EFO_0006890'
[map][disease][OpenTargets] raw='Gastrointestinal Stromal Tumors' -> id='MONDO_0011719'
[map][disease][OpenTargets] raw='Generalized Epilepsy and Paroxysmal Dyskinesia' -> id='MONDO_0012276'
[map][disease][OpenTargets] raw='Glioblastoma' -> id='EFO_0000519'
[map][disease][OpenTargets] raw='Glioma' -> id='EFO_0005543'
[map][disease][OpenTargets] raw='Glucose Intolerance' -> id='HP_0001952'
[map][disease][OpenTargets] raw='Heart Diseases' -> id='EFO_0003777'
[map][disease][OpenTargets] raw='Heart Failure' -> id='EFO_0003144'
[map][disease][OpenTargets] raw='Hemangiosarcoma' -> id='EFO_0003968'
[map][disease][OpenTargets] raw='Hemolysis' -> id='EFO_0009473'
[map][disease][OpenTargets] raw='Hepatitis' -> id='HP_0012115'
[map][disease][OpenTargets] raw='Hepatitis C' -> id='EFO_0003047'
[map][disease][OpenTargets] raw='Hepatomegaly' -> id='HP_0002240'
[map][disease][OpenTargets] raw='Hodgkin Disease' -> id='EFO_0000183'
[map][disease][OpenTargets] raw='Huntington Disease' -> id='MONDO_0007739'
[map][disease][OpenTargets] raw='Hyperandrogenism' -> id='EFO_0009006'
[map][disease][OpenTargets] raw='Hyperbilirubinemia' -> id='MONDO_0002408'
[map][disease][OpenTargets] raw='Hypercholesterolemia' -> id='HP_0003124'
[map][disease][OpenTargets] raw='Hyperekplexia and Epilepsy' -> id='MONDO_0010375'
[map][disease][OpenTargets] raw='Hyperglycemia' -> id='HP_0003074'
[map][disease][OpenTargets] raw='Hyperinsulinism' -> id='MONDO_0002177'
[map][disease][OpenTargets] raw='Hyperkalemia' -> id='HP_0002153'
[map][disease][OpenTargets] raw='Hypertension' -> id='EFO_0000537'
[map][disease][OpenTargets] raw='Hypertriglyceridemia' -> id='EFO_0004211'
[map][disease][OpenTargets] raw='Hypophosphatemia' -> id='MONDO_0000313'
[map][disease][OpenTargets] raw='Hypotension' -> id='EFO_0005251'
[map][disease][OpenTargets] raw='Hypothermia' -> id='HP_0002045'
[map][disease][OpenTargets] raw='Infantile Epileptic-Dyskinetic Encephalopathy' -> id='MONDO_0010632'
[map][disease][OpenTargets] raw='Inflammatory Bowel Diseases' -> id='EFO_0003767'
[map][disease][OpenTargets] raw='Insulin Resistance' -> id='HP_0000855'
[map][disease][OpenTargets] raw='Intellectual Disability' -> id='HP_0001249'
[map][disease][OpenTargets] raw='Ischemia' -> id='EFO_0000556'
[map][disease][OpenTargets] raw='Jackson-Weiss syndrome' -> id='MONDO_0007400'
[map][disease][OpenTargets] raw='Jaundice' -> id='HP_0000952'
[map][disease][OpenTargets] raw='Keratosis' -> id='EFO_1000720'
[map][disease][OpenTargets] raw='Kidney Diseases' -> id='EFO_0003086'
[map][disease][OpenTargets] raw='Kidney Neoplasms' -> id='EFO_0003865'
[map][disease][OpenTargets] raw='LEOPARD SYNDROME 3' -> id='MONDO_0013380'
[map][disease][OpenTargets] raw='Lacrimoauriculodentodigital syndrome' -> id='MONDO_0007872'
[map][disease][OpenTargets] raw='Lafora Disease' -> id='MONDO_0009697'
[map][disease][OpenTargets] raw='Landau-Kleffner Syndrome' -> id='EFO_1001010'
[map][disease][OpenTargets] raw='Leiomyoma' -> id='MONDO_0001572'
[map][disease][OpenTargets] raw='Leukemia' -> id='EFO_0000565'
[map][disease][OpenTargets] raw='Leukocytosis' -> id='HP_0001974'
[map][disease][OpenTargets] raw='Li-Fraumeni Syndrome' -> id='MONDO_0018875'
[map][disease][OpenTargets] raw='Liposarcoma' -> id='EFO_0000569'
[map][disease][OpenTargets] raw='Liver Cirrhosis' -> id='EFO_0001422'
[map][disease][OpenTargets] raw='Liver Diseases' -> id='EFO_0001421'
[map][disease][OpenTargets] raw='Lung Neoplasms' -> id='MONDO_0021117'
[map][disease][OpenTargets] raw='Lymphatic Metastasis' -> id='EFO_1001364'
[map][disease][OpenTargets] raw='Lymphoma' -> id='EFO_0000574'
[map][disease][OpenTargets] raw='MYOCLONIC-ATONIC EPILEPSY' -> id='MONDO_0014633'
[map][disease][OpenTargets] raw='Manganese Poisoning' -> id='EFO_1001808'
[map][disease][OpenTargets] raw='Medulloblastoma' -> id='EFO_0002939'
[map][disease][OpenTargets] raw='Melanoma' -> id='EFO_0000756'
[map][disease][OpenTargets] raw='Mesothelioma' -> id='EFO_0000588'
[map][disease][OpenTargets] raw='Metabolic Diseases' -> id='EFO_0000589'
[map][disease][OpenTargets] raw='Metabolic Syndrome' -> id='EFO_0000195'
[map][disease][OpenTargets] raw='Migraine with Aura' -> id='MONDO_0005475'
[map][disease][OpenTargets] raw='Migraine without Aura' -> id='MONDO_0100431'
[map][disease][OpenTargets] raw='Mood Disorders' -> id='EFO_0004247'
[map][disease][OpenTargets] raw='Mouth Neoplasms' -> id='EFO_0003868'
[map][disease][OpenTargets] raw='Movement Disorders' -> id='EFO_0004280'
[map][disease][OpenTargets] raw='Multiple Sclerosis' -> id='MONDO_0005301'
[map][disease][OpenTargets] raw='Muscular Diseases' -> id='EFO_0002970'
[map][disease][OpenTargets] raw='Myelodysplastic Syndromes' -> id='EFO_0000198'
[map][disease][OpenTargets] raw='Myocardial Infarction' -> id='EFO_0000612'
[map][disease][OpenTargets] raw='Myoclonus' -> id='HP_0001336'
[map][disease][OpenTargets] raw='Myositis' -> id='EFO_0000783'
[map][disease][OpenTargets] raw='NOONAN SYNDROME 7' -> id='MONDO_0013379'
[map][disease][OpenTargets] raw='Nasopharyngeal Carcinoma' -> id='MONDO_0011775'
[map][disease][OpenTargets] raw='Nasopharyngeal Neoplasms' -> id='EFO_0004252'
[map][disease][OpenTargets] raw='Nausea' -> id='HP_0002018'
[map][disease][OpenTargets] raw='Neoplasm Metastasis' -> id='EFO_0009708'
[map][disease][OpenTargets] raw='Nephrosclerosis' -> id='EFO_1000041'
[map][disease][OpenTargets] raw='Neuroblastoma' -> id='EFO_0000621'
[map][disease][OpenTargets] raw='Noonan Syndrome' -> id='MONDO_0018997'
[map][disease][OpenTargets] raw='Noonan syndrome 3' -> id='MONDO_0012371'
[map][disease][OpenTargets] raw='Obesity' -> id='EFO_0001073'
[map][disease][OpenTargets] raw='Obsessive-Compulsive Disorder' -> id='EFO_0004242'
[map][disease][OpenTargets] raw='Osteoarthritis' -> id='MONDO_0005178'
[map][disease][OpenTargets] raw='Osteosarcoma' -> id='EFO_0000637'
[map][disease][OpenTargets] raw='Ovarian Neoplasms' -> id='EFO_0003893'
[map][disease][OpenTargets] raw='Pancreatic Neoplasms' -> id='EFO_0003860'
[map][disease][OpenTargets] raw='Pancreatitis' -> id='EFO_0000278'
[map][disease][OpenTargets] raw='Papilloma' -> id='MONDO_0002363'
[map][disease][OpenTargets] raw='Parkinson Disease' -> id='MONDO_0005180'
[map][disease][OpenTargets] raw='Penile Neoplasms' -> id='EFO_1001094'
[map][disease][OpenTargets] raw='Pfeiffer type acrocephalosyndactyly' -> id='MONDO_0007043'
[map][disease][OpenTargets] raw='Pleural Effusion' -> id='HP_0002202'
[map][disease][OpenTargets] raw='Polycystic Ovary Syndrome' -> id='EFO_0000660'
[map][disease][OpenTargets] raw='Polyploidy' -> id='MONDO_0019934'
[map][disease][OpenTargets] raw='Posterior Leukoencephalopathy Syndrome' -> id='EFO_1001829'
[map][disease][OpenTargets] raw='Pre-Eclampsia' -> id='EFO_0000668'
[map][disease][OpenTargets] raw='Prostatic Hyperplasia' -> id='EFO_0000284'
[map][disease][OpenTargets] raw='Pruritus' -> id='HP_0000989'
[map][disease][OpenTargets] raw='Psoriasis' -> id='EFO_0000676'
[map][disease][OpenTargets] raw='Pulmonary Edema' -> id='EFO_1001134'
[map][disease][OpenTargets] raw='Pulmonary Fibrosis' -> id='EFO_0009448'
[map][disease][OpenTargets] raw='Pyridoxine-dependent epilepsy' -> id='MONDO_0009945'
[map][disease][OpenTargets] raw='Renal Insufficiency' -> id='EFO_1002048'
[map][disease][OpenTargets] raw='Rickets' -> id='EFO_0005583'
[map][disease][OpenTargets] raw='Sarcoma' -> id='EFO_0000691'
[map][disease][OpenTargets] raw='Schizophrenia' -> id='MONDO_0005090'
[map][disease][OpenTargets] raw='Seizures' -> id='HP_0001250'
[map][disease][OpenTargets] raw='Sezary Syndrome' -> id='EFO_1000785'
[map][disease][OpenTargets] raw='Silicosis' -> id='EFO_0007485'
[map][disease][OpenTargets] raw='Sjogren's Syndrome' -> id='EFO_0000699'
[map][disease][OpenTargets] raw='Skin Neoplasms' -> id='EFO_0004198'
[map][disease][OpenTargets] raw='Small Cell Lung Carcinoma' -> id='EFO_0000702'
[map][disease][OpenTargets] raw='Spinal Dysraphism' -> id='EFO_1001210'
[map][disease][OpenTargets] raw='Splenomegaly' -> id='HP_0001744'
[map][disease][OpenTargets] raw='Squamous Cell Carcinoma of Head and Neck' -> id='EFO_0000181'
[map][disease][OpenTargets] raw='Status Epilepticus' -> id='EFO_0008526'
[map][disease][OpenTargets] raw='Stevens-Johnson Syndrome' -> id='EFO_0004276'
[map][disease][OpenTargets] raw='Stomach Neoplasms' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='Stomatitis' -> id='EFO_0009688'
[map][disease][OpenTargets] raw='Stroke' -> id='EFO_0000712'
[map][disease][OpenTargets] raw='Substance Withdrawal Syndrome' -> id='EFO_0005800'
[map][disease][OpenTargets] raw='Tachycardia' -> id='HP_0001649'
[map][disease][OpenTargets] raw='Tetralogy of Fallot' -> id='HP_0001636'
[map][disease][OpenTargets] raw='Thymic epithelial tumor' -> id='MONDO_0018079'
[map][disease][OpenTargets] raw='Thymoma' -> id='EFO_1000581'
[map][disease][OpenTargets] raw='Thyroid Neoplasms' -> id='EFO_0003841'
[map][disease][OpenTargets] raw='Tongue Neoplasms' -> id='EFO_0003871'
[map][disease][OpenTargets] raw='Tooth Abnormalities' -> id='HP_0000164'
[map][disease][OpenTargets] raw='Tuberculosis' -> id='MONDO_0018076'
[map][disease][OpenTargets] raw='Unconsciousness' -> id='HP_0001259'
[map][disease][OpenTargets] raw='Unverricht-Lundborg Syndrome' -> id='MONDO_0009698'
[map][disease][OpenTargets] raw='Urinary Bladder Neoplasms' -> id='EFO_0000294'
[map][disease][OpenTargets] raw='Urogenital Neoplasms' -> id='EFO_0003863'
[map][disease][OpenTargets] raw='Urticaria' -> id='EFO_0005531'
[map][disease][OpenTargets] raw='Uterine Neoplasms' -> id='EFO_0003859'
[map][disease][OpenTargets] raw='Vitamin B 12 Deficiency' -> id='EFO_0000734'
[map][disease][OpenTargets] raw='Vomiting' -> id='HP_0002013'
[map][disease][OpenTargets] raw='Vulvar Lichen Sclerosus' -> id='EFO_1000623'
[map][disease][OpenTargets] raw='Weight Gain' -> id='HP_0004324'
[map][disease][OpenTargets] raw='Weight Loss' -> id='HP_0001824'
[map][disease][OpenTargets] raw='Williams Syndrome' -> id='MONDO_0008678'
[map][disease][OpenTargets] raw='Wilms Tumor' -> id='MONDO_0024676'

2026-02-27 17:45:15,510 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:15,513 [INFO] [LLM] Batch done in 2.75s
2026-02-27 17:45:15,590 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:15,593 [INFO] [LLM] Batch done in 2.84s
2026-02-27 17:45:17,676 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:17,679 [INFO] [LLM] Batch done in 4.92s
2026-02-27 17:45:17,680 [INFO] [LLM] 'AMYOTROPHIC LATERAL SCLEROSIS 12 WITH OR WITHOUT FRONTOTEMPORAL DEMENTIA' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,681 [INFO] [LLM] 'AMYOTROPHIC LATERAL SCLEROSIS 16, JUVENILE' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,682 [INFO] [LLM] 'AMYOTROPHIC LATERAL SCLEROSIS 19' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,682 [INFO] [LLM] 'Abnormalities, Multiple' → None
2026-02-27 17:45:17,683 [INFO] [LLM] 'Abortion, Spontaneous' → 'spontaneous abortion'
2026-02-27 17:45:17,683 [INFO] [LLM] 'Acidosis, Lactic' → 'lactic acidosis'
2026-02-27 17:45:17,684 [INFO] [LLM] 'Adenocarcinoma, Bronchiolo-Alveolar' → 'adenocarcinoma'
2026-02-27 17:45:17,684 [INFO] [LLM] 'Adenocarcinoma, Clear Cell' → 'adenocarcinoma'
2026-02-27 17:45:17,685 [INFO] [LLM] 'Adenocarcinoma, Follicular' → 'adenocarcinoma'
2026-02-27 17:45:17,685 [INFO] [LLM] 'Adrenocortical Carcinoma, Hereditary' → 'adrenocortical carcinoma'
2026-02-27 17:45:17,685 [INFO] [LLM] 'Alzheimer Disease, Familial, 3, with Spastic Paraparesis and Apraxia' → 'alzheimer disease'
2026-02-27 17:45:17,686 [INFO] [LLM] 'Alzheimer disease type 2' → 'alzheimer disease'
2026-02-27 17:45:17,686 [INFO] [LLM] 'Alzheimer disease type 4' → 'alzheimer disease'
2026-02-27 17:45:17,686 [INFO] [LLM] 'Amyotrophic Lateral Sclerosis 10' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,687 [INFO] [LLM] 'Amyotrophic Lateral Sclerosis 2, Juvenile' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,687 [INFO] [LLM] 'Amyotrophic Lateral Sclerosis 4, Juvenile' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,687 [INFO] [LLM] 'Amyotrophic Lateral Sclerosis 6, Autosomal Recessive' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,688 [INFO] [LLM] 'Amyotrophic Lateral Sclerosis 9' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,688 [INFO] [LLM] 'Amyotrophic lateral sclerosis 1' → 'amyotrophic lateral sclerosis'
2026-02-27 17:45:17,688 [INFO] [LLM] 'Anemia, Hemolytic' → 'hemolytic anemia'
2026-02-27 17:45:17,688 [INFO] [LLM] 'Anemia, Megaloblastic' → 'megaloblastic anemia'
2026-02-27 17:45:17,689 [INFO] [LLM] 'Angina Pectoris, Variant' → 'angina pectoris'
2026-02-27 17:45:17,689 [INFO] [LLM] 'Antley-Bixler Syndrome Phenotype' → 'antley-bixler syndrome'
2026-02-27 17:45:17,689 [INFO] [LLM] 'Aortic Valve, Calcification of' → None
2026-02-27 17:45:17,691 [INFO] [LLM] 'Arsenic Poisoning' → 'arsenic poisoning'
2026-02-27 17:45:17,691 [INFO] [LLM] 'Arthritis, Experimental' → None
2026-02-27 17:45:17,691 [INFO] [LLM] 'Arthritis, Juvenile' → 'juvenile arthritis'
2026-02-27 17:45:17,692 [INFO] [LLM] 'Arthritis, Psoriatic' → 'psoriatic arthritis'
2026-02-27 17:45:17,692 [INFO] [LLM] 'Arthritis, Rheumatoid' → 'rheumatoid arthritis'
2026-02-27 17:45:17,692 [INFO] [LLM] 'Bile Duct Neoplasms' → 'bile duct cancer'
2026-02-27 17:45:17,693 [INFO] [LLM] 'Biliary Tract Neoplasms' → 'biliary tract cancer'
2026-02-27 17:45:17,694 [INFO] [LLM] 'Bone Diseases, Developmental' → None
2026-02-27 17:45:17,694 [INFO] [LLM] 'Brain Injuries' → None
2026-02-27 17:45:17,695 [INFO] [LLM] 'Burns, Chemical' → 'chemical burn'
2026-02-27 17:45:17,695 [INFO] [LLM] 'CYSTIC FIBROSIS, MODIFIER OF, 1' → 'cystic fibrosis'
2026-02-27 17:45:17,695 [INFO] [LLM] 'Carcinogenesis' → None
2026-02-27 17:45:17,696 [INFO] [LLM] 'Carcinoma, Adenoid Cystic' → 'adenoid cystic carcinoma'
2026-02-27 17:45:17,696 [INFO] [LLM] 'Carcinoma, Basal Cell' → 'basal cell carcinoma'
2026-02-27 17:45:17,696 [INFO] [LLM] 'Carcinoma, Ductal' → 'ductal carcinoma'
2026-02-27 17:45:17,697 [INFO] [LLM] 'Carcinoma, Ductal, Breast' → 'breast cancer'
2026-02-27 17:45:17,697 [INFO] [LLM] 'Carcinoma, Hepatocellular' → 'hepatocellular carcinoma'
2026-02-27 17:45:17,698 [INFO] [LLM] 'Carcinoma, Lewis Lung' → 'lung cancer'
2026-02-27 17:45:17,698 [INFO] [LLM] 'Carcinoma, Non-Small-Cell Lung' → 'non-small cell lung cancer'
2026-02-27 17:45:17,698 [INFO] [LLM] 'Carcinoma, Ovarian Epithelial' → 'ovarian cancer'
2026-02-27 17:45:17,699 [INFO] [LLM] 'Carcinoma, Pancreatic Ductal' → 'pancreatic cancer'
2026-02-27 17:45:17,699 [INFO] [LLM] 'Carcinoma, Renal Cell' → 'renal cell carcinoma'
2026-02-27 17:45:17,700 [INFO] [LLM] 'Carcinoma, Small Cell' → 'small cell carcinoma'
2026-02-27 17:45:17,701 [INFO] [LLM] 'Carcinoma, Squamous Cell' → 'squamous cell carcinoma'
2026-02-27 17:45:17,701 [INFO] [LLM] 'Carcinoma, Transitional Cell' → 'transitional cell carcinoma'
2026-02-27 17:45:17,701 [INFO] [LLM] 'Cardiomyopathy, Dilated' → 'dilated cardiomyopathy'
2026-02-27 17:45:17,702 [INFO] [LLM] 'Cardiomyopathy, Hypertrophic' → 'hypertrophic cardiomyopathy'
2026-02-27 17:45:17,702 [INFO] [LLM] 'Cecal Neoplasms' → 'cecal cancer'
2026-02-27 17:45:17,702 [INFO] [LLM] 'Cell Transformation, Neoplastic' → None
2026-02-27 17:45:17,703 [INFO] [LLM] 'Central Nervous System Neoplasms' → 'central nervous system cancer'
2026-02-27 17:45:17,703 [INFO] [LLM] 'Chemical and Drug Induced Liver Injury' → 'liver injury'
2026-02-27 17:45:17,704 [INFO] [LLM] 'Cholestasis, Intrahepatic' → 'intrahepatic cholestasis'
2026-02-27 17:45:17,704 [INFO] [LLM] 'Chromosomal Instability' → None
2026-02-27 17:45:17,704 [INFO] [LLM] 'Chromosome 17 deletion' → None
2026-02-27 17:45:17,705 [INFO] [LLM] 'Chromosome Breakage' → None
2026-02-27 17:45:17,705 [INFO] [LLM] 'Clinical Deterioration' → None
2026-02-27 17:45:17,706 [INFO] [LLM] 'Cocaine-Related Disorders' → 'cocaine dependence'
2026-02-27 17:45:17,707 [INFO] [LLM] 'Cognition Disorders' → None
2026-02-27 17:45:17,707 [INFO] [LLM] 'Colitis, Ulcerative' → 'ulcerative colitis'
2026-02-27 17:45:17,708 [INFO] [LLM] 'Colonic Neoplasms' → 'colon cancer'
2026-02-27 17:45:17,708 [INFO] [LLM] 'Colorectal Cancer, Hereditary Nonpolyposis, Type 4' → 'colorectal cancer'
2026-02-27 17:45:17,708 [INFO] [LLM] 'Colorectal Cancer, Hereditary Nonpolyposis, Type 5' → 'colorectal cancer'
2026-02-27 17:45:17,709 [INFO] [LLM] 'Colorectal Cancer, Hereditary Nonpolyposis, Type 6' → 'colorectal cancer'
2026-02-27 17:45:17,709 [INFO] [LLM] 'Colorectal Cancer, Hereditary Nonpolyposis, Type 7' → 'colorectal cancer'
2026-02-27 17:45:17,710 [INFO] [LLM] 'Colorectal Cancer, Hereditary Nonpolyposis, Type 8' → 'colorectal cancer'
2026-02-27 17:45:17,710 [INFO] [LLM] 'Colorectal Neoplasms' → 'colorectal cancer'
2026-02-27 17:45:17,710 [INFO] [LLM] 'Colorectal Neoplasms, Hereditary Nonpolyposis' → 'colorectal cancer'
2026-02-27 17:45:17,711 [INFO] [LLM] 'Craniofacial Abnormalities' → None
2026-02-27 17:45:17,711 [INFO] [LLM] 'Craniosynostoses' → 'craniosynostosis'
2026-02-27 17:45:17,712 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 21' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,712 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 23' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,713 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 24' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,714 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 26' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,715 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 30' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,715 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 32' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,716 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 34' → 'developmental and epileptic encephalopathy'
2026-02-27 17:45:17,717 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 37' → None
2026-02-27 17:45:17,717 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 38' → None
2026-02-27 17:45:17,717 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 40' → None
2026-02-27 17:45:17,718 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 47' → None
2026-02-27 17:45:17,718 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 49' → None
2026-02-27 17:45:17,719 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 50' → None
2026-02-27 17:45:17,719 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 53' → None
2026-02-27 17:45:17,719 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 7' → None
2026-02-27 17:45:17,720 [INFO] [LLM] 'Demyelinating Diseases' → None
2026-02-27 17:45:17,725 [INFO] [LLM] 'Depressive Disorder, Major' → 'major depressive disorder'
2026-02-27 17:45:17,725 [INFO] [LLM] 'Diabetes Complications' → None
2026-02-27 17:45:17,726 [INFO] [LLM] 'Diabetes Mellitus, Experimental' → None
2026-02-27 17:45:17,727 [INFO] [LLM] 'Diabetes Mellitus, Type 2' → 'diabetes mellitus type 2'
2026-02-27 17:45:17,728 [INFO] [LLM] 'Diabetes, Gestational' → 'gestational diabetes'
2026-02-27 17:45:17,728 [INFO] [LLM] 'Disease Models, Animal' → None
2026-02-27 17:45:17,729 [INFO] [LLM] 'Disease Progression' → None
2026-02-27 17:45:17,729 [INFO] [LLM] 'Drug Eruptions' → None
2026-02-27 17:45:17,729 [INFO] [LLM] 'Drug Overdose' → None
2026-02-27 17:45:17,730 [INFO] [LLM] 'Drug-Related Side Effects and Adverse Reactions' → None
2026-02-27 17:45:17,730 [INFO] [LLM] 'Ductus Arteriosus, Patent' → 'patent ductus arteriosus'
2026-02-27 17:45:17,731 [INFO] [LLM] 'Dyskinesia, Drug-Induced' → None
2026-02-27 17:45:17,731 [INFO] [LLM] 'Dyslipidemias' → 'dyslipidemia'
2026-02-27 17:45:17,731 [INFO] [LLM] 'EPILEPSY, FAMILIAL TEMPORAL LOBE, 5' → None
2026-02-27 17:45:17,732 [INFO] [LLM] 'EPILEPSY, FAMILIAL TEMPORAL LOBE, 7' → None
2026-02-27 17:45:17,732 [INFO] [LLM] 'EPILEPSY, FOCAL, WITH SPEECH DISORDER AND WITH OR WITHOUT IMPAIRED INTELLECTUAL DEVELOPMENT' → None
2026-02-27 17:45:17,733 [INFO] [LLM] 'EPILEPSY, NOCTURNAL FRONTAL LOBE, 5' → None
2026-02-27 17:45:17,733 [INFO] [LLM] 'EPILEPSY, PROGRESSIVE MYOCLONIC, 3, WITH OR WITHOUT INTRACELLULAR INCLUSIONS' → None
2026-02-27 17:45:17,733 [INFO] [LLM] 'EPILEPSY, PROGRESSIVE MYOCLONIC, 4, WITH OR WITHOUT RENAL FAILURE' → None
2026-02-27 17:45:17,733 [INFO] [LLM] 'Epilepsies, Partial' → 'epilepsy, partial'
2026-02-27 17:45:17,734 [INFO] [LLM] 'Epilepsy, Absence' → 'absence epilepsy'
2026-02-27 17:45:17,734 [INFO] [LLM] 'Epilepsy, Complex Partial' → 'complex partial epilepsy'
2026-02-27 17:45:17,735 [INFO] [LLM] 'Epilepsy, Female-Restricted, with Mental Retardation' → None
2026-02-27 17:45:17,735 [INFO] [LLM] 'Epilepsy, Generalized' → 'generalized epilepsy'
2026-02-27 17:45:17,735 [INFO] [LLM] 'Epilepsy, Idiopathic Generalized' → 'idiopathic generalized epilepsy'
2026-02-27 17:45:17,736 [INFO] [LLM] 'Epilepsy, Partial, with Variable Foci' → None
2026-02-27 17:45:17,736 [INFO] [LLM] 'Epilepsy, Temporal Lobe' → 'temporal lobe epilepsy'
2026-02-27 17:45:17,737 [INFO] [LLM] 'Epilepsy, Tonic-Clonic' → 'tonic-clonic epilepsy'
2026-02-27 17:45:17,737 [INFO] [LLM] 'Epilepsy, X-Linked, with Variable Learning Disabilities and Behavior Disorders' → None
2026-02-27 17:45:17,737 [INFO] [LLM] 'Epileptic Encephalopathy, Early Infantile, 4' → None
2026-02-27 17:45:17,737 [INFO] [LLM] 'Esophageal Neoplasms' → 'esophageal cancer'
2026-02-27 17:45:17,738 [INFO] [LLM] 'Extensively Drug-Resistant Tuberculosis' → 'extensively drug-resistant tuberculosis'
2026-02-27 17:45:17,738 [INFO] [LLM] 'Familial Hypophosphatemic Rickets' → None
2026-02-27 17:45:17,739 [INFO] [LLM] 'Fractures, Bone' → 'bone fracture'
2026-02-27 17:45:17,739 [INFO] [LLM] 'Gait Disorders, Neurologic' → 'gait disorder'
2026-02-27 17:45:17,739 [INFO] [LLM] 'Gallbladder Neoplasms' → 'gallbladder cancer'
2026-02-27 17:45:17,740 [INFO] [LLM] 'Gastrointestinal Diseases' → None
2026-02-27 17:45:17,740 [INFO] [LLM] 'Generalized Epilepsy With Febrile Seizures Plus, Type 2' → None
2026-02-27 17:45:17,740 [INFO] [LLM] 'Granuloma, Plasma Cell' → None
2026-02-27 17:45:17,741 [INFO] [LLM] 'Hamartoma Syndrome, Multiple' → None
2026-02-27 17:45:17,741 [INFO] [LLM] 'Head and Neck Neoplasms' → 'head and neck cancer'
2026-02-27 17:45:17,742 [INFO] [LLM] 'Hepatic Encephalopathy' → 'hepatic encephalopathy'
2026-02-27 17:45:17,744 [INFO] [LLM] 'Hepatitis C, Chronic' → 'chronic hepatitis c'
2026-02-27 17:45:17,744 [INFO] [LLM] 'Hyperlipidemias' → 'hyperlipidemia'
2026-02-27 17:45:17,745 [INFO] [LLM] 'Hypertension, Pulmonary' → 'pulmonary hypertension'
2026-02-27 17:45:17,745 [INFO] [LLM] 'Infertility, Female' → 'female infertility'
2026-02-27 17:45:17,748 [INFO] [LLM] 'Infertility, Male' → 'male infertility'
2026-02-27 17:45:17,748 [INFO] [LLM] 'Inflammatory Breast Neoplasms' → 'inflammatory breast cancer'
2026-02-27 17:45:17,749 [INFO] [LLM] 'Intracranial Arteriovenous Malformations' → 'intracranial arteriovenous malformation'
2026-02-27 17:45:17,749 [INFO] [LLM] 'Jaundice, Obstructive' → 'obstructive jaundice'
2026-02-27 17:45:17,750 [INFO] [LLM] 'Latent Tuberculosis' → 'latent tuberculosis'
2026-02-27 17:45:17,751 [INFO] [LLM] 'Learning Disabilities' → None
2026-02-27 17:45:17,751 [INFO] [LLM] 'Leukemia, Lymphocytic, Chronic, B-Cell' → 'chronic lymphocytic leukemia'
2026-02-27 17:45:17,751 [INFO] [LLM] 'Leukemia, Megakaryoblastic, of Down Syndrome' → None
2026-02-27 17:45:17,752 [INFO] [LLM] 'Leukemia, Myelogenous, Chronic, BCR-ABL Positive' → 'chronic myeloid leukemia'
2026-02-27 17:45:17,752 [INFO] [LLM] 'Leukemia, Myeloid, Acute' → 'acute myeloid leukemia'
2026-02-27 17:45:17,753 [INFO] [LLM] 'Leukemia, Myeloid, Chronic-Phase' → None
2026-02-27 17:45:17,753 [INFO] [LLM] 'Leukemia, Myelomonocytic, Juvenile' → 'juvenile myelomonocytic leukemia'
2026-02-27 17:45:17,753 [INFO] [LLM] 'Leukemia, Promyelocytic, Acute' → 'acute promyelocytic leukemia'
2026-02-27 17:45:17,753 [INFO] [LLM] 'Limb Deformities, Congenital' → None
2026-02-27 17:45:17,754 [INFO] [LLM] 'Liver Diseases, Parasitic' → None
2026-02-27 17:45:17,754 [INFO] [LLM] 'Liver Failure, Acute' → 'acute liver failure'
2026-02-27 17:45:17,755 [INFO] [LLM] 'Liver Neoplasms' → 'liver cancer'
2026-02-27 17:45:17,756 [INFO] [LLM] 'Liver Neoplasms, Experimental' → None
2026-02-27 17:45:17,756 [INFO] [LLM] 'Lupus Erythematosus, Systemic' → 'systemic lupus erythematosus'
2026-02-27 17:45:17,757 [INFO] [LLM] 'Lymphoma, Large B-Cell, Diffuse' → 'diffuse large b-cell lymphoma'
2026-02-27 17:45:17,757 [INFO] [LLM] 'Lymphoma, Large-Cell, Anaplastic' → 'anaplastic large cell lymphoma'
2026-02-27 17:45:17,757 [INFO] [LLM] 'Lymphoma, T-Cell' → 't-cell lymphoma'
2026-02-27 17:45:17,757 [INFO] [LLM] 'Lymphoma, T-Cell, Cutaneous' → 'cutaneous t-cell lymphoma'
2026-02-27 17:45:17,758 [INFO] [LLM] 'MYOCLONIC EPILEPSY, FAMILIAL INFANTILE' → None
2026-02-27 17:45:17,759 [INFO] [LLM] 'Macrocephaly Autism Syndrome' → None
2026-02-27 17:45:17,759 [INFO] [LLM] 'Mammary Neoplasms, Animal' → None
2026-02-27 17:45:17,760 [INFO] [LLM] 'Mammary Neoplasms, Experimental' → None
2026-02-27 17:45:17,760 [INFO] [LLM] 'Mandibular Neoplasms' → 'mandibular neoplasm'
2026-02-27 17:45:17,761 [INFO] [LLM] 'Melanoma, Cutaneous Malignant' → 'melanoma'
2026-02-27 17:45:17,761 [INFO] [LLM] 'Melanoma, Experimental' → None
2026-02-27 17:45:17,762 [INFO] [LLM] 'Memory Disorders' → None
2026-02-27 17:45:17,763 [INFO] [LLM] 'Mental Retardation, X-Linked, with Epilepsy' → None
2026-02-27 17:45:17,763 [INFO] [LLM] 'Mesothelioma, Malignant' → 'malignant mesothelioma'
2026-02-27 17:45:17,764 [INFO] [LLM] 'Micronuclei, Chromosome-Defective' → None
2026-02-27 17:45:17,764 [INFO] [LLM] 'Microsatellite Instability' → None
2026-02-27 17:45:17,764 [INFO] [LLM] 'Migraine Disorders' → 'migraine'
2026-02-27 17:45:17,765 [INFO] [LLM] 'Mitochondrial Diseases' → 'mitochondrial disease'
2026-02-27 17:45:17,765 [INFO] [LLM] 'Motor Skills Disorders' → None
2026-02-27 17:45:17,766 [INFO] [LLM] 'Multiple Sclerosis, Relapsing-Remitting' → 'multiple sclerosis'
2026-02-27 17:45:17,767 [INFO] [LLM] 'Myeloproliferative Disorders' → 'myeloproliferative neoplasm'
2026-02-27 17:45:17,768 [INFO] [LLM] 'Myoclonic Epilepsy, Juvenile' → 'juvenile myoclonic epilepsy'
2026-02-27 17:45:17,768 [INFO] [LLM] 'NEONATAL NEPHROCUTANEOUS INFLAMMATORY SYNDROME' → None
2026-02-27 17:45:17,769 [INFO] [LLM] 'Neoplasm Invasiveness' → None
2026-02-27 17:45:17,769 [INFO] [LLM] 'Neoplasm Recurrence, Local' → None
2026-02-27 17:45:17,770 [INFO] [LLM] 'Neoplasms' → 'neoplasm'
2026-02-27 17:45:17,771 [INFO] [LLM] 'Neoplasms, Experimental' → None
2026-02-27 17:45:17,772 [INFO] [LLM] 'Neovascularization, Pathologic' → None
2026-02-27 17:45:17,773 [INFO] [LLM] 'Nerve Sheath Neoplasms' → 'nerve sheath tumor'
2026-02-27 17:45:17,773 [INFO] [LLM] 'Nervous System Diseases' → None
2026-02-27 17:45:17,774 [INFO] [LLM] 'Neuroendocrine Tumors' → 'neuroendocrine tumor'
2026-02-27 17:45:17,775 [INFO] [LLM] 'Nevus, Sebaceous of Jadassohn' → 'nevus sebaceous'
2026-02-27 17:45:17,775 [INFO] [LLM] 'Nystagmus, Pathologic' → None
2026-02-27 17:45:17,776 [INFO] [LLM] 'Papilloma, Choroid Plexus' → 'choroid plexus papilloma'
2026-02-27 17:45:17,777 [INFO] [LLM] 'Parkinson Disease 6, Autosomal Recessive Early-Onset' → 'parkinson disease'
2026-02-27 17:45:17,777 [INFO] [LLM] 'Parkinson Disease, Secondary' → 'parkinson disease'
2026-02-27 17:45:17,778 [INFO] [LLM] "Pediatric Crohn's disease" → 'crohn disease'
2026-02-27 17:45:17,778 [INFO] [LLM] 'Peripheral Nervous System Diseases' → None
2026-02-27 17:45:17,779 [INFO] [LLM] 'Personality Disorders' → None
2026-02-27 17:45:17,779 [INFO] [LLM] 'Plagiocephaly, Nonsynostotic' → 'plagiocephaly'
2026-02-27 17:45:17,780 [INFO] [LLM] 'Plasma Cell Granuloma, Pulmonary' → None
2026-02-27 17:45:17,781 [INFO] [LLM] 'Polycystic Kidney, Autosomal Recessive' → 'polycystic kidney disease'
2026-02-27 17:45:17,782 [INFO] [LLM] 'Polyhydramnios, Megalencephaly, And Symptomatic Epilepsy' → None
2026-02-27 17:45:17,782 [INFO] [LLM] 'Precancerous Conditions' → None
2026-02-27 17:45:17,783 [INFO] [LLM] 'Precursor Cell Lymphoblastic Leukemia-Lymphoma' → 'precursor t-cell lymphoblastic leukemia-lymphoma'
2026-02-27 17:45:17,783 [INFO] [LLM] 'Prenatal Exposure Delayed Effects' → None
2026-02-27 17:45:17,784 [INFO] [LLM] 'Prostatic Neoplasms' → 'prostate cancer'
2026-02-27 17:45:17,784 [INFO] [LLM] 'Pulmonary Disease, Chronic Obstructive' → 'chronic obstructive pulmonary disease'
2026-02-27 17:45:17,784 [INFO] [LLM] 'Rectal Neoplasms' → 'rectal cancer'
2026-02-27 17:45:17,785 [INFO] [LLM] 'Recurrence' → None
2026-02-27 17:45:17,785 [INFO] [LLM] 'Rheumatoid Arthritis, Systemic Juvenile' → 'juvenile rheumatoid arthritis'
2026-02-27 17:45:17,786 [INFO] [LLM] 'SEIZURES, BENIGN FAMILIAL INFANTILE, 5' → None
2026-02-27 17:45:17,787 [INFO] [LLM] 'Scaphocephaly, Maxillary Retrusion, And Mental Retardation' → None
2026-02-27 17:45:17,788 [INFO] [LLM] 'Schizophrenia Spectrum and Other Psychotic Disorders' → None
2026-02-27 17:45:17,788 [INFO] [LLM] 'Schizophrenia, Paranoid' → 'schizophrenia'
2026-02-27 17:45:17,788 [INFO] [LLM] 'Skin Abnormalities' → None
2026-02-27 17:45:17,789 [INFO] [LLM] 'Skin Diseases' → None
2026-02-27 17:45:17,789 [INFO] [LLM] 'Substance-Related Disorders' → None
2026-02-27 17:45:17,790 [INFO] [LLM] 'Sudden Infant Death' → 'sudden infant death syndrome'
2026-02-27 17:45:17,790 [INFO] [LLM] 'Teratogenesis' → None
2026-02-27 17:45:17,791 [INFO] [LLM] 'Thymus Neoplasms' → 'thymoma'
2026-02-27 17:45:17,791 [INFO] [LLM] 'Thyroid Cancer, Papillary' → 'papillary thyroid carcinoma'
2026-02-27 17:45:17,791 [INFO] [LLM] 'Thyroid cancer, follicular' → 'follicular thyroid cancer'
2026-02-27 17:45:17,792 [INFO] [LLM] 'Triple Negative Breast Neoplasms' → 'triple-negative breast cancer'

[map][disease][Llama] raw='AMYOTROPHIC LATERAL SCLEROSIS 12 WITH OR WITHOUT FRONTOTEMPORAL DEMENTIA' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='AMYOTROPHIC LATERAL SCLEROSIS 16, JUVENILE' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='AMYOTROPHIC LATERAL SCLEROSIS 19' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Abortion, Spontaneous' -> canonical='spontaneous abortion' -> id='EFO_1001255'
[map][disease][Llama] raw='Acidosis, Lactic' -> canonical='lactic acidosis' -> id='EFO_1000036'
[map][disease][Llama] raw='Adenocarcinoma, Bronchiolo-Alveolar' -> canonical='adenocarcinoma' -> id='EFO_0000228'
[map][disease][Llama] raw='Adenocarcinoma, Clear Cell' -> canonical='adenocarcinoma' -> id='EFO_0000228'
[map][disease][Llama] raw='Adenocarcinoma, Follicular' -> canonical='adenocarcinoma' -> id='EFO_0000228'
[map][disease][Llama] raw='Adrenocortical Carcinoma, Hereditary' -> canonical='adrenal cortex carcinoma' -> id='EFO_1000796'
[map][disease][Llama] raw='Alzheimer Disease, Familial, 3, with Spastic Paraparesis and Apraxia' -> canonical='Alzheimer disease type 1' -> id='MONDO_0007088'
[map][disease][Llama] raw='Alzheimer disease type 2' -> canonical='Alzheimer disease type 1' -> id='MONDO_0007088'
[map][disease][Llama] raw='Alzheimer disease type 4' -> canonical='Alzheimer disease type 1' -> id='MONDO_0007088'
[map][disease][Llama] raw='Amyotrophic Lateral Sclerosis 10' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Amyotrophic Lateral Sclerosis 2, Juvenile' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Amyotrophic Lateral Sclerosis 4, Juvenile' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Amyotrophic Lateral Sclerosis 6, Autosomal Recessive' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Amyotrophic Lateral Sclerosis 9' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Amyotrophic lateral sclerosis 1' -> canonical='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][Llama] raw='Anemia, Hemolytic' -> canonical='hemolytic anemia' -> id='EFO_0005558'
[map][disease][Llama] raw='Anemia, Megaloblastic' -> canonical='megaloblastic anemia' -> id='MONDO_0001700'
[map][disease][Llama] raw='Angina Pectoris, Variant' -> canonical='angina pectoris' -> id='EFO_0003913'
[map][disease][Llama] raw='Antley-Bixler Syndrome Phenotype' -> canonical='Antley-Bixler syndrome' -> id='MONDO_0008803'
[map][disease][Llama] raw='Arthritis, Juvenile' -> canonical='juvenile idiopathic arthritis' -> id='EFO_0002609'
[map][disease][Llama] raw='Arthritis, Psoriatic' -> canonical='psoriatic arthritis' -> id='EFO_0003778'
[map][disease][Llama] raw='Arthritis, Rheumatoid' -> canonical='rheumatoid arthritis' -> id='EFO_0000685'
[map][disease][Llama] raw='Bile Duct Neoplasms' -> canonical='bile duct carcinoma' -> id='EFO_0005540'
[map][disease][Llama] raw='Biliary Tract Neoplasms' -> canonical='biliary tract cancer' -> id='MONDO_0003060'
[map][disease][Llama] raw='Burns, Chemical' -> canonical='caustic injury' -> id='EFO_0009503'
[map][disease][Llama] raw='CYSTIC FIBROSIS, MODIFIER OF, 1' -> canonical='cystic fibrosis' -> id='MONDO_0009061'
[map][disease][Llama] raw='Carcinoma, Adenoid Cystic' -> canonical='adrenal cortex carcinoma' -> id='EFO_1000796'
[map][disease][Llama] raw='Carcinoma, Basal Cell' -> canonical='basal cell carcinoma' -> id='EFO_0004193'
[map][disease][Llama] raw='Carcinoma, Ductal' -> canonical='breast ductal adenocarcinoma' -> id='EFO_0006318'
[map][disease][Llama] raw='Carcinoma, Ductal, Breast' -> canonical='breast carcinoma' -> id='EFO_0000305'
[map][disease][Llama] raw='Carcinoma, Hepatocellular' -> canonical='hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][Llama] raw='Carcinoma, Lewis Lung' -> canonical='lung carcinoma' -> id='EFO_0001071'
[map][disease][Llama] raw='Carcinoma, Non-Small-Cell Lung' -> canonical='non-small cell lung carcinoma' -> id='EFO_0003060'
[map][disease][Llama] raw='Carcinoma, Ovarian Epithelial' -> canonical='ovarian carcinoma' -> id='EFO_0001075'
[map][disease][Llama] raw='Carcinoma, Pancreatic Ductal' -> canonical='pancreatic carcinoma' -> id='EFO_0002618'
[map][disease][Llama] raw='Carcinoma, Renal Cell' -> canonical='renal cell carcinoma' -> id='EFO_0000681'
[map][disease][Llama] raw='Carcinoma, Small Cell' -> canonical='small cell carcinoma' -> id='EFO_0008524'
[map][disease][Llama] raw='Carcinoma, Squamous Cell' -> canonical='squamous cell carcinoma' -> id='EFO_0000707'
[map][disease][Llama] raw='Carcinoma, Transitional Cell' -> canonical='Transitional Cell Carcinoma' -> id='EFO_1000601'
[map][disease][Llama] raw='Cardiomyopathy, Dilated' -> canonical='dilated cardiomyopathy' -> id='EFO_0000407'
[map][disease][Llama] raw='Cardiomyopathy, Hypertrophic' -> canonical='hypertrophic cardiomyopathy' -> id='EFO_0000538'
[map][disease][Llama] raw='Cecal Neoplasms' -> canonical='cecum carcinoma' -> id='EFO_1000021'
[map][disease][Llama] raw='Central Nervous System Neoplasms' -> canonical='central nervous system cancer' -> id='EFO_0000326'
[map][disease][Llama] raw='Cholestasis, Intrahepatic' -> canonical='intrahepatic cholestasis' -> id='MONDO_0019072'
[map][disease][Llama] raw='Cocaine-Related Disorders' -> canonical='cocaine dependence' -> id='EFO_0002610'
[map][disease][Llama] raw='Colitis, Ulcerative' -> canonical='ulcerative colitis' -> id='EFO_0000729'
[map][disease][Llama] raw='Colonic Neoplasms' -> canonical='colon carcinoma' -> id='EFO_1001950'
[map][disease][Llama] raw='Colorectal Cancer, Hereditary Nonpolyposis, Type 4' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Colorectal Cancer, Hereditary Nonpolyposis, Type 5' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Colorectal Cancer, Hereditary Nonpolyposis, Type 6' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Colorectal Cancer, Hereditary Nonpolyposis, Type 7' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Colorectal Cancer, Hereditary Nonpolyposis, Type 8' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Colorectal Neoplasms' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Colorectal Neoplasms, Hereditary Nonpolyposis' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='Craniosynostoses' -> canonical='craniosynostosis' -> id='MONDO_0015469'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 21' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 23' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 24' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 26' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 30' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 32' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 34' -> canonical='developmental and epileptic encephalopathy' -> id='MONDO_0100620'
[map][disease][Llama] raw='Depressive Disorder, Major' -> canonical='major depressive disorder' -> id='MONDO_0002009'
[map][disease][Llama] raw='Diabetes Mellitus, Type 2' -> canonical='type 2 diabetes mellitus' -> id='MONDO_0005148'
[map][disease][Llama] raw='Diabetes, Gestational' -> canonical='gestational diabetes' -> id='EFO_0004593'
[map][disease][Llama] raw='Ductus Arteriosus, Patent' -> canonical='Patent ductus arteriosus' -> id='HP_0001643'
[map][disease][Llama] raw='Dyslipidemias' -> canonical='inherited lipid metabolism disorder' -> id='MONDO_0002525'
[map][disease][Llama] raw='Epilepsy, Complex Partial' -> canonical='complex partial epilepsy' -> id='EFO_1000877'
[map][disease][Llama] raw='Epilepsy, Generalized' -> canonical='generalised epilepsy' -> id='EFO_0005917'
[map][disease][Llama] raw='Epilepsy, Idiopathic Generalized' -> canonical='generalised epilepsy' -> id='EFO_0005917'
[map][disease][Llama] raw='Epilepsy, Temporal Lobe' -> canonical='temporal lobe epilepsy' -> id='EFO_0000773'
[map][disease][Llama] raw='Epilepsy, Tonic-Clonic' -> canonical='epilepsy with generalized tonic-clonic seizures' -> id='EFO_0007262'
[map][disease][Llama] raw='Esophageal Neoplasms' -> canonical='esophageal carcinoma' -> id='EFO_0002916'
[map][disease][Llama] raw='Fractures, Bone' -> canonical='bone fracture' -> id='EFO_0003931'
[map][disease][Llama] raw='Gallbladder Neoplasms' -> canonical='gallbladder carcinoma' -> id='EFO_1001956'
[map][disease][Llama] raw='Head and Neck Neoplasms' -> canonical='head and neck malignant neoplasia' -> id='EFO_0006859'
[map][disease][Llama] raw='Hepatitis C, Chronic' -> canonical='hepatitis C virus infection' -> id='EFO_0003047'
[map][disease][Llama] raw='Hyperlipidemias' -> canonical='hyperlipidemia' -> id='MONDO_0021187'
[map][disease][Llama] raw='Hypertension, Pulmonary' -> canonical='pulmonary arterial hypertension' -> id='EFO_0001361'
[map][disease][Llama] raw='Infertility, Female' -> canonical='female infertility' -> id='EFO_0008560'
[map][disease][Llama] raw='Infertility, Male' -> canonical='male infertility' -> id='EFO_0004248'
[map][disease][Llama] raw='Inflammatory Breast Neoplasms' -> canonical='inflammatory breast carcinoma' -> id='EFO_1000984'
[map][disease][Llama] raw='Intracranial Arteriovenous Malformations' -> canonical='arteriovenous malformations of the brain' -> id='MONDO_0007154'
[map][disease][Llama] raw='Jaundice, Obstructive' -> canonical='obstructive jaundice' -> id='EFO_1001068'
[map][disease][Llama] raw='Leukemia, Lymphocytic, Chronic, B-Cell' -> canonical='chronic lymphocytic leukemia' -> id='EFO_0000095'
[map][disease][Llama] raw='Leukemia, Myelogenous, Chronic, BCR-ABL Positive' -> canonical='chronic myelogenous leukemia' -> id='EFO_0000339'
[map][disease][Llama] raw='Leukemia, Myeloid, Acute' -> canonical='acute myeloid leukemia' -> id='EFO_0000222'
[map][disease][Llama] raw='Leukemia, Myelomonocytic, Juvenile' -> canonical='Juvenile Myelomonocytic Leukemia' -> id='EFO_1000309'
[map][disease][Llama] raw='Leukemia, Promyelocytic, Acute' -> canonical='acute promyelocytic leukemia' -> id='EFO_0000224'
[map][disease][Llama] raw='Liver Failure, Acute' -> canonical='acute liver failure' -> id='MONDO_0019542'
[map][disease][Llama] raw='Liver Neoplasms' -> canonical='hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][Llama] raw='Lupus Erythematosus, Systemic' -> canonical='systemic lupus erythematosus' -> id='MONDO_0007915'
[map][disease][Llama] raw='Lymphoma, Large B-Cell, Diffuse' -> canonical='diffuse large B-cell lymphoma' -> id='EFO_0000403'
[map][disease][Llama] raw='Lymphoma, Large-Cell, Anaplastic' -> canonical='anaplastic large cell lymphoma' -> id='EFO_0003032'
[map][disease][Llama] raw='Lymphoma, T-Cell' -> canonical='T-cell non-Hodgkin lymphoma' -> id='MONDO_0015760'
[map][disease][Llama] raw='Lymphoma, T-Cell, Cutaneous' -> canonical='Cutaneous T-cell lymphoma' -> id='EFO_0002913'
[map][disease][Llama] raw='Mandibular Neoplasms' -> canonical='mandibular cancer' -> id='EFO_0007356'
[map][disease][Llama] raw='Melanoma, Cutaneous Malignant' -> canonical='melanoma' -> id='EFO_0000756'
[map][disease][Llama] raw='Mesothelioma, Malignant' -> canonical='Malignant Mesothelioma' -> id='EFO_1000355'
[map][disease][Llama] raw='Migraine Disorders' -> canonical='migraine disorder' -> id='MONDO_0005277'
[map][disease][Llama] raw='Mitochondrial Diseases' -> canonical='mitochondrial disease' -> id='MONDO_0044970'
[map][disease][Llama] raw='Multiple Sclerosis, Relapsing-Remitting' -> canonical='multiple sclerosis' -> id='MONDO_0005301'
[map][disease][Llama] raw='Myeloproliferative Disorders' -> canonical='chronic myeloproliferative disorder' -> id='EFO_0002428'
[map][disease][Llama] raw='Myoclonic Epilepsy, Juvenile' -> canonical='juvenile myoclonic epilepsy' -> id='MONDO_0009696'
[map][disease][Llama] raw='Neoplasms' -> canonical='neoplasm' -> id='EFO_0000616'
[map][disease][Llama] raw='Nerve Sheath Neoplasms' -> canonical='neurofibroma' -> id='EFO_0000622'
[map][disease][Llama] raw='Neuroendocrine Tumors' -> canonical='neuroendocrine neoplasm' -> id='EFO_1001901'
[map][disease][Llama] raw='Papilloma, Choroid Plexus' -> canonical='choroid plexus papilloma' -> id='MONDO_0009837'
[map][disease][Llama] raw='Parkinson Disease 6, Autosomal Recessive Early-Onset' -> canonical='Parkinson disease' -> id='MONDO_0005180'
[map][disease][Llama] raw='Parkinson Disease, Secondary' -> canonical='Parkinson disease' -> id='MONDO_0005180'
[map][disease][Llama] raw='Pediatric Crohn's disease' -> canonical='Crohn's disease' -> id='EFO_0000384'
[map][disease][Llama] raw='Plagiocephaly, Nonsynostotic' -> canonical='Plagiocephaly' -> id='HP_0001357'
[map][disease][Llama] raw='Polycystic Kidney, Autosomal Recessive' -> canonical='Polycystic Kidney Disease' -> id='EFO_0008620'
[map][disease][Llama] raw='Precursor Cell Lymphoblastic Leukemia-Lymphoma' -> canonical='precursor T-cell lymphoblastic leukemia-lymphoma' -> id='EFO_1001830'
[map][disease][Llama] raw='Prostatic Neoplasms' -> canonical='prostate carcinoma' -> id='EFO_0001663'
[map][disease][Llama] raw='Pulmonary Disease, Chronic Obstructive' -> canonical='chronic obstructive pulmonary disease' -> id='EFO_0000341'
[map][disease][Llama] raw='Rectal Neoplasms' -> canonical='rectum cancer' -> id='EFO_1000657'
[map][disease][Llama] raw='Rheumatoid Arthritis, Systemic Juvenile' -> canonical='juvenile idiopathic arthritis' -> id='EFO_0002609'
[map][disease][Llama] raw='Schizophrenia, Paranoid' -> canonical='schizophrenia' -> id='MONDO_0005090'
[map][disease][Llama] raw='Sudden Infant Death' -> canonical='sudden infant death syndrome' -> id='EFO_0005303'
[map][disease][Llama] raw='Thymus Neoplasms' -> canonical='Thymoma' -> id='EFO_1000581'
[map][disease][Llama] raw='Thyroid Cancer, Papillary' -> canonical='papillary thyroid carcinoma' -> id='EFO_0000641'
[map][disease][Llama] raw='Thyroid cancer, follicular' -> canonical='follicular thyroid carcinoma' -> id='EFO_0000501'
[map][disease][Llama] raw='Triple Negative Breast Neoplasms' -> canonical='triple-negative breast cancer' -> id='EFO_0005537'
[map][disease][Llama] raw='Tuberculoma, Intracranial' -> canonical='central nervous system tuberculosis' -> id='EFO_0007199'
[map][disease][Llama] raw='Tuberculosis, Central Nervous System' -> canonical='central nervous system tuberculosis' -> id='EFO_0007199'
[map][disease][Llama] raw='Tuberculosis, Gastrointestinal' -> canonical='gastrointestinal tuberculosis' -> id='EFO_0007280'
[map][disease][Llama] raw='Tuberculosis, Lymph Node' -> canonical='lymph node tuberculosis' -> id='EFO_0007350'
[map][disease][Llama] raw='Tuberculosis, Meningeal' -> canonical='meningeal tuberculosis' -> id='EFO_1000039'
[map][disease][Llama] raw='Tuberculosis, Miliary' -> canonical='miliary tuberculosis' -> id='EFO_0007368'
[map][disease][Llama] raw='Tuberculosis, Multidrug-Resistant' -> canonical='multidrug-resistant tuberculosis' -> id='EFO_0007381'
[map][disease][Llama] raw='Tuberculosis, Pleural' -> canonical='pleural tuberculosis' -> id='EFO_0007446'
[map][disease][Llama] raw='Tuberculosis, Pulmonary' -> canonical='pulmonary tuberculosis' -> id='EFO_1000049'
[map][disease][Llama] raw='Tuberculosis, Renal' -> canonical='renal tuberculosis' -> id='EFO_0007463'
[map][disease][Llama] raw='Uterine Cervical Neoplasms' -> canonical='cervical carcinoma' -> id='EFO_0001061'
[warn] Unresolved diseases after OpenTargets/Llama/OLS: ['Abnormalities, Multiple', 'Aortic Valve, Calcification of', 'Arsenic Poisoning', 'Arthritis, Experimental', 'Bone Diseases, Developmental', 'Brain Injuries', 'Carcinogenesis', 'Cell Transformation, Neoplastic', 'Chemical and Drug Induced Liver Injury', 'Chromosomal Instability', 'Chromosome 17 deletion', 'Chromosome Breakage', 'Clinical Deterioration', 'Cognition Disorders', 'Craniofacial Abnormalities', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 37', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 38', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 40', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 47', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 49', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 50', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 53', 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 7', 'Demyelinating Diseases', 'Diabetes Complications', 'Diabetes Mellitus, Experimental', 'Disease Models, Animal', 'Disease Progression', 'Drug Eruptions', 'Drug Overdose', 'Drug-Related Side Effects and Adverse Reactions', 'Dyskinesia, Drug-Induced', 'EPILEPSY, FAMILIAL TEMPORAL LOBE, 5', 'EPILEPSY, FAMILIAL TEMPORAL LOBE, 7', 'EPILEPSY, FOCAL, WITH SPEECH DISORDER AND WITH OR WITHOUT IMPAIRED INTELLECTUAL DEVELOPMENT', 'EPILEPSY, NOCTURNAL FRONTAL LOBE, 5', 'EPILEPSY, PROGRESSIVE MYOCLONIC, 3, WITH OR WITHOUT INTRACELLULAR INCLUSIONS', 'EPILEPSY, PROGRESSIVE MYOCLONIC, 4, WITH OR WITHOUT RENAL FAILURE', 'Epilepsies, Partial', 'Epilepsy, Absence', 'Epilepsy, Female-Restricted, with Mental Retardation', 'Epilepsy, Partial, with Variable Foci', 'Epilepsy, X-Linked, with Variable Learning Disabilities and Behavior Disorders', 'Epileptic Encephalopathy, Early Infantile, 4', 'Extensively Drug-Resistant Tuberculosis', 'Familial Hypophosphatemic Rickets', 'Gait Disorders, Neurologic', 'Gastrointestinal Diseases', 'Generalized Epilepsy With Febrile Seizures Plus, Type 2', 'Granuloma, Plasma Cell', 'Hamartoma Syndrome, Multiple', 'Hepatic Encephalopathy', 'Latent Tuberculosis', 'Learning Disabilities', 'Leukemia, Megakaryoblastic, of Down Syndrome', 'Leukemia, Myeloid, Chronic-Phase', 'Limb Deformities, Congenital', 'Liver Diseases, Parasitic', 'Liver Neoplasms, Experimental', 'MYOCLONIC EPILEPSY, FAMILIAL INFANTILE', 'Macrocephaly Autism Syndrome', 'Mammary Neoplasms, Animal', 'Mammary Neoplasms, Experimental', 'Melanoma, Experimental', 'Memory Disorders', 'Mental Retardation, X-Linked, with Epilepsy', 'Micronuclei, Chromosome-Defective', 'Microsatellite Instability', 'Motor Skills Disorders', 'NEONATAL NEPHROCUTANEOUS INFLAMMATORY SYNDROME', 'Neoplasm Invasiveness', 'Neoplasm Recurrence, Local', 'Neoplasms, Experimental', 'Neovascularization, Pathologic', 'Nervous System Diseases', 'Nevus, Sebaceous of Jadassohn', 'Nystagmus, Pathologic', 'Peripheral Nervous System Diseases', 'Personality Disorders', 'Plasma Cell Granuloma, Pulmonary', 'Polyhydramnios, Megalencephaly, And Symptomatic Epilepsy', 'Precancerous Conditions', 'Prenatal Exposure Delayed Effects', 'Recurrence', 'SEIZURES, BENIGN FAMILIAL INFANTILE, 5', 'Scaphocephaly, Maxillary Retrusion, And Mental Retardation', 'Schizophrenia Spectrum and Other Psychotic Disorders', 'Skin Abnormalities', 'Skin Diseases', 'Substance-Related Disorders', 'Teratogenesis', 'Tuberculosis, Bovine', 'Tuberculosis, Osteoarticular', 'Tuberculosis, Spinal', 'Urologic Neoplasms', 'Vasculitis, Leukocytoclastic, Cutaneous', 'Ventricular Dysfunction, Left', 'Vision Disorders']

,disease_name,disease_id,source
0,AMYOTROPHIC LATERAL SCLEROSIS 12 WITH OR WITHO...,MONDO_0004976,Llama
1,AMYOTROPHIC LATERAL SCLEROSIS 15 WITH OR WITHO...,MONDO_0010459,OpenTargets
2,"AMYOTROPHIC LATERAL SCLEROSIS 16, JUVENILE",MONDO_0004976,Llama
3,AMYOTROPHIC LATERAL SCLEROSIS 18,MONDO_0013891,OpenTargets
4,AMYOTROPHIC LATERAL SCLEROSIS 19,MONDO_0004976,Llama
...,...,...,...
489,Vulvar Lichen Sclerosus,EFO_1000623,OpenTargets
490,Weight Gain,HP_0004324,OpenTargets
491,Weight Loss,HP_0001824,OpenTargets
492,Williams Syndrome,MONDO_0008678,OpenTargets
493,Wilms Tumor,MONDO_0024676,OpenTargets

In [15]:
df_disease["source"].value_counts()

source
OpenTargets    258
Llama          138
Name: count, dtype: int64

In [16]:
df_disease[df_disease.isna().any(axis=1)]

                                disease_name disease_id source
9                    Abnormalities, Multiple       None   None
56            Aortic Valve, Calcification of       None   None
57                         Arsenic Poisoning       None   None
58                   Arthritis, Experimental       None   None
74              Bone Diseases, Developmental       None   None
..                                       ...        ...    ...
475                     Tuberculosis, Spinal       None   None
480                       Urologic Neoplasms       None   None
484  Vasculitis, Leukocytoclastic, Cutaneous       None   None
485            Ventricular Dysfunction, Left       None   None
486                         Vision Disorders       None   None

[98 rows x 3 columns]

In [17]:
# ------------------------------------------------------------------
# Disease canonical audit (OpenTargets-strict IDs only)
# ------------------------------------------------------------------
# IMPORTANT:
# - This cell runs an additional Llama canonicalization pass over unresolved rows.
# - IDs are still resolved ONLY via OpenTargets mapIds (score==1).
# - To avoid changing the baseline resolver output, writeback is OFF by default.
APPLY_AUDIT_MAPPINGS = False

# 1) Rows unresolved after primary resolver
unresolved_rows = df_disease[df_disease["disease_id"].isna()].reset_index(drop=True)
unresolved_raw_names = list(
    dict.fromkeys(
        str(name).strip()
        for name in unresolved_rows["disease_name"].dropna().astype(str).tolist()
        if str(name).strip()
    )
)

# 2) Llama canonicalization suggestions
disease_input_map = {name: None for name in unresolved_raw_names}
canonicalisation_map = await utility.canonicalise_disease_dict(disease_input_map)

# 3) OpenTargets strict verification (score==1 only)
canonical_terms_norm = list(
    dict.fromkeys(
        utility._normalize_disease_term(v)
        for v in canonicalisation_map.values()
        if isinstance(v, str) and v.strip()
    )
)
canonical_to_id = utility.resolve_diseases_opentargets_bulk(
    canonical_terms_norm,
    strict_score_one=True,
)

# 4) Build persistent audit table
audit_rows = []
applied_count = 0
candidate_count = 0

for raw_disease_name in unresolved_raw_names:
    canonical_name = canonicalisation_map.get(raw_disease_name)
    if isinstance(canonical_name, str) and canonical_name.strip():
        canonical_name = canonical_name.strip()
        canonical_norm = utility._normalize_disease_term(canonical_name)
        resolved_id = canonical_to_id.get(canonical_norm)
    else:
        canonical_name = None
        canonical_norm = None
        resolved_id = None

    can_apply = bool(resolved_id)
    if can_apply:
        candidate_count += 1
        print(f"[audit][disease][Llama->OT] raw='{raw_disease_name}' -> canonical='{canonical_name}' -> id='{resolved_id}'")

    if can_apply and APPLY_AUDIT_MAPPINGS:
        mask = df_disease["disease_name"].astype(str).str.strip() == raw_disease_name
        df_disease.loc[mask, "disease_id"] = resolved_id
        df_disease.loc[mask, "source"] = "Llama"
        applied_count += 1

    status = (
        "mappable_ot_exact" if can_apply else
        ("no_canonical" if canonical_name is None else "canonical_not_in_ot")
    )
    audit_rows.append({
        "raw_disease_name": raw_disease_name,
        "canonical_name": canonical_name,
        "canonical_norm": canonical_norm,
        "resolved_disease_id": resolved_id,
        "status": status,
        "can_apply": can_apply,
        "applied": bool(can_apply and APPLY_AUDIT_MAPPINGS),
    })

disease_canonical_audit_df = pd.DataFrame(audit_rows)
if not disease_canonical_audit_df.empty:
    disease_canonical_audit_df = disease_canonical_audit_df.sort_values(
        ["status", "raw_disease_name"],
        ascending=[True, True],
    ).reset_index(drop=True)

print(f"[summary][disease][audit] OT-mappable candidates: {candidate_count}")
print(f"[summary][disease][audit] applied to df_disease: {applied_count} (APPLY_AUDIT_MAPPINGS={APPLY_AUDIT_MAPPINGS})")
if not disease_canonical_audit_df.empty:
    print("[summary][disease][audit] status counts:")
    print(disease_canonical_audit_df["status"].value_counts(dropna=False))

disease_canonical_audit_df

2026-02-27 17:45:19,479 [INFO] [LLM] Total 98 names split into 2 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 17:45:19,480 [INFO] [LLM] Batch size: 80
2026-02-27 17:45:19,481 [INFO] [LLM] Batch size: 18
2026-02-27 17:45:20,162 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:20,165 [INFO] [LLM] Batch done in 0.68s
2026-02-27 17:45:21,516 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:45:21,518 [INFO] [LLM] Batch done in 2.04s
2026-02-27 17:45:21,519 [INFO] [LLM] 'Abnormalities, Multiple' → None
2026-02-27 17:45:21,520 [INFO] [LLM] 'Aortic Valve, Calcification of' → None
2026-02-27 17:45:21,520 [INFO] [LLM] 'Arsenic Poisoning' → 'arsenic poisoning'
2026-02-27 17:45:21,521 [INFO] [LLM] 'Arthritis, Experimental' → None
2026-02-27 17:45:21,521 [INFO] [LLM] 'Bone Diseases, Developmental' → None
2026-02-27 17:45:21,521 [INFO] [LLM] 'Brain Injuries' → 'brain injury'
2026-02-27 17:45:21,522 [INFO] [LLM] 'Carcinogenesis' → None
2026-02-27 17:45:21,522 [INFO] [LLM] 'Cell Transformation, Neoplastic' → None
2026-02-27 17:45:21,522 [INFO] [LLM] 'Chemical and Drug Induced Liver Injury' → None
2026-02-27 17:45:21,523 [INFO] [LLM] 'Chromosomal Instability' → None
2026-02-27 17:45:21,523 [INFO] [LLM] 'Chromosome 17 deletion' → None
2026-02-27 17:45:21,523 [INFO] [LLM] 'Chromosome Breakage' → None
2026-02-27 17:45:21,524 [INFO] [LLM] 'Clinical Deterioration' → None
2026-02-27 17:45:21,524 [INFO] [LLM] 'Cognition Disorders' → None
2026-02-27 17:45:21,524 [INFO] [LLM] 'Craniofacial Abnormalities' → None
2026-02-27 17:45:21,525 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 37' → None
2026-02-27 17:45:21,525 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 38' → None
2026-02-27 17:45:21,526 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 40' → None
2026-02-27 17:45:21,526 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 47' → None
2026-02-27 17:45:21,526 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 49' → None
2026-02-27 17:45:21,527 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 50' → None
2026-02-27 17:45:21,527 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 53' → None
2026-02-27 17:45:21,527 [INFO] [LLM] 'DEVELOPMENTAL AND EPILEPTIC ENCEPHALOPATHY 7' → None
2026-02-27 17:45:21,528 [INFO] [LLM] 'Demyelinating Diseases' → None
2026-02-27 17:45:21,528 [INFO] [LLM] 'Diabetes Complications' → None
2026-02-27 17:45:21,528 [INFO] [LLM] 'Diabetes Mellitus, Experimental' → None
2026-02-27 17:45:21,529 [INFO] [LLM] 'Disease Models, Animal' → None
2026-02-27 17:45:21,529 [INFO] [LLM] 'Disease Progression' → None
2026-02-27 17:45:21,529 [INFO] [LLM] 'Drug Eruptions' → None
2026-02-27 17:45:21,530 [INFO] [LLM] 'Drug Overdose' → None
2026-02-27 17:45:21,530 [INFO] [LLM] 'Drug-Related Side Effects and Adverse Reactions' → None
2026-02-27 17:45:21,531 [INFO] [LLM] 'Dyskinesia, Drug-Induced' → None
2026-02-27 17:45:21,531 [INFO] [LLM] 'EPILEPSY, FAMILIAL TEMPORAL LOBE, 5' → None
2026-02-27 17:45:21,531 [INFO] [LLM] 'EPILEPSY, FAMILIAL TEMPORAL LOBE, 7' → None
2026-02-27 17:45:21,532 [INFO] [LLM] 'EPILEPSY, FOCAL, WITH SPEECH DISORDER AND WITH OR WITHOUT IMPAIRED INTELLECTUAL DEVELOPMENT' → None
2026-02-27 17:45:21,532 [INFO] [LLM] 'EPILEPSY, NOCTURNAL FRONTAL LOBE, 5' → None
2026-02-27 17:45:21,532 [INFO] [LLM] 'EPILEPSY, PROGRESSIVE MYOCLONIC, 3, WITH OR WITHOUT INTRACELLULAR INCLUSIONS' → None
2026-02-27 17:45:21,536 [INFO] [LLM] 'EPILEPSY, PROGRESSIVE MYOCLONIC, 4, WITH OR WITHOUT RENAL FAILURE' → None
2026-02-27 17:45:21,536 [INFO] [LLM] 'Epilepsies, Partial' → None
2026-02-27 17:45:21,537 [INFO] [LLM] 'Epilepsy, Absence' → 'absence epilepsy'
2026-02-27 17:45:21,537 [INFO] [LLM] 'Epilepsy, Female-Restricted, with Mental Retardation' → None
2026-02-27 17:45:21,537 [INFO] [LLM] 'Epilepsy, Partial, with Variable Foci' → None
2026-02-27 17:45:21,538 [INFO] [LLM] 'Epilepsy, X-Linked, with Variable Learning Disabilities and Behavior Disorders' → None
2026-02-27 17:45:21,538 [INFO] [LLM] 'Epileptic Encephalopathy, Early Infantile, 4' → None
2026-02-27 17:45:21,538 [INFO] [LLM] 'Extensively Drug-Resistant Tuberculosis' → 'extensively drug-resistant tuberculosis'
2026-02-27 17:45:21,539 [INFO] [LLM] 'Familial Hypophosphatemic Rickets' → None
2026-02-27 17:45:21,539 [INFO] [LLM] 'Gait Disorders, Neurologic' → None
2026-02-27 17:45:21,540 [INFO] [LLM] 'Gastrointestinal Diseases' → None
2026-02-27 17:45:21,540 [INFO] [LLM] 'Generalized Epilepsy With Febrile Seizures Plus, Type 2' → None
2026-02-27 17:45:21,540 [INFO] [LLM] 'Granuloma, Plasma Cell' → None
2026-02-27 17:45:21,541 [INFO] [LLM] 'Hamartoma Syndrome, Multiple' → None
2026-02-27 17:45:21,541 [INFO] [LLM] 'Hepatic Encephalopathy' → 'hepatic encephalopathy'
2026-02-27 17:45:21,541 [INFO] [LLM] 'Latent Tuberculosis' → 'latent tuberculosis'
2026-02-27 17:45:21,542 [INFO] [LLM] 'Learning Disabilities' → None
2026-02-27 17:45:21,542 [INFO] [LLM] 'Leukemia, Megakaryoblastic, of Down Syndrome' → None
2026-02-27 17:45:21,542 [INFO] [LLM] 'Leukemia, Myeloid, Chronic-Phase' → None
2026-02-27 17:45:21,543 [INFO] [LLM] 'Limb Deformities, Congenital' → None
2026-02-27 17:45:21,543 [INFO] [LLM] 'Liver Diseases, Parasitic' → None
2026-02-27 17:45:21,543 [INFO] [LLM] 'Liver Neoplasms, Experimental' → None
2026-02-27 17:45:21,544 [INFO] [LLM] 'MYOCLONIC EPILEPSY, FAMILIAL INFANTILE' → None
2026-02-27 17:45:21,544 [INFO] [LLM] 'Macrocephaly Autism Syndrome' → None
2026-02-27 17:45:21,544 [INFO] [LLM] 'Mammary Neoplasms, Animal' → None
2026-02-27 17:45:21,545 [INFO] [LLM] 'Mammary Neoplasms, Experimental' → None
2026-02-27 17:45:21,545 [INFO] [LLM] 'Melanoma, Experimental' → None
2026-02-27 17:45:21,545 [INFO] [LLM] 'Memory Disorders' → None
2026-02-27 17:45:21,546 [INFO] [LLM] 'Mental Retardation, X-Linked, with Epilepsy' → None
2026-02-27 17:45:21,546 [INFO] [LLM] 'Micronuclei, Chromosome-Defective' → None
2026-02-27 17:45:21,547 [INFO] [LLM] 'Microsatellite Instability' → None
2026-02-27 17:45:21,547 [INFO] [LLM] 'Motor Skills Disorders' → None
2026-02-27 17:45:21,547 [INFO] [LLM] 'NEONATAL NEPHROCUTANEOUS INFLAMMATORY SYNDROME' → None
2026-02-27 17:45:21,551 [INFO] [LLM] 'Neoplasm Invasiveness' → None
2026-02-27 17:45:21,551 [INFO] [LLM] 'Neoplasm Recurrence, Local' → None
2026-02-27 17:45:21,551 [INFO] [LLM] 'Neoplasms, Experimental' → None
2026-02-27 17:45:21,552 [INFO] [LLM] 'Neovascularization, Pathologic' → None
2026-02-27 17:45:21,552 [INFO] [LLM] 'Nervous System Diseases' → None
2026-02-27 17:45:21,552 [INFO] [LLM] 'Nevus, Sebaceous of Jadassohn' → None
2026-02-27 17:45:21,553 [INFO] [LLM] 'Nystagmus, Pathologic' → None
2026-02-27 17:45:21,553 [INFO] [LLM] 'Peripheral Nervous System Diseases' → None
2026-02-27 17:45:21,554 [INFO] [LLM] 'Personality Disorders' → None
2026-02-27 17:45:21,554 [INFO] [LLM] 'Plasma Cell Granuloma, Pulmonary' → None
2026-02-27 17:45:21,555 [INFO] [LLM] 'Polyhydramnios, Megalencephaly, And Symptomatic Epilepsy' → None
2026-02-27 17:45:21,555 [INFO] [LLM] 'Precancerous Conditions' → None
2026-02-27 17:45:21,556 [INFO] [LLM] 'Prenatal Exposure Delayed Effects' → None
2026-02-27 17:45:21,556 [INFO] [LLM] 'Recurrence' → None
2026-02-27 17:45:21,556 [INFO] [LLM] 'SEIZURES, BENIGN FAMILIAL INFANTILE, 5' → 'benign familial infantile epilepsy'
2026-02-27 17:45:21,557 [INFO] [LLM] 'Scaphocephaly, Maxillary Retrusion, And Mental Retardation' → None
2026-02-27 17:45:21,557 [INFO] [LLM] 'Schizophrenia Spectrum and Other Psychotic Disorders' → 'schizophrenia'
2026-02-27 17:45:21,558 [INFO] [LLM] 'Skin Abnormalities' → None
2026-02-27 17:45:21,559 [INFO] [LLM] 'Skin Diseases' → None
2026-02-27 17:45:21,559 [INFO] [LLM] 'Substance-Related Disorders' → None
2026-02-27 17:45:21,559 [INFO] [LLM] 'Teratogenesis' → None
2026-02-27 17:45:21,560 [INFO] [LLM] 'Tuberculosis, Bovine' → 'bovine tuberculosis'
2026-02-27 17:45:21,560 [INFO] [LLM] 'Tuberculosis, Osteoarticular' → 'ostearticular tuberculosis'
2026-02-27 17:45:21,560 [INFO] [LLM] 'Tuberculosis, Spinal' → 'spinal tuberculosis'
2026-02-27 17:45:21,561 [INFO] [LLM] 'Urologic Neoplasms' → None
2026-02-27 17:45:21,561 [INFO] [LLM] 'Vasculitis, Leukocytoclastic, Cutaneous' → 'cutaneous leukocytoclastic vasculitis'
2026-02-27 17:45:21,562 [INFO] [LLM] 'Ventricular Dysfunction, Left' → 'left ventricular dysfunction'
2026-02-27 17:45:21,562 [INFO] [LLM] 'Vision Disorders' → None
2026-02-27 17:45:21,562 [INFO] [OT] Verifying 13 unique suggestions...
2026-02-27 17:45:22,009 [INFO] [OT] 'schizophrenia' → 'schizophrenia' (MONDO_0005090)
2026-02-27 17:45:22,010 [INFO] [OT] 'brain injury' → 'brain injury' (MONDO_0043510)
2026-02-27 17:45:22,011 [INFO] [OT] 'benign familial infantile epilepsy' → 'benign familial infantile epilepsy' (MONDO_0017615)
2026-02-27 17:45:22,011 [INFO] [OT] 'spinal tuberculosis' → 'tuberculosis, spinal' (MONDO_0043836)
2026-02-27 17:45:22,012 [INFO] [OT] 'bovine tuberculosis' → 'Tuberculosis, Bovine' (EFO_1001441)
2026-02-27 17:45:22,013 [INFO] Done: 5 / 98 confirmed | 93 → None

[audit][disease][Llama->OT] raw='Brain Injuries' -> canonical='brain injury' -> id='MONDO_0043510'
[audit][disease][Llama->OT] raw='SEIZURES, BENIGN FAMILIAL INFANTILE, 5' -> canonical='benign familial infantile epilepsy' -> id='MONDO_0017615'
[audit][disease][Llama->OT] raw='Schizophrenia Spectrum and Other Psychotic Disorders' -> canonical='schizophrenia' -> id='MONDO_0005090'
[summary][disease][audit] OT-mappable candidates: 3
[summary][disease][audit] applied to df_disease: 0 (APPLY_AUDIT_MAPPINGS=False)
[summary][disease][audit] status counts:
status
no_canonical           93
mappable_ot_exact       3
canonical_not_in_ot     2
Name: count, dtype: int64

,raw_disease_name,canonical_name,canonical_norm,resolved_disease_id,status,can_apply,applied
0,"Tuberculosis, Bovine","Tuberculosis, Bovine","tuberculosis, bovine",None,canonical_not_in_ot,False,False
1,"Tuberculosis, Spinal","tuberculosis, spinal","tuberculosis, spinal",None,canonical_not_in_ot,False,False
2,Brain Injuries,brain injury,brain injury,MONDO_0043510,mappable_ot_exact,True,False
3,"SEIZURES, BENIGN FAMILIAL INFANTILE, 5",benign familial infantile epilepsy,benign familial infantile epilepsy,MONDO_0017615,mappable_ot_exact,True,False
4,Schizophrenia Spectrum and Other Psychotic Dis...,schizophrenia,schizophrenia,MONDO_0005090,mappable_ot_exact,True,False
...,...,...,...,...,...,...,...
93,"Tuberculosis, Osteoarticular",None,None,None,no_canonical,False,False
94,Urologic Neoplasms,None,None,None,no_canonical,False,False
95,"Vasculitis, Leukocytoclastic, Cutaneous",None,None,None,no_canonical,False,False
96,"Ventricular Dysfunction, Left",None,None,None,no_canonical,False,False
97,Vision Disorders,None,None,None,no_canonical,False,False

In [18]:
# disease_canonical_audit_df

In [19]:
df_disease[df_disease["source"]=='Llama']

                                          disease_name     disease_id source
0    AMYOTROPHIC LATERAL SCLEROSIS 12 WITH OR WITHO...  MONDO_0004976  Llama
2           AMYOTROPHIC LATERAL SCLEROSIS 16, JUVENILE  MONDO_0004976  Llama
4                     AMYOTROPHIC LATERAL SCLEROSIS 19  MONDO_0004976  Llama
10                               Abortion, Spontaneous    EFO_1001255  Llama
11                                    Acidosis, Lactic    EFO_1000036  Llama
..                                                 ...            ...    ...
470                  Tuberculosis, Multidrug-Resistant    EFO_0007381  Llama
472                              Tuberculosis, Pleural    EFO_0007446  Llama
473                            Tuberculosis, Pulmonary    EFO_1000049  Llama
474                                Tuberculosis, Renal    EFO_0007463  Llama
482                         Uterine Cervical Neoplasms    EFO_0001061  Llama

[138 rows x 3 columns]

In [20]:
df_disease["source"].value_counts()

source
OpenTargets    258
Llama          138
Name: count, dtype: int64

In [21]:
df_disease

,disease_name,disease_id,source
0,AMYOTROPHIC LATERAL SCLEROSIS 12 WITH OR WITHO...,MONDO_0004976,Llama
1,AMYOTROPHIC LATERAL SCLEROSIS 15 WITH OR WITHO...,MONDO_0010459,OpenTargets
2,"AMYOTROPHIC LATERAL SCLEROSIS 16, JUVENILE",MONDO_0004976,Llama
3,AMYOTROPHIC LATERAL SCLEROSIS 18,MONDO_0013891,OpenTargets
4,AMYOTROPHIC LATERAL SCLEROSIS 19,MONDO_0004976,Llama
...,...,...,...
489,Vulvar Lichen Sclerosus,EFO_1000623,OpenTargets
490,Weight Gain,HP_0004324,OpenTargets
491,Weight Loss,HP_0001824,OpenTargets
492,Williams Syndrome,MONDO_0008678,OpenTargets
493,Wilms Tumor,MONDO_0024676,OpenTargets

In [22]:
# df_disease[df_disease["source"]=="Llama"]

In [23]:
def compute_jaccard_from_run_dataframes(dct_result, df_gene, df_disease, df_drug):
    """
    Compute per-question cross-run Jaccard consistency after mapping entities to IDs.

    For each (model, question):
    - intersection: entries present in ALL valid runs
    - union: entries present in ANY valid run
    - jaccard = |intersection| / |union|

    All comparisons are CASE-INDEPENDENT and ID-based.

    Side effects:
    - Stores per-run mapped dataframe in:
        dct_result[model][question][run]['dataframe_id']

    Returns:
    - dct_jaccard[model][question] = {
          'jaccard': float,
          'n_valid_runs': int,
          'intersection': set[tuple],
          'union': set[tuple],
      }
    """

    dct_jaccard = {}

    # ------------------------------------------------------------------
    # Build deterministic one-to-one mapping tables
    # ------------------------------------------------------------------
    gene_map = (
        df_gene.assign(_gene_norm=df_gene["gene_name"].astype(str).str.strip().str.upper())
        [["_gene_norm", "gene_id"]]
        .dropna(subset=["gene_id"])
        .drop_duplicates("_gene_norm", keep="first")
    )

    disease_map = (
        df_disease.assign(_disease_norm=df_disease["disease_name"].astype(str).str.strip().str.upper())
        [["_disease_norm", "disease_id"]]
        .dropna(subset=["disease_id"])
        .drop_duplicates("_disease_norm", keep="first")
    )

    drug_map = (
        df_drug.assign(_drug_norm=df_drug["drug_name"].astype(str).str.strip().str.upper())
        [["_drug_norm", "drug_id"]]
        .dropna(subset=["drug_id"])
        .drop_duplicates("_drug_norm", keep="first")
    )

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    for model, model_payload in dct_result.items():
        dct_jaccard[model] = {}
        print(f"\nWorking for model: {model}")

        for question_key, runs_dict in model_payload.items():
            run_sets = {}

            for run_number, run_payload in runs_dict.items():
                df = run_payload.get("dataframe")

                # ---- basic validity ----
                if not isinstance(df, pd.DataFrame) or df.empty:
                    continue

                if "pathway_name" in df.columns:
                    continue

                work_df = df.copy()

                # print(work_df.head())

                final_cols = []

                # ---- gene ----
                if "gene_name" in work_df.columns:
                    work_df["_gene_norm"] = (
                        work_df["gene_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(gene_map, on="_gene_norm", how="left")
                    final_cols.append("gene_id")

                # ---- disease ----
                if "disease_name" in work_df.columns:
                    work_df["_disease_norm"] = (
                        work_df["disease_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(disease_map, on="_disease_norm", how="left")
                    final_cols.append("disease_id")

                # ---- drug ----
                if "drug_name" in work_df.columns:
                    work_df["_drug_norm"] = (
                        work_df["drug_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(drug_map, on="_drug_norm", how="left")
                    final_cols.append("drug_id")

                if not final_cols:
                    continue

                # ---- canonical ID dataframe ----
                id_df = (
                    work_df[final_cols]
                    .dropna(how="any")
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

                dct_result[model][question_key][run_number]["dataframe_id"] = id_df

                if id_df.empty:
                    continue

                # ---- CASE-INDEPENDENT tuple set ----
                run_set = {
                    tuple(str(v).strip().upper() for v in row)
                    for row in id_df.itertuples(index=False, name=None)
                }

                if run_set:
                    run_sets[run_number] = run_set

            # ------------------------------------------------------------------
            # Compute intersection / union
            # ------------------------------------------------------------------
            n_valid_runs = len(run_sets)

            if n_valid_runs < 2:
                print(
                    f"Not enough valid runs for '{question_key}' "
                    f"({n_valid_runs}/{len(runs_dict)}). Skipping."
                )
                continue

            sets = list(run_sets.values())
            intersection = set.intersection(*sets)
            union = set.union(*sets)

            if not union:
                print(f"Empty union for '{question_key}', skipping.")
                continue

            jaccard = len(intersection) / len(union)

            dct_jaccard[model][question_key] = {
                "jaccard": jaccard,
                "n_valid_runs": n_valid_runs,
                "intersection": intersection,
                "union": union,
            }

            print(
                f"'{question_key}': "
                f"J={jaccard:.4f}, "
                f"|∩|={len(intersection)}, "
                f"|∪|={len(union)}, "
                f"runs={n_valid_runs}"
            )

    return dct_jaccard


dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

Working for model: ctd
'Which diseases are associated with BRAF?': J=1.0000, |∩|=34, |∪|=34, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=0.9904, |∩|=103, |∪|=104, runs=5
'Which diseases are associated with CDK4?': J=1.0000, |∩|=9, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=1.0000, |∩|=80, |∪|=80, runs=5
'Which genes are associated with ovarian cancer?': J=0.1988, |∩|=32, |∪|=161, runs=5
'What are the known targets of regorafenib?': J=1.0000, |∩|=24, |∪|=24, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
Not enough valid runs for 'Which genes are associated with fever (pyrexia)?' (0/0). Skipping.
Not enough valid runs for 'Which diseases are treated with bevacizumab?' (0/0). Skipping.
'What are the known targets of cabozantinib?': J=1.0000, |∩|=3, |∪|=3, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=1.0000, |∩|=8, |∪|=8, runs=5
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=1.0000, |∩|=119, |∪|=119, runs=5
'What drugs are used to treat rickets?': J=1.0000, |∩|=7, |∪|=7, runs=5
'Which genes are associated with epilepsy?': J=0.6962, |∩|=165, |∪|=237, runs=4
Not enough valid runs for 'Which diseases are treated with trastuzumab deruxtecan?' (0/0). Skipping.
'Which genes are associated with Alzheimer’s disease?': J=1.0000, |∩|=105, |∪|=105, runs=5
Not enough valid runs for 'For which diseases is darolutamide used?' (0/0). Skipping.
'Which genes are associated with renal cell carcinoma?': J=1.0000, |∩|=134, |∪|=134, runs=5
'Which diseases are associated with the KRAS gene?': J=1.0000, |∩|=47, |∪|=47, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=1.0000, |∩|=174, |∪|=174, runs=5
'Which diseases are treated with valdecoxib?': J=1.0000, |∩|=6, |∪|=6, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=38, |∪|=38, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.9868, |∩|=75, |∪|=76, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which drugs are used to treat chronic myeloid leukemia?': J=1.0000, |∩|=29, |∪|=29, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=1.0000, |∩|=163, |∪|=163, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=0.7059, |∩|=60, |∪|=85, runs=5
'Which targets are acted on by imatinib?': J=1.0000, |∩|=135, |∪|=135, runs=5
'Which biological targets does sorafenib interact with?': J=1.0000, |∩|=167, |∪|=167, runs=5
'Which biological targets does tofacitinib interact with?': J=1.0000, |∩|=78, |∪|=78, runs=5
'Which drugs target EGFR?': J=1.0000, |∩|=193, |∪|=193, runs=5
'Which diseases are associated with TP53?': J=1.0000, |∩|=93, |∪|=93, runs=5
'Which diseases are associated with FGFR2?': J=1.0000, |∩|=28, |∪|=28, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=20, |∪|=20, runs=5
'Which genes are associated with breast cancer?': J=0.8857, |∩|=31, |∪|=35, runs=5
'Which genes are associated with colorectal cancer?': J=0.5556, |∩|=5, |∪|=9, runs=5
'Which genes are associated with cystic fibrosis?': J=0.6923, |∩|=9, |∪|=13, runs=5
'Which drugs are used to treat TNBC?': J=1.0000, |∩|=11, |∪|=11, runs=5
'Which diseases are treated with metformin?': J=1.0000, |∩|=87, |∪|=87, runs=5
Not enough valid runs for 'Which diseases are treated with adalimumab?' (0/0). Skipping.
Not enough valid runs for 'For which diseases is pembrolizumab used?' (0/0). Skipping.
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=38, |∪|=38, runs=5
Not enough valid runs for 'Which diseases are treated with nivolumab?' (0/0). Skipping.
'Which genes are associated with multiple sclerosis?': J=1.0000, |∩|=66, |∪|=66, runs=5
'Which genes are associated with rheumatoid arthritis?': J=1.0000, |∩|=179, |∪|=179, runs=5
Not enough valid runs for 'What are the known targets of abatacept?' (0/0). Skipping.
'Which genes are associated with lung cancer?': J=0.9538, |∩|=351, |∪|=368, runs=5
'What are the known targets of ponatinib?': J=1.0000, |∩|=74, |∪|=74, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=1.0000, |∩|=51, |∪|=51, runs=5
'Which genes are associated with autism spectrum disorder?': J=0.9968, |∩|=616, |∪|=618, runs=5
'Which diseases are associated with the ROS1 gene?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=16, |∪|=16, runs=5
'Which diseases are associated with the EGFR gene?': J=1.0000, |∩|=42, |∪|=42, runs=5
'Which genes are associated with psoriasis?': J=0.8143, |∩|=57, |∪|=70, runs=5
'Which genes are associated with ulcerative colitis?': J=1.0000, |∩|=68, |∪|=68, runs=5
'Which genes are associated with tuberculosis?': J=1.0000, |∩|=10, |∪|=10, runs=5
'Which genes are associated with hepatitis C?': J=1.0000, |∩|=20, |∪|=20, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=1.0000, |∩|=18, |∪|=18, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=1.0000, |∩|=95, |∪|=95, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
'Which drugs target CD19?': J=1.0000, |∩|=11, |∪|=11, runs=5
'Which drugs target CTLA4?': J=1.0000, |∩|=8, |∪|=8, runs=5

In [24]:
# Run Jaccard consistency computation across runs after ID grounding.
dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

# Flatten into a quick summary table for inspection.
rows = [
    {
        "model": model,
        "question": question,
        "jaccard": payload["jaccard"],
        "n_valid_runs": payload["n_valid_runs"],
        "intersection_size": len(payload["intersection"]),
        "union_size": len(payload["union"]),
    }
    for model, qmap in dct_jaccard.items()
    for question, payload in qmap.items()
]

jaccard_summary = pd.DataFrame(rows)
if jaccard_summary.empty:
    print("No valid Jaccard entries were produced. Check input runs and validation filters.")
else:
    display(jaccard_summary.sort_values(["model", "jaccard"], ascending=[True, False]).head(20))

Working for model: ctd
'Which diseases are associated with BRAF?': J=1.0000, |∩|=34, |∪|=34, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=0.9904, |∩|=103, |∪|=104, runs=5
'Which diseases are associated with CDK4?': J=1.0000, |∩|=9, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=1.0000, |∩|=80, |∪|=80, runs=5
'Which genes are associated with ovarian cancer?': J=0.1988, |∩|=32, |∪|=161, runs=5
'What are the known targets of regorafenib?': J=1.0000, |∩|=24, |∪|=24, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
Not enough valid runs for 'Which genes are associated with fever (pyrexia)?' (0/0). Skipping.
Not enough valid runs for 'Which diseases are treated with bevacizumab?' (0/0). Skipping.
'What are the known targets of cabozantinib?': J=1.0000, |∩|=3, |∪|=3, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=1.0000, |∩|=8, |∪|=8, runs=5
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=1.0000, |∩|=119, |∪|=119, runs=5
'What drugs are used to treat rickets?': J=1.0000, |∩|=7, |∪|=7, runs=5
'Which genes are associated with epilepsy?': J=0.6962, |∩|=165, |∪|=237, runs=4
Not enough valid runs for 'Which diseases are treated with trastuzumab deruxtecan?' (0/0). Skipping.
'Which genes are associated with Alzheimer’s disease?': J=1.0000, |∩|=105, |∪|=105, runs=5
Not enough valid runs for 'For which diseases is darolutamide used?' (0/0). Skipping.
'Which genes are associated with renal cell carcinoma?': J=1.0000, |∩|=134, |∪|=134, runs=5
'Which diseases are associated with the KRAS gene?': J=1.0000, |∩|=47, |∪|=47, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=1.0000, |∩|=174, |∪|=174, runs=5
'Which diseases are treated with valdecoxib?': J=1.0000, |∩|=6, |∪|=6, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=38, |∪|=38, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.9868, |∩|=75, |∪|=76, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which drugs are used to treat chronic myeloid leukemia?': J=1.0000, |∩|=29, |∪|=29, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=1.0000, |∩|=163, |∪|=163, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=0.7059, |∩|=60, |∪|=85, runs=5
'Which targets are acted on by imatinib?': J=1.0000, |∩|=135, |∪|=135, runs=5
'Which biological targets does sorafenib interact with?': J=1.0000, |∩|=167, |∪|=167, runs=5
'Which biological targets does tofacitinib interact with?': J=1.0000, |∩|=78, |∪|=78, runs=5
'Which drugs target EGFR?': J=1.0000, |∩|=193, |∪|=193, runs=5
'Which diseases are associated with TP53?': J=1.0000, |∩|=93, |∪|=93, runs=5
'Which diseases are associated with FGFR2?': J=1.0000, |∩|=28, |∪|=28, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=20, |∪|=20, runs=5
'Which genes are associated with breast cancer?': J=0.8857, |∩|=31, |∪|=35, runs=5
'Which genes are associated with colorectal cancer?': J=0.5556, |∩|=5, |∪|=9, runs=5
'Which genes are associated with cystic fibrosis?': J=0.6923, |∩|=9, |∪|=13, runs=5
'Which drugs are used to treat TNBC?': J=1.0000, |∩|=11, |∪|=11, runs=5
'Which diseases are treated with metformin?': J=1.0000, |∩|=87, |∪|=87, runs=5
Not enough valid runs for 'Which diseases are treated with adalimumab?' (0/0). Skipping.
Not enough valid runs for 'For which diseases is pembrolizumab used?' (0/0). Skipping.
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=38, |∪|=38, runs=5
Not enough valid runs for 'Which diseases are treated with nivolumab?' (0/0). Skipping.
'Which genes are associated with multiple sclerosis?': J=1.0000, |∩|=66, |∪|=66, runs=5
'Which genes are associated with rheumatoid arthritis?': J=1.0000, |∩|=179, |∪|=179, runs=5
Not enough valid runs for 'What are the known targets of abatacept?' (0/0). Skipping.
'Which genes are associated with lung cancer?': J=0.9538, |∩|=351, |∪|=368, runs=5
'What are the known targets of ponatinib?': J=1.0000, |∩|=74, |∪|=74, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=1.0000, |∩|=51, |∪|=51, runs=5
'Which genes are associated with autism spectrum disorder?': J=0.9968, |∩|=616, |∪|=618, runs=5
'Which diseases are associated with the ROS1 gene?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=16, |∪|=16, runs=5
'Which diseases are associated with the EGFR gene?': J=1.0000, |∩|=42, |∪|=42, runs=5
'Which genes are associated with psoriasis?': J=0.8143, |∩|=57, |∪|=70, runs=5
'Which genes are associated with ulcerative colitis?': J=1.0000, |∩|=68, |∪|=68, runs=5
'Which genes are associated with tuberculosis?': J=1.0000, |∩|=10, |∪|=10, runs=5
'Which genes are associated with hepatitis C?': J=1.0000, |∩|=20, |∪|=20, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=1.0000, |∩|=18, |∪|=18, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=1.0000, |∩|=95, |∪|=95, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
'Which drugs target CD19?': J=1.0000, |∩|=11, |∪|=11, runs=5
'Which drugs target CTLA4?': J=1.0000, |∩|=8, |∪|=8, runs=5

,model,question,jaccard,n_valid_runs,intersection_size,union_size
0,ctd,Which diseases are associated with BRAF?,1.0,5,34,34
2,ctd,Which diseases are associated with CDK4?,1.0,5,9,9
3,ctd,Which drugs are used to treat rheumatoid arthr...,1.0,5,80,80
5,ctd,What are the known targets of regorafenib?,1.0,5,24,24
6,ctd,What are the known targets of cabozantinib?,1.0,5,3,3
7,ctd,Which diseases are associated with the NPM1 gene?,1.0,5,8,8
8,ctd,Which drugs are used to treat migraine?,1.0,5,119,119
9,ctd,What drugs are used to treat rickets?,1.0,5,7,7
11,ctd,Which genes are associated with Alzheimer’s di...,1.0,5,105,105
12,ctd,Which genes are associated with renal cell car...,1.0,5,134,134
13,ctd,Which diseases are associated with the KRAS gene?,1.0,5,47,47
14,ctd,Which genes are associated with schizophrenia?,1.0,5,174,174
15,ctd,Which diseases are treated with valdecoxib?,1.0,5,6,6
16,ctd,What are the known targets of vandetanib?,1.0,5,38,38
18,ctd,Which drugs are used to treat pancreatic adeno...,1.0,5,4,4
19,ctd,Which drugs are used to treat chronic myeloid ...,1.0,5,29,29
20,ctd,Which drugs are used to treat Parkinson’s dise...,1.0,5,163,163
22,ctd,Which targets are acted on by imatinib?,1.0,5,135,135
23,ctd,Which biological targets does sorafenib intera...,1.0,5,167,167
24,ctd,Which biological targets does tofacitinib inte...,1.0,5,78,78

In [25]:
# Persist enriched run payloads with dataframe_id attached for each run.
with open("CTD_same_question_response_with_id.pkl", "wb") as f:
    pickle.dump(dct_result, f)