In [1]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from openai_utility import return_openai_answer

In [2]:



model = "gpt-5-nano"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [3]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 8

  disease_name gene_name
0     melanoma      braf

 Run 1 completed | rows=8 | latency=24.345s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0     melanoma      braf

 Run 2 completed | rows=7 | latency=16.119s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     melanoma      braf

 Run 3 completed | rows=9 | latency=15.052s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     melanoma      braf

 Run 4 completed | rows=10 | latency=17.214s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 8

  disease_name gene_name
0     melanoma      braf

 Run 5 completed | rows=8 | latency=16.129s
------------------------------------------------------------


## Question 2

**Which genes are associated with amyotrophic lateral sclerosis?**

In [4]:

question = 'Which genes are associated with amyotrophic lateral sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 20

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 1 completed | rows=20 | latency=28.939s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 22

                    disease_name gene_name
0  amyotrophic lateral sclerosis   c9orf72

  Attempt 2/3
Entries retrieved: 16

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 2 completed | rows=16 | latency=18.811s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 3 completed | rows=4 | latency=16.347s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 17

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 4 completed | rows=17 | latency=20.821s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 16

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 5 completed | rows=16 | latency=20.032s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [5]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     melanoma      cdk4

 Run 1 completed | rows=3 | latency=19.307s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     melanoma      cdk4

 Run 2 completed | rows=3 | latency=29.226s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  breast cancer      cdk4

 Run 3 completed | rows=3 | latency=15.121s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     melanoma      cdk4

 Run 4 completed | rows=3 | latency=18.232s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     melanoma      cdk4

 Run 5 completed | rows=3 | latency=24.973s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [6]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 17.212s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name                pathway_name
0      jak2  jak-stat signaling pathway

 Run 1 completed | rows=1 | latency=14.196s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      jak2  jak-stat signaling pathway

 Run 2 completed | rows=1 | latency=11.196s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  jak-stat signaling pathway      jak2

 Run 3 completed | rows=1 | latency=17.302s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      jak2  jak-stat signaling pathway

 Run 4 completed | rows=1 | latency=16.927s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  jak-stat signaling pathway      jak2

 Run 5 completed | rows=1 | latency=16.276s
------------------------------------------------------------


## Question 5

**Which drugs are used to treat rheumatoid arthritis?**

In [7]:

question = 'Which drugs are used to treat rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  methotrexate  rheumatoid arthritis

 Run 1 completed | rows=17 | latency=17.889s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  methotrexate  rheumatoid arthritis

 Run 2 completed | rows=17 | latency=18.805s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 18

      drug_name          disease_name
0  methotrexate  rheumatoid arthritis

 Run 3 completed | rows=18 | latency=21.511s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

      drug_name          disease_name
0  methotrexate  rheumatoid arthritis

 Run 4 completed | rows=17 | latency=19.654s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 19

      drug_name          disease_name
0  methotrexate  rheumatoid arthritis

 Run 5 completed | rows=19 | latency=23.102s
------------------------------------------------------------


## Question 6

**Which genes are associated with ovarian cancer?**

In [8]:

question = 'Which genes are associated with ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

     disease_name gene_name
0  ovarian cancer     brca1

 Run 1 completed | rows=10 | latency=18.058s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 6

     disease_name gene_name
0  ovarian cancer     brca1

 Run 2 completed | rows=6 | latency=21.082s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 11

     disease_name gene_name
0  ovarian cancer     brca1

 Run 3 completed | rows=11 | latency=22.222s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 16

  gene_name    disease_name
0     brca1  ovarian cancer

 Run 4 completed | rows=16 | latency=22.125s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

     disease_name gene_name
0  ovarian cancer     brca1

 Run 5 completed | rows=10 | latency=14.495s
------------------------------------------------------------


## Question 7

**What are the known targets of regorafenib?**

In [9]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name gene_name
0  regorafenib       kdr

 Run 1 completed | rows=9 | latency=17.732s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  regorafenib       kdr

 Run 2 completed | rows=11 | latency=20.568s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  regorafenib       kdr

 Run 3 completed | rows=11 | latency=20.177s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

     drug_name gene_name
0  regorafenib       kdr

 Run 4 completed | rows=12 | latency=23.364s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 8

     drug_name gene_name
0  regorafenib       kdr

 Run 5 completed | rows=8 | latency=21.548s
------------------------------------------------------------


## Question 8

**Which pathways are associated with the STAT3 gene?**

In [10]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 1 completed | rows=2 | latency=14.709s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

  Attempt 2/3
Entries retrieved: 1

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 2 completed | rows=1 | latency=18.233s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 3 completed | rows=1 | latency=14.257s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

                 pathway_name gene_name
0  jak-stat signaling pathway     stat3

 Run 4 completed | rows=2 | latency=22.389s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 5 completed | rows=2 | latency=17.648s
------------------------------------------------------------


## Question 9

**Which genes are associated with fever (pyrexia)?**

In [11]:

question = 'Which genes are associated with fever (pyrexia)?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 8

                   disease_name gene_name
0  familial mediterranean fever      mefv

 Run 1 completed | rows=8 | latency=25.159s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0        fever     nlrp3

 Run 2 completed | rows=5 | latency=18.622s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [disease_name, gene_name]
Index: []

 Attempt 1 failed after 14.361s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 6

  disease_name gene_name
0        fever      il1b

 Run 3 completed | rows=6 | latency=19.213s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0        fever      mefv

 Run 4 completed | rows=10 | latency=26.867s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0        fever      il1b

 Run 5 completed | rows=5 | latency=21.483s
------------------------------------------------------------


## Question 10

**Which diseases are treated with bevacizumab?**

In [12]:

question = 'Which diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name                  disease_name
0  bevacizumab  metastatic colorectal cancer

  Attempt 2/3
Entries retrieved: 8

     drug_name                  disease_name
0  bevacizumab  metastatic colorectal cancer

  Attempt 3/3
Entries retrieved: 8

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 1 completed | rows=8 | latency=15.228s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 2 completed | rows=6 | latency=19.606s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 3 completed | rows=7 | latency=20.211s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 8

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 4 completed | rows=8 | latency=26.070s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 5 completed | rows=6 | latency=20.332s
------------------------------------------------------------


## Question 11

**What are the known targets of cabozantinib?**

In [13]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       met

 Run 1 completed | rows=5 | latency=9.795s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       met

 Run 2 completed | rows=5 | latency=10.818s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       met

 Run 3 completed | rows=5 | latency=13.932s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       met

 Run 4 completed | rows=5 | latency=9.520s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       met

 Run 5 completed | rows=5 | latency=13.861s
------------------------------------------------------------


## Question 12

**Which pathways are associated with the TNF gene?**

In [14]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 17.212s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 3

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 1 completed | rows=3 | latency=23.939s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 2 completed | rows=4 | latency=15.471s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 3 completed | rows=5 | latency=20.624s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                 pathway_name
0       tnf  nf-kappab signaling pathway

 Run 4 completed | rows=3 | latency=28.420s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name           pathway_name
0       tnf  tnf signaling pathway

  Attempt 2/3
Entries retrieved: 4

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 5 completed | rows=4 | latency=24.883s
------------------------------------------------------------


## Question 13

**Which diseases are associated with the NPM1 gene?**

In [15]:

question = 'Which diseases are associated with the NPM1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  acute myeloid leukemia with mutated npm1      npm1

 Run 1 completed | rows=1 | latency=13.755s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  acute myeloid leukemia      npm1

 Run 2 completed | rows=1 | latency=14.153s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  acute myeloid leukemia      npm1

 Run 3 completed | rows=1 | latency=9.697s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  acute myeloid leukemia      npm1

 Run 4 completed | rows=1 | latency=13.492s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

                                disease_name gene_name
0  acute myeloid leukemia with npm1 mutation      npm1

 Run 5 completed | rows=1 | latency=12.062s
------------------------------------------------------------


## Question 14

**Which pathways are associated with the CD19 gene?**

In [16]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 1 completed | rows=2 | latency=21.080s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 2 completed | rows=2 | latency=19.531s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 3 completed | rows=2 | latency=16.828s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 4 completed | rows=1 | latency=26.329s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 5 completed | rows=4 | latency=19.942s
------------------------------------------------------------


## Question 15

**Which drugs are used to treat migraine?**

In [17]:

question = 'Which drugs are used to treat migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 12

     drug_name disease_name
0  sumatriptan     migraine

  Attempt 2/3
Entries retrieved: 25

     drug_name disease_name
0  sumatriptan     migraine

  Attempt 3/3
Entries retrieved: 22

     drug_name disease_name
0  sumatriptan     migraine

 Run 1 completed | rows=22 | latency=28.889s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 18

     drug_name disease_name
0  sumatriptan     migraine

  Attempt 2/3
Entries retrieved: 15

     drug_name disease_name
0  sumatriptan     migraine

 Run 2 completed | rows=15 | latency=24.458s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 13

     drug_name disease_name
0  sumatriptan     migraine

 Run 3 completed | rows=13 | latency=24.889s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 18

     drug_name disease_name
0  sumatriptan     migraine

 Run 4 completed | rows=18 | latency=23.870s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 26

     drug_name disease_name
0  sumatriptan     migraine

  Attempt 2/3
Entries retrieved: 22

     drug_name disease_name
0  sumatriptan     migraine

  Attempt 3/3
Entries retrieved: 12

     drug_name disease_name
0  sumatriptan     migraine

 Run 5 completed | rows=12 | latency=28.813s
------------------------------------------------------------


## Question 16

**What drugs are used to treat rickets?**

In [4]:

question = 'What drugs are used to treat rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

         drug_name disease_name
0  cholecalciferol      rickets

 Run 1 completed | rows=3 | latency=12.555s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

         drug_name disease_name
0  cholecalciferol      rickets

 Run 2 completed | rows=3 | latency=11.784s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

         drug_name disease_name
0  cholecalciferol      rickets

 Run 3 completed | rows=3 | latency=8.604s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

         drug_name disease_name
0  cholecalciferol      rickets

 Run 4 completed | rows=3 | latency=10.611s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

         drug_name disease_name
0  cholecalciferol      rickets

 Run 5 completed | rows=3 | latency=16.870s
------------------------------------------------------------


## Question 17

**Which genes are associated with epilepsy?**

In [19]:

question = 'Which genes are associated with epilepsy?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 21

  disease_name gene_name
0     epilepsy     scn1a

 Run 1 completed | rows=21 | latency=18.115s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 22

  disease_name gene_name
0     epilepsy     scn1a

 Run 2 completed | rows=22 | latency=21.878s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 18

  disease_name gene_name
0     epilepsy     scn1a

 Run 3 completed | rows=18 | latency=12.449s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 20

  disease_name gene_name
0     epilepsy     scn1a

 Run 4 completed | rows=20 | latency=20.598s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 21

  disease_name gene_name
0     epilepsy     scn1a

 Run 5 completed | rows=21 | latency=26.654s
------------------------------------------------------------


## Question 18

**Which diseases are treated with trastuzumab deruxtecan?**

In [20]:

question = 'Which diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  trastuzumab deruxtecan  breast cancer

 Run 1 completed | rows=2 | latency=18.596s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  trastuzumab deruxtecan  breast cancer

 Run 2 completed | rows=2 | latency=14.477s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name   disease_name
0  trastuzumab deruxtecan  breast cancer

 Run 3 completed | rows=3 | latency=15.890s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  trastuzumab deruxtecan  breast cancer

 Run 4 completed | rows=2 | latency=23.426s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name   disease_name
0  trastuzumab deruxtecan  breast cancer

 Run 5 completed | rows=3 | latency=21.897s
------------------------------------------------------------


## Question 19

**Which genes are associated with Alzheimer’s disease?**

In [21]:

question = 'Which genes are associated with Alzheimer’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 15

          disease_name gene_name
0  alzheimer's disease       app

 Run 1 completed | rows=15 | latency=17.307s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 10

          disease_name gene_name
0  alzheimer's disease       app

 Run 2 completed | rows=10 | latency=14.833s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 16

          disease_name gene_name
0  alzheimer's disease      apoe

 Run 3 completed | rows=16 | latency=17.310s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 12

          disease_name gene_name
0  alzheimer's disease      apoe

 Run 4 completed | rows=12 | latency=15.831s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 18

          disease_name gene_name
0  alzheimer's disease      apoe

 Run 5 completed | rows=18 | latency=17.466s
------------------------------------------------------------


## Question 20

**For which diseases is darolutamide used?**

In [22]:

question = 'For which diseases is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  nonmetastatic castration-resistant prostate ca...

 Run 1 completed | rows=1 | latency=8.415s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  non-metastatic castration-resistant prostate c...

 Run 2 completed | rows=1 | latency=10.304s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  non-metastatic castration-resistant prostate c...

 Run 3 completed | rows=1 | latency=9.004s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  non-metastatic castration-resistant prostate c...

 Run 4 completed | rows=1 | latency=8.773s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  non-metastatic castration-resistant prostate c...

 Run 5 completed | rows=1 | latency=6.953s
------------------------------------------------------------


## Question 21

**Which genes are associated with renal cell carcinoma?**

In [23]:

question = 'Which genes are associated with renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

           disease_name gene_name
0  renal cell carcinoma       vhl

 Run 1 completed | rows=8 | latency=17.980s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 7

           disease_name gene_name
0  renal cell carcinoma       vhl

 Run 2 completed | rows=7 | latency=16.806s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

           disease_name gene_name
0  renal cell carcinoma       vhl

 Run 3 completed | rows=8 | latency=21.237s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 4

           disease_name gene_name
0  renal cell carcinoma       vhl

 Run 4 completed | rows=4 | latency=14.590s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

           disease_name gene_name
0  renal cell carcinoma       vhl

 Run 5 completed | rows=8 | latency=28.823s
------------------------------------------------------------


## Question 22

**Which diseases are associated with the KRAS gene?**

In [24]:

question = 'Which diseases are associated with the KRAS gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 6

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 1 completed | rows=6 | latency=22.046s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 6

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 2 completed | rows=6 | latency=18.171s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 5

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 3 completed | rows=5 | latency=17.148s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 5

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 4 completed | rows=5 | latency=25.427s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 7

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 5 completed | rows=7 | latency=23.844s
------------------------------------------------------------


## Question 23

**Which pathways are associated with the APP gene?**

In [25]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 14.893s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name         pathway_name
0       app  alzheimer's disease

 Run 1 completed | rows=1 | latency=22.534s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 13.106s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name               pathway_name
0       app  alzheimer disease pathway

 Run 2 completed | rows=1 | latency=27.867s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                 pathway_name
0       app  alzheimer's disease pathway

 Run 3 completed | rows=1 | latency=18.214s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 11.759s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name                 pathway_name
0       app  alzheimer's disease pathway

 Run 4 completed | rows=1 | latency=16.537s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                 pathway_name
0       app  alzheimer's disease pathway

 Run 5 completed | rows=1 | latency=18.865s
------------------------------------------------------------


## Question 24

**Which genes are associated with schizophrenia?**

In [26]:

question = 'Which genes are associated with schizophrenia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 9

    disease_name gene_name
0  schizophrenia      drd2

 Run 1 completed | rows=9 | latency=21.478s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 14

    disease_name gene_name
0  schizophrenia      drd2

 Run 2 completed | rows=14 | latency=18.415s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 10

    disease_name gene_name
0  schizophrenia      drd2

 Run 3 completed | rows=10 | latency=21.142s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 1

    disease_name gene_name
0  schizophrenia      drd2

 Run 4 completed | rows=1 | latency=13.566s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 10

    disease_name gene_name
0  schizophrenia      drd2

 Run 5 completed | rows=10 | latency=22.826s
------------------------------------------------------------


## Question 25

**Which diseases are treated with valdecoxib?**

In [27]:

question = 'Which diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  osteoarthritis

 Run 1 completed | rows=2 | latency=14.794s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  osteoarthritis

 Run 2 completed | rows=2 | latency=13.575s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name]
Index: []

 Attempt 1 failed after 11.790s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  osteoarthritis

 Run 3 completed | rows=2 | latency=22.011s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  osteoarthritis

 Run 4 completed | rows=2 | latency=11.063s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 1

    drug_name    disease_name
0  valdecoxib  osteoarthritis

 Run 5 completed | rows=1 | latency=13.445s
------------------------------------------------------------


## Question 26

**What are the known targets of vandetanib?**

In [28]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       kdr

 Run 1 completed | rows=4 | latency=14.319s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       kdr

 Run 2 completed | rows=4 | latency=15.822s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  vandetanib       kdr

 Run 3 completed | rows=4 | latency=12.154s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       kdr

 Run 4 completed | rows=3 | latency=7.225s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       kdr

 Run 5 completed | rows=3 | latency=7.763s
------------------------------------------------------------


## Question 27

**Which pathways are associated with the CFTR gene?**

In [29]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name     pathway_name
0      cftr  cystic fibrosis

 Run 1 completed | rows=1 | latency=12.091s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name            pathway_name
0      cftr  camp signaling pathway

 Run 2 completed | rows=1 | latency=21.054s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

         pathway_name gene_name
0  chloride transport      cftr

 Run 3 completed | rows=1 | latency=17.004s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name            pathway_name
0      cftr  chloride ion transport

  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 12.320s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 3 failed after 17.252s: Returned DataFrame is empty
 Run 4 failed after 3 attempts
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 15.749s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 17.633s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 3 failed after 11.602s: Returned DataFrame is empty
 Run 5 failed after 3 attempts
------------------------------------------------------------


## Question 28

**Which drugs are used to treat tuberculosis?**

In [30]:

question = 'Which drugs are used to treat tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 15

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 1 completed | rows=15 | latency=20.447s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 2 completed | rows=4 | latency=14.665s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 3 completed | rows=4 | latency=11.404s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 4 completed | rows=4 | latency=14.492s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 5 completed | rows=4 | latency=8.353s
------------------------------------------------------------


## Question 29

**Which drugs are used to treat pancreatic adenocarcinoma?**

In [31]:

question = 'Which drugs are used to treat pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 3/3
Entries retrieved: 7

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 1 completed | rows=7 | latency=27.339s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 9

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 3/3
Entries retrieved: 7

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 3 completed | rows=5 | latency=24.689s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 5

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 3/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 2/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

  Attempt 3/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 5 completed | rows=8 | latency=26.519s
------------------------------------------------------------


## Question 30

**Which drugs are used to treat chronic myeloid leukemia?**

In [32]:

question = 'Which drugs are used to treat chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 1 completed | rows=6 | latency=13.528s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 2 completed | rows=5 | latency=7.930s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 3 completed | rows=6 | latency=15.654s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 4 completed | rows=6 | latency=9.936s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 5 completed | rows=6 | latency=12.400s
------------------------------------------------------------


## Question 31

**Which drugs are used to treat Parkinson’s disease?**

In [33]:

question = 'Which drugs are used to treat Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

  drug_name         disease_name
0  levodopa  parkinson's disease

 Run 1 completed | rows=15 | latency=21.818s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

  drug_name         disease_name
0  levodopa  parkinson's disease

  Attempt 2/3
Entries retrieved: 16

  drug_name         disease_name
0  levodopa  parkinson's disease

  Attempt 3/3
Entries retrieved: 15

  drug_name       disease_name
0  levodopa  parkinson disease

 Run 2 completed | rows=15 | latency=26.044s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 18

  drug_name         disease_name
0  levodopa  parkinson's disease

  Attempt 2/3
Entries retrieved: 16

  drug_name         disease_name
0  levodopa  parkinson's disease

 Run 3 completed | rows=16 | latency=25.578s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

  drug_name         disease_name
0  levodopa  parkinson's disease

 Run 4 completed | rows=15 | latency=23.873s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 14

  drug_name         disease_name
0  levodopa  parkinson's disease

 Run 5 completed | rows=14 | latency=23.794s
------------------------------------------------------------


## Question 32

**Which drugs are used to treat inflammatory bowel disease?**

In [34]:

question = 'Which drugs are used to treat inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 16

    drug_name                disease_name
0  mesalamine  inflammatory bowel disease

 Run 1 completed | rows=16 | latency=28.046s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 18

    drug_name                disease_name
0  mesalamine  inflammatory bowel disease

 Run 2 completed | rows=18 | latency=29.707s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 16

    drug_name                disease_name
0  mesalamine  inflammatory bowel disease

 Run 3 completed | rows=16 | latency=26.250s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 13

    drug_name                disease_name
0  mesalamine  inflammatory bowel disease

 Run 4 completed | rows=13 | latency=27.320s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 14

    drug_name                disease_name
0  mesalamine  inflammatory bowel disease

 Run 5 completed | rows=14 | latency=28.162s
------------------------------------------------------------


## Question 33

**Which targets are acted on by imatinib?**

In [35]:

question = 'Which targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 5

  drug_name gene_name
0  imatinib      abl1

 Run 1 completed | rows=5 | latency=12.985s
------------------------------------------------------------

 Starting run 2 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 5

  drug_name gene_name
0  imatinib      abl1

 Run 2 completed | rows=5 | latency=8.896s
------------------------------------------------------------

 Starting run 3 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      abl1

 Run 3 completed | rows=4 | latency=12.689s
------------------------------------------------------------

 Starting run 4 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      abl1

 Run 4 completed | rows=4 | latency=11.252s
------------------------------------------------------------

 Starting run 5 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      abl1

 Run 5 completed | rows=4 | latency=8.210s
------------------------------------------------------------


## Question 34

**Which biological targets does sorafenib interact with?**

In [36]:

question = 'Which biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      braf

 Run 1 completed | rows=8 | latency=11.634s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 9

   drug_name gene_name
0  sorafenib      braf

 Run 2 completed | rows=9 | latency=11.537s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      braf

 Run 3 completed | rows=8 | latency=19.262s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  sorafenib      braf

 Run 4 completed | rows=8 | latency=21.883s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 7

   drug_name gene_name
0  sorafenib      braf

 Run 5 completed | rows=7 | latency=20.352s
------------------------------------------------------------


## Question 35

**Which biological targets does tofacitinib interact with?**

In [37]:

question = 'Which biological targets does tofacitinib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  tofacitinib      jak1

 Run 1 completed | rows=2 | latency=8.795s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  tofacitinib      jak1

 Run 2 completed | rows=3 | latency=13.668s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  tofacitinib      jak1

 Run 3 completed | rows=2 | latency=14.112s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  tofacitinib      jak1

 Run 4 completed | rows=2 | latency=9.495s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  tofacitinib      jak1

 Run 5 completed | rows=3 | latency=17.249s
------------------------------------------------------------


## Question 36

**Which drugs target EGFR?**

In [38]:

question = 'Which drugs target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 12

     drug_name gene_name
0  amivantamab      egfr

 Run 1 completed | rows=12 | latency=19.220s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 13

   drug_name gene_name
0  gefitinib      egfr

 Run 2 completed | rows=13 | latency=28.139s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 14

   drug_name gene_name
0  erlotinib      egfr

 Run 3 completed | rows=14 | latency=22.120s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  erlotinib      egfr

 Run 4 completed | rows=10 | latency=21.297s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 12

   drug_name gene_name
0  gefitinib      egfr

 Run 5 completed | rows=12 | latency=25.224s
------------------------------------------------------------


## Question 37

**Which diseases are associated with TP53?**

In [39]:

question = 'Which diseases are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 9

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 1 completed | rows=9 | latency=28.467s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 2 completed | rows=6 | latency=17.315s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 8

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 3 completed | rows=8 | latency=28.278s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 9

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 4 completed | rows=9 | latency=20.589s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 5 completed | rows=6 | latency=14.317s
------------------------------------------------------------


## Question 38

**Which diseases are associated with FGFR2?**

In [40]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 1 completed | rows=9 | latency=23.863s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 6

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 2 completed | rows=6 | latency=23.624s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 7

       disease_name gene_name
0  crouzon syndrome     fgfr2

 Run 3 completed | rows=7 | latency=25.525s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 4

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 4 completed | rows=4 | latency=16.982s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 6

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 5 completed | rows=6 | latency=27.066s
------------------------------------------------------------


## Question 39

**Which diseases are associated with HTT?**

In [41]:

question = 'Which diseases are associated with HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  huntington disease       htt

 Run 1 completed | rows=1 | latency=13.247s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  huntington disease       htt

 Run 2 completed | rows=1 | latency=13.035s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  huntington disease       htt

 Run 3 completed | rows=1 | latency=10.360s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  huntington's disease       htt

 Run 4 completed | rows=1 | latency=11.769s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  huntington disease       htt

 Run 5 completed | rows=1 | latency=12.014s
------------------------------------------------------------


## Question 40

**Which genes are associated with breast cancer?**

In [42]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 13

    disease_name gene_name
0  breast cancer     brca1

 Run 1 completed | rows=13 | latency=16.788s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 15

    disease_name gene_name
0  breast cancer     brca1

  Attempt 2/3
Entries retrieved: 19

    disease_name gene_name
0  breast cancer     brca1

 Run 2 completed | rows=19 | latency=20.160s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 17

    disease_name gene_name
0  breast cancer     brca1

  Attempt 2/3
Entries retrieved: 15

    disease_name gene_name
0  breast cancer     brca1

 Run 3 completed | rows=15 | latency=18.117s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

    disease_name gene_name
0  breast cancer     brca1

 Run 4 completed | rows=10 | latency=22.077s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 7

    disease_name gene_name
0  breast cancer     brca1

 Run 5 completed | rows=7 | latency=11.576s
------------------------------------------------------------


## Question 41

**Which genes are associated with colorectal cancer?**

In [43]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 15

        disease_name gene_name
0  colorectal cancer       apc

 Run 1 completed | rows=15 | latency=19.274s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 12

        disease_name gene_name
0  colorectal cancer       apc

 Run 2 completed | rows=12 | latency=19.305s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 12

        disease_name gene_name
0  colorectal cancer       apc

 Run 3 completed | rows=12 | latency=21.540s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  colorectal cancer       apc

 Run 4 completed | rows=14 | latency=18.024s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 13

        disease_name gene_name
0  colorectal cancer       apc

 Run 5 completed | rows=13 | latency=19.628s
------------------------------------------------------------


## Question 42

**Which genes are associated with cystic fibrosis?**

In [44]:

question = 'Which genes are associated with cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 1 completed | rows=1 | latency=12.576s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      cftr  cystic fibrosis

 Run 2 completed | rows=1 | latency=17.142s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 3 completed | rows=1 | latency=13.968s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 4 completed | rows=1 | latency=9.976s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 5 completed | rows=1 | latency=9.343s
------------------------------------------------------------


## Question 43

**Which drugs are used to treat TNBC?**

In [45]:

question = 'Which drugs are used to treat TNBC?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 10

    drug_name                   disease_name
0  paclitaxel  triple-negative breast cancer

  Attempt 2/3
Entries retrieved: 11

    drug_name                   disease_name
0  paclitaxel  triple-negative breast cancer

 Run 1 completed | rows=11 | latency=23.195s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 11

     drug_name                   disease_name
0  doxorubicin  triple-negative breast cancer

 Run 2 completed | rows=11 | latency=23.390s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 10

     drug_name                   disease_name
0  doxorubicin  triple-negative breast cancer

 Run 3 completed | rows=10 | latency=19.286s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 13

    drug_name                   disease_name
0  paclitaxel  triple-negative breast cancer

  Attempt 2/3
Entries retrieved: 10

     drug_name                   disease_name
0  doxorubicin  triple-negative breast cancer

 Run 4 completed | rows=10 | latency=23.116s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 8

     drug_name                   disease_name
0  doxorubicin  triple-negative breast cancer

 Run 5 completed | rows=8 | latency=24.706s
------------------------------------------------------------


## Question 44

**Which diseases are treated with metformin?**

In [46]:

question = 'Which diseases are treated with metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  metformin  type 2 diabetes mellitus

 Run 1 completed | rows=1 | latency=14.305s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  type 2 diabetes mellitus

 Run 2 completed | rows=2 | latency=10.055s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  type 2 diabetes mellitus

 Run 3 completed | rows=2 | latency=14.162s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  metformin  type 2 diabetes mellitus

 Run 4 completed | rows=1 | latency=9.132s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name              disease_name
0  metformin  type 2 diabetes mellitus

 Run 5 completed | rows=2 | latency=14.937s
------------------------------------------------------------


## Question 45

**Which diseases are treated with adalimumab?**

In [47]:

question = 'Which diseases are treated with adalimumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 10

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 1 completed | rows=10 | latency=18.798s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 2 completed | rows=9 | latency=15.778s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 3 completed | rows=8 | latency=16.876s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 4 completed | rows=9 | latency=15.882s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 5 completed | rows=9 | latency=21.084s
------------------------------------------------------------


## Question 46

**For which diseases is pembrolizumab used?**

In [48]:

question = 'For which diseases is pembrolizumab used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name
0  pembrolizumab     melanoma

  Attempt 2/3
Entries retrieved: 8

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 1 completed | rows=8 | latency=25.799s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 2 completed | rows=11 | latency=25.873s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 3 completed | rows=9 | latency=25.320s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 12

       drug_name disease_name
0  pembrolizumab     melanoma

  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name]
Index: []

 Attempt 2 failed after 26.797s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 12

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 4 completed | rows=12 | latency=29.764s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 10

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 5 completed | rows=10 | latency=26.701s
------------------------------------------------------------


## Question 47

**Which diseases are treated with sorafenib?**

In [49]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name          disease_name
0  sorafenib  renal cell carcinoma

 Run 1 completed | rows=3 | latency=6.836s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  hepatocellular carcinoma

 Run 2 completed | rows=3 | latency=10.008s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  hepatocellular carcinoma

 Run 3 completed | rows=3 | latency=9.353s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  hepatocellular carcinoma

 Run 4 completed | rows=3 | latency=14.899s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  hepatocellular carcinoma

 Run 5 completed | rows=3 | latency=8.073s
------------------------------------------------------------


## Question 48

**Which diseases are treated with nivolumab?**

In [50]:

question = 'Which diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     melanoma

 Run 1 completed | rows=6 | latency=17.737s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 2 completed | rows=7 | latency=18.727s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 3 completed | rows=7 | latency=23.844s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 4 completed | rows=7 | latency=23.719s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 5 completed | rows=7 | latency=23.774s
------------------------------------------------------------


## Question 49

**Which genes are associated with multiple sclerosis?**

In [51]:

question = 'Which genes are associated with multiple sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 1 completed | rows=4 | latency=16.283s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 11

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 2 completed | rows=11 | latency=22.995s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 3 completed | rows=1 | latency=19.711s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 4 completed | rows=4 | latency=20.944s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 5 completed | rows=4 | latency=17.784s
------------------------------------------------------------


## Question 50

**Which genes are associated with rheumatoid arthritis?**

In [52]:

question = 'Which genes are associated with rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  rheumatoid arthritis  hla-drb1

 Run 1 completed | rows=6 | latency=16.843s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  rheumatoid arthritis  hla-drb1

 Run 2 completed | rows=5 | latency=18.384s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  rheumatoid arthritis  hla-drb1

 Run 3 completed | rows=6 | latency=15.880s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 7

           disease_name gene_name
0  rheumatoid arthritis  hla-drb1

 Run 4 completed | rows=7 | latency=17.543s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 9

           disease_name gene_name
0  rheumatoid arthritis  hla-drb1

 Run 5 completed | rows=9 | latency=17.741s
------------------------------------------------------------


## Question 51

**What are the known targets of abatacept?**

In [53]:

question = 'What are the known targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      cd80

 Run 1 completed | rows=2 | latency=4.583s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      cd80

 Run 2 completed | rows=2 | latency=8.128s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      cd80

 Run 3 completed | rows=2 | latency=7.397s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      cd80

 Run 4 completed | rows=2 | latency=5.955s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      cd80

 Run 5 completed | rows=2 | latency=15.961s
------------------------------------------------------------


## Question 52

**Which genes are associated with lung cancer?**

In [54]:

question = 'Which genes are associated with lung cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0  lung cancer      egfr

 Run 1 completed | rows=10 | latency=16.584s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 11

  disease_name gene_name
0  lung cancer      egfr

 Run 2 completed | rows=11 | latency=18.875s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0  lung cancer      egfr

 Run 3 completed | rows=10 | latency=17.913s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0  lung cancer      egfr

 Run 4 completed | rows=7 | latency=15.625s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 21

  disease_name gene_name
0  lung cancer      egfr

 Run 5 completed | rows=21 | latency=22.871s
------------------------------------------------------------


## Question 53

**What are the known targets of ponatinib?**

In [55]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 12

   drug_name gene_name
0  ponatinib      abl1

 Run 1 completed | rows=12 | latency=17.401s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 13

   drug_name gene_name
0  ponatinib      abl1

 Run 2 completed | rows=13 | latency=22.182s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 16

   drug_name gene_name
0  ponatinib      abl1

 Run 3 completed | rows=16 | latency=22.129s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 14

   drug_name gene_name
0  ponatinib      abl1

 Run 4 completed | rows=14 | latency=21.106s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 14

   drug_name gene_name
0  ponatinib      abl1

 Run 5 completed | rows=14 | latency=19.908s
------------------------------------------------------------


## Question 54

**Which drugs are used to treat systemic lupus erythematosus?**

In [56]:

question = 'Which drugs are used to treat systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 9

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 1 completed | rows=9 | latency=19.102s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 2 completed | rows=8 | latency=21.730s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 3 completed | rows=7 | latency=17.954s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 11

    drug_name                  disease_name
0  prednisone  systemic lupus erythematosus

  Attempt 2/3
Entries retrieved: 10

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 4 completed | rows=10 | latency=25.604s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 9

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 5 completed | rows=9 | latency=23.062s
------------------------------------------------------------


## Question 55

**Which genes are associated with autism spectrum disorder?**

In [57]:

question = 'Which genes are associated with autism spectrum disorder?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 18

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 1 completed | rows=18 | latency=23.977s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 18

               disease_name gene_name
0  autism spectrum disorder      chd8

  Attempt 2/3
Entries retrieved: 17

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 2 completed | rows=17 | latency=24.935s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 14

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 3 completed | rows=14 | latency=23.561s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 13

               disease_name gene_name
0  autism spectrum disorder      chd8

  Attempt 2/3
Entries retrieved: 14

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 4 completed | rows=14 | latency=19.919s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 11

               disease_name gene_name
0  autism spectrum disorder    shank3

 Run 5 completed | rows=11 | latency=23.004s
------------------------------------------------------------


## Question 56

**Which diseases are associated with the ROS1 gene?**

In [58]:

question = 'Which diseases are associated with the ROS1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 1 completed | rows=3 | latency=17.670s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 2 completed | rows=2 | latency=13.428s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 3 completed | rows=4 | latency=15.790s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 4 completed | rows=2 | latency=14.869s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 5 completed | rows=2 | latency=11.908s
------------------------------------------------------------


## Question 57

**Which diseases are associated with the ALK gene?**

In [59]:

question = 'Which diseases are associated with the ALK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  anaplastic large cell lymphoma       alk

 Run 1 completed | rows=4 | latency=14.825s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  anaplastic large cell lymphoma       alk

 Run 2 completed | rows=4 | latency=16.794s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  non-small cell lung cancer       alk

 Run 3 completed | rows=4 | latency=17.393s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

    disease_name gene_name
0  neuroblastoma       alk

 Run 4 completed | rows=4 | latency=14.548s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 5

                 disease_name gene_name
0  non-small cell lung cancer       alk

 Run 5 completed | rows=5 | latency=18.642s
------------------------------------------------------------


## Question 58

**Which diseases are associated with the EGFR gene?**

In [60]:

question = 'Which diseases are associated with the EGFR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

   disease_name gene_name
0  glioblastoma      egfr

 Run 1 completed | rows=5 | latency=16.347s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

                 disease_name gene_name
0  non-small cell lung cancer      egfr

 Run 2 completed | rows=5 | latency=18.993s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

                    disease_name gene_name
0  non-small cell lung carcinoma      egfr

 Run 3 completed | rows=5 | latency=19.951s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  non-small cell lung cancer      egfr

 Run 4 completed | rows=3 | latency=17.494s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  non-small cell lung cancer      egfr

 Run 5 completed | rows=4 | latency=27.139s
------------------------------------------------------------


## Question 59

**Which genes are associated with psoriasis?**

In [61]:

question = 'Which genes are associated with psoriasis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0    psoriasis     hla-c

 Run 1 completed | rows=10 | latency=17.081s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 8

  disease_name gene_name
0    psoriasis     hla-c

 Run 2 completed | rows=8 | latency=18.207s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0    psoriasis     hla-c

 Run 3 completed | rows=10 | latency=21.165s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 13

  disease_name gene_name
0    psoriasis     hla-c

 Run 4 completed | rows=13 | latency=18.187s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0    psoriasis     hla-c

 Run 5 completed | rows=9 | latency=21.166s
------------------------------------------------------------


## Question 60

**Which genes are associated with ulcerative colitis?**

In [62]:

question = 'Which genes are associated with ulcerative colitis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 9

         disease_name gene_name
0  ulcerative colitis     il23r

 Run 1 completed | rows=9 | latency=24.208s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 7

  gene_name        disease_name
0     il23r  ulcerative colitis

 Run 2 completed | rows=7 | latency=15.028s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 2

         disease_name gene_name
0  ulcerative colitis     il23r

 Run 3 completed | rows=2 | latency=18.672s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 10

         disease_name gene_name
0  ulcerative colitis     il23r

  Attempt 2/3
Entries retrieved: 6

         disease_name gene_name
0  ulcerative colitis     il23r

  Attempt 3/3
Entries retrieved: 1

         disease_name gene_name
0  ulcerative colitis     il23r

 Run 4 completed | rows=1 | latency=14.577s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  ulcerative colitis     il23r

 Run 5 completed | rows=5 | latency=22.916s
------------------------------------------------------------


## Question 61

**Which genes are associated with tuberculosis?**

In [5]:

question = 'Which genes are associated with tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 11

   disease_name gene_name
0  tuberculosis   slc11a1

 Run 1 completed | rows=11 | latency=14.926s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 7

   disease_name gene_name
0  tuberculosis   slc11a1

 Run 2 completed | rows=7 | latency=20.217s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 13

   disease_name gene_name
0  tuberculosis      ifng

 Run 3 completed | rows=13 | latency=20.517s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 15

   disease_name gene_name
0  tuberculosis      ifng

 Run 4 completed | rows=15 | latency=20.524s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 12

   disease_name gene_name
0  tuberculosis      ifng

 Run 5 completed | rows=12 | latency=23.651s
------------------------------------------------------------


## Question 62

**Which genes are associated with hepatitis C?**

In [64]:

question = 'Which genes are associated with hepatitis C?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0  hepatitis c     ifnl3

 Run 1 completed | rows=7 | latency=24.475s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  hepatitis c     ifnl3

 Run 2 completed | rows=2 | latency=13.609s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  hepatitis c     ifnl3

 Run 3 completed | rows=2 | latency=20.266s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  hepatitis c     ifnl3

 Run 4 completed | rows=2 | latency=19.243s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  hepatitis c     ifnl3

 Run 5 completed | rows=2 | latency=19.418s
------------------------------------------------------------


## Question 63

**Which genes are associated with Hodgkin lymphoma?**

In [65]:

question = 'Which genes are associated with Hodgkin lymphoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 8

       disease_name gene_name
0  hodgkin lymphoma       rel

 Run 1 completed | rows=8 | latency=19.659s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 6

       disease_name gene_name
0  hodgkin lymphoma       rel

 Run 2 completed | rows=6 | latency=15.113s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 7

       disease_name gene_name
0  hodgkin lymphoma       rel

 Run 3 completed | rows=7 | latency=16.794s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 7

       disease_name gene_name
0  hodgkin lymphoma       rel

 Run 4 completed | rows=7 | latency=23.474s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 8

       disease_name gene_name
0  hodgkin lymphoma       rel

 Run 5 completed | rows=8 | latency=26.508s
------------------------------------------------------------


## Question 64

**Which pathways are associated with TP53?**

In [66]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      tp53  p53 signaling pathway

 Run 1 completed | rows=4 | latency=23.487s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 19.713s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 5

  gene_name           pathway_name
0      tp53  p53 signaling pathway

 Run 2 completed | rows=5 | latency=19.507s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      tp53  p53 signaling pathway

 Run 3 completed | rows=4 | latency=26.545s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      tp53  p53 signaling pathway

 Run 4 completed | rows=4 | latency=22.728s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name           pathway_name
0      tp53  p53 signaling pathway

 Run 5 completed | rows=5 | latency=19.938s
------------------------------------------------------------


## Question 65

**Which drugs target ERBB2?**

In [67]:

question = 'Which drugs target ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  trastuzumab     erbb2

  Attempt 2/3
Entries retrieved: 10

     drug_name gene_name
0  trastuzumab     erbb2

 Run 1 completed | rows=10 | latency=18.828s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 12

     drug_name gene_name
0  trastuzumab     erbb2

  Attempt 2/3
Entries retrieved: 10

     drug_name gene_name
0  trastuzumab     erbb2

  Attempt 3/3
Entries retrieved: 9

     drug_name gene_name
0  trastuzumab     erbb2

 Run 2 completed | rows=9 | latency=26.978s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 10

     drug_name gene_name
0  trastuzumab     erbb2

 Run 3 completed | rows=10 | latency=25.372s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  trastuzumab     erbb2

  Attempt 2/3
Entries retrieved: 11

     drug_name gene_name
0  trastuzumab     erbb2

  Attempt 3/3
Entries retrieved: 9

     drug_name gene_name
0  trastuzumab     erbb2

 Run 4 completed | rows=9 | latency=24.321s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 11

     drug_name gene_name
0  trastuzumab     erbb2

 Run 5 completed | rows=11 | latency=27.576s
------------------------------------------------------------


## Question 66

**Which pathways are associated with the ADRB1 gene?**

In [68]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                            pathway_name
0     adrb1  adrenergic signaling in cardiomyocytes

 Run 1 completed | rows=2 | latency=21.709s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 22.936s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name, gene_name, pathway_name]
Index: []

 Attempt 2 failed after 12.480s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 3

  gene_name                                  pathway_name
0     adrb1  g protein-coupled receptor signaling pathway

 Run 2 completed | rows=3 | latency=18.824s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 10.876s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 3

  gene_name            pathway_name
0     adrb1  camp signaling pathway

 Run 3 completed | rows=3 | latency=24.833s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name            pathway_name
0     adrb1  camp signaling pathway

  Attempt 2/3
Entries retrieved: 8

                             pathway_name gene_name
0  adrenergic signaling in cardiomyocytes     adrb1

 Run 4 completed | rows=8 | latency=23.621s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name, gene_name, pathway_name]
Index: []

 Attempt 1 failed after 13.800s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 4

  gene_name            pathway_name
0     adrb1  gpcr signaling pathway

 Run 5 completed | rows=4 | latency=27.901s
------------------------------------------------------------


## Question 67

**Which pathways are associated with the DRD2 gene?**

In [69]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [drug_name, disease_name, gene_name, pathway_name]
Index: []

 Attempt 1 failed after 28.551s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 2

  gene_name          pathway_name
0      drd2  dopaminergic synapse

  Attempt 3/3
Entries retrieved: 4

  gene_name          pathway_name
0      drd2  dopaminergic synapse

 Run 1 completed | rows=4 | latency=28.306s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                         pathway_name
0      drd2  dopamine receptor signaling pathway

 Run 2 completed | rows=2 | latency=19.241s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0      drd2  dopaminergic synapse

 Run 3 completed | rows=2 | latency=20.913s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name          pathway_name
0      drd2  dopaminergic synapse

 Run 4 completed | rows=3 | latency=26.086s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0      drd2  dopaminergic synapse

 Run 5 completed | rows=2 | latency=20.921s
------------------------------------------------------------


## Question 68

**Which pathways are associated with the HTR2A gene?**

In [70]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 17.976s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 17.673s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 3 failed after 10.782s: Returned DataFrame is empty
 Run 1 failed after 3 attempts
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name          pathway_name
0     htr2a  serotonergic synapse

 Run 2 completed | rows=3 | latency=24.213s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 13.955s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 2 failed after 15.577s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [pathway_name, gene_name]
Index: []

 Attempt 3 failed after 22.075s: Returned DataFrame is empty
 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, pathway_name]
Index: []

 Attempt 1 failed after 27.548s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 3

  gene_name          pathway_name
0     htr2a  serotonergic synapse

  Attempt 3/3
Entries retrieved: 1

                           pathway_name gene_name
0  serotonin receptor signaling pathway     htr2a

------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                          pathway_name
0     htr2a  serotonin receptor signaling pathway

 Run 5 completed | rows=3 | latency=27.722s
------------------------------------------------------------


## Question 69

**Which drugs target CD19?**

In [71]:

question = 'Which drugs target CD19?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name
0  blinatumomab      cd19

 Run 1 completed | rows=7 | latency=15.245s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 8

          drug_name gene_name
0  tisagenlecleucel      cd19

 Run 2 completed | rows=8 | latency=28.615s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 7

                 drug_name gene_name
0  axicabtagene ciloleucel      cd19

 Run 3 completed | rows=7 | latency=23.358s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 7

          drug_name gene_name
0  tisagenlecleucel      cd19

 Run 4 completed | rows=7 | latency=29.615s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name
0  blinatumomab      cd19

 Run 5 completed | rows=7 | latency=25.046s
------------------------------------------------------------


## Question 70

**Which drugs target CTLA4?**

In [72]:

question = 'Which drugs target CTLA4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time


            if latency>30:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     ctla4

 Run 1 completed | rows=2 | latency=8.546s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     ctla4

 Run 2 completed | rows=2 | latency=11.204s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     ctla4

 Run 3 completed | rows=2 | latency=6.559s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     ctla4

 Run 4 completed | rows=2 | latency=13.247s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  ipilimumab     ctla4

 Run 5 completed | rows=2 | latency=8.622s
------------------------------------------------------------

In [6]:
import pickle
with open("OpenAI_same_question_response_final.pkl", "wb") as f:
    pickle.dump(dct_result, f)

import json
import pandas as pd

def make_json_safe(obj):
    if isinstance(obj, pd.DataFrame):
        return {
            "__type__": "dataframe",
            "columns": obj.columns.tolist(),
            "rows": obj.to_dict(orient="records")
        }
    elif isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    else:
        return obj


json_safe_result = make_json_safe(dct_result)

with open("OpenAI_same_question_response_final.json", "w", encoding="utf-8") as f:
    json.dump(
        json_safe_result,
        f,
        indent=2,
        ensure_ascii=False
    )