In [1]:
import sys
sys.path.append("../")

##### import library

In [2]:
from typing import List, Optional
import requests
import pandas as pd
import mygene
import utility
import importlib
importlib.reload(utility)
from utility import resolve_ensembl_ids_with_fallback, get_chembl_ids_fast,  get_disease_ids_fast, validate_id_dataframe
import pickle

In [3]:
dct_result = dict()

##### Read pickle

In [4]:
with open("OpenAI_same_question_response_final.pkl", "rb") as f:
    OpenAI_same_question_response = pickle.load(f)

In [5]:
for model in ['llama-3.3-70b-versatile', 'gpt-5-nano', 'grok-4-1-fast-non-reasoning-latest', "gemini-2.5-flash-lite", "OpenTarget", "BioChatter", "ctd", "ttd", "hcdt"]:

    
    # if model=="llama-3.3-70b-versatile":
    #     dct_result[model] = Llama_same_question_response[model]

    if model=="gpt-5-nano":
        dct_result[model] = OpenAI_same_question_response[model]

    # if model=='grok-4-1-fast-non-reasoning-latest':
    #     dct_result[model] = Grok_same_question_response[model]

    # if model=="gemini-2.5-flash-lite":
    #     dct_result[model] = Gemini_same_question_response[model]

    # if model=="OpenTarget":
    #     dct_result[model] = Opentarget_same_question_response[model]

    # if model=="BioChatter":
    #     dct_result[model] = Biochatter_same_question_response[model]

    # if model=="ctd":
    #     dct_result[model] = CTD_same_question_response[model]

    # if model=="hcdt":
    #     dct_result[model] = HCDT_same_question_response[model]

##### Verify if only valid columns are present

In [6]:
allowed = {"gene_name", "drug_name", "disease_name", "pathway_name"}

missing_df = []
not_dataframe = []
empty_df = []
bad_columns = []

total_payloads = 0

for model, queries in dct_result.items():
    if not isinstance(queries, dict):
        continue

    for question, runs in queries.items():
        if not isinstance(runs, dict):
            continue

        for run_id, payload in runs.items():
            total_payloads += 1

            if not isinstance(payload, dict) or "dataframe" not in payload:
                missing_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "payload_type": type(payload).__name__
                })
                continue

            df = payload.get("dataframe")

            if not isinstance(df, pd.DataFrame):
                not_dataframe.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "df_type": type(df).__name__
                })
                continue

            if df.empty:
                empty_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns)
                })

            cols = {str(c) for c in df.columns}
            extra = sorted(cols - allowed)

            if extra:
                bad_columns.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns),
                    "extra_columns": extra
                })

print(f"Total payloads checked: {total_payloads}")
print(f"Missing dataframe key: {len(missing_df)}")
print(f"Dataframe is not pd.DataFrame: {len(not_dataframe)}")
print(f"Empty dataframes: {len(empty_df)}")
print(f"Dataframes with disallowed columns: {len(bad_columns)}")

bad_columns_df = pd.DataFrame(bad_columns)
missing_df_df = pd.DataFrame(missing_df)
not_dataframe_df = pd.DataFrame(not_dataframe)
empty_df_df = pd.DataFrame(empty_df)

display(bad_columns_df)
display(missing_df_df)
display(not_dataframe_df)
display(empty_df_df)

Total payloads checked: 343
Missing dataframe key: 0
Dataframe is not pd.DataFrame: 0
Empty dataframes: 0
Dataframes with disallowed columns: 0

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [7]:
dct_jaccard = dict()

question_entities = {
    "gene_name": set(),
    "drug_name": set(),
    "disease_name": set(),
}

allowed_cols = {"gene_name", "drug_name", "disease_name"}

for model, queries in dct_result.items():
    dct_jaccard[model] = {}
    print(f"\nWorking for model: {model}")

    for question, runs in queries.items():

        for run_id, payload in runs.items():
            df = payload.get("dataframe")

            # ---- validation ----
            if not isinstance(df, pd.DataFrame) or df.empty:
                continue

            # ---- skip pathway outputs ----
            if "pathway_name" in df.columns:
                continue

            # ---- column sanity ----
            if not set(df.columns).issubset(allowed_cols):
                continue

            # ---- collect entities globally ----
            for col in allowed_cols:
                if col in df.columns:
                    values = (
                        df[col]
                        .dropna()
                        .astype(str)
                        .str.strip()
                        .tolist()
                    )
                    question_entities[col].update(values)

# ---- finalize (sets → sorted lists) ----
for k in question_entities:
    question_entities[k] = sorted(question_entities[k])

Working for model: gpt-5-nano

##### Associate id with all gene entry

In [8]:
# Resolve unique gene symbols to IDs (MyGene -> OpenTargets fallback).
df_gene = resolve_ensembl_ids_with_fallback(
    list(question_entities["gene_name"]),
    use_opentargets_fallback=True,
)
df_gene = df_gene.drop_duplicates(subset=["gene_name", "gene_id"]).reset_index(drop=True)
df_gene

2026-02-27 18:47:38,823 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:47:38,824 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:47:38,824 [INFO] querying 1-283 ...
2026-02-27 18:47:40,286 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 18:47:41,290 [INFO] Finished.
2026-02-27 18:47:41,295 [WARNING] 1 input query terms found no hit:	['ERBB1']

    gene_name          gene_id  source
0       abca7  ENSG00000064687  mygene
1        abl1  ENSG00000097007  mygene
2        abl2  ENSG00000143322  mygene
3        adnp  ENSG00000101126  mygene
4        akt1  ENSG00000142208  mygene
..        ...              ...     ...
278       vcp  ENSG00000165280  mygene
279       vdr  ENSG00000111424  mygene
280       vhl  ENSG00000134086  mygene
281      wwox  ENSG00000186153  mygene
282   znf804a  ENSG00000170396  mygene

[283 rows x 3 columns]

In [9]:
df_gene[df_gene.isna().any(axis=1)]

Empty DataFrame
Columns: [gene_name, gene_id, source]
Index: []

##### Associate id with all drug entry

In [10]:
# Resolve unique drug surface forms to IDs.
# This keeps original raw names as rows and writes mapped ID + source.
df_drug = await get_chembl_ids_fast(list(question_entities["drug_name"]))
df_drug = df_drug.drop_duplicates(subset=["drug_name", "drug_id"]).reset_index(drop=True)
df_drug

2026-02-27 18:47:57,127 [INFO] [LLM] Total 2 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:47:57,128 [INFO] [LLM] Batch size: 2

[map][drug][OpenTargets] raw='5-fluorouracil' -> id='CHEMBL185'
[map][drug][OpenTargets] raw='abatacept' -> id='CHEMBL1201823'
[map][drug][OpenTargets] raw='acetylsalicylic acid' -> id='CHEMBL25'
[map][drug][OpenTargets] raw='adalimumab' -> id='CHEMBL1201580'
[map][drug][OpenTargets] raw='ado-trastuzumab emtansine' -> id='CHEMBL1743082'
[map][drug][OpenTargets] raw='afatinib' -> id='CHEMBL1173655'
[map][drug][OpenTargets] raw='almotriptan' -> id='CHEMBL1505'
[map][drug][OpenTargets] raw='amantadine' -> id='CHEMBL660'
[map][drug][OpenTargets] raw='amikacin' -> id='CHEMBL177'
[map][drug][OpenTargets] raw='amitriptyline' -> id='CHEMBL629'
[map][drug][OpenTargets] raw='amivantamab' -> id='CHEMBL4297774'
[map][drug][OpenTargets] raw='anakinra' -> id='CHEMBL1201570'
[map][drug][OpenTargets] raw='apomorphine' -> id='CHEMBL53'
[map][drug][OpenTargets] raw='asciminib' -> id='CHEMBL4208229'
[map][drug][OpenTargets] raw='aspirin' -> id='CHEMBL25'
[map][drug][OpenTargets] raw='axicabtagene ciloleucel' -> id='CHEMBL3989989'
[map][drug][OpenTargets] raw='azathioprine' -> id='CHEMBL1542'
[map][drug][OpenTargets] raw='baricitinib' -> id='CHEMBL2105759'
[map][drug][OpenTargets] raw='bedaquiline' -> id='CHEMBL376488'
[map][drug][OpenTargets] raw='belimumab' -> id='CHEMBL1789843'
[map][drug][OpenTargets] raw='benztropine' -> id='CHEMBL1201203'
[map][drug][OpenTargets] raw='bevacizumab' -> id='CHEMBL1201583'
[map][drug][OpenTargets] raw='blinatumomab' -> id='CHEMBL1742992'
[map][drug][OpenTargets] raw='bosutinib' -> id='CHEMBL288441'
[map][drug][OpenTargets] raw='brexucabtagene autoleucel' -> id='CHEMBL4594618'
[map][drug][OpenTargets] raw='bromocriptine' -> id='CHEMBL493'
[map][drug][OpenTargets] raw='budesonide' -> id='CHEMBL1370'
[map][drug][OpenTargets] raw='cabergoline' -> id='CHEMBL1201087'
[map][drug][OpenTargets] raw='cabozantinib' -> id='CHEMBL2105717'
[map][drug][OpenTargets] raw='calcitriol' -> id='CHEMBL846'
[map][drug][OpenTargets] raw='capecitabine' -> id='CHEMBL1773'
[map][drug][OpenTargets] raw='capreomycin' -> id='CHEMBL2221250'
[map][drug][OpenTargets] raw='carbidopa' -> id='CHEMBL1200748'
[map][drug][OpenTargets] raw='carboplatin' -> id='CHEMBL1351'
[map][drug][OpenTargets] raw='certolizumab pegol' -> id='CHEMBL1201831'
[map][drug][OpenTargets] raw='cetuximab' -> id='CHEMBL1201577'
[map][drug][OpenTargets] raw='cholecalciferol' -> id='CHEMBL1042'
[map][drug][OpenTargets] raw='cisplatin' -> id='CHEMBL11359'
[map][drug][OpenTargets] raw='cyclophosphamide' -> id='CHEMBL1200796'
[map][drug][OpenTargets] raw='cyclosporine' -> id='CHEMBL160'
[map][drug][OpenTargets] raw='dacomitinib' -> id='CHEMBL2105719'
[map][drug][OpenTargets] raw='darolutamide' -> id='CHEMBL4297185'
[map][drug][OpenTargets] raw='dasatinib' -> id='CHEMBL5416410'
[map][drug][OpenTargets] raw='delamanid' -> id='CHEMBL218650'
[map][drug][OpenTargets] raw='depatuxizumab mafodotin' -> id='CHEMBL3707277'
[map][drug][OpenTargets] raw='dihydroergotamine' -> id='CHEMBL1732'
[map][drug][OpenTargets] raw='docetaxel' -> id='CHEMBL3545252'
[map][drug][OpenTargets] raw='doxorubicin' -> id='CHEMBL53463'
[map][drug][OpenTargets] raw='eletriptan' -> id='CHEMBL1510'
[map][drug][OpenTargets] raw='entacapone' -> id='CHEMBL953'
[map][drug][OpenTargets] raw='epirubicin' -> id='CHEMBL417'
[map][drug][OpenTargets] raw='erenumab' -> id='CHEMBL3833329'
[map][drug][OpenTargets] raw='ergocalciferol' -> id='CHEMBL1536'
[map][drug][OpenTargets] raw='ergotamine' -> id='CHEMBL442'
[map][drug][OpenTargets] raw='erlotinib' -> id='CHEMBL553'
[map][drug][OpenTargets] raw='etanercept' -> id='CHEMBL1201572'
[map][drug][OpenTargets] raw='ethambutol' -> id='CHEMBL44884'
[map][drug][OpenTargets] raw='ethionamide' -> id='CHEMBL1441'
[map][drug][OpenTargets] raw='fluorouracil' -> id='CHEMBL185'
[map][drug][OpenTargets] raw='folinic acid' -> id='CHEMBL1232801'
[map][drug][OpenTargets] raw='fremanezumab' -> id='CHEMBL4297756'
[map][drug][OpenTargets] raw='frovatriptan' -> id='CHEMBL1279'
[map][drug][OpenTargets] raw='galcanezumab' -> id='CHEMBL3707328'
[map][drug][OpenTargets] raw='gefitinib' -> id='CHEMBL939'
[map][drug][OpenTargets] raw='gemcitabine' -> id='CHEMBL888'
[map][drug][OpenTargets] raw='golimumab' -> id='CHEMBL1201833'
[map][drug][OpenTargets] raw='hydrocortisone' -> id='CHEMBL389621'
[map][drug][OpenTargets] raw='hydroxychloroquine' -> id='CHEMBL1535'
[map][drug][OpenTargets] raw='hydroxyurea' -> id='CHEMBL467'
[map][drug][OpenTargets] raw='ibuprofen' -> id='CHEMBL521'
[map][drug][OpenTargets] raw='icotinib' -> id='CHEMBL2087361'
[map][drug][OpenTargets] raw='imatinib' -> id='CHEMBL941'
[map][drug][OpenTargets] raw='inebilizumab' -> id='CHEMBL2109334'
[map][drug][OpenTargets] raw='infliximab' -> id='CHEMBL1201581'
[map][drug][OpenTargets] raw='ipilimumab' -> id='CHEMBL1789844'
[map][drug][OpenTargets] raw='irinotecan' -> id='CHEMBL481'
[map][drug][OpenTargets] raw='isoniazid' -> id='CHEMBL64'
[map][drug][OpenTargets] raw='kanamycin' -> id='CHEMBL1384'
[map][drug][OpenTargets] raw='lapatinib' -> id='CHEMBL554'
[map][drug][OpenTargets] raw='lasmiditan' -> id='CHEMBL3039520'
[map][drug][OpenTargets] raw='leflunomide' -> id='CHEMBL960'
[map][drug][OpenTargets] raw='leucovorin' -> id='CHEMBL1679'
[map][drug][OpenTargets] raw='levodopa' -> id='CHEMBL1009'
[map][drug][OpenTargets] raw='lisocabtagene maraleucel' -> id='CHEMBL4297236'
[map][drug][OpenTargets] raw='loncastuximab tesirine' -> id='CHEMBL4297778'
[map][drug][OpenTargets] raw='margetuximab' -> id='CHEMBL2364649'
[map][drug][OpenTargets] raw='mesalamine' -> id='CHEMBL704'
[map][drug][OpenTargets] raw='metformin' -> id='CHEMBL1431'
[map][drug][OpenTargets] raw='methotrexate' -> id='CHEMBL34259'
[map][drug][OpenTargets] raw='methylprednisolone' -> id='CHEMBL650'
[map][drug][OpenTargets] raw='metoprolol' -> id='CHEMBL13'
[map][drug][OpenTargets] raw='mycophenolate mofetil' -> id='CHEMBL1456'
[map][drug][OpenTargets] raw='naproxen' -> id='CHEMBL154'
[map][drug][OpenTargets] raw='naratriptan' -> id='CHEMBL1278'
[map][drug][OpenTargets] raw='natalizumab' -> id='CHEMBL1201607'
[map][drug][OpenTargets] raw='necitumumab' -> id='CHEMBL1743047'
[map][drug][OpenTargets] raw='neratinib' -> id='CHEMBL180022'
[map][drug][OpenTargets] raw='nilotinib' -> id='CHEMBL255863'
[map][drug][OpenTargets] raw='nimotuzumab' -> id='CHEMBL2108359'
[map][drug][OpenTargets] raw='nivolumab' -> id='CHEMBL2108738'
[map][drug][OpenTargets] raw='olaparib' -> id='CHEMBL521686'
[map][drug][OpenTargets] raw='olsalazine' -> id='CHEMBL425'
[map][drug][OpenTargets] raw='opicapone' -> id='CHEMBL1089318'
[map][drug][OpenTargets] raw='osimertinib' -> id='CHEMBL3353410'
[map][drug][OpenTargets] raw='oxaliplatin' -> id='CHEMBL414804'
[map][drug][OpenTargets] raw='paclitaxel' -> id='CHEMBL428647'
[map][drug][OpenTargets] raw='panitumumab' -> id='CHEMBL1201827'
[map][drug][OpenTargets] raw='para-aminosalicylic acid' -> id='CHEMBL1169'
[map][drug][OpenTargets] raw='paracetamol' -> id='CHEMBL112'
[map][drug][OpenTargets] raw='pembrolizumab' -> id='CHEMBL3137343'
[map][drug][OpenTargets] raw='penicillamine' -> id='CHEMBL1430'
[map][drug][OpenTargets] raw='pertuzumab' -> id='CHEMBL2007641'
[map][drug][OpenTargets] raw='pimavanserin' -> id='CHEMBL2111101'
[map][drug][OpenTargets] raw='ponatinib' -> id='CHEMBL1171837'
[map][drug][OpenTargets] raw='pramipexole' -> id='CHEMBL301265'
[map][drug][OpenTargets] raw='prednisolone' -> id='CHEMBL131'
[map][drug][OpenTargets] raw='prednisone' -> id='CHEMBL635'
[map][drug][OpenTargets] raw='pretomanid' -> id='CHEMBL227875'
[map][drug][OpenTargets] raw='propranolol' -> id='CHEMBL27'
[map][drug][OpenTargets] raw='pyrazinamide' -> id='CHEMBL614'
[map][drug][OpenTargets] raw='pyrotinib' -> id='CHEMBL3647420'
[map][drug][OpenTargets] raw='rasagiline' -> id='CHEMBL887'
[map][drug][OpenTargets] raw='regorafenib' -> id='CHEMBL1946170'
[map][drug][OpenTargets] raw='rifabutin' -> id='CHEMBL444633'
[map][drug][OpenTargets] raw='rifampicin' -> id='CHEMBL374478'
[map][drug][OpenTargets] raw='rifapentine' -> id='CHEMBL1660'
[map][drug][OpenTargets] raw='rimegepant' -> id='CHEMBL2178422'
[map][drug][OpenTargets] raw='rituximab' -> id='CHEMBL1201576'
[map][drug][OpenTargets] raw='rizatriptan' -> id='CHEMBL905'
[map][drug][OpenTargets] raw='ropinirole' -> id='CHEMBL589'
[map][drug][OpenTargets] raw='rotigotine' -> id='CHEMBL1303'
[map][drug][OpenTargets] raw='sacituzumab govitecan' -> id='CHEMBL3545262'
[map][drug][OpenTargets] raw='safinamide' -> id='CHEMBL396778'
[map][drug][OpenTargets] raw='sarilumab' -> id='CHEMBL2108730'
[map][drug][OpenTargets] raw='selegiline' -> id='CHEMBL972'
[map][drug][OpenTargets] raw='sorafenib' -> id='CHEMBL1336'
[map][drug][OpenTargets] raw='streptomycin' -> id='CHEMBL372795'
[map][drug][OpenTargets] raw='sulfasalazine' -> id='CHEMBL421'
[map][drug][OpenTargets] raw='sumatriptan' -> id='CHEMBL128'
[map][drug][OpenTargets] raw='tacrolimus' -> id='CHEMBL3989887'
[map][drug][OpenTargets] raw='tafasitamab' -> id='CHEMBL4298047'
[map][drug][OpenTargets] raw='talazoparib' -> id='CHEMBL3137320'
[map][drug][OpenTargets] raw='tisagenlecleucel' -> id='CHEMBL3301574'
[map][drug][OpenTargets] raw='tocilizumab' -> id='CHEMBL1237022'
[map][drug][OpenTargets] raw='tofacitinib' -> id='CHEMBL221959'
[map][drug][OpenTargets] raw='tolcapone' -> id='CHEMBL1324'
[map][drug][OpenTargets] raw='topiramate' -> id='CHEMBL220492'
[map][drug][OpenTargets] raw='trastuzumab' -> id='CHEMBL1201585'
[map][drug][OpenTargets] raw='trastuzumab deruxtecan' -> id='CHEMBL4297844'
[map][drug][OpenTargets] raw='trastuzumab emtansine' -> id='CHEMBL1743082'
[map][drug][OpenTargets] raw='tremelimumab' -> id='CHEMBL2108658'
[map][drug][OpenTargets] raw='trihexyphenidyl' -> id='CHEMBL1490'
[map][drug][OpenTargets] raw='tucatinib' -> id='CHEMBL3989868'
[map][drug][OpenTargets] raw='ubrogepant' -> id='CHEMBL2364638'
[map][drug][OpenTargets] raw='upadacitinib' -> id='CHEMBL3622821'
[map][drug][OpenTargets] raw='ustekinumab' -> id='CHEMBL1201835'
[map][drug][OpenTargets] raw='valdecoxib' -> id='CHEMBL865'
[map][drug][OpenTargets] raw='valproic acid' -> id='CHEMBL109'
[map][drug][OpenTargets] raw='vandetanib' -> id='CHEMBL24828'
[map][drug][OpenTargets] raw='vedolizumab' -> id='CHEMBL1743087'
[map][drug][OpenTargets] raw='zolmitriptan' -> id='CHEMBL1185'

2026-02-27 18:47:57,535 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:47:57,556 [INFO] [LLM] Batch done in 0.43s
2026-02-27 18:47:57,556 [INFO] [OT] Verifying 1 unique drug suggestions...
2026-02-27 18:47:57,955 [INFO] [OT] 'mercaptopurine' → 'MERCAPTOPURINE' (CHEMBL1200751)
2026-02-27 18:47:57,957 [INFO] Done: 1 / 2 confirmed | 1 → None

[map][drug][Llama] raw='6-mercaptopurine' -> canonical='MERCAPTOPURINE' -> id='CHEMBL1200751'

                drug_name        drug_id       source
0          5-fluorouracil      CHEMBL185  OpenTargets
1        6-mercaptopurine  CHEMBL1200751        Llama
2               abatacept  CHEMBL1201823  OpenTargets
3    acetylsalicylic acid       CHEMBL25  OpenTargets
4              adalimumab  CHEMBL1201580  OpenTargets
..                    ...            ...          ...
158            valdecoxib      CHEMBL865  OpenTargets
159         valproic acid      CHEMBL109  OpenTargets
160            vandetanib    CHEMBL24828  OpenTargets
161           vedolizumab  CHEMBL1743087  OpenTargets
162          zolmitriptan     CHEMBL1185  OpenTargets

[163 rows x 3 columns]

In [11]:
df_drug["source"].value_counts()

source
OpenTargets    161
Llama            1
Name: count, dtype: int64

In [12]:
# df_drug[df_drug["source"]=="Llama"]

In [13]:
df_drug[df_drug.isna().any(axis=1)]

             drug_name drug_id source
34  carbidopa/levodopa    None   None

##### Associate id with all disease entry

In [14]:
# Resolve unique disease surface forms to IDs.
# Canonical fallback is internal; returned rows remain keyed by raw input disease_name.
df_disease = await get_disease_ids_fast(list(question_entities["disease_name"]))
df_disease = df_disease.drop_duplicates(subset=["disease_name", "disease_id"]).reset_index(drop=True)
df_disease

2026-02-27 18:47:59,261 [INFO] [LLM] Total 14 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:47:59,263 [INFO] [LLM] Batch size: 14

[map][disease][OpenTargets] raw='acute lymphoblastic leukemia' -> id='EFO_0000220'
[map][disease][OpenTargets] raw='acute myeloid leukemia' -> id='EFO_0000222'
[map][disease][OpenTargets] raw='acute myeloid leukemia with mutated npm1' -> id='MONDO_0044923'
[map][disease][OpenTargets] raw='adrenocortical carcinoma' -> id='EFO_1000796'
[map][disease][OpenTargets] raw='alzheimer's disease' -> id='MONDO_0007088'
[map][disease][OpenTargets] raw='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][OpenTargets] raw='anaplastic large cell lymphoma' -> id='EFO_0003032'
[map][disease][OpenTargets] raw='anaplastic thyroid carcinoma' -> id='EFO_1000595'
[map][disease][OpenTargets] raw='ankylosing spondylitis' -> id='EFO_0003898'
[map][disease][OpenTargets] raw='apert syndrome' -> id='MONDO_0007041'
[map][disease][OpenTargets] raw='autism spectrum disorder' -> id='EFO_0003756'
[map][disease][OpenTargets] raw='beare-stevenson cutis gyrata syndrome' -> id='MONDO_0007412'
[map][disease][OpenTargets] raw='beare-stevenson syndrome' -> id='MONDO_0007412'
[map][disease][OpenTargets] raw='blau syndrome' -> id='MONDO_0008523'
[map][disease][OpenTargets] raw='breast cancer' -> id='EFO_0000305'
[map][disease][OpenTargets] raw='cardiofaciocutaneous syndrome' -> id='MONDO_0015280'
[map][disease][OpenTargets] raw='cervical cancer' -> id='EFO_0001061'
[map][disease][OpenTargets] raw='cholangiocarcinoma' -> id='EFO_0005221'
[map][disease][OpenTargets] raw='choroid plexus carcinoma' -> id='MONDO_0009837'
[map][disease][OpenTargets] raw='chronic myeloid leukemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='classical hodgkin lymphoma' -> id='MONDO_0009348'
[map][disease][OpenTargets] raw='colorectal adenocarcinoma' -> id='EFO_0000365'
[map][disease][OpenTargets] raw='colorectal cancer' -> id='EFO_1001951'
[map][disease][OpenTargets] raw='crohn's disease' -> id='EFO_0000384'
[map][disease][OpenTargets] raw='crouzon syndrome' -> id='MONDO_0007405'
[map][disease][OpenTargets] raw='cutaneous squamous cell carcinoma' -> id='EFO_1001927'
[map][disease][OpenTargets] raw='cystic fibrosis' -> id='MONDO_0009061'
[map][disease][OpenTargets] raw='dedifferentiated liposarcoma' -> id='EFO_0003085'
[map][disease][OpenTargets] raw='differentiated thyroid carcinoma' -> id='EFO_1002017'
[map][disease][OpenTargets] raw='endometrial cancer' -> id='EFO_0007532'
[map][disease][OpenTargets] raw='endometrial carcinoma' -> id='EFO_1001512'
[map][disease][OpenTargets] raw='epilepsy' -> id='EFO_0000474'
[map][disease][OpenTargets] raw='epithelial ovarian cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='erdheim-chester disease' -> id='EFO_1000926'
[map][disease][OpenTargets] raw='esophageal cancer' -> id='EFO_0002916'
[map][disease][OpenTargets] raw='fallopian tube cancer' -> id='EFO_1000251'
[map][disease][OpenTargets] raw='familial mediterranean fever' -> id='MONDO_0009572'
[map][disease][OpenTargets] raw='fever' -> id='HP_0001945'
[map][disease][OpenTargets] raw='follicular thyroid carcinoma' -> id='EFO_0000501'
[map][disease][OpenTargets] raw='gastric cancer' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='gastroesophageal junction adenocarcinoma' -> id='MONDO_0003219'
[map][disease][OpenTargets] raw='glioblastoma' -> id='EFO_0000519'
[map][disease][OpenTargets] raw='hairy cell leukemia' -> id='EFO_1000956'
[map][disease][OpenTargets] raw='head and neck squamous cell carcinoma' -> id='EFO_0000181'
[map][disease][OpenTargets] raw='hepatitis c' -> id='EFO_0003047'
[map][disease][OpenTargets] raw='hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='hidradenitis suppurativa' -> id='EFO_1000710'
[map][disease][OpenTargets] raw='hodgkin lymphoma' -> id='EFO_0000183'
[map][disease][OpenTargets] raw='huntington disease' -> id='MONDO_0007739'
[map][disease][OpenTargets] raw='huntington's disease' -> id='MONDO_0007739'
[map][disease][OpenTargets] raw='inflammatory bowel disease' -> id='EFO_0003767'
[map][disease][OpenTargets] raw='inflammatory myofibroblastic tumor' -> id='MONDO_0015798'
[map][disease][OpenTargets] raw='intrahepatic cholangiocarcinoma' -> id='EFO_1001961'
[map][disease][OpenTargets] raw='jackson-weiss syndrome' -> id='MONDO_0007400'
[map][disease][OpenTargets] raw='juvenile idiopathic arthritis' -> id='EFO_0002609'
[map][disease][OpenTargets] raw='langerhans cell histiocytosis' -> id='EFO_1000318'
[map][disease][OpenTargets] raw='leukemia' -> id='EFO_0000565'
[map][disease][OpenTargets] raw='li-fraumeni syndrome' -> id='MONDO_0018875'
[map][disease][OpenTargets] raw='liposarcoma' -> id='EFO_0000569'
[map][disease][OpenTargets] raw='lung adenocarcinoma' -> id='EFO_0005288'
[map][disease][OpenTargets] raw='lung cancer' -> id='EFO_0001071'
[map][disease][OpenTargets] raw='majeed syndrome' -> id='MONDO_0012316'
[map][disease][OpenTargets] raw='melanoma' -> id='EFO_0000756'
[map][disease][OpenTargets] raw='merkel cell carcinoma' -> id='EFO_1001471'
[map][disease][OpenTargets] raw='mevalonate kinase deficiency' -> id='MONDO_0017708'
[map][disease][OpenTargets] raw='migraine' -> id='MONDO_0005277'
[map][disease][OpenTargets] raw='multiple sclerosis' -> id='MONDO_0005301'
[map][disease][OpenTargets] raw='myelodysplastic syndrome' -> id='EFO_0000198'
[map][disease][OpenTargets] raw='neovascular age-related macular degeneration' -> id='EFO_0004683'
[map][disease][OpenTargets] raw='neuroblastoma' -> id='EFO_0000621'
[map][disease][OpenTargets] raw='non-small cell lung cancer' -> id='EFO_0003060'
[map][disease][OpenTargets] raw='non-small cell lung carcinoma' -> id='EFO_0003060'
[map][disease][OpenTargets] raw='noonan syndrome' -> id='MONDO_0018997'
[map][disease][OpenTargets] raw='osteoarthritis' -> id='MONDO_0005178'
[map][disease][OpenTargets] raw='osteosarcoma' -> id='EFO_0000637'
[map][disease][OpenTargets] raw='ovarian cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='ovarian mucinous adenocarcinoma' -> id='EFO_0006462'
[map][disease][OpenTargets] raw='pancreatic adenocarcinoma' -> id='EFO_1000044'
[map][disease][OpenTargets] raw='pancreatic cancer' -> id='EFO_0002618'
[map][disease][OpenTargets] raw='pancreatic ductal adenocarcinoma' -> id='MONDO_0005184'
[map][disease][OpenTargets] raw='papa syndrome' -> id='MONDO_0011462'
[map][disease][OpenTargets] raw='papillary thyroid carcinoma' -> id='EFO_0000641'
[map][disease][OpenTargets] raw='parkinson disease' -> id='MONDO_0005180'
[map][disease][OpenTargets] raw='parkinson's disease' -> id='MONDO_0005180'
[map][disease][OpenTargets] raw='pfeiffer syndrome' -> id='MONDO_0007043'
[map][disease][OpenTargets] raw='pilocytic astrocytoma' -> id='MONDO_0004000'
[map][disease][OpenTargets] raw='plaque psoriasis' -> id='EFO_1001494'
[map][disease][OpenTargets] raw='pleomorphic xanthoastrocytoma' -> id='MONDO_0016690'
[map][disease][OpenTargets] raw='polycystic ovary syndrome' -> id='EFO_0000660'
[map][disease][OpenTargets] raw='primary peritoneal cancer' -> id='MONDO_0015686'
[map][disease][OpenTargets] raw='psoriasis' -> id='EFO_0000676'
[map][disease][OpenTargets] raw='psoriatic arthritis' -> id='EFO_0003778'
[map][disease][OpenTargets] raw='renal cell carcinoma' -> id='EFO_0000681'
[map][disease][OpenTargets] raw='rhabdomyosarcoma' -> id='EFO_0002918'
[map][disease][OpenTargets] raw='rheumatoid arthritis' -> id='EFO_0000685'
[map][disease][OpenTargets] raw='rickets' -> id='EFO_0005583'
[map][disease][OpenTargets] raw='schizophrenia' -> id='MONDO_0005090'
[map][disease][OpenTargets] raw='soft tissue sarcoma' -> id='EFO_1001968'
[map][disease][OpenTargets] raw='squamous cell carcinoma of the head and neck' -> id='EFO_0000181'
[map][disease][OpenTargets] raw='systemic lupus erythematosus' -> id='MONDO_0007915'
[map][disease][OpenTargets] raw='thymic carcinoma' -> id='EFO_1000576'
[map][disease][OpenTargets] raw='tnf receptor-associated periodic syndrome' -> id='MONDO_0007727'
[map][disease][OpenTargets] raw='triple-negative breast cancer' -> id='EFO_0005537'
[map][disease][OpenTargets] raw='tuberculosis' -> id='MONDO_0018076'
[map][disease][OpenTargets] raw='type 2 diabetes mellitus' -> id='MONDO_0005148'
[map][disease][OpenTargets] raw='ulcerative colitis' -> id='EFO_0000729'
[map][disease][OpenTargets] raw='urothelial carcinoma' -> id='EFO_0008528'
[map][disease][OpenTargets] raw='uveitis' -> id='EFO_1001231'
[map][disease][OpenTargets] raw='well-differentiated liposarcoma' -> id='EFO_0000736'

2026-02-27 18:47:59,827 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:47:59,829 [INFO] [LLM] Batch done in 0.57s
2026-02-27 18:47:59,830 [INFO] [LLM] 'acute myeloid leukemia with npm1 mutation' → None
2026-02-27 18:47:59,831 [INFO] [LLM] 'alk-positive diffuse large b-cell lymphoma' → None
2026-02-27 18:47:59,831 [INFO] [LLM] 'anal canal squamous cell carcinoma' → None
2026-02-27 18:47:59,832 [INFO] [LLM] 'cryopyrin-associated periodic syndromes' → 'cryopyrin-associated periodic syndrome'
2026-02-27 18:47:59,833 [INFO] [LLM] 'gastroesophageal junction cancer' → None
2026-02-27 18:47:59,833 [INFO] [LLM] 'low-grade serous ovarian carcinoma' → None
2026-02-27 18:47:59,834 [INFO] [LLM] 'nlrp12-related autoinflammatory disease' → None
2026-02-27 18:47:59,834 [INFO] [LLM] 'non-metastatic castration-resistant prostate cancer' → None
2026-02-27 18:47:59,835 [INFO] [LLM] 'non-radiographic axial spondyloarthritis' → None
2026-02-27 18:47:59,835 [INFO] [LLM] 'noninfectious uveitis' → None
2026-02-27 18:47:59,836 [INFO] [LLM] 'nonmetastatic castration-resistant prostate cancer' → None
2026-02-27 18:47:59,836 [INFO] [LLM] 'primary mediastinal large b-cell lymphoma' → None
2026-02-27 18:47:59,836 [INFO] [LLM] 'psoriasis tyk2' → None
2026-02-27 18:47:59,837 [INFO] [LLM] 'systemic lupus erytheus' → 'systemic lupus erythematosus'
2026-02-27 18:47:59,837 [INFO] [OT] Verifying 2 unique suggestions...
2026-02-27 18:48:00,252 [INFO] [OT] 'systemic lupus erythematosus' → 'systemic lupus erythematosus' (MONDO_0007915)
2026-02-27 18:48:00,254 [INFO] [OT] 'cryopyrin-associated periodic syndrome' → 'cryopyrin-associated periodic syndrome' (MONDO_0016168)
2026-02-27 18:48:00,256 [INFO] Done: 2 / 14 confirmed | 12 → None

[map][disease][Llama] raw='cryopyrin-associated periodic syndromes' -> canonical='cryopyrin-associated periodic syndrome' -> id='MONDO_0016168'
[map][disease][Llama] raw='systemic lupus erytheus' -> canonical='systemic lupus erythematosus' -> id='MONDO_0007915'
[warn] Unresolved diseases after OpenTargets/Llama/OLS: ['acute myeloid leukemia with npm1 mutation', 'alk-positive diffuse large b-cell lymphoma', 'anal canal squamous cell carcinoma', 'gastroesophageal junction cancer', 'low-grade serous ovarian carcinoma', 'nlrp12-related autoinflammatory disease', 'non-metastatic castration-resistant prostate cancer', 'non-radiographic axial spondyloarthritis', 'noninfectious uveitis', 'nonmetastatic castration-resistant prostate cancer', 'primary mediastinal large b-cell lymphoma', 'psoriasis tyk2']

                                  disease_name     disease_id       source
0                 acute lymphoblastic leukemia    EFO_0000220  OpenTargets
1                       acute myeloid leukemia    EFO_0000222  OpenTargets
2     acute myeloid leukemia with mutated npm1  MONDO_0044923  OpenTargets
3    acute myeloid leukemia with npm1 mutation           None         None
4                     adrenocortical carcinoma    EFO_1000796  OpenTargets
..                                         ...            ...          ...
118                   type 2 diabetes mellitus  MONDO_0005148  OpenTargets
119                         ulcerative colitis    EFO_0000729  OpenTargets
120                       urothelial carcinoma    EFO_0008528  OpenTargets
121                                    uveitis    EFO_1001231  OpenTargets
122            well-differentiated liposarcoma    EFO_0000736  OpenTargets

[123 rows x 3 columns]

In [15]:
df_disease["source"].value_counts()

source
OpenTargets    109
Llama            2
Name: count, dtype: int64

In [16]:
df_disease[df_disease.isna().any(axis=1)]

                                          disease_name disease_id source
3            acute myeloid leukemia with npm1 mutation       None   None
5           alk-positive diffuse large b-cell lymphoma       None   None
8                   anal canal squamous cell carcinoma       None   None
45                    gastroesophageal junction cancer       None   None
64                  low-grade serous ovarian carcinoma       None   None
76             nlrp12-related autoinflammatory disease       None   None
77   non-metastatic castration-resistant prostate c...       None   None
78            non-radiographic axial spondyloarthritis       None   None
81                               noninfectious uveitis       None   None
82   nonmetastatic castration-resistant prostate ca...       None   None
100          primary mediastinal large b-cell lymphoma       None   None
103                                     psoriasis tyk2       None   None

In [17]:
# ------------------------------------------------------------------
# Disease canonical audit (OpenTargets-strict IDs only)
# ------------------------------------------------------------------
# IMPORTANT:
# - This cell runs an additional Llama canonicalization pass over unresolved rows.
# - IDs are still resolved ONLY via OpenTargets mapIds (score==1).
# - To avoid changing the baseline resolver output, writeback is OFF by default.
APPLY_AUDIT_MAPPINGS = False

# 1) Rows unresolved after primary resolver
unresolved_rows = df_disease[df_disease["disease_id"].isna()].reset_index(drop=True)
unresolved_raw_names = list(
    dict.fromkeys(
        str(name).strip()
        for name in unresolved_rows["disease_name"].dropna().astype(str).tolist()
        if str(name).strip()
    )
)

# 2) Llama canonicalization suggestions
disease_input_map = {name: None for name in unresolved_raw_names}
canonicalisation_map = await utility.canonicalise_disease_dict(disease_input_map)

# 3) OpenTargets strict verification (score==1 only)
canonical_terms_norm = list(
    dict.fromkeys(
        utility._normalize_disease_term(v)
        for v in canonicalisation_map.values()
        if isinstance(v, str) and v.strip()
    )
)
canonical_to_id = utility.resolve_diseases_opentargets_bulk(
    canonical_terms_norm,
    strict_score_one=True,
)

# 4) Build persistent audit table
audit_rows = []
applied_count = 0
candidate_count = 0

for raw_disease_name in unresolved_raw_names:
    canonical_name = canonicalisation_map.get(raw_disease_name)
    if isinstance(canonical_name, str) and canonical_name.strip():
        canonical_name = canonical_name.strip()
        canonical_norm = utility._normalize_disease_term(canonical_name)
        resolved_id = canonical_to_id.get(canonical_norm)
    else:
        canonical_name = None
        canonical_norm = None
        resolved_id = None

    can_apply = bool(resolved_id)
    if can_apply:
        candidate_count += 1
        print(f"[audit][disease][Llama->OT] raw='{raw_disease_name}' -> canonical='{canonical_name}' -> id='{resolved_id}'")

    if can_apply and APPLY_AUDIT_MAPPINGS:
        mask = df_disease["disease_name"].astype(str).str.strip() == raw_disease_name
        df_disease.loc[mask, "disease_id"] = resolved_id
        df_disease.loc[mask, "source"] = "Llama"
        applied_count += 1

    status = (
        "mappable_ot_exact" if can_apply else
        ("no_canonical" if canonical_name is None else "canonical_not_in_ot")
    )
    audit_rows.append({
        "raw_disease_name": raw_disease_name,
        "canonical_name": canonical_name,
        "canonical_norm": canonical_norm,
        "resolved_disease_id": resolved_id,
        "status": status,
        "can_apply": can_apply,
        "applied": bool(can_apply and APPLY_AUDIT_MAPPINGS),
    })

disease_canonical_audit_df = pd.DataFrame(audit_rows)
if not disease_canonical_audit_df.empty:
    disease_canonical_audit_df = disease_canonical_audit_df.sort_values(
        ["status", "raw_disease_name"],
        ascending=[True, True],
    ).reset_index(drop=True)

print(f"[summary][disease][audit] OT-mappable candidates: {candidate_count}")
print(f"[summary][disease][audit] applied to df_disease: {applied_count} (APPLY_AUDIT_MAPPINGS={APPLY_AUDIT_MAPPINGS})")
if not disease_canonical_audit_df.empty:
    print("[summary][disease][audit] status counts:")
    print(disease_canonical_audit_df["status"].value_counts(dropna=False))

disease_canonical_audit_df

2026-02-27 18:48:00,809 [INFO] [LLM] Total 12 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:48:00,811 [INFO] [LLM] Batch size: 12
2026-02-27 18:48:01,325 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:48:01,328 [INFO] [LLM] Batch done in 0.52s
2026-02-27 18:48:01,329 [INFO] [LLM] 'acute myeloid leukemia with npm1 mutation' → None
2026-02-27 18:48:01,330 [INFO] [LLM] 'alk-positive diffuse large b-cell lymphoma' → None
2026-02-27 18:48:01,331 [INFO] [LLM] 'anal canal squamous cell carcinoma' → None
2026-02-27 18:48:01,331 [INFO] [LLM] 'gastroesophageal junction cancer' → None
2026-02-27 18:48:01,332 [INFO] [LLM] 'low-grade serous ovarian carcinoma' → None
2026-02-27 18:48:01,332 [INFO] [LLM] 'nlrp12-related autoinflammatory disease' → None
2026-02-27 18:48:01,333 [INFO] [LLM] 'non-metastatic castration-resistant prostate cancer' → None
2026-02-27 18:48:01,333 [INFO] [LLM] 'non-radiographic axial spondyloarthritis' → None
2026-02-27 18:48:01,334 [INFO] [LLM] 'noninfectious uveitis' → None
2026-02-27 18:48:01,335 [INFO] [LLM] 'nonmetastatic castration-resistant prostate cancer' → None
2026-02-27 18:48:01,335 [INFO] [LLM] 'primary mediastinal large b-cell lymphoma' → None
2026-02-27 18:48:01,336 [INFO] [LLM] 'psoriasis tyk2' → None
2026-02-27 18:48:01,336 [INFO] Done: 0 / 12 confirmed | 12 → None

[summary][disease][audit] OT-mappable candidates: 0
[summary][disease][audit] applied to df_disease: 0 (APPLY_AUDIT_MAPPINGS=False)
[summary][disease][audit] status counts:
status
no_canonical    12
Name: count, dtype: int64

,raw_disease_name,canonical_name,canonical_norm,resolved_disease_id,status,can_apply,applied
0,acute myeloid leukemia with npm1 mutation,None,None,None,no_canonical,False,False
1,alk-positive diffuse large b-cell lymphoma,None,None,None,no_canonical,False,False
2,anal canal squamous cell carcinoma,None,None,None,no_canonical,False,False
3,gastroesophageal junction cancer,None,None,None,no_canonical,False,False
4,low-grade serous ovarian carcinoma,None,None,None,no_canonical,False,False
5,nlrp12-related autoinflammatory disease,None,None,None,no_canonical,False,False
6,non-metastatic castration-resistant prostate c...,None,None,None,no_canonical,False,False
7,non-radiographic axial spondyloarthritis,None,None,None,no_canonical,False,False
8,noninfectious uveitis,None,None,None,no_canonical,False,False
9,nonmetastatic castration-resistant prostate ca...,None,None,None,no_canonical,False,False
10,primary mediastinal large b-cell lymphoma,None,None,None,no_canonical,False,False
11,psoriasis tyk2,None,None,None,no_canonical,False,False

In [18]:
# disease_canonical_audit_df

In [19]:
df_disease[df_disease["source"]=='Llama']

                                disease_name     disease_id source
28   cryopyrin-associated periodic syndromes  MONDO_0016168  Llama
113                  systemic lupus erytheus  MONDO_0007915  Llama

In [20]:
df_disease["source"].value_counts()

source
OpenTargets    109
Llama            2
Name: count, dtype: int64

In [21]:
df_disease

                                  disease_name     disease_id       source
0                 acute lymphoblastic leukemia    EFO_0000220  OpenTargets
1                       acute myeloid leukemia    EFO_0000222  OpenTargets
2     acute myeloid leukemia with mutated npm1  MONDO_0044923  OpenTargets
3    acute myeloid leukemia with npm1 mutation           None         None
4                     adrenocortical carcinoma    EFO_1000796  OpenTargets
..                                         ...            ...          ...
118                   type 2 diabetes mellitus  MONDO_0005148  OpenTargets
119                         ulcerative colitis    EFO_0000729  OpenTargets
120                       urothelial carcinoma    EFO_0008528  OpenTargets
121                                    uveitis    EFO_1001231  OpenTargets
122            well-differentiated liposarcoma    EFO_0000736  OpenTargets

[123 rows x 3 columns]

In [22]:
# df_disease[df_disease["source"]=="Llama"]

In [23]:
def compute_jaccard_from_run_dataframes(dct_result, df_gene, df_disease, df_drug):
    """
    Compute per-question cross-run Jaccard consistency after mapping entities to IDs.

    For each (model, question):
    - intersection: entries present in ALL valid runs
    - union: entries present in ANY valid run
    - jaccard = |intersection| / |union|

    All comparisons are CASE-INDEPENDENT and ID-based.

    Side effects:
    - Stores per-run mapped dataframe in:
        dct_result[model][question][run]['dataframe_id']

    Returns:
    - dct_jaccard[model][question] = {
          'jaccard': float,
          'n_valid_runs': int,
          'intersection': set[tuple],
          'union': set[tuple],
      }
    """

    dct_jaccard = {}

    # ------------------------------------------------------------------
    # Build deterministic one-to-one mapping tables
    # ------------------------------------------------------------------
    gene_map = (
        df_gene.assign(_gene_norm=df_gene["gene_name"].astype(str).str.strip().str.upper())
        [["_gene_norm", "gene_id"]]
        .dropna(subset=["gene_id"])
        .drop_duplicates("_gene_norm", keep="first")
    )

    disease_map = (
        df_disease.assign(_disease_norm=df_disease["disease_name"].astype(str).str.strip().str.upper())
        [["_disease_norm", "disease_id"]]
        .dropna(subset=["disease_id"])
        .drop_duplicates("_disease_norm", keep="first")
    )

    drug_map = (
        df_drug.assign(_drug_norm=df_drug["drug_name"].astype(str).str.strip().str.upper())
        [["_drug_norm", "drug_id"]]
        .dropna(subset=["drug_id"])
        .drop_duplicates("_drug_norm", keep="first")
    )

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    for model, model_payload in dct_result.items():
        dct_jaccard[model] = {}
        print(f"\nWorking for model: {model}")

        for question_key, runs_dict in model_payload.items():
            run_sets = {}

            for run_number, run_payload in runs_dict.items():
                df = run_payload.get("dataframe")

                # ---- basic validity ----
                if not isinstance(df, pd.DataFrame) or df.empty:
                    continue

                if "pathway_name" in df.columns:
                    continue

                work_df = df.copy()

                # print(work_df.head())

                final_cols = []

                # ---- gene ----
                if "gene_name" in work_df.columns:
                    work_df["_gene_norm"] = (
                        work_df["gene_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(gene_map, on="_gene_norm", how="left")
                    final_cols.append("gene_id")

                # ---- disease ----
                if "disease_name" in work_df.columns:
                    work_df["_disease_norm"] = (
                        work_df["disease_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(disease_map, on="_disease_norm", how="left")
                    final_cols.append("disease_id")

                # ---- drug ----
                if "drug_name" in work_df.columns:
                    work_df["_drug_norm"] = (
                        work_df["drug_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(drug_map, on="_drug_norm", how="left")
                    final_cols.append("drug_id")

                if not final_cols:
                    continue

                # ---- canonical ID dataframe ----
                id_df = (
                    work_df[final_cols]
                    .dropna(how="any")
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

                dct_result[model][question_key][run_number]["dataframe_id"] = id_df

                if id_df.empty:
                    continue

                # ---- CASE-INDEPENDENT tuple set ----
                run_set = {
                    tuple(str(v).strip().upper() for v in row)
                    for row in id_df.itertuples(index=False, name=None)
                }

                if run_set:
                    run_sets[run_number] = run_set

            # ------------------------------------------------------------------
            # Compute intersection / union
            # ------------------------------------------------------------------
            n_valid_runs = len(run_sets)

            if n_valid_runs < 2:
                print(
                    f"Not enough valid runs for '{question_key}' "
                    f"({n_valid_runs}/{len(runs_dict)}). Skipping."
                )
                continue

            sets = list(run_sets.values())
            intersection = set.intersection(*sets)
            union = set.union(*sets)

            if not union:
                print(f"Empty union for '{question_key}', skipping.")
                continue

            jaccard = len(intersection) / len(union)

            dct_jaccard[model][question_key] = {
                "jaccard": jaccard,
                "n_valid_runs": n_valid_runs,
                "intersection": intersection,
                "union": union,
            }

            print(
                f"'{question_key}': "
                f"J={jaccard:.4f}, "
                f"|∩|={len(intersection)}, "
                f"|∪|={len(union)}, "
                f"runs={n_valid_runs}"
            )

    return dct_jaccard


dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

Working for model: gpt-5-nano
'Which diseases are associated with BRAF?': J=0.5000, |∩|=5, |∪|=10, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=0.1667, |∩|=4, |∪|=24, runs=5
'Which diseases are associated with CDK4?': J=0.1667, |∩|=1, |∪|=6, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=0.8500, |∩|=17, |∪|=20, runs=5
'Which genes are associated with ovarian cancer?': J=0.3750, |∩|=6, |∪|=16, runs=5
'What are the known targets of regorafenib?': J=0.6667, |∩|=8, |∪|=12, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
'Which genes are associated with fever (pyrexia)?': J=0.0000, |∩|=0, |∪|=21, runs=5
'Which diseases are treated with bevacizumab?': J=0.6667, |∩|=6, |∪|=9, runs=5
'What are the known targets of cabozantinib?': J=1.0000, |∩|=5, |∪|=5, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=0.0000, |∩|=0, |∪|=2, runs=4
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=0.4167, |∩|=10, |∪|=24, runs=5
'Which genes are associated with epilepsy?': J=0.3143, |∩|=11, |∪|=35, runs=5
'Which diseases are treated with trastuzumab deruxtecan?': J=0.6667, |∩|=2, |∪|=3, runs=5
'Which genes are associated with Alzheimer’s disease?': J=0.5263, |∩|=10, |∪|=19, runs=5
Not enough valid runs for 'For which diseases is darolutamide used?' (0/5). Skipping.
'Which genes are associated with renal cell carcinoma?': J=0.4000, |∩|=4, |∪|=10, runs=5
'Which diseases are associated with the KRAS gene?': J=0.3000, |∩|=3, |∪|=10, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=0.0625, |∩|=1, |∪|=16, runs=5
'Which diseases are treated with valdecoxib?': J=0.5000, |∩|=1, |∪|=2, runs=5
'What are the known targets of vandetanib?': J=0.7500, |∩|=3, |∪|=4, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/3). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.2667, |∩|=4, |∪|=15, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=0.5556, |∩|=5, |∪|=9, runs=3
'Which drugs are used to treat chronic myeloid leukemia?': J=0.7143, |∩|=5, |∪|=7, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=0.6667, |∩|=12, |∪|=18, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=0.6316, |∩|=12, |∪|=19, runs=5
'Which targets are acted on by imatinib?': J=0.8000, |∩|=4, |∪|=5, runs=5
'Which biological targets does sorafenib interact with?': J=0.7778, |∩|=7, |∪|=9, runs=5
'Which biological targets does tofacitinib interact with?': J=0.6667, |∩|=2, |∪|=3, runs=5
'Which drugs target EGFR?': J=0.5000, |∩|=8, |∪|=16, runs=5
'Which diseases are associated with TP53?': J=0.3077, |∩|=4, |∪|=13, runs=5
'Which diseases are associated with FGFR2?': J=0.3000, |∩|=3, |∪|=10, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with breast cancer?': J=0.2857, |∩|=6, |∪|=21, runs=5
'Which genes are associated with colorectal cancer?': J=0.7333, |∩|=11, |∪|=15, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which drugs are used to treat TNBC?': J=0.5385, |∩|=7, |∪|=13, runs=5
'Which diseases are treated with metformin?': J=0.5000, |∩|=1, |∪|=2, runs=5
'Which diseases are treated with adalimumab?': J=0.8889, |∩|=8, |∪|=9, runs=5
'For which diseases is pembrolizumab used?': J=0.4667, |∩|=7, |∪|=15, runs=5
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which diseases are treated with nivolumab?': J=0.4000, |∩|=4, |∪|=10, runs=5
'Which genes are associated with multiple sclerosis?': J=0.0909, |∩|=1, |∪|=11, runs=5
'Which genes are associated with rheumatoid arthritis?': J=0.5000, |∩|=5, |∪|=10, runs=5
'What are the known targets of abatacept?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which genes are associated with lung cancer?': J=0.3333, |∩|=7, |∪|=21, runs=5
'What are the known targets of ponatinib?': J=0.5263, |∩|=10, |∪|=19, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.5833, |∩|=7, |∪|=12, runs=5
'Which genes are associated with autism spectrum disorder?': J=0.2800, |∩|=7, |∪|=25, runs=5
'Which diseases are associated with the ROS1 gene?': J=0.5000, |∩|=2, |∪|=4, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which diseases are associated with the EGFR gene?': J=0.4286, |∩|=3, |∪|=7, runs=5
'Which genes are associated with psoriasis?': J=0.2222, |∩|=4, |∪|=18, runs=5
'Which genes are associated with ulcerative colitis?': J=0.0833, |∩|=1, |∪|=12, runs=5
'Which genes are associated with hepatitis C?': J=0.2857, |∩|=2, |∪|=7, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=0.2500, |∩|=3, |∪|=12, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=0.7273, |∩|=8, |∪|=11, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/2). Skipping.
'Which drugs target CD19?': J=0.7500, |∩|=6, |∪|=8, runs=5
'Which drugs target CTLA4?': J=1.0000, |∩|=2, |∪|=2, runs=5
'What drugs are used to treat rickets?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which genes are associated with tuberculosis?': J=0.2105, |∩|=4, |∪|=19, runs=5

In [24]:
# Run Jaccard consistency computation across runs after ID grounding.
dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

# Flatten into a quick summary table for inspection.
rows = [
    {
        "model": model,
        "question": question,
        "jaccard": payload["jaccard"],
        "n_valid_runs": payload["n_valid_runs"],
        "intersection_size": len(payload["intersection"]),
        "union_size": len(payload["union"]),
    }
    for model, qmap in dct_jaccard.items()
    for question, payload in qmap.items()
]

jaccard_summary = pd.DataFrame(rows)
if jaccard_summary.empty:
    print("No valid Jaccard entries were produced. Check input runs and validation filters.")
else:
    display(jaccard_summary.sort_values(["model", "jaccard"], ascending=[True, False]).head(20))

Working for model: gpt-5-nano
'Which diseases are associated with BRAF?': J=0.5000, |∩|=5, |∪|=10, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=0.1667, |∩|=4, |∪|=24, runs=5
'Which diseases are associated with CDK4?': J=0.1667, |∩|=1, |∪|=6, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=0.8500, |∩|=17, |∪|=20, runs=5
'Which genes are associated with ovarian cancer?': J=0.3750, |∩|=6, |∪|=16, runs=5
'What are the known targets of regorafenib?': J=0.6667, |∩|=8, |∪|=12, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
'Which genes are associated with fever (pyrexia)?': J=0.0000, |∩|=0, |∪|=21, runs=5
'Which diseases are treated with bevacizumab?': J=0.6667, |∩|=6, |∪|=9, runs=5
'What are the known targets of cabozantinib?': J=1.0000, |∩|=5, |∪|=5, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=0.0000, |∩|=0, |∪|=2, runs=4
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=0.4167, |∩|=10, |∪|=24, runs=5
'Which genes are associated with epilepsy?': J=0.3143, |∩|=11, |∪|=35, runs=5
'Which diseases are treated with trastuzumab deruxtecan?': J=0.6667, |∩|=2, |∪|=3, runs=5
'Which genes are associated with Alzheimer’s disease?': J=0.5263, |∩|=10, |∪|=19, runs=5
Not enough valid runs for 'For which diseases is darolutamide used?' (0/5). Skipping.
'Which genes are associated with renal cell carcinoma?': J=0.4000, |∩|=4, |∪|=10, runs=5
'Which diseases are associated with the KRAS gene?': J=0.3000, |∩|=3, |∪|=10, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=0.0625, |∩|=1, |∪|=16, runs=5
'Which diseases are treated with valdecoxib?': J=0.5000, |∩|=1, |∪|=2, runs=5
'What are the known targets of vandetanib?': J=0.7500, |∩|=3, |∪|=4, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/3). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.2667, |∩|=4, |∪|=15, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=0.5556, |∩|=5, |∪|=9, runs=3
'Which drugs are used to treat chronic myeloid leukemia?': J=0.7143, |∩|=5, |∪|=7, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=0.6667, |∩|=12, |∪|=18, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=0.6316, |∩|=12, |∪|=19, runs=5
'Which targets are acted on by imatinib?': J=0.8000, |∩|=4, |∪|=5, runs=5
'Which biological targets does sorafenib interact with?': J=0.7778, |∩|=7, |∪|=9, runs=5
'Which biological targets does tofacitinib interact with?': J=0.6667, |∩|=2, |∪|=3, runs=5
'Which drugs target EGFR?': J=0.5000, |∩|=8, |∪|=16, runs=5
'Which diseases are associated with TP53?': J=0.3077, |∩|=4, |∪|=13, runs=5
'Which diseases are associated with FGFR2?': J=0.3000, |∩|=3, |∪|=10, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with breast cancer?': J=0.2857, |∩|=6, |∪|=21, runs=5
'Which genes are associated with colorectal cancer?': J=0.7333, |∩|=11, |∪|=15, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which drugs are used to treat TNBC?': J=0.5385, |∩|=7, |∪|=13, runs=5
'Which diseases are treated with metformin?': J=0.5000, |∩|=1, |∪|=2, runs=5
'Which diseases are treated with adalimumab?': J=0.8889, |∩|=8, |∪|=9, runs=5
'For which diseases is pembrolizumab used?': J=0.4667, |∩|=7, |∪|=15, runs=5
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which diseases are treated with nivolumab?': J=0.4000, |∩|=4, |∪|=10, runs=5
'Which genes are associated with multiple sclerosis?': J=0.0909, |∩|=1, |∪|=11, runs=5
'Which genes are associated with rheumatoid arthritis?': J=0.5000, |∩|=5, |∪|=10, runs=5
'What are the known targets of abatacept?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which genes are associated with lung cancer?': J=0.3333, |∩|=7, |∪|=21, runs=5
'What are the known targets of ponatinib?': J=0.5263, |∩|=10, |∪|=19, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.5833, |∩|=7, |∪|=12, runs=5
'Which genes are associated with autism spectrum disorder?': J=0.2800, |∩|=7, |∪|=25, runs=5
'Which diseases are associated with the ROS1 gene?': J=0.5000, |∩|=2, |∪|=4, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which diseases are associated with the EGFR gene?': J=0.4286, |∩|=3, |∪|=7, runs=5
'Which genes are associated with psoriasis?': J=0.2222, |∩|=4, |∪|=18, runs=5
'Which genes are associated with ulcerative colitis?': J=0.0833, |∩|=1, |∪|=12, runs=5
'Which genes are associated with hepatitis C?': J=0.2857, |∩|=2, |∪|=7, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=0.2500, |∩|=3, |∪|=12, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=0.7273, |∩|=8, |∪|=11, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/2). Skipping.
'Which drugs target CD19?': J=0.7500, |∩|=6, |∪|=8, runs=5
'Which drugs target CTLA4?': J=1.0000, |∩|=2, |∪|=2, runs=5
'What drugs are used to treat rickets?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which genes are associated with tuberculosis?': J=0.2105, |∩|=4, |∪|=19, runs=5

,model,question,jaccard,n_valid_runs,intersection_size,union_size
8,gpt-5-nano,What are the known targets of cabozantinib?,1.000000,5,5,5
30,gpt-5-nano,Which diseases are associated with HTT?,1.000000,5,1,1
33,gpt-5-nano,Which genes are associated with cystic fibrosis?,1.000000,5,1,1
38,gpt-5-nano,Which diseases are treated with sorafenib?,1.000000,5,3,3
42,gpt-5-nano,What are the known targets of abatacept?,1.000000,5,2,2
48,gpt-5-nano,Which diseases are associated with the ALK gene?,1.000000,5,4,4
56,gpt-5-nano,Which drugs target CTLA4?,1.000000,5,2,2
57,gpt-5-nano,What drugs are used to treat rickets?,1.000000,5,3,3
36,gpt-5-nano,Which diseases are treated with adalimumab?,0.888889,5,8,9
3,gpt-5-nano,Which drugs are used to treat rheumatoid arthr...,0.850000,5,17,20
24,gpt-5-nano,Which targets are acted on by imatinib?,0.800000,5,4,5
25,gpt-5-nano,Which biological targets does sorafenib intera...,0.777778,5,7,9
18,gpt-5-nano,What are the known targets of vandetanib?,0.750000,5,3,4
55,gpt-5-nano,Which drugs target CD19?,0.750000,5,6,8
32,gpt-5-nano,Which genes are associated with colorectal can...,0.733333,5,11,15
54,gpt-5-nano,Which drugs target ERBB2?,0.727273,5,8,11
21,gpt-5-nano,Which drugs are used to treat chronic myeloid ...,0.714286,5,5,7
5,gpt-5-nano,What are the known targets of regorafenib?,0.666667,5,8,12
7,gpt-5-nano,Which diseases are treated with bevacizumab?,0.666667,5,6,9
12,gpt-5-nano,Which diseases are treated with trastuzumab de...,0.666667,5,2,3

In [25]:
# Persist enriched run payloads with dataframe_id attached for each run.
with open("OpenAI_same_question_response_with_id.pkl", "wb") as f:
    pickle.dump(dct_result, f)