In [1]:
import sys
sys.path.append("../")

##### import library

In [2]:
from typing import List, Optional
import requests
import pandas as pd
import mygene
import utility
import importlib
importlib.reload(utility)
from utility import resolve_ensembl_ids_with_fallback, get_chembl_ids_fast,  get_disease_ids_fast, validate_id_dataframe
import pickle

In [3]:
dct_result = dict()

##### Read pickle

In [4]:
with open("Gemini_same_question_response_final.pkl", "rb") as f:
    Gemini_same_question_response = pickle.load(f)

In [5]:
for model in ['llama-3.3-70b-versatile', 'gpt-5-nano', 'grok-4-1-fast-non-reasoning-latest', "gemini-2.5-flash-lite", "OpenTarget", "BioChatter", "ctd", "ttd", "hcdt"]:

    
    # if model=="llama-3.3-70b-versatile":
    #     dct_result[model] = Llama_same_question_response[model]

    # if model=="gpt-5-nano":
    #     dct_result[model] = OpenAI_same_question_response[model]

    # if model=='grok-4-1-fast-non-reasoning-latest':
    #     dct_result[model] = Grok_same_question_response[model]

    if model=="gemini-2.5-flash-lite":
        dct_result[model] = Gemini_same_question_response[model]

    # if model=="OpenTarget":
    #     dct_result[model] = Opentarget_same_question_response[model]

    # if model=="BioChatter":
    #     dct_result[model] = Biochatter_same_question_response[model]
    # if model=="ctd":
    #     dct_result[model] = CTD_same_question_response[model]

    # if model=="hcdt":
    #     dct_result[model] = HCDT_same_question_response[model]

##### Verify if only valid columns are present

In [6]:
allowed = {"gene_name", "drug_name", "disease_name", "pathway_name"}

missing_df = []
not_dataframe = []
empty_df = []
bad_columns = []

total_payloads = 0

for model, queries in dct_result.items():
    if not isinstance(queries, dict):
        continue

    for question, runs in queries.items():
        if not isinstance(runs, dict):
            continue

        for run_id, payload in runs.items():
            total_payloads += 1

            if not isinstance(payload, dict) or "dataframe" not in payload:
                missing_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "payload_type": type(payload).__name__
                })
                continue

            df = payload.get("dataframe")

            if not isinstance(df, pd.DataFrame):
                not_dataframe.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "df_type": type(df).__name__
                })
                continue

            if df.empty:
                empty_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns)
                })

            cols = {str(c) for c in df.columns}
            extra = sorted(cols - allowed)

            if extra:
                bad_columns.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns),
                    "extra_columns": extra
                })

print(f"Total payloads checked: {total_payloads}")
print(f"Missing dataframe key: {len(missing_df)}")
print(f"Dataframe is not pd.DataFrame: {len(not_dataframe)}")
print(f"Empty dataframes: {len(empty_df)}")
print(f"Dataframes with disallowed columns: {len(bad_columns)}")

bad_columns_df = pd.DataFrame(bad_columns)
missing_df_df = pd.DataFrame(missing_df)
not_dataframe_df = pd.DataFrame(not_dataframe)
empty_df_df = pd.DataFrame(empty_df)

display(bad_columns_df)
display(missing_df_df)
display(not_dataframe_df)
display(empty_df_df)

Total payloads checked: 350
Missing dataframe key: 0
Dataframe is not pd.DataFrame: 0
Empty dataframes: 0
Dataframes with disallowed columns: 0

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [7]:
dct_jaccard = dict()

question_entities = {
    "gene_name": set(),
    "drug_name": set(),
    "disease_name": set(),
}

allowed_cols = {"gene_name", "drug_name", "disease_name"}

for model, queries in dct_result.items():
    dct_jaccard[model] = {}
    print(f"\nWorking for model: {model}")

    for question, runs in queries.items():

        for run_id, payload in runs.items():
            df = payload.get("dataframe")

            # ---- validation ----
            if not isinstance(df, pd.DataFrame) or df.empty:
                continue

            # ---- skip pathway outputs ----
            if "pathway_name" in df.columns:
                continue

            # ---- column sanity ----
            if not set(df.columns).issubset(allowed_cols):
                continue

            # ---- collect entities globally ----
            for col in allowed_cols:
                if col in df.columns:
                    values = (
                        df[col]
                        .dropna()
                        .astype(str)
                        .str.strip()
                        .tolist()
                    )
                    question_entities[col].update(values)

# ---- finalize (sets → sorted lists) ----
for k in question_entities:
    question_entities[k] = sorted(question_entities[k])

Working for model: gemini-2.5-flash-lite

##### Associate id with all gene entry

In [8]:
# Resolve unique gene symbols to IDs (MyGene -> OpenTargets fallback).
df_gene = resolve_ensembl_ids_with_fallback(
    list(question_entities["gene_name"]),
    use_opentargets_fallback=True,
)
df_gene = df_gene.drop_duplicates(subset=["gene_name", "gene_id"]).reset_index(drop=True)
df_gene

2026-02-27 17:51:50,086 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 17:51:50,087 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 17:51:50,088 [INFO] querying 1-940 ...
2026-02-27 17:51:52,460 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 17:51:53,466 [INFO] Finished.
2026-02-27 17:51:53,475 [WARNING] 2 input query terms found dup hits:	[('IGHG1', 2), ('MTOR', 2)]
2026-02-27 17:51:53,475 [WARNING] 182 input query terms found no hit:	['*/;', '...', '</H3>', 'ALK FUSION', 'ARGHECN1', 'ARGHEIS', 'ARPP', 'ARPP-21', 'AS', 'BCR-ABL1', 'B
2026-02-27 17:51:53,489 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 17:51:53,489 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 17:51:53,490 [INFO] querying 1-53 ...
2026-02-27 17:51:53,861 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 17:51:54,863 [INFO] Finished.
2026-02-27 17:51:54,866 [WARNING] 3 input query terms found dup hits:	[('</H3>', 10), ('SWI/SNF COMPLEX', 10), ('WNT PATHWAY', 10)]
2026-02-27 17:51:54,867 [WARNING] 50 input query terms found no hit:	['*/;', '...', 'ALK FUSION', 'BRAF V600E', 'CDKN2A DELETION', 'CÁC NHÀ KHOA HỌC ĐANG NGHIÊN CỨU CÁC

[warn] Could not resolve '*/;' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve '...' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ALK fusion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ARGHECN1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ARGHEIS' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'BCR-ABL1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'BRAF V600E' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'C1QTNFIP3' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'CD3' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'CDKN2A deletion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Core' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'Các nhà khoa học đang nghiên cứu các gen khác có liên quan đến bệnh ung thư biểu mô tế bào thận': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'Các nhà khoa học đang nghiên cứu các gen khác có liên quan đến bệnh ung thư biểu mô tế bào thận' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'DDT': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'DDT' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'DEFA1': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'DEFA1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'DEFA4': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'DEFA4' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'E2': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'E2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'EBNA1': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'EBNA1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'EGFR L858R' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'EGFR exon 19 deletion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Epigenetic regulation' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'FCAM2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'FGFR' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'GWAS' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'HER2 amplification' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'HLA-DR' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'INNK' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'JAK/STAT pathway' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS G12C' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS G12D' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS G12V' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS G13C' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS G13D' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS G13V' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS Q61H' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS Q61K' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS Q61L' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS Q61P' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS Q61R' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'KRAS Q61X' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'LGG11' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MAPK pathway' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MET exon 14 skipping' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MHC class II' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MS4A' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MYC amplification' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NF-kB pathway' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NFE2L2 mutation' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NOTCH1 mutation' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NS3/4A' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NS4A' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NS4B' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NS5A' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NS5B' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ORMDL5' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PAGRBP1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PCDHA' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PCDHB' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PCDHG' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PI3K/AKT/mTOR pathway' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PIK3CA mutation' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS10' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS11' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS16' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS17' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS18' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS19' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS20' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS21' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS22' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS23' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS24' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS25' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS26' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS27' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS28' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS29' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS3' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS30' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS31' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS32' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS33' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS34' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS35' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS36' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS37' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS38' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS39' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS4' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS40' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS41' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS42' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS43' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS44' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS45' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS46' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS47' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS48' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS49' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS5' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS50' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS6' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS8' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PSORS9' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'PTEN mutation' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'RAS pathway' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'RB1 deletion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'RET fusion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ROS1 fusion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'RP11-303O10.2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SEPW1L' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SOX2 amplification' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SPHN' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'SPN4' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'STK11 deletion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'TALLYHO1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'TP53 R175H' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'TP53 R248W' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'TP53 R273H' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'VEGF pathway' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'VHL deletion' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'VPS22D1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Vascular endothelial growth factor receptor' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'WDR60': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'WDR60' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'XKR6': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'XKR6' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'ZCCHC1': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'ZCCHC1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'ZDHHC10': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'ZDHHC10' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[OpenTargets] GraphQL errors for 'ZNF436': [{'message': 'Internal server error', 'path': ['search'], 'locations': [{'line': 3, 'column': 3}]}]
[warn] Could not resolve 'ZNF436' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve '_G6PC' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve '```' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'gấp' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.

    gene_name          gene_id       source
0         */;              NaN         None
1         ...              NaN         None
2       </h3>  ENSG00000101180       mygene
3       ABCA7  ENSG00000064687       mygene
4       ABCG2  ENSG00000118777       mygene
..        ...              ...          ...
935       ```              NaN         None
936       gấp              NaN         None
937      mTOR  ENSG00000198793       mygene
938       p38  ENSG00000100030  opentargets
939        p7  ENSG00000120519  opentargets

[940 rows x 3 columns]

In [9]:
df_gene[df_gene.isna().any(axis=1)]

      gene_name gene_id source
0           */;     NaN   None
1           ...     NaN   None
16   ALK fusion     NaN   None
41     ARGHECN1     NaN   None
42      ARGHEIS     NaN   None
..          ...     ...    ...
917     ZDHHC10     NaN   None
926      ZNF436     NaN   None
934       _G6PC     NaN   None
935         ```     NaN   None
936         gấp     NaN   None

[130 rows x 3 columns]

##### Associate id with all drug entry

In [10]:
# Resolve unique drug surface forms to IDs.
# This keeps original raw names as rows and writes mapped ID + source.
df_drug = await get_chembl_ids_fast(list(question_entities["drug_name"]))
df_drug = df_drug.drop_duplicates(subset=["drug_name", "drug_id"]).reset_index(drop=True)
df_drug

2026-02-27 17:54:09,738 [INFO] [LLM] Total 80 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 17:54:09,739 [INFO] [LLM] Batch size: 80

[map][drug][OpenTargets] raw='5-fluorouracil' -> id='CHEMBL185'
[map][drug][OpenTargets] raw='Abraxane' -> id='CHEMBL428647'
[map][drug][OpenTargets] raw='Ado-trastuzumab emtansine' -> id='CHEMBL1743082'
[map][drug][OpenTargets] raw='Afatinib' -> id='CHEMBL1173655'
[map][drug][OpenTargets] raw='Aimovig' -> id='CHEMBL3833329'
[map][drug][OpenTargets] raw='Ajovy' -> id='CHEMBL4297756'
[map][drug][OpenTargets] raw='Alfacalcidol' -> id='CHEMBL1601669'
[map][drug][OpenTargets] raw='Almotriptan' -> id='CHEMBL1505'
[map][drug][OpenTargets] raw='Amantadine' -> id='CHEMBL660'
[map][drug][OpenTargets] raw='Amivantamab' -> id='CHEMBL4297774'
[map][drug][OpenTargets] raw='Apomorphine' -> id='CHEMBL53'
[map][drug][OpenTargets] raw='Asciminib' -> id='CHEMBL4208229'
[map][drug][OpenTargets] raw='Atezolizumab' -> id='CHEMBL3707227'
[map][drug][OpenTargets] raw='Axicabtagene ciloleucel' -> id='CHEMBL3989989'
[map][drug][OpenTargets] raw='Axitinib' -> id='CHEMBL1289926'
[map][drug][OpenTargets] raw='Azathioprine' -> id='CHEMBL1542'
[map][drug][OpenTargets] raw='Belimumab' -> id='CHEMBL1789843'
[map][drug][OpenTargets] raw='Bevacizumab' -> id='CHEMBL1201583'
[map][drug][OpenTargets] raw='Brexucabtagene autoleucel' -> id='CHEMBL4594618'
[map][drug][OpenTargets] raw='Brigatinib' -> id='CHEMBL3545311'
[map][drug][OpenTargets] raw='Bromocriptine' -> id='CHEMBL493'
[map][drug][OpenTargets] raw='Calcitriol' -> id='CHEMBL846'
[map][drug][OpenTargets] raw='Carbidopa' -> id='CHEMBL1200748'
[map][drug][OpenTargets] raw='Carboplatin' -> id='CHEMBL1351'
[map][drug][OpenTargets] raw='Cetuximab' -> id='CHEMBL1201577'
[map][drug][OpenTargets] raw='Cholecalciferol' -> id='CHEMBL1042'
[map][drug][OpenTargets] raw='Cisplatin' -> id='CHEMBL11359'
[map][drug][OpenTargets] raw='Cyclophosphamide' -> id='CHEMBL1200796'
[map][drug][OpenTargets] raw='Dacomitinib' -> id='CHEMBL2105719'
[map][drug][OpenTargets] raw='Docetaxel' -> id='CHEMBL3545252'
[map][drug][OpenTargets] raw='Doxorubicin' -> id='CHEMBL53463'
[map][drug][OpenTargets] raw='Eletriptan' -> id='CHEMBL1510'
[map][drug][OpenTargets] raw='Emgality' -> id='CHEMBL3707328'
[map][drug][OpenTargets] raw='Entacapone' -> id='CHEMBL953'
[map][drug][OpenTargets] raw='Epirubicin' -> id='CHEMBL417'
[map][drug][OpenTargets] raw='Erenumab' -> id='CHEMBL3833329'
[map][drug][OpenTargets] raw='Ergocalciferol' -> id='CHEMBL1536'
[map][drug][OpenTargets] raw='Erlotinib' -> id='CHEMBL553'
[map][drug][OpenTargets] raw='Etoposide' -> id='CHEMBL44657'
[map][drug][OpenTargets] raw='Fremanezumab' -> id='CHEMBL4297756'
[map][drug][OpenTargets] raw='Frova' -> id='CHEMBL2138684'
[map][drug][OpenTargets] raw='Frovatriptan' -> id='CHEMBL1279'
[map][drug][OpenTargets] raw='Galcanezumab' -> id='CHEMBL3707328'
[map][drug][OpenTargets] raw='Gefitinib' -> id='CHEMBL939'
[map][drug][OpenTargets] raw='Gemcitabine' -> id='CHEMBL888'
[map][drug][OpenTargets] raw='Hydroxychloroquine' -> id='CHEMBL1535'
[map][drug][OpenTargets] raw='Inotuzumab ozogamicin' -> id='CHEMBL2108611'
[map][drug][OpenTargets] raw='Ipilimumab' -> id='CHEMBL1789844'
[map][drug][OpenTargets] raw='Lapatinib' -> id='CHEMBL554'
[map][drug][OpenTargets] raw='Lasmiditan' -> id='CHEMBL3039520'
[map][drug][OpenTargets] raw='Lazertinib' -> id='CHEMBL4558324'
[map][drug][OpenTargets] raw='Levodopa' -> id='CHEMBL1009'
[map][drug][OpenTargets] raw='Lisocabtagene maraleucel' -> id='CHEMBL4297236'
[map][drug][OpenTargets] raw='Maxalt' -> id='CHEMBL1201032'
[map][drug][OpenTargets] raw='Mycophenolate mofetil' -> id='CHEMBL1456'
[map][drug][OpenTargets] raw='Naratriptan' -> id='CHEMBL1278'
[map][drug][OpenTargets] raw='Necitumumab' -> id='CHEMBL1743047'
[map][drug][OpenTargets] raw='Neratinib' -> id='CHEMBL180022'
[map][drug][OpenTargets] raw='Niraparib' -> id='CHEMBL1094636'
[map][drug][OpenTargets] raw='Nurtec ODT' -> id='CHEMBL2364629'
[map][drug][OpenTargets] raw='Obinutuzumab' -> id='CHEMBL1743048'
[map][drug][OpenTargets] raw='Olaparib' -> id='CHEMBL521686'
[map][drug][OpenTargets] raw='OnabotulinumtoxinA' -> id='CHEMBL1201574'
[map][drug][OpenTargets] raw='Onzetra Xsail' -> id='CHEMBL1201150'
[map][drug][OpenTargets] raw='Oportuzumab monatox' -> id='CHEMBL1743052'
[map][drug][OpenTargets] raw='Osimertinib' -> id='CHEMBL3353410'
[map][drug][OpenTargets] raw='Paclitaxel' -> id='CHEMBL428647'
[map][drug][OpenTargets] raw='Panitumumab' -> id='CHEMBL1201827'
[map][drug][OpenTargets] raw='Pembrolizumab' -> id='CHEMBL3137343'
[map][drug][OpenTargets] raw='Pertuzumab' -> id='CHEMBL2007641'
[map][drug][OpenTargets] raw='Phytomenadione' -> id='CHEMBL1550'
[map][drug][OpenTargets] raw='Pramipexole' -> id='CHEMBL301265'
[map][drug][OpenTargets] raw='Prednisone' -> id='CHEMBL635'
[map][drug][OpenTargets] raw='Rasagiline' -> id='CHEMBL887'
[map][drug][OpenTargets] raw='Relpax' -> id='CHEMBL1201003'
[map][drug][OpenTargets] raw='Rimegepant' -> id='CHEMBL2178422'
[map][drug][OpenTargets] raw='Rituximab' -> id='CHEMBL1201576'
[map][drug][OpenTargets] raw='Rizatriptan' -> id='CHEMBL905'
[map][drug][OpenTargets] raw='Ropinirole' -> id='CHEMBL589'
[map][drug][OpenTargets] raw='Rotigotine' -> id='CHEMBL1303'
[map][drug][OpenTargets] raw='Sacituzumab govitecan' -> id='CHEMBL3545262'
[map][drug][OpenTargets] raw='Safinamide' -> id='CHEMBL396778'
[map][drug][OpenTargets] raw='Selegiline' -> id='CHEMBL972'
[map][drug][OpenTargets] raw='Seltorexant' -> id='CHEMBL3597971'
[map][drug][OpenTargets] raw='Sumatriptan' -> id='CHEMBL128'
[map][drug][OpenTargets] raw='Talazoparib' -> id='CHEMBL3137320'
[map][drug][OpenTargets] raw='Tisagenlecleucel' -> id='CHEMBL3301574'
[map][drug][OpenTargets] raw='Tislelizumab' -> id='CHEMBL4297840'
[map][drug][OpenTargets] raw='Tisotumab vedotin' -> id='CHEMBL4297841'
[map][drug][OpenTargets] raw='Tolcapone' -> id='CHEMBL1324'
[map][drug][OpenTargets] raw='Trastuzumab' -> id='CHEMBL1201585'
[map][drug][OpenTargets] raw='Trastuzumab deruxtecan' -> id='CHEMBL4297844'
[map][drug][OpenTargets] raw='Tremelimumab' -> id='CHEMBL2108658'
[map][drug][OpenTargets] raw='Treximet' -> id='CHEMBL1201150'
[map][drug][OpenTargets] raw='Tucatinib' -> id='CHEMBL3989868'
[map][drug][OpenTargets] raw='Ubrelvy' -> id='CHEMBL2364638'
[map][drug][OpenTargets] raw='Ubrogepant' -> id='CHEMBL2364638'
[map][drug][OpenTargets] raw='Umbralisib' -> id='CHEMBL3948730'
[map][drug][OpenTargets] raw='Vinorelbine' -> id='CHEMBL553025'
[map][drug][OpenTargets] raw='Vitamin D' -> id='CHEMBL1536'
[map][drug][OpenTargets] raw='Zanubrutinib' -> id='CHEMBL3936761'
[map][drug][OpenTargets] raw='Zolmitriptan' -> id='CHEMBL1185'
[map][drug][OpenTargets] raw='Zomig' -> id='CHEMBL1185'
[map][drug][OpenTargets] raw='abatacept' -> id='CHEMBL1201823'
[map][drug][OpenTargets] raw='acetaminophen' -> id='CHEMBL112'
[map][drug][OpenTargets] raw='adalimumab' -> id='CHEMBL1201580'
[map][drug][OpenTargets] raw='adalimumab-adbm' -> id='CHEMBL1201580'
[map][drug][OpenTargets] raw='adalimumab-atto' -> id='CHEMBL1201580'
[map][drug][OpenTargets] raw='afatinib' -> id='CHEMBL1173655'
[map][drug][OpenTargets] raw='alitretinoin' -> id='CHEMBL705'
[map][drug][OpenTargets] raw='almotriptan' -> id='CHEMBL1505'
[map][drug][OpenTargets] raw='alpelisib' -> id='CHEMBL2396661'
[map][drug][OpenTargets] raw='amikacin' -> id='CHEMBL177'
[map][drug][OpenTargets] raw='amitriptyline' -> id='CHEMBL629'
[map][drug][OpenTargets] raw='anakinra' -> id='CHEMBL1201570'
[map][drug][OpenTargets] raw='asciminib' -> id='CHEMBL4208229'
[map][drug][OpenTargets] raw='aspirin' -> id='CHEMBL25'
[map][drug][OpenTargets] raw='atenolol' -> id='CHEMBL24'
[map][drug][OpenTargets] raw='atezolizumab' -> id='CHEMBL3707227'
[map][drug][OpenTargets] raw='atogepant' -> id='CHEMBL3991065'
[map][drug][OpenTargets] raw='axicabtagene ciloleucel' -> id='CHEMBL3989989'
[map][drug][OpenTargets] raw='azathioprine' -> id='CHEMBL1542'
[map][drug][OpenTargets] raw='balsalazide' -> id='CHEMBL1201346'
[map][drug][OpenTargets] raw='baricitinib' -> id='CHEMBL2105759'
[map][drug][OpenTargets] raw='bedaquiline' -> id='CHEMBL376488'
[map][drug][OpenTargets] raw='belimumab' -> id='CHEMBL1789843'
[map][drug][OpenTargets] raw='bevacizumab' -> id='CHEMBL1201583'
[map][drug][OpenTargets] raw='bosutinib' -> id='CHEMBL288441'
[map][drug][OpenTargets] raw='brexucabtagene autoleucel' -> id='CHEMBL4594618'
[map][drug][OpenTargets] raw='budesonide' -> id='CHEMBL1370'
[map][drug][OpenTargets] raw='butalbital' -> id='CHEMBL454'
[map][drug][OpenTargets] raw='cabozantinib' -> id='CHEMBL2105717'
[map][drug][OpenTargets] raw='calcitriol' -> id='CHEMBL846'
[map][drug][OpenTargets] raw='capecitabine' -> id='CHEMBL1773'
[map][drug][OpenTargets] raw='capreomycin' -> id='CHEMBL2221250'
[map][drug][OpenTargets] raw='carboplatin' -> id='CHEMBL1351'
[map][drug][OpenTargets] raw='certolizumab pegol' -> id='CHEMBL1201831'
[map][drug][OpenTargets] raw='cholecalciferol' -> id='CHEMBL1042'
[map][drug][OpenTargets] raw='ciprofloxacin' -> id='CHEMBL8'
[map][drug][OpenTargets] raw='cisplatin' -> id='CHEMBL11359'
[map][drug][OpenTargets] raw='clofazimine' -> id='CHEMBL1292'
[map][drug][OpenTargets] raw='clonazepam' -> id='CHEMBL452'
[map][drug][OpenTargets] raw='cyclophosphamide' -> id='CHEMBL1200796'
[map][drug][OpenTargets] raw='cycloserine' -> id='CHEMBL771'
[map][drug][OpenTargets] raw='cyclosporine' -> id='CHEMBL160'
[map][drug][OpenTargets] raw='dacomitinib' -> id='CHEMBL2105719'
[map][drug][OpenTargets] raw='darolutamide' -> id='CHEMBL4297185'
[map][drug][OpenTargets] raw='dasatinib' -> id='CHEMBL5416410'
[map][drug][OpenTargets] raw='delamanid' -> id='CHEMBL218650'
[map][drug][OpenTargets] raw='dexamethasone' -> id='CHEMBL384467'
[map][drug][OpenTargets] raw='diclofenac' -> id='CHEMBL139'
[map][drug][OpenTargets] raw='diltiazem' -> id='CHEMBL23'
[map][drug][OpenTargets] raw='divalproex sodium' -> id='CHEMBL2105613'
[map][drug][OpenTargets] raw='docetaxel' -> id='CHEMBL3545252'
[map][drug][OpenTargets] raw='doxorubicin' -> id='CHEMBL53463'
[map][drug][OpenTargets] raw='durvalumab' -> id='CHEMBL3301587'
[map][drug][OpenTargets] raw='eletriptan' -> id='CHEMBL1510'
[map][drug][OpenTargets] raw='epirubicin' -> id='CHEMBL417'
[map][drug][OpenTargets] raw='eptinezumab' -> id='CHEMBL3833320'
[map][drug][OpenTargets] raw='erenumab' -> id='CHEMBL3833329'
[map][drug][OpenTargets] raw='ergocalciferol' -> id='CHEMBL1536'
[map][drug][OpenTargets] raw='eribulin' -> id='CHEMBL1683590'
[map][drug][OpenTargets] raw='erlotinib' -> id='CHEMBL553'
[map][drug][OpenTargets] raw='etanercept' -> id='CHEMBL1201572'
[map][drug][OpenTargets] raw='etanercept-szzs' -> id='CHEMBL1201572'
[map][drug][OpenTargets] raw='ethambutol' -> id='CHEMBL44884'
[map][drug][OpenTargets] raw='ethionamide' -> id='CHEMBL1441'
[map][drug][OpenTargets] raw='everolimus' -> id='CHEMBL1908360'
[map][drug][OpenTargets] raw='filgotinib' -> id='CHEMBL3301607'
[map][drug][OpenTargets] raw='fluorouracil' -> id='CHEMBL185'
[map][drug][OpenTargets] raw='fremanezumab' -> id='CHEMBL4297756'
[map][drug][OpenTargets] raw='frovatriptan' -> id='CHEMBL1279'
[map][drug][OpenTargets] raw='gabapentin' -> id='CHEMBL940'
[map][drug][OpenTargets] raw='galcanezumab' -> id='CHEMBL3707328'
[map][drug][OpenTargets] raw='gefitinib' -> id='CHEMBL939'
[map][drug][OpenTargets] raw='gemcitabine' -> id='CHEMBL888'
[map][drug][OpenTargets] raw='golimumab' -> id='CHEMBL1201833'
[map][drug][OpenTargets] raw='hydroxychloroquine' -> id='CHEMBL1535'
[map][drug][OpenTargets] raw='ibuprofen' -> id='CHEMBL521'
[map][drug][OpenTargets] raw='ifosfamide' -> id='CHEMBL1024'
[map][drug][OpenTargets] raw='imatinib' -> id='CHEMBL941'
[map][drug][OpenTargets] raw='imipenem' -> id='CHEMBL43708'
[map][drug][OpenTargets] raw='infliximab' -> id='CHEMBL1201581'
[map][drug][OpenTargets] raw='infliximab-abda' -> id='CHEMBL1201581'
[map][drug][OpenTargets] raw='infliximab-dyyb' -> id='CHEMBL1201581'
[map][drug][OpenTargets] raw='ipilimumab' -> id='CHEMBL1789844'
[map][drug][OpenTargets] raw='irinotecan' -> id='CHEMBL481'
[map][drug][OpenTargets] raw='isoniazid' -> id='CHEMBL64'
[map][drug][OpenTargets] raw='kanamycin' -> id='CHEMBL1384'
[map][drug][OpenTargets] raw='lapatinib' -> id='CHEMBL554'
[map][drug][OpenTargets] raw='lasmiditan' -> id='CHEMBL3039520'
[map][drug][OpenTargets] raw='leflunomide' -> id='CHEMBL960'
[map][drug][OpenTargets] raw='levofloxacin' -> id='CHEMBL5315124'
[map][drug][OpenTargets] raw='linezolid' -> id='CHEMBL126'
[map][drug][OpenTargets] raw='lisocabtagene maraleucel' -> id='CHEMBL4297236'
[map][drug][OpenTargets] raw='mercaptopurine' -> id='CHEMBL1200751'
[map][drug][OpenTargets] raw='meropenem' -> id='CHEMBL127'
[map][drug][OpenTargets] raw='mesalamine' -> id='CHEMBL704'
[map][drug][OpenTargets] raw='mesalazine' -> id='CHEMBL704'
[map][drug][OpenTargets] raw='metformin' -> id='CHEMBL1431'
[map][drug][OpenTargets] raw='methotrexate' -> id='CHEMBL34259'
[map][drug][OpenTargets] raw='metoprolol' -> id='CHEMBL13'
[map][drug][OpenTargets] raw='minocycline' -> id='CHEMBL1434'
[map][drug][OpenTargets] raw='mirvetuximab soravtansine' -> id='CHEMBL3545132'
[map][drug][OpenTargets] raw='moxifloxacin' -> id='CHEMBL32'
[map][drug][OpenTargets] raw='naproxen' -> id='CHEMBL154'
[map][drug][OpenTargets] raw='naratriptan' -> id='CHEMBL1278'
[map][drug][OpenTargets] raw='natalizumab' -> id='CHEMBL1201607'
[map][drug][OpenTargets] raw='necitumumab' -> id='CHEMBL1743047'
[map][drug][OpenTargets] raw='neratinib' -> id='CHEMBL180022'
[map][drug][OpenTargets] raw='nilotinib' -> id='CHEMBL255863'
[map][drug][OpenTargets] raw='niraparib' -> id='CHEMBL1094636'
[map][drug][OpenTargets] raw='nivolumab' -> id='CHEMBL2108738'
[map][drug][OpenTargets] raw='nortriptyline' -> id='CHEMBL445'
[map][drug][OpenTargets] raw='ofloxacin' -> id='CHEMBL4'
[map][drug][OpenTargets] raw='olaparib' -> id='CHEMBL521686'
[map][drug][OpenTargets] raw='onabotulinumtoxinA' -> id='CHEMBL1201574'
[map][drug][OpenTargets] raw='osimertinib' -> id='CHEMBL3353410'
[map][drug][OpenTargets] raw='oxaliplatin' -> id='CHEMBL414804'
[map][drug][OpenTargets] raw='paclitaxel' -> id='CHEMBL428647'
[map][drug][OpenTargets] raw='pembrolizumab' -> id='CHEMBL3137343'
[map][drug][OpenTargets] raw='pertuzumab' -> id='CHEMBL2007641'
[map][drug][OpenTargets] raw='ponatinib' -> id='CHEMBL1171837'
[map][drug][OpenTargets] raw='prednisolone' -> id='CHEMBL131'
[map][drug][OpenTargets] raw='prednisone' -> id='CHEMBL635'
[map][drug][OpenTargets] raw='pregabalin' -> id='CHEMBL1059'
[map][drug][OpenTargets] raw='pretomanid' -> id='CHEMBL227875'
[map][drug][OpenTargets] raw='propranolol' -> id='CHEMBL27'
[map][drug][OpenTargets] raw='pyrazinamide' -> id='CHEMBL614'
[map][drug][OpenTargets] raw='regorafenib' -> id='CHEMBL1946170'
[map][drug][OpenTargets] raw='rifampicin' -> id='CHEMBL374478'
[map][drug][OpenTargets] raw='rifaximin' -> id='CHEMBL1617'
[map][drug][OpenTargets] raw='rimegepant' -> id='CHEMBL2178422'
[map][drug][OpenTargets] raw='rituximab' -> id='CHEMBL1201576'
[map][drug][OpenTargets] raw='rituximab-abbs' -> id='CHEMBL1201576'
[map][drug][OpenTargets] raw='rituximab-pvvr' -> id='CHEMBL1201576'
[map][drug][OpenTargets] raw='rizatriptan' -> id='CHEMBL905'
[map][drug][OpenTargets] raw='rucaparib' -> id='CHEMBL1173055'
[map][drug][OpenTargets] raw='sacituzumab govitecan' -> id='CHEMBL3545262'
[map][drug][OpenTargets] raw='sapanisertib' -> id='CHEMBL3545097'
[map][drug][OpenTargets] raw='sarilumab' -> id='CHEMBL2108730'
[map][drug][OpenTargets] raw='sorafenib' -> id='CHEMBL1336'
[map][drug][OpenTargets] raw='streptomycin' -> id='CHEMBL372795'
[map][drug][OpenTargets] raw='sulfasalazine' -> id='CHEMBL421'
[map][drug][OpenTargets] raw='sumatriptan' -> id='CHEMBL128'
[map][drug][OpenTargets] raw='tacrolimus' -> id='CHEMBL3989887'
[map][drug][OpenTargets] raw='talazoparib' -> id='CHEMBL3137320'
[map][drug][OpenTargets] raw='timolol' -> id='CHEMBL499'
[map][drug][OpenTargets] raw='tipiracil' -> id='CHEMBL235668'
[map][drug][OpenTargets] raw='tisagenlecleucel' -> id='CHEMBL3301574'
[map][drug][OpenTargets] raw='tocilizumab' -> id='CHEMBL1237022'
[map][drug][OpenTargets] raw='tofacitinib' -> id='CHEMBL221959'
[map][drug][OpenTargets] raw='topiramate' -> id='CHEMBL220492'
[map][drug][OpenTargets] raw='trastuzumab' -> id='CHEMBL1201585'
[map][drug][OpenTargets] raw='trastuzumab deruxtecan' -> id='CHEMBL4297844'
[map][drug][OpenTargets] raw='trifluridine' -> id='CHEMBL1129'
[map][drug][OpenTargets] raw='tucatinib' -> id='CHEMBL3989868'
[map][drug][OpenTargets] raw='ubrogepant' -> id='CHEMBL2364638'
[map][drug][OpenTargets] raw='upadacitinib' -> id='CHEMBL3622821'
[map][drug][OpenTargets] raw='ustekinumab' -> id='CHEMBL1201835'
[map][drug][OpenTargets] raw='valdecoxib' -> id='CHEMBL865'
[map][drug][OpenTargets] raw='valproic acid' -> id='CHEMBL109'
[map][drug][OpenTargets] raw='vandetanib' -> id='CHEMBL24828'
[map][drug][OpenTargets] raw='vedolizumab' -> id='CHEMBL1743087'
[map][drug][OpenTargets] raw='venlafaxine' -> id='CHEMBL637'
[map][drug][OpenTargets] raw='verapamil' -> id='CHEMBL6966'
[map][drug][OpenTargets] raw='vinorelbine' -> id='CHEMBL553025'
[map][drug][OpenTargets] raw='zolmitriptan' -> id='CHEMBL1185'

2026-02-27 17:54:11,690 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:54:11,700 [INFO] [LLM] Batch done in 1.96s
2026-02-27 17:54:11,701 [INFO] [OT] Verifying 19 unique drug suggestions...
2026-02-27 17:54:12,146 [INFO] [OT] 'tocilizumab' → 'TOCILIZUMAB' (CHEMBL1237022)
2026-02-27 17:54:12,147 [INFO] [OT] 'upadacitinib' → 'UPADACITINIB' (CHEMBL3622821)
2026-02-27 17:54:12,148 [INFO] [OT] 'irinotecan' → 'IRINOTECAN' (CHEMBL481)
2026-02-27 17:54:12,148 [INFO] [OT] 'leflunomide' → 'LEFLUNOMIDE' (CHEMBL960)
2026-02-27 17:54:12,149 [INFO] [OT] 'paclitaxel' → 'PACLITAXEL' (CHEMBL428647)
2026-02-27 17:54:12,149 [INFO] [OT] 'sulfasalazine' → 'SULFASALAZINE' (CHEMBL421)
2026-02-27 17:54:12,150 [INFO] [OT] 'prednisone' → 'PREDNISONE' (CHEMBL635)
2026-02-27 17:54:12,150 [INFO] [OT] 'rituximab' → 'RITUXIMAB' (CHEMBL1201576)
2026-02-27 17:54:12,150 [INFO] [OT] 'tofacitinib' → 'TOFACITINIB' (CHEMBL221959)
2026-02-27 17:54:12,151 [INFO] [OT] 'dapsone' → 'DAPSONE' (CHEMBL1043)
2026-02-27 17:54:12,151 [INFO] [OT] 'methotrexate' → 'METHOTREXATE' (CHEMBL34259)
2026-02-27 17:54:12,151 [INFO] [OT] 'infliximab' → 'INFLIXIMAB' (CHEMBL1201581)
2026-02-27 17:54:12,152 [INFO] [OT] 'cyclosporine' → 'CYCLOSPORINE' (CHEMBL160)
2026-02-27 17:54:12,152 [INFO] [OT] 'azathioprine' → 'AZATHIOPRINE' (CHEMBL1542)
2026-02-27 17:54:12,153 [INFO] [OT] 'baricitinib' → 'BARICITINIB' (CHEMBL2105759)
2026-02-27 17:54:12,153 [INFO] [OT] 'adalimumab' → 'ADALIMUMAB' (CHEMBL1201580)
2026-02-27 17:54:12,154 [INFO] [OT] 'minocycline' → 'MINOCYCLINE' (CHEMBL1434)
2026-02-27 17:54:12,155 [INFO] [OT] 'hydroxychloroquine' → 'HYDROXYCHLOROQUINE' (CHEMBL1535)
2026-02-27 17:54:12,157 [INFO] Done: 60 / 80 confirmed | 20 → None

[map][drug][Llama] raw='adalimumab-afal' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-aflx' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-aqbz' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-bdgm' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-bmsj' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-dyar' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-htkn' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-kmrt' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-lwbs' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-sybb' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-tmcn' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-yflx' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='adalimumab-zmnl' -> canonical='ADALIMUMAB' -> id='CHEMBL1201580'
[map][drug][Llama] raw='azathioprine-yjyr' -> canonical='AZATHIOPRINE' -> id='CHEMBL1542'
[map][drug][Llama] raw='baricitinib-111' -> canonical='BARICITINIB' -> id='CHEMBL2105759'
[map][drug][Llama] raw='baricitinib-hybd' -> canonical='BARICITINIB' -> id='CHEMBL2105759'
[map][drug][Llama] raw='cyclosporine-sjyr' -> canonical='CYCLOSPORINE' -> id='CHEMBL160'
[map][drug][Llama] raw='dapson' -> canonical='DAPSONE' -> id='CHEMBL1043'
[map][drug][Llama] raw='dapson-klrx' -> canonical='DAPSONE' -> id='CHEMBL1043'
[map][drug][Llama] raw='hydroxychloroquine-qxbl' -> canonical='HYDROXYCHLOROQUINE' -> id='CHEMBL1535'
[map][drug][Llama] raw='infliximab-dgyl' -> canonical='INFLIXIMAB' -> id='CHEMBL1201581'
[map][drug][Llama] raw='infliximab-qbxj' -> canonical='INFLIXIMAB' -> id='CHEMBL1201581'
[map][drug][Llama] raw='infliximab-qryn' -> canonical='INFLIXIMAB' -> id='CHEMBL1201581'
[map][drug][Llama] raw='infliximab-xyyf' -> canonical='INFLIXIMAB' -> id='CHEMBL1201581'
[map][drug][Llama] raw='infliximab-yyjx' -> canonical='INFLIXIMAB' -> id='CHEMBL1201581'
[map][drug][Llama] raw='leflunomide-yqbl' -> canonical='LEFLUNOMIDE' -> id='CHEMBL960'
[map][drug][Llama] raw='methotrexate-bxrl' -> canonical='METHOTREXATE' -> id='CHEMBL34259'
[map][drug][Llama] raw='methotrexate-qqlx' -> canonical='METHOTREXATE' -> id='CHEMBL34259'
[map][drug][Llama] raw='minocycline-rlbz' -> canonical='MINOCYCLINE' -> id='CHEMBL1434'
[map][drug][Llama] raw='nab-nab-paclitaxel' -> canonical='PACLITAXEL' -> id='CHEMBL428647'
[map][drug][Llama] raw='nab-paclitaxel' -> canonical='PACLITAXEL' -> id='CHEMBL428647'
[map][drug][Llama] raw='nal-IRI' -> canonical='IRINOTECAN' -> id='CHEMBL481'
[map][drug][Llama] raw='prednisone-tkrx' -> canonical='PREDNISONE' -> id='CHEMBL635'
[map][drug][Llama] raw='rituximab-cyrn' -> canonical='RITUXIMAB' -> id='CHEMBL1201576'
[map][drug][Llama] raw='rituximab-gdox' -> canonical='RITUXIMAB' -> id='CHEMBL1201576'
[map][drug][Llama] raw='rituximab-johy' -> canonical='RITUXIMAB' -> id='CHEMBL1201576'
[map][drug][Llama] raw='rituximab-uyvw' -> canonical='RITUXIMAB' -> id='CHEMBL1201576'
[map][drug][Llama] raw='rituximab-wlso' -> canonical='RITUXIMAB' -> id='CHEMBL1201576'
[map][drug][Llama] raw='sulfasalazine-rbfb' -> canonical='SULFASALAZINE' -> id='CHEMBL421'
[map][drug][Llama] raw='tocilizumab-dqrx' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-kmrz' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-njrz' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-qdvj' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-tlzo' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-ttz' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-twpj' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-xjrz' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tocilizumab-yvzp' -> canonical='TOCILIZUMAB' -> id='CHEMBL1237022'
[map][drug][Llama] raw='tofacitinib-101' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-dtax' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-kjyr' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-lnrx' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-mgzx' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-sbtx' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-sjyr' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-xklr' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-yklr' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='tofacitinib-ytbx' -> canonical='TOFACITINIB' -> id='CHEMBL221959'
[map][drug][Llama] raw='upadacitinib-rblx' -> canonical='UPADACITINIB' -> id='CHEMBL3622821'
[map][drug][Llama] raw='upadacitinib-rwbl' -> canonical='UPADACITINIB' -> id='CHEMBL3622821'

                     drug_name        drug_id       source
0                                        None         None
1               5-fluorouracil      CHEMBL185  OpenTargets
2                     Abraxane   CHEMBL428647  OpenTargets
3    Ado-trastuzumab emtansine  CHEMBL1743082  OpenTargets
4                     Afatinib  CHEMBL1173655  OpenTargets
..                         ...            ...          ...
344                venlafaxine      CHEMBL637  OpenTargets
345                  verapamil     CHEMBL6966  OpenTargets
346                vinorelbine   CHEMBL553025  OpenTargets
347   z Jucabtagene autoleucel           None         None
348               zolmitriptan     CHEMBL1185  OpenTargets

[349 rows x 3 columns]

In [11]:
df_drug["source"].value_counts()

source
OpenTargets    268
Llama           60
Name: count, dtype: int64

In [12]:
# df_drug[df_drug["source"]=="Llama"]

In [13]:
df_drug[df_drug.isna().any(axis=1)]

                       drug_name drug_id source
0                                   None   None
22               COMT inhibitors    None   None
32             Dopamine agonists    None   None
42                    FOLFIRINOX    None   None
50                    Innotyucel    None   None
58              MAO-B inhibitors    None   None
77   Platinum-based chemotherapy    None   None
91                       Stalevo    None   None
109                      Zinbota    None   None
113               abatacept-kybx    None   None
114               abatacept-rvbx    None   None
115               abatacept-sxyn    None   None
116               abatacept-xryn    None   None
117               abatacept-yjbx    None   None
192                  eraminophen    None   None
199              etarnecept-trsb    None   None
278               ramedemiglucan    None   None
296                  sipanizumab    None   None
298     sotacabtagene autoleucel    None   None
304                     taissubt    None   None
347     z Jucabtagene autoleucel    None   None

##### Associate id with all disease entry

In [14]:
# Resolve unique disease surface forms to IDs.
# Canonical fallback is internal; returned rows remain keyed by raw input disease_name.
df_disease = await get_disease_ids_fast(list(question_entities["disease_name"]))
df_disease = df_disease.drop_duplicates(subset=["disease_name", "disease_id"]).reset_index(drop=True)
df_disease

2026-02-27 17:54:14,940 [INFO] [LLM] Total 43 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 17:54:14,941 [INFO] [LLM] Batch size: 43

[map][disease][OpenTargets] raw='Achondroplasia' -> id='MONDO_0007037'
[map][disease][OpenTargets] raw='Acute lymphoblastic leukemia' -> id='EFO_0000220'
[map][disease][OpenTargets] raw='Acute myeloid leukemia' -> id='EFO_0000222'
[map][disease][OpenTargets] raw='Adenocarcinoma' -> id='EFO_0000228'
[map][disease][OpenTargets] raw='Alveolar soft part sarcoma' -> id='EFO_0007143'
[map][disease][OpenTargets] raw='Alzheimer's disease' -> id='MONDO_0007088'
[map][disease][OpenTargets] raw='Amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][OpenTargets] raw='Anaplastic large cell lymphoma' -> id='EFO_0003032'
[map][disease][OpenTargets] raw='Angiosarcoma' -> id='EFO_0003968'
[map][disease][OpenTargets] raw='Antley-Bixler syndrome' -> id='MONDO_0008803'
[map][disease][OpenTargets] raw='Apert syndrome' -> id='MONDO_0007041'
[map][disease][OpenTargets] raw='Astrocytoma' -> id='EFO_0000272'
[map][disease][OpenTargets] raw='B-cell lymphoma' -> id='EFO_1001938'
[map][disease][OpenTargets] raw='Biliary tract cancer' -> id='MONDO_0003060'
[map][disease][OpenTargets] raw='Bladder cancer' -> id='MONDO_0004986'
[map][disease][OpenTargets] raw='Bladder carcinoma' -> id='MONDO_0004986'
[map][disease][OpenTargets] raw='Brain cancer' -> id='MONDO_0001657'
[map][disease][OpenTargets] raw='Breast Cancer' -> id='EFO_0000305'
[map][disease][OpenTargets] raw='Breast cancer' -> id='EFO_0000305'
[map][disease][OpenTargets] raw='Bronchopulmonary dysplasia' -> id='MONDO_0019091'
[map][disease][OpenTargets] raw='Cancer' -> id='MONDO_0004992'
[map][disease][OpenTargets] raw='Carcinoid tumor' -> id='EFO_0004243'
[map][disease][OpenTargets] raw='Carcinoma' -> id='EFO_0000313'
[map][disease][OpenTargets] raw='Carcinosarcoma' -> id='MONDO_0002928'
[map][disease][OpenTargets] raw='Cardiofaciocutaneous syndrome' -> id='MONDO_0015280'
[map][disease][OpenTargets] raw='Cervical cancer' -> id='EFO_0001061'
[map][disease][OpenTargets] raw='Cholangiocarcinoma' -> id='EFO_0005221'
[map][disease][OpenTargets] raw='Chondrosarcoma' -> id='EFO_0000333'
[map][disease][OpenTargets] raw='Chromophobe renal cell carcinoma' -> id='EFO_0000335'
[map][disease][OpenTargets] raw='Chronic lymphocytic leukemia' -> id='EFO_0000095'
[map][disease][OpenTargets] raw='Chronic myeloid leukemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='Chronic myelomonocytic leukemia' -> id='EFO_1001779'
[map][disease][OpenTargets] raw='Clear cell renal cell carcinoma' -> id='EFO_0000349'
[map][disease][OpenTargets] raw='Colon cancer' -> id='EFO_1001950'
[map][disease][OpenTargets] raw='Colonic adenocarcinoma' -> id='EFO_1001949'
[map][disease][OpenTargets] raw='Colorectal Cancer' -> id='EFO_1001951'
[map][disease][OpenTargets] raw='Colorectal cancer' -> id='EFO_1001951'
[map][disease][OpenTargets] raw='Corneal dystrophy' -> id='MONDO_0018102'
[map][disease][OpenTargets] raw='Coronary artery disease' -> id='EFO_0001645'
[map][disease][OpenTargets] raw='Costello syndrome' -> id='MONDO_0009026'
[map][disease][OpenTargets] raw='Craniosynostosis' -> id='MONDO_0015469'
[map][disease][OpenTargets] raw='Crohn's disease' -> id='EFO_0000384'
[map][disease][OpenTargets] raw='Crouzon syndrome' -> id='MONDO_0007405'
[map][disease][OpenTargets] raw='Cutaneous T-cell lymphoma' -> id='EFO_0002913'
[map][disease][OpenTargets] raw='Cystic Fibrosis' -> id='MONDO_0009061'
[map][disease][OpenTargets] raw='Diabetic macular edema' -> id='EFO_0009321'
[map][disease][OpenTargets] raw='Diffuse large B-cell lymphoma' -> id='EFO_0000403'
[map][disease][OpenTargets] raw='Ductal carcinoma' -> id='EFO_0006318'
[map][disease][OpenTargets] raw='Ductal carcinoma in situ' -> id='EFO_0000432'
[map][disease][OpenTargets] raw='Endometrial Cancer' -> id='EFO_0007532'
[map][disease][OpenTargets] raw='Endometrial cancer' -> id='EFO_0007532'
[map][disease][OpenTargets] raw='Ependymoma' -> id='EFO_1000028'
[map][disease][OpenTargets] raw='Epithelial ovarian cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='Esophageal cancer' -> id='EFO_0002916'
[map][disease][OpenTargets] raw='Ewing sarcoma' -> id='EFO_0000174'
[map][disease][OpenTargets] raw='Fallopian tube cancer' -> id='EFO_1000251'
[map][disease][OpenTargets] raw='Fibrosarcoma' -> id='EFO_0002087'
[map][disease][OpenTargets] raw='Fibrous dysplasia' -> id='MONDO_0000845'
[map][disease][OpenTargets] raw='Gallbladder cancer' -> id='EFO_1001956'
[map][disease][OpenTargets] raw='Gastric cancer' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='Gastrointestinal stromal tumor' -> id='EFO_0010279'
[map][disease][OpenTargets] raw='Germ cell tumor' -> id='EFO_0000514'
[map][disease][OpenTargets] raw='Glioblastoma' -> id='EFO_0000519'
[map][disease][OpenTargets] raw='Glioma' -> id='EFO_0005543'
[map][disease][OpenTargets] raw='Glomerulonephritis' -> id='MONDO_0002462'
[map][disease][OpenTargets] raw='Head and Neck Squamous Cell Carcinoma' -> id='EFO_0000181'
[map][disease][OpenTargets] raw='Head and neck cancer' -> id='EFO_0006859'
[map][disease][OpenTargets] raw='Hemangioblastoma' -> id='MONDO_0016748'
[map][disease][OpenTargets] raw='Hepatitis C' -> id='EFO_0003047'
[map][disease][OpenTargets] raw='Hepatoblastoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Hepatoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Hereditary diffuse gastric cancer' -> id='MONDO_0007648'
[map][disease][OpenTargets] raw='Hodgkin lymphoma' -> id='EFO_0000183'
[map][disease][OpenTargets] raw='Hodgkin's lymphoma' -> id='EFO_0000183'
[map][disease][OpenTargets] raw='Human papillomavirus infection' -> id='EFO_0001668'
[map][disease][OpenTargets] raw='Huntington's Disease' -> id='MONDO_0007739'
[map][disease][OpenTargets] raw='Huntington's disease' -> id='MONDO_0007739'
[map][disease][OpenTargets] raw='Immune thrombocytopenic purpura' -> id='EFO_0007160'
[map][disease][OpenTargets] raw='Inflammatory myofibroblastic tumor' -> id='MONDO_0015798'
[map][disease][OpenTargets] raw='Intraductal papillary mucinous neoplasm' -> id='MONDO_0004286'
[map][disease][OpenTargets] raw='Intrahepatic cholangiocarcinoma' -> id='EFO_1001961'
[map][disease][OpenTargets] raw='Jackson-Weiss syndrome' -> id='MONDO_0007400'
[map][disease][OpenTargets] raw='Juvenile polyposis syndrome' -> id='MONDO_0017380'
[map][disease][OpenTargets] raw='Keratosis follicularis' -> id='MONDO_0007417'
[map][disease][OpenTargets] raw='Kidney cancer' -> id='EFO_0002890'
[map][disease][OpenTargets] raw='Langerhans cell histiocytosis' -> id='EFO_1000318'
[map][disease][OpenTargets] raw='Laryngeal cancer' -> id='EFO_0003817'
[map][disease][OpenTargets] raw='Leiomyosarcoma' -> id='EFO_0000564'
[map][disease][OpenTargets] raw='Leukemia' -> id='EFO_0000565'
[map][disease][OpenTargets] raw='Li-Fraumeni syndrome' -> id='MONDO_0018875'
[map][disease][OpenTargets] raw='Liposarcoma' -> id='EFO_0000569'
[map][disease][OpenTargets] raw='Liver cancer' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Lung Adenocarcinoma' -> id='EFO_0005288'
[map][disease][OpenTargets] raw='Lung Neoplasms' -> id='MONDO_0021117'
[map][disease][OpenTargets] raw='Lung adenocarcinoma' -> id='EFO_0005288'
[map][disease][OpenTargets] raw='Lung cancer' -> id='EFO_0001071'
[map][disease][OpenTargets] raw='Lymphoma' -> id='EFO_0000574'
[map][disease][OpenTargets] raw='Macular edema' -> id='MONDO_0003005'
[map][disease][OpenTargets] raw='Malignancy' -> id='MONDO_0004992'
[map][disease][OpenTargets] raw='Malignant melanoma' -> id='EFO_0000756'
[map][disease][OpenTargets] raw='Malignant neoplasm' -> id='EFO_1000654'
[map][disease][OpenTargets] raw='Malignant neoplasm of bladder' -> id='MONDO_0001187'
[map][disease][OpenTargets] raw='Malignant neoplasm of colon' -> id='MONDO_0021063'
[map][disease][OpenTargets] raw='Malignant neoplasm of endometrium' -> id='MONDO_0011962'
[map][disease][OpenTargets] raw='Malignant neoplasm of kidney' -> id='MONDO_0002367'
[map][disease][OpenTargets] raw='Malignant neoplasm of lung' -> id='MONDO_0008903'
[map][disease][OpenTargets] raw='Malignant neoplasm of ovary' -> id='MONDO_0008170'
[map][disease][OpenTargets] raw='Malignant neoplasm of pancreas' -> id='EFO_1000359'
[map][disease][OpenTargets] raw='Malignant neoplasm of rectum' -> id='EFO_1000657'
[map][disease][OpenTargets] raw='Malignant neoplasm of stomach' -> id='MONDO_0001056'
[map][disease][OpenTargets] raw='Malignant neoplasm of uterus' -> id='MONDO_0002715'
[map][disease][OpenTargets] raw='Malignant peripheral nerve sheath tumor' -> id='EFO_0000760'
[map][disease][OpenTargets] raw='Mantle cell lymphoma' -> id='EFO_1001469'
[map][disease][OpenTargets] raw='Medullary thyroid carcinoma' -> id='MONDO_0007958'
[map][disease][OpenTargets] raw='Medulloblastoma' -> id='EFO_0002939'
[map][disease][OpenTargets] raw='Melanoma' -> id='EFO_0000756'
[map][disease][OpenTargets] raw='Meningioma' -> id='MONDO_0003057'
[map][disease][OpenTargets] raw='Merkel cell carcinoma' -> id='EFO_1001471'
[map][disease][OpenTargets] raw='Mesothelioma' -> id='EFO_0000588'
[map][disease][OpenTargets] raw='Metastasis' -> id='EFO_0009708'
[map][disease][OpenTargets] raw='Metastatic melanoma' -> id='EFO_0002617'
[map][disease][OpenTargets] raw='Migraine' -> id='MONDO_0005277'
[map][disease][OpenTargets] raw='Mucinous adenocarcinoma' -> id='EFO_0000197'
[map][disease][OpenTargets] raw='Multiple Sclerosis' -> id='MONDO_0005301'
[map][disease][OpenTargets] raw='Myelodysplastic syndrome' -> id='EFO_0000198'
[map][disease][OpenTargets] raw='Myelodysplastic syndromes' -> id='EFO_0000198'
[map][disease][OpenTargets] raw='Myeloproliferative neoplasms' -> id='EFO_0002428'
[map][disease][OpenTargets] raw='Nasopharyngeal carcinoma' -> id='MONDO_0011775'
[map][disease][OpenTargets] raw='Neoplasm' -> id='EFO_0000616'
[map][disease][OpenTargets] raw='Neovascular glaucoma' -> id='EFO_1001060'
[map][disease][OpenTargets] raw='Nephroblastoma' -> id='MONDO_0008679'
[map][disease][OpenTargets] raw='Neuroblastoma' -> id='EFO_0000621'
[map][disease][OpenTargets] raw='Neurofibromatosis type 1' -> id='MONDO_0018975'
[map][disease][OpenTargets] raw='Non-Small Cell Lung Cancer' -> id='EFO_0003060'
[map][disease][OpenTargets] raw='Non-small cell lung cancer' -> id='EFO_0003060'
[map][disease][OpenTargets] raw='Non-small cell lung carcinoma' -> id='EFO_0003060'
[map][disease][OpenTargets] raw='Noonan syndrome' -> id='MONDO_0018997'
[map][disease][OpenTargets] raw='Oligodendroglioma' -> id='EFO_0000632'
[map][disease][OpenTargets] raw='Oral cavity cancer' -> id='EFO_0005570'
[map][disease][OpenTargets] raw='Osteosarcoma' -> id='EFO_0000637'
[map][disease][OpenTargets] raw='Ovarian Cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='Ovarian Neoplasms' -> id='EFO_0003893'
[map][disease][OpenTargets] raw='Ovarian cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='Ovarian carcinoma' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='Ovarian clear cell carcinoma' -> id='MONDO_0000548'
[map][disease][OpenTargets] raw='Pancreatic Cancer' -> id='EFO_0002618'
[map][disease][OpenTargets] raw='Pancreatic Neoplasms' -> id='EFO_0003860'
[map][disease][OpenTargets] raw='Pancreatic cancer' -> id='EFO_0002618'
[map][disease][OpenTargets] raw='Pancreatic ductal adenocarcinoma' -> id='MONDO_0005184'
[map][disease][OpenTargets] raw='Papillary renal cell carcinoma' -> id='EFO_0000640'
[map][disease][OpenTargets] raw='Papillary thyroid carcinoma' -> id='EFO_0000641'
[map][disease][OpenTargets] raw='Parkinson's disease' -> id='MONDO_0005180'
[map][disease][OpenTargets] raw='Pfeiffer syndrome' -> id='MONDO_0007043'
[map][disease][OpenTargets] raw='Pheochromocytoma' -> id='EFO_0000239'
[map][disease][OpenTargets] raw='Pituitary adenoma' -> id='EFO_1000478'
[map][disease][OpenTargets] raw='Pleomorphic xanthoastrocytoma' -> id='MONDO_0016690'
[map][disease][OpenTargets] raw='Polycystic kidney disease' -> id='EFO_0008620'
[map][disease][OpenTargets] raw='Primary peritoneal cancer' -> id='MONDO_0015686'
[map][disease][OpenTargets] raw='Prostate cancer' -> id='EFO_0001663'
[map][disease][OpenTargets] raw='Prostate carcinoma' -> id='EFO_0001663'
[map][disease][OpenTargets] raw='Pulmonary embolism' -> id='EFO_0003827'
[map][disease][OpenTargets] raw='Rectal adenocarcinoma' -> id='EFO_0005631'
[map][disease][OpenTargets] raw='Renal cell carcinoma' -> id='EFO_0000681'
[map][disease][OpenTargets] raw='Retinal vein occlusion' -> id='EFO_1001157'
[map][disease][OpenTargets] raw='Retinoblastoma' -> id='MONDO_0008380'
[map][disease][OpenTargets] raw='Rhabdomyosarcoma' -> id='EFO_0002918'
[map][disease][OpenTargets] raw='Rheumatoid arthritis' -> id='EFO_0000685'
[map][disease][OpenTargets] raw='Rickets' -> id='EFO_0005583'
[map][disease][OpenTargets] raw='Roberts syndrome' -> id='MONDO_0100253'
[map][disease][OpenTargets] raw='Saethre-Chotzen syndrome' -> id='MONDO_0007042'
[map][disease][OpenTargets] raw='Salivary gland cancer' -> id='MONDO_0000521'
[map][disease][OpenTargets] raw='Sarcoidosis' -> id='MONDO_0019338'
[map][disease][OpenTargets] raw='Sarcoma' -> id='EFO_0000691'
[map][disease][OpenTargets] raw='Schwannoma' -> id='EFO_0000693'
[map][disease][OpenTargets] raw='Schwannomatosis' -> id='MONDO_0008075'
[map][disease][OpenTargets] raw='Seminoma' -> id='EFO_1000566'
[map][disease][OpenTargets] raw='Sinonasal undifferentiated carcinoma' -> id='EFO_1000527'
[map][disease][OpenTargets] raw='Small cell lung cancer' -> id='EFO_0000702'
[map][disease][OpenTargets] raw='Small intestinal adenocarcinoma' -> id='EFO_1000532'
[map][disease][OpenTargets] raw='Soft tissue sarcoma' -> id='EFO_1001968'
[map][disease][OpenTargets] raw='Solitary fibrous tumor' -> id='MONDO_0016238'
[map][disease][OpenTargets] raw='Spinal cord tumor' -> id='EFO_0003828'
[map][disease][OpenTargets] raw='Squamous cell carcinoma' -> id='EFO_0000707'
[map][disease][OpenTargets] raw='Squamous cell carcinoma of the head and neck' -> id='EFO_0000181'
[map][disease][OpenTargets] raw='Stomach cancer' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='Synovial sarcoma' -> id='EFO_0001376'
[map][disease][OpenTargets] raw='Systemic lupus erythematosus' -> id='MONDO_0007915'
[map][disease][OpenTargets] raw='T-cell acute lymphoblastic leukemia' -> id='EFO_0000209'
[map][disease][OpenTargets] raw='T-cell leukemia' -> id='EFO_0005592'
[map][disease][OpenTargets] raw='T-cell lymphoma' -> id='MONDO_0015760'
[map][disease][OpenTargets] raw='T-cell prolymphocytic leukemia' -> id='EFO_1000560'
[map][disease][OpenTargets] raw='TNBC' -> id='EFO_0005537'
[map][disease][OpenTargets] raw='Teratoma' -> id='MONDO_0002601'
[map][disease][OpenTargets] raw='Testicular cancer' -> id='EFO_0004281'
[map][disease][OpenTargets] raw='Testicular carcinoma' -> id='EFO_0005088'
[map][disease][OpenTargets] raw='Thymoma' -> id='EFO_1000581'
[map][disease][OpenTargets] raw='Thyroid cancer' -> id='EFO_0002892'
[map][disease][OpenTargets] raw='Thyroid gland cancer' -> id='EFO_0002892'
[map][disease][OpenTargets] raw='Tongue cancer' -> id='EFO_0003871'
[map][disease][OpenTargets] raw='Transitional cell carcinoma' -> id='EFO_1000601'
[map][disease][OpenTargets] raw='Triple-negative breast cancer' -> id='EFO_0005537'
[map][disease][OpenTargets] raw='Tubo-ovarian abscess' -> id='MONDO_0001172'
[map][disease][OpenTargets] raw='Tumor' -> id='EFO_0000616'
[map][disease][OpenTargets] raw='Type 2 diabetes mellitus' -> id='MONDO_0005148'
[map][disease][OpenTargets] raw='Urethral cancer' -> id='EFO_0003846'
[map][disease][OpenTargets] raw='Urothelial carcinoma' -> id='EFO_0008528'
[map][disease][OpenTargets] raw='Uterine cancer' -> id='MONDO_0002715'
[map][disease][OpenTargets] raw='Uterine sarcoma' -> id='EFO_0002914'
[map][disease][OpenTargets] raw='Vaginal cancer' -> id='MONDO_0001402'
[map][disease][OpenTargets] raw='Vascular malformation' -> id='EFO_0006888'
[map][disease][OpenTargets] raw='Ventricular tachycardia' -> id='EFO_0005306'
[map][disease][OpenTargets] raw='Vulvar cancer' -> id='EFO_0002921'
[map][disease][OpenTargets] raw='Waldenstrom macroglobulinemia' -> id='EFO_0009441'
[map][disease][OpenTargets] raw='Wilms tumor' -> id='MONDO_0024676'
[map][disease][OpenTargets] raw='X-linked adrenoleukodystrophy' -> id='MONDO_0018544'
[map][disease][OpenTargets] raw='acute myeloid leukemia' -> id='EFO_0000222'
[map][disease][OpenTargets] raw='adenocarcinoma' -> id='EFO_0000228'
[map][disease][OpenTargets] raw='adenoid cystic carcinoma' -> id='EFO_1000796'
[map][disease][OpenTargets] raw='adrenocortical carcinoma' -> id='EFO_1000796'
[map][disease][OpenTargets] raw='amyotrophic lateral sclerosis' -> id='MONDO_0004976'
[map][disease][OpenTargets] raw='anaplastic large cell lymphoma' -> id='EFO_0003032'
[map][disease][OpenTargets] raw='ankylosing spondylitis' -> id='EFO_0003898'
[map][disease][OpenTargets] raw='arthritis' -> id='EFO_0005856'
[map][disease][OpenTargets] raw='astrocytoma' -> id='EFO_0000272'
[map][disease][OpenTargets] raw='autism spectrum disorder' -> id='EFO_0003756'
[map][disease][OpenTargets] raw='bladder cancer' -> id='MONDO_0004986'
[map][disease][OpenTargets] raw='brain cancer' -> id='MONDO_0001657'
[map][disease][OpenTargets] raw='breast cancer' -> id='EFO_0000305'
[map][disease][OpenTargets] raw='celiac disease' -> id='EFO_0001060'
[map][disease][OpenTargets] raw='cervical cancer' -> id='EFO_0001061'
[map][disease][OpenTargets] raw='cholangiocarcinoma' -> id='EFO_0005221'
[map][disease][OpenTargets] raw='chronic myeloid leukemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='classical hodgkin lymphoma' -> id='MONDO_0009348'
[map][disease][OpenTargets] raw='colon cancer' -> id='EFO_1001950'
[map][disease][OpenTargets] raw='colorectal adenocarcinoma' -> id='EFO_0000365'
[map][disease][OpenTargets] raw='colorectal cancer' -> id='EFO_1001951'
[map][disease][OpenTargets] raw='crohn's disease' -> id='EFO_0000384'
[map][disease][OpenTargets] raw='cystic fibrosis' -> id='MONDO_0009061'
[map][disease][OpenTargets] raw='diabetes mellitus' -> id='EFO_0000400'
[map][disease][OpenTargets] raw='dysmenorrhea' -> id='HP_0100607'
[map][disease][OpenTargets] raw='endometrial cancer' -> id='EFO_0007532'
[map][disease][OpenTargets] raw='endometrial carcinoma' -> id='EFO_1001512'
[map][disease][OpenTargets] raw='epilepsy' -> id='EFO_0000474'
[map][disease][OpenTargets] raw='esophageal cancer' -> id='EFO_0002916'
[map][disease][OpenTargets] raw='esophageal squamous cell carcinoma' -> id='EFO_0005922'
[map][disease][OpenTargets] raw='fever' -> id='HP_0001945'
[map][disease][OpenTargets] raw='gastric cancer' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='glioblastoma' -> id='EFO_0000519'
[map][disease][OpenTargets] raw='glioma' -> id='EFO_0005543'
[map][disease][OpenTargets] raw='hairy cell leukemia' -> id='EFO_1000956'
[map][disease][OpenTargets] raw='head and neck squamous cell carcinoma' -> id='EFO_0000181'
[map][disease][OpenTargets] raw='hepatitis C' -> id='EFO_0003047'
[map][disease][OpenTargets] raw='hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='hidradenitis suppurativa' -> id='EFO_1000710'
[map][disease][OpenTargets] raw='inflammatory bowel disease' -> id='EFO_0003767'
[map][disease][OpenTargets] raw='juvenile idiopathic arthritis' -> id='EFO_0002609'
[map][disease][OpenTargets] raw='leukemia' -> id='EFO_0000565'
[map][disease][OpenTargets] raw='liposarcoma' -> id='EFO_0000569'
[map][disease][OpenTargets] raw='lung adenocarcinoma' -> id='EFO_0005288'
[map][disease][OpenTargets] raw='lung cancer' -> id='EFO_0001071'
[map][disease][OpenTargets] raw='lymphoma' -> id='EFO_0000574'
[map][disease][OpenTargets] raw='melanocytic nevus' -> id='EFO_0009675'
[map][disease][OpenTargets] raw='melanoma' -> id='EFO_0000756'
[map][disease][OpenTargets] raw='merkel cell carcinoma' -> id='EFO_1001471'
[map][disease][OpenTargets] raw='migraine' -> id='MONDO_0005277'
[map][disease][OpenTargets] raw='multiple sclerosis' -> id='MONDO_0005301'

2026-02-27 17:54:16,239 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:54:16,241 [INFO] [LLM] Batch done in 1.30s
2026-02-27 17:54:16,242 [INFO] [LLM] 'Appendiceal cancer' → 'appendix cancer'
2026-02-27 17:54:16,243 [INFO] [LLM] 'Bronchial carcinoid tumor' → 'bronchial carcinoid tumor'
2026-02-27 17:54:16,243 [INFO] [LLM] 'Carcinogenesis' → None
2026-02-27 17:54:16,243 [INFO] [LLM] 'Co-arctation of the aorta' → 'coarctation of the aorta'
2026-02-27 17:54:16,244 [INFO] [LLM] 'Colorectal Neoplasms' → 'colorectal cancer'
2026-02-27 17:54:16,245 [INFO] [LLM] 'Cutaneous anaplastic large cell lymphoma' → 'cutaneous anaplastic large cell lymphoma'
2026-02-27 17:54:16,245 [INFO] [LLM] 'Disease' → None
2026-02-27 17:54:16,246 [INFO] [LLM] 'Fibroblast growth factor receptor 2-related developmental disorder' → None
2026-02-27 17:54:16,246 [INFO] [LLM] 'Gastrointestinal cancer' → 'gastrointestinal cancer'
2026-02-27 17:54:16,246 [INFO] [LLM] 'HER2-low breast cancer' → 'breast cancer'
2026-02-27 17:54:16,247 [INFO] [LLM] 'HER2-mutant lung cancer' → 'lung cancer'
2026-02-27 17:54:16,247 [INFO] [LLM] 'HER2-mutant non-small cell lung cancer' → 'non-small cell lung cancer'
2026-02-27 17:54:16,247 [INFO] [LLM] 'HER2-positive advanced or metastatic breast cancer' → 'breast cancer'
2026-02-27 17:54:16,248 [INFO] [LLM] 'HER2-positive breast cancer' → 'breast cancer'
2026-02-27 17:54:16,248 [INFO] [LLM] 'HER2-positive gastric cancer' → 'gastric cancer'
2026-02-27 17:54:16,248 [INFO] [LLM] 'HER2-positive metastatic breast cancer' → 'breast cancer'
2026-02-27 17:54:16,249 [INFO] [LLM] 'HER2-positive unresectable or metastatic breast cancer' → 'breast cancer'
2026-02-27 17:54:16,249 [INFO] [LLM] 'Hutchenreuter-TP53 syndrome' → None
2026-02-27 17:54:16,249 [INFO] [LLM] 'Large B-cell lymphoma' → 'diffuse large B-cell lymphoma'
2026-02-27 17:54:16,251 [INFO] [LLM] 'Large cell lymphoma' → 'large cell lymphoma'
2026-02-27 17:54:16,251 [INFO] [LLM] 'Multiple types of cancer' → None
2026-02-27 17:54:16,252 [INFO] [LLM] 'Neoplasms' → None
2026-02-27 17:54:16,252 [INFO] [LLM] 'Neuroendocrine tumors' → 'neuroendocrine tumor'
2026-02-27 17:54:16,253 [INFO] [LLM] 'Pediatric low-grade glioma' → 'pediatric low-grade glioma'
2026-02-27 17:54:16,253 [INFO] [LLM] 'Peripheral nerve sheath tumor' → 'peripheral nerve sheath tumor'
2026-02-27 17:54:16,254 [INFO] [LLM] 'Skeletal dysplasias' → None
2026-02-27 17:54:16,254 [INFO] [LLM] 'Thyroid gland tumors' → 'thyroid cancer'
2026-02-27 17:54:16,255 [INFO] [LLM] 'Tumorigenesis' → None
2026-02-27 17:54:16,255 [INFO] [LLM] '_renal cell carcinoma' → 'renal cell carcinoma'
2026-02-27 17:54:16,256 [INFO] [LLM] 'bao gồm cả các gen liên quan đến hội chứng ung thư biểu mô tế bào thận di truyền.' → None
2026-02-27 17:54:16,256 [INFO] [LLM] 'idiopathic ulcerative colitis' → 'ulcerative colitis'
2026-02-27 17:54:16,257 [INFO] [LLM] 'melanocytic nevi' → None
2026-02-27 17:54:16,257 [INFO] [LLM] 'melanocytic tumors' → None
2026-02-27 17:54:16,257 [INFO] [LLM] 'microsatellite instability-high cancer' → None
2026-02-27 17:54:16,259 [INFO] [LLM] 'microsatellite instability-high colorectal cancer' → 'colorectal cancer'
2026-02-27 17:54:16,260 [INFO] [LLM] 'microsatellite instability-high solid tumors' → None
2026-02-27 17:54:16,260 [INFO] [LLM] 'non-infectious uveitis' → 'uveitis'
2026-02-27 17:54:16,260 [INFO] [LLM] "pediatric crohn's disease" → "crohn's disease"
2026-02-27 17:54:16,261 [INFO] [LLM] 'pediatric idiopathic ulcerative colitis' → 'ulcerative colitis'
2026-02-27 17:54:16,261 [INFO] [LLM] 'primary dysmenorrhea' → None
2026-02-27 17:54:16,262 [INFO] [LLM] 'primary mediastinal large B-cell lymphoma' → 'primary mediastinal large B-cell lymphoma'
2026-02-27 17:54:16,263 [INFO] [LLM] 'primary mediastinal large b-cell lymphoma' → 'primary mediastinal large B-cell lymphoma'
2026-02-27 17:54:16,264 [INFO] [LLM] 'tumor mutational burden-high solid tumors' → None
2026-02-27 17:54:16,264 [INFO] [OT] Verifying 21 unique suggestions...
2026-02-27 17:54:16,735 [INFO] [OT] 'renal cell carcinoma' → 'renal cell carcinoma' (EFO_0000681)
2026-02-27 17:54:16,736 [INFO] [OT] 'ulcerative colitis' → 'ulcerative colitis' (EFO_0000729)
2026-02-27 17:54:16,736 [INFO] [OT] "crohn's disease" → "Crohn's disease" (EFO_0000384)
2026-02-27 17:54:16,737 [INFO] [OT] 'gastric cancer' → 'stomach neoplasm' (EFO_0003897)
2026-02-27 17:54:16,738 [INFO] [OT] 'thyroid cancer' → 'thyroid carcinoma' (EFO_0002892)
2026-02-27 17:54:16,738 [INFO] [OT] 'breast cancer' → 'breast carcinoma' (EFO_0000305)
2026-02-27 17:54:16,738 [INFO] [OT] 'non-small cell lung cancer' → 'non-small cell lung carcinoma' (EFO_0003060)
2026-02-27 17:54:16,739 [INFO] [OT] 'coarctation of the aorta' → 'Aortic Coarctation' (EFO_1001267)
2026-02-27 17:54:16,740 [INFO] [OT] 'diffuse large B-cell lymphoma' → 'diffuse large B-cell lymphoma' (EFO_0000403)
2026-02-27 17:54:16,741 [INFO] [OT] 'lung cancer' → 'lung carcinoma' (EFO_0001071)
2026-02-27 17:54:16,741 [INFO] [OT] 'uveitis' → 'uveitis' (EFO_1001231)
2026-02-27 17:54:16,742 [INFO] [OT] 'appendix cancer' → 'appendix cancer' (MONDO_0001235)
2026-02-27 17:54:16,742 [INFO] [OT] 'neuroendocrine tumor' → 'neuroendocrine neoplasm' (EFO_1001901)
2026-02-27 17:54:16,743 [INFO] [OT] 'colorectal cancer' → 'colorectal carcinoma' (EFO_1001951)
2026-02-27 17:54:16,745 [INFO] Done: 20 / 43 confirmed | 23 → None

[map][disease][Llama] raw='Appendiceal cancer' -> canonical='appendix cancer' -> id='MONDO_0001235'
[map][disease][Llama] raw='Co-arctation of the aorta' -> canonical='Aortic Coarctation' -> id='EFO_1001267'
[map][disease][Llama] raw='Colorectal Neoplasms' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='HER2-low breast cancer' -> canonical='breast carcinoma' -> id='EFO_0000305'
[map][disease][Llama] raw='HER2-mutant lung cancer' -> canonical='lung carcinoma' -> id='EFO_0001071'
[map][disease][Llama] raw='HER2-mutant non-small cell lung cancer' -> canonical='non-small cell lung carcinoma' -> id='EFO_0003060'
[map][disease][Llama] raw='HER2-positive advanced or metastatic breast cancer' -> canonical='breast carcinoma' -> id='EFO_0000305'
[map][disease][Llama] raw='HER2-positive breast cancer' -> canonical='breast carcinoma' -> id='EFO_0000305'
[map][disease][Llama] raw='HER2-positive gastric cancer' -> canonical='stomach neoplasm' -> id='EFO_0003897'
[map][disease][Llama] raw='HER2-positive metastatic breast cancer' -> canonical='breast carcinoma' -> id='EFO_0000305'
[map][disease][Llama] raw='HER2-positive unresectable or metastatic breast cancer' -> canonical='breast carcinoma' -> id='EFO_0000305'
[map][disease][Llama] raw='Large B-cell lymphoma' -> canonical='diffuse large B-cell lymphoma' -> id='EFO_0000403'
[map][disease][Llama] raw='Neuroendocrine tumors' -> canonical='neuroendocrine neoplasm' -> id='EFO_1001901'
[map][disease][Llama] raw='Thyroid gland tumors' -> canonical='thyroid carcinoma' -> id='EFO_0002892'
[map][disease][Llama] raw='_renal cell carcinoma' -> canonical='renal cell carcinoma' -> id='EFO_0000681'
[map][disease][Llama] raw='idiopathic ulcerative colitis' -> canonical='ulcerative colitis' -> id='EFO_0000729'
[map][disease][Llama] raw='microsatellite instability-high colorectal cancer' -> canonical='colorectal carcinoma' -> id='EFO_1001951'
[map][disease][Llama] raw='non-infectious uveitis' -> canonical='uveitis' -> id='EFO_1001231'
[map][disease][Llama] raw='pediatric crohn's disease' -> canonical='Crohn's disease' -> id='EFO_0000384'
[map][disease][Llama] raw='pediatric idiopathic ulcerative colitis' -> canonical='ulcerative colitis' -> id='EFO_0000729'
[warn] Unresolved diseases after OpenTargets/Llama/OLS: ['Bronchial carcinoid tumor', 'Carcinogenesis', 'Cutaneous anaplastic large cell lymphoma', 'Disease', 'Fibroblast growth factor receptor 2-related developmental disorder', 'Gastrointestinal cancer', 'Hutchenreuter-TP53 syndrome', 'Large cell lymphoma', 'Multiple types of cancer', 'Neoplasms', 'Pediatric low-grade glioma', 'Peripheral nerve sheath tumor', 'Skeletal dysplasias', 'Tumorigenesis', 'bao gồm cả các gen liên quan đến hội chứng ung thư biểu mô tế bào thận di truyền.', 'melanocytic nevi', 'melanocytic tumors', 'microsatellite instability-high cancer', 'microsatellite instability-high solid tumors', 'primary dysmenorrhea', 'primary mediastinal large B-cell lymphoma', 'primary mediastinal large b-cell lymphoma', 'tumor mutational burden-high solid tumors']

                                  disease_name     disease_id       source
0                               Achondroplasia  MONDO_0007037  OpenTargets
1                 Acute lymphoblastic leukemia    EFO_0000220  OpenTargets
2                       Acute myeloid leukemia    EFO_0000222  OpenTargets
3                               Adenocarcinoma    EFO_0000228  OpenTargets
4                   Alveolar soft part sarcoma    EFO_0007143  OpenTargets
..                                         ...            ...          ...
342  tumor mutational burden-high solid tumors           None         None
343                   type 2 diabetes mellitus  MONDO_0005148  OpenTargets
344                         ulcerative colitis    EFO_0000729  OpenTargets
345                       urothelial carcinoma    EFO_0008528  OpenTargets
346                                    uveitis    EFO_1001231  OpenTargets

[347 rows x 3 columns]

In [15]:
df_disease["source"].value_counts()

source
OpenTargets    304
Llama           20
Name: count, dtype: int64

In [16]:
df_disease[df_disease.isna().any(axis=1)]

                                          disease_name disease_id source
20                           Bronchial carcinoid tumor       None   None
23                                      Carcinogenesis       None   None
49            Cutaneous anaplastic large cell lymphoma       None   None
53                                             Disease       None   None
63   Fibroblast growth factor receptor 2-related de...       None   None
68                             Gastrointestinal cancer       None   None
95                         Hutchenreuter-TP53 syndrome       None   None
106                                Large cell lymphoma       None   None
145                           Multiple types of cancer       None   None
151                                          Neoplasms       None   None
176                         Pediatric low-grade glioma       None   None
177                      Peripheral nerve sheath tumor       None   None
203                                Skeletal dysplasias       None   None
231                                      Tumorigenesis       None   None
255  bao gồm cả các gen liên quan đến hội chứng ung...       None   None
293                                   melanocytic nevi       None   None
295                                 melanocytic tumors       None   None
298             microsatellite instability-high cancer       None   None
300       microsatellite instability-high solid tumors       None   None
319                               primary dysmenorrhea       None   None
320          primary mediastinal large B-cell lymphoma       None   None
321          primary mediastinal large b-cell lymphoma       None   None
342          tumor mutational burden-high solid tumors       None   None

In [17]:
# ------------------------------------------------------------------
# Disease canonical audit (OpenTargets-strict IDs only)
# ------------------------------------------------------------------
# IMPORTANT:
# - This cell runs an additional Llama canonicalization pass over unresolved rows.
# - IDs are still resolved ONLY via OpenTargets mapIds (score==1).
# - To avoid changing the baseline resolver output, writeback is OFF by default.
APPLY_AUDIT_MAPPINGS = False

# 1) Rows unresolved after primary resolver
unresolved_rows = df_disease[df_disease["disease_id"].isna()].reset_index(drop=True)
unresolved_raw_names = list(
    dict.fromkeys(
        str(name).strip()
        for name in unresolved_rows["disease_name"].dropna().astype(str).tolist()
        if str(name).strip()
    )
)

# 2) Llama canonicalization suggestions
disease_input_map = {name: None for name in unresolved_raw_names}
canonicalisation_map = await utility.canonicalise_disease_dict(disease_input_map)

# 3) OpenTargets strict verification (score==1 only)
canonical_terms_norm = list(
    dict.fromkeys(
        utility._normalize_disease_term(v)
        for v in canonicalisation_map.values()
        if isinstance(v, str) and v.strip()
    )
)
canonical_to_id = utility.resolve_diseases_opentargets_bulk(
    canonical_terms_norm,
    strict_score_one=True,
)

# 4) Build persistent audit table
audit_rows = []
applied_count = 0
candidate_count = 0

for raw_disease_name in unresolved_raw_names:
    canonical_name = canonicalisation_map.get(raw_disease_name)
    if isinstance(canonical_name, str) and canonical_name.strip():
        canonical_name = canonical_name.strip()
        canonical_norm = utility._normalize_disease_term(canonical_name)
        resolved_id = canonical_to_id.get(canonical_norm)
    else:
        canonical_name = None
        canonical_norm = None
        resolved_id = None

    can_apply = bool(resolved_id)
    if can_apply:
        candidate_count += 1
        print(f"[audit][disease][Llama->OT] raw='{raw_disease_name}' -> canonical='{canonical_name}' -> id='{resolved_id}'")

    if can_apply and APPLY_AUDIT_MAPPINGS:
        mask = df_disease["disease_name"].astype(str).str.strip() == raw_disease_name
        df_disease.loc[mask, "disease_id"] = resolved_id
        df_disease.loc[mask, "source"] = "Llama"
        applied_count += 1

    status = (
        "mappable_ot_exact" if can_apply else
        ("no_canonical" if canonical_name is None else "canonical_not_in_ot")
    )
    audit_rows.append({
        "raw_disease_name": raw_disease_name,
        "canonical_name": canonical_name,
        "canonical_norm": canonical_norm,
        "resolved_disease_id": resolved_id,
        "status": status,
        "can_apply": can_apply,
        "applied": bool(can_apply and APPLY_AUDIT_MAPPINGS),
    })

disease_canonical_audit_df = pd.DataFrame(audit_rows)
if not disease_canonical_audit_df.empty:
    disease_canonical_audit_df = disease_canonical_audit_df.sort_values(
        ["status", "raw_disease_name"],
        ascending=[True, True],
    ).reset_index(drop=True)

print(f"[summary][disease][audit] OT-mappable candidates: {candidate_count}")
print(f"[summary][disease][audit] applied to df_disease: {applied_count} (APPLY_AUDIT_MAPPINGS={APPLY_AUDIT_MAPPINGS})")
if not disease_canonical_audit_df.empty:
    print("[summary][disease][audit] status counts:")
    print(disease_canonical_audit_df["status"].value_counts(dropna=False))

disease_canonical_audit_df

2026-02-27 17:54:17,264 [INFO] [LLM] Total 23 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 17:54:17,264 [INFO] [LLM] Batch size: 23
2026-02-27 17:54:18,146 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 17:54:18,148 [INFO] [LLM] Batch done in 0.88s
2026-02-27 17:54:18,148 [INFO] [LLM] 'Bronchial carcinoid tumor' → 'bronchial carcinoid tumor'
2026-02-27 17:54:18,149 [INFO] [LLM] 'Carcinogenesis' → None
2026-02-27 17:54:18,149 [INFO] [LLM] 'Cutaneous anaplastic large cell lymphoma' → 'cutaneous anaplastic large cell lymphoma'
2026-02-27 17:54:18,150 [INFO] [LLM] 'Disease' → None
2026-02-27 17:54:18,150 [INFO] [LLM] 'Fibroblast growth factor receptor 2-related developmental disorder' → None
2026-02-27 17:54:18,150 [INFO] [LLM] 'Gastrointestinal cancer' → None
2026-02-27 17:54:18,151 [INFO] [LLM] 'Hutchenreuter-TP53 syndrome' → None
2026-02-27 17:54:18,151 [INFO] [LLM] 'Large cell lymphoma' → 'large cell lymphoma'
2026-02-27 17:54:18,151 [INFO] [LLM] 'Multiple types of cancer' → None
2026-02-27 17:54:18,152 [INFO] [LLM] 'Neoplasms' → None
2026-02-27 17:54:18,153 [INFO] [LLM] 'Pediatric low-grade glioma' → 'pediatric low-grade glioma'
2026-02-27 17:54:18,154 [INFO] [LLM] 'Peripheral nerve sheath tumor' → 'peripheral nerve sheath tumor'
2026-02-27 17:54:18,154 [INFO] [LLM] 'Skeletal dysplasias' → None
2026-02-27 17:54:18,154 [INFO] [LLM] 'Tumorigenesis' → None
2026-02-27 17:54:18,154 [INFO] [LLM] 'bao gồm cả các gen liên quan đến hội chứng ung thư biểu mô tế bào thận di truyền.' → None
2026-02-27 17:54:18,155 [INFO] [LLM] 'melanocytic nevi' → 'melanocytic nevi'
2026-02-27 17:54:18,155 [INFO] [LLM] 'melanocytic tumors' → 'melanocytic tumors'
2026-02-27 17:54:18,155 [INFO] [LLM] 'microsatellite instability-high cancer' → None
2026-02-27 17:54:18,156 [INFO] [LLM] 'microsatellite instability-high solid tumors' → None
2026-02-27 17:54:18,156 [INFO] [LLM] 'primary dysmenorrhea' → 'primary dysmenorrhea'
2026-02-27 17:54:18,156 [INFO] [LLM] 'primary mediastinal large B-cell lymphoma' → 'primary mediastinal large B-cell lymphoma'
2026-02-27 17:54:18,157 [INFO] [LLM] 'primary mediastinal large b-cell lymphoma' → 'primary mediastinal large B-cell lymphoma'
2026-02-27 17:54:18,157 [INFO] [LLM] 'tumor mutational burden-high solid tumors' → None
2026-02-27 17:54:18,158 [INFO] [OT] Verifying 9 unique suggestions...
2026-02-27 17:54:18,563 [INFO] Done: 0 / 23 confirmed | 23 → None

[summary][disease][audit] OT-mappable candidates: 0
[summary][disease][audit] applied to df_disease: 0 (APPLY_AUDIT_MAPPINGS=False)
[summary][disease][audit] status counts:
status
no_canonical    23
Name: count, dtype: int64

,raw_disease_name,canonical_name,canonical_norm,resolved_disease_id,status,can_apply,applied
0,Bronchial carcinoid tumor,None,None,None,no_canonical,False,False
1,Carcinogenesis,None,None,None,no_canonical,False,False
2,Cutaneous anaplastic large cell lymphoma,None,None,None,no_canonical,False,False
3,Disease,None,None,None,no_canonical,False,False
4,Fibroblast growth factor receptor 2-related de...,None,None,None,no_canonical,False,False
5,Gastrointestinal cancer,None,None,None,no_canonical,False,False
6,Hutchenreuter-TP53 syndrome,None,None,None,no_canonical,False,False
7,Large cell lymphoma,None,None,None,no_canonical,False,False
8,Multiple types of cancer,None,None,None,no_canonical,False,False
9,Neoplasms,None,None,None,no_canonical,False,False
10,Pediatric low-grade glioma,None,None,None,no_canonical,False,False
11,Peripheral nerve sheath tumor,None,None,None,no_canonical,False,False
12,Skeletal dysplasias,None,None,None,no_canonical,False,False
13,Tumorigenesis,None,None,None,no_canonical,False,False
14,bao gồm cả các gen liên quan đến hội chứng ung...,None,None,None,no_canonical,False,False
15,melanocytic nevi,None,None,None,no_canonical,False,False
16,melanocytic tumors,None,None,None,no_canonical,False,False
17,microsatellite instability-high cancer,None,None,None,no_canonical,False,False
18,microsatellite instability-high solid tumors,None,None,None,no_canonical,False,False
19,primary dysmenorrhea,None,None,None,no_canonical,False,False
20,primary mediastinal large B-cell lymphoma,None,None,None,no_canonical,False,False
21,primary mediastinal large b-cell lymphoma,None,None,None,no_canonical,False,False
22,tumor mutational burden-high solid tumors,None,None,None,no_canonical,False,False

In [18]:
# disease_canonical_audit_df

In [19]:
df_disease[df_disease["source"]=='Llama']

                                          disease_name     disease_id source
11                                  Appendiceal cancer  MONDO_0001235  Llama
36                           Co-arctation of the aorta    EFO_1001267  Llama
40                                Colorectal Neoplasms    EFO_1001951  Llama
74                              HER2-low breast cancer    EFO_0000305  Llama
75                             HER2-mutant lung cancer    EFO_0001071  Llama
76              HER2-mutant non-small cell lung cancer    EFO_0003060  Llama
77   HER2-positive advanced or metastatic breast ca...    EFO_0000305  Llama
78                         HER2-positive breast cancer    EFO_0000305  Llama
79                        HER2-positive gastric cancer    EFO_0003897  Llama
80              HER2-positive metastatic breast cancer    EFO_0000305  Llama
81   HER2-positive unresectable or metastatic breas...    EFO_0000305  Llama
105                              Large B-cell lymphoma    EFO_0000403  Llama
155                              Neuroendocrine tumors    EFO_1001901  Llama
225                               Thyroid gland tumors    EFO_0002892  Llama
244                              _renal cell carcinoma    EFO_0000681  Llama
285                      idiopathic ulcerative colitis    EFO_0000729  Llama
299  microsatellite instability-high colorectal cancer    EFO_1001951  Llama
305                             non-infectious uveitis    EFO_1001231  Llama
315                          pediatric crohn's disease    EFO_0000384  Llama
316            pediatric idiopathic ulcerative colitis    EFO_0000729  Llama

In [20]:
df_disease["source"].value_counts()

source
OpenTargets    304
Llama           20
Name: count, dtype: int64

In [21]:
df_disease

                                  disease_name     disease_id       source
0                               Achondroplasia  MONDO_0007037  OpenTargets
1                 Acute lymphoblastic leukemia    EFO_0000220  OpenTargets
2                       Acute myeloid leukemia    EFO_0000222  OpenTargets
3                               Adenocarcinoma    EFO_0000228  OpenTargets
4                   Alveolar soft part sarcoma    EFO_0007143  OpenTargets
..                                         ...            ...          ...
342  tumor mutational burden-high solid tumors           None         None
343                   type 2 diabetes mellitus  MONDO_0005148  OpenTargets
344                         ulcerative colitis    EFO_0000729  OpenTargets
345                       urothelial carcinoma    EFO_0008528  OpenTargets
346                                    uveitis    EFO_1001231  OpenTargets

[347 rows x 3 columns]

In [22]:
# df_disease[df_disease["source"]=="Llama"]

In [23]:
def compute_jaccard_from_run_dataframes(dct_result, df_gene, df_disease, df_drug):
    """
    Compute per-question cross-run Jaccard consistency after mapping entities to IDs.

    For each (model, question):
    - intersection: entries present in ALL valid runs
    - union: entries present in ANY valid run
    - jaccard = |intersection| / |union|

    All comparisons are CASE-INDEPENDENT and ID-based.

    Side effects:
    - Stores per-run mapped dataframe in:
        dct_result[model][question][run]['dataframe_id']

    Returns:
    - dct_jaccard[model][question] = {
          'jaccard': float,
          'n_valid_runs': int,
          'intersection': set[tuple],
          'union': set[tuple],
      }
    """

    dct_jaccard = {}

    # ------------------------------------------------------------------
    # Build deterministic one-to-one mapping tables
    # ------------------------------------------------------------------
    gene_map = (
        df_gene.assign(_gene_norm=df_gene["gene_name"].astype(str).str.strip().str.upper())
        [["_gene_norm", "gene_id"]]
        .dropna(subset=["gene_id"])
        .drop_duplicates("_gene_norm", keep="first")
    )

    disease_map = (
        df_disease.assign(_disease_norm=df_disease["disease_name"].astype(str).str.strip().str.upper())
        [["_disease_norm", "disease_id"]]
        .dropna(subset=["disease_id"])
        .drop_duplicates("_disease_norm", keep="first")
    )

    drug_map = (
        df_drug.assign(_drug_norm=df_drug["drug_name"].astype(str).str.strip().str.upper())
        [["_drug_norm", "drug_id"]]
        .dropna(subset=["drug_id"])
        .drop_duplicates("_drug_norm", keep="first")
    )

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    for model, model_payload in dct_result.items():
        dct_jaccard[model] = {}
        print(f"\nWorking for model: {model}")

        for question_key, runs_dict in model_payload.items():
            run_sets = {}

            for run_number, run_payload in runs_dict.items():
                df = run_payload.get("dataframe")

                # ---- basic validity ----
                if not isinstance(df, pd.DataFrame) or df.empty:
                    continue

                if "pathway_name" in df.columns:
                    continue

                work_df = df.copy()

                # print(work_df.head())

                final_cols = []

                # ---- gene ----
                if "gene_name" in work_df.columns:
                    work_df["_gene_norm"] = (
                        work_df["gene_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(gene_map, on="_gene_norm", how="left")
                    final_cols.append("gene_id")

                # ---- disease ----
                if "disease_name" in work_df.columns:
                    work_df["_disease_norm"] = (
                        work_df["disease_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(disease_map, on="_disease_norm", how="left")
                    final_cols.append("disease_id")

                # ---- drug ----
                if "drug_name" in work_df.columns:
                    work_df["_drug_norm"] = (
                        work_df["drug_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(drug_map, on="_drug_norm", how="left")
                    final_cols.append("drug_id")

                if not final_cols:
                    continue

                # ---- canonical ID dataframe ----
                id_df = (
                    work_df[final_cols]
                    .dropna(how="any")
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

                dct_result[model][question_key][run_number]["dataframe_id"] = id_df

                if id_df.empty:
                    continue

                # ---- CASE-INDEPENDENT tuple set ----
                run_set = {
                    tuple(str(v).strip().upper() for v in row)
                    for row in id_df.itertuples(index=False, name=None)
                }

                if run_set:
                    run_sets[run_number] = run_set

            # ------------------------------------------------------------------
            # Compute intersection / union
            # ------------------------------------------------------------------
            n_valid_runs = len(run_sets)

            if n_valid_runs < 2:
                print(
                    f"Not enough valid runs for '{question_key}' "
                    f"({n_valid_runs}/{len(runs_dict)}). Skipping."
                )
                continue

            sets = list(run_sets.values())
            intersection = set.intersection(*sets)
            union = set.union(*sets)

            if not union:
                print(f"Empty union for '{question_key}', skipping.")
                continue

            jaccard = len(intersection) / len(union)

            dct_jaccard[model][question_key] = {
                "jaccard": jaccard,
                "n_valid_runs": n_valid_runs,
                "intersection": intersection,
                "union": union,
            }

            print(
                f"'{question_key}': "
                f"J={jaccard:.4f}, "
                f"|∩|={len(intersection)}, "
                f"|∪|={len(union)}, "
                f"runs={n_valid_runs}"
            )

    return dct_jaccard


dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

Working for model: gemini-2.5-flash-lite
'Which diseases are associated with BRAF?': J=0.1579, |∩|=3, |∪|=19, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=0.1429, |∩|=11, |∪|=77, runs=5
'Which diseases are associated with CDK4?': J=0.1500, |∩|=3, |∪|=20, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=0.4583, |∩|=11, |∪|=24, runs=5
'Which genes are associated with ovarian cancer?': J=0.1277, |∩|=6, |∪|=47, runs=5
'What are the known targets of regorafenib?': J=0.0789, |∩|=3, |∪|=38, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
'Which genes are associated with fever (pyrexia)?': J=0.1667, |∩|=1, |∪|=6, runs=5
'Which diseases are treated with bevacizumab?': J=0.3846, |∩|=5, |∪|=13, runs=5
'What are the known targets of cabozantinib?': J=0.6667, |∩|=6, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=1.0000, |∩|=1, |∪|=1, runs=5
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=0.2143, |∩|=9, |∪|=42, runs=5
'Which genes are associated with epilepsy?': J=0.1429, |∩|=4, |∪|=28, runs=5
'Which diseases are treated with trastuzumab deruxtecan?': J=0.4000, |∩|=2, |∪|=5, runs=5
'Which genes are associated with Alzheimer’s disease?': J=0.1081, |∩|=4, |∪|=37, runs=5
'For which diseases is darolutamide used?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with renal cell carcinoma?': J=0.1000, |∩|=4, |∪|=40, runs=5
'Which diseases are associated with the KRAS gene?': J=0.0417, |∩|=2, |∪|=48, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=0.0526, |∩|=4, |∪|=76, runs=5
'Which diseases are treated with valdecoxib?': J=0.0000, |∩|=0, |∪|=5, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=3, |∪|=3, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.1905, |∩|=4, |∪|=21, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=0.1154, |∩|=3, |∪|=26, runs=5
'Which drugs are used to treat chronic myeloid leukemia?': J=0.8333, |∩|=5, |∪|=6, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=0.6154, |∩|=8, |∪|=13, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=0.3636, |∩|=8, |∪|=22, runs=5
'Which targets are acted on by imatinib?': J=0.3333, |∩|=4, |∪|=12, runs=5
'Which biological targets does sorafenib interact with?': J=0.5556, |∩|=5, |∪|=9, runs=5
'Which biological targets does tofacitinib interact with?': J=0.7500, |∩|=3, |∪|=4, runs=5
'Which drugs target EGFR?': J=0.3846, |∩|=5, |∪|=13, runs=5
'Which diseases are associated with TP53?': J=0.1373, |∩|=7, |∪|=51, runs=5
'Which diseases are associated with FGFR2?': J=0.1364, |∩|=6, |∪|=44, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with breast cancer?': J=0.0784, |∩|=4, |∪|=51, runs=5
'Which genes are associated with colorectal cancer?': J=0.0273, |∩|=5, |∪|=183, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which drugs are used to treat TNBC?': J=0.0435, |∩|=1, |∪|=23, runs=5
'Which diseases are treated with metformin?': J=0.3333, |∩|=1, |∪|=3, runs=5
'Which diseases are treated with adalimumab?': J=0.8000, |∩|=8, |∪|=10, runs=5
'For which diseases is pembrolizumab used?': J=0.6667, |∩|=10, |∪|=15, runs=5
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which diseases are treated with nivolumab?': J=0.3529, |∩|=6, |∪|=17, runs=5
'Which genes are associated with multiple sclerosis?': J=0.0204, |∩|=4, |∪|=196, runs=5
'Which genes are associated with rheumatoid arthritis?': J=0.0164, |∩|=1, |∪|=61, runs=5
'What are the known targets of abatacept?': J=0.3333, |∩|=1, |∪|=3, runs=5
'Which genes are associated with lung cancer?': J=0.1887, |∩|=10, |∪|=53, runs=5
'What are the known targets of ponatinib?': J=0.0000, |∩|=0, |∪|=13, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.1429, |∩|=1, |∪|=7, runs=5
'Which genes are associated with autism spectrum disorder?': J=0.0455, |∩|=2, |∪|=44, runs=5
'Which diseases are associated with the ROS1 gene?': J=0.3333, |∩|=1, |∪|=3, runs=5
'Which diseases are associated with the ALK gene?': J=0.0345, |∩|=4, |∪|=116, runs=5
'Which diseases are associated with the EGFR gene?': J=0.0000, |∩|=0, |∪|=12, runs=5
'Which genes are associated with psoriasis?': J=0.0175, |∩|=1, |∪|=57, runs=5
'Which genes are associated with ulcerative colitis?': J=0.0217, |∩|=1, |∪|=46, runs=5
'Which genes are associated with hepatitis C?': J=0.0000, |∩|=0, |∪|=4, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=0.0150, |∩|=2, |∪|=133, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=0.4444, |∩|=4, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
'Which drugs target CD19?': J=0.0000, |∩|=0, |∪|=14, runs=5
'Which drugs target CTLA4?': J=0.5000, |∩|=1, |∪|=2, runs=5
'Which genes are associated with tuberculosis?': J=0.0152, |∩|=1, |∪|=66, runs=5
'What drugs are used to treat rickets?': J=0.4000, |∩|=2, |∪|=5, runs=5

In [24]:
# Run Jaccard consistency computation across runs after ID grounding.
dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

# Flatten into a quick summary table for inspection.
rows = [
    {
        "model": model,
        "question": question,
        "jaccard": payload["jaccard"],
        "n_valid_runs": payload["n_valid_runs"],
        "intersection_size": len(payload["intersection"]),
        "union_size": len(payload["union"]),
    }
    for model, qmap in dct_jaccard.items()
    for question, payload in qmap.items()
]

jaccard_summary = pd.DataFrame(rows)
if jaccard_summary.empty:
    print("No valid Jaccard entries were produced. Check input runs and validation filters.")
else:
    display(jaccard_summary.sort_values(["model", "jaccard"], ascending=[True, False]).head(20))

Working for model: gemini-2.5-flash-lite
'Which diseases are associated with BRAF?': J=0.1579, |∩|=3, |∪|=19, runs=5
'Which genes are associated with amyotrophic lateral sclerosis?': J=0.1429, |∩|=11, |∪|=77, runs=5
'Which diseases are associated with CDK4?': J=0.1500, |∩|=3, |∪|=20, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=0.4583, |∩|=11, |∪|=24, runs=5
'Which genes are associated with ovarian cancer?': J=0.1277, |∩|=6, |∪|=47, runs=5
'What are the known targets of regorafenib?': J=0.0789, |∩|=3, |∪|=38, runs=5
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
'Which genes are associated with fever (pyrexia)?': J=0.1667, |∩|=1, |∪|=6, runs=5
'Which diseases are treated with bevacizumab?': J=0.3846, |∩|=5, |∪|=13, runs=5
'What are the known targets of cabozantinib?': J=0.6667, |∩|=6, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
'Which diseases are associated with the NPM1 gene?': J=1.0000, |∩|=1, |∪|=1, runs=5
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=0.2143, |∩|=9, |∪|=42, runs=5
'Which genes are associated with epilepsy?': J=0.1429, |∩|=4, |∪|=28, runs=5
'Which diseases are treated with trastuzumab deruxtecan?': J=0.4000, |∩|=2, |∪|=5, runs=5
'Which genes are associated with Alzheimer’s disease?': J=0.1081, |∩|=4, |∪|=37, runs=5
'For which diseases is darolutamide used?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with renal cell carcinoma?': J=0.1000, |∩|=4, |∪|=40, runs=5
'Which diseases are associated with the KRAS gene?': J=0.0417, |∩|=2, |∪|=48, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=0.0526, |∩|=4, |∪|=76, runs=5
'Which diseases are treated with valdecoxib?': J=0.0000, |∩|=0, |∪|=5, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=3, |∪|=3, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.1905, |∩|=4, |∪|=21, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=0.1154, |∩|=3, |∪|=26, runs=5
'Which drugs are used to treat chronic myeloid leukemia?': J=0.8333, |∩|=5, |∪|=6, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=0.6154, |∩|=8, |∪|=13, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=0.3636, |∩|=8, |∪|=22, runs=5
'Which targets are acted on by imatinib?': J=0.3333, |∩|=4, |∪|=12, runs=5
'Which biological targets does sorafenib interact with?': J=0.5556, |∩|=5, |∪|=9, runs=5
'Which biological targets does tofacitinib interact with?': J=0.7500, |∩|=3, |∪|=4, runs=5
'Which drugs target EGFR?': J=0.3846, |∩|=5, |∪|=13, runs=5
'Which diseases are associated with TP53?': J=0.1373, |∩|=7, |∪|=51, runs=5
'Which diseases are associated with FGFR2?': J=0.1364, |∩|=6, |∪|=44, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with breast cancer?': J=0.0784, |∩|=4, |∪|=51, runs=5
'Which genes are associated with colorectal cancer?': J=0.0273, |∩|=5, |∪|=183, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which drugs are used to treat TNBC?': J=0.0435, |∩|=1, |∪|=23, runs=5
'Which diseases are treated with metformin?': J=0.3333, |∩|=1, |∪|=3, runs=5
'Which diseases are treated with adalimumab?': J=0.8000, |∩|=8, |∪|=10, runs=5
'For which diseases is pembrolizumab used?': J=0.6667, |∩|=10, |∪|=15, runs=5
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which diseases are treated with nivolumab?': J=0.3529, |∩|=6, |∪|=17, runs=5
'Which genes are associated with multiple sclerosis?': J=0.0204, |∩|=4, |∪|=196, runs=5
'Which genes are associated with rheumatoid arthritis?': J=0.0164, |∩|=1, |∪|=61, runs=5
'What are the known targets of abatacept?': J=0.3333, |∩|=1, |∪|=3, runs=5
'Which genes are associated with lung cancer?': J=0.1887, |∩|=10, |∪|=53, runs=5
'What are the known targets of ponatinib?': J=0.0000, |∩|=0, |∪|=13, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.1429, |∩|=1, |∪|=7, runs=5
'Which genes are associated with autism spectrum disorder?': J=0.0455, |∩|=2, |∪|=44, runs=5
'Which diseases are associated with the ROS1 gene?': J=0.3333, |∩|=1, |∪|=3, runs=5
'Which diseases are associated with the ALK gene?': J=0.0345, |∩|=4, |∪|=116, runs=5
'Which diseases are associated with the EGFR gene?': J=0.0000, |∩|=0, |∪|=12, runs=5
'Which genes are associated with psoriasis?': J=0.0175, |∩|=1, |∪|=57, runs=5
'Which genes are associated with ulcerative colitis?': J=0.0217, |∩|=1, |∪|=46, runs=5
'Which genes are associated with hepatitis C?': J=0.0000, |∩|=0, |∪|=4, runs=5
'Which genes are associated with Hodgkin lymphoma?': J=0.0150, |∩|=2, |∪|=133, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=0.4444, |∩|=4, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
'Which drugs target CD19?': J=0.0000, |∩|=0, |∪|=14, runs=5
'Which drugs target CTLA4?': J=0.5000, |∩|=1, |∪|=2, runs=5
'Which genes are associated with tuberculosis?': J=0.0152, |∩|=1, |∪|=66, runs=5
'What drugs are used to treat rickets?': J=0.4000, |∩|=2, |∪|=5, runs=5

,model,question,jaccard,n_valid_runs,intersection_size,union_size
9,gemini-2.5-flash-lite,Which diseases are associated with the NPM1 gene?,1.000000,5,1,1
14,gemini-2.5-flash-lite,For which diseases is darolutamide used?,1.000000,5,1,1
19,gemini-2.5-flash-lite,What are the known targets of vandetanib?,1.000000,5,3,3
31,gemini-2.5-flash-lite,Which diseases are associated with HTT?,1.000000,5,1,1
34,gemini-2.5-flash-lite,Which genes are associated with cystic fibrosis?,1.000000,5,1,1
39,gemini-2.5-flash-lite,Which diseases are treated with sorafenib?,1.000000,5,3,3
22,gemini-2.5-flash-lite,Which drugs are used to treat chronic myeloid ...,0.833333,5,5,6
37,gemini-2.5-flash-lite,Which diseases are treated with adalimumab?,0.800000,5,8,10
27,gemini-2.5-flash-lite,Which biological targets does tofacitinib inte...,0.750000,5,3,4
8,gemini-2.5-flash-lite,What are the known targets of cabozantinib?,0.666667,5,6,9
38,gemini-2.5-flash-lite,For which diseases is pembrolizumab used?,0.666667,5,10,15
23,gemini-2.5-flash-lite,Which drugs are used to treat Parkinson’s dise...,0.615385,5,8,13
26,gemini-2.5-flash-lite,Which biological targets does sorafenib intera...,0.555556,5,5,9
57,gemini-2.5-flash-lite,Which drugs target CTLA4?,0.500000,5,1,2
3,gemini-2.5-flash-lite,Which drugs are used to treat rheumatoid arthr...,0.458333,5,11,24
55,gemini-2.5-flash-lite,Which drugs target ERBB2?,0.444444,5,4,9
12,gemini-2.5-flash-lite,Which diseases are treated with trastuzumab de...,0.400000,5,2,5
59,gemini-2.5-flash-lite,What drugs are used to treat rickets?,0.400000,5,2,5
7,gemini-2.5-flash-lite,Which diseases are treated with bevacizumab?,0.384615,5,5,13
28,gemini-2.5-flash-lite,Which drugs target EGFR?,0.384615,5,5,13

In [25]:
# Persist enriched run payloads with dataframe_id attached for each run.
with open("Gemini_same_question_response_with_id.pkl", "wb") as f:
    pickle.dump(dct_result, f)