In [2]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from opentarget_utility import retrieve_opentarget

In [3]:
model = "OpenTargets"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [3]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: Retrieved 1558 diseases for target BRAF.
----------------------------------------
Entries retrieved: 1558

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000157764,BRAF,MONDO_0015280,cardiofaciocutaneous syndrome,0.877319

 Run 1 completed | rows=1558 | latency=16.693s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: Retrieved 1558 diseases for target BRAF.
----------------------------------------
Entries retrieved: 1558

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000157764,BRAF,MONDO_0015280,cardiofaciocutaneous syndrome,0.877319

 Run 2 completed | rows=1558 | latency=12.605s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: Retrieved 1558 diseases for target BRAF.
----------------------------------------
Entries retrieved: 1558

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000157764,BRAF,MONDO_0015280,cardiofaciocutaneous syndrome,0.877319

 Run 3 completed | rows=1558 | latency=17.092s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: Retrieved 1558 diseases for target BRAF.
----------------------------------------
Entries retrieved: 1558

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000157764,BRAF,MONDO_0015280,cardiofaciocutaneous syndrome,0.877319

 Run 4 completed | rows=1558 | latency=12.624s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: Retrieved 1558 diseases for target BRAF.
----------------------------------------
Entries retrieved: 1558

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000157764,BRAF,MONDO_0015280,cardiofaciocutaneous syndrome,0.877319

 Run 5 completed | rows=1558 | latency=14.049s
------------------------------------------------------------


## Question 2

**Which genes are associated with amyotrophic lateral sclerosis?**

In [4]:

question = 'Which genes are associated with amyotrophic lateral sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 1492 targets for disease amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 1492

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004976,amyotrophic lateral sclerosis,ENSG00000142168,SOD1,superoxide dismutase 1,0.883359

 Run 1 completed | rows=1492 | latency=14.693s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 1492 targets for disease amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 1492

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004976,amyotrophic lateral sclerosis,ENSG00000142168,SOD1,superoxide dismutase 1,0.883359

 Run 2 completed | rows=1492 | latency=15.652s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 1492 targets for disease amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 1492

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004976,amyotrophic lateral sclerosis,ENSG00000142168,SOD1,superoxide dismutase 1,0.883359

 Run 3 completed | rows=1492 | latency=16.723s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 1492 targets for disease amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 1492

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004976,amyotrophic lateral sclerosis,ENSG00000142168,SOD1,superoxide dismutase 1,0.883359

 Run 4 completed | rows=1492 | latency=12.795s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 1492 targets for disease amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 1492

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004976,amyotrophic lateral sclerosis,ENSG00000142168,SOD1,superoxide dismutase 1,0.883359

 Run 5 completed | rows=1492 | latency=14.046s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [5]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: Retrieved 1136 diseases for target CDK4.
----------------------------------------
Entries retrieved: 1136

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000135446,CDK4,MONDO_0012183,"melanoma, cutaneous malignant, susceptibility ...",0.71412

 Run 1 completed | rows=1136 | latency=18.627s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: Retrieved 1136 diseases for target CDK4.
----------------------------------------
Entries retrieved: 1136

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000135446,CDK4,MONDO_0012183,"melanoma, cutaneous malignant, susceptibility ...",0.71412

 Run 2 completed | rows=1136 | latency=12.640s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: Retrieved 1136 diseases for target CDK4.
----------------------------------------
Entries retrieved: 1136

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000135446,CDK4,MONDO_0012183,"melanoma, cutaneous malignant, susceptibility ...",0.71412

 Run 3 completed | rows=1136 | latency=12.648s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: Retrieved 1136 diseases for target CDK4.
----------------------------------------
Entries retrieved: 1136

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000135446,CDK4,MONDO_0012183,"melanoma, cutaneous malignant, susceptibility ...",0.71412

 Run 4 completed | rows=1136 | latency=11.829s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: No resolved target found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: The system aimed to identify specific disease–drug relationships based on a user query. However, since no steps are recorded in the execution log, there is no detailed information on how the data was processed or filtered. This suggests that no data retrieval or filtering steps occurred or that the log is incomplete. As a result, there is no information available about the number of records retrieved or filtered.
----------------------------------------
[target_tool]: The query seems to aim at retrieving information related to disease–drug relationships, filtering by specific diseases, drugs, and mechanisms of action, and including pathway information.
[target_tool]: Since the execution log provided contains no steps, the process cannot be described in detail. It appears that no operations were carried out, or the log was not recorded. Therefore, no filters or retrievals were applied to narrow down the data, and no results were obtained.
[target_tool]: In summary, with no steps executed, there is no result set to report or analyze.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[target_tool]: Retrieved 1136 diseases for target CDK4.
----------------------------------------
Entries retrieved: 1136

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000135446,CDK4,MONDO_0012183,"melanoma, cutaneous malignant, susceptibility ...",0.71412

 Run 5 completed | rows=1136 | latency=13.712s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [6]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target JAK2.
[target_tool]: The first step involved retrieving pathway information associated with JAK2. This process resulted in 38 pathways being identified, although the initial number of pathways before retrieval is not specified. No further reduction or filtering was applied in this step, as only the retrieval of pathway data was performed.
[target_tool]: In summary, 38 pathways linked to JAK2 were successfully retrieved through this step.
----------------------------------------
Entries retrieved: 38

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 1 completed | rows=38 | latency=17.292s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target JAK2. The first step involved retrieving pathways associated with this target, resulting in 38 pathways. This step provided the relevant biological pathways connected to JAK2 for further analysis or filtering. The final result from this step included 38 pathways.
----------------------------------------
Entries retrieved: 38

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 2 completed | rows=38 | latency=17.463s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aims to identify relevant pathways associated with the target gene JAK2.
[target_tool]: The process began with retrieving pathways related to JAK2, resulting in 38 pathways being identified. Since no previous number of pathways is provided, the step focused on gathering this pathway information without further filtering.
[target_tool]: In summary, the final step retrieved 38 pathways linked to JAK2, providing the pathway context for further analysis.
----------------------------------------
Entries retrieved: 38

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 3 completed | rows=38 | latency=12.948s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the biological pathways associated with the target JAK2.
[target_tool]: The first step involved retrieving pathways for this target, resulting in a total of 38 pathways. Since this was the initial retrieval step, there was no previous number of pathways to compare with.
[target_tool]: In summary, a total of 38 pathways related to JAK2 were identified through this step.
----------------------------------------
Entries retrieved: 38

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 4 completed | rows=38 | latency=15.030s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify relevant pathways associated with the target JAK2.
[target_tool]: The first step involved retrieving pathways linked to JAK2. This process resulted in 38 pathways being identified, expanding the set of potential biological routes connected to the target. Since the log does not specify the number of pathways before retrieval, we only know that after this step, 38 pathways were associated with JAK2.
[target_tool]: There are no subsequent filtering steps or reductions shown in this log entry, so the pathway retrieval is the main focus here.
[target_tool]: In total, 38 pathways related to JAK2 were obtained through this pathway retrieval step.
----------------------------------------
Entries retrieved: 38

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 5 completed | rows=38 | latency=15.166s
------------------------------------------------------------


## Question 5

**Which drugs are used to treat rheumatoid arthritis?**

In [7]:

question = 'Which drugs are used to treat rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aims to identify associations related to rheumatoid arthritis. First, the system retrieved known disease–drug associations linked to rheumatoid arthritis, resulting in 1,365 entries. Next, it performed a deduplication process to remove duplicate records, which reduced the number of entries from 1,365 to 797. In total, this process narrowed down the initial set of associations to a more refined list of 797 unique entries related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 797

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201570,ANAKINRA,EFO_0000685,rheumatoid arthritis,4.0,Completed,Protein,EFO_0000685,rheumatoid arthritis

 Run 1 completed | rows=797 | latency=21.018s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aimed to explore disease–drug associations related to rheumatoid arthritis.
[disease_tool]: Initially, the system retrieved known disease associations specifically for rheumatoid arthritis, resulting in a total of 1,365 entries. This step gathered all potential links between the disease and various drugs or related factors.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from this set. This process reduced the number of entries from 1,365 down to 797, ensuring that each association was unique and no repeated records remained.
[disease_tool]: In summary, the final result contains 797 unique entries related to rheumatoid arthritis after filtering out duplicates.
----------------------------------------
Entries retrieved: 797

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201570,ANAKINRA,EFO_0000685,rheumatoid arthritis,4.0,Completed,Protein,EFO_0000685,rheumatoid arthritis

 Run 2 completed | rows=797 | latency=16.018s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: This query aimed to retrieve information related to rheumatoid arthritis. First, the system retrieved a set of known disease–drug associations related to rheumatoid arthritis, resulting in 1,365 entries. Next, duplicate entries within this set were removed, reducing the number of rows from 1,365 to 797. In summary, the final result contains 797 unique entries associated with rheumatoid arthritis.
----------------------------------------
Entries retrieved: 797

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201570,ANAKINRA,EFO_0000685,rheumatoid arthritis,4.0,Completed,Protein,EFO_0000685,rheumatoid arthritis

 Run 3 completed | rows=797 | latency=15.732s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The intent of the query was to identify disease associations related to rheumatoid arthritis.
[disease_tool]: First, the system retrieved known disease–drug associations specifically for rheumatoid arthritis, which resulted in an initial set of 1365 entries. Next, to ensure the data was unique and free of redundancies, the system removed duplicate rows from this set. This deduplication step reduced the number of entries from 1365 to 797, leaving a refined collection of unique disease association data. In total, the process ended with 797 entries after filtering for duplicates.
----------------------------------------
Entries retrieved: 797

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201570,ANAKINRA,EFO_0000685,rheumatoid arthritis,4.0,Completed,Protein,EFO_0000685,rheumatoid arthritis

 Run 4 completed | rows=797 | latency=19.315s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aimed to find disease–drug associations related to rheumatoid arthritis.
[disease_tool]: First, the system retrieved all known disease–drug associations for rheumatoid arthritis, resulting in 1,365 entries. This step gathered the relevant data connections from the database.
[disease_tool]: Next, duplicate records within this set were identified and removed, reducing the number of entries from 1,365 to 797. This deduplication ensures that only unique associations remained for further analysis.
[disease_tool]: In total, the process started with a broad collection of 1,365 potential associations and ended with 797 unique entries related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 797

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201570,ANAKINRA,EFO_0000685,rheumatoid arthritis,4.0,Completed,Protein,EFO_0000685,rheumatoid arthritis

 Run 5 completed | rows=797 | latency=16.378s
------------------------------------------------------------


## Question 6

**Which genes are associated with ovarian cancer?**

In [8]:

question = 'Which genes are associated with ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
[disease_tool]: Retrieved 8979 targets for disease ovarian cancer.
----------------------------------------
Entries retrieved: 8979

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008170,ovarian cancer,ENSG00000012048,BRCA1,BRCA1 DNA repair associated,0.880854

 Run 1 completed | rows=8979 | latency=28.223s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
[disease_tool]: Retrieved 8979 targets for disease ovarian cancer.
----------------------------------------
Entries retrieved: 8979

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008170,ovarian cancer,ENSG00000012048,BRCA1,BRCA1 DNA repair associated,0.880854

 Run 2 completed | rows=8979 | latency=19.936s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
[disease_tool]: Retrieved 8979 targets for disease ovarian cancer.
----------------------------------------
Entries retrieved: 8979

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008170,ovarian cancer,ENSG00000012048,BRCA1,BRCA1 DNA repair associated,0.880854

 Run 3 completed | rows=8979 | latency=17.374s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
[disease_tool]: Retrieved 8979 targets for disease ovarian cancer.
----------------------------------------
Entries retrieved: 8979

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008170,ovarian cancer,ENSG00000012048,BRCA1,BRCA1 DNA repair associated,0.880854

 Run 4 completed | rows=8979 | latency=19.254s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
[disease_tool]: Retrieved 8979 targets for disease ovarian cancer.
----------------------------------------
Entries retrieved: 8979

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008170,ovarian cancer,ENSG00000012048,BRCA1,BRCA1 DNA repair associated,0.880854

 Run 5 completed | rows=8979 | latency=17.899s
------------------------------------------------------------


## Question 7

**What are the known targets of regorafenib?**

In [9]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The query aims to identify drugs associated with a specific target, regorafenib.
[drug_tool]: The first step involved retrieving known associations between drugs and diseases related to regorafenib. This retrieved a total of 2,286 rows of data that potentially link regorafenib to various disease, gene, or pathway entries.
[drug_tool]: Next, the process applied deduplication to remove duplicate records from these associations. This filtering greatly reduced the dataset from 2,286 entries to just 18 unique association records.
[drug_tool]: In summary, after retrieving all potential known associations, only 18 unique entries remained for consideration, providing a more concise set of data related to regorafenib.
----------------------------------------
Entries retrieved: 18

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL1946170,REGORAFENIB,Vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 1 completed | rows=18 | latency=16.731s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The goal of the query was to retrieve drug associations related to regorafenib.
[drug_tool]: First, the system retrieved the known associations between drugs and diseases for regorafenib, resulting in 2,286 entries.
[drug_tool]: Next, the system removed duplicate entries from this data. This filtering step reduced the number of associations from 2,286 to 18.
[drug_tool]: In total, the final result consists of 18 unique drug association entries related to regorafenib.
----------------------------------------
Entries retrieved: 18

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL1946170,REGORAFENIB,Vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 2 completed | rows=18 | latency=16.750s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The query's goal was to find relevant drug associations for the drug regorafenib.
[drug_tool]: First, the system retrieved a set of known disease–drug associations related to regorafenib, resulting in 2,286 rows.
[drug_tool]: Next, to refine the data, duplicates were removed, reducing the number of entries from 2,286 to 18.
[drug_tool]: Overall, after applying association retrieval and deduplication, the final result consisted of 18 unique records related to regorafenib.
----------------------------------------
Entries retrieved: 18

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL1946170,REGORAFENIB,Vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 3 completed | rows=18 | latency=14.537s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The system was tasked with retrieving information related to drugs associated with the chemical regorafenib.
[drug_tool]: First, the system retrieved all known associations between drugs and diseases related to regorafenib, resulting in a total of 2,286 entries. This initial step gathered a broad set of data without applying any filters.
[drug_tool]: Next, the system performed deduplication to remove duplicate entries from the retrieved data. This process reduced the number of records significantly from 2,286 to 18, leaving only unique association records.
[drug_tool]: In summary, after retrieving all associations and removing duplicates, the final dataset contained 18 unique entries related to regorafenib.
----------------------------------------
Entries retrieved: 18

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL1946170,REGORAFENIB,Vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 4 completed | rows=18 | latency=17.277s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to regorafenib.
[drug_tool]: First, the system retrieved known drug associations for regorafenib, resulting in 2,286 entries. This retrieval provided the initial dataset of potential associations.
[drug_tool]: Next, the system removed duplicate records from this set, reducing the number of entries significantly from 2,286 to 18. This step ensured that each association was unique, eliminating redundancy.
[drug_tool]: In conclusion, after these steps, the total number of unique drug association entries related to regorafenib was 18.
----------------------------------------
Entries retrieved: 18

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL1946170,REGORAFENIB,Vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 5 completed | rows=18 | latency=15.518s
------------------------------------------------------------


## Question 8

**Which pathways are associated with the STAT3 gene?**

In [10]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify biological pathways related to the target STAT3.
[target_tool]: The first step involved retrieving pathways associated with STAT3, resulting in 39 pathways being identified from an initial, unspecified number of pathways. No specific number of pathways before retrieval was provided.
[target_tool]: This process only included retrieving pathway information, and further filtering or reduction steps were not included in this part of the log.
[target_tool]: Overall, the final result after this step is the set of 39 pathways related to STAT3.
----------------------------------------
Entries retrieved: 39

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 1 completed | rows=39 | latency=16.308s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify pathways involving the target STAT3. First, the system retrieved pathway information related to STAT3, which resulted in 39 pathways. This step provided a base set of pathway data associated with the target. No further filtering or reduction steps are indicated, so the final number of pathways remaining after this step is 39.
----------------------------------------
Entries retrieved: 39

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 2 completed | rows=39 | latency=15.461s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve pathways related to the target STAT3.
[target_tool]: The first step involved retrieving pathways associated with this target, which resulted in 39 pathways. This step did not specify a prior number of pathways, but it produced 39 pathways linked to the target.
[target_tool]: Since only one step is detailed, there is no further filtering or deduplication described in this log. The process successfully retrieved 39 pathways relevant to STAT3.
----------------------------------------
Entries retrieved: 39

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 3 completed | rows=39 | latency=15.209s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to find information related to the target gene STAT3. The first step involved retrieving pathway data for STAT3, which resulted in 39 pathways being identified. This initial retrieval gathered the relevant biological pathways associated with the target gene. Since this step focused solely on retrieving pathway information, the number of entries increased from none to 39. The final step involved these pathways, and the number of pathways associated with STAT3 remained at 39.
----------------------------------------
Entries retrieved: 39

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 4 completed | rows=39 | latency=15.315s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The purpose of the query was to explore pathways related to the target protein STAT3. The process began with retrieving pathway information associated with STAT3, which resulted in a total of 39 pathways. Since only pathway retrieval was recorded, no filters or further steps were applied beyond this stage. In the end, the system identified 39 pathways linked to the target STAT3.
----------------------------------------
Entries retrieved: 39

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 5 completed | rows=39 | latency=14.380s
------------------------------------------------------------


## Question 9

**Which genes are associated with fever (pyrexia)?**

In [11]:

question = 'Which genes are associated with fever (pyrexia)?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
[disease_tool]: Retrieved 951 targets for disease pyrexia.
----------------------------------------
Entries retrieved: 951

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,HP_0001945,Fever,ENSG00000073756,PTGS2,prostaglandin-endoperoxide synthase 2,0.608161

 Run 1 completed | rows=951 | latency=14.384s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
[disease_tool]: Retrieved 951 targets for disease fever.
----------------------------------------
Entries retrieved: 951

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,HP_0001945,Fever,ENSG00000073756,PTGS2,prostaglandin-endoperoxide synthase 2,0.608161

 Run 2 completed | rows=951 | latency=14.662s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
[disease_tool]: Retrieved 951 targets for disease fever.
----------------------------------------
Entries retrieved: 951

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,HP_0001945,Fever,ENSG00000073756,PTGS2,prostaglandin-endoperoxide synthase 2,0.608161

 Run 3 completed | rows=951 | latency=11.654s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
[disease_tool]: Retrieved 951 targets for disease fever.
----------------------------------------
Entries retrieved: 951

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,HP_0001945,Fever,ENSG00000073756,PTGS2,prostaglandin-endoperoxide synthase 2,0.608161

 Run 4 completed | rows=951 | latency=13.481s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
[disease_tool]: Retrieved 951 targets for disease fever.
----------------------------------------
Entries retrieved: 951

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,HP_0001945,Fever,ENSG00000073756,PTGS2,prostaglandin-endoperoxide synthase 2,0.608161

 Run 5 completed | rows=951 | latency=11.484s
------------------------------------------------------------


## Question 10

**Which diseases are treated with bevacizumab?**

In [12]:

question = 'Which diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug bevacizumab.
[drug_tool]: The first step retrieved known associations between bevacizumab and various diseases, resulting in a set of 857 records. This step established the initial pool of disease–drug relationships involving bevacizumab.
[drug_tool]: Since only the association retrieval step is shown, it indicates that the process started by gathering all known associations for bevacizumab without applying any further filters or mechanisms at this stage.
[drug_tool]: In summary, the initial retrieval yielded 857 records connecting bevacizumab to different diseases, forming the foundation for subsequent filtering or analysis.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,BEVACIZUMAB,MONDO_0005575,colorectal cancer,4.0,Completed,Vascular endothelial growth factor A inhibitor,"DailyMed, PubMed"

 Run 1 completed | rows=857 | latency=16.577s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve drug associations related to bevacizumab.
[drug_tool]: The first step involved retrieving all known relationships between drugs and diseases for bevacizumab. Before this retrieval, no specific data was selected. After the retrieval process, 857 associations were obtained, indicating the total number of drug association records related to bevacizumab found in the database.
[drug_tool]: This step set the foundation for further filtering by providing a comprehensive list of known drug associations for the specified drug.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,BEVACIZUMAB,MONDO_0005575,colorectal cancer,4.0,Completed,Vascular endothelial growth factor A inhibitor,"DailyMed, PubMed"

 Run 2 completed | rows=857 | latency=13.032s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aims to explore drug associations related to bevacizumab. First, the system retrieved known disease-drug associations for bevacizumab, resulting in 857 entries. No initial number of associations was specified, but after this step, there were 857 associations in the dataset.
[drug_tool]: Next, the system applied filters to narrow down the results based on specific diseases, drugs, mechanisms, and pathways, though only the initial association retrieval was detailed in the log. This process likely involved further filtering steps, but specific details or reductions are not provided under those steps in this log.
[drug_tool]: In conclusion, after the initial retrieval, the database contained 857 drug association entries related to bevacizumab.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,BEVACIZUMAB,MONDO_0005575,colorectal cancer,4.0,Completed,Vascular endothelial growth factor A inhibitor,"DailyMed, PubMed"

 Run 3 completed | rows=857 | latency=16.256s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aims to identify drug-disease associations related to bevacizumab.
[drug_tool]: First, the system retrieved the known disease–drug associations for bevacizumab. This initial retrieval resulted in 857 entries, which encompass various diseases linked to bevacizumab.
[drug_tool]: Since only one step is shown in the execution log, no further filtering or narrowing of results is detailed beyond this initial association retrieval.
[drug_tool]: In the end, the process produced a total of 857 entries related to bevacizumab.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,BEVACIZUMAB,MONDO_0005575,colorectal cancer,4.0,Completed,Vascular endothelial growth factor A inhibitor,"DailyMed, PubMed"

 Run 4 completed | rows=857 | latency=13.239s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug bevacizumab. The first step involved retrieving known disease–drug associations for bevacizumab. This retrieval resulted in 857 associations, providing a broad set of data on how this drug is connected to various diseases. Since this initial step did not specify any further filters or narrowing criteria, the total of 857 associations represents the full set obtained from the database at this stage. In summary, the search started with 857 associations related to bevacizumab, forming the base dataset for subsequent analysis or filtering.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,BEVACIZUMAB,MONDO_0005575,colorectal cancer,4.0,Completed,Vascular endothelial growth factor A inhibitor,"DailyMed, PubMed"

 Run 5 completed | rows=857 | latency=13.631s
------------------------------------------------------------


## Question 11

**What are the known targets of cabozantinib?**

In [13]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: This query aims to find information related to the drug cabozantinib.
[drug_tool]: The process began with the system retrieving known drug associations for cabozantinib, which initially returned 316 entries. This step gathered all associations linked to the drug without any filters applied yet.
[drug_tool]: Next, the system performed deduplication to remove duplicate entries from the retrieved data. As a result, only 2 unique records remained, after removing 314 duplicate entries.
[drug_tool]: In summary, the process started with 316 related associations and was refined down to 2 unique entries, providing a concise set of relevant and distinct data about cabozantinib.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,MET,CHEMBL2105717,CABOZANTINIB,Hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 1 completed | rows=2 | latency=15.079s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The goal of this query was to retrieve and refine information about drugs associated with a specific medication.
[drug_tool]: Initially, the system retrieved known associations for the drug cabozantinib, resulting in 316 entries. These entries represented different relationships or data points related to this drug.
[drug_tool]: Next, the system performed a deduplication process to remove any duplicate records. This step reduced the number of entries significantly from 316 down to 2, leaving only unique associations related to the drug.
[drug_tool]: In summary, the final result consists of 2 distinct and unique associations for cabozantinib after all filtering steps.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,MET,CHEMBL2105717,CABOZANTINIB,Hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 2 completed | rows=2 | latency=13.005s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The query aimed to find relationships involving the drug cabozantinib. First, the system retrieved known disease–drug associations related to cabozantinib, which resulted in 316 entries. Next, it removed duplicate records from these results to ensure each association was unique, reducing the total number of entries from 316 to just 2. In the end, only two unique associations involving cabozantinib remained after deduplication.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,MET,CHEMBL2105717,CABOZANTINIB,Hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 3 completed | rows=2 | latency=18.400s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The purpose of the query was to find specific information related to the drug cabozantinib.
[drug_tool]: First, the system retrieved known disease–drug associations for cabozantinib, resulting in a total of 316 associations.
[drug_tool]: Next, the system removed duplicate rows from this list, reducing the number of records significantly from 316 down to just 2 entries.
[drug_tool]: In summary, after filtering and removing duplicates, the final result consists of 2 unique associations related to cabozantinib.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,MET,CHEMBL2105717,CABOZANTINIB,Hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 4 completed | rows=2 | latency=12.603s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The intent of the query was to find associations related to the drug cabozantinib.
[drug_tool]: First, the system retrieved a list of known drug associations for cabozantinib, resulting in 316 entries. This step gathered all the relevant data available for this specific drug.
[drug_tool]: Next, the system performed deduplication to remove any duplicate records from the list. This process reduced the number of entries from 316 to 2, leaving only unique association records.
[drug_tool]: In summary, after these steps, the system identified 2 unique associations related to cabozantinib.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,MET,CHEMBL2105717,CABOZANTINIB,Hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 5 completed | rows=2 | latency=14.283s
------------------------------------------------------------


## Question 12

**Which pathways are associated with the TNF gene?**

In [14]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: This query aimed to retrieve information related to the biological target TNF. The first step involved retrieving pathways associated with TNF, resulting in 10 pathways being identified. Since this step was primarily about gathering pathway data, the number of pathways after retrieval was 10, with no prior count for comparison. In summary, the process concluded with 10 pathways linked to TNF being retrieved.
----------------------------------------
Entries retrieved: 10

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 1 completed | rows=10 | latency=14.741s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathways related to the target TNF.
[target_tool]: In the first step, the system retrieved pathway information associated with TNF, resulting in a total of 10 relevant pathways. No previous number of pathways was provided, but the retrieval process expanded the information to include these 10 pathways.
[target_tool]: Since only one step was recorded, the process concluded with 10 pathways linked to TNF being obtained.
----------------------------------------
Entries retrieved: 10

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 2 completed | rows=10 | latency=12.134s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The system started by retrieving pathways associated with the target, TNF. This step returned 10 pathways. Since this was the initial retrieval, there was no previous data to compare to, and no immediate reduction in the number of pathways occurred at this stage.
----------------------------------------
Entries retrieved: 10

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 3 completed | rows=10 | latency=12.286s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target TNF. The first step involved retrieving pathway information associated with TNF; this retrieval produced 10 pathways. Since only this step is documented, it indicates that the process focused on obtaining pathway data for the target. The total number of pathways retrieved after this step was 10.
----------------------------------------
Entries retrieved: 10

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 4 completed | rows=10 | latency=12.036s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target 'TNF'. In the first step, the system retrieved pathway information associated with this target. After this retrieval, 10 pathways were identified. Since there was no prior number of pathways listed, it is only clear that 10 pathways were obtained in this step, with no reduction explained from a previous number. The final result from this step is a list of 10 pathways linked to 'TNF'.
----------------------------------------
Entries retrieved: 10

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 5 completed | rows=10 | latency=13.333s
------------------------------------------------------------


## Question 13

**Which diseases are associated with the NPM1 gene?**

In [15]:

question = 'Which diseases are associated with the NPM1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
[target_tool]: Retrieved 664 diseases for target NPM1.
----------------------------------------
Entries retrieved: 664

           gene_id gene_name     disease_id disease_name  association_score
0  ENSG00000181163      NPM1  MONDO_0004992       cancer           0.708707

 Run 1 completed | rows=664 | latency=16.406s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
[target_tool]: Retrieved 664 diseases for target NPM1.
----------------------------------------
Entries retrieved: 664

           gene_id gene_name     disease_id disease_name  association_score
0  ENSG00000181163      NPM1  MONDO_0004992       cancer           0.708707

 Run 2 completed | rows=664 | latency=12.147s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
[target_tool]: Retrieved 664 diseases for target NPM1.
----------------------------------------
Entries retrieved: 664

           gene_id gene_name     disease_id disease_name  association_score
0  ENSG00000181163      NPM1  MONDO_0004992       cancer           0.708707

 Run 3 completed | rows=664 | latency=13.449s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
[target_tool]: Retrieved 664 diseases for target NPM1.
----------------------------------------
Entries retrieved: 664

           gene_id gene_name     disease_id disease_name  association_score
0  ENSG00000181163      NPM1  MONDO_0004992       cancer           0.708707

 Run 4 completed | rows=664 | latency=11.351s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
[target_tool]: Retrieved 664 diseases for target NPM1.
----------------------------------------
Entries retrieved: 664

           gene_id gene_name     disease_id disease_name  association_score
0  ENSG00000181163      NPM1  MONDO_0004992       cancer           0.708707

 Run 5 completed | rows=664 | latency=13.377s
------------------------------------------------------------


## Question 14

**Which pathways are associated with the CD19 gene?**

In [16]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The intent of the query was to retrieve information related to pathways associated with the target, CD19.
[target_tool]: The first step involved retrieving pathway information for CD19. This step resulted in 6 pathways being identified, but the number of pathways before retrieval was not specified.
[target_tool]: In summary, after retrieving pathways related to CD19, there were a total of 6 pathways identified.
----------------------------------------
Entries retrieved: 6

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 1 completed | rows=6 | latency=14.331s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target gene CD19 and its associated pathways.
[target_tool]: Initially, the system retrieved pathways related to CD19. This step resulted in 6 pathways being identified. Since this step was only retrieval, it did not reduce the number of entries but provided the pathway information associated with the target.
[target_tool]: In summary, the final outcome involved retrieving 6 pathways connected to CD19.
----------------------------------------
Entries retrieved: 6

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 2 completed | rows=6 | latency=15.335s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify pathways associated with the target CD19.
[target_tool]: Initially, the system retrieved pathway information related to CD19, resulting in 6 pathways. This step involved gathering relevant biological pathway data for the target.
[target_tool]: Since there was only one step in the execution log, it indicates that no further filtering or additional steps were performed.
[target_tool]: In the end, the process resulted in a total of 6 pathways associated with CD19.
----------------------------------------
Entries retrieved: 6

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 3 completed | rows=6 | latency=15.622s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify pathways associated with the target CD19.
[target_tool]: First, the system retrieved information about pathways linked to CD19; this resulted in 6 pathways being identified. Since this was a retrieval step, the number of pathways after the retrieval was 6.
[target_tool]: No further filtering steps or reductions are shown in the log, so the final result consists of these 6 pathways related to the target CD19.
----------------------------------------
Entries retrieved: 6

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 4 completed | rows=6 | latency=13.158s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target, CD19.
[target_tool]: The first step involved retrieving pathways associated with CD19, resulting in six pathways being identified. This step provided a set of pathway data linked to the target but did not further narrow down the results at this stage.
[target_tool]: Since no additional filters or steps are listed, the final result is the set of six pathways retrieved for CD19.
----------------------------------------
Entries retrieved: 6

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 5 completed | rows=6 | latency=14.477s
------------------------------------------------------------


## Question 15

**Which drugs are used to treat migraine?**

In [17]:

question = 'Which drugs are used to treat migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat migraine?
  Attempt 1/3
[disease_tool]: The goal of the query was to identify disease information related to migraine.
[disease_tool]: First, the system retrieved all known disease–drug associations related to migraine, which resulted in 1,226 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the total from 1,226 to 366 unique entries.
[disease_tool]: In summary, after applying the association retrieval and deduplication steps, the final result includes 366 unique data entries related to migraine.
----------------------------------------
Entries retrieved: 366

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1185,ZOLMITRIPTAN,MONDO_0005277,migraine disorder,4.0,NaN,Small molecule,MONDO_0005277,migraine disorder

 Run 1 completed | rows=366 | latency=19.277s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat migraine?
  Attempt 1/3
[disease_tool]: The query aims to identify relevant disease–drug associations related to migraine.
[disease_tool]: Initially, the system retrieved known disease associations for migraine, resulting in 1,226 records. This step gathered all potential connections between migraine and various drugs.
[disease_tool]: Next, the process applied a deduplication step to this data set. This filtering removed duplicate entries, reducing the total number of records from 1,226 to 366. This step ensured that each association was unique and non-redundant.
[disease_tool]: In summary, after these filtering steps, there are 366 distinct disease–drug association records related to migraine.
----------------------------------------
Entries retrieved: 366

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1185,ZOLMITRIPTAN,MONDO_0005277,migraine disorder,4.0,NaN,Small molecule,MONDO_0005277,migraine disorder

 Run 2 completed | rows=366 | latency=17.081s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat migraine?
  Attempt 1/3
[disease_tool]: The goal of this query was to retrieve associations related to migraine.
[disease_tool]: First, the system retrieved the known disease–drug associations for migraine, resulting in 1,226 entries.
[disease_tool]: Next, it removed duplicate records from this list, reducing the number of entries from 1,226 to 366. This step ensured that each association was unique and no duplicates were present in the final results.
[disease_tool]: In total, the process ended with 366 distinct disease–drug associations related to migraine.
----------------------------------------
Entries retrieved: 366

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1185,ZOLMITRIPTAN,MONDO_0005277,migraine disorder,4.0,NaN,Small molecule,MONDO_0005277,migraine disorder

 Run 3 completed | rows=366 | latency=19.752s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat migraine?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to migraines by analyzing associated diseases and drugs.
[disease_tool]: Initially, the system retrieved known disease–drug associations specifically related to migraines. This step brought back 1,226 entries corresponding to various disease associations related to that condition.
[disease_tool]: Next, the system performed a deduplication process to remove any duplicate records from the retrieved data. This step reduced the number of entries from 1,226 to 366, leaving only unique records.
[disease_tool]: In summary, after these steps, the result set was narrowed down to 366 distinct disease–drug associations related to migraines.
----------------------------------------
Entries retrieved: 366

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1185,ZOLMITRIPTAN,MONDO_0005277,migraine disorder,4.0,NaN,Small molecule,MONDO_0005277,migraine disorder

 Run 4 completed | rows=366 | latency=14.874s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat migraine?
  Attempt 1/3
[disease_tool]: This query is aimed at exploring the associations related to migraine, particularly focusing on disease–drug relationships.
[disease_tool]: First, the system retrieved known disease–drug associations specifically for migraine, resulting in a total of 1,226 entries. This step gathered all relevant relationship data related to the disease without applying any filters initially.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from this dataset. This process reduced the number of entries from 1,226 to 366, eliminating repetitions and ensuring a cleaner set of unique associations.
[disease_tool]: In the end, the resulting dataset contains 366 unique disease–drug association entries related to migraine, providing a more concise and non-redundant collection of relevant data.
----------------------------------------
Entries retrieved: 366

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1185,ZOLMITRIPTAN,MONDO_0005277,migraine disorder,4.0,NaN,Small molecule,MONDO_0005277,migraine disorder

 Run 5 completed | rows=366 | latency=14.750s
------------------------------------------------------------


## Question 16

**What drugs are used to treat rickets?**

In [12]:

question = 'What drugs are used to treat rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used to treat rickets?
  Attempt 1/3
[disease_tool]: The query aims to find information related to the disease 'rickets' by examining associated drugs, mechanisms, and pathways.
[disease_tool]: Initially, the system retrieved known disease–drug associations related to 'rickets.' This step resulted in 15 entries, which represented different drugs linked to the disease.
[disease_tool]: Next, duplicate entries were removed from these associations, reducing the number from 15 to 12. This deduplication process helped ensure that each association was unique, removing 3 duplicate records.
[disease_tool]: Finally, the process concluded with 12 distinct records related to 'rickets' after the association retrieval and deduplication steps.
----------------------------------------
Entries retrieved: 12

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3707326,BUROSUMAB,EFO_0005583,rickets,4.0,NaN,Antibody,EFO_1002027,osteomalacia

 Run 1 completed | rows=12 | latency=26.476s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used to treat rickets?
  Attempt 1/3
[disease_tool]: The query aims to identify associations related to rickets. Initially, the system retrieved known disease–drug associations for rickets. This retrieval process started with an unspecified number of entries and resulted in 15 rows after the association retrieval step. Next, the system performed deduplication to remove any duplicate records, reducing the total from 15 to 12 entries. This step ensured that only unique associations remained. The final result is a set of 12 unique disease–drug associations related to rickets.
----------------------------------------
Entries retrieved: 12

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3707326,BUROSUMAB,EFO_0005583,rickets,4.0,NaN,Antibody,EFO_1002027,osteomalacia

 Run 2 completed | rows=12 | latency=27.656s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used to treat rickets?
  Attempt 1/3
[disease_tool]: The query aimed to explore disease-drug associations related to rickets. First, the system retrieved known disease associations for rickets, resulting in 15 entries. These entries included various associations related to the disease. Next, the system removed duplicate records from this set, which reduced the number of entries from 15 to 12. In summary, after filtering out duplicates, there are 12 unique disease association records related to rickets.
----------------------------------------
Entries retrieved: 12

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3707326,BUROSUMAB,EFO_0005583,rickets,4.0,NaN,Antibody,EFO_1002027,osteomalacia

 Run 3 completed | rows=12 | latency=17.381s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used to treat rickets?
  Attempt 1/3
[disease_tool]: The query aimed to find specific information related to 'rickets.' The first step retrieved known disease–drug associations associated with 'rickets,' resulting in 15 entries. Next, duplicate records within these associations were removed, reducing the total from 15 to 12 entries. In summary, the final dataset contains 12 unique disease association records for 'rickets.'
----------------------------------------
Entries retrieved: 12

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3707326,BUROSUMAB,EFO_0005583,rickets,4.0,NaN,Antibody,EFO_1002027,osteomalacia

 Run 4 completed | rows=12 | latency=16.435s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used to treat rickets?
  Attempt 1/3
[disease_tool]: The goal of the query was to identify associations related to the disease rickets. First, the system retrieved known disease–drug associations specifically linked to rickets, resulting in 15 relevant entries. This initial retrieval provided the base set of data focused on this disease.
[disease_tool]: Next, the process involved removing duplicate records to ensure the data was unique. This deduplication step reduced the number of entries from 15 to 12, eliminating 3 duplicate rows.
[disease_tool]: In total, after these steps, the system retained 12 unique disease–drug association records related to rickets.
----------------------------------------
Entries retrieved: 12

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3707326,BUROSUMAB,EFO_0005583,rickets,4.0,NaN,Antibody,EFO_1002027,osteomalacia

 Run 5 completed | rows=12 | latency=19.200s
------------------------------------------------------------


## Question 17

**Which genes are associated with epilepsy?**

In [19]:

question = 'Which genes are associated with epilepsy?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with epilepsy?
  Attempt 1/3
[disease_tool]: Retrieved 7140 targets for disease epilepsy.
----------------------------------------
Entries retrieved: 7140

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000474,epilepsy,ENSG00000144285,SCN1A,sodium voltage-gated channel alpha subunit 1,0.926469

 Run 1 completed | rows=7140 | latency=23.726s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with epilepsy?
  Attempt 1/3
[disease_tool]: Retrieved 7140 targets for disease epilepsy.
----------------------------------------
Entries retrieved: 7140

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000474,epilepsy,ENSG00000144285,SCN1A,sodium voltage-gated channel alpha subunit 1,0.926469

 Run 2 completed | rows=7140 | latency=19.120s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with epilepsy?
  Attempt 1/3
[disease_tool]: Retrieved 7140 targets for disease epilepsy.
----------------------------------------
Entries retrieved: 7140

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000474,epilepsy,ENSG00000144285,SCN1A,sodium voltage-gated channel alpha subunit 1,0.926469

 Run 3 completed | rows=7140 | latency=18.592s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with epilepsy?
  Attempt 1/3
[disease_tool]: Retrieved 7140 targets for disease epilepsy.
----------------------------------------
Entries retrieved: 7140

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000474,epilepsy,ENSG00000144285,SCN1A,sodium voltage-gated channel alpha subunit 1,0.926469

 Run 4 completed | rows=7140 | latency=15.619s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with epilepsy?
  Attempt 1/3
[disease_tool]: Retrieved 7140 targets for disease epilepsy.
----------------------------------------
Entries retrieved: 7140

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000474,epilepsy,ENSG00000144285,SCN1A,sodium voltage-gated channel alpha subunit 1,0.926469

 Run 5 completed | rows=7140 | latency=15.300s
------------------------------------------------------------


## Question 18

**Which diseases are treated with trastuzumab deruxtecan?**

In [20]:

question = 'Which diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query was aiming to explore information related to the drug trastuzumab deruxtecan.
[drug_tool]: The first step involved retrieving known disease–drug associations for this drug. Initially, no specific number of entries was given, but after this step, the number of retrieved associations was 92. This indicates that the system collected 92 disease-related associations linked to trastuzumab deruxtecan.
[drug_tool]: Since no further filtering steps are included in the provided log, the resulting dataset contains these 92 associations directly related to the drug in question.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,TRASTUZUMAB DERUXTECAN,MONDO_0007254,breast cancer,4,Not yet recruiting,DNA topoisomerase I inhibitor,FDA

 Run 1 completed | rows=92 | latency=16.202s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query aims to identify specific drug-disease associations based on a set of filtering criteria. However, since the execution log contains no steps, it appears that no processing was performed on the data. Consequently, no filters or further narrowing of results occurred throughout the process. This means that the final result set remains unprocessed or empty, with no information available from the execution steps provided.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[drug_tool]: The query aimed to identify disease-associated drugs related to a specific target, focusing on the mechanisms involved.
[drug_tool]: Since the execution log contains no steps, it indicates that no processing steps were performed. As a result, no filters or retrievals reduced or refined the data, and no pathway or association information was obtained.
[drug_tool]: In summary, the final result consists of an empty set, with no data retrieved or filtered through any steps.
----------------------------------------
[drug_tool]: The query aims to explore the relationships between a specific disease and certain drugs, including their mechanisms of action and associated pathways.
[drug_tool]: Since the execution log is empty, no specific data retrieval or filtering steps were performed. Therefore, the process was not executed, and no further filtering or data reduction occurred.
[drug_tool]: As a result, there is no resulting data or number of entries to report.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[drug_tool]: The query's goal was to analyze associations between diseases and drugs, with subsequent filtering based on specific disease and drug criteria, and considering mechanisms of action and pathways.
[drug_tool]: However, since the execution log provided contains no steps, it indicates that no processing was performed on the query. Therefore, no filters were applied, and no results were retrieved or narrowed down through any filtering or mechanism-specific steps.
[drug_tool]: In summary, without any execution steps recorded, no associations or further filtering results were generated.
----------------------------------------
 Attempt 1 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[drug_tool]: The query aimed to retrieve information related to the drug trastuzumab deruxtecan. First, the system retrieved known disease–drug associations for this drug. This initial step resulted in 92 associations, but did not specify the initial number of associations before retrieval.
[drug_tool]: Next, no additional filters or steps are detailed in the provided log, so we proceed to the final count. The result set after this association retrieval contains 92 records related to trastuzumab deruxtecan.
[drug_tool]: In summary, the process started with retrieving known associations for trastuzumab deruxtecan, culminating in a total of 92 associations.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,TRASTUZUMAB DERUXTECAN,MONDO_0007254,breast cancer,4,Not yet recruiting,DNA topoisomerase I inhibitor,FDA

 Run 2 completed | rows=92 | latency=15.318s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve information about drugs associated with a particular target. In the first step, referred to as association retrieval, the system retrieved known drug associations for the drug trastuzumab deruxtecan, resulting in 92 entries. This step set the foundation for further filtering by providing the initial set of potential drug-disease interactions.
[drug_tool]: Since there are no additional steps shown in the provided log, the initial set of 92 associations remains as the current result. Therefore, the final number of associations after this retrieval is 92.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,TRASTUZUMAB DERUXTECAN,MONDO_0007254,breast cancer,4,Not yet recruiting,DNA topoisomerase I inhibitor,FDA

 Run 3 completed | rows=92 | latency=14.672s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query was intended to explore drug associations related to a specific drug, trastuzumab deruxtecan. The first step involved retrieving known associations between drugs and diseases, which initially resulted in a collection of 92 entries related to this drug. This step provided the base set of data for further filtering and analysis.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,TRASTUZUMAB DERUXTECAN,MONDO_0007254,breast cancer,4,Not yet recruiting,DNA topoisomerase I inhibitor,FDA

 Run 4 completed | rows=92 | latency=15.526s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query's goal was to find information related to the drug trastuzumab deruxtecan.
[drug_tool]: Initially, the system retrieved known disease–drug associations for this drug. This step produced 92 entries, representing the base set of associations related to trastuzumab deruxtecan.
[drug_tool]: At this stage, no filtering had been applied yet, so the result set contained all associations linked to this drug.
[drug_tool]: The final result consists of 92 entries, which form the starting point for further filtering or analysis if needed.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,TRASTUZUMAB DERUXTECAN,MONDO_0007254,breast cancer,4,Not yet recruiting,DNA topoisomerase I inhibitor,FDA

 Run 5 completed | rows=92 | latency=13.005s
------------------------------------------------------------


## Question 19

**Which genes are associated with Alzheimer’s disease?**

In [21]:

question = 'Which genes are associated with Alzheimer’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
[disease_tool]: The query's goal appears to be to find specific information related to disease–drug associations and mechanisms. However, the execution log provided is empty, indicating that no steps were performed during the process. As a result, no data was retrieved or filtered, and no further narrowing of results occurred.
[disease_tool]: In summary, since no steps were executed, the final result set is empty.
----------------------------------------
[disease_tool]: The provided log contains no steps, so no specific processing details can be described. Therefore, it appears that the query was not executed or recorded in this case. This means there is no information available about how the query results were filtered or refined. As a result, there is no final result count to report.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: The query's goal was to explore biomedical information, but since the execution log contains no steps, it indicates that no specific processing or filtering was performed. Therefore, no data retrieval, filtering, or narrowing of results took place. As a result, there are no further details or reductions to report.
----------------------------------------
[disease_tool]: The query was intended to find specific drug-disease associations based on certain criteria.
[disease_tool]: Since the execution log contains no steps, it appears that no processing was performed or recorded. Therefore, no filters or retrievals took place, and no results were obtained.
[disease_tool]: As a result, there is no information on how the data was filtered or narrowed down, and the final number of results remains unknown due to the absence of execution steps.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
 Attempt 2 failed after 30.008s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: Retrieved 12727 targets for disease Alzheimer's disease.
----------------------------------------
Entries retrieved: 12727

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004975,Alzheimer disease,ENSG00000080815,PSEN1,presenilin 1,0.867114

 Run 1 completed | rows=12727 | latency=22.336s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
[disease_tool]: Retrieved 12727 targets for disease Alzheimer's disease.
----------------------------------------
Entries retrieved: 12727

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004975,Alzheimer disease,ENSG00000080815,PSEN1,presenilin 1,0.867114

 Run 2 completed | rows=12727 | latency=25.888s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
[disease_tool]: No resolved disease found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.006s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: No resolved disease found.
----------------------------------------
[disease_tool]: The query aimed to identify disease–drug interactions based on specific criteria. Since the execution log is empty, no steps were taken to retrieve or filter data. This means that no disease associations, drugs, mechanisms, or pathways were retrieved or filtered at any step. As a result, there are no data reductions or filtering effects to report. The final result set is empty due to the lack of executed steps.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: The query's goal was to identify associations between a specific disease and drugs, then refine these results based on various filters.
[disease_tool]: Since the execution log is empty, it indicates that no processing steps were performed on the data. Consequently, no filtering, deduplication, or pathway retrieval steps took place.
[disease_tool]: As a result, the final number of associations returned remains unknown due to the absence of any processed data.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 2 failed after 30.003s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: No resolved disease found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: The query was designed to find information related to a specific biomedical question, but the execution log shows no recorded steps. This indicates that no processing steps, such as retrieving disease–drug associations, applying disease or drug filters, or other filtering operations, were executed or documented. As a result, there is no detailed information on how the search was narrowed down. Therefore, the final result count remains unspecified based on the provided log.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 3 failed after 24.555s: 'NoneType' object has no attribute 'columns'
 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
[disease_tool]: No resolved disease found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[disease_tool]: The user's query aims to identify relevant disease–drug associations based on certain filters and mechanisms.
[disease_tool]: Initially, no specific actions are recorded in the execution log, so it appears that the system did not perform any data retrieval or filtering steps. Since there are no steps documented, no associations, diseases, drugs, or mechanisms have been explicitly processed or narrowed down.
[disease_tool]: In summary, because the execution log contains no steps, no data has been filtered or reduced through the process, and no results have been obtained.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: Retrieved 12727 targets for disease Alzheimer's disease.
----------------------------------------
Entries retrieved: 12727

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004975,Alzheimer disease,ENSG00000080815,PSEN1,presenilin 1,0.867114

 Run 4 completed | rows=12727 | latency=19.937s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
[disease_tool]: No resolved disease found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[disease_tool]: The query aimed to identify potential drug candidates related to a specific disease. However, the execution log is empty, indicating that no steps were performed during the process. This means that no association retrieval, filtering, or pathway retrieval occurred. Consequently, there is no result set to analyze or summarize. The final outcome contains no data.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: The query aimed to find potential drug interactions or related information based on a specified set of criteria.
[disease_tool]: Since the execution log is empty and contains no steps, no specific filtering or retrieval processes were performed. As a result, no data was retrieved or narrowed down through association retrieval, disease filtering, drug filtering, mechanism filtering, deduplication, or pathway retrieval.
[disease_tool]: In summary, because there are no recorded steps, the process did not produce any resulting data, and no further explanation of filtering or reduction can be provided.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The query aimed to identify drugs associated with a specific disease or mechanism of action.
[disease_tool]: Since the execution log is empty, no specific steps or filters were applied during the process. This means that no retrievals, filtering, or deduplication steps took place. Consequently, there are no details on the number of associations found or any narrowing of results based on disease, drug, or mechanism filters.
[disease_tool]: In summary, because the execution log is empty, no result set was generated or refined through any process.
----------------------------------------
[disease_tool]: The query aimed to identify drug-target associations related to specific diseases and mechanisms. However, because no detailed execution steps are provided, I am unable to describe the specific process or how the filters or retrievals were applied. Without additional information in the execution log, I cannot determine how the results were narrowed or what the final outcomes were.
----------------------------------------
 Attempt 2 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: Retrieved 12727 targets for disease Alzheimer's disease.
----------------------------------------
Entries retrieved: 12727

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0004975,Alzheimer disease,ENSG00000080815,PSEN1,presenilin 1,0.867114

 Run 5 completed | rows=12727 | latency=21.888s
------------------------------------------------------------


## Question 20

**For which diseases is darolutamide used?**

In [22]:

question = 'For which diseases is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is darolutamide used?
  Attempt 1/3
[drug_tool]: The query aims to find information related to darolutamide and its associated drugs.
[drug_tool]: The first step involved retrieving known associations of darolutamide with various drugs. This initial retrieval brought back 39 associations, providing a foundational list of drugs linked to darolutamide.
[drug_tool]: There were no further filtering steps shown in the provided log, so the resulting set of 39 associations represents the outcome of the initial association retrieval.
[drug_tool]: In summary, the final result includes 39 drug associations related to darolutamide.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,DAROLUTAMIDE,EFO_0000616,neoplasm,4.0,NaN,Androgen Receptor antagonist,"Other, PubMed"

 Run 1 completed | rows=39 | latency=15.916s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is darolutamide used?
  Attempt 1/3
[drug_tool]: The query's goal was to identify drugs associated with a specific target.
[drug_tool]: Initially, the system retrieved known disease–drug associations related to the drug darolutamide. This basic association retrieval provided a starting set of data containing a total of 39 entries.
[drug_tool]: Since only one step is shown in the provided log, the process concluded with the retrieval of these 39 associations, which form the basis for further analysis or filtering if additional steps are performed later.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,DAROLUTAMIDE,EFO_0000616,neoplasm,4.0,NaN,Androgen Receptor antagonist,"Other, PubMed"

 Run 2 completed | rows=39 | latency=14.219s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is darolutamide used?
  Attempt 1/3
[drug_tool]: The query aims to explore information related to the drug darolutamide.
[drug_tool]: Initially, the system retrieved known associations between darolutamide and various diseases, resulting in 39 entries.
[drug_tool]: The process then proceeded to filter these results based on specific criteria, although details of further filters such as disease, drug, or mechanism filters are not provided in this particular log.
[drug_tool]: Finally, the system removed any duplicate records to ensure unique entries in the dataset.
[drug_tool]: The final result consists of 39 links related to darolutamide.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,DAROLUTAMIDE,EFO_0000616,neoplasm,4.0,NaN,Androgen Receptor antagonist,"Other, PubMed"

 Run 3 completed | rows=39 | latency=14.353s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is darolutamide used?
  Attempt 1/3
[drug_tool]: The query aimed to identify drugs associated with a specific disease or target. The first step involved retrieving known drug associations related to the drug darolutamide. This initial retrieval resulted in 39 entries, which provided a set of potential disease or target associations for analysis. Since this was the first step, there was no reduction from a previous set. The final result after this step was 39 association entries relevant to darolutamide.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,DAROLUTAMIDE,EFO_0000616,neoplasm,4.0,NaN,Androgen Receptor antagonist,"Other, PubMed"

 Run 4 completed | rows=39 | latency=14.418s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is darolutamide used?
  Attempt 1/3
[drug_tool]: The goal of the query was to explore drug associations related to darolutamide.
[drug_tool]: First, the system retrieved known disease–drug associations specifically for darolutamide, which resulted in 39 related entries.
[drug_tool]: Since there were no additional filters applied at this stage, the number of entries remained at 39.
[drug_tool]: In the final step, pathway information was retrieved for these associations, but no reduction in the number of entries was indicated at this stage.
[drug_tool]: Overall, the process started with a search for darolutamide-related associations and concluded with 39 relevant entries in the dataset.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,DAROLUTAMIDE,EFO_0000616,neoplasm,4.0,NaN,Androgen Receptor antagonist,"Other, PubMed"

 Run 5 completed | rows=39 | latency=14.616s
------------------------------------------------------------


## Question 21

**Which genes are associated with renal cell carcinoma?**

In [23]:

question = 'Which genes are associated with renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
[disease_tool]: Retrieved 8668 targets for disease renal cell carcinoma.
----------------------------------------
Entries retrieved: 8668

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000681,renal cell carcinoma,ENSG00000105976,MET,"MET proto-oncogene, receptor tyrosine kinase",0.888778

 Run 1 completed | rows=8668 | latency=26.539s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
[disease_tool]: Retrieved 8668 targets for disease renal cell carcinoma.
----------------------------------------
Entries retrieved: 8668

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000681,renal cell carcinoma,ENSG00000105976,MET,"MET proto-oncogene, receptor tyrosine kinase",0.888778

 Run 2 completed | rows=8668 | latency=21.691s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
[disease_tool]: Retrieved 8668 targets for disease renal cell carcinoma.
----------------------------------------
Entries retrieved: 8668

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000681,renal cell carcinoma,ENSG00000105976,MET,"MET proto-oncogene, receptor tyrosine kinase",0.888778

 Run 3 completed | rows=8668 | latency=18.631s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
[disease_tool]: Retrieved 8668 targets for disease renal cell carcinoma.
----------------------------------------
Entries retrieved: 8668

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000681,renal cell carcinoma,ENSG00000105976,MET,"MET proto-oncogene, receptor tyrosine kinase",0.888778

 Run 4 completed | rows=8668 | latency=15.834s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
[disease_tool]: Retrieved 8668 targets for disease renal cell carcinoma.
----------------------------------------
Entries retrieved: 8668

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000681,renal cell carcinoma,ENSG00000105976,MET,"MET proto-oncogene, receptor tyrosine kinase",0.888778

 Run 5 completed | rows=8668 | latency=17.655s
------------------------------------------------------------


## Question 22

**Which diseases are associated with the KRAS gene?**

In [24]:

question = 'Which diseases are associated with the KRAS gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
[target_tool]: Retrieved 1801 diseases for target KRAS.
----------------------------------------
Entries retrieved: 1801

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000133703,KRAS,MONDO_0012371,Noonan syndrome 3,0.826323

 Run 1 completed | rows=1801 | latency=14.629s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
[target_tool]: Retrieved 1801 diseases for target KRAS.
----------------------------------------
Entries retrieved: 1801

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000133703,KRAS,MONDO_0012371,Noonan syndrome 3,0.826323

 Run 2 completed | rows=1801 | latency=12.017s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
[target_tool]: Retrieved 1801 diseases for target KRAS.
----------------------------------------
Entries retrieved: 1801

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000133703,KRAS,MONDO_0012371,Noonan syndrome 3,0.826323

 Run 3 completed | rows=1801 | latency=12.158s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
[target_tool]: Retrieved 1801 diseases for target KRAS.
----------------------------------------
Entries retrieved: 1801

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000133703,KRAS,MONDO_0012371,Noonan syndrome 3,0.826323

 Run 4 completed | rows=1801 | latency=13.471s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
[target_tool]: Retrieved 1801 diseases for target KRAS.
----------------------------------------
Entries retrieved: 1801

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000133703,KRAS,MONDO_0012371,Noonan syndrome 3,0.826323

 Run 5 completed | rows=1801 | latency=14.315s
------------------------------------------------------------


## Question 23

**Which pathways are associated with the APP gene?**

In [25]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: This query aimed to retrieve pathway information related to the target protein APP. First, the system retrieved pathways associated with APP, resulting in a total of 17 pathways. Since this step only involved retrieval, no rows were filtered out at this point. The final result includes these 17 pathway entries, providing pathway information linked to the target.
----------------------------------------
Entries retrieved: 17

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 1 completed | rows=17 | latency=14.786s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The query aimed to analyze biological pathways related to the target gene APP.
[target_tool]: Initially, the system retrieved pathway information associated with APP. This step resulted in 17 pathways being identified, but no specific number of pathways was provided before retrieval.
[target_tool]: Since only the pathway retrieval step is documented here, no further filtering steps are evidenced in this log. The process primarily focused on gathering pathway data related to APP, and the total number of identified pathways after this step was 17.
----------------------------------------
Entries retrieved: 17

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 2 completed | rows=17 | latency=13.585s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve pathway information related to the target APP.
[target_tool]: First, the system retrieved pathways associated with the target APP, resulting in a total of 17 pathways. This step involved collecting all pathway data related to the specified target without initial filtering.
[target_tool]: Since the log does not show any prior filtering steps or reductions, the retrieval of pathways by itself resulted in 17 records related to APP.
[target_tool]: In summary, the process concluded with 17 pathways associated with APP being retrieved.
----------------------------------------
Entries retrieved: 17

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 3 completed | rows=17 | latency=14.794s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathways associated with the target "APP." The first step involved retrieving pathway information for this target, which resulted in 17 pathways. No initial number of pathways was specified, and this step simply provided the pathway data related to the target. In the end, there are 17 pathways linked to "APP."
----------------------------------------
Entries retrieved: 17

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 4 completed | rows=17 | latency=15.529s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target molecule APP. In the first step, the system retrieved pathways associated with APP, and this resulted in a total of 17 pathways being identified. Since this was the initial retrieval of pathway data in this process, no previous row count is provided. After this step, the total pathways related to APP amounted to 17.
----------------------------------------
Entries retrieved: 17

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 5 completed | rows=17 | latency=12.692s
------------------------------------------------------------


## Question 24

**Which genes are associated with schizophrenia?**

In [26]:

question = 'Which genes are associated with schizophrenia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
[disease_tool]: Retrieved 7041 targets for disease schizophrenia.
----------------------------------------
Entries retrieved: 7041

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005090,schizophrenia,ENSG00000149295,DRD2,dopamine receptor D2,0.733924

 Run 1 completed | rows=7041 | latency=20.928s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
[disease_tool]: Retrieved 7041 targets for disease schizophrenia.
----------------------------------------
Entries retrieved: 7041

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005090,schizophrenia,ENSG00000149295,DRD2,dopamine receptor D2,0.733924

 Run 2 completed | rows=7041 | latency=21.782s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
[disease_tool]: Retrieved 7041 targets for disease schizophrenia.
----------------------------------------
Entries retrieved: 7041

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005090,schizophrenia,ENSG00000149295,DRD2,dopamine receptor D2,0.733924

 Run 3 completed | rows=7041 | latency=18.712s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
[disease_tool]: Retrieved 7041 targets for disease schizophrenia.
----------------------------------------
Entries retrieved: 7041

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005090,schizophrenia,ENSG00000149295,DRD2,dopamine receptor D2,0.733924

 Run 4 completed | rows=7041 | latency=16.174s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
[disease_tool]: Retrieved 7041 targets for disease schizophrenia.
----------------------------------------
Entries retrieved: 7041

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005090,schizophrenia,ENSG00000149295,DRD2,dopamine receptor D2,0.733924

 Run 5 completed | rows=7041 | latency=15.232s
------------------------------------------------------------


## Question 25

**Which diseases are treated with valdecoxib?**

In [27]:

question = 'Which diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to a specific drug, valdecoxib, including its associations with diseases and mechanisms of action.
[drug_tool]: The first step, association retrieval, involved fetching known drug associations, specifically for valdecoxib. This step resulted in a single association being retrieved, reducing the initial dataset to just one record related to that drug.
[drug_tool]: Subsequently, additional filters such as disease, drug, or mechanism filters were not shown in this part of the log, indicating they may not have been applied yet or information is limited. There was also no indication of pathway retrieval or deduplication steps in the provided log excerpt.
[drug_tool]: In summary, the process started with retrieving associations for valdecoxib and resulted in exactly one note of association being identified at this point.
----------------------------------------
Entries retrieved: 1

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,VALDECOXIB,NaN,NaN,NaN,NaN,Cyclooxygenase-2 inhibitor,DailyMed

 Run 1 completed | rows=1 | latency=15.144s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to valdecoxib.
[drug_tool]: First, the system retrieved known disease–drug associations specifically for valdecoxib, which resulted in 13 entries. This step involved collecting all relevant associations from the database.
[drug_tool]: No additional filters or steps are indicated in this segment.
[drug_tool]: In conclusion, the process yielded 13 potential associations involving valdecoxib.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,VALDECOXIB,EFO_0000685,rheumatoid arthritis,4,NaN,Cyclooxygenase-2 inhibitor,DailyMed

 Run 2 completed | rows=13 | latency=11.634s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to valdecoxib. The first step involved retrieving the known disease–drug associations for valdecoxib, resulting in a very small initial result set with just one entry.
[drug_tool]: Since only one association was retrieved at this stage, there was no further filtering or narrowing down based on diseases or mechanisms.
[drug_tool]: In summary, after retrieving the associations for valdecoxib, the final result consisted of a single record.
----------------------------------------
Entries retrieved: 1

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,VALDECOXIB,NaN,NaN,NaN,NaN,Cyclooxygenase-2 inhibitor,DailyMed

 Run 3 completed | rows=1 | latency=13.492s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drugs associated with a specific disease or target.
[drug_tool]: Initially, the system retrieved known drug associations for valdecoxib. This step yielded 13 entries related to valdecoxib, focusing the dataset on this particular drug.
[drug_tool]: Subsequently, filters were applied to narrow down these associations. However, the log indicates that there were no further filters, such as disease or mechanism filters, applied after this retrieval.
[drug_tool]: Finally, no deduplication or pathway retrieval steps are shown in the provided log.
[drug_tool]: In total, the process resulted in 13 drug association entries related to valdecoxib.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,VALDECOXIB,EFO_0000685,rheumatoid arthritis,4,NaN,Cyclooxygenase-2 inhibitor,DailyMed

 Run 4 completed | rows=13 | latency=13.947s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aims to retrieve information related to the drug valdecoxib.
[drug_tool]: First, the system performed an association retrieval step, where it fetched known disease-drug associations for the target drug. At this point, only one association was found and retained in the result set.
[drug_tool]: Since there are no further filtering or processing steps provided in this log, the final result contains this single entry involving valdecoxib.
----------------------------------------
Entries retrieved: 1

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,VALDECOXIB,NaN,NaN,NaN,NaN,Cyclooxygenase-2 inhibitor,DailyMed

 Run 5 completed | rows=1 | latency=13.980s
------------------------------------------------------------


## Question 26

**What are the known targets of vandetanib?**

In [28]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The query aimed to find associations related to the drug vandetanib.
[drug_tool]: First, the system retrieved known drug associations for vandetanib, resulting in a total of 2,275 entries.
[drug_tool]: Next, the process performed deduplication to remove any duplicate records from this list. After this step, the list was reduced substantially from 2,275 to 25 unique entries, eliminating 2,250 duplicates.
[drug_tool]: In summary, the final result set contains 25 unique associations related to vandetanib.
----------------------------------------
Entries retrieved: 25

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL24828,VANDETANIB,Vascular endothelial growth factor receptor in...,DailyMed

 Run 1 completed | rows=25 | latency=15.403s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The query's goal was to find drug associations related to vandetanib.
[drug_tool]: First, the system retrieved all known drug associations involving vandetanib, resulting in a total of 2,275 entries.
[drug_tool]: Next, the system removed duplicate rows from this list to ensure each association was unique, reducing the total from 2,275 to 25 entries.
[drug_tool]: In the end, the final result set contained 25 unique drug association records related to vandetanib.
----------------------------------------
Entries retrieved: 25

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL24828,VANDETANIB,Vascular endothelial growth factor receptor in...,DailyMed

 Run 2 completed | rows=25 | latency=13.978s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The intent of the query was to find specific drug-related associations for the molecule vandetanib.
[drug_tool]: First, the system retrieved known associations linking vandetanib to various diseases or mechanisms, resulting in a total of 2,275 associated records.
[drug_tool]: Next, the process involved removing duplicate entries from this initial dataset, which significantly reduced the number of records from 2,275 to 25. This deduplication step ensured that the final list contained only unique associations.
[drug_tool]: Overall, after these steps, the system provided a refined set of 25 unique association records related to vandetanib.
----------------------------------------
Entries retrieved: 25

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL24828,VANDETANIB,Vascular endothelial growth factor receptor in...,DailyMed

 Run 3 completed | rows=25 | latency=14.699s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drugs associated with a specific target, vandetanib.
[drug_tool]: Initially, the system retrieved known drug associations related to vandetanib, resulting in a total of 2,275 entries. This step pulled together all the relevant known connections for the drug before any filtering was applied.
[drug_tool]: Next, the system performed a deduplication step to remove duplicate records from the retrieved associations. This process reduced the number of entries from 2,275 to 25, leaving only unique association records.
[drug_tool]: In summary, after retrieving all known associations for vandetanib and removing duplicates, the final dataset consisted of 25 unique entries.
----------------------------------------
Entries retrieved: 25

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL24828,VANDETANIB,Vascular endothelial growth factor receptor in...,DailyMed

 Run 4 completed | rows=25 | latency=15.731s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The purpose of the query was to identify drug associations related to vandetanib.
[drug_tool]: First, the system retrieved all known drug associations for vandetanib, which resulted in a total of 2,275 entries.
[drug_tool]: Next, duplicate records among these associations were identified and removed through a deduplication process. This step reduced the total number of entries dramatically, leaving only 25 unique records.
[drug_tool]: In summary, the final result after filtering was 25 unique drug association entries related to vandetanib.
----------------------------------------
Entries retrieved: 25

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,FLT4,CHEMBL24828,VANDETANIB,Vascular endothelial growth factor receptor in...,DailyMed

 Run 5 completed | rows=25 | latency=15.062s
------------------------------------------------------------


## Question 27

**Which pathways are associated with the CFTR gene?**

In [29]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the CFTR target, focusing on pathways involved in its function.
[target_tool]: The process started with retrieving pathways associated with the CFTR target. This step was solely concerned with gathering pathway information, and no prior pathways were specified, so the exact number before retrieval is not provided. After this step, 11 pathways were identified as related to CFTR, indicating that these pathways are potentially involved in CFTR's biological processes or disease mechanisms.
[target_tool]: In summary, the final result included 11 pathways associated with the CFTR target.
----------------------------------------
Entries retrieved: 11

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 1 completed | rows=11 | latency=17.456s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: This query aimed to explore pathways related to the CFTR target. The process began with retrieving pathways associated with CFTR. This step resulted in the selection of 11 pathways, providing a foundation for further analysis. Since pathway retrieval was the initial step, there was no reduction from a prior set of pathways. The final result includes these 11 pathways related to CFTR, completing the query process.
----------------------------------------
Entries retrieved: 11

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 2 completed | rows=11 | latency=13.240s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The goal of the query was to explore pathways related to the CFTR target. The first step involved retrieving pathways associated with CFTR, which resulted in 11 pathway records. There were no previous pathway records to compare, but this step provided the pathway information needed for further analysis. The final result contains 11 pathway entries linked to CFTR.
----------------------------------------
 Attempt 1 failed after 14.983s: 'NoneType' object has no attribute 'columns'
  Attempt 2/3
[target_tool]: The system aimed to retrieve pathway information related to the target CFTR. In this step, it collected a total of 11 pathways associated with CFTR. Since no prior count is provided, we only know that 11 pathways were retrieved following this step.
----------------------------------------
Entries retrieved: 11

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 3 completed | rows=11 | latency=12.053s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the CFTR target, particularly focusing on pathways associated with it. The first step involved retrieving pathway data for CFTR, resulting in 11 pathways being identified. Since this was the initial data retrieval related to pathways, there was no reduction of rows at this stage. Overall, 11 pathways associated with CFTR were obtained through this step.
----------------------------------------
Entries retrieved: 11

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 4 completed | rows=11 | latency=12.332s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target CFTR. First, the system retrieved pathways associated with CFTR, resulting in a total of 11 pathways. This step provided pathway data for further analysis. Since there are no prior pathway data or filters applied before this step, no reduction in rows can be mentioned. The final result includes 11 pathways linked to CFTR.
----------------------------------------
Entries retrieved: 11

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 5 completed | rows=11 | latency=12.595s
------------------------------------------------------------


## Question 28

**Which drugs are used to treat tuberculosis?**

In [30]:

question = 'Which drugs are used to treat tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
[disease_tool]: The query aims to identify associations related to tuberculosis.
[disease_tool]: First, the system retrieved known disease–drug associations for tuberculosis. This initial retrieval provided a total of 161 rows. Next, the system removed duplicate records from these associations to ensure each entry was unique, which reduced the number of entries from 161 down to 53.
[disease_tool]: In summary, after applying these steps, the final dataset contained 53 unique disease association entries related to tuberculosis.
----------------------------------------
Entries retrieved: 53

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL2021430,DEXAMETHASONE SODIUM PHOSPHATE,MONDO_0018076,tuberculosis,4,NaN,Small molecule,EFO_1000039,meningeal tuberculosis

 Run 1 completed | rows=53 | latency=24.988s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease-drug associations related to tuberculosis. First, the system retrieved known associations between diseases and drugs specifically for tuberculosis, resulting in 161 entries. Then, to eliminate redundancies, a deduplication step removed duplicate records, reducing the number of entries from 161 to 53. The final result contains 53 unique disease-drug associations related to tuberculosis.
----------------------------------------
Entries retrieved: 53

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL2021430,DEXAMETHASONE SODIUM PHOSPHATE,MONDO_0018076,tuberculosis,4,NaN,Small molecule,EFO_1000039,meningeal tuberculosis

 Run 2 completed | rows=53 | latency=13.890s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
[disease_tool]: The query aims to identify drugs related to tuberculosis.
[disease_tool]: First, the system retrieved known disease–drug associations for tuberculosis, resulting in 161 initial records. Then, to eliminate any duplicate entries, the system performed a deduplication step. This process reduced the number of records from 161 to 53 by removing 108 duplicate rows.
[disease_tool]: Overall, after these steps, the system was left with 53 unique disease–drug association records for tuberculosis.
----------------------------------------
Entries retrieved: 53

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL2021430,DEXAMETHASONE SODIUM PHOSPHATE,MONDO_0018076,tuberculosis,4,NaN,Small molecule,EFO_1000039,meningeal tuberculosis

 Run 3 completed | rows=53 | latency=16.556s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
[disease_tool]: The purpose of the query was to identify disease-drug associations related to tuberculosis.
[disease_tool]: Initially, the system retrieved all known disease associations for tuberculosis, which resulted in 161 entries. To ensure the results were unique, duplicate rows were then removed, decreasing the total from 161 to 53. This deduplication step helped refine the dataset by eliminating redundant records.
[disease_tool]: In summary, the final result includes 53 unique entries related to disease–drug associations for tuberculosis after the filtering steps.
----------------------------------------
Entries retrieved: 53

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL2021430,DEXAMETHASONE SODIUM PHOSPHATE,MONDO_0018076,tuberculosis,4,NaN,Small molecule,EFO_1000039,meningeal tuberculosis

 Run 4 completed | rows=53 | latency=16.268s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
[disease_tool]: The goal of this query was to find disease–drug associations related to tuberculosis.
[disease_tool]: First, the system retrieved the initial set of disease associations related to tuberculosis, which resulted in 161 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from this initial list, reducing the total from 161 to 53 unique entries.
[disease_tool]: In total, the final result set contains 53 entries of unique disease–drug associations related to tuberculosis.
----------------------------------------
Entries retrieved: 53

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL2021430,DEXAMETHASONE SODIUM PHOSPHATE,MONDO_0018076,tuberculosis,4,NaN,Small molecule,EFO_1000039,meningeal tuberculosis

 Run 5 completed | rows=53 | latency=13.745s
------------------------------------------------------------


## Question 29

**Which drugs are used to treat pancreatic adenocarcinoma?**

In [31]:

question = 'Which drugs are used to treat pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations based on specific biological mechanisms.
[disease_tool]: Since the execution log is empty, no specific steps or filtering processes were recorded or executed. Therefore, no associations, diseases, drugs, mechanisms, or pathways were retrieved or filtered at any stage. As a result, there are no data points about the number of entries or any filtering outcomes.
[disease_tool]: In summary, the final result set contains no entries, indicating that no data was processed or returned during the execution.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 17.387s: 'NoneType' object has no attribute 'columns'
  Attempt 2/3
[disease_tool]: Disease tool failed: anonymous_query: Internal server error
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: Disease tool failed: anonymous_query: Internal server error
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: The query's goal was to identify disease-drug associations based on specific filtering criteria.
[disease_tool]: Since the execution log provided is empty, no steps were taken to retrieve or refine data. This means that no associations, diseases, drugs, mechanisms, or pathways were retrieved or filtered. Consequently, there are no reduction steps or filtering details to explain.
[disease_tool]: In summary, the process did not produce any results because no steps were executed, so the final result set is empty.
----------------------------------------
 Attempt 2 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: The intent of the query was to retrieve information related to pancreatic adenocarcinoma and associated drugs or mechanisms.
[disease_tool]: The first step involved retrieving known associations between diseases and drugs. Initially, this process fetched 1,000 rows of data related to disease associations.
[disease_tool]: Next, deduplication was performed to remove duplicate entries, reducing the total number of associations from 1,000 to 229. This step ensured that only unique records remained for further analysis.
[disease_tool]: Overall, the process resulted in 229 unique disease association records for pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 229

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL888,GEMCITABINE,EFO_1000044,pancreatic adenocarcinoma,3,Completed,Small molecule,MONDO_0005184,pancreatic ductal adenocarcinoma

 Run 1 completed | rows=229 | latency=23.263s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to pancreatic adenocarcinoma, focusing on associated diseases and drugs.
[disease_tool]: First, the system retrieved known disease associations for pancreatic adenocarcinoma, resulting in 1,918 entries. This step gathered all potential links between this disease and other conditions or factors.
[disease_tool]: Next, the system removed duplicate records from this set to ensure only unique entries remained. This deduplication reduced the number of results from 1,918 to 460 entries, effectively eliminating 1,458 duplicate rows.
[disease_tool]: In summary, after these steps, the resulting dataset contained 460 unique disease associations related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 460

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL888,GEMCITABINE,EFO_1000044,pancreatic adenocarcinoma,3.0,Unknown status,Small molecule,EFO_1000044,pancreatic adenocarcinoma

 Run 2 completed | rows=460 | latency=22.407s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: This query aimed to identify associations related to pancreatic adenocarcinoma.
[disease_tool]: Initially, the system retrieved known disease–drug associations for this disease, bringing back 1000 records.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, reducing the number of records from 1000 to 229.
[disease_tool]: In total, the final result contains 229 unique disease–drug association entries related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 229

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL888,GEMCITABINE,EFO_1000044,pancreatic adenocarcinoma,3,Completed,Small molecule,MONDO_0005184,pancreatic ductal adenocarcinoma

 Run 3 completed | rows=229 | latency=19.829s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aims to find information related to pancreatic adenocarcinoma and associated drugs or mechanisms.
[disease_tool]: First, the system retrieved known disease associations for pancreatic adenocarcinoma, resulting in 1918 entries. This step brought together all initial known disease-related data relevant to this condition.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the result set from 1918 to 460 entries. This step eliminated repeated data points to ensure each association or fact was unique.
[disease_tool]: In total, the process resulted in 460 unique records linked to pancreatic adenocarcinoma after applying these retrieval and deduplication steps.
----------------------------------------
Entries retrieved: 460

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL888,GEMCITABINE,EFO_1000044,pancreatic adenocarcinoma,3.0,Unknown status,Small molecule,EFO_1000044,pancreatic adenocarcinoma

 Run 4 completed | rows=460 | latency=18.087s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The purpose of the query was to retrieve information related to pancreatic adenocarcinoma.
[disease_tool]: First, the system retrieved known disease–drug associations for pancreatic adenocarcinoma, resulting in 1,000 rows. This step gathered all initial associations related to this disease.
[disease_tool]: Next, the system removed duplicate records from the dataset, reducing the number of entries from 1,000 to 229. This deduplication step eliminated 771 redundant rows to ensure a set of unique associations.
[disease_tool]: In conclusion, after these steps, there are 229 distinct disease–drug association records related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 229

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL888,GEMCITABINE,EFO_1000044,pancreatic adenocarcinoma,3,Completed,Small molecule,MONDO_0005184,pancreatic ductal adenocarcinoma

 Run 5 completed | rows=229 | latency=15.761s
------------------------------------------------------------


## Question 30

**Which drugs are used to treat chronic myeloid leukemia?**

In [32]:

question = 'Which drugs are used to treat chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: Disease tool failed: anonymous_query: Internal server error
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The query aimed to identify information related to chronic myeloid leukemia.
[disease_tool]: First, the system retrieved known disease–drug associations specifically for chronic myeloid leukemia, resulting in 976 records.
[disease_tool]: Next, the system removed duplicate records from this dataset, reducing the total number of entries from 976 to 246.
[disease_tool]: In summary, the final result contains 246 unique associations related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 246

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1421,DASATINIB ANHYDROUS,EFO_0000339,chronic myelogenous leukemia,4.0,NaN,Small molecule,EFO_0000339,chronic myelogenous leukemia

 Run 1 completed | rows=246 | latency=26.459s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The query appears to aim at identifying specific disease-drug associations, filtering them according to detailed criteria, and collecting relevant pathway information along the way. However, since the execution log contains no steps, it indicates that no processing steps were performed.
[disease_tool]: As a result, there are no associated results to describe, and the process did not generate any filtered or narrowed-down data points. The final outcome is that no records were retrieved or filtered through any of the methods, and the resulting dataset remains empty.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: The query aims to find disease-drug associations related to a specific disease or condition.
[disease_tool]: Since the execution log contains no steps, it appears that no processing steps were carried out, or the log was not provided. Therefore, no filters or retrievals were performed.
[disease_tool]: As a result, there is no information on any retrieved associations, applied disease or drug filters, mechanisms, pathway retrievals, or deduplications.
[disease_tool]: Without any execution steps shown, the final result count cannot be determined.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The query aimed to identify biomedical information related to a specific topic or set of conditions, although no details about the specific search parameters are provided.
[disease_tool]: Since the execution log is empty, it indicates that no steps were performed during the process. As a result, no filtering, retrieval, or data processing actions took place.
[disease_tool]: In conclusion, there are no results or further details available based on this execution, implying that the final result set remains empty.
----------------------------------------
 Attempt 1 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: The query aimed to identify disease associations related to chronic myeloid leukemia, focusing on its connections with drugs or mechanisms.
[disease_tool]: First, the system retrieved known disease associations for chronic myeloid leukemia. This step resulted in a dataset of 976 entries. Next, the system performed a deduplication process to remove duplicate records, reducing the number of entries from 976 to 246. This step eliminated 730 duplicate rows, leaving a cleaner set of unique associations.
[disease_tool]: In summary, after retrieving and cleaning the data, there are 246 unique associations related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 246

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1421,DASATINIB ANHYDROUS,EFO_0000339,chronic myelogenous leukemia,4.0,NaN,Small molecule,EFO_0000339,chronic myelogenous leukemia

 Run 2 completed | rows=246 | latency=21.660s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 16.788s: 'NoneType' object has no attribute 'columns'
  Attempt 2/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[disease_tool]: The goal of the query was to identify information related to chronic myeloid leukemia.
[disease_tool]: Initially, the system retrieved all known disease–drug associations for chronic myeloid leukemia, which resulted in 976 entries.
[disease_tool]: Next, the system removed duplicate records from this set, reducing the number of entries from 976 to 246. This step ensured that only unique associations remained.
[disease_tool]: In total, the process ended with 246 unique disease–drug association entries related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 246

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1421,DASATINIB ANHYDROUS,EFO_0000339,chronic myelogenous leukemia,4.0,NaN,Small molecule,EFO_0000339,chronic myelogenous leukemia

 Run 3 completed | rows=246 | latency=24.661s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The query aimed to explore associations related to chronic myeloid leukemia. First, the system retrieved a set of known disease-drug associations related to this disease, which initially consisted of 976 entries. Next, the process removed duplicate records from this set, reducing the number from 976 to 246. In total, the final result includes 246 unique associations related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 246

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1421,DASATINIB ANHYDROUS,EFO_0000339,chronic myelogenous leukemia,4.0,NaN,Small molecule,EFO_0000339,chronic myelogenous leukemia

 Run 4 completed | rows=246 | latency=14.462s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The intent of the query was to explore disease–drug associations for chronic myeloid leukemia.
[disease_tool]: First, the system retrieved all known disease associations related to this disease, resulting in an initial set of 976 entries. Next, to remove any redundancy, duplicate records were eliminated, reducing the result set from 976 to 246 entries.
[disease_tool]: In summary, after retrieving and cleaning the data, the final result includes 246 unique disease association entries related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 246

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1421,DASATINIB ANHYDROUS,EFO_0000339,chronic myelogenous leukemia,4.0,NaN,Small molecule,EFO_0000339,chronic myelogenous leukemia

 Run 5 completed | rows=246 | latency=20.448s
------------------------------------------------------------


## Question 31

**Which drugs are used to treat Parkinson’s disease?**

In [33]:

question = 'Which drugs are used to treat Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The goal of the query was to identify disease-drug associations related to Parkinson's disease.
[disease_tool]: First, the system retrieved known disease associations specifically for Parkinson's disease, which initially resulted in 855 records. Next, to ensure data quality and eliminate redundancy, duplicate entries were removed, reducing the dataset from 855 to 359 records.
[disease_tool]: Overall, after these steps, the system arrived at 359 unique records related to Parkinson's disease associations.
----------------------------------------
Entries retrieved: 359

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1324,TOLCAPONE,MONDO_0005180,Parkinson disease,4.0,NaN,Small molecule,MONDO_0005180,Parkinson disease

 Run 1 completed | rows=359 | latency=29.597s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The query aims to identify disease–drug associations related to Parkinson's disease.
[disease_tool]: Initially, the system retrieved all known disease–drug associations linked to Parkinson's disease, resulting in 855 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the number of entries from 855 to 359.
[disease_tool]: In summary, after retrieving the relevant associations and removing duplicates, the final result includes 359 unique entries related to Parkinson's disease.
----------------------------------------
Entries retrieved: 359

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1324,TOLCAPONE,MONDO_0005180,Parkinson disease,4.0,NaN,Small molecule,MONDO_0005180,Parkinson disease

 Run 2 completed | rows=359 | latency=18.122s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The user query aimed to find drug targets associated with Parkinson disease.
[disease_tool]: Initially, the system retrieved known disease-drug associations related to Parkinson disease, which resulted in a total of 855 records.
[disease_tool]: Next, the system performed a deduplication step, removing duplicate entries to refine the dataset. This process reduced the number of records from 855 to 359, eliminating 496 duplicate rows to ensure each association was unique.
[disease_tool]: In summary, after retrieving the disease associations and removing duplicates, the final dataset included 359 unique records related to Parkinson disease.
----------------------------------------
Entries retrieved: 359

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1324,TOLCAPONE,MONDO_0005180,Parkinson disease,4.0,NaN,Small molecule,MONDO_0005180,Parkinson disease

 Run 3 completed | rows=359 | latency=16.970s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The goal of the query was to find disease-drug associations related to Parkinson's disease. First, the system retrieved known disease associations for Parkinson disease, resulting in 855 entries. Then, the system removed duplicate records from these entries, which reduced the number of results from 855 to 359. Therefore, after filtering and deduplication, there are 359 unique records related to Parkinson's disease.
----------------------------------------
Entries retrieved: 359

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1324,TOLCAPONE,MONDO_0005180,Parkinson disease,4.0,NaN,Small molecule,MONDO_0005180,Parkinson disease

 Run 4 completed | rows=359 | latency=18.176s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The purpose of this query was to retrieve associations related to Parkinson's disease. The process began with retrieving known disease–drug associations for Parkinson's disease, which initially resulted in 855 records. After this, duplicate entries were removed to ensure unique data, which reduced the number of records from 855 to 359. In summary, the final result included 359 distinct associations related to Parkinson's disease.
----------------------------------------
Entries retrieved: 359

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1324,TOLCAPONE,MONDO_0005180,Parkinson disease,4.0,NaN,Small molecule,MONDO_0005180,Parkinson disease

 Run 5 completed | rows=359 | latency=17.919s
------------------------------------------------------------


## Question 32

**Which drugs are used to treat inflammatory bowel disease?**

In [34]:

question = 'Which drugs are used to treat inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query was designed to find information related to inflammatory bowel disease and its associations.
[disease_tool]: Initially, the system retrieved known disease–drug associations related to inflammatory bowel disease, resulting in 1,282 records.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, which reduced the number of records from 1,282 to 607.
[disease_tool]: The final result contains 607 unique records related to inflammatory bowel disease associations.
----------------------------------------
Entries retrieved: 607

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201835,USTEKINUMAB,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,EFO_0000729,ulcerative colitis

 Run 1 completed | rows=607 | latency=29.322s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease–drug associations related to inflammatory bowel disease.
[disease_tool]: Initially, the system retrieved a list of 1,282 known disease associations for inflammatory bowel disease. Subsequently, it removed duplicate records from this list, reducing the total from 1,282 to 607, thus ensuring each association was unique.
[disease_tool]: In summary, the final result set contained 607 distinct disease associations related to inflammatory bowel disease.
----------------------------------------
Entries retrieved: 607

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201835,USTEKINUMAB,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,EFO_0000729,ulcerative colitis

 Run 2 completed | rows=607 | latency=21.235s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to find specific disease-related information involving inflammatory bowel disease.
[disease_tool]: Initially, the system retrieved known associations between diseases and drugs related to inflammatory bowel disease, resulting in 1282 records.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, reducing the dataset from 1282 to 607 unique records.
[disease_tool]: This process compiled a refined list of disease associations related to inflammatory bowel disease, with a total of 607 unique entries remaining.
----------------------------------------
Entries retrieved: 607

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201835,USTEKINUMAB,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,EFO_0000729,ulcerative colitis

 Run 3 completed | rows=607 | latency=19.436s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to identify specific disease-drug associations related to inflammatory bowel disease.
[disease_tool]: Initially, the system retrieved a set of 1,282 known associations between diseases and drugs related to inflammatory bowel disease. This provided a broad base of data for further filtering.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, which reduced the set from 1,282 to 607 unique entries. This step ensured that only distinct disease-drug association records remained.
[disease_tool]: In summary, after retrieving the associations and removing duplicates, the final dataset contained 607 unique disease-drug associations related to inflammatory bowel disease.
----------------------------------------
Entries retrieved: 607

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201835,USTEKINUMAB,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,EFO_0000729,ulcerative colitis

 Run 4 completed | rows=607 | latency=23.154s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to inflammatory bowel disease, focusing on associated diseases and drugs.
[disease_tool]: First, the system retrieved known disease associations related to inflammatory bowel disease, initially gathering 1,282 entries.
[disease_tool]: Next, the process involved deduplicating this set of data to remove any duplicate records, which reduced the total from 1,282 to 607 entries. This step ensured the dataset contained only unique records, making subsequent analysis more efficient.
[disease_tool]: In summary, after these filtering steps, the dataset consisted of 607 unique disease association records related to inflammatory bowel disease.
----------------------------------------
Entries retrieved: 607

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL1201835,USTEKINUMAB,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,EFO_0000729,ulcerative colitis

 Run 5 completed | rows=607 | latency=19.562s
------------------------------------------------------------


## Question 33

**Which targets are acted on by imatinib?**

In [35]:

question = 'Which targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve information related to the drug imatinib.
[drug_tool]: Initially, the system retrieved a set of 920 known associations between drugs and diseases related to imatinib. This step involved gathering all relevant disease–drug connections associated with imatinib before applying any filters.
[drug_tool]: Next, the system performed deduplication to eliminate duplicate entries from the retrieved data. This process reduced the number of association records from 920 to just 4 unique entries, ensuring that the final dataset contained only distinct disease–drug associations linked to imatinib.
[drug_tool]: In summary, after retrieving all relevant associations and removing duplicates, the final result consisted of 4 unique records related to imatinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,KIT,CHEMBL941,IMATINIB,Stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 1 completed | rows=4 | latency=17.242s
------------------------------------------------------------

 Starting run 2 for query: Which targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations for imatinib. First, the system retrieved known associations related to imatinib, resulting in 920 entries. Next, it removed duplicate records from these associations, reducing the total number of entries from 920 to 4. In the end, only 4 unique associations for imatinib remained after deduplication.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,KIT,CHEMBL941,IMATINIB,Stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 2 completed | rows=4 | latency=14.991s
------------------------------------------------------------

 Starting run 3 for query: Which targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to imatinib. First, the system retrieved the base associations for imatinib, resulting in 920 records. Next, it removed duplicate entries, which greatly reduced the result set from 920 to just 4 unique records. The final result contains 4 distinct drug association entries after deduplication.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,KIT,CHEMBL941,IMATINIB,Stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 3 completed | rows=4 | latency=13.453s
------------------------------------------------------------

 Starting run 4 for query: Which targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aims to find drug associations related to imatinib.
[drug_tool]: Initially, the system retrieved all known disease–drug associations for imatinib. This retrieval resulted in 920 records. Afterwards, the system performed a deduplication process, which removed duplicate entries from these associations. After this step, only 4 unique records remained, indicating that most of the original associations were duplicates.
[drug_tool]: In summary, the process filtered down from 920 associations to just 4 unique entries.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,KIT,CHEMBL941,IMATINIB,Stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 4 completed | rows=4 | latency=17.112s
------------------------------------------------------------

 Starting run 5 for query: Which targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to imatinib.
[drug_tool]: First, the system retrieved known drug associations for imatinib, initially obtaining 920 entries. Next, it performed deduplication to remove duplicate records, reducing the total from 920 to 4 unique entries.
[drug_tool]: In summary, after these steps, the final result includes 4 distinct drug associations related to imatinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,KIT,CHEMBL941,IMATINIB,Stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 5 completed | rows=4 | latency=15.051s
------------------------------------------------------------


## Question 34

**Which biological targets does sorafenib interact with?**

In [36]:

question = 'Which biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The query was designed to find drug associations related to sorafenib. First, the system retrieved the known associations for sorafenib, which initially resulted in 2,799 records. Next, the system removed duplicate entries from this set, reducing the total number of records from 2,799 to 9. This process ensured that only unique association data remained. In total, the final result consists of 9 distinct records related to sorafenib.
----------------------------------------
Entries retrieved: 9

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,PDGFRB,CHEMBL1336,SORAFENIB,Platelet-derived growth factor receptor beta i...,FDA

 Run 1 completed | rows=9 | latency=16.718s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The purpose of this query was to find associations related to the drug sorafenib.
[drug_tool]: First, the system retrieved all known disease–drug associations specifically for sorafenib, resulting in a total of 2,799 entries. This step gathered the initial set of data that linked sorafenib to various diseases.
[drug_tool]: Next, the system removed duplicate records from this collection. This deduplication process reduced the total number of entries from 2,799 to just 9, eliminating redundant data to ensure more accurate analysis.
[drug_tool]: In summary, after retrieving all associations for sorafenib and removing duplicates, there were 9 unique association records remaining.
----------------------------------------
Entries retrieved: 9

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,PDGFRB,CHEMBL1336,SORAFENIB,Platelet-derived growth factor receptor beta i...,FDA

 Run 2 completed | rows=9 | latency=16.078s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The query aimed to identify drugs associated with a specific drug, sorafenib.
[drug_tool]: Initially, the system retrieved a broad set of known associations for sorafenib, resulting in 2,799 rows. This step gathered all potential disease or drug-related associations linked to sorafenib without applying any filters.
[drug_tool]: Next, the system performed deduplication to eliminate duplicate entries from the data set. This process reduced the number of association records significantly from 2,799 down to 9, leaving a more concise list of unique associations related to sorafenib.
[drug_tool]: In total, the process ended with a final set of 9 unique associations for sorafenib.
----------------------------------------
Entries retrieved: 9

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,PDGFRB,CHEMBL1336,SORAFENIB,Platelet-derived growth factor receptor beta i...,FDA

 Run 3 completed | rows=9 | latency=14.293s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The goal of the query was to find drug associations related to sorafenib.
[drug_tool]: First, the system retrieved base disease–drug associations for sorafenib, resulting in 2,799 records. This step gathered all known associations without filtering or narrowing down at this stage.
[drug_tool]: Next, the system removed duplicate records from these initial results, reducing the number of entries from 2,799 to 9. This deduplication process ensured that only unique association entries remained.
[drug_tool]: In total, after executing the steps, the final set included 9 unique disease–drug associations for sorafenib.
----------------------------------------
Entries retrieved: 9

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,PDGFRB,CHEMBL1336,SORAFENIB,Platelet-derived growth factor receptor beta i...,FDA

 Run 4 completed | rows=9 | latency=16.754s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to sorafenib.
[drug_tool]: First, the system retrieved known disease–drug associations for sorafenib, which initially resulted in 2,799 records.
[drug_tool]: Next, the system removed duplicate records from these associations, reducing the number of entries from 2,799 to 9.
[drug_tool]: In total, the process narrowed down the initial broad set of associations to a small, distinct group of 9 records, providing a more focused result.
----------------------------------------
Entries retrieved: 9

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,PDGFRB,CHEMBL1336,SORAFENIB,Platelet-derived growth factor receptor beta i...,FDA

 Run 5 completed | rows=9 | latency=14.763s
------------------------------------------------------------


## Question 35

**Which biological targets does tofacitinib interact with?**

In [37]:

question = 'Which biological targets does tofacitinib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations for tofacitinib.
[drug_tool]: First, the system retrieved known disease–drug associations specifically related to tofacitinib. This initial retrieval yielded 280 rows.
[drug_tool]: Next, the system performed deduplication to remove any duplicate entries. After this step, the number of rows was reduced from 280 to 4, effectively eliminating 276 duplicate records.
[drug_tool]: In summary, the final result contains 4 unique disease–drug association entries for tofacitinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,TYK2,CHEMBL221959,TOFACITINIB,Janus Kinase (JAK) inhibitor,Expert

 Run 1 completed | rows=4 | latency=16.736s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
[drug_tool]: The query aimed to find drug associations for tofacitinib.
[drug_tool]: First, the system retrieved all known drug associations related to tofacitinib, resulting in 280 entries.
[drug_tool]: Next, it removed duplicate records, reducing the list from 280 to 4 unique entries.
[drug_tool]: In total, the process ended with 4 distinct drug association records for tofacitinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,TYK2,CHEMBL221959,TOFACITINIB,Janus Kinase (JAK) inhibitor,Expert

 Run 2 completed | rows=4 | latency=13.840s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
[drug_tool]: The query aimed to find drug associations related to tofacitinib. The first step involved retrieving known associations involving tofacitinib, which initially resulted in 280 entries.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries. This step reduced the number of entries from 280 to 4, removing 276 duplicate rows.
[drug_tool]: In the end, the process yielded 4 unique association records involving tofacitinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,TYK2,CHEMBL221959,TOFACITINIB,Janus Kinase (JAK) inhibitor,Expert

 Run 3 completed | rows=4 | latency=17.867s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
[drug_tool]: The goal of the query was to identify associations related to the drug tofacitinib.
[drug_tool]: First, the system retrieved the known disease–drug associations for tofacitinib, which initially resulted in 280 records.
[drug_tool]: Next, to refine the data, it removed duplicate records, reducing the number from 280 to 4 entries.
[drug_tool]: This process resulted in a final set of 4 distinct associations related to tofacitinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,TYK2,CHEMBL221959,TOFACITINIB,Janus Kinase (JAK) inhibitor,Expert

 Run 4 completed | rows=4 | latency=12.908s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
[drug_tool]: The query was designed to identify associations between a specific disease and drugs, and to further analyze their mechanisms and pathways.
[drug_tool]: Since the execution log is empty, no steps were performed. As a result, the system did not retrieve any data, apply any filters, or refine the results at any point.
[drug_tool]: In summary, there are no retrieved or filtered entries, and the final result set remains empty.
----------------------------------------
[drug_tool]: The user's query aimed to identify drugs associated with specific diseases and mechanisms of action. However, in this particular case, there are no execution steps provided in the log to describe. Therefore, I cannot detail the processing steps or how the filters were applied. The final result set is not available in this instance.
----------------------------------------
[drug_tool]: The query's intent appears to be to retrieve information related to diseases and their associated drugs, focusing on mechanisms of action and pathway details. However, the execution log indicates that no steps were performed during the process.
[drug_tool]: Since there are no recorded steps, no filters or retrievals took place. This means the system did not fetch any disease–drug associations, apply any disease or drug filters, retrieve pathway information, or perform any deduplication.
[drug_tool]: In summary, because the execution log contains no steps, no results were obtained, and the search did not produce any data.
----------------------------------------
[drug_tool]: The provided execution log contains no steps, which suggests that no processing was performed or recorded for this query. Therefore, no filtering or retrieval actions occurred, and there is no data to describe regarding disease associations, drug filtering, mechanism-of-action filtering, deduplication, or pathway retrieval. As a result, there are no results to report.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.003s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[drug_tool]: The query aimed to retrieve drug-related information specifically for tofacitinib. First, the system retrieved known disease–drug associations related to tofacitinib, which initially resulted in an unspecified number of entries. After that, the system performed a deduplication step to remove duplicate records, reducing the total from 280 to just 4 unique entries. The final result contains 4 distinct associations related to tofacitinib.
----------------------------------------
Entries retrieved: 4

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,TYK2,CHEMBL221959,TOFACITINIB,Janus Kinase (JAK) inhibitor,Expert

 Run 5 completed | rows=4 | latency=14.517s
------------------------------------------------------------


## Question 36

**Which drugs target EGFR?**

In [38]:

question = 'Which drugs target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target EGFR?
  Attempt 1/3
[target_tool]: The query aimed to identify specific drug associations related to the target gene EGFR. The process started with the retrieval of known disease–drug associations for EGFR, which initially resulted in 1,870 records. No duplicates had been eliminated at that point. Following this, the system removed duplicate rows, reducing the total from 1,870 to 510 unique entries. This final number of 510 records represents the deduplicated set of disease–drug associations associated with EGFR.
----------------------------------------
Entries retrieved: 510

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,EGFR,CHEMBL1201179,LAPATINIB DITOSYLATE,4.0,NaN,NaN,Epidermal growth factor receptor erbB1 inhibitor

 Run 1 completed | rows=510 | latency=18.537s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target EGFR?
  Attempt 1/3
[target_tool]: The query aimed to retrieve associations related to the target EGFR. Initially, the system retrieved a total of 1,870 known disease-drug associations for EGFR. Next, duplicate entries within this dataset were removed in a deduplication step, which reduced the number of associations from 1,870 to 510. In the end, the final result contained 510 unique association records.
----------------------------------------
Entries retrieved: 510

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,EGFR,CHEMBL1201179,LAPATINIB DITOSYLATE,4.0,NaN,NaN,Epidermal growth factor receptor erbB1 inhibitor

 Run 2 completed | rows=510 | latency=19.476s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target EGFR?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target EGFR, including potential drugs and mechanisms.
[target_tool]: First, the system retrieved the base set of known disease–drug associations for EGFR, resulting in 1,870 rows. This initial step compiled all relevant associations without any filtering.
[target_tool]: Next, the system performed deduplication to remove duplicate entries from this dataset. After this process, the dataset was reduced from 1,870 to 510 unique entries.
[target_tool]: In summary, the process filtered the initial set of associations for EGFR to a final collection of 510 unique records, providing a more concise and non-redundant result set.
----------------------------------------
Entries retrieved: 510

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,EGFR,CHEMBL1201179,LAPATINIB DITOSYLATE,4.0,NaN,NaN,Epidermal growth factor receptor erbB1 inhibitor

 Run 3 completed | rows=510 | latency=17.344s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target EGFR?
  Attempt 1/3
[target_tool]: The purpose of the query was to identify relevant drug associations for the target EGFR.
[target_tool]: Initially, the system retrieved a total of 1,870 known disease–drug associations related to EGFR. Next, to ensure data quality and eliminate redundant information, duplicate rows were removed, reducing the number of associations from 1,870 to 510.
[target_tool]: Overall, after these steps, the final result included 510 unique associations related to EGFR.
----------------------------------------
Entries retrieved: 510

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,EGFR,CHEMBL1201179,LAPATINIB DITOSYLATE,4.0,NaN,NaN,Epidermal growth factor receptor erbB1 inhibitor

 Run 4 completed | rows=510 | latency=14.831s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target EGFR?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve and process disease–drug association data related to the target EGFR.
[target_tool]: First, the system retrieved known associations for this target, resulting in 1,870 rows of data.
[target_tool]: Next, the process included a deduplication step where duplicate records were removed, reducing the total from 1,870 to 510 unique entries.
[target_tool]: Overall, after filtering out duplicates, the final result contained 510 distinct associations related to EGFR.
----------------------------------------
Entries retrieved: 510

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,EGFR,CHEMBL1201179,LAPATINIB DITOSYLATE,4.0,NaN,NaN,Epidermal growth factor receptor erbB1 inhibitor

 Run 5 completed | rows=510 | latency=14.577s
------------------------------------------------------------


## Question 37

**Which diseases are associated with TP53?**

In [39]:

question = 'Which diseases are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with TP53?
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 1 completed | rows=3258 | latency=18.414s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with TP53?
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 2 completed | rows=3258 | latency=14.638s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with TP53?
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 3 completed | rows=3258 | latency=15.374s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with TP53?
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 4 completed | rows=3258 | latency=14.397s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with TP53?
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 5 completed | rows=3258 | latency=14.734s
------------------------------------------------------------


## Question 38

**Which diseases are associated with FGFR2?**

In [40]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: Retrieved 1639 diseases for target FGFR2.
----------------------------------------
Entries retrieved: 1639

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000066468,FGFR2,MONDO_0007405,Crouzon syndrome,0.863721

 Run 1 completed | rows=1639 | latency=23.967s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: Retrieved 1639 diseases for target FGFR2.
----------------------------------------
Entries retrieved: 1639

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000066468,FGFR2,MONDO_0007405,Crouzon syndrome,0.863721

 Run 2 completed | rows=1639 | latency=15.773s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: Retrieved 1639 diseases for target FGFR2.
----------------------------------------
Entries retrieved: 1639

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000066468,FGFR2,MONDO_0007405,Crouzon syndrome,0.863721

 Run 3 completed | rows=1639 | latency=14.529s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: Retrieved 1639 diseases for target FGFR2.
----------------------------------------
Entries retrieved: 1639

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000066468,FGFR2,MONDO_0007405,Crouzon syndrome,0.863721

 Run 4 completed | rows=1639 | latency=13.458s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: Retrieved 1639 diseases for target FGFR2.
----------------------------------------
Entries retrieved: 1639

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000066468,FGFR2,MONDO_0007405,Crouzon syndrome,0.863721

 Run 5 completed | rows=1639 | latency=14.858s
------------------------------------------------------------


## Question 39

**Which diseases are associated with HTT?**

In [41]:

question = 'Which diseases are associated with HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with HTT?
  Attempt 1/3
[target_tool]: Retrieved 562 diseases for target HTT.
----------------------------------------
Entries retrieved: 562

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000197386,HTT,MONDO_0007739,Huntington disease,0.708144

 Run 1 completed | rows=562 | latency=13.427s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with HTT?
  Attempt 1/3
[target_tool]: Retrieved 562 diseases for target HTT.
----------------------------------------
Entries retrieved: 562

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000197386,HTT,MONDO_0007739,Huntington disease,0.708144

 Run 2 completed | rows=562 | latency=12.266s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with HTT?
  Attempt 1/3
[target_tool]: Retrieved 562 diseases for target HTT.
----------------------------------------
Entries retrieved: 562

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000197386,HTT,MONDO_0007739,Huntington disease,0.708144

 Run 3 completed | rows=562 | latency=13.013s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with HTT?
  Attempt 1/3
[target_tool]: Retrieved 562 diseases for target HTT.
----------------------------------------
Entries retrieved: 562

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000197386,HTT,MONDO_0007739,Huntington disease,0.708144

 Run 4 completed | rows=562 | latency=11.584s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with HTT?
  Attempt 1/3
[target_tool]: Retrieved 562 diseases for target HTT.
----------------------------------------
Entries retrieved: 562

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000197386,HTT,MONDO_0007739,Huntington disease,0.708144

 Run 5 completed | rows=562 | latency=13.229s
------------------------------------------------------------


## Question 40

**Which genes are associated with breast cancer?**

In [42]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
 Attempt 1 failed after 30.008s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
 Attempt 2 failed after 30.006s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: Retrieved 14833 targets for disease breast cancer.
----------------------------------------
Entries retrieved: 14833

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0007254,breast cancer,ENSG00000139618,BRCA2,BRCA2 DNA repair associated,0.91741

 Run 1 completed | rows=14833 | latency=27.340s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14833 targets for disease breast cancer.
----------------------------------------
Entries retrieved: 14833

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0007254,breast cancer,ENSG00000139618,BRCA2,BRCA2 DNA repair associated,0.91741

 Run 2 completed | rows=14833 | latency=25.029s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14833 targets for disease breast cancer.
----------------------------------------
Entries retrieved: 14833

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0007254,breast cancer,ENSG00000139618,BRCA2,BRCA2 DNA repair associated,0.91741

 Run 3 completed | rows=14833 | latency=22.460s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14833 targets for disease breast cancer.
----------------------------------------
Entries retrieved: 14833

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0007254,breast cancer,ENSG00000139618,BRCA2,BRCA2 DNA repair associated,0.91741

 Run 4 completed | rows=14833 | latency=18.587s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14833 targets for disease breast cancer.
----------------------------------------
Entries retrieved: 14833

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0007254,breast cancer,ENSG00000139618,BRCA2,BRCA2 DNA repair associated,0.91741

 Run 5 completed | rows=14833 | latency=22.375s
------------------------------------------------------------


## Question 41

**Which genes are associated with colorectal cancer?**

In [43]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
 Attempt 1 failed after 30.007s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: Retrieved 14200 targets for disease colorectal cancer.
----------------------------------------
 Attempt 2 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: Retrieved 14200 targets for disease colorectal cancer.
----------------------------------------
Entries retrieved: 14200

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005575,colorectal cancer,ENSG00000095002,MSH2,mutS homolog 2,0.924764

 Run 1 completed | rows=14200 | latency=25.892s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14200 targets for disease colorectal cancer.
----------------------------------------
Entries retrieved: 14200

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005575,colorectal cancer,ENSG00000095002,MSH2,mutS homolog 2,0.924764

 Run 2 completed | rows=14200 | latency=21.624s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14200 targets for disease colorectal cancer.
----------------------------------------
Entries retrieved: 14200

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005575,colorectal cancer,ENSG00000095002,MSH2,mutS homolog 2,0.924764

 Run 3 completed | rows=14200 | latency=23.593s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14200 targets for disease colorectal cancer.
----------------------------------------
Entries retrieved: 14200

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005575,colorectal cancer,ENSG00000095002,MSH2,mutS homolog 2,0.924764

 Run 4 completed | rows=14200 | latency=19.548s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: Retrieved 14200 targets for disease colorectal cancer.
----------------------------------------
Entries retrieved: 14200

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005575,colorectal cancer,ENSG00000095002,MSH2,mutS homolog 2,0.924764

 Run 5 completed | rows=14200 | latency=24.279s
------------------------------------------------------------


## Question 42

**Which genes are associated with cystic fibrosis?**

In [44]:

question = 'Which genes are associated with cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
[disease_tool]: Retrieved 3693 targets for disease cystic fibrosis.
----------------------------------------
Entries retrieved: 3693

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0009061,cystic fibrosis,ENSG00000001626,CFTR,CF transmembrane conductance regulator,0.913383

 Run 1 completed | rows=3693 | latency=16.990s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
[disease_tool]: Retrieved 3693 targets for disease cystic fibrosis.
----------------------------------------
Entries retrieved: 3693

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0009061,cystic fibrosis,ENSG00000001626,CFTR,CF transmembrane conductance regulator,0.913383

 Run 2 completed | rows=3693 | latency=15.193s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
[disease_tool]: Retrieved 3693 targets for disease cystic fibrosis.
----------------------------------------
Entries retrieved: 3693

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0009061,cystic fibrosis,ENSG00000001626,CFTR,CF transmembrane conductance regulator,0.913383

 Run 3 completed | rows=3693 | latency=14.678s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
[disease_tool]: Retrieved 3693 targets for disease cystic fibrosis.
----------------------------------------
Entries retrieved: 3693

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0009061,cystic fibrosis,ENSG00000001626,CFTR,CF transmembrane conductance regulator,0.913383

 Run 4 completed | rows=3693 | latency=12.593s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
[disease_tool]: Retrieved 3693 targets for disease cystic fibrosis.
----------------------------------------
Entries retrieved: 3693

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0009061,cystic fibrosis,ENSG00000001626,CFTR,CF transmembrane conductance regulator,0.913383

 Run 5 completed | rows=3693 | latency=17.353s
------------------------------------------------------------


## Question 43

**Which drugs are used to treat TNBC?**

In [45]:

question = 'Which drugs are used to treat TNBC?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to triple-negative breast cancer. First, the system retrieved known disease–drug associations related to this disease, resulting in 856 entries. Next, it removed duplicate records from this set of data, reducing the number of entries from 856 to 227. In summary, the final result consists of 227 unique records associated with triple-negative breast cancer.
----------------------------------------
Entries retrieved: 227

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3545262,SACITUZUMAB GOVITECAN,EFO_0005537,triple-negative breast cancer,4.0,NaN,Antibody drug conjugate,EFO_0005537,triple-negative breast cancer

 Run 1 completed | rows=227 | latency=24.140s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
[disease_tool]: The query aimed to analyze disease associations related to triple-negative breast cancer. First, the system retrieved known disease-drug associations for this disease, resulting in a set of 856 entries. Next, it performed a deduplication step to remove duplicate records, which reduced the total from 856 to 227 entries. This final count of 227 entries represents the unique associations related to triple-negative breast cancer after duplicates were eliminated.
----------------------------------------
Entries retrieved: 227

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3545262,SACITUZUMAB GOVITECAN,EFO_0005537,triple-negative breast cancer,4.0,NaN,Antibody drug conjugate,EFO_0005537,triple-negative breast cancer

 Run 2 completed | rows=227 | latency=18.382s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
[disease_tool]: The goal of the query was to analyze disease associations related to triple-negative breast cancer.
[disease_tool]: First, the system retrieved the known disease–drug associations for triple-negative breast cancer, resulting in 856 entries. This step involved searching a database for records linked to this specific disease.
[disease_tool]: Next, to ensure the data was unique and to avoid duplicate information, the system performed a deduplication process. This step reduced the number of records from 856 to 227, removing 629 duplicate rows and leaving a set of unique associations.
[disease_tool]: In total, the process ended with 227 distinct records related to the disease.
----------------------------------------
Entries retrieved: 227

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3545262,SACITUZUMAB GOVITECAN,EFO_0005537,triple-negative breast cancer,4.0,NaN,Antibody drug conjugate,EFO_0005537,triple-negative breast cancer

 Run 3 completed | rows=227 | latency=21.486s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
[disease_tool]: This query aims to identify disease and drug associations related to triple-negative breast cancer.
[disease_tool]: First, the system retrieved base disease associations for triple-negative breast cancer, resulting in 856 records. This step gathered all known disease–drug relationships for the specified disease.
[disease_tool]: Next, the process involved removing duplicate records to ensure each association was unique. This deduplication step reduced the total number of records from 856 to 227.
[disease_tool]: In summary, after these steps, there are 227 unique disease–drug associations related to triple-negative breast cancer.
----------------------------------------
Entries retrieved: 227

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3545262,SACITUZUMAB GOVITECAN,EFO_0005537,triple-negative breast cancer,4.0,NaN,Antibody drug conjugate,EFO_0005537,triple-negative breast cancer

 Run 4 completed | rows=227 | latency=15.863s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
[disease_tool]: The query was designed to retrieve disease–drug associations related to triple-negative breast cancer.
[disease_tool]: First, the system retrieved the known disease associations for triple-negative breast cancer, resulting in 856 entries. Next, to ensure the quality of the data, duplicate rows were removed, reducing the number of entries from 856 to 227.
[disease_tool]: In summary, after these steps, the data set was narrowed down to 227 unique disease association records for triple-negative breast cancer.
----------------------------------------
Entries retrieved: 227

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL3545262,SACITUZUMAB GOVITECAN,EFO_0005537,triple-negative breast cancer,4.0,NaN,Antibody drug conjugate,EFO_0005537,triple-negative breast cancer

 Run 5 completed | rows=227 | latency=18.098s
------------------------------------------------------------


## Question 44

**Which diseases are treated with metformin?**

In [46]:

question = 'Which diseases are treated with metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with metformin?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to metformin. First, the system retrieved a total of 20,298 known drug associations involving metformin. Then, to eliminate duplicate entries, a deduplication process was applied, which reduced the number of associations from 20,298 to 796. This process removed 19,502 duplicate records, leaving a refined set of 796 unique associations.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,METFORMIN,EFO_0000400,diabetes mellitus,4.0,Recruiting,Mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 1 completed | rows=796 | latency=25.969s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with metformin?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to metformin.
[drug_tool]: Initially, the system retrieved 20,298 drug association entries for metformin. This step collected a comprehensive set of potential associations.
[drug_tool]: Next, the deduplication process was performed to remove duplicate records. After this step, the number of entries was reduced to 796, meaning that 19,502 duplicate entries were eliminated, leaving a set of unique association records related to metformin.
[drug_tool]: In summary, the final result consists of 796 unique drug association records for metformin.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,METFORMIN,EFO_0000400,diabetes mellitus,4.0,Recruiting,Mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 2 completed | rows=796 | latency=24.414s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with metformin?
  Attempt 1/3
[drug_tool]: The goal of this query was to retrieve and refine information related to drug associations for the drug metformin. First, the system retrieved a large set of known drug associations related to metformin, resulting in 20,298 entries. This step involved collecting all relevant association data before any filtering.
[drug_tool]: Next, to ensure the data was accurate and free from redundancies, the system performed deduplication. This step removed duplicate rows from the retrieved set, reducing the number of entries from 20,298 to 796. This process eliminated redundant data, leaving a cleaner, more manageable set of unique records.
[drug_tool]: In summary, the process started with a broad collection of over twenty thousand association records and was refined down to 796 unique associations for metformin, ensuring the data was both comprehensive and non-redundant.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,METFORMIN,EFO_0000400,diabetes mellitus,4.0,Recruiting,Mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 3 completed | rows=796 | latency=23.753s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with metformin?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug metformin.
[drug_tool]: First, the system retrieved known associations between drugs and diseases related to metformin. This initial step resulted in a list of 20,298 associations.
[drug_tool]: Next, the system removed duplicate entries from this list. After deduplication, the number of unique associations was reduced to 796.
[drug_tool]: In summary, the process started with over twenty thousand associations and, after removing duplicates, resulted in 796 unique entries related to metformin.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,METFORMIN,EFO_0000400,diabetes mellitus,4.0,Recruiting,Mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 4 completed | rows=796 | latency=23.012s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with metformin?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to metformin.
[drug_tool]: First, the system retrieved a large set of known drug associations for metformin, resulting in 20,298 records. This initial step gathered all potential data points related to the drug.
[drug_tool]: Next, the system removed duplicate entries from this dataset. After deduplication, the number of records was reduced significantly from 20,298 to 796. This step ensures that only unique association entries remain for further analysis.
[drug_tool]: In summary, after the filtering steps, the dataset contained 796 unique drug association records related to metformin.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,METFORMIN,EFO_0000400,diabetes mellitus,4.0,Recruiting,Mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 5 completed | rows=796 | latency=22.078s
------------------------------------------------------------


## Question 45

**Which diseases are treated with adalimumab?**

In [47]:

question = 'Which diseases are treated with adalimumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
[drug_tool]: The query aimed to explore the relationships between a specific drug, adalimumab, and its associated diseases.
[drug_tool]: Initially, the system retrieved the known associations related to adalimumab, resulting in a total of 131 entries. This step provided a comprehensive list of disease–drug relationships tied to adalimumab before applying further filters.
[drug_tool]: Since only one step is shown in the execution log, the process ends with 131 associations related to adalimumab.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,ADALIMUMAB,EFO_0000384,Crohn's disease,4.0,Enrolling by invitation,TNF-alpha inhibitor,DailyMed

 Run 1 completed | rows=131 | latency=17.846s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to adalimumab.
[drug_tool]: First, the system retrieved known disease–drug associations for adalimumab, resulting in 131 entries.
[drug_tool]: Since no further filters such as disease, drug, or mechanism filters are shown in the provided log, the process focused solely on this initial retrieval. The system then performed additional steps, although they are not detailed in the snippet provided.
[drug_tool]: In the end, the final number of associations related to adalimumab remaining after all processes is 131 entries.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,ADALIMUMAB,EFO_0000384,Crohn's disease,4.0,Enrolling by invitation,TNF-alpha inhibitor,DailyMed

 Run 2 completed | rows=131 | latency=13.353s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
[drug_tool]: The query aims to identify drugs associated with certain diseases, with a particular focus on adalimumab.
[drug_tool]: In the first step, the system retrieved the basic known associations between drugs and diseases related to adalimumab. This resulted in 131 records, providing a foundation of drug-disease links for further analysis.
[drug_tool]: However, based on the provided information, there are no additional filtering steps shown, so the result currently includes these 131 associations.
[drug_tool]: In summary, the final dataset contains 131 drug association records related to adalimumab, after the initial retrieval step.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,ADALIMUMAB,EFO_0000384,Crohn's disease,4.0,Enrolling by invitation,TNF-alpha inhibitor,DailyMed

 Run 3 completed | rows=131 | latency=13.855s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
[drug_tool]: The query aims to identify associations involving the drug adalimumab. The first step in the process retrieved known disease-drug associations related to adalimumab, resulting in 131 entries. This initial retrieval provided a broad set of data without applying any filters at this stage. Since no further filtering steps are detailed in this part of the log, the process primarily focused on collecting all known associations for adalimumab to serve as the foundation for subsequent analysis.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,ADALIMUMAB,EFO_0000384,Crohn's disease,4.0,Enrolling by invitation,TNF-alpha inhibitor,DailyMed

 Run 4 completed | rows=131 | latency=13.368s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve drug associations related to adalimumab. First, the system collected base associations for this drug, resulting in 131 records. This step provided a starting dataset of known drug-disease relationships involving adalimumab. Since no previous number of records is provided, we only know that this initial collection included 131 entries.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,ADALIMUMAB,EFO_0000384,Crohn's disease,4.0,Enrolling by invitation,TNF-alpha inhibitor,DailyMed

 Run 5 completed | rows=131 | latency=13.625s
------------------------------------------------------------


## Question 46

**For which diseases is pembrolizumab used?**

In [48]:

question = 'For which diseases is pembrolizumab used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to pembrolizumab.
[drug_tool]: The first step involved retrieving known associations between pembrolizumab and various diseases or conditions. This initial retrieval resulted in 815 entries, providing a broad set of possible relationships to analyze further.
[drug_tool]: No further filtering steps are shown in this log, so the initial set of 815 associations remains the primary result.
[drug_tool]: Overall, the process started with a broad collection of associative data related to pembrolizumab, ending with a total of 815 entries in the dataset.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,PEMBROLIZUMAB,MONDO_0021251,endometrium neoplasm,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 1 completed | rows=815 | latency=15.225s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug associations related to pembrolizumab. First, the system retrieved known disease–drug associations for pembrolizumab, resulting in an initial set of 815 entries. This step collected all existing known associations involving this drug. Since there were no previous associations retrieved or filters applied at this stage, the number after this step was 815. The overall number of associations found in this step is 815, providing a broad base for further filtering.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,PEMBROLIZUMAB,MONDO_0021251,endometrium neoplasm,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 2 completed | rows=815 | latency=12.195s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
[drug_tool]: The query aims to find information related to pembrolizumab, likely focusing on its associations with diseases or mechanisms.
[drug_tool]: The first step was association retrieval, where the system retrieved known drug associations for pembrolizumab. This initial step resulted in 815 associations, providing a broad base of data about the drug.
[drug_tool]: There are no further filtering steps shown in the current information. The process, as described, stopped after retrieving these 815 associations, so the final result set consists of 815 entries related to pembrolizumab.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,PEMBROLIZUMAB,MONDO_0021251,endometrium neoplasm,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 3 completed | rows=815 | latency=13.072s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
[drug_tool]: The purpose of the query was to find drugs related to pembrolizumab based on known disease–drug associations.
[drug_tool]: The first step involved retrieving all established associations for pembrolizumab by searching a database of disease–drug links. Before this retrieval, there was no specified number of entries, but after completing this step, 815 associations were identified, indicating the scope of known connections.
[drug_tool]: Since no further filtering steps are shown in the provided log, the process concluded with this initial set of 815 associations, representing the total number of disease–drug relationships retrieved for pembrolizumab in this step.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,PEMBROLIZUMAB,MONDO_0021251,endometrium neoplasm,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 4 completed | rows=815 | latency=12.933s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
[drug_tool]: The query aims to retrieve information about drugs associated with a specific biological context. Initially, the system performed an association retrieval step, during which it fetched known associations between drugs and diseases related to pembrolizumab. This step resulted in 815 entries, providing a foundational set of drug-disease associations for further analysis. The process then continued with additional filtering steps, but those are not detailed in this particular part of the log. In summary, the final result at this stage included 815 drug association records for pembrolizumab.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,PEMBROLIZUMAB,MONDO_0021251,endometrium neoplasm,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 5 completed | rows=815 | latency=13.588s
------------------------------------------------------------


## Question 47

**Which diseases are treated with sorafenib?**

In [49]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The intent of the query was to identify drugs associated with a specific target, sorafenib.
[drug_tool]: First, the system retrieved known disease–drug associations related to sorafenib, resulting in a total of 2,799 entries. This step provided the initial dataset of possible associations.
[drug_tool]: Next, the system performed deduplication to remove any duplicate records from this dataset. As a result, the number of entries was reduced from 2,799 to 2,177, removing 622 duplicate rows.
[drug_tool]: In summary, after retrieving the associations and removing duplicates, the final dataset contains 2,177 unique disease-related associations for sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,SORAFENIB,MONDO_0002691,liver cancer,3.0,Recruiting,Serine/threonine-protein kinase RAF inhibitor,FDA

 Run 1 completed | rows=2177 | latency=12.569s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The goal of the query was to retrieve and filter drug associations for the drug sorafenib.
[drug_tool]: First, the system retrieved known drug associations for sorafenib, resulting in a total of 2,799 entries. This initial retrieval brought back all known associations without applying any filters to reduce the dataset.
[drug_tool]: Next, the system removed duplicate records from this list. This deduplication step reduced the number of entries from 2,799 to 2,177, eliminating 622 duplicate rows to ensure that each association was unique.
[drug_tool]: In summary, after these steps, the result set was narrowed down to 2,177 unique drug association entries for sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,SORAFENIB,MONDO_0002691,liver cancer,3.0,Recruiting,Serine/threonine-protein kinase RAF inhibitor,FDA

 Run 2 completed | rows=2177 | latency=15.483s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The goal of this query was to retrieve and refine information related to the drug sorafenib.
[drug_tool]: First, the system retrieved all known disease-drug associations for sorafenib, resulting in a total of 2,799 rows. This step gathered a broad set of data linking the drug to various diseases.
[drug_tool]: Next, the system performed deduplication to remove duplicate entries from this data. After this process, the number of results was reduced from 2,799 to 2,177, meaning that 622 duplicate records were eliminated.
[drug_tool]: In summary, the final dataset contains 2,177 unique records of disease associations for sorafenib after duplicate removal.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,SORAFENIB,MONDO_0002691,liver cancer,3.0,Recruiting,Serine/threonine-protein kinase RAF inhibitor,FDA

 Run 3 completed | rows=2177 | latency=16.625s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The query was designed to identify drugs associated with a specific target, in this case, sorafenib.
[drug_tool]: First, the system retrieved known drug associations related to sorafenib, resulting in 2,799 entries.
[drug_tool]: Next, the process involved removing duplicate records from this set, which decreased the total from 2,799 to 2,177 entries, by eliminating 622 duplicate rows.
[drug_tool]: Finally, the resulting data set contains 2,177 unique drug association records for sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,SORAFENIB,MONDO_0002691,liver cancer,3.0,Recruiting,Serine/threonine-protein kinase RAF inhibitor,FDA

 Run 4 completed | rows=2177 | latency=13.047s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve and filter information related to drugs associated with sorafenib.
[drug_tool]: Initially, the system retrieved all known drug associations for sorafenib, resulting in 2,799 entries. This step gathered the initial comprehensive list of potential interactions or connections.
[drug_tool]: Next, the deduplication process was applied to remove any duplicate records from this list. After this step, the number of entries was reduced from 2,799 to 2,177, eliminating 622 redundant rows to ensure the list contained only unique entries.
[drug_tool]: In total, the process ended with 2,177 unique associations related to sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,SORAFENIB,MONDO_0002691,liver cancer,3.0,Recruiting,Serine/threonine-protein kinase RAF inhibitor,FDA

 Run 5 completed | rows=2177 | latency=16.051s
------------------------------------------------------------


## Question 48

**Which diseases are treated with nivolumab?**

In [50]:

question = 'Which diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to nivolumab.
[drug_tool]: First, the system retrieved known disease-drug associations specifically for nivolumab. This initial step resulted in 655 entries, though the original number of associations was not specified.
[drug_tool]: Next, no further filters such as disease filters, drug filters, or mechanism filtering were applied, so the result set remained at 655 entries.
[drug_tool]: Finally, no steps involving deduplication or pathway retrieval were mentioned in the provided log.
[drug_tool]: In conclusion, the final result includes 655 associations related to nivolumab after the initial retrieval.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,NIVOLUMAB,MONDO_0009348,classic Hodgkin lymphoma,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 1 completed | rows=655 | latency=14.302s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aimed to find associations related to the drug nivolumab.
[drug_tool]: First, the system retrieved the known disease–drug associations for nivolumab, resulting in 655 records. This step provided a broad set of potential links between nivolumab and various diseases.
[drug_tool]: Next, no specific filters were applied for diseases, drugs, mechanisms, pathways, or deduplication, so the number of entries remained at 655. Therefore, the initial retrieval gave the full set of known associations for nivolumab without further narrowing.
[drug_tool]: In conclusion, the final result consists of 655 known associations related to nivolumab, set up for further filtering or analysis if needed.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,NIVOLUMAB,MONDO_0009348,classic Hodgkin lymphoma,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 2 completed | rows=655 | latency=15.203s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aimed to find associations between the drug nivolumab and diseases or mechanisms of action.
[drug_tool]: First, the system retrieved the known associations related to nivolumab, specifically drug-disease or drug-mechanism links, which resulted in 655 entries.
[drug_tool]: Since this initial retrieval did not involve filtering by specific diseases or drugs, the result remained at 655 associations.
[drug_tool]: The process focused on the known drug associations for nivolumab, without applying further filters or additional steps, resulting in a total of 655 associations at this stage.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,NIVOLUMAB,MONDO_0009348,classic Hodgkin lymphoma,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 3 completed | rows=655 | latency=14.519s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aimed to find specific drug associations related to nivolumab. First, the system retrieved known associations between diseases and drugs for nivolumab, resulting in a total of 655 entries. This initial retrieval provided a foundation for further filtering based on the user's criteria. Since this was the first step, no prior result set was available to compare with. Overall, the process started with 655 retrieved disease–drug associations related to nivolumab.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,NIVOLUMAB,MONDO_0009348,classic Hodgkin lymphoma,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 4 completed | rows=655 | latency=11.929s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aimed to identify drugs associated with a specific condition, in this case, nivolumab.
[drug_tool]: The first step involved retrieving known disease-drug associations related to nivolumab. This initial association retrieval resulted in 655 records, providing a base set of data.
[drug_tool]: This was the only step described in the log, and no further filters or processes were applied afterwards.
[drug_tool]: Therefore, the final result of the query consists of 655 records related to nivolumab associations.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,NIVOLUMAB,MONDO_0009348,classic Hodgkin lymphoma,4.0,NaN,Programmed cell death protein 1 inhibitor,FDA

 Run 5 completed | rows=655 | latency=13.417s
------------------------------------------------------------


## Question 49

**Which genes are associated with multiple sclerosis?**

In [51]:

question = 'Which genes are associated with multiple sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 4737 targets for disease multiple sclerosis.
----------------------------------------
Entries retrieved: 4737

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005301,multiple sclerosis,ENSG00000113580,NR3C1,nuclear receptor subfamily 3 group C member 1,0.684313

 Run 1 completed | rows=4737 | latency=17.911s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 4737 targets for disease multiple sclerosis.
----------------------------------------
Entries retrieved: 4737

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005301,multiple sclerosis,ENSG00000113580,NR3C1,nuclear receptor subfamily 3 group C member 1,0.684313

 Run 2 completed | rows=4737 | latency=22.599s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 4737 targets for disease multiple sclerosis.
----------------------------------------
Entries retrieved: 4737

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005301,multiple sclerosis,ENSG00000113580,NR3C1,nuclear receptor subfamily 3 group C member 1,0.684313

 Run 3 completed | rows=4737 | latency=15.627s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 4737 targets for disease multiple sclerosis.
----------------------------------------
Entries retrieved: 4737

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005301,multiple sclerosis,ENSG00000113580,NR3C1,nuclear receptor subfamily 3 group C member 1,0.684313

 Run 4 completed | rows=4737 | latency=14.029s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
[disease_tool]: Retrieved 4737 targets for disease multiple sclerosis.
----------------------------------------
Entries retrieved: 4737

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0005301,multiple sclerosis,ENSG00000113580,NR3C1,nuclear receptor subfamily 3 group C member 1,0.684313

 Run 5 completed | rows=4737 | latency=13.685s
------------------------------------------------------------


## Question 50

**Which genes are associated with rheumatoid arthritis?**

In [52]:

question = 'Which genes are associated with rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: Retrieved 4950 targets for disease rheumatoid arthritis.
----------------------------------------
Entries retrieved: 4950

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000685,rheumatoid arthritis,ENSG00000160712,IL6R,interleukin 6 receptor,0.735062

 Run 1 completed | rows=4950 | latency=15.457s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: Retrieved 4950 targets for disease rheumatoid arthritis.
----------------------------------------
Entries retrieved: 4950

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000685,rheumatoid arthritis,ENSG00000160712,IL6R,interleukin 6 receptor,0.735062

 Run 2 completed | rows=4950 | latency=14.124s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: Retrieved 4950 targets for disease rheumatoid arthritis.
----------------------------------------
Entries retrieved: 4950

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000685,rheumatoid arthritis,ENSG00000160712,IL6R,interleukin 6 receptor,0.735062

 Run 3 completed | rows=4950 | latency=15.542s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: Retrieved 4950 targets for disease rheumatoid arthritis.
----------------------------------------
Entries retrieved: 4950

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000685,rheumatoid arthritis,ENSG00000160712,IL6R,interleukin 6 receptor,0.735062

 Run 4 completed | rows=4950 | latency=11.352s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: Retrieved 4950 targets for disease rheumatoid arthritis.
----------------------------------------
Entries retrieved: 4950

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000685,rheumatoid arthritis,ENSG00000160712,IL6R,interleukin 6 receptor,0.735062

 Run 5 completed | rows=4950 | latency=13.027s
------------------------------------------------------------


## Question 51

**What are the known targets of abatacept?**

In [53]:

question = 'What are the known targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of abatacept?
  Attempt 1/3
[drug_tool]: The query aimed to identify specific drug associations related to abatacept.
[drug_tool]: Initially, the system retrieved known disease–drug associations for abatacept, resulting in a dataset of 182 entries. This step provided a broad collection of potential relationships.
[drug_tool]: Next, a deduplication process was applied to the retrieved data to remove duplicate records. This filtering greatly reduced the dataset from 182 entries down to just 2 unique records, eliminating any repetitive information.
[drug_tool]: In summary, after these steps, the system was left with 2 distinct associations related to abatacept.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,CD86,CHEMBL1201823,ABATACEPT,T-lymphocyte activation antigen CD86 inhibitor,DailyMed

 Run 1 completed | rows=2 | latency=13.110s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of abatacept?
  Attempt 1/3
[drug_tool]: The query aims to identify specific drug associations related to abatacept.
[drug_tool]: First, the system retrieved known disease–drug associations for abatacept, initially gathering 182 rows of data.
[drug_tool]: Next, the system removed duplicate entries from this set, reducing the number of rows from 182 down to just 2.
[drug_tool]: In summary, the final result contains 2 unique associations related to abatacept after filtering out duplicates.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,CD86,CHEMBL1201823,ABATACEPT,T-lymphocyte activation antigen CD86 inhibitor,DailyMed

 Run 2 completed | rows=2 | latency=13.946s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of abatacept?
  Attempt 1/3
[drug_tool]: The query aimed to examine drug associations related to a specific drug.
[drug_tool]: First, the system retrieved a set of known disease–drug associations for the drug abatacept, resulting in 182 entries.
[drug_tool]: Next, the system performed a deduplication step to remove duplicate records from this list. This process reduced the number of entries dramatically from 182 to just 2, eliminating 180 duplicate rows.
[drug_tool]: In the end, the search resulted in 2 unique association records after removing duplicates.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,CD86,CHEMBL1201823,ABATACEPT,T-lymphocyte activation antigen CD86 inhibitor,DailyMed

 Run 3 completed | rows=2 | latency=12.838s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of abatacept?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to a specific drug, abatacept. First, the system retrieved known disease–drug associations for abatacept, resulting in 182 entries. Next, it removed duplicate records from this set, reducing the number of entries to 2. In the end, the process yielded 2 unique associations related to abatacept.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,CD86,CHEMBL1201823,ABATACEPT,T-lymphocyte activation antigen CD86 inhibitor,DailyMed

 Run 4 completed | rows=2 | latency=14.969s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of abatacept?
  Attempt 1/3
[drug_tool]: The user's query aimed to find drug associations related to abatacept. First, the system retrieved all known drug association records for abatacept, resulting in 182 entries. Next, it performed a deduplication process to remove duplicate entries, reducing the total from 182 to just 2 unique records. The final result includes these 2 distinct association records for abatacept.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,CD86,CHEMBL1201823,ABATACEPT,T-lymphocyte activation antigen CD86 inhibitor,DailyMed

 Run 5 completed | rows=2 | latency=13.364s
------------------------------------------------------------


## Question 52

**Which genes are associated with lung cancer?**

In [54]:

question = 'Which genes are associated with lung cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with lung cancer?
  Attempt 1/3
 Attempt 1 failed after 30.008s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: Retrieved 13634 targets for disease lung cancer.
----------------------------------------
Entries retrieved: 13634

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008903,lung cancer,ENSG00000146648,EGFR,epidermal growth factor receptor,0.897761

 Run 1 completed | rows=13634 | latency=27.987s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with lung cancer?
  Attempt 1/3
[disease_tool]: Retrieved 13634 targets for disease lung cancer.
----------------------------------------
Entries retrieved: 13634

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008903,lung cancer,ENSG00000146648,EGFR,epidermal growth factor receptor,0.897761

 Run 2 completed | rows=13634 | latency=22.335s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with lung cancer?
  Attempt 1/3
[disease_tool]: Retrieved 13634 targets for disease lung cancer.
----------------------------------------
Entries retrieved: 13634

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008903,lung cancer,ENSG00000146648,EGFR,epidermal growth factor receptor,0.897761

 Run 3 completed | rows=13634 | latency=22.749s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with lung cancer?
  Attempt 1/3
[disease_tool]: Retrieved 13634 targets for disease lung cancer.
----------------------------------------
Entries retrieved: 13634

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008903,lung cancer,ENSG00000146648,EGFR,epidermal growth factor receptor,0.897761

 Run 4 completed | rows=13634 | latency=22.886s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with lung cancer?
  Attempt 1/3
[disease_tool]: Retrieved 13634 targets for disease lung cancer.
----------------------------------------
Entries retrieved: 13634

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0008903,lung cancer,ENSG00000146648,EGFR,epidermal growth factor receptor,0.897761

 Run 5 completed | rows=13634 | latency=20.925s
------------------------------------------------------------


## Question 53

**What are the known targets of ponatinib?**

In [55]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The goal of this query was to find relevant drug associations for the drug ponatinib.
[drug_tool]: First, the system retrieved known disease-drug associations related to ponatinib, resulting in 76 entries.
[drug_tool]: Next, the system performed deduplication to remove duplicate records, which dramatically reduced the number from 76 to 2 entries.
[drug_tool]: In summary, the final result consists of 2 unique disease-drug association entries related to ponatinib after filtering out duplicates.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,ABL1,CHEMBL1171837,PONATINIB,Bcr/Abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 1 completed | rows=2 | latency=13.697s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drugs associated with a specific target, in this case, ponatinib.
[drug_tool]: Initially, the system retrieved known disease–drug associations related to ponatinib, which resulted in 76 entries. This step gathered all the relevant associations involving ponatinib without any initial filtering.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries. This step reduced the number of associations from 76 to just 2, by eliminating repeated records and ensuring that only unique associations remained.
[drug_tool]: In summary, the final result consisted of 2 distinct disease–drug associations related to ponatinib after processing and removing duplicates.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,ABL1,CHEMBL1171837,PONATINIB,Bcr/Abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 2 completed | rows=2 | latency=12.762s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve drug associations related to ponatinib. First, the system retrieved known drug associations for ponatinib, resulting in 76 entries. Next, it removed duplicate records from these associations, which reduced the number of entries from 76 to 2. In total, the final result consists of 2 unique drug association records for ponatinib.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,ABL1,CHEMBL1171837,PONATINIB,Bcr/Abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 3 completed | rows=2 | latency=11.296s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The goal of the query was to retrieve information related to drugs associated with ponatinib. First, the system retrieved known disease–drug associations for ponatinib, resulting in a total of 76 entries. Then, it removed duplicate records from this set, reducing the number of entries from 76 to 2. This process ensured that only unique associations remained. The final result after these steps is 2 unique disease–drug association records related to ponatinib.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,ABL1,CHEMBL1171837,PONATINIB,Bcr/Abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 4 completed | rows=2 | latency=15.120s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The goal of the query was to identify drug associations related to ponatinib.
[drug_tool]: Initially, the system retrieved a set of known drug associations for ponatinib, which resulted in 76 entries. This step provided a broad collection of data related to the drug.
[drug_tool]: Next, the system performed deduplication to remove any duplicate records from this set. As a result, the number of unique associations was reduced from 76 to just 2 entries, eliminating 74 duplicate records.
[drug_tool]: In summary, after retrieving the associations for ponatinib and removing duplicates, the final result consisted of 2 unique drug association entries.
----------------------------------------
Entries retrieved: 2

,gene_id,gene_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,ABL1,CHEMBL1171837,PONATINIB,Bcr/Abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 5 completed | rows=2 | latency=15.147s
------------------------------------------------------------


## Question 54

**Which drugs are used to treat systemic lupus erythematosus?**

In [56]:

question = 'Which drugs are used to treat systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The purpose of the query was to identify disease–drug associations related to systemic lupus erythematosus.
[disease_tool]: First, the system retrieved a set of known disease associations related to systemic lupus erythematosus, resulting in 352 rows. These rows represented potential disease–drug pairs associated with this disease.
[disease_tool]: Next, the system performed deduplication to eliminate duplicate entries within this set. This process reduced the number of rows from 352 to 197, removing 155 duplicate records to ensure a cleaner, more accurate list of unique disease–drug associations.
[disease_tool]: In total, after applying these steps, there are now 197 unique disease–drug association entries related to systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 197

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL635,PREDNISONE,MONDO_0007915,systemic lupus erythematosus,4.0,NaN,Small molecule,MONDO_0007915,systemic lupus erythematosus

 Run 1 completed | rows=197 | latency=20.453s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The query aims to find associations related to systemic lupus erythematosus.
[disease_tool]: First, the system retrieved all known disease–drug associations related to this disease, resulting in 352 entries. Next, the system removed duplicate records from these associations, reducing the total from 352 to 197 entries.
[disease_tool]: In total, the process concluded with 197 unique disease–drug association records for systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 197

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL635,PREDNISONE,MONDO_0007915,systemic lupus erythematosus,4.0,NaN,Small molecule,MONDO_0007915,systemic lupus erythematosus

 Run 2 completed | rows=197 | latency=13.291s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The goal of the query was to find information related to systemic lupus erythematosus.
[disease_tool]: First, the system retrieved known disease associations for systemic lupus erythematosus, which initially resulted in 352 entries. Immediately after this, the system performed deduplication, removing duplicate records, which reduced the number of entries from 352 to 197.
[disease_tool]: In summary, after these steps, the final result contained 197 unique disease association entries related to systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 197

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL635,PREDNISONE,MONDO_0007915,systemic lupus erythematosus,4.0,NaN,Small molecule,MONDO_0007915,systemic lupus erythematosus

 Run 3 completed | rows=197 | latency=14.382s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The query aimed to identify associations related to systemic lupus erythematosus. First, the system retrieved the base disease associations for this condition, resulting in 352 entries. Next, duplicate records within this dataset were removed, reducing the number of entries from 352 to 197. This step eliminated 155 duplicate rows, leaving a cleaner set of data. In total, the final result includes 197 unique associations related to systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 197

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL635,PREDNISONE,MONDO_0007915,systemic lupus erythematosus,4.0,NaN,Small molecule,MONDO_0007915,systemic lupus erythematosus

 Run 4 completed | rows=197 | latency=16.762s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The goal of the query was to identify related drug associations for systemic lupus erythematosus. First, the system retrieved known disease–drug associations specifically for systemic lupus erythematosus, resulting in 352 entries. Next, the system removed any duplicate entries, reducing the number from 352 to 197, which left only unique associations. Overall, the final result includes 197 distinct known drug associations related to systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 197

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,indication_id,indication_name
0,CHEMBL635,PREDNISONE,MONDO_0007915,systemic lupus erythematosus,4.0,NaN,Small molecule,MONDO_0007915,systemic lupus erythematosus

 Run 5 completed | rows=197 | latency=14.858s
------------------------------------------------------------


## Question 55

**Which genes are associated with autism spectrum disorder?**

In [57]:

question = 'Which genes are associated with autism spectrum disorder?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
[disease_tool]: Retrieved 3148 targets for disease autism spectrum disorder.
----------------------------------------
Entries retrieved: 3148

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003756,autism spectrum disorder,ENSG00000136535,TBR1,T-box brain transcription factor 1,0.816201

 Run 1 completed | rows=3148 | latency=16.767s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
[disease_tool]: Retrieved 3148 targets for disease autism spectrum disorder.
----------------------------------------
Entries retrieved: 3148

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003756,autism spectrum disorder,ENSG00000136535,TBR1,T-box brain transcription factor 1,0.816201

 Run 2 completed | rows=3148 | latency=14.685s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
[disease_tool]: Retrieved 3148 targets for disease autism spectrum disorder.
----------------------------------------
Entries retrieved: 3148

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003756,autism spectrum disorder,ENSG00000136535,TBR1,T-box brain transcription factor 1,0.816201

 Run 3 completed | rows=3148 | latency=15.962s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
[disease_tool]: Retrieved 3148 targets for disease autism spectrum disorder.
----------------------------------------
Entries retrieved: 3148

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003756,autism spectrum disorder,ENSG00000136535,TBR1,T-box brain transcription factor 1,0.816201

 Run 4 completed | rows=3148 | latency=12.954s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
[disease_tool]: Retrieved 3148 targets for disease autism spectrum disorder.
----------------------------------------
Entries retrieved: 3148

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003756,autism spectrum disorder,ENSG00000136535,TBR1,T-box brain transcription factor 1,0.816201

 Run 5 completed | rows=3148 | latency=18.663s
------------------------------------------------------------


## Question 56

**Which diseases are associated with the ROS1 gene?**

In [58]:

question = 'Which diseases are associated with the ROS1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
[target_tool]: Retrieved 613 diseases for target ROS1.
----------------------------------------
Entries retrieved: 613

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000047936,ROS1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 1 completed | rows=613 | latency=11.941s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
[target_tool]: Retrieved 613 diseases for target ROS1.
----------------------------------------
Entries retrieved: 613

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000047936,ROS1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 2 completed | rows=613 | latency=12.056s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
[target_tool]: Retrieved 613 diseases for target ROS1.
----------------------------------------
Entries retrieved: 613

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000047936,ROS1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 3 completed | rows=613 | latency=10.671s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
[target_tool]: Retrieved 613 diseases for target ROS1.
----------------------------------------
Entries retrieved: 613

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000047936,ROS1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 4 completed | rows=613 | latency=11.714s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
[target_tool]: Retrieved 613 diseases for target ROS1.
----------------------------------------
Entries retrieved: 613

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000047936,ROS1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 5 completed | rows=613 | latency=11.845s
------------------------------------------------------------


## Question 57

**Which diseases are associated with the ALK gene?**

In [59]:

question = 'Which diseases are associated with the ALK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
[target_tool]: Retrieved 1272 diseases for target ALK.
----------------------------------------
Entries retrieved: 1272

           gene_id gene_name   disease_id   disease_name  association_score
0  ENSG00000171094       ALK  EFO_0000621  neuroblastoma           0.807305

 Run 1 completed | rows=1272 | latency=14.326s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
[target_tool]: Retrieved 1272 diseases for target ALK.
----------------------------------------
Entries retrieved: 1272

           gene_id gene_name   disease_id   disease_name  association_score
0  ENSG00000171094       ALK  EFO_0000621  neuroblastoma           0.807305

 Run 2 completed | rows=1272 | latency=12.686s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
[target_tool]: Retrieved 1272 diseases for target ALK.
----------------------------------------
Entries retrieved: 1272

           gene_id gene_name   disease_id   disease_name  association_score
0  ENSG00000171094       ALK  EFO_0000621  neuroblastoma           0.807305

 Run 3 completed | rows=1272 | latency=14.388s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
[target_tool]: Retrieved 1272 diseases for target ALK.
----------------------------------------
Entries retrieved: 1272

           gene_id gene_name   disease_id   disease_name  association_score
0  ENSG00000171094       ALK  EFO_0000621  neuroblastoma           0.807305

 Run 4 completed | rows=1272 | latency=13.392s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
[target_tool]: Retrieved 1272 diseases for target ALK.
----------------------------------------
Entries retrieved: 1272

           gene_id gene_name   disease_id   disease_name  association_score
0  ENSG00000171094       ALK  EFO_0000621  neuroblastoma           0.807305

 Run 5 completed | rows=1272 | latency=13.203s
------------------------------------------------------------


## Question 58

**Which diseases are associated with the EGFR gene?**

In [60]:

question = 'Which diseases are associated with the EGFR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
[target_tool]: Retrieved 2521 diseases for target EGFR.
----------------------------------------
Entries retrieved: 2521

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000146648,EGFR,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 1 completed | rows=2521 | latency=11.936s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
[target_tool]: Retrieved 2521 diseases for target EGFR.
----------------------------------------
Entries retrieved: 2521

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000146648,EGFR,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 2 completed | rows=2521 | latency=12.563s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
[target_tool]: Retrieved 2521 diseases for target EGFR.
----------------------------------------
Entries retrieved: 2521

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000146648,EGFR,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 3 completed | rows=2521 | latency=12.405s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
[target_tool]: Retrieved 2521 diseases for target EGFR.
----------------------------------------
Entries retrieved: 2521

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000146648,EGFR,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 4 completed | rows=2521 | latency=11.637s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
[target_tool]: Retrieved 2521 diseases for target EGFR.
----------------------------------------
Entries retrieved: 2521

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000146648,EGFR,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 5 completed | rows=2521 | latency=11.949s
------------------------------------------------------------


## Question 59

**Which genes are associated with psoriasis?**

In [61]:

question = 'Which genes are associated with psoriasis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with psoriasis?
  Attempt 1/3
[disease_tool]: Retrieved 7131 targets for disease psoriasis.
----------------------------------------
Entries retrieved: 7131

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000676,psoriasis,ENSG00000141527,CARD14,caspase recruitment domain family member 14,0.841465

 Run 1 completed | rows=7131 | latency=21.979s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with psoriasis?
  Attempt 1/3
[disease_tool]: Retrieved 7131 targets for disease psoriasis.
----------------------------------------
Entries retrieved: 7131

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000676,psoriasis,ENSG00000141527,CARD14,caspase recruitment domain family member 14,0.841465

 Run 2 completed | rows=7131 | latency=16.107s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with psoriasis?
  Attempt 1/3
[disease_tool]: Retrieved 7131 targets for disease psoriasis.
----------------------------------------
Entries retrieved: 7131

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000676,psoriasis,ENSG00000141527,CARD14,caspase recruitment domain family member 14,0.841465

 Run 3 completed | rows=7131 | latency=16.819s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with psoriasis?
  Attempt 1/3
[disease_tool]: Retrieved 7131 targets for disease psoriasis.
----------------------------------------
Entries retrieved: 7131

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000676,psoriasis,ENSG00000141527,CARD14,caspase recruitment domain family member 14,0.841465

 Run 4 completed | rows=7131 | latency=17.224s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with psoriasis?
  Attempt 1/3
[disease_tool]: Retrieved 7131 targets for disease psoriasis.
----------------------------------------
Entries retrieved: 7131

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000676,psoriasis,ENSG00000141527,CARD14,caspase recruitment domain family member 14,0.841465

 Run 5 completed | rows=7131 | latency=17.714s
------------------------------------------------------------


## Question 60

**Which genes are associated with ulcerative colitis?**

In [62]:

question = 'Which genes are associated with ulcerative colitis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
[disease_tool]: Retrieved 9311 targets for disease ulcerative colitis.
----------------------------------------
Entries retrieved: 9311

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000729,ulcerative colitis,ENSG00000232810,TNF,tumor necrosis factor,0.637689

 Run 1 completed | rows=9311 | latency=25.416s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
[disease_tool]: Retrieved 9311 targets for disease ulcerative colitis.
----------------------------------------
 Attempt 1 failed after 30.005s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: Retrieved 9311 targets for disease ulcerative colitis.
----------------------------------------
Entries retrieved: 9311

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000729,ulcerative colitis,ENSG00000232810,TNF,tumor necrosis factor,0.637689

 Run 2 completed | rows=9311 | latency=19.528s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
[disease_tool]: Retrieved 9311 targets for disease ulcerative colitis.
----------------------------------------
Entries retrieved: 9311

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000729,ulcerative colitis,ENSG00000232810,TNF,tumor necrosis factor,0.637689

 Run 3 completed | rows=9311 | latency=16.918s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
[disease_tool]: Retrieved 9311 targets for disease ulcerative colitis.
----------------------------------------
Entries retrieved: 9311

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000729,ulcerative colitis,ENSG00000232810,TNF,tumor necrosis factor,0.637689

 Run 4 completed | rows=9311 | latency=16.462s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
[disease_tool]: Retrieved 9311 targets for disease ulcerative colitis.
----------------------------------------
Entries retrieved: 9311

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000729,ulcerative colitis,ENSG00000232810,TNF,tumor necrosis factor,0.637689

 Run 5 completed | rows=9311 | latency=15.937s
------------------------------------------------------------


## Question 61

**Which genes are associated with tuberculosis?**

In [63]:

question = 'Which genes are associated with tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
[disease_tool]: Retrieved 3970 targets for disease tuberculosis.
----------------------------------------
Entries retrieved: 3970

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0018076,tuberculosis,ENSG00000036473,OTC,ornithine transcarbamylase,0.86757

 Run 1 completed | rows=3970 | latency=14.630s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
[disease_tool]: Retrieved 3970 targets for disease tuberculosis.
----------------------------------------
Entries retrieved: 3970

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0018076,tuberculosis,ENSG00000036473,OTC,ornithine transcarbamylase,0.86757

 Run 2 completed | rows=3970 | latency=12.317s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
[disease_tool]: Retrieved 3970 targets for disease tuberculosis.
----------------------------------------
Entries retrieved: 3970

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0018076,tuberculosis,ENSG00000036473,OTC,ornithine transcarbamylase,0.86757

 Run 3 completed | rows=3970 | latency=16.077s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
[disease_tool]: Retrieved 3970 targets for disease tuberculosis.
----------------------------------------
Entries retrieved: 3970

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0018076,tuberculosis,ENSG00000036473,OTC,ornithine transcarbamylase,0.86757

 Run 4 completed | rows=3970 | latency=13.821s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
[disease_tool]: Retrieved 3970 targets for disease tuberculosis.
----------------------------------------
Entries retrieved: 3970

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,MONDO_0018076,tuberculosis,ENSG00000036473,OTC,ornithine transcarbamylase,0.86757

 Run 5 completed | rows=3970 | latency=14.684s
------------------------------------------------------------


## Question 62

**Which genes are associated with hepatitis C?**

In [64]:

question = 'Which genes are associated with hepatitis C?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
[disease_tool]: Retrieved 2815 targets for disease hepatitis C.
----------------------------------------
Entries retrieved: 2815

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003047,hepatitis C virus infection,ENSG00000142166,IFNAR1,interferon alpha and beta receptor subunit 1,0.613074

 Run 1 completed | rows=2815 | latency=14.405s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
[disease_tool]: Retrieved 2815 targets for disease hepatitis C.
----------------------------------------
Entries retrieved: 2815

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003047,hepatitis C virus infection,ENSG00000142166,IFNAR1,interferon alpha and beta receptor subunit 1,0.613074

 Run 2 completed | rows=2815 | latency=14.709s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
[disease_tool]: Retrieved 2815 targets for disease hepatitis C.
----------------------------------------
Entries retrieved: 2815

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003047,hepatitis C virus infection,ENSG00000142166,IFNAR1,interferon alpha and beta receptor subunit 1,0.613074

 Run 3 completed | rows=2815 | latency=14.152s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
[disease_tool]: Retrieved 2815 targets for disease hepatitis C.
----------------------------------------
Entries retrieved: 2815

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003047,hepatitis C virus infection,ENSG00000142166,IFNAR1,interferon alpha and beta receptor subunit 1,0.613074

 Run 4 completed | rows=2815 | latency=12.590s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
[disease_tool]: Retrieved 2815 targets for disease hepatitis C.
----------------------------------------
Entries retrieved: 2815

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0003047,hepatitis C virus infection,ENSG00000142166,IFNAR1,interferon alpha and beta receptor subunit 1,0.613074

 Run 5 completed | rows=2815 | latency=14.578s
------------------------------------------------------------


## Question 63

**Which genes are associated with Hodgkin lymphoma?**

In [65]:

question = 'Which genes are associated with Hodgkin lymphoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
[disease_tool]: Retrieved 2846 targets for disease Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 2846

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000183,Hodgkins lymphoma,ENSG00000188389,PDCD1,programmed cell death 1,0.596561

 Run 1 completed | rows=2846 | latency=14.451s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
[disease_tool]: Retrieved 2846 targets for disease Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 2846

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000183,Hodgkins lymphoma,ENSG00000188389,PDCD1,programmed cell death 1,0.596561

 Run 2 completed | rows=2846 | latency=15.945s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
[disease_tool]: Retrieved 2846 targets for disease Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 2846

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000183,Hodgkins lymphoma,ENSG00000188389,PDCD1,programmed cell death 1,0.596561

 Run 3 completed | rows=2846 | latency=15.104s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
[disease_tool]: Retrieved 2846 targets for disease Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 2846

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000183,Hodgkins lymphoma,ENSG00000188389,PDCD1,programmed cell death 1,0.596561

 Run 4 completed | rows=2846 | latency=13.150s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
[disease_tool]: Retrieved 2846 targets for disease Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 2846

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000183,Hodgkins lymphoma,ENSG00000188389,PDCD1,programmed cell death 1,0.596561

 Run 5 completed | rows=2846 | latency=17.271s
------------------------------------------------------------


## Question 64

**Which pathways are associated with TP53?**

In [66]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: This query was designed to find pathways related to the target gene TP53. The process began with retrieving pathways for TP53, resulting in 45 pathways identified after this step.
[target_tool]: Since this log does not show any prior filtering or association retrieval steps, it appears that the pathway retrieval was the initial action taken. No filters or deduplication steps are detailed in this part of the log, which suggests that no subsequent reduction of pathways was executed after retrieval.
[target_tool]: In conclusion, the final result consists of 45 pathways associated with the target TP53.
----------------------------------------
Entries retrieved: 45

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 1 completed | rows=45 | latency=15.413s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The goal of the query was to explore biological pathways related to the target TP53.
[target_tool]: First, the system retrieved pathways associated with TP53. After this step, 45 pathways were identified.
[target_tool]: This step involved gathering pathway information without filtering or reducing the number of pathways at this point.
[target_tool]: At the end of this process, 45 pathways related to TP53 were retrieved.
----------------------------------------
Entries retrieved: 45

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 2 completed | rows=45 | latency=18.428s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The query was aimed at retrieving pathway information related to the target TP53. The first step involved pathway retrieval, which fetched 45 pathways associated with TP53. This step provided a collection of biological pathways linked to the target gene but did not involve any filtering or reduction of data at this point. The overall process resulted in a set of 45 pathways related to TP53.
----------------------------------------
Entries retrieved: 45

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 3 completed | rows=45 | latency=14.772s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The query aims to retrieve pathway information related to the target gene TP53. First, the system retrieved pathways associated with TP53, resulting in 45 pathways. This step involved collecting pathway data linked to the target without applying any filters at this stage. Since only this step is recorded in the log, it is clear that the system gathered pathway information for TP53, ending with 45 pathways.
----------------------------------------
Entries retrieved: 45

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 4 completed | rows=45 | latency=13.413s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The query aims to retrieve pathway information associated with the target gene TP53.
[target_tool]: First, the system retrieved pathways related to TP53. Before this step, the number of pathways was not specified, but after the retrieval, 45 pathways were identified. This step was solely for collecting pathway data relevant to the target.
[target_tool]: Since there are no other steps shown in the provided log, it appears that the process concluded after pathway retrieval, resulting in 45 pathways associated with TP53.
----------------------------------------
Entries retrieved: 45

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 5 completed | rows=45 | latency=13.628s
------------------------------------------------------------


## Question 65

**Which drugs target ERBB2?**

In [67]:

question = 'Which drugs target ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target ERBB2?
  Attempt 1/3
[target_tool]: The query aimed to find connections between the target ERBB2 and related disease or drug associations.
[target_tool]: First, the system retrieved known disease–drug associations related to ERBB2, which resulted in a total of 1,048 entries.
[target_tool]: Next, the system removed duplicate entries from this set, reducing the number from 1,048 to 299. This step ensured that only unique associations remained for further analysis.
[target_tool]: Overall, the final result consisted of 299 unique entries after removing duplicates.
----------------------------------------
Entries retrieved: 299

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,ERBB2,CHEMBL1201585,TRASTUZUMAB,4.0,NaN,NaN,Receptor protein-tyrosine kinase erbB-2 inhibitor

 Run 1 completed | rows=299 | latency=15.311s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target ERBB2?
  Attempt 1/3
[target_tool]: The goal of the query was to identify associations related to the target ERBB2. First, the system retrieved known disease-drug associations for ERBB2, resulting in a set of 1,048 entries. Next, the system removed duplicate records from this set, reducing the number from 1,048 to 299. In total, the query produced 299 unique association entries related to ERBB2.
----------------------------------------
Entries retrieved: 299

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,ERBB2,CHEMBL1201585,TRASTUZUMAB,4.0,NaN,NaN,Receptor protein-tyrosine kinase erbB-2 inhibitor

 Run 2 completed | rows=299 | latency=15.346s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target ERBB2?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target ERBB2. Initially, the system retrieved known disease-drug associations for ERBB2, resulting in 1,048 rows. To ensure unique records, the system then removed duplicate entries, reducing the dataset from 1,048 to 299 rows. In summary, after filtering, 299 unique associations related to ERBB2 remained.
----------------------------------------
Entries retrieved: 299

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,ERBB2,CHEMBL1201585,TRASTUZUMAB,4.0,NaN,NaN,Receptor protein-tyrosine kinase erbB-2 inhibitor

 Run 3 completed | rows=299 | latency=14.886s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target ERBB2?
  Attempt 1/3
[target_tool]: The query aimed to find specific drug and disease associations related to the target ERBB2, and then refine the results based on duplicates.
[target_tool]: The first step involved retrieving known disease–drug associations for ERBB2, which initially produced 1,048 records. This step aimed to gather all relevant associations before filtering.
[target_tool]: Next, the system removed duplicate records from this initial set. After deduplication, the total number of entries was reduced to 299, eliminating 749 duplicate rows. This process helped ensure that the remaining data was unique and more reliable for further analysis.
[target_tool]: In summary, the process started with 1,048 associations and, after removing duplicates, resulted in 299 unique associations related to ERBB2.
----------------------------------------
Entries retrieved: 299

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,ERBB2,CHEMBL1201585,TRASTUZUMAB,4.0,NaN,NaN,Receptor protein-tyrosine kinase erbB-2 inhibitor

 Run 4 completed | rows=299 | latency=15.627s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target ERBB2?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target ERBB2.
[target_tool]: Initially, the system retrieved a set of known disease–drug associations for ERBB2, resulting in 1,048 records.
[target_tool]: Next, it removed duplicate entries from this set to refine the data, reducing the total number of records from 1,048 to 299. This deduplication step ensured that only unique associations remained, making the data more manageable and accurate.
[target_tool]: The final result includes 299 unique disease–drug associations related to ERBB2.
----------------------------------------
Entries retrieved: 299

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,ERBB2,CHEMBL1201585,TRASTUZUMAB,4.0,NaN,NaN,Receptor protein-tyrosine kinase erbB-2 inhibitor

 Run 5 completed | rows=299 | latency=16.999s
------------------------------------------------------------


## Question 66

**Which pathways are associated with the ADRB1 gene?**

In [68]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the pathways associated with the target ADRB1.
[target_tool]: First, the system retrieved pathways linked to ADRB1. This step resulted in obtaining 2 pathway entries, though it did not specify how many pathways were initially available.
[target_tool]: Since only pathway retrieval is shown in the log, no further filtering or reduction steps are indicated after this retrieval.
[target_tool]: In total, the final result includes 2 pathways associated with ADRB1.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 1 completed | rows=2 | latency=14.219s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target ADRB1. First, the system retrieved pathways associated with this target, which resulted in a total of 2 pathways. This step involved collecting relevant pathway data without filtering or reducing the initial set. Since only this single step is shown in the log, the process concluded with the retrieval of the pathways without further filtering or deduplication.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 2 completed | rows=2 | latency=17.363s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve information related to the pathways associated with the target ADRB1.
[target_tool]: The first step involved retrieving pathway information specific to ADRB1, which resulted in a total of 2 pathways being identified. The details indicate that pathways were successfully retrieved for this target, but no further filtering or reduction steps are specified in this log entry.
[target_tool]: In summary, the final result includes 2 pathways linked to ADRB1, based on the pathway retrieval process.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 3 completed | rows=2 | latency=15.455s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target ADRB1. In the pathway retrieval step, the system accessed pathway data associated with ADRB1 and found two relevant pathways. This step simply involved collecting pathway information without filtering or narrowing down the results further. The final result included two pathways linked to ADRB1.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 4 completed | rows=2 | latency=13.318s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The purpose of the query was to find pathways related to the biological target ADRB1.
[target_tool]: First, the system retrieved pathway information associated with ADRB1. This step resulted in two pathways being identified linked to the target.
[target_tool]: Since only the pathway retrieval step is shown in the provided log, it indicates that the pathway information was collected without additional filtering at this stage.
[target_tool]: In total, the final result is the identification of two pathways related to ADRB1.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 5 completed | rows=2 | latency=15.228s
------------------------------------------------------------


## Question 67

**Which pathways are associated with the DRD2 gene?**

In [69]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query's goal was to retrieve biological pathway information related to the target gene DRD2.
[target_tool]: First, the system retrieved pathway information associated with DRD2. This step resulted in a single pathway entry, although the initial number of pathways was not specified. The retrieval confirmed the existence of at least one pathway linked to the target gene.
[target_tool]: Since no further filtering steps are shown in the provided log, and only one pathway result remains, the process concluded with one pathway identified for DRD2.
----------------------------------------
Entries retrieved: 1

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 1 completed | rows=1 | latency=19.236s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The purpose of the query was to find pathway information related to the target DRD2. The first step involved retrieving pathways associated with this target, resulting in a single pathway being retrieved. This step provided the initial pathway data for further analysis. No additional filtering or data reduction occurred at this stage since only one pathway was retrieved. In summary, the final result includes one pathway linked to DRD2.
----------------------------------------
Entries retrieved: 1

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 2 completed | rows=1 | latency=14.875s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target DRD2. In the process, the system retrieved pathways associated with DRD2, resulting in a single pathway. This step simply involved accessing known pathway data without further filtering or reduction of results. The final output indicates that one pathway is connected to the DRD2 target.
----------------------------------------
Entries retrieved: 1

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 3 completed | rows=1 | latency=12.668s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aimed to explore pathways associated with the target gene DRD2.
[target_tool]: Initially, the system retrieved pathway information related to DRD2, which resulted in a single pathway being identified. This step provided a pathway context for DRD2 but did not involve filtering or reduction of multiple records, as only one pathway was retrieved.
[target_tool]: The final step confirmed that one pathway was associated with DRD2, indicating that the system successfully retrieved relevant pathway data for the target gene.
----------------------------------------
Entries retrieved: 1

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 4 completed | rows=1 | latency=12.178s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The goal was to find pathways related to the target gene DRD2.
[target_tool]: First, the system retrieved pathway information associated with DRD2, resulting in a single pathway being identified. This step involved gathering pathway data solely for this target.
[target_tool]: Since only pathway retrieval is shown in the log, no further filtering steps are detailed, and it appears no other filters were applied in this process.
[target_tool]: In conclusion, the final result includes information about one pathway linked to DRD2.
----------------------------------------
Entries retrieved: 1

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 5 completed | rows=1 | latency=12.796s
------------------------------------------------------------


## Question 68

**Which pathways are associated with the HTR2A gene?**

In [70]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve pathway information related to the target HTR2A.
[target_tool]: The first step involved retrieving pathway details associated with HTR2A, which resulted in 2 pathways being identified. Because no previous pathway data was specified, the number of pathways after retrieval is simply given as 2.
[target_tool]: In summary, the final result set contains information about 2 pathways linked to the target HTR2A.
----------------------------------------
 Attempt 1 failed after 15.726s: 'NoneType' object has no attribute 'columns'
  Attempt 2/3
[target_tool]: The query aimed to investigate pathways related to the target gene HTR2A.
[target_tool]: First, the system retrieved pathway information associated with HTR2A, which resulted in two pathways being identified.
[target_tool]: Since there was only a pathway retrieval step recorded, no further filtering or reduction in data occurred beyond this initial retrieval.
[target_tool]: In the end, the total number of pathways associated with HTR2A was two.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 1 completed | rows=2 | latency=21.628s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aimed to identify biological pathways related to the target HTR2A. The process began with retrieving pathways associated with this specific target. After this retrieval, 2 pathways were identified and stored, providing the basis for further analysis. Since no previous result count was given, it is not clear how many pathways were initially considered before this step. In summary, the final step involved retrieving pathway information, resulting in 2 pathways related to HTR2A.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 2 completed | rows=2 | latency=12.842s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The goal of the query was to find pathway information related to the target HTR2A.
[target_tool]: The process began with retrieving pathways associated with the target HTR2A. This step resulted in extracting 2 pathways related to HTR2A. Since no prior data is given, we only know that pathways were retrieved for this specific target, and that 2 pathway entries were obtained after this step. No further filtering or reduction steps are described beyond this retrieval.
[target_tool]: In summary, the final result consists of pathways associated with HTR2A, and there are 2 such pathways identified.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 3 completed | rows=2 | latency=15.373s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The goal of the query was to gather pathway information related to the target HTR2A. In the first step, the system retrieved pathways associated with this target, resulting in 2 pathways being identified. This step provided the pathway data necessary for further analysis. Since only one step is recorded, no additional filtering or deduplication occurred, and the final result is that 2 pathways are now associated with HTR2A.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 4 completed | rows=2 | latency=11.479s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target HTR2A. First, the system retrieved pathways associated with this target, which resulted in a total of 2 pathways after the retrieval step. Prior to this step, the number of pathways was not specified, but after retrieval, there were 2 entries in the result set. This indicates that pathway data for HTR2A was successfully obtained.
----------------------------------------
Entries retrieved: 2

,gene_name,gene_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 5 completed | rows=2 | latency=15.426s
------------------------------------------------------------


## Question 69

**Which drugs target CD19?**

In [71]:

question = 'Which drugs target CD19?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CD19?
  Attempt 1/3
[target_tool]: The system's goal was to find information related to the target CD19. First, it retrieved the initial set of known disease–drug associations for CD19, which resulted in 248 entries. Next, the system performed a deduplication process to remove duplicate entries, reducing the total from 248 to 112. In summary, after applying all steps, the final result included 112 unique associations related to CD19.
----------------------------------------
Entries retrieved: 112

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,CD19,CHEMBL3301574,TISAGENLECLEUCEL,4.0,NaN,NaN,B-lymphocyte antigen CD19 binding agent

 Run 1 completed | rows=112 | latency=17.525s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CD19?
  Attempt 1/3
[target_tool]: The goal of the query was to identify relevant disease-drug associations related to the target CD19.
[target_tool]: Initially, the system retrieved a broad set of 248 known associations between CD19 and various diseases or drugs. After that, the system performed deduplication to remove duplicate records, which reduced the number of entries from 248 to 112. This process ensured that each association was listed only once, avoiding redundant information.
[target_tool]: In summary, the final dataset contains 112 unique disease-drug associations related to CD19.
----------------------------------------
Entries retrieved: 112

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,CD19,CHEMBL3301574,TISAGENLECLEUCEL,4.0,NaN,NaN,B-lymphocyte antigen CD19 binding agent

 Run 2 completed | rows=112 | latency=13.787s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CD19?
  Attempt 1/3
[target_tool]: The query aimed to identify information related to the target "CD19." First, the system retrieved known disease–drug associations associated with CD19, which resulted in 248 entries. Next, the process removed duplicate entries from this set, reducing the number of records from 248 to 112. Overall, the final result included 112 unique records related to CD19.
----------------------------------------
Entries retrieved: 112

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,CD19,CHEMBL3301574,TISAGENLECLEUCEL,4.0,NaN,NaN,B-lymphocyte antigen CD19 binding agent

 Run 3 completed | rows=112 | latency=26.059s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CD19?
  Attempt 1/3
[target_tool]: The query aimed to find information related to the target CD19, focusing on its associations with disease and drug data.
[target_tool]: First, the system retrieved known disease–drug associations for CD19. This initial retrieval yielded 248 records.
[target_tool]: Next, the system removed duplicate records from these associations to ensure that each entry was unique. This deduplication process reduced the total number of records from 248 to 112.
[target_tool]: In summary, after retrieving the initial data and removing duplicates, the final result included 112 unique disease–drug association entries related to CD19.
----------------------------------------
Entries retrieved: 112

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,CD19,CHEMBL3301574,TISAGENLECLEUCEL,4.0,NaN,NaN,B-lymphocyte antigen CD19 binding agent

 Run 4 completed | rows=112 | latency=14.091s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CD19?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve associations for the target CD19. The process started with retrieving all known disease-drug associations related to CD19, which resulted in 248 entries. Then, to refine the dataset, duplicate entries were removed, reducing the number of associations from 248 down to 112. Overall, the final result includes 112 unique associations for CD19 after filtering out duplicates.
----------------------------------------
Entries retrieved: 112

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,CD19,CHEMBL3301574,TISAGENLECLEUCEL,4.0,NaN,NaN,B-lymphocyte antigen CD19 binding agent

 Run 5 completed | rows=112 | latency=13.317s
------------------------------------------------------------


## Question 70

**Which drugs target CTLA4?**

In [72]:

question = 'Which drugs target CTLA4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CTLA4?
  Attempt 1/3
[target_tool]: The purpose of the query was to identify relevant associations related to the target CTLA4.
[target_tool]: First, the system retrieved known disease–drug associations for CTLA4, resulting in a dataset of 607 entries.
[target_tool]: Next, the system performed deduplication to remove duplicate entries from this dataset. After this step, the number of unique association records was reduced to 84.
[target_tool]: In summary, the final set contains 84 unique associations related to CTLA4 after filtering duplicates.
----------------------------------------
Entries retrieved: 84

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,CTLA4,CHEMBL2108658,TREMELIMUMAB,4.0,NaN,NaN,Cytotoxic T-lymphocyte protein 4 inhibitor

 Run 1 completed | rows=84 | latency=18.593s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CTLA4?
  Attempt 1/3
[target_tool]: The intent of the query was to identify associations related to the biological target CTLA4.
[target_tool]: First, the system retrieved all known associations related to the target CTLA4, which initially resulted in 607 entries. Next, it performed a deduplication step to remove duplicate records, reducing the total from 607 to 84 unique entries.
[target_tool]: In summary, the system narrowed down the initial data to 84 distinct associations involving CTLA4.
----------------------------------------
Entries retrieved: 84

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,CTLA4,CHEMBL2108658,TREMELIMUMAB,4.0,NaN,NaN,Cytotoxic T-lymphocyte protein 4 inhibitor

 Run 2 completed | rows=84 | latency=12.884s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CTLA4?
  Attempt 1/3
[target_tool]: The query aimed to find disease–drug associations related to the target CTLA4.
[target_tool]: First, the system retrieved known associations for CTLA4, resulting in 607 rows.
[target_tool]: Next, it removed duplicate entries, which reduced the number from 607 to 84 rows, eliminating 523 duplicates.
[target_tool]: The final result contains 84 unique disease–drug associations linked to CTLA4.
----------------------------------------
Entries retrieved: 84

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,CTLA4,CHEMBL2108658,TREMELIMUMAB,4.0,NaN,NaN,Cytotoxic T-lymphocyte protein 4 inhibitor

 Run 3 completed | rows=84 | latency=15.916s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CTLA4?
  Attempt 1/3
[target_tool]: The goal of the query was to identify relevant information related to the target CTLA4.
[target_tool]: Initially, the system retrieved a set of known associations between diseases and drugs related to CTLA4, resulting in a total of 607 records. Next, the system performed deduplication to remove duplicate entries, which greatly reduced the number of records from 607 to 84. This step ensured that only unique data entries remained, making the results clearer and more manageable.
[target_tool]: Overall, the process concluded with 84 unique records associated with CTLA4 after filtering out duplicates.
----------------------------------------
Entries retrieved: 84

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,CTLA4,CHEMBL2108658,TREMELIMUMAB,4.0,NaN,NaN,Cytotoxic T-lymphocyte protein 4 inhibitor

 Run 4 completed | rows=84 | latency=14.278s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CTLA4?
  Attempt 1/3
[target_tool]: The intent of the query was to identify disease–drug associations related to the target CTLA4. First, the system retrieved known disease–drug associations for CTLA4, resulting in 607 entries. Next, duplicate entries within this data were removed, reducing the number of associations from 607 to 84. This was achieved through deduplication to ensure unique records. The final result includes 84 unique disease–drug associations associated with CTLA4.
----------------------------------------
Entries retrieved: 84

,gene_id,gene_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,CTLA4,CHEMBL2108658,TREMELIMUMAB,4.0,NaN,NaN,Cytotoxic T-lymphocyte protein 4 inhibitor

 Run 5 completed | rows=84 | latency=14.117s
------------------------------------------------------------

In [13]:
import pickle
with open("Opentargets_same_question_response_final.pkl", "wb") as f:
    pickle.dump(dct_result, f)

import json
import pandas as pd

def make_json_safe(obj):
    if isinstance(obj, pd.DataFrame):
        return {
            "__type__": "dataframe",
            "columns": obj.columns.tolist(),
            "rows": obj.to_dict(orient="records")
        }
    elif isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    else:
        return obj


json_safe_result = make_json_safe(dct_result)

with open("Opentargets_same_question_response_final.json", "w", encoding="utf-8") as f:
    json.dump(
        json_safe_result,
        f,
        indent=2,
        ensure_ascii=False
    )