In [ ]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from llama_utility import return_llama_answer

In [4]:
model = "llama-3.3-70b-versatile"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [3]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  gene_name       disease_name
0      BRAF  Colorectal Cancer

 Run 1 completed | rows=5 | latency=0.899s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      BRAF     Melanoma

 Run 2 completed | rows=4 | latency=0.437s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal Cancer      BRAF

 Run 3 completed | rows=5 | latency=0.517s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name       disease_name
0      BRAF  Colorectal Cancer

 Run 4 completed | rows=4 | latency=0.402s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name       disease_name
0      BRAF  Colorectal Cancer

 Run 5 completed | rows=4 | latency=0.424s
------------------------------------------------------------


## Question 2

**Which genes are associated with amyotrophic lateral sclerosis?**

In [4]:

question = 'Which genes are associated with amyotrophic lateral sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 13

  gene_name                   disease_name
0      ALS2  amyotrophic lateral sclerosis

 Run 1 completed | rows=13 | latency=0.595s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 35

  gene_name                   disease_name
0      ALS2  amyotrophic lateral sclerosis

 Run 2 completed | rows=35 | latency=1.161s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 12

  gene_name                   disease_name
0      ALS2  amyotrophic lateral sclerosis

 Run 3 completed | rows=12 | latency=0.587s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 21

  gene_name                   disease_name
0      ALS2  amyotrophic lateral sclerosis

 Run 4 completed | rows=21 | latency=0.860s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 18

  gene_name                   disease_name
0      ALS2  Amyotrophic Lateral Sclerosis

 Run 5 completed | rows=18 | latency=0.825s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [5]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 1 completed | rows=3 | latency=0.411s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 2 completed | rows=3 | latency=0.376s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     Melanoma      CDK4

 Run 3 completed | rows=3 | latency=0.498s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      CDK4     Melanoma

 Run 4 completed | rows=4 | latency=0.385s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 5 completed | rows=3 | latency=0.384s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [6]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 1 completed | rows=4 | latency=0.422s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 2 completed | rows=4 | latency=0.566s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 3 completed | rows=5 | latency=0.425s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 4 completed | rows=6 | latency=0.470s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 5 completed | rows=3 | latency=0.392s
------------------------------------------------------------


## Question 5

**Which drugs are used to treat rheumatoid arthritis?**

In [7]:

question = 'Which drugs are used to treat rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

      drug_name          disease_name
0  Methotrexate  Rheumatoid Arthritis

 Run 1 completed | rows=10 | latency=0.651s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

      drug_name          disease_name
0  Methotrexate  Rheumatoid Arthritis

 Run 2 completed | rows=10 | latency=0.546s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

      drug_name          disease_name
0  Methotrexate  Rheumatoid Arthritis

 Run 3 completed | rows=10 | latency=0.532s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

      drug_name          disease_name
0  Methotrexate  Rheumatoid Arthritis

 Run 4 completed | rows=10 | latency=0.533s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

      drug_name          disease_name
0  Methotrexate  Rheumatoid Arthritis

 Run 5 completed | rows=10 | latency=0.555s
------------------------------------------------------------


## Question 6

**Which genes are associated with ovarian cancer?**

In [8]:

question = 'Which genes are associated with ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 6

     disease_name gene_name
0  Ovarian Cancer     BRCA1

 Run 1 completed | rows=6 | latency=0.406s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

     disease_name gene_name
0  Ovarian Cancer     BRCA1

 Run 2 completed | rows=10 | latency=0.517s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 5

     disease_name gene_name
0  Ovarian Cancer     BRCA1

 Run 3 completed | rows=5 | latency=0.509s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 8

     disease_name gene_name
0  Ovarian Cancer     BRCA1

 Run 4 completed | rows=8 | latency=0.426s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 7

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 5 completed | rows=7 | latency=0.394s
------------------------------------------------------------


## Question 7

**What are the known targets of regorafenib?**

In [9]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 6

     drug_name gene_name
0  Regorafenib      FLT3

 Run 1 completed | rows=6 | latency=0.418s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 10

     drug_name gene_name
0  Regorafenib       KIT

 Run 2 completed | rows=10 | latency=0.548s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 10

     drug_name gene_name
0  Regorafenib      FLT3

 Run 3 completed | rows=10 | latency=0.525s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 7

     drug_name gene_name
0  Regorafenib    VEGFR2

 Run 4 completed | rows=7 | latency=0.466s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 13

     drug_name gene_name
0  Regorafenib    VEGFR2

 Run 5 completed | rows=13 | latency=0.577s
------------------------------------------------------------


## Question 8

**Which pathways are associated with the STAT3 gene?**

In [10]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 1 completed | rows=5 | latency=0.403s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 5

                 pathway_name gene_name
0  JAK/STAT signaling pathway     STAT3

 Run 2 completed | rows=5 | latency=0.444s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 3 completed | rows=5 | latency=0.384s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 4 completed | rows=5 | latency=0.421s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 5 completed | rows=5 | latency=0.388s
------------------------------------------------------------


## Question 9

**Which genes are associated with fever (pyrexia)?**

In [11]:

question = 'Which genes are associated with fever (pyrexia)?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

  gene_name  disease_name
0       TNF  disease_name

 Run 1 completed | rows=4 | latency=0.327s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0       TNF      Pyrexia

 Run 2 completed | rows=3 | latency=0.410s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 6

  gene_name  disease_name
0       TNF  disease_name

 Run 3 completed | rows=6 | latency=0.404s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 6

  gene_name  disease_name
0       TNF  disease_name

 Run 4 completed | rows=6 | latency=0.399s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      IL1B        Fever

 Run 5 completed | rows=4 | latency=0.476s
------------------------------------------------------------


## Question 10

**Which diseases are treated with bevacizumab?**

In [12]:

question = 'Which diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 1 completed | rows=6 | latency=0.419s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 2 completed | rows=7 | latency=0.431s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 3 completed | rows=7 | latency=0.449s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 4 completed | rows=7 | latency=0.422s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 5 completed | rows=7 | latency=0.415s
------------------------------------------------------------


## Question 11

**What are the known targets of cabozantinib?**

In [13]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name
0  Cabozantinib       MET

 Run 1 completed | rows=7 | latency=0.524s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name gene_name
0  cabozantinib       MET

 Run 2 completed | rows=6 | latency=0.530s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name gene_name
0  cabozantinib       MET

 Run 3 completed | rows=6 | latency=0.502s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name gene_name
0  cabozantinib       MET

 Run 4 completed | rows=6 | latency=0.479s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name gene_name
0  cabozantinib       MET

 Run 5 completed | rows=6 | latency=0.480s
------------------------------------------------------------


## Question 12

**Which pathways are associated with the TNF gene?**

In [14]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0       TNF    Apoptosis

 Run 1 completed | rows=5 | latency=0.423s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  pathway_name gene_name
0    Apoptosis       TNF

 Run 2 completed | rows=5 | latency=0.479s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0       TNF    Apoptosis

 Run 3 completed | rows=5 | latency=0.485s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  pathway_name gene_name
0    Apoptosis       TNF

 Run 4 completed | rows=5 | latency=0.455s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0       TNF    Apoptosis

 Run 5 completed | rows=5 | latency=0.477s
------------------------------------------------------------


## Question 13

**Which diseases are associated with the NPM1 gene?**

In [15]:

question = 'Which diseases are associated with the NPM1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 5

             disease_name gene_name
0  Acute Myeloid Leukemia      NPM1

 Run 1 completed | rows=5 | latency=0.454s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            disease_name
0      NPM1  Acute Myeloid Leukemia

 Run 2 completed | rows=3 | latency=0.387s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 3

             disease_name gene_name
0  Acute Myeloid Leukemia      NPM1

 Run 3 completed | rows=3 | latency=0.385s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 3

             disease_name gene_name
0  Acute Myeloid Leukemia      NPM1

 Run 4 completed | rows=3 | latency=0.399s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 5

             disease_name gene_name
0  Acute Myeloid Leukemia      NPM1

 Run 5 completed | rows=5 | latency=0.430s
------------------------------------------------------------


## Question 14

**Which pathways are associated with the CD19 gene?**

In [16]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 1 completed | rows=5 | latency=0.512s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 2 completed | rows=4 | latency=0.465s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 3 completed | rows=4 | latency=0.396s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 4 completed | rows=3 | latency=0.378s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 5 completed | rows=5 | latency=0.491s
------------------------------------------------------------


## Question 15

**Which drugs are used to treat migraine?**

In [17]:

question = 'Which drugs are used to treat migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 5

     drug_name disease_name
0  Sumatriptan     Migraine

 Run 1 completed | rows=5 | latency=0.425s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 5

     drug_name disease_name
0  Sumatriptan     Migraine

 Run 2 completed | rows=5 | latency=0.480s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 5

     drug_name disease_name
0  Sumatriptan     Migraine

 Run 3 completed | rows=5 | latency=0.401s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 15

     drug_name disease_name
0  Sumatriptan     migraine

 Run 4 completed | rows=15 | latency=0.608s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 8

     drug_name disease_name
0  Sumatriptan     Migraine

 Run 5 completed | rows=8 | latency=0.426s
------------------------------------------------------------


## Question 16

**What drugs are used to treat rickets?**

In [6]:

question = 'What drugs are used to treat rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 4

        drug_name disease_name
0  Ergocalciferol      Rickets

 Run 1 completed | rows=4 | latency=1.011s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 4

        drug_name disease_name
0  Ergocalciferol      Rickets

 Run 2 completed | rows=4 | latency=0.378s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 4

        drug_name disease_name
0  Ergocalciferol      Rickets

 Run 3 completed | rows=4 | latency=0.430s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 5

      drug_name disease_name
0  Alfacalcidol      Rickets

 Run 4 completed | rows=5 | latency=0.368s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 5

      drug_name disease_name
0  Alfacalcidol      Rickets

 Run 5 completed | rows=5 | latency=0.388s
------------------------------------------------------------


## Question 17

**Which genes are associated with epilepsy?**

In [19]:

question = 'Which genes are associated with epilepsy?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 1 completed | rows=7 | latency=0.495s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 2 completed | rows=10 | latency=0.478s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 6

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 3 completed | rows=6 | latency=0.399s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 4 completed | rows=10 | latency=0.512s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 5 completed | rows=10 | latency=0.528s
------------------------------------------------------------


## Question 18

**Which diseases are treated with trastuzumab deruxtecan?**

In [20]:

question = 'Which diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  Trastuzumab deruxtecan  Breast cancer

 Run 1 completed | rows=2 | latency=0.394s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  Trastuzumab deruxtecan  Breast cancer

 Run 2 completed | rows=2 | latency=0.392s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  Trastuzumab Deruxtecan  Breast Cancer

 Run 3 completed | rows=2 | latency=0.447s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

    disease_name               drug_name
0  Breast Cancer  Trastuzumab Deruxtecan

 Run 4 completed | rows=2 | latency=0.356s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  Trastuzumab Deruxtecan  Breast Cancer

 Run 5 completed | rows=2 | latency=0.371s
------------------------------------------------------------


## Question 19

**Which genes are associated with Alzheimer’s disease?**

In [21]:

question = 'Which genes are associated with Alzheimer’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 7

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 1 completed | rows=7 | latency=0.390s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 10

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 2 completed | rows=10 | latency=0.467s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 7

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 3 completed | rows=7 | latency=0.388s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 5

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 4 completed | rows=5 | latency=0.388s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 14

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 5 completed | rows=14 | latency=0.605s
------------------------------------------------------------


## Question 20

**For which diseases is darolutamide used?**

In [22]:

question = 'For which diseases is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 1 completed | rows=1 | latency=0.382s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 2 completed | rows=1 | latency=0.379s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 3 completed | rows=1 | latency=0.328s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 4 completed | rows=1 | latency=0.334s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 5 completed | rows=1 | latency=0.375s
------------------------------------------------------------


## Question 21

**Which genes are associated with renal cell carcinoma?**

In [23]:

question = 'Which genes are associated with renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 6

  gene_name          disease_name
0       VHL  Renal Cell Carcinoma

 Run 1 completed | rows=6 | latency=0.463s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Renal Cell Carcinoma       VHL

 Run 2 completed | rows=5 | latency=0.450s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 13

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 3 completed | rows=13 | latency=0.538s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 4 completed | rows=8 | latency=0.464s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

  gene_name          disease_name
0       VHL  Renal Cell Carcinoma

 Run 5 completed | rows=8 | latency=0.573s
------------------------------------------------------------


## Question 22

**Which diseases are associated with the KRAS gene?**

In [24]:

question = 'Which diseases are associated with the KRAS gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 1 completed | rows=3 | latency=0.401s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 2 completed | rows=3 | latency=0.381s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 3 completed | rows=3 | latency=0.371s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name       disease_name
0      KRAS  Pancreatic Cancer

 Run 4 completed | rows=3 | latency=0.457s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 5 completed | rows=3 | latency=0.367s
------------------------------------------------------------


## Question 23

**Which pathways are associated with the APP gene?**

In [25]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0       APP  Alzheimer's disease pathway

 Run 1 completed | rows=4 | latency=0.393s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                                       pathway_name
0       APP  Alzheimer disease-amyloid precursor protein pr...

 Run 2 completed | rows=4 | latency=0.589s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 3 completed | rows=4 | latency=0.463s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 4 completed | rows=6 | latency=0.468s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                 pathway_name
0       APP  Alzheimer's disease pathway

 Run 5 completed | rows=5 | latency=0.464s
------------------------------------------------------------


## Question 24

**Which genes are associated with schizophrenia?**

In [26]:

question = 'Which genes are associated with schizophrenia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 10

    disease_name gene_name
0  Schizophrenia      AKT1

 Run 1 completed | rows=10 | latency=0.467s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 2 completed | rows=5 | latency=0.373s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 8

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 3 completed | rows=8 | latency=0.476s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 4 completed | rows=5 | latency=0.353s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0      DRD2  Schizophrenia

 Run 5 completed | rows=5 | latency=0.430s
------------------------------------------------------------


## Question 25

**Which diseases are treated with valdecoxib?**

In [27]:

question = 'Which diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 1 completed | rows=4 | latency=0.405s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 2 completed | rows=4 | latency=0.397s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 3 completed | rows=4 | latency=0.520s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 4 completed | rows=4 | latency=0.472s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 5 completed | rows=4 | latency=0.460s
------------------------------------------------------------


## Question 26

**What are the known targets of vandetanib?**

In [28]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name
0  Vandetanib       RET

 Run 1 completed | rows=4 | latency=0.429s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 5

    drug_name gene_name
0  Vandetanib       RET

 Run 2 completed | rows=5 | latency=0.430s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 5

    drug_name gene_name
0  Vandetanib       RET

 Run 3 completed | rows=5 | latency=0.446s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 6

    drug_name gene_name
0  Vandetanib       RET

 Run 4 completed | rows=6 | latency=0.436s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  Vandetanib      EGFR

 Run 5 completed | rows=3 | latency=0.379s
------------------------------------------------------------


## Question 27

**Which pathways are associated with the CFTR gene?**

In [29]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 9

  gene_name pathway_name
0      CFTR    Apoptosis

 Run 1 completed | rows=9 | latency=0.532s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 11

  gene_name pathway_name
0      CFTR    Apoptosis

 Run 2 completed | rows=11 | latency=0.570s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 8

  gene_name pathway_name
0      CFTR    Apoptosis

 Run 3 completed | rows=8 | latency=0.481s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 4 completed | rows=4 | latency=0.433s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 11

  gene_name pathway_name
0      CFTR    Apoptosis

 Run 5 completed | rows=11 | latency=0.642s
------------------------------------------------------------


## Question 28

**Which drugs are used to treat tuberculosis?**

In [30]:

question = 'Which drugs are used to treat tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  Isoniazid  tuberculosis

 Run 1 completed | rows=4 | latency=0.387s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 2 completed | rows=5 | latency=0.393s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 3 completed | rows=5 | latency=0.459s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 4 completed | rows=5 | latency=0.388s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 5 completed | rows=5 | latency=0.385s
------------------------------------------------------------


## Question 29

**Which drugs are used to treat pancreatic adenocarcinoma?**

In [31]:

question = 'Which drugs are used to treat pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
 Attempt 1 failed after 0.424s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  Attempt 2/3
Entries retrieved: 6

     drug_name               disease_name
0  Gemcitabine  pancreatic adenocarcinoma

 Run 1 completed | rows=6 | latency=0.473s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  Gemcitabine  Pancreatic Adenocarcinoma

 Run 2 completed | rows=5 | latency=0.439s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  Gemcitabine  pancreatic adenocarcinoma

 Run 3 completed | rows=5 | latency=0.391s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  Gemcitabine  Pancreatic Adenocarcinoma

 Run 4 completed | rows=5 | latency=0.422s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  Gemcitabine  pancreatic adenocarcinoma

 Run 5 completed | rows=6 | latency=0.423s
------------------------------------------------------------


## Question 30

**Which drugs are used to treat chronic myeloid leukemia?**

In [32]:

question = 'Which drugs are used to treat chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  Chronic Myeloid Leukemia

 Run 1 completed | rows=5 | latency=0.438s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  Chronic Myeloid Leukemia

 Run 2 completed | rows=5 | latency=0.498s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  Chronic Myeloid Leukemia

 Run 3 completed | rows=5 | latency=0.440s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  Chronic Myeloid Leukemia

 Run 4 completed | rows=5 | latency=0.396s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  Chronic Myeloid Leukemia

 Run 5 completed | rows=5 | latency=0.428s
------------------------------------------------------------


## Question 31

**Which drugs are used to treat Parkinson’s disease?**

In [33]:

question = 'Which drugs are used to treat Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 10

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 1 completed | rows=10 | latency=0.510s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 12

  drug_name         disease_name
0  Levodopa  Parkinson’s disease

 Run 2 completed | rows=12 | latency=0.588s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 12

  drug_name         disease_name
0  Levodopa  Parkinson’s disease

 Run 3 completed | rows=12 | latency=0.561s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 10

  drug_name         disease_name
0  Levodopa  Parkinson’s disease

 Run 4 completed | rows=10 | latency=0.530s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 9

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 5 completed | rows=9 | latency=0.470s
------------------------------------------------------------


## Question 32

**Which drugs are used to treat inflammatory bowel disease?**

In [34]:

question = 'Which drugs are used to treat inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 9

          drug_name                disease_name
0  Aminosalicylates  Inflammatory Bowel Disease

 Run 1 completed | rows=9 | latency=0.521s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 13

    drug_name                disease_name
0  Infliximab  Inflammatory Bowel Disease

 Run 2 completed | rows=13 | latency=0.629s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 10

          drug_name                disease_name
0  Aminosalicylates  Inflammatory Bowel Disease

 Run 3 completed | rows=10 | latency=0.743s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 12

    drug_name                disease_name
0  Infliximab  Inflammatory Bowel Disease

 Run 4 completed | rows=12 | latency=0.549s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 9

          drug_name                disease_name
0  Aminosalicylates  Inflammatory Bowel Disease

 Run 5 completed | rows=9 | latency=0.576s
------------------------------------------------------------


## Question 33

**Which targets are acted on by imatinib?**

In [35]:

question = 'Which targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  Imatinib      ABL1

 Run 1 completed | rows=4 | latency=0.395s
------------------------------------------------------------

 Starting run 2 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  Imatinib      ABL1

 Run 2 completed | rows=4 | latency=0.386s
------------------------------------------------------------

 Starting run 3 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  Imatinib      ABL1

 Run 3 completed | rows=4 | latency=0.460s
------------------------------------------------------------

 Starting run 4 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  Imatinib      ABL1

 Run 4 completed | rows=4 | latency=0.445s
------------------------------------------------------------

 Starting run 5 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  Imatinib      ABL1

 Run 5 completed | rows=4 | latency=0.404s
------------------------------------------------------------


## Question 34

**Which biological targets does sorafenib interact with?**

In [36]:

question = 'Which biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Sorafenib      BRAF

 Run 1 completed | rows=6 | latency=0.424s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  Sorafenib      RAF1

 Run 2 completed | rows=10 | latency=0.532s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 7

   drug_name gene_name
0  Sorafenib      RAF1

 Run 3 completed | rows=7 | latency=0.569s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  Sorafenib      RAF1

 Run 4 completed | rows=5 | latency=0.414s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  Sorafenib      RAF1

 Run 5 completed | rows=5 | latency=0.462s
------------------------------------------------------------


## Question 35

**Which biological targets does tofacitinib interact with?**

In [37]:

question = 'Which biological targets does tofacitinib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 1 completed | rows=4 | latency=0.447s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 2 completed | rows=4 | latency=0.433s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 3 completed | rows=4 | latency=0.507s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 4 completed | rows=4 | latency=0.419s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 5 completed | rows=4 | latency=0.445s
------------------------------------------------------------


## Question 36

**Which drugs target EGFR?**

In [38]:

question = 'Which drugs target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 5

  drug_name gene_name
0  Afatinib      EGFR

 Run 1 completed | rows=5 | latency=0.409s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  Cetuximab      EGFR

 Run 2 completed | rows=5 | latency=0.543s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Erlotinib      EGFR

 Run 3 completed | rows=6 | latency=0.472s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name gene_name
0  Erlotinib      EGFR

 Run 4 completed | rows=7 | latency=0.597s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  Erlotinib      EGFR

 Run 5 completed | rows=5 | latency=0.381s
------------------------------------------------------------


## Question 37

**Which diseases are associated with TP53?**

In [39]:

question = 'Which diseases are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 7

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 1 completed | rows=7 | latency=0.423s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 9

    disease_name gene_name
0  Breast Cancer      TP53

 Run 2 completed | rows=9 | latency=0.457s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0      TP53  Breast Cancer

 Run 3 completed | rows=5 | latency=0.404s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0      TP53  Li-Fraumeni Syndrome

 Run 4 completed | rows=5 | latency=0.354s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 5 completed | rows=5 | latency=0.356s
------------------------------------------------------------


## Question 38

**Which diseases are associated with FGFR2?**

In [40]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 4

  gene_name    disease_name
0     FGFR2  Apert syndrome

 Run 1 completed | rows=4 | latency=0.493s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Apert syndrome

 Run 2 completed | rows=3 | latency=0.526s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 3 completed | rows=8 | latency=0.526s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Apert syndrome

 Run 4 completed | rows=3 | latency=0.432s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 7

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 5 completed | rows=7 | latency=0.465s
------------------------------------------------------------


## Question 39

**Which diseases are associated with HTT?**

In [41]:

question = 'Which diseases are associated with HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 1 completed | rows=1 | latency=0.313s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 2 completed | rows=1 | latency=0.339s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 3 completed | rows=1 | latency=0.318s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 4 completed | rows=1 | latency=0.382s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 5 completed | rows=1 | latency=0.324s
------------------------------------------------------------


## Question 40

**Which genes are associated with breast cancer?**

In [42]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Breast Cancer     BRCA1

 Run 1 completed | rows=5 | latency=0.386s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Breast Cancer     BRCA1

 Run 2 completed | rows=5 | latency=0.399s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Breast Cancer     BRCA1

 Run 3 completed | rows=5 | latency=0.436s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Breast Cancer     BRCA1

 Run 4 completed | rows=5 | latency=0.389s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Breast Cancer     BRCA1

 Run 5 completed | rows=5 | latency=0.368s
------------------------------------------------------------


## Question 41

**Which genes are associated with colorectal cancer?**

In [43]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 7

        disease_name gene_name
0  Colorectal cancer       APC

 Run 1 completed | rows=7 | latency=0.420s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal Cancer       APC

 Run 2 completed | rows=5 | latency=0.437s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal cancer       APC

 Run 3 completed | rows=5 | latency=0.379s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal Cancer       APC

 Run 4 completed | rows=5 | latency=0.419s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal Cancer       APC

 Run 5 completed | rows=5 | latency=0.373s
------------------------------------------------------------


## Question 42

**Which genes are associated with cystic fibrosis?**

In [44]:

question = 'Which genes are associated with cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  cystic fibrosis

 Run 1 completed | rows=1 | latency=0.292s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  cystic fibrosis

 Run 2 completed | rows=1 | latency=0.403s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic Fibrosis

 Run 3 completed | rows=1 | latency=0.325s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  cystic fibrosis

 Run 4 completed | rows=1 | latency=0.359s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  cystic fibrosis

 Run 5 completed | rows=1 | latency=0.317s
------------------------------------------------------------


## Question 43

**Which drugs are used to treat TNBC?**

In [45]:

question = 'Which drugs are used to treat TNBC?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 9

      drug_name                   disease_name
0  Capecitabine  Triple Negative Breast Cancer

 Run 1 completed | rows=9 | latency=0.520s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 9

       drug_name                   disease_name
0  Pembrolizumab  Triple-Negative Breast Cancer

 Run 2 completed | rows=9 | latency=0.597s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 8

       drug_name                   disease_name
0  Pembrolizumab  Triple Negative Breast Cancer

 Run 3 completed | rows=8 | latency=0.520s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 8

  drug_name                   disease_name
0  Eribulin  Triple-Negative Breast Cancer

 Run 4 completed | rows=8 | latency=0.555s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 10

      drug_name                   disease_name
0  Capecitabine  Triple Negative Breast Cancer

 Run 5 completed | rows=10 | latency=0.542s
------------------------------------------------------------


## Question 44

**Which diseases are treated with metformin?**

In [46]:

question = 'Which diseases are treated with metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 4

   drug_name     disease_name
0  Metformin  Type 2 Diabetes

 Run 1 completed | rows=4 | latency=0.419s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 3

   drug_name     disease_name
0  Metformin  Type 2 Diabetes

 Run 2 completed | rows=3 | latency=0.412s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 3

   drug_name     disease_name
0  Metformin  Type 2 Diabetes

 Run 3 completed | rows=3 | latency=0.461s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 3

   drug_name     disease_name
0  Metformin  Type 2 Diabetes

 Run 4 completed | rows=3 | latency=0.386s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 4

   drug_name     disease_name
0  Metformin  Type 2 Diabetes

 Run 5 completed | rows=4 | latency=0.441s
------------------------------------------------------------


## Question 45

**Which diseases are treated with adalimumab?**

In [47]:

question = 'Which diseases are treated with adalimumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 1 completed | rows=8 | latency=0.476s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 2 completed | rows=8 | latency=0.522s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 3 completed | rows=8 | latency=0.503s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 4 completed | rows=8 | latency=0.533s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 5 completed | rows=8 | latency=0.475s
------------------------------------------------------------


## Question 46

**For which diseases is pembrolizumab used?**

In [48]:

question = 'For which diseases is pembrolizumab used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 10

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 1 completed | rows=10 | latency=0.605s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 2 completed | rows=9 | latency=0.591s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 13

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 3 completed | rows=13 | latency=0.721s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 4 completed | rows=11 | latency=0.618s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 7

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 5 completed | rows=7 | latency=0.462s
------------------------------------------------------------


## Question 47

**Which diseases are treated with sorafenib?**

In [49]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  Hepatocellular carcinoma

 Run 1 completed | rows=3 | latency=0.373s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  Hepatocellular Carcinoma

 Run 2 completed | rows=3 | latency=0.385s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 4

   drug_name              disease_name
0  Sorafenib  Hepatocellular Carcinoma

 Run 3 completed | rows=4 | latency=0.398s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  Hepatocellular Carcinoma

 Run 4 completed | rows=3 | latency=0.371s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  Hepatocellular Carcinoma

 Run 5 completed | rows=3 | latency=0.475s
------------------------------------------------------------


## Question 48

**Which diseases are treated with nivolumab?**

In [50]:

question = 'Which diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 10

   drug_name          disease_name
0  Nivolumab  Renal Cell Carcinoma

 Run 1 completed | rows=10 | latency=0.677s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  Nivolumab     Melanoma

 Run 2 completed | rows=7 | latency=0.455s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

   drug_name disease_name
0  Nivolumab     Melanoma

 Run 3 completed | rows=9 | latency=0.498s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

   drug_name disease_name
0  Nivolumab     Melanoma

 Run 4 completed | rows=8 | latency=0.491s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 10

   drug_name disease_name
0  Nivolumab     Melanoma

 Run 5 completed | rows=10 | latency=0.642s
------------------------------------------------------------


## Question 49

**Which genes are associated with multiple sclerosis?**

In [51]:

question = 'Which genes are associated with multiple sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 16

  gene_name        disease_name
0     IL2RA  multiple sclerosis

 Run 1 completed | rows=16 | latency=0.741s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 2 completed | rows=5 | latency=0.411s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 17

         disease_name gene_name
0  Multiple Sclerosis      CD40

 Run 3 completed | rows=17 | latency=0.705s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 9

  gene_name        disease_name
0     IL2RA  multiple sclerosis

 Run 4 completed | rows=9 | latency=0.556s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 5 completed | rows=5 | latency=0.463s
------------------------------------------------------------


## Question 50

**Which genes are associated with rheumatoid arthritis?**

In [52]:

question = 'Which genes are associated with rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

           disease_name gene_name
0  Rheumatoid Arthritis  HLA-DRB1

 Run 1 completed | rows=10 | latency=0.519s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

  gene_name          disease_name
0  HLA-DRB1  rheumatoid arthritis

 Run 2 completed | rows=8 | latency=0.523s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Rheumatoid Arthritis       TNF

 Run 3 completed | rows=5 | latency=0.417s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Rheumatoid Arthritis  HLA-DRB1

 Run 4 completed | rows=5 | latency=0.414s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 10

  gene_name          disease_name
0  HLA-DRB1  rheumatoid arthritis

 Run 5 completed | rows=10 | latency=0.506s
------------------------------------------------------------


## Question 51

**What are the known targets of abatacept?**

In [53]:

question = 'What are the known targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  Abatacept      CD80

 Run 1 completed | rows=2 | latency=0.335s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  Abatacept      CD80

 Run 2 completed | rows=2 | latency=0.424s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  Abatacept      CD80

 Run 3 completed | rows=2 | latency=0.344s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 4 completed | rows=2 | latency=0.356s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  Abatacept      CD80

 Run 5 completed | rows=2 | latency=0.325s
------------------------------------------------------------


## Question 52

**Which genes are associated with lung cancer?**

In [54]:

question = 'Which genes are associated with lung cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0  Lung Cancer      EGFR

 Run 1 completed | rows=10 | latency=0.455s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0  Lung Cancer      EGFR

 Run 2 completed | rows=9 | latency=0.450s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0  Lung Cancer      EGFR

 Run 3 completed | rows=10 | latency=0.476s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0  Lung Cancer      EGFR

 Run 4 completed | rows=5 | latency=0.489s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0  Lung Cancer      EGFR

 Run 5 completed | rows=10 | latency=0.440s
------------------------------------------------------------


## Question 53

**What are the known targets of ponatinib?**

In [55]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 14

   drug_name gene_name
0  Ponatinib      ABL1

 Run 1 completed | rows=14 | latency=0.594s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 13

   drug_name gene_name
0  Ponatinib      ABL1

 Run 2 completed | rows=13 | latency=0.590s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 16

   drug_name gene_name
0  Ponatinib      ABL1

 Run 3 completed | rows=16 | latency=0.627s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 16

   drug_name gene_name
0  Ponatinib      ABL1

 Run 4 completed | rows=16 | latency=0.649s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 12

   drug_name gene_name
0  Ponatinib      ABL1

 Run 5 completed | rows=12 | latency=0.531s
------------------------------------------------------------


## Question 54

**Which drugs are used to treat systemic lupus erythematosus?**

In [56]:

question = 'Which drugs are used to treat systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic Lupus Erythematosus

 Run 1 completed | rows=8 | latency=0.659s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

   drug_name                  disease_name
0  Belimumab  Systemic Lupus Erythematosus

 Run 2 completed | rows=7 | latency=0.548s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic Lupus Erythematosus

 Run 3 completed | rows=6 | latency=0.534s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 3

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic Lupus Erythematosus

 Run 4 completed | rows=3 | latency=0.381s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 4

   drug_name                  disease_name
0  Belimumab  Systemic Lupus Erythematosus

 Run 5 completed | rows=4 | latency=0.468s
------------------------------------------------------------


## Question 55

**Which genes are associated with autism spectrum disorder?**

In [57]:

question = 'Which genes are associated with autism spectrum disorder?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 10

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 1 completed | rows=10 | latency=0.529s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 8

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 2 completed | rows=8 | latency=0.479s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 7

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 3 completed | rows=7 | latency=0.439s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 9

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 4 completed | rows=9 | latency=0.540s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 10

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 5 completed | rows=10 | latency=0.515s
------------------------------------------------------------


## Question 56

**Which diseases are associated with the ROS1 gene?**

In [58]:

question = 'Which diseases are associated with the ROS1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-Small Cell Lung Cancer      ROS1

 Run 1 completed | rows=4 | latency=0.408s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 2 completed | rows=5 | latency=0.450s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 3 completed | rows=5 | latency=0.463s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 4 completed | rows=6 | latency=0.493s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 5 completed | rows=6 | latency=0.481s
------------------------------------------------------------


## Question 57

**Which diseases are associated with the ALK gene?**

In [59]:

question = 'Which diseases are associated with the ALK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 1 completed | rows=3 | latency=0.396s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 2 completed | rows=3 | latency=0.567s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 3 completed | rows=3 | latency=0.369s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 4 completed | rows=3 | latency=0.411s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 3

                     disease_name gene_name
0  Anaplastic Large Cell Lymphoma       ALK

 Run 5 completed | rows=3 | latency=0.362s
------------------------------------------------------------


## Question 58

**Which diseases are associated with the EGFR gene?**

In [60]:

question = 'Which diseases are associated with the EGFR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name disease_name
0      EGFR  Lung Cancer

 Run 1 completed | rows=5 | latency=0.392s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      EGFR  Non-Small Cell Lung Cancer

 Run 2 completed | rows=5 | latency=0.417s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      EGFR  Non-Small Cell Lung Cancer

 Run 3 completed | rows=5 | latency=0.455s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0  Lung Cancer      EGFR

 Run 4 completed | rows=4 | latency=0.359s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      EGFR  Non-Small Cell Lung Cancer

 Run 5 completed | rows=5 | latency=0.400s
------------------------------------------------------------


## Question 59

**Which genes are associated with psoriasis?**

In [61]:

question = 'Which genes are associated with psoriasis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0    Psoriasis   TNFAIP3

 Run 1 completed | rows=5 | latency=0.399s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 11

  gene_name disease_name
0   TNFAIP3    Psoriasis

 Run 2 completed | rows=11 | latency=0.679s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 11

  gene_name disease_name
0     IL12B    Psoriasis

 Run 3 completed | rows=11 | latency=0.493s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 10

  gene_name disease_name
0     IL17A    Psoriasis

 Run 4 completed | rows=10 | latency=0.599s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 16

  gene_name disease_name
0     IL12B    Psoriasis

 Run 5 completed | rows=16 | latency=0.669s
------------------------------------------------------------


## Question 60

**Which genes are associated with ulcerative colitis?**

In [62]:

question = 'Which genes are associated with ulcerative colitis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 9

  gene_name        disease_name
0      NOD2  ulcerative colitis

 Run 1 completed | rows=9 | latency=0.672s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 10

  gene_name        disease_name
0      NOD2  ulcerative colitis

 Run 2 completed | rows=10 | latency=0.516s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 14

  gene_name        disease_name
0      NOD2  ulcerative colitis

 Run 3 completed | rows=14 | latency=0.667s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 10

  gene_name        disease_name
0      IL10  ulcerative colitis

 Run 4 completed | rows=10 | latency=0.603s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 8

  gene_name        disease_name
0      NOD2  ulcerative colitis

 Run 5 completed | rows=8 | latency=0.479s
------------------------------------------------------------


## Question 61

**Which genes are associated with tuberculosis?**

In [7]:

question = 'Which genes are associated with tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   disease_name gene_name
0  Tuberculosis    NRAMP1

 Run 1 completed | rows=5 | latency=0.416s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   disease_name gene_name
0  Tuberculosis    NRAMP1

 Run 2 completed | rows=5 | latency=0.521s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 6

  gene_name  disease_name
0    NRAMP1  tuberculosis

 Run 3 completed | rows=6 | latency=0.388s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 9

  gene_name  disease_name
0    NRAMP1  tuberculosis

 Run 4 completed | rows=9 | latency=0.448s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   disease_name gene_name
0  Tuberculosis    NRAMP1

 Run 5 completed | rows=5 | latency=0.423s
------------------------------------------------------------


## Question 62

**Which genes are associated with hepatitis C?**

In [64]:

question = 'Which genes are associated with hepatitis C?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0     IFNL3  Hepatitis C

 Run 1 completed | rows=4 | latency=0.403s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 5

  gene_name disease_name
0     IFNL3  Hepatitis C

 Run 2 completed | rows=5 | latency=0.429s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 5

  gene_name disease_name
0     IFNA1  Hepatitis C

 Run 3 completed | rows=5 | latency=0.410s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 5

  gene_name disease_name
0     IFNL3  Hepatitis C

 Run 4 completed | rows=5 | latency=0.425s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 8

  gene_name disease_name
0     IL28B  Hepatitis C

 Run 5 completed | rows=8 | latency=0.518s
------------------------------------------------------------


## Question 63

**Which genes are associated with Hodgkin lymphoma?**

In [65]:

question = 'Which genes are associated with Hodgkin lymphoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 11

  gene_name      disease_name
0   TNFAIP3  Hodgkin lymphoma

 Run 1 completed | rows=11 | latency=0.629s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 12

  gene_name      disease_name
0      BCL2  Hodgkin lymphoma

  Attempt 2/3
Entries retrieved: 7

  gene_name      disease_name
0      BCL2  Hodgkin lymphoma

 Run 2 completed | rows=7 | latency=0.514s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 9

  gene_name      disease_name
0      BCL2  Hodgkin lymphoma

 Run 3 completed | rows=9 | latency=0.480s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 12

  gene_name      disease_name
0      IRF5  Hodgkin lymphoma

 Run 4 completed | rows=12 | latency=0.537s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 22

  gene_name      disease_name
0      BCL2  Hodgkin lymphoma

 Run 5 completed | rows=22 | latency=0.811s
------------------------------------------------------------


## Question 64

**Which pathways are associated with TP53?**

In [66]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0      TP53    Apoptosis

 Run 1 completed | rows=5 | latency=0.498s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0      TP53    Apoptosis

 Run 2 completed | rows=5 | latency=0.418s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 3 completed | rows=4 | latency=0.472s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0      TP53    Apoptosis

 Run 4 completed | rows=5 | latency=0.420s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0      TP53    Apoptosis

 Run 5 completed | rows=5 | latency=0.425s
------------------------------------------------------------


## Question 65

**Which drugs target ERBB2?**

In [67]:

question = 'Which drugs target ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 1 completed | rows=3 | latency=0.444s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 8

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 2 completed | rows=7 | latency=0.668s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 3 completed | rows=3 | latency=0.404s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 5

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 4 completed | rows=5 | latency=0.605s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 5 completed | rows=3 | latency=0.414s
------------------------------------------------------------


## Question 66

**Which pathways are associated with the ADRB1 gene?**

In [68]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 7

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 1 completed | rows=7 | latency=0.599s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 2 completed | rows=3 | latency=0.429s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 3 completed | rows=5 | latency=0.532s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 4 completed | rows=3 | latency=0.418s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 9

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 5 completed | rows=9 | latency=0.655s
------------------------------------------------------------


## Question 67

**Which pathways are associated with the DRD2 gene?**

In [69]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 14

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 1 completed | rows=14 | latency=0.745s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 2 completed | rows=4 | latency=0.503s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 3 completed | rows=5 | latency=0.466s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 4 completed | rows=5 | latency=0.445s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 5 completed | rows=4 | latency=0.432s
------------------------------------------------------------


## Question 68

**Which pathways are associated with the HTR2A gene?**

In [70]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 1 completed | rows=4 | latency=0.435s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 2 completed | rows=4 | latency=0.470s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 3 completed | rows=4 | latency=0.440s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 4 completed | rows=4 | latency=0.499s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

                  pathway_name gene_name
0  Serotonin signaling pathway     HTR2A

 Run 5 completed | rows=4 | latency=0.480s
------------------------------------------------------------


## Question 69

**Which drugs target CD19?**

In [71]:

question = 'Which drugs target CD19?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 4

          drug_name gene_name
0  Tisagenlecleucel      CD19

 Run 1 completed | rows=4 | latency=0.520s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

          drug_name gene_name
0  Tisagenlecleucel      CD19

 Run 2 completed | rows=6 | latency=0.566s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Rituximab      CD19

 Run 3 completed | rows=6 | latency=0.521s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

          drug_name gene_name
0  Tisagenlecleucel      CD19

 Run 4 completed | rows=6 | latency=0.552s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

          drug_name gene_name
0  Tisagenlecleucel      CD19

 Run 5 completed | rows=6 | latency=0.513s
------------------------------------------------------------


## Question 70

**Which drugs target CTLA4?**

In [72]:

question = 'Which drugs target CTLA4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            df = df.drop_duplicates()
            latency = time.perf_counter() - start_time

            if latency>1.5:
                continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 1 completed | rows=2 | latency=0.402s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 2 completed | rows=2 | latency=0.375s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 3 completed | rows=2 | latency=0.436s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 4 completed | rows=2 | latency=0.373s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 5 completed | rows=2 | latency=0.455s
------------------------------------------------------------

In [8]:
import pickle
with open("Llama_same_question_response_final.pkl", "wb") as f:
    pickle.dump(dct_result, f)

import json
import pandas as pd

def make_json_safe(obj):
    if isinstance(obj, pd.DataFrame):
        return {
            "__type__": "dataframe",
            "columns": obj.columns.tolist(),
            "rows": obj.to_dict(orient="records")
        }
    elif isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    else:
        return obj


json_safe_result = make_json_safe(dct_result)

with open("Llama_same_question_response_final.json", "w", encoding="utf-8") as f:
    json.dump(
        json_safe_result,
        f,
        indent=2,
        ensure_ascii=False
    )