In [107]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from opentarget_utility import retrieve_opentarget

from gemini_utility import return_gemini_answer

In [108]:



model = "gemini-2.5-flash-lite"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [109]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     Melanoma      BRAF

 Run 1 completed | rows=5 | latency=1.252s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     melanoma      BRAF

 Run 2 completed | rows=5 | latency=1.219s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     melanoma      BRAF

 Run 3 completed | rows=5 | latency=0.889s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     melanoma      BRAF

 Run 4 completed | rows=5 | latency=1.206s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 31

  disease_name gene_name
0     melanoma      BRAF

 Run 5 completed | rows=31 | latency=1.963s
------------------------------------------------------------


## Question 2

**List genes linked to amyotrophic lateral sclerosis.**

In [110]:

question = 'List genes linked to amyotrophic lateral sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 46

  gene_name
0      SOD1

 Run 1 completed | rows=46 | latency=3.169s
------------------------------------------------------------

 Starting run 2 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 49

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 2 completed | rows=49 | latency=3.283s
------------------------------------------------------------

 Starting run 3 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 30

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 3 completed | rows=30 | latency=2.291s
------------------------------------------------------------

 Starting run 4 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 2099

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 4 completed | rows=2099 | latency=71.833s
------------------------------------------------------------

 Starting run 5 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 43

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 5 completed | rows=43 | latency=3.073s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [111]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
 Attempt 1 failed after 174.502s: Error tokenizing data. C error: Expected 2 fields in line 124, saw 4

  Attempt 2/3
Entries retrieved: 7

  disease_name gene_name
0     melanoma      CDK4

 Run 1 completed | rows=7 | latency=1.517s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0     melanoma      CDK4

 Run 2 completed | rows=4 | latency=1.033s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 10

  gene_name disease_name
0      CDK4     Melanoma

 Run 3 completed | rows=10 | latency=1.628s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     melanoma      CDK4

 Run 4 completed | rows=3 | latency=1.094s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 7

  gene_name  disease_name
0      CDK4  Glioblastoma

 Run 5 completed | rows=7 | latency=0.881s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [112]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 1 completed | rows=1 | latency=1.095s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 2 completed | rows=1 | latency=1.215s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
 Attempt 1 failed after 188.230s: Error tokenizing data. C error: Expected 2 fields in line 303, saw 4

  Attempt 2/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 3 completed | rows=1 | latency=1.543s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
 Attempt 1 failed after 3.737s: Error tokenizing data. C error: Expected 2 fields in line 8, saw 3

  Attempt 2/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 4 completed | rows=1 | latency=1.005s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 5 completed | rows=1 | latency=1.212s
------------------------------------------------------------


## Question 5

**Which drugs are used for treating rheumatoid arthritis?**

In [113]:

question = 'Which drugs are used for treating rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 15

           disease_name   drug_name
0  Rheumatoid Arthritis  Adalimumab

 Run 1 completed | rows=15 | latency=1.944s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 38

           disease_name  drug_name
0  Rheumatoid arthritis  Abatacept

 Run 2 completed | rows=38 | latency=2.641s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name   drug_name
0  Rheumatoid arthritis  Adalimumab

 Run 3 completed | rows=17 | latency=1.085s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 13

           disease_name   drug_name
0  Rheumatoid Arthritis  Adalimumab

 Run 4 completed | rows=13 | latency=1.217s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 15

           disease_name   drug_name
0  Rheumatoid arthritis  adalimumab

 Run 5 completed | rows=15 | latency=1.851s
------------------------------------------------------------


## Question 6

**What are the targets and mechanisms for dulaglutide?**

In [114]:

question = 'What are the targets and mechanisms for dulaglutide?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

                        target_name gene_name mechanism_of_action
0  Glucagon-like peptide-1 receptor     GLP1R             Agonist

 Run 1 completed | rows=1 | latency=1.089s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

      target_name gene_name                       mechanism_of_action
0  GLP-1 receptor     GLP1R  Glucagon-like peptide-1 receptor agonist

 Run 2 completed | rows=1 | latency=1.103s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

                        target_name gene_name mechanism_of_action
0  Glucagon-like peptide-1 receptor     GLP1R             Agonist

 Run 3 completed | rows=1 | latency=1.202s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 4 completed | rows=1 | latency=1.209s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

      target_name gene_name                       mechanism_of_action
0  GLP-1 receptor     GLP1R  Glucagon-like peptide-1 receptor agonist

 Run 5 completed | rows=1 | latency=1.316s
------------------------------------------------------------


## Question 7

**Provide target names for ovarian cancer?**

In [115]:

question = 'Provide target names for ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 5738

  gene_name    disease_name
0     BRCA1  ovarian cancer

 Run 1 completed | rows=5738 | latency=161.404s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 1 failed after 0.631s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 2 failed after 0.776s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 559

     disease_name target_name
0  ovarian cancer       BRCA1

 Run 2 completed | rows=559 | latency=15.232s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 1 failed after 0.775s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 2 failed after 0.761s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [target_name]
Index: []

 Attempt 3 failed after 0.984s: Returned DataFrame is empty
 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

  target_name
0        KRAS

 Run 4 completed | rows=10 | latency=1.116s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name    disease_name
0     BRCA1  ovarian cancer

 Run 5 completed | rows=10 | latency=1.446s
------------------------------------------------------------


## Question 8

**What are the known targets of regorafenib?**

In [116]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

     drug_name target_name gene_name mechanism_of_action
0  Regorafenib      VEGFR1       KDR           Inhibitor

 Run 1 completed | rows=12 | latency=1.720s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

     drug_name target_name gene_name        mechanism_of_action
0  Regorafenib      VEGFR1       KDR  Tyrosine kinase inhibitor

 Run 2 completed | rows=12 | latency=1.653s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name target_name gene_name        mechanism_of_action
0  regorafenib      VEGFR1       KDR  Tyrosine kinase inhibitor

 Run 3 completed | rows=9 | latency=1.537s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name target_name
0  regorafenib      VEGFR1

 Run 4 completed | rows=9 | latency=1.205s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 8

     drug_name target_name gene_name        mechanism_of_action
0  Regorafenib      VEGFR1       KDR  Tyrosine kinase inhibitor

 Run 5 completed | rows=8 | latency=1.305s
------------------------------------------------------------


## Question 9

**Which pathways are associated with the STAT3 gene?**

In [117]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 1 completed | rows=1 | latency=0.854s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 47

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 2 completed | rows=47 | latency=2.101s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 3 completed | rows=1 | latency=1.195s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 4 completed | rows=1 | latency=0.875s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 20

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 5 completed | rows=20 | latency=1.769s
------------------------------------------------------------


## Question 10

**Genes linked to fever.**

In [118]:

question = 'Genes linked to fever.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0        fever      IL1B

 Run 1 completed | rows=3 | latency=0.756s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0        Fever      IL1B

 Run 2 completed | rows=3 | latency=1.200s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0        fever      IL1B

 Run 3 completed | rows=10 | latency=1.429s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0        fever      IL1B

 Run 4 completed | rows=5 | latency=1.440s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0        fever      IL1B

 Run 5 completed | rows=3 | latency=1.091s
------------------------------------------------------------


## Question 11

**List all drugs that target EGFR?**

In [119]:

question = 'List all drugs that target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 10

     drug_name target_name
0  Osimertinib        EGFR

 Run 1 completed | rows=10 | latency=1.096s
------------------------------------------------------------

 Starting run 2 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 7

     drug_name target_name
0  Osimertinib        EGFR

 Run 2 completed | rows=7 | latency=0.984s
------------------------------------------------------------

 Starting run 3 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 8

     drug_name target_name
0  Osimertinib        EGFR

 Run 3 completed | rows=8 | latency=1.318s
------------------------------------------------------------

 Starting run 4 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name
0  Osimertinib        EGFR

 Run 4 completed | rows=6 | latency=1.315s
------------------------------------------------------------

 Starting run 5 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 5

     drug_name target_name
0  Osimertinib        EGFR

 Run 5 completed | rows=5 | latency=1.434s
------------------------------------------------------------


## Question 12

**Show drugs that inhibit the FGFR2 gene?**

In [120]:

question = 'Show drugs that inhibit the FGFR2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name mechanism_of_action
0  Pemigatinib     FGFR2      FGFR inhibitor

 Run 1 completed | rows=4 | latency=1.518s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name mechanism_of_action
0  Pemigatinib     FGFR2      FGFR inhibitor

 Run 2 completed | rows=4 | latency=1.097s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name mechanism_of_action
0  Pemigatinib     FGFR2      FGFR inhibitor

 Run 3 completed | rows=4 | latency=1.325s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Pemigatinib     FGFR2

 Run 4 completed | rows=4 | latency=1.313s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

     drug_name gene_name
0  Pemigatinib     FGFR2

 Run 5 completed | rows=4 | latency=1.422s
------------------------------------------------------------


## Question 13

**What diseases are treated with bevacizumab?**

In [121]:

question = 'What diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 12

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 1 completed | rows=12 | latency=1.620s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

        disease_name    drug_name
0  colorectal cancer  bevacizumab

 Run 2 completed | rows=7 | latency=1.305s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 10

        disease_name    drug_name
0  colorectal cancer  bevacizumab

 Run 3 completed | rows=10 | latency=0.914s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

        disease_name    drug_name
0  colorectal cancer  bevacizumab

 Run 4 completed | rows=7 | latency=0.636s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

        disease_name    drug_name
0  colorectal cancer  bevacizumab

 Run 5 completed | rows=7 | latency=1.535s
------------------------------------------------------------


## Question 14

**List treatments for plaque psoriasis and their mechanisms.**

In [122]:

question = 'List treatments for plaque psoriasis and their mechanisms.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 12

       disease_name   drug_name mechanism_of_action
0  plaque psoriasis  adalimumab       TNF inhibitor

 Run 1 completed | rows=12 | latency=1.730s
------------------------------------------------------------

 Starting run 2 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 10

       disease_name   drug_name                   mechanism_of_action
0  plaque psoriasis  adalimumab  Inhibits tumor necrosis factor-alpha

 Run 2 completed | rows=10 | latency=1.974s
------------------------------------------------------------

 Starting run 3 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 9

       disease_name   drug_name                       mechanism_of_action
0  plaque psoriasis  adalimumab  Inhibitor of tumor necrosis factor-alpha

 Run 3 completed | rows=9 | latency=1.339s
------------------------------------------------------------

 Starting run 4 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
 Attempt 1 failed after 1.293s: Error tokenizing data. C error: Expected 3 fields in line 11, saw 4

  Attempt 2/3
Entries retrieved: 13

       disease_name   drug_name     mechanism_of_action
0  plaque psoriasis  adalimumab  Inhibitor of TNF-alpha

 Run 4 completed | rows=13 | latency=1.431s
------------------------------------------------------------

 Starting run 5 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 8

       disease_name   drug_name mechanism_of_action
0  plaque psoriasis  adalimumab  inhibits TNF-alpha

 Run 5 completed | rows=8 | latency=1.415s
------------------------------------------------------------


## Question 15

**What are the known targets of cabozantinib?**

In [123]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name target_name gene_name        mechanism_of_action
0  cabozantinib         MET       MET  Tyrosine kinase inhibitor

 Run 1 completed | rows=6 | latency=1.442s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name target_name gene_name mechanism_of_action
0  cabozantinib         MET       MET           inhibitor

 Run 2 completed | rows=7 | latency=1.537s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 8

      drug_name target_name gene_name        mechanism_of_action
0  cabozantinib         MET       MET  tyrosine kinase inhibitor

 Run 3 completed | rows=8 | latency=1.551s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 8

      drug_name target_name gene_name                 mechanism_of_action
0  Cabozantinib         MET       MET  Receptor tyrosine kinase inhibitor

 Run 4 completed | rows=8 | latency=1.537s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name target_name gene_name        mechanism_of_action
0  cabozantinib         MET       MET  Tyrosine kinase inhibitor

 Run 5 completed | rows=7 | latency=1.211s
------------------------------------------------------------


## Question 16

**Show drugs that inhibit the RET gene?**

In [124]:

question = 'Show drugs that inhibit the RET gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

       drug_name gene_name mechanism_of_action
0  Selpercatinib       RET    Kinase inhibitor

 Run 1 completed | rows=2 | latency=1.183s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

       drug_name gene_name mechanism_of_action
0  Selpercatinib       RET    Kinase inhibitor

 Run 2 completed | rows=2 | latency=0.877s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

       drug_name gene_name
0  Selpercatinib       RET

 Run 3 completed | rows=2 | latency=1.438s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

       drug_name target_name gene_name mechanism_of_action
0  Selpercatinib         RET       RET    Kinase inhibitor

 Run 4 completed | rows=2 | latency=0.997s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 10

     drug_name gene_name mechanism_of_action
0  Selumetinib       RET           Inhibitor

 Run 5 completed | rows=10 | latency=2.085s
------------------------------------------------------------


## Question 17

**Which pathways are associated with the TNF gene?**

In [125]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 10

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 1 completed | rows=10 | latency=1.523s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 113

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 2 completed | rows=113 | latency=5.632s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
 Attempt 1 failed after 174.908s: Error tokenizing data. C error: Expected 2 fields in line 8, saw 3

  Attempt 2/3
Entries retrieved: 4

  gene_name                  pathway_name
0       TNF  NF-kappa B signaling pathway

 Run 3 completed | rows=4 | latency=1.312s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name          pathway_name
0       TNF  NF-kappa B signaling

 Run 4 completed | rows=5 | latency=0.886s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

                   pathway_name gene_name
0  NF-kappa B signaling pathway       TNF

 Run 5 completed | rows=5 | latency=0.891s
------------------------------------------------------------


## Question 18

**Diseases associated with the gene NPM1.**

In [126]:

question = 'Diseases associated with the gene NPM1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 2

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 1 completed | rows=2 | latency=1.196s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 2 completed | rows=1 | latency=0.765s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 3 completed | rows=1 | latency=0.772s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 2

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 4 completed | rows=2 | latency=1.194s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 5 completed | rows=1 | latency=1.215s
------------------------------------------------------------


## Question 19

**Which pathways are associated with the CD19 gene?**

In [127]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 1 completed | rows=1 | latency=0.988s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
 Attempt 1 failed after 19.927s: Error tokenizing data. C error: Expected 2 fields in line 19, saw 3

  Attempt 2/3
Entries retrieved: 3

            pathway_name gene_name
0  BCR signaling pathway      CD19

 Run 2 completed | rows=3 | latency=1.336s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 3 completed | rows=1 | latency=1.204s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

             pathway_name gene_name
0  MAPK signaling pathway      CD19

 Run 4 completed | rows=5 | latency=1.003s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
 Attempt 1 failed after 181.165s: Error tokenizing data. C error: Expected 2 fields in line 46, saw 3

  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [pathway_name]
Index: []

 Attempt 2 failed after 1.293s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 1

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 5 completed | rows=1 | latency=1.098s
------------------------------------------------------------


## Question 20

**Which drugs are used for treating migraine?**

In [128]:

question = 'Which drugs are used for treating migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 16

     drug_name disease_name
0  sumatriptan     migraine

 Run 1 completed | rows=16 | latency=1.516s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 30

  disease_name    drug_name
0     Migraine  Sumatriptan

 Run 2 completed | rows=30 | latency=1.973s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 32

     drug_name disease_name
0  sumatriptan     migraine

 Run 3 completed | rows=32 | latency=1.862s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 27

     drug_name disease_name
0  Sumatriptan     Migraine

 Run 4 completed | rows=27 | latency=2.525s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 52

  disease_name    drug_name
0     Migraine  Sumatriptan

 Run 5 completed | rows=52 | latency=3.066s
------------------------------------------------------------


## Question 21

**What are the targets and mechanisms for rituximab?**

In [129]:

question = 'What are the targets and mechanisms for rituximab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
Rituximab,CD20,CD20,Antibody-dependent cell-mediated cytotoxicity,Complement-dependent cytotoxicity

 Run 1 completed | rows=1 | latency=1.087s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,Rituximab,CD20,CD20,Antibody-dependent cell-mediated cytotoxicity

 Run 2 completed | rows=1 | latency=0.884s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name gene_name   mechanism_of_action
0  Rituximab        CD20      CD20  Depletion of B cells

 Run 3 completed | rows=1 | latency=1.202s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

  target_name   mechanism_of_action
0        CD20  Depletion of B cells

 Run 4 completed | rows=1 | latency=1.199s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

  target_name gene_name                                mechanism_of_action
0        CD20     MS4A1  Depletes B cells by binding to CD20 antigen ex...

 Run 5 completed | rows=1 | latency=1.396s
------------------------------------------------------------


## Question 22

**Provide target names for colorectal cancer?**

In [130]:

question = 'Provide target names for colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name target_name
0  Colorectal cancer        KRAS

 Run 1 completed | rows=14 | latency=1.737s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 10

        disease_name target_name
0  colorectal cancer        KRAS

 Run 2 completed | rows=10 | latency=1.427s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 62

  gene_name       disease_name
0      KRAS  colorectal cancer

 Run 3 completed | rows=62 | latency=2.526s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 378

  gene_name       disease_name
0      KRAS  colorectal cancer

 Run 4 completed | rows=378 | latency=11.159s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5048

  gene_name       disease_name
0      KRAS  colorectal cancer

 Run 5 completed | rows=5048 | latency=128.943s
------------------------------------------------------------


## Question 23

**Which are possible drugs against rickets?**

In [131]:

question = 'Which are possible drugs against rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

  disease_name   drug_name
0      rickets  calcitriol

 Run 1 completed | rows=4 | latency=0.809s
------------------------------------------------------------

 Starting run 2 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 3

  disease_name       drug_name
0      rickets  Ergocalciferol

 Run 2 completed | rows=3 | latency=1.054s
------------------------------------------------------------

 Starting run 3 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

  disease_name   drug_name
0      rickets  calcitriol

 Run 3 completed | rows=4 | latency=1.403s
------------------------------------------------------------

 Starting run 4 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 3

  disease_name   drug_name
0      rickets  calcitriol

 Run 4 completed | rows=3 | latency=0.766s
------------------------------------------------------------

 Starting run 5 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 3

  disease_name        drug_name
0      rickets  cholecalciferol

 Run 5 completed | rows=3 | latency=0.821s
------------------------------------------------------------


## Question 24

**Give me genes linked to epilepsy.**

In [132]:

question = 'Give me genes linked to epilepsy.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0     SCN1A

 Run 1 completed | rows=5 | latency=1.055s
------------------------------------------------------------

 Starting run 2 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 10

  gene_name
0     SCN1A

 Run 2 completed | rows=10 | latency=1.060s
------------------------------------------------------------

 Starting run 3 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     epilepsy     SCN1A

 Run 3 completed | rows=10 | latency=0.846s
------------------------------------------------------------

 Starting run 4 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     epilepsy     SCN1A

 Run 4 completed | rows=10 | latency=1.278s
------------------------------------------------------------

 Starting run 5 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 10

  disease_name gene_name
0     epilepsy     SCN1A

 Run 5 completed | rows=10 | latency=1.057s
------------------------------------------------------------


## Question 25

**What diseases are treated with trastuzumab deruxtecan?**

In [133]:

question = 'What diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 7

    disease_name               drug_name
0  breast cancer  trastuzumab deruxtecan

 Run 1 completed | rows=7 | latency=1.286s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 5

               disease_name
0  metastatic breast cancer

 Run 2 completed | rows=5 | latency=1.262s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 8

    disease_name               drug_name
0  breast cancer  trastuzumab deruxtecan

 Run 3 completed | rows=8 | latency=1.077s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 5

               disease_name               drug_name
0  metastatic breast cancer  trastuzumab deruxtecan

 Run 4 completed | rows=5 | latency=1.485s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 5

                  disease_name               drug_name
0  HER2-positive breast cancer  trastuzumab deruxtecan

 Run 5 completed | rows=5 | latency=0.625s
------------------------------------------------------------


## Question 26

**Genes linked to Alzheimer’s disease.**

In [134]:

question = 'Genes linked to Alzheimer’s disease.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 5

          disease_name gene_name
0  Alzheimer’s disease       APP

 Run 1 completed | rows=5 | latency=1.486s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 10

          disease_name gene_name
0  Alzheimer’s disease       APP

 Run 2 completed | rows=10 | latency=1.485s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 93

          disease_name gene_name
0  Alzheimer’s disease       APP

 Run 3 completed | rows=93 | latency=5.806s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 5

          disease_name gene_name
0  Alzheimer’s disease       APP

 Run 4 completed | rows=5 | latency=1.269s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4771

          disease_name gene_name
0  Alzheimer’s disease       APP

 Run 5 completed | rows=4771 | latency=168.881s
------------------------------------------------------------


## Question 27

**For which disease is darolutamide used?**

In [135]:

question = 'For which disease is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  prostate cancer  darolutamide

 Run 1 completed | rows=1 | latency=1.240s
------------------------------------------------------------

 Starting run 2 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  prostate cancer  darolutamide

 Run 2 completed | rows=1 | latency=1.062s
------------------------------------------------------------

 Starting run 3 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  prostate cancer  darolutamide

 Run 3 completed | rows=1 | latency=0.749s
------------------------------------------------------------

 Starting run 4 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  prostate cancer  darolutamide

 Run 4 completed | rows=1 | latency=1.178s
------------------------------------------------------------

 Starting run 5 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  prostate cancer  darolutamide

 Run 5 completed | rows=1 | latency=0.858s
------------------------------------------------------------


## Question 28

**Provide target names for renal cell carcinoma?**

In [136]:

question = 'Provide target names for renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 48

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 1 completed | rows=48 | latency=2.335s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 1 failed after 1.057s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 2 failed after 0.738s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 3 failed after 0.533s: Returned DataFrame is empty
 Run 2 failed after 3 attempts
------------------------------------------------------------

 Starting run 3 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 1 failed after 1.067s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 2 failed after 0.851s: Returned DataFrame is empty
  Attempt 3/3
Entries retrieved: 21

  gene_name          disease_name target_name
0       VHL  renal cell carcinoma         VHL

 Run 3 completed | rows=21 | latency=1.804s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 9

           disease_name target_name
0  Renal cell carcinoma       VEGFA

 Run 4 completed | rows=9 | latency=1.601s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 10

  gene_name target_name          disease_name
0       VHL         VHL  renal cell carcinoma

 Run 5 completed | rows=10 | latency=1.411s
------------------------------------------------------------


## Question 29

**Diseases associated with the gene KRAS.**

In [137]:

question = 'Diseases associated with the gene KRAS.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 2914

        disease_name gene_name
0  Colorectal cancer      KRAS

 Run 1 completed | rows=2914 | latency=175.602s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 27

        disease_name gene_name
0  Colorectal cancer      KRAS

 Run 2 completed | rows=27 | latency=2.318s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 4

        disease_name gene_name
0  Colorectal cancer      KRAS

 Run 3 completed | rows=4 | latency=1.173s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 4

        disease_name gene_name
0  pancreatic cancer      KRAS

 Run 4 completed | rows=4 | latency=1.168s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 6

        disease_name gene_name
0  pancreatic cancer      KRAS

 Run 5 completed | rows=6 | latency=1.270s
------------------------------------------------------------


## Question 30

**Which pathways are associated with the APP gene?**

In [138]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

                           pathway_name gene_name
0  Alzheimer disease-Amyloid processing       APP

 Run 1 completed | rows=1 | latency=0.949s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 5312

        pathway_name gene_name
0  Amyloid formation       APP

 Run 2 completed | rows=5312 | latency=180.837s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 3

         pathway_name gene_name
0  Amyloid processing       APP

 Run 3 completed | rows=3 | latency=1.057s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

                           pathway_name gene_name
0  Alzheimer disease-Amyloid processing       APP

 Run 4 completed | rows=2 | latency=1.278s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 9493

                             pathway_name gene_name
0  Alzheimer's disease-Amyloid processing       APP

 Run 5 completed | rows=9493 | latency=165.498s
------------------------------------------------------------


## Question 31

**Genes linked to schizophrenia.**

In [139]:

question = 'Genes linked to schizophrenia.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 1 completed | rows=5 | latency=1.683s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0      DRD2  schizophrenia

 Run 2 completed | rows=10 | latency=1.378s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0      DRD2  schizophrenia

 Run 3 completed | rows=10 | latency=1.689s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 4 completed | rows=3 | latency=1.177s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 5 completed | rows=5 | latency=0.957s
------------------------------------------------------------


## Question 32

**What diseases are treated with valdecoxib?**

In [140]:

question = 'What diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

           disease_name   drug_name
0  Rheumatoid arthritis  valdecoxib

 Run 1 completed | rows=2 | latency=1.253s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 3

     disease_name   drug_name
0  Osteoarthritis  valdecoxib

 Run 2 completed | rows=3 | latency=0.849s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 3

  disease_name   drug_name
0    Arthritis  valdecoxib

 Run 3 completed | rows=3 | latency=1.168s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

  disease_name   drug_name
0    Arthritis  valdecoxib

 Run 4 completed | rows=2 | latency=1.277s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

     disease_name   drug_name
0  Osteoarthritis  valdecoxib

 Run 5 completed | rows=4 | latency=0.752s
------------------------------------------------------------


## Question 33

**What are the known targets of vandetanib?**

In [141]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 6

    drug_name target_name gene_name        mechanism_of_action
0  vandetanib      VEGFR2       KDR  tyrosine kinase inhibitor

 Run 1 completed | rows=6 | latency=1.472s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action
0,vandetanib,Vascular endothelial growth factor receptor 2,KDR,Tyrosine kinase inhibitor

 Run 2 completed | rows=5 | latency=1.562s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 42

,target_name,gene_name,drug_name,mechanism_of_action,approval_status
0,Vascular endothelial growth factor receptor 2,KDR,vandetanib,Tyrosine kinase inhibitor,Approved

 Run 3 completed | rows=42 | latency=4.562s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name        mechanism_of_action
0      VEGFR1      FLT1  Tyrosine kinase inhibitor

 Run 4 completed | rows=5 | latency=0.958s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name gene_name        mechanism_of_action
0  vandetanib      VEGFR2       KDR  Tyrosine kinase inhibitor

 Run 5 completed | rows=4 | latency=1.698s
------------------------------------------------------------


## Question 34

**Which pathways are associated with the CFTR gene?**

In [142]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name     pathway_name
0      CFTR  Cystic fibrosis

 Run 1 completed | rows=2 | latency=1.138s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 3

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 2 completed | rows=3 | latency=1.166s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 3

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 3 completed | rows=3 | latency=0.958s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

                       pathway_name gene_name
0  CFTR-mediated chloride transport      CFTR

 Run 4 completed | rows=1 | latency=1.272s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 5

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 5 completed | rows=5 | latency=0.951s
------------------------------------------------------------


## Question 35

**Which drugs are used for TB?**

In [143]:

question = 'Which drugs are used for TB?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 14

   disease_name   drug_name
0  Tuberculosis  Rifampicin

 Run 1 completed | rows=14 | latency=1.456s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 10

    drug_name  disease_name
0  Rifampicin  Tuberculosis

 Run 2 completed | rows=10 | latency=1.491s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 14

   disease_name   drug_name
0  Tuberculosis  Ethambutol

 Run 3 completed | rows=14 | latency=1.488s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for TB?
  Attempt 1/3
 Attempt 1 failed after 163.779s: Error tokenizing data. C error: Expected 2 fields in line 47, saw 3

  Attempt 2/3
Entries retrieved: 17

   disease_name   drug_name
0  Tuberculosis  Rifampicin

 Run 4 completed | rows=17 | latency=1.638s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 8

   disease_name  drug_name
0  Tuberculosis  Isoniazid

 Run 5 completed | rows=8 | latency=1.322s
------------------------------------------------------------


## Question 36

**Which drugs are used for pancreatic adenocarcinoma?**

In [144]:

question = 'Which drugs are used for pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 15

                disease_name    drug_name
0  pancreatic adenocarcinoma  Gemcitabine

 Run 1 completed | rows=15 | latency=1.524s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 40

                disease_name    drug_name
0  pancreatic adenocarcinoma  Gemcitabine

 Run 2 completed | rows=40 | latency=2.729s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 662

                disease_name    drug_name
0  pancreatic adenocarcinoma  gemcitabine

 Run 3 completed | rows=662 | latency=12.667s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 25

                disease_name    drug_name
0  pancreatic adenocarcinoma  Gemcitabine

 Run 4 completed | rows=25 | latency=2.001s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 35

                disease_name    drug_name
0  pancreatic adenocarcinoma  Gemcitabine

 Run 5 completed | rows=35 | latency=2.672s
------------------------------------------------------------


## Question 37

**Which drugs are used in chronic myeloid leukemia?**

In [145]:

question = 'Which drugs are used in chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 9

               disease_name drug_name
0  Chronic myeloid leukemia  Imatinib

 Run 1 completed | rows=9 | latency=1.405s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name
0  chronic myeloid leukemia  Imatinib

 Run 2 completed | rows=6 | latency=1.215s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 13

               disease_name  drug_name approval_status
0  chronic myeloid leukemia  Asciminib        Approved

 Run 3 completed | rows=13 | latency=1.870s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name
0  Chronic myeloid leukemia  Imatinib

 Run 4 completed | rows=6 | latency=1.329s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

               disease_name drug_name
0  chronic myeloid leukemia  imatinib

 Run 5 completed | rows=5 | latency=0.877s
------------------------------------------------------------


## Question 38

**What drugs are used in the treatment of Parkinson’s disease?**

In [146]:

question = 'What drugs are used in the treatment of Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 9

          disease_name drug_name
0  Parkinson's disease  Levodopa

 Run 1 completed | rows=9 | latency=1.423s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

          disease_name drug_name
0  Parkinson's disease  Levodopa

 Run 2 completed | rows=15 | latency=1.869s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 11

          disease_name drug_name
0  Parkinson's disease  Levodopa

 Run 3 completed | rows=11 | latency=1.564s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 11

          disease_name drug_name
0  Parkinson's disease  Levodopa

 Run 4 completed | rows=11 | latency=1.876s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 11

          disease_name drug_name
0  Parkinson's disease  Levodopa

 Run 5 completed | rows=11 | latency=1.441s
------------------------------------------------------------


## Question 39

**Which drugs are used for inflammatory bowel disease?**

In [147]:

question = 'Which drugs are used for inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 14

                 disease_name   drug_name
0  Inflammatory bowel disease  Adalimumab

 Run 1 completed | rows=14 | latency=1.751s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 27

                 disease_name   drug_name
0  Inflammatory Bowel Disease  Adalimumab

 Run 2 completed | rows=27 | latency=2.264s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 22

                 disease_name   drug_name
0  Inflammatory bowel disease  Adalimumab

 Run 3 completed | rows=22 | latency=2.142s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 19

                 disease_name   drug_name
0  Inflammatory bowel disease  Infliximab

 Run 4 completed | rows=19 | latency=1.213s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 12

                 disease_name   drug_name
0  Inflammatory Bowel Disease  Adalimumab

 Run 5 completed | rows=12 | latency=1.102s
------------------------------------------------------------


## Question 40

**What targets are acted on by imatinib?**

In [148]:

question = 'What targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 6

  target_name gene_name        mechanism_of_action
0     BCR-ABL      ABL1  Tyrosine kinase inhibitor

 Run 1 completed | rows=6 | latency=1.188s
------------------------------------------------------------

 Starting run 2 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  target_name
0     BCR-ABL

 Run 2 completed | rows=4 | latency=0.768s
------------------------------------------------------------

 Starting run 3 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 9

  target_name drug_name
0     BCR-ABL  imatinib

 Run 3 completed | rows=9 | latency=1.306s
------------------------------------------------------------

 Starting run 4 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 6

  target_name drug_name
0     BCR-ABL  imatinib

 Run 4 completed | rows=6 | latency=1.085s
------------------------------------------------------------

 Starting run 5 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name
0     BCR-ABL      ABL1

 Run 5 completed | rows=5 | latency=0.897s
------------------------------------------------------------


## Question 41

**What biological targets does sorafenib interact with?**

In [149]:

question = 'What biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action
0,Sorafenib,VEGFR,Vascular Endothelial Growth Factor Receptor,Inhibitor

 Run 1 completed | rows=5 | latency=1.185s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name
0  sorafenib        RAF1

 Run 2 completed | rows=6 | latency=0.762s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 12

,drug_name,target_name,gene_name,mechanism_of_action
0,sorafenib,RAF proto-oncogene serine/threonine-protein ki...,RAF1,Inhibitor

 Run 3 completed | rows=12 | latency=1.968s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
 Attempt 1 failed after 1.509s: Error tokenizing data. C error: Expected 4 fields in line 5, saw 5

  Attempt 2/3
Entries retrieved: 20

,drug_name,target_name,gene_name,mechanism_of_action
sorafenib,RAF proto-oncogene,serine/threonine kinase,BRAF,Inhibitor

 Run 4 completed | rows=20 | latency=3.196s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name gene_name                         mechanism_of_action
0  Sorafenib       VEGFR     VEGFA  Inhibits receptor tyrosine kinase activity

 Run 5 completed | rows=7 | latency=0.762s
------------------------------------------------------------


## Question 42

**What biological targets does tofacitinib affect?**

In [150]:

question = 'What biological targets does tofacitinib affect?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 4

     drug_name   target_name gene_name mechanism_of_action
0  Tofacitinib  Janus kinase      JAK1           Inhibitor

 Run 1 completed | rows=4 | latency=1.330s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name   target_name gene_name mechanism_of_action
0  tofacitinib  Janus kinase      JAK1           Inhibitor

 Run 2 completed | rows=3 | latency=0.868s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name     target_name gene_name mechanism_of_action
0  tofacitinib  Janus kinase 1      JAK1           Inhibitor

 Run 3 completed | rows=3 | latency=1.299s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name     target_name gene_name mechanism_of_action
0  tofacitinib  Janus kinase 1      JAK1           Inhibitor

 Run 4 completed | rows=3 | latency=1.105s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name   target_name gene_name mechanism_of_action
0  tofacitinib  Janus kinase      JAK1     JAK1 inhibition

 Run 5 completed | rows=3 | latency=1.435s
------------------------------------------------------------


## Question 43

**Which drugs are known to target EGFR?**

In [151]:

question = 'Which drugs are known to target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 11

     drug_name                       target_name gene_name
0  Osimertinib  Epidermal growth factor receptor      EGFR

 Run 1 completed | rows=11 | latency=1.076s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 24

     drug_name target_name
0  Osimertinib        EGFR

 Run 2 completed | rows=24 | latency=1.754s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name
0  Osimertinib        EGFR

 Run 3 completed | rows=6 | latency=0.991s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6685

     drug_name target_name
0  Osimertinib        EGFR

 Run 4 completed | rows=6685 | latency=113.889s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name gene_name
0  Osimertinib        EGFR      EGFR

 Run 5 completed | rows=6 | latency=1.302s
------------------------------------------------------------


## Question 44

**Which diseases are linked to the TP53?**

In [152]:

question = 'Which diseases are linked to the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 13

    disease_name gene_name
0  Breast cancer      TP53

 Run 1 completed | rows=13 | latency=1.396s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 2

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 2 completed | rows=2 | latency=0.977s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 2

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 3 completed | rows=2 | latency=0.883s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0       Cancer      TP53

 Run 4 completed | rows=2 | latency=0.990s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 8

  disease_name gene_name
0     leukemia      TP53

 Run 5 completed | rows=8 | latency=1.209s
------------------------------------------------------------


## Question 45

**Which diseases are associated with FGFR2?**

In [153]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 7

     disease_name
0  Gastric cancer

 Run 1 completed | rows=7 | latency=1.301s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 5318

     disease_name gene_name
0  gastric cancer     FGFR2

 Run 2 completed | rows=5318 | latency=166.047s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

     disease_name
0  Gastric cancer

 Run 3 completed | rows=8 | latency=1.090s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

     disease_name
0  Gastric cancer

 Run 4 completed | rows=8 | latency=1.199s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 20

     disease_name gene_name
0  gastric cancer     FGFR2

 Run 5 completed | rows=20 | latency=1.646s
------------------------------------------------------------


## Question 46

**Which diseases are linked to the HTT?**

In [154]:

question = 'Which diseases are linked to the HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 1 completed | rows=1 | latency=1.080s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name
0  Huntington's disease

 Run 2 completed | rows=1 | latency=1.092s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name
0  Huntington's disease

 Run 3 completed | rows=1 | latency=0.771s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name
0  Huntington's disease

 Run 4 completed | rows=1 | latency=1.099s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name
0  Huntington's disease

 Run 5 completed | rows=1 | latency=1.101s
------------------------------------------------------------


## Question 47

**Which genes are associated with breast cancer?**

In [155]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0     BRCA1  breast cancer

 Run 1 completed | rows=10 | latency=0.647s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0     BRCA1  breast cancer

 Run 2 completed | rows=10 | latency=1.323s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0     BRCA1  breast cancer

 Run 3 completed | rows=10 | latency=1.868s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0     BRCA1  breast cancer

 Run 4 completed | rows=10 | latency=1.322s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name   disease_name
0     BRCA1  breast cancer

 Run 5 completed | rows=10 | latency=1.875s
------------------------------------------------------------


## Question 48

**Which genes are associated with colorectal cancer?**

In [156]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 1496

        disease_name gene_name
0  colorectal cancer       APC

 Run 1 completed | rows=1496 | latency=36.891s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5603

  gene_name       disease_name
0       APC  colorectal cancer

 Run 2 completed | rows=5603 | latency=133.867s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 10

  gene_name
0       APC

 Run 3 completed | rows=10 | latency=1.137s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 6161

  gene_name       disease_name
0       APC  colorectal cancer

 Run 4 completed | rows=6161 | latency=170.946s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 20

        disease_name gene_name
0  colorectal cancer       APC

 Run 5 completed | rows=20 | latency=2.159s
------------------------------------------------------------


## Question 49

**What genes are linked to cystic fibrosis?**

In [157]:

question = 'What genes are linked to cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name
0      CFTR

 Run 1 completed | rows=1 | latency=1.083s
------------------------------------------------------------

 Starting run 2 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name
0      CFTR

 Run 2 completed | rows=1 | latency=1.105s
------------------------------------------------------------

 Starting run 3 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      CFTR

 Run 3 completed | rows=1 | latency=1.092s
------------------------------------------------------------

 Starting run 4 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name
0      CFTR

 Run 4 completed | rows=1 | latency=0.989s
------------------------------------------------------------

 Starting run 5 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      CFTR

 Run 5 completed | rows=1 | latency=0.439s
------------------------------------------------------------


## Question 50

**What drugs are used in glioblastoma?**

In [158]:

question = 'What drugs are used in glioblastoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 4

   disease_name     drug_name
0  glioblastoma  temozolomide

 Run 1 completed | rows=4 | latency=1.192s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 5

   disease_name     drug_name
0  glioblastoma  temozolomide

 Run 2 completed | rows=5 | latency=1.314s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 67

   disease_name     drug_name
0  glioblastoma  temozolomide

 Run 3 completed | rows=67 | latency=2.981s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 7

   disease_name     drug_name
0  glioblastoma  Temozolomide

 Run 4 completed | rows=7 | latency=0.979s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 8

   disease_name     drug_name approval_status
0  glioblastoma  temozolomide        Approved

 Run 5 completed | rows=8 | latency=1.210s
------------------------------------------------------------


## Question 51

**Which diseases are treated by metformin?**

In [159]:

question = 'Which diseases are treated by metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 4

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 1 completed | rows=4 | latency=0.760s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 2 completed | rows=1 | latency=0.988s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 4

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 3 completed | rows=4 | latency=1.221s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 4 completed | rows=1 | latency=1.326s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 7

               disease_name  drug_name
0  type 2 diabetes mellitus  metformin

 Run 5 completed | rows=7 | latency=1.202s
------------------------------------------------------------


## Question 52

**What conditions is adalimumab used for?**

In [160]:

question = 'What conditions is adalimumab used for?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name approval_status
0  Rheumatoid arthritis  adalimumab        Approved

 Run 1 completed | rows=8 | latency=1.509s
------------------------------------------------------------

 Starting run 2 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name approval_status
0  Rheumatoid arthritis  adalimumab        Approved

 Run 2 completed | rows=8 | latency=1.324s
------------------------------------------------------------

 Starting run 3 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

           disease_name   drug_name approval_status
0  Rheumatoid Arthritis  adalimumab        Approved

 Run 3 completed | rows=9 | latency=1.540s
------------------------------------------------------------

 Starting run 4 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name approval_status
0  Rheumatoid arthritis  adalimumab        Approved

 Run 4 completed | rows=8 | latency=1.676s
------------------------------------------------------------

 Starting run 5 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name approval_status
0  Rheumatoid Arthritis  adalimumab        Approved

 Run 5 completed | rows=8 | latency=1.422s
------------------------------------------------------------


## Question 53

**Which diseases are pembrolizumab used in?**

In [161]:

question = 'Which diseases are pembrolizumab used in?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 20

  disease_name      drug_name approval_status
0     Melanoma  pembrolizumab        Approved

 Run 1 completed | rows=20 | latency=1.850s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 15

  disease_name      drug_name
0     melanoma  pembrolizumab

 Run 2 completed | rows=15 | latency=1.863s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 17

  disease_name      drug_name
0     melanoma  pembrolizumab

 Run 3 completed | rows=17 | latency=1.984s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 16

  disease_name      drug_name
0     Melanoma  pembrolizumab

 Run 4 completed | rows=16 | latency=1.215s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 13

  disease_name      drug_name
0     melanoma  pembrolizumab

 Run 5 completed | rows=13 | latency=1.630s
------------------------------------------------------------


## Question 54

**Which diseases are treated with sorafenib?**

In [162]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 1 completed | rows=3 | latency=0.960s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 2 completed | rows=3 | latency=1.169s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 3 completed | rows=3 | latency=1.088s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 4 completed | rows=3 | latency=1.100s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 5 completed | rows=3 | latency=1.201s
------------------------------------------------------------


## Question 55

**What diseases are treated with nivolumab?**

In [163]:

question = 'What diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 11

  disease_name  drug_name
0     melanoma  nivolumab

 Run 1 completed | rows=11 | latency=1.644s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 13

  disease_name  drug_name
0     melanoma  nivolumab

 Run 2 completed | rows=13 | latency=1.769s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

  disease_name  drug_name
0     melanoma  nivolumab

 Run 3 completed | rows=8 | latency=1.763s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 10

  disease_name  drug_name
0     melanoma  nivolumab

 Run 4 completed | rows=10 | latency=1.862s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 11

  disease_name  drug_name
0     melanoma  nivolumab

 Run 5 completed | rows=11 | latency=1.542s
------------------------------------------------------------


## Question 56

**Genes linked to multiple sclerosis.**

In [164]:

question = 'Genes linked to multiple sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 9826

  gene_name
0      CD40

 Run 1 completed | rows=9826 | latency=181.859s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 901

  gene_name        disease_name
0  HLA-DRB1  multiple sclerosis

 Run 2 completed | rows=901 | latency=16.239s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 16829

  gene_name
0      CD40

 Run 3 completed | rows=16829 | latency=178.195s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 9

  gene_name
0      CD40

 Run 4 completed | rows=9 | latency=1.415s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 6

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 5 completed | rows=6 | latency=1.308s
------------------------------------------------------------


## Question 57

**Provide target names for rheumatoid arthritis.**

In [165]:

question = 'Provide target names for rheumatoid arthritis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 6

           disease_name target_name
0  Rheumatoid arthritis   TNF-alpha

 Run 1 completed | rows=6 | latency=1.515s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 10

           disease_name target_name
0  Rheumatoid Arthritis         TNF

 Run 2 completed | rows=10 | latency=1.540s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 10

           disease_name                  target_name
0  Rheumatoid arthritis  Tumor necrosis factor alpha

 Run 3 completed | rows=10 | latency=1.222s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 3

           disease_name target_name
0  Rheumatoid Arthritis         TNF

 Run 4 completed | rows=3 | latency=0.983s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 6

           disease_name                  target_name
0  Rheumatoid arthritis  Tumor necrosis factor alpha

 Run 5 completed | rows=6 | latency=1.434s
------------------------------------------------------------


## Question 58

**What are the targets of abatacept?**

In [166]:

question = 'What are the targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name gene_name               mechanism_of_action
0  abatacept        CD80      CD80  inhibits binding of CD80 to CD28

 Run 1 completed | rows=2 | latency=1.317s
------------------------------------------------------------

 Starting run 2 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name gene_name               mechanism_of_action
0  abatacept        CD80      CD80  inhibits binding of CD80 to CD28

 Run 2 completed | rows=2 | latency=1.204s
------------------------------------------------------------

 Starting run 3 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
abatacept,CTLA-4,CTLA4,binds to CD80 and CD86 on antigen-presenting c...,blocking interaction with CD28

 Run 3 completed | rows=1 | latency=1.304s
------------------------------------------------------------

 Starting run 4 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 1

,target_name,gene_name,mechanism_of_action
CD28,CD28,CTLA-4-Ig fusion protein that binds to CD80 an...,blocking their interaction with CD28.

 Run 4 completed | rows=1 | latency=1.532s
------------------------------------------------------------

 Starting run 5 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name gene_name                        mechanism_of_action
0  abatacept        CD80      CD80  Binds to CD80 on antigen-presenting cells

 Run 5 completed | rows=2 | latency=1.313s
------------------------------------------------------------


## Question 59

**Provide target names for lung cancer.**

In [167]:

question = 'Provide target names for lung cancer.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for lung cancer.
  Attempt 1/3
 Attempt 1 failed after 38.944s: Error tokenizing data. C error: Expected 3 fields in line 837, saw 4

  Attempt 2/3
Entries retrieved: 146

  gene_name target_name disease_name
0      EGFR        EGFR  lung cancer

 Run 1 completed | rows=146 | latency=6.726s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 459

  gene_name target_name disease_name
0      EGFR        EGFR  Lung Cancer

 Run 2 completed | rows=459 | latency=15.947s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 12

  disease_name target_name
0  Lung Cancer        EGFR

 Run 3 completed | rows=12 | latency=1.444s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for lung cancer.
  Attempt 1/3
 Attempt 1 failed after 175.899s: Error tokenizing data. C error: Expected 3 fields in line 5719, saw 4

  Attempt 2/3
Entries retrieved: 918

  disease_name target_name
0  Lung Cancer        EGFR

 Run 4 completed | rows=918 | latency=20.456s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 10

  gene_name disease_name target_name
0      EGFR  Lung Cancer        EGFR

 Run 5 completed | rows=10 | latency=1.327s
------------------------------------------------------------


## Question 60

**What are the known targets of ponatinib?**

In [168]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 7

  target_name gene_name        mechanism_of_action
0    BCR-ABL1      ABL1  Tyrosine kinase inhibitor

 Run 1 completed | rows=7 | latency=1.413s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 7

  target_name
0     BCR-ABL

 Run 2 completed | rows=7 | latency=1.105s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 8

  target_name gene_name  drug_name
0     BCR-ABL      ABL1  ponatinib

 Run 3 completed | rows=8 | latency=1.440s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 7

  target_name gene_name
0     BCR-ABL      ABL1

 Run 4 completed | rows=7 | latency=1.321s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 9

   drug_name target_name gene_name        mechanism_of_action
0  Ponatinib     BCR-ABL      ABL1  Tyrosine kinase inhibitor

 Run 5 completed | rows=9 | latency=1.301s
------------------------------------------------------------


## Question 61

**Which drugs are used for systemic lupus erythematosus?**

In [169]:

question = 'Which drugs are used for systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 10

                   disease_name  drug_name
0  systemic lupus erythematosus  belimumab

 Run 1 completed | rows=10 | latency=1.526s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 9

                   disease_name  drug_name
0  systemic lupus erythematosus  belimumab

 Run 2 completed | rows=9 | latency=1.222s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 9

                   disease_name  drug_name
0  systemic lupus erythematosus  belimumab

 Run 3 completed | rows=9 | latency=0.987s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 9

                   disease_name  drug_name
0  systemic lupus erythematosus  belimumab

 Run 4 completed | rows=9 | latency=1.194s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 10

                   disease_name  drug_name
0  systemic lupus erythematosus  belimumab

 Run 5 completed | rows=10 | latency=1.422s
------------------------------------------------------------


## Question 62

**Genes associated with autism spectrum disorder.**

In [170]:

question = 'Genes associated with autism spectrum disorder.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 10

  gene_name              disease_name
0    SHANK3  autism spectrum disorder

 Run 1 completed | rows=10 | latency=1.619s
------------------------------------------------------------

 Starting run 2 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 5

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 2 completed | rows=5 | latency=0.984s
------------------------------------------------------------

 Starting run 3 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 10

  gene_name              disease_name
0    SHANK3  Autism Spectrum Disorder

 Run 3 completed | rows=10 | latency=1.196s
------------------------------------------------------------

 Starting run 4 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 6185

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 4 completed | rows=6185 | latency=169.133s
------------------------------------------------------------

 Starting run 5 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 10

               disease_name gene_name
0  Autism Spectrum Disorder    SHANK3

 Run 5 completed | rows=10 | latency=1.730s
------------------------------------------------------------


## Question 63

**Diseases associated with the gene ROS1.**

In [171]:

question = 'Diseases associated with the gene ROS1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  Lung cancer      ROS1

 Run 1 completed | rows=2 | latency=1.291s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 1681

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 2 completed | rows=1681 | latency=60.191s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 43

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 3 completed | rows=43 | latency=2.409s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 7

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 4 completed | rows=7 | latency=1.302s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 1

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 5 completed | rows=1 | latency=1.313s
------------------------------------------------------------


## Question 64

**Diseases associated with the gene ALK.**

In [172]:

question = 'Diseases associated with the gene ALK.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 10604

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 1 completed | rows=10604 | latency=170.947s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 150

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 2 completed | rows=150 | latency=4.166s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 95

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 3 completed | rows=95 | latency=3.721s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 279

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 4 completed | rows=279 | latency=6.816s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 41

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 5 completed | rows=41 | latency=2.196s
------------------------------------------------------------


## Question 65

**Diseases associated with the gene EGFR.**

In [173]:

question = 'Diseases associated with the gene EGFR.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 7

          disease_name gene_name
0  Lung adenocarcinoma      EGFR

 Run 1 completed | rows=7 | latency=0.900s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 905

          disease_name gene_name
0  Lung adenocarcinoma      EGFR

 Run 2 completed | rows=905 | latency=25.143s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
 Attempt 1 failed after 19.711s: Error tokenizing data. C error: Expected 2 fields in line 105, saw 3

  Attempt 2/3
Entries retrieved: 4

  disease_name gene_name
0  Lung cancer      EGFR

 Run 3 completed | rows=4 | latency=0.984s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0  Lung cancer      EGFR

 Run 4 completed | rows=7 | latency=1.336s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
 Attempt 1 failed after 144.850s: Error tokenizing data. C error: Expected 2 fields in line 353, saw 5

  Attempt 2/3
 Attempt 2 failed after 164.829s: Error tokenizing data. C error: Expected 2 fields in line 133, saw 3

  Attempt 3/3
Entries retrieved: 7

          disease_name gene_name
0  Lung adenocarcinoma      EGFR

 Run 5 completed | rows=7 | latency=1.190s
------------------------------------------------------------


## Question 66

**Provide target names for psoriasis.**

In [174]:

question = 'Provide target names for psoriasis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 4

  disease_name target_name
0    psoriasis       IL-17

 Run 1 completed | rows=4 | latency=1.189s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  disease_name target_name
0    psoriasis      IL-17A

 Run 2 completed | rows=5 | latency=0.875s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 4

  disease_name target_name
0    Psoriasis       IL-17

 Run 3 completed | rows=4 | latency=1.649s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  disease_name target_name
0    psoriasis       IL-17

 Run 4 completed | rows=5 | latency=0.890s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 14

  disease_name target_name
0    psoriasis       IL-17

 Run 5 completed | rows=14 | latency=1.964s
------------------------------------------------------------


## Question 67

**Provide target names for ulcerative colitis.**

In [175]:

question = 'Provide target names for ulcerative colitis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 33

         disease_name target_name
0  Ulcerative colitis   TNF-alpha

 Run 1 completed | rows=33 | latency=2.190s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 6

         disease_name target_name
0  ulcerative colitis         TNF

 Run 2 completed | rows=6 | latency=1.210s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 8

  target_name
0         TNF

 Run 3 completed | rows=8 | latency=1.089s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 243

  target_name
0         TNF

 Run 4 completed | rows=243 | latency=3.666s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 9

         disease_name target_name
0  ulcerative colitis         TNF

 Run 5 completed | rows=9 | latency=0.986s
------------------------------------------------------------


## Question 68

**Provide target names for tuberculosis.**

In [176]:

question = 'Provide target names for tuberculosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 1

                          target_name
0  Mycobacterium tuberculosis complex

 Run 1 completed | rows=1 | latency=0.758s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 7733

              target_name
0  ESX-1 secretion system

 Run 2 completed | rows=7733 | latency=104.413s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 10

   disease_name                            target_name
0  tuberculosis  Mycobacterium tuberculosis DNA gyrase

 Run 3 completed | rows=10 | latency=1.618s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 1 failed after 1.095s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name  disease_name
0     ESX-1  Tuberculosis

 Run 4 completed | rows=1 | latency=1.335s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name]
Index: []

 Attempt 1 failed after 0.979s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

  gene_name  disease_name
0     ESX-1  tuberculosis

 Run 5 completed | rows=1 | latency=0.547s
------------------------------------------------------------


## Question 69

**Provide target names for hepatitis C.**

In [177]:

question = 'Provide target names for hepatitis C.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 1

  gene_name target_name
0      NS5B        NS5B

 Run 1 completed | rows=1 | latency=0.871s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  disease_name      target_name
0  Hepatitis C  NS3/4A protease

 Run 2 completed | rows=3 | latency=1.210s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  disease_name      target_name
0  Hepatitis C  NS3/4A protease

 Run 3 completed | rows=3 | latency=1.104s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  disease_name      target_name
0  Hepatitis C  NS3/4A protease

 Run 4 completed | rows=3 | latency=1.535s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  disease_name      target_name
0  Hepatitis C  NS3/4A protease

 Run 5 completed | rows=3 | latency=1.654s
------------------------------------------------------------


## Question 70

**Provide target names for Hodgkin lymphoma.**

In [178]:

question = 'Provide target names for Hodgkin lymphoma.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 1

  gene_name      disease_name
0      CD30  Hodgkin lymphoma

 Run 1 completed | rows=1 | latency=1.190s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 0

Empty DataFrame
Columns: [gene_name, target_name]
Index: []

 Attempt 1 failed after 1.096s: Returned DataFrame is empty
  Attempt 2/3
Entries retrieved: 1

       disease_name target_name
0  Hodgkin lymphoma        CD30

 Run 2 completed | rows=1 | latency=0.766s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 1

  gene_name target_name      disease_name
0      CD30        CD30  Hodgkin lymphoma

 Run 3 completed | rows=1 | latency=1.328s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 1

  target_name
0        CD30

 Run 4 completed | rows=1 | latency=1.098s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 1

  gene_name      disease_name
0      CD30  Hodgkin lymphoma

 Run 5 completed | rows=1 | latency=0.775s
------------------------------------------------------------


## Question 71

**Which pathways are associated with the TP53?**

In [179]:

question = 'Which pathways are associated with the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 53

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 1 completed | rows=53 | latency=2.946s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TP53?
  Attempt 1/3
 Attempt 1 failed after 101.275s: Error tokenizing data. C error: Expected 2 fields in line 11, saw 3

  Attempt 2/3
Entries retrieved: 9

  pathway_name gene_name
0   cell cycle      TP53

 Run 2 completed | rows=9 | latency=2.313s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 5

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 3 completed | rows=5 | latency=1.098s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TP53?
  Attempt 1/3
 Attempt 1 failed after 163.527s: Error tokenizing data. C error: Expected 2 fields in line 49, saw 3

  Attempt 2/3
Entries retrieved: 8

  pathway_name gene_name
0   Cell cycle      TP53

 Run 4 completed | rows=8 | latency=1.215s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TP53?
  Attempt 1/3
 Attempt 1 failed after 3.095s: Error tokenizing data. C error: Expected 2 fields in line 41, saw 3

  Attempt 2/3
Entries retrieved: 8

,,,pathway_name,gene_name
TP53 regulates cell cycle,apoptosis,DNA repair,and genomic stability,TP53

 Run 5 completed | rows=8 | latency=1.456s
------------------------------------------------------------


## Question 72

**Which drugs are associated with the ERBB2?**

In [180]:

question = 'Which drugs are associated with the ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 15

     drug_name target_name gene_name
0  Trastuzumab       ERBB2     ERBB2

 Run 1 completed | rows=15 | latency=1.410s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 3279

     drug_name target_name gene_name
0  Trastuzumab       ERBB2     ERBB2

 Run 2 completed | rows=3279 | latency=159.655s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name gene_name
0  Trastuzumab       ERBB2     ERBB2

 Run 3 completed | rows=6 | latency=1.408s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 10

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 4 completed | rows=10 | latency=1.425s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 7

     drug_name target_name gene_name
0  Trastuzumab       ERBB2     ERBB2

 Run 5 completed | rows=7 | latency=1.203s
------------------------------------------------------------


## Question 73

**Which pathways are associated with the ADRB1 gene?**

In [181]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 1

                        pathway_name gene_name
0  Beta-adrenergic signaling pathway     ADRB1

 Run 1 completed | rows=1 | latency=1.192s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 1

                                        pathway_name gene_name
0  Beta-adrenergic signaling and cardiac hypertrophy     ADRB1

 Run 2 completed | rows=1 | latency=1.312s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 12

                   pathway_name gene_name
0  adrenergic signaling pathway     ADRB1

 Run 3 completed | rows=12 | latency=0.986s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 1

                        pathway_name gene_name
0  Beta-adrenergic signaling pathway     ADRB1

 Run 4 completed | rows=1 | latency=0.659s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 1

                        pathway_name gene_name
0  Beta-adrenergic signaling pathway     ADRB1

 Run 5 completed | rows=1 | latency=1.098s
------------------------------------------------------------


## Question 74

**Which pathways are associated with the DRD2 gene?**

In [182]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

           pathway_name gene_name
0  Dopaminergic pathway      DRD2

 Run 1 completed | rows=3 | latency=1.300s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 1716

           pathway_name gene_name
0  Dopaminergic pathway      DRD2

 Run 2 completed | rows=1716 | latency=29.319s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 1

           pathway_name gene_name
0  Dopaminergic pathway      DRD2

 Run 3 completed | rows=1 | latency=0.968s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name          pathway_name
0      DRD2  Dopaminergic pathway

 Run 4 completed | rows=1 | latency=1.224s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 11

           pathway_name gene_name
0  Dopaminergic pathway      DRD2

 Run 5 completed | rows=11 | latency=1.597s
------------------------------------------------------------


## Question 75

**Which pathways are associated with the HTR2A gene?**

In [183]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

          pathway_name gene_name
0  serotonergic system     HTR2A

 Run 1 completed | rows=3 | latency=0.850s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

                           pathway_name gene_name
0  serotonin receptor signaling pathway     HTR2A

 Run 2 completed | rows=2 | latency=0.829s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

                           pathway_name gene_name
0  serotonin receptor signaling pathway     HTR2A

 Run 3 completed | rows=4 | latency=0.872s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

           pathway_name gene_name
0  Serotonergic pathway     HTR2A

 Run 4 completed | rows=2 | latency=1.097s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

                           pathway_name gene_name
0  serotonin receptor signaling pathway     HTR2A

 Run 5 completed | rows=4 | latency=1.200s
------------------------------------------------------------


## Question 76

**Which drugs are associated with the CD19 gene?**

In [184]:

question = 'Which drugs are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 11

      drug_name gene_name
0  Tislelizumab      CD19

 Run 1 completed | rows=11 | latency=1.740s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name     drug_name
0      CD19  blinatumomab

 Run 2 completed | rows=6 | latency=1.333s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

          drug_name gene_name
0  Tisagenlecleucel      CD19

 Run 3 completed | rows=5 | latency=1.312s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name     drug_name
0      CD19  blinatumomab

 Run 4 completed | rows=3 | latency=0.890s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

      drug_name gene_name
0  Tislelizumab      CD19

 Run 5 completed | rows=2 | latency=1.411s
------------------------------------------------------------


## Question 77

**Which drugs are associated with the CTLA4 gene?**

In [185]:

question = 'Which drugs are associated with the CTLA4 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name   drug_name
0     CTLA4  Ipilimumab

 Run 1 completed | rows=1 | latency=0.647s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 1

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 2 completed | rows=1 | latency=1.110s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 1

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 3 completed | rows=1 | latency=0.872s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 1

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 4 completed | rows=1 | latency=0.656s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 5 completed | rows=2 | latency=1.198s
------------------------------------------------------------


## Question 78

**Which drugs are associated with the BTK gene?**

In [186]:

question = 'Which drugs are associated with the BTK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 7

   drug_name gene_name
0  ibrutinib       BTK

 Run 1 completed | rows=7 | latency=1.197s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Ibrutinib       BTK

 Run 2 completed | rows=6 | latency=1.202s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Ibrutinib       BTK

 Run 3 completed | rows=6 | latency=1.325s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  Ibrutinib       BTK

 Run 4 completed | rows=10 | latency=1.322s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 9

   drug_name gene_name
0  Ibrutinib       BTK

 Run 5 completed | rows=9 | latency=1.424s
------------------------------------------------------------


## Question 79

**Which drugs are associated with the SYK gene?**

In [187]:

question = 'Which drugs are associated with the SYK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 10

  gene_name     drug_name
0       SYK  Fostamatinib

 Run 1 completed | rows=10 | latency=1.743s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 9

      drug_name gene_name
0  Fostamatinib       SYK

 Run 2 completed | rows=9 | latency=1.209s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name
0  Fostamatinib       SYK

 Run 3 completed | rows=7 | latency=1.544s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 12

      drug_name gene_name
0  Fostamatinib       SYK

 Run 4 completed | rows=12 | latency=1.644s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 328

      drug_name gene_name
0  Fostamatinib       SYK

 Run 5 completed | rows=328 | latency=6.403s
------------------------------------------------------------


## Question 80

**Which pathways are associated with TP53?**

In [188]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_gemini_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 6099

                               pathway_name gene_name
0  Cellular response to DNA damage stimulus      TP53

 Run 1 completed | rows=6099 | latency=131.477s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  pathway_name gene_name
0   cell cycle      TP53

 Run 2 completed | rows=3 | latency=1.098s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 20

  gene_name pathway_name
0      TP53   Cell cycle

 Run 3 completed | rows=20 | latency=1.756s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

  pathway_name gene_name
0   Cell cycle      TP53

 Run 4 completed | rows=5 | latency=1.220s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

                               pathway_name gene_name
0  Cellular response to DNA damage stimulus      TP53

 Run 5 completed | rows=5 | latency=1.223s
------------------------------------------------------------

##### Save as .pkl and json

In [ ]:
# import pickle
# with open("Gemini_same_question_response.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

# import json
# import pandas as pd

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("Gemini_same_question_response.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )