In [108]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from openai_utility import return_openai_answer

In [109]:



model = "gpt-5-nano"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [110]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     melanoma      braf

 Run 1 completed | rows=9 | latency=21.946s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     melanoma      braf

 Run 2 completed | rows=9 | latency=16.201s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     melanoma      braf

 Run 3 completed | rows=9 | latency=19.563s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     melanoma      braf

 Run 4 completed | rows=9 | latency=26.661s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     melanoma      braf

 Run 5 completed | rows=9 | latency=22.100s
------------------------------------------------------------


## Question 2

**List genes linked to amyotrophic lateral sclerosis.**

In [111]:

question = 'List genes linked to amyotrophic lateral sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 18

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 1 completed | rows=18 | latency=25.740s
------------------------------------------------------------

 Starting run 2 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 24

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 2 completed | rows=24 | latency=27.450s
------------------------------------------------------------

 Starting run 3 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 20

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 3 completed | rows=20 | latency=40.597s
------------------------------------------------------------

 Starting run 4 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 24

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 4 completed | rows=24 | latency=29.074s
------------------------------------------------------------

 Starting run 5 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 18

                    disease_name gene_name
0  amyotrophic lateral sclerosis      sod1

 Run 5 completed | rows=18 | latency=31.870s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [112]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0     melanoma      cdk4

 Run 1 completed | rows=4 | latency=21.202s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

   disease_name gene_name
0  glioblastoma      cdk4

 Run 2 completed | rows=3 | latency=22.474s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

   disease_name gene_name
0  glioblastoma      cdk4

 Run 3 completed | rows=4 | latency=23.225s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     melanoma      cdk4

 Run 4 completed | rows=3 | latency=16.643s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0  liposarcoma      cdk4

 Run 5 completed | rows=2 | latency=14.225s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [113]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      jak2  jak-stat signaling pathway

 Run 1 completed | rows=1 | latency=13.529s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  jak-stat signaling pathway      jak2

 Run 2 completed | rows=1 | latency=13.860s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  jak-stat signaling pathway      jak2

 Run 3 completed | rows=1 | latency=12.908s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0      jak2  jak-stat signaling pathway

 Run 4 completed | rows=2 | latency=12.689s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0      jak2  jak-stat signaling pathway

 Run 5 completed | rows=2 | latency=15.414s
------------------------------------------------------------


## Question 5

**Which drugs are used for treating rheumatoid arthritis?**

In [114]:

question = 'Which drugs are used for treating rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 16

           disease_name     drug_name
0  rheumatoid arthritis  methotrexate

 Run 1 completed | rows=16 | latency=22.718s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  rheumatoid arthritis  methotrexate

 Run 2 completed | rows=17 | latency=37.485s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 16

           disease_name     drug_name approval_status
0  rheumatoid arthritis  methotrexate        approved

 Run 3 completed | rows=16 | latency=21.540s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  rheumatoid arthritis  methotrexate

 Run 4 completed | rows=17 | latency=30.734s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  rheumatoid arthritis  methotrexate

 Run 5 completed | rows=17 | latency=34.177s
------------------------------------------------------------


## Question 6

**What are the targets and mechanisms for dulaglutide?**

In [115]:

question = 'What are the targets and mechanisms for dulaglutide?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,dulaglutide,glucagon-like peptide-1 receptor,glp1r,glp-1 receptor agonist; increases glucose-depe...,approved

 Run 1 completed | rows=1 | latency=14.951s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,dulaglutide,glp-1 receptor,glp1r,glp-1 receptor agonist; stimulates glucose-dep...,approved

 Run 2 completed | rows=1 | latency=17.681s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,dulaglutide,glucagon-like peptide-1 receptor,glp1r,glp-1 receptor agonist; increases glucose-depe...

 Run 3 completed | rows=1 | latency=19.430s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,dulaglutide,glp-1 receptor,glp1r,glp-1 receptor agonism; increases glucose-depe...

 Run 4 completed | rows=1 | latency=20.536s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,dulaglutide,glp-1 receptor,glp1r,glp-1 receptor agonist; increases glucose-depe...

 Run 5 completed | rows=1 | latency=20.063s
------------------------------------------------------------


## Question 7

**Provide target names for ovarian cancer?**

In [116]:

question = 'Provide target names for ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 7

,disease_name,target_name,gene_name,mechanism_of_action,approval_status
0,ovarian cancer,vegfa,vegfa,neutralizes vegf-a to inhibit vegf-vegfr signa...,approved

 Run 1 completed | rows=7 | latency=50.744s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name    disease_name
0      vegf-a  ovarian cancer

 Run 2 completed | rows=4 | latency=38.010s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 8

     disease_name target_name gene_name
0  ovarian cancer        egfr      egfr

 Run 3 completed | rows=8 | latency=24.406s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 9

  target_name    disease_name
0       parp1  ovarian cancer

 Run 4 completed | rows=9 | latency=24.811s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 2

  target_name gene_name    disease_name
0       parp1     parp1  ovarian cancer

 Run 5 completed | rows=2 | latency=22.387s
------------------------------------------------------------


## Question 8

**What are the known targets of regorafenib?**

In [117]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 12

,drug_name,target_name,gene_name,mechanism_of_action
0,regorafenib,vascular endothelial growth factor receptor 2,kdr,inhibits tyrosine kinase activity

 Run 1 completed | rows=12 | latency=42.959s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,regorafenib,vegfr-2,kdr,inhibits vegfr-2 kinase activity,approved

 Run 2 completed | rows=8 | latency=36.593s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

,drug_name,target_name,gene_name,mechanism_of_action
0,regorafenib,vegfr-2,kdr,multikinase inhibitor; inhibits vegfr-2 signaling

 Run 3 completed | rows=11 | latency=40.806s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name gene_name               mechanism_of_action
0  regorafenib     vegfr-2       kdr  inhibits vegfr-2 tyrosine kinase

 Run 4 completed | rows=11 | latency=50.205s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name gene_name                 mechanism_of_action
0  regorafenib     vegfr-2       kdr  vegfr-2 tyrosine kinase inhibition

 Run 5 completed | rows=11 | latency=47.904s
------------------------------------------------------------


## Question 9

**Which pathways are associated with the STAT3 gene?**

In [118]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 1 completed | rows=3 | latency=19.993s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

                 pathway_name gene_name
0  jak-stat signaling pathway     stat3

 Run 2 completed | rows=2 | latency=12.831s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 3

                 pathway_name gene_name
0  jak-stat signaling pathway     stat3

 Run 3 completed | rows=3 | latency=19.891s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 4 completed | rows=2 | latency=16.281s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     stat3  jak-stat signaling pathway

 Run 5 completed | rows=1 | latency=10.954s
------------------------------------------------------------


## Question 10

**Genes linked to fever.**

In [119]:

question = 'Genes linked to fever.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 5

                   disease_name gene_name
0  familial mediterranean fever      mefv

 Run 1 completed | rows=5 | latency=19.663s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0        fever      il1b

 Run 2 completed | rows=7 | latency=15.520s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 5

                   disease_name gene_name
0  familial mediterranean fever      mefv

 Run 3 completed | rows=5 | latency=19.002s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 8

                   disease_name gene_name
0  familial mediterranean fever      mefv

 Run 4 completed | rows=8 | latency=23.659s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 7

                   disease_name gene_name
0  familial mediterranean fever      mefv

 Run 5 completed | rows=7 | latency=36.906s
------------------------------------------------------------


## Question 11

**List all drugs that target EGFR?**

In [120]:

question = 'List all drugs that target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,egfr,egfr,egfr tyrosine kinase inhibitor,approved

 Run 1 completed | rows=8 | latency=29.182s
------------------------------------------------------------

 Starting run 2 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 12

,drug_name,target_name,gene_name,mechanism_of_action
0,gefitinib,egfr,egfr,reversible egfr (erbb1) tyrosine kinase inhibi...

 Run 2 completed | rows=12 | latency=52.752s
------------------------------------------------------------

 Starting run 3 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 10

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,egfr,egfr,egfr tyrosine kinase inhibitor,approved

 Run 3 completed | rows=10 | latency=39.274s
------------------------------------------------------------

 Starting run 4 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 10

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,egfr,egfr,egfr tyrosine kinase inhibitor,approved

 Run 4 completed | rows=10 | latency=46.643s
------------------------------------------------------------

 Starting run 5 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action
0,cetuximab,egfr,egfr,monoclonal antibody against egfr; inhibits lig...

 Run 5 completed | rows=9 | latency=39.769s
------------------------------------------------------------


## Question 12

**Show drugs that inhibit the FGFR2 gene?**

In [121]:

question = 'Show drugs that inhibit the FGFR2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,erdafitinib,fgfr2,fgfr2,pan-fgfr tyrosine kinase inhibitor,approved

 Run 1 completed | rows=5 | latency=38.779s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,erdafitinib,fgfr2,fgfr2,fgfr2 tyrosine kinase inhibition,approved

 Run 2 completed | rows=7 | latency=49.632s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,gene_name,target_name,mechanism_of_action
0,erdafitinib,fgfr2,fgfr2,pan-fgfr tyrosine kinase inhibitor (fgfr1-4)

 Run 3 completed | rows=4 | latency=32.516s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 2

     drug_name target_name gene_name                 mechanism_of_action
0  erdafitinib       fgfr2     fgfr2  pan-fgfr tyrosine kinase inhibitor

 Run 4 completed | rows=2 | latency=24.897s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,erdafitinib,fgfr2,fgfr2,fgfr1-4 tyrosine kinase inhibition,approved

 Run 5 completed | rows=5 | latency=41.426s
------------------------------------------------------------


## Question 13

**What diseases are treated with bevacizumab?**

In [122]:

question = 'What diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

                   disease_name     drug_name approval_status
0  metastatic colorectal cancer  bevaczizumab        approved

 Run 1 completed | rows=6 | latency=20.136s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 8

        disease_name    drug_name
0  colorectal cancer  bevacizumab

 Run 2 completed | rows=8 | latency=21.386s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 3 completed | rows=6 | latency=18.187s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

        disease_name    drug_name
0  colorectal cancer  bevacizumab

 Run 4 completed | rows=6 | latency=23.481s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

                   disease_name    drug_name
0  metastatic colorectal cancer  bevacizumab

 Run 5 completed | rows=6 | latency=30.796s
------------------------------------------------------------


## Question 14

**List treatments for plaque psoriasis and their mechanisms.**

In [123]:

question = 'List treatments for plaque psoriasis and their mechanisms.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 18

,drug_name,disease_name,target_name,gene_name,mechanism_of_action,approval_status
0,hydrocortisone,plaque psoriasis,nr3c1,nr3c1,binds glucocorticoid receptor; suppresses infl...,approved

 Run 1 completed | rows=18 | latency=65.199s
------------------------------------------------------------

 Starting run 2 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
 Attempt 1 failed after 41.135s: Error tokenizing data. C error: Expected 4 fields in line 9, saw 5

  Attempt 2/3
Entries retrieved: 18

,drug_name,disease_name,target_name,gene_name,mechanism_of_action,approval_status
0,clobetasol propionate,plaque psoriasis,glucocorticoid receptor,nr3c1,glucocorticoid receptor agonism; suppresses in...,approved

 Run 2 completed | rows=18 | latency=49.070s
------------------------------------------------------------

 Starting run 3 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 17

,drug_name,disease_name,target_name,gene_name,biomarker_name,pathway_name,approval_status,mechanism_of_action
0,calcipotriol,plaque psoriasis,vitamin d receptor,vdr,vdr,vitamin d receptor signaling,approved,vitamin d receptor agonist; modulates keratino...

 Run 3 completed | rows=17 | latency=138.462s
------------------------------------------------------------

 Starting run 4 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
 Attempt 1 failed after 29.414s: Error tokenizing data. C error: Expected 4 fields in line 12, saw 5

  Attempt 2/3
 Attempt 2 failed after 87.132s: Error tokenizing data. C error: Expected 8 fields in line 11, saw 9

  Attempt 3/3
Entries retrieved: 12

,drug_name,disease_name,target_name,gene_name,mechanism_of_action,approval_status
0,etanercept,plaque psoriasis,tnf,tnf,fusion protein acting as a decoy receptor for ...,approved

 Run 4 completed | rows=12 | latency=59.648s
------------------------------------------------------------

 Starting run 5 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 15

,drug_name,disease_name,mechanism_of_action,target_name,gene_name,approval_status
0,methotrexate,plaque psoriasis,dihydrofolate reductase inhibition,dhfr,dhfr,approved

 Run 5 completed | rows=15 | latency=50.447s
------------------------------------------------------------


## Question 15

**What are the known targets of cabozantinib?**

In [124]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name target_name gene_name         mechanism_of_action
0  cabozantinib         met       met  tyrosine kinase inhibition

 Run 1 completed | rows=5 | latency=19.717s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action
0,cabozantinib,met proto-oncogene receptor tyrosine kinase,met,inhibits tyrosine kinase activity

 Run 2 completed | rows=5 | latency=22.239s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name target_name gene_name                      mechanism_of_action
0  cabozantinib         met       met  tyrosine kinase inhibitor targeting met

 Run 3 completed | rows=5 | latency=20.384s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name target_name gene_name                    mechanism_of_action
0  cabozantinib         met       met  inhibits met tyrosine kinase activity

 Run 4 completed | rows=5 | latency=22.657s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action
0,cabozantinib,met proto-oncogene receptor tyrosine kinase,met,inhibits met tyrosine kinase activity

 Run 5 completed | rows=5 | latency=25.467s
------------------------------------------------------------


## Question 16

**Show drugs that inhibit the RET gene?**

In [125]:

question = 'Show drugs that inhibit the RET gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,selpercatinib,ret proto-oncogene,ret,selective ret tyrosine kinase inhibitor

 Run 1 completed | rows=4 | latency=20.451s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,vandetanib,ret,ret,ret tyrosine kinase inhibition,approved

 Run 2 completed | rows=4 | latency=18.224s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,selpercatinib,ret tyrosine kinase,ret,selective ret tyrosine kinase inhibition,approved

 Run 3 completed | rows=4 | latency=25.409s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,selpercatinib,ret,ret,selective ret tyrosine kinase inhibition,approved

 Run 4 completed | rows=4 | latency=18.968s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,selpercatinib,ret tyrosine kinase,ret,selective ret kinase inhibitor,approved

 Run 5 completed | rows=4 | latency=18.216s
------------------------------------------------------------


## Question 17

**Which pathways are associated with the TNF gene?**

In [126]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 1 completed | rows=5 | latency=17.393s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 2 completed | rows=6 | latency=17.233s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  tnf signaling pathway       tnf

 Run 3 completed | rows=4 | latency=15.057s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 4 completed | rows=4 | latency=23.233s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name           pathway_name
0       tnf  tnf signaling pathway

 Run 5 completed | rows=5 | latency=20.988s
------------------------------------------------------------


## Question 18

**Diseases associated with the gene NPM1.**

In [127]:

question = 'Diseases associated with the gene NPM1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  acute myeloid leukemia with mutated npm1      npm1

 Run 1 completed | rows=1 | latency=12.887s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  acute myeloid leukemia      npm1

 Run 2 completed | rows=1 | latency=11.138s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  acute myeloid leukemia      npm1

 Run 3 completed | rows=1 | latency=12.123s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  acute myeloid leukemia with mutated npm1      npm1

 Run 4 completed | rows=1 | latency=13.911s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  acute myeloid leukemia      npm1

 Run 5 completed | rows=1 | latency=14.581s
------------------------------------------------------------


## Question 19

**Which pathways are associated with the CD19 gene?**

In [128]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 1 completed | rows=2 | latency=14.240s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

,gene_name,pathway_name,mechanism_of_action
0,cd19,b cell receptor signaling pathway,cd19 acts as a b cell co-receptor that amplifi...

 Run 2 completed | rows=2 | latency=15.081s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      cd19  b cell receptor signaling pathway

 Run 3 completed | rows=2 | latency=14.068s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  b cell receptor signaling pathway      cd19

 Run 4 completed | rows=2 | latency=12.451s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

                        pathway_name gene_name
0  b cell receptor signaling pathway      cd19

 Run 5 completed | rows=3 | latency=14.954s
------------------------------------------------------------


## Question 20

**Which drugs are used for treating migraine?**

In [129]:

question = 'Which drugs are used for treating migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 21

  disease_name    drug_name
0     migraine  sumatriptan

 Run 1 completed | rows=21 | latency=34.297s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 13

  disease_name    drug_name
0     migraine  sumatriptan

 Run 2 completed | rows=13 | latency=25.828s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 24

  disease_name    drug_name
0     migraine  sumatriptan

 Run 3 completed | rows=24 | latency=29.536s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 18

     drug_name disease_name approval_status         mechanism_of_action
0  sumatriptan     migraine        approved  5-ht1b/1d receptor agonist

 Run 4 completed | rows=18 | latency=48.240s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 10

  disease_name    drug_name
0     migraine  sumatriptan

 Run 5 completed | rows=10 | latency=14.200s
------------------------------------------------------------


## Question 21

**What are the targets and mechanisms for rituximab?**

In [130]:

question = 'What are the targets and mechanisms for rituximab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,cd20,ms4a1,cd20 binding; mediates b-cell depletion via an...

 Run 1 completed | rows=1 | latency=10.761s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,cd20,ms4a1,cd20 binding on b cells; mediates b-cell deple...

 Run 2 completed | rows=1 | latency=12.720s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,cd20,ms4a1,complement-dependent cytotoxicity; antibody-de...

 Run 3 completed | rows=1 | latency=11.937s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,cd20,ms4a1,"b-cell depletion via anti-cd20 binding, activa..."

 Run 4 completed | rows=1 | latency=9.241s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,rituximab,cd20,ms4a1,cd20-directed monoclonal antibody; mediates b-...,approved

 Run 5 completed | rows=1 | latency=15.494s
------------------------------------------------------------


## Question 22

**Provide target names for colorectal cancer?**

In [131]:

question = 'Provide target names for colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 9

        disease_name target_name
0  colorectal cancer        egfr

 Run 1 completed | rows=9 | latency=24.245s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name target_name
0  colorectal cancer        egfr

 Run 2 completed | rows=5 | latency=22.307s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 9

,disease_name,target_name,gene_name,approval_status,mechanism_of_action
0,colorectal cancer,egfr,egfr,approved,egfr signaling inhibition

 Run 3 completed | rows=9 | latency=50.205s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 11

        disease_name target_name
0  colorectal cancer        egfr

 Run 4 completed | rows=11 | latency=24.442s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 10

        disease_name target_name
0  colorectal cancer        egfr

 Run 5 completed | rows=10 | latency=22.842s
------------------------------------------------------------


## Question 23

**Which are possible drugs against rickets?**

In [132]:

question = 'Which are possible drugs against rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 6

,drug_name,disease_name,mechanism_of_action,approval_status
0,cholecalciferol,rickets,vitamin d3; increases intestinal absorption of...,approved

 Run 1 completed | rows=6 | latency=36.520s
------------------------------------------------------------

 Starting run 2 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 6

         drug_name disease_name
0  cholecalciferol      rickets

 Run 2 completed | rows=6 | latency=21.093s
------------------------------------------------------------

 Starting run 3 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 6

,drug_name,disease_name,mechanism_of_action,approval_status
0,cholecalciferol,rickets,vitamin d3 increases intestinal absorption of ...,approved

 Run 3 completed | rows=6 | latency=24.796s
------------------------------------------------------------

 Starting run 4 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

,drug_name,disease_name,mechanism_of_action,approval_status
0,cholecalciferol,rickets,vitamin d receptor agonist; increases intestin...,approved

 Run 4 completed | rows=4 | latency=17.118s
------------------------------------------------------------

 Starting run 5 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

,drug_name,disease_name,approval_status,mechanism_of_action
0,cholecalciferol,rickets,approved,vitamin d receptor activation; increases intes...

 Run 5 completed | rows=4 | latency=19.058s
------------------------------------------------------------


## Question 24

**Give me genes linked to epilepsy.**

In [133]:

question = 'Give me genes linked to epilepsy.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 21

  disease_name gene_name
0     epilepsy     scn1a

 Run 1 completed | rows=21 | latency=16.526s
------------------------------------------------------------

 Starting run 2 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 27

  disease_name gene_name
0     epilepsy     scn1a

 Run 2 completed | rows=27 | latency=28.203s
------------------------------------------------------------

 Starting run 3 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 25

  disease_name gene_name
0     epilepsy     scn1a

 Run 3 completed | rows=25 | latency=18.865s
------------------------------------------------------------

 Starting run 4 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 29

  disease_name gene_name
0     epilepsy     scn1a

 Run 4 completed | rows=29 | latency=27.697s
------------------------------------------------------------

 Starting run 5 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 38

  disease_name gene_name
0     epilepsy     scn1a

 Run 5 completed | rows=38 | latency=35.632s
------------------------------------------------------------


## Question 25

**What diseases are treated with trastuzumab deruxtecan?**

In [134]:

question = 'What diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name approval_status
0  trastuzumab deruxtecan  breast cancer        approved

 Run 1 completed | rows=2 | latency=21.477s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                            disease_name
0  trastuzumab deruxtecan  her2-positive metastatic breast cancer

 Run 2 completed | rows=2 | latency=11.421s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                                        disease_name               drug_name
0  unresectable or metastatic her2-positive breas...  trastuzumab deruxtecan

 Run 3 completed | rows=2 | latency=18.822s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                  disease_name               drug_name
0  her2-positive breast cancer  trastuzumab deruxtecan

 Run 4 completed | rows=2 | latency=18.474s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

,drug_name,disease_name,approval_status,mechanism_of_action
0,trastuzumab deruxtecan,her2-positive breast cancer,approved,antibody-drug conjugate targeting her2; deruxt...

 Run 5 completed | rows=3 | latency=26.221s
------------------------------------------------------------


## Question 26

**Genes linked to Alzheimer’s disease.**

In [135]:

question = 'Genes linked to Alzheimer’s disease.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 13

          disease_name gene_name
0  alzheimer's disease       app

 Run 1 completed | rows=13 | latency=17.489s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 6

          disease_name gene_name
0  alzheimer's disease       app

 Run 2 completed | rows=6 | latency=12.021s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 11

          disease_name gene_name
0  alzheimer's disease       app

 Run 3 completed | rows=11 | latency=13.526s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 12

          disease_name gene_name
0  alzheimer's disease       app

 Run 4 completed | rows=12 | latency=14.242s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 17

          disease_name gene_name
0  alzheimer's disease       app

 Run 5 completed | rows=17 | latency=22.662s
------------------------------------------------------------


## Question 27

**For which disease is darolutamide used?**

In [136]:

question = 'For which disease is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

                                        disease_name     drug_name
0  nonmetastatic castration-resistant prostate ca...  darolutamide

 Run 1 completed | rows=1 | latency=7.310s
------------------------------------------------------------

 Starting run 2 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

                                        disease_name     drug_name
0  non-metastatic castration-resistant prostate c...  darolutamide

 Run 2 completed | rows=1 | latency=10.132s
------------------------------------------------------------

 Starting run 3 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

                                        disease_name     drug_name
0  non-metastatic castration-resistant prostate c...  darolutamide

 Run 3 completed | rows=1 | latency=12.126s
------------------------------------------------------------

 Starting run 4 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  non-metastatic castration-resistant prostate c...

 Run 4 completed | rows=1 | latency=7.274s
------------------------------------------------------------

 Starting run 5 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

,disease_name,drug_name,approval_status
0,nonmetastatic castration-resistant prostate ca...,darolutamide,approved

 Run 5 completed | rows=1 | latency=10.784s
------------------------------------------------------------


## Question 28

**Provide target names for renal cell carcinoma?**

In [137]:

question = 'Provide target names for renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 9

       target_name gene_name          disease_name
0  vegf receptor 2       kdr  renal cell carcinoma

 Run 1 completed | rows=9 | latency=30.126s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 2

           disease_name target_name
0  renal cell carcinoma       vegfa

 Run 2 completed | rows=2 | latency=25.570s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 16

           disease_name target_name
0  renal cell carcinoma         kdr

 Run 3 completed | rows=16 | latency=22.337s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

  target_name gene_name
0       vegfa     vegfa

 Run 4 completed | rows=8 | latency=20.929s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 10

           disease_name target_name gene_name
0  renal cell carcinoma      vegfr2       kdr

 Run 5 completed | rows=10 | latency=27.223s
------------------------------------------------------------


## Question 29

**Diseases associated with the gene KRAS.**

In [138]:

question = 'Diseases associated with the gene KRAS.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 1 completed | rows=5 | latency=17.923s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 6

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 2 completed | rows=6 | latency=20.071s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 3 completed | rows=3 | latency=17.525s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 4 completed | rows=3 | latency=10.995s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 4

                       disease_name gene_name
0  pancreatic ductal adenocarcinoma      kras

 Run 5 completed | rows=4 | latency=15.099s
------------------------------------------------------------


## Question 30

**Which pathways are associated with the APP gene?**

In [139]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

                  pathway_name gene_name
0  alzheimer's disease pathway       app

 Run 1 completed | rows=1 | latency=17.695s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

                  pathway_name gene_name
0  alzheimer's disease pathway       app

 Run 2 completed | rows=1 | latency=19.774s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 3

                  pathway_name gene_name
0  alzheimer's disease pathway       app

 Run 3 completed | rows=3 | latency=21.256s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

          pathway_name gene_name
0  alzheimer's disease       app

 Run 4 completed | rows=1 | latency=18.080s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                          pathway_name
0       app  amyloid precursor protein processing

 Run 5 completed | rows=1 | latency=19.528s
------------------------------------------------------------


## Question 31

**Genes linked to schizophrenia.**

In [140]:

question = 'Genes linked to schizophrenia.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 8

    disease_name gene_name
0  schizophrenia      drd2

 Run 1 completed | rows=8 | latency=17.571s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 11

    disease_name gene_name
0  schizophrenia      drd2

 Run 2 completed | rows=11 | latency=18.038s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 15

    disease_name gene_name
0  schizophrenia      drd2

 Run 3 completed | rows=15 | latency=18.979s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 13

    disease_name gene_name
0  schizophrenia     disc1

 Run 4 completed | rows=13 | latency=20.570s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 12

    disease_name gene_name
0  schizophrenia      drd2

 Run 5 completed | rows=12 | latency=15.772s
------------------------------------------------------------


## Question 32

**What diseases are treated with valdecoxib?**

In [141]:

question = 'What diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

     disease_name   drug_name
0  osteoarthritis  valdecoxib

 Run 1 completed | rows=2 | latency=15.242s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 3

    drug_name    disease_name approval_status
0  valdecoxib  osteoarthritis       withdrawn

 Run 2 completed | rows=3 | latency=16.879s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 3

     disease_name   drug_name
0  osteoarthritis  valdecoxib

 Run 3 completed | rows=3 | latency=19.188s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 1

         disease_name   drug_name approval_status        mechanism_of_action
0  postoperative pain  valdecoxib       withdrawn  cox-2 selective inhibitor

 Run 4 completed | rows=1 | latency=27.758s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name approval_status
0  valdecoxib  osteoarthritis       withdrawn

 Run 5 completed | rows=2 | latency=17.596s
------------------------------------------------------------


## Question 33

**What are the known targets of vandetanib?**

In [142]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name gene_name                        mechanism_of_action
0  vandetanib     vegfr-2       kdr  inhibits vegfr-2 tyrosine kinase activity

 Run 1 completed | rows=4 | latency=21.813s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name gene_name                        mechanism_of_action
0  vandetanib     vegfr-2       kdr  inhibits vegfr-2 tyrosine kinase activity

 Run 2 completed | rows=3 | latency=23.858s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,vandetanib,vegfr-2,kdr,tyrosine kinase inhibition of vegfr-2 (kdr/veg...

 Run 3 completed | rows=4 | latency=37.461s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name gene_name                     mechanism_of_action
0  vandetanib        egfr      egfr  inhibits egfr tyrosine kinase activity

 Run 4 completed | rows=3 | latency=34.035s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name      target_name gene_name                   mechanism_of_action
0  vandetanib  vegf receptor 2       kdr  tyrosine kinase inhibitor of vegfr-2

 Run 5 completed | rows=3 | latency=30.782s
------------------------------------------------------------


## Question 34

**Which pathways are associated with the CFTR gene?**

In [143]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

             pathway_name gene_name
0  camp signaling pathway      cftr

 Run 1 completed | rows=1 | latency=25.222s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

             pathway_name gene_name
0  camp signaling pathway      cftr

 Run 2 completed | rows=1 | latency=16.467s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name            pathway_name
0      cftr  camp signaling pathway

 Run 3 completed | rows=2 | latency=26.655s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

,pathway_name,gene_name,mechanism_of_action
0,camp signaling pathway,cftr,pka-mediated phosphorylation activates cftr in...

 Run 4 completed | rows=1 | latency=20.072s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 4

             pathway_name
0  camp signaling pathway

 Run 5 completed | rows=4 | latency=19.571s
------------------------------------------------------------


## Question 35

**Which drugs are used for TB?**

In [144]:

question = 'Which drugs are used for TB?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 15

   disease_name  drug_name
0  tuberculosis  isoniazid

 Run 1 completed | rows=15 | latency=32.728s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 5

   disease_name  drug_name
0  tuberculosis  isoniazid

 Run 2 completed | rows=5 | latency=14.773s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 18

   disease_name  drug_name
0  tuberculosis  isoniazid

 Run 3 completed | rows=18 | latency=28.114s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 8

   disease_name  drug_name
0  tuberculosis  isoniazid

 Run 4 completed | rows=8 | latency=22.758s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 11

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 5 completed | rows=11 | latency=27.272s
------------------------------------------------------------


## Question 36

**Which drugs are used for pancreatic adenocarcinoma?**

In [145]:

question = 'Which drugs are used for pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 9

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 1 completed | rows=9 | latency=67.104s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

                disease_name    drug_name
0  pancreatic adenocarcinoma  gemcitabine

 Run 2 completed | rows=6 | latency=46.074s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 8

                disease_name    drug_name
0  pancreatic adenocarcinoma  gemcitabine

 Run 3 completed | rows=8 | latency=70.876s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 9

                disease_name    drug_name
0  pancreatic adenocarcinoma  gemcitabine

 Run 4 completed | rows=9 | latency=50.861s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 9

                disease_name    drug_name
0  pancreatic adenocarcinoma  gemcitabine

 Run 5 completed | rows=9 | latency=64.615s
------------------------------------------------------------


## Question 37

**Which drugs are used in chronic myeloid leukemia?**

In [146]:

question = 'Which drugs are used in chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 8

               disease_name drug_name
0  chronic myeloid leukemia  imatinib

 Run 1 completed | rows=8 | latency=27.763s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name
0  chronic myeloid leukemia  imatinib

 Run 2 completed | rows=6 | latency=20.004s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

  drug_name              disease_name
0  imatinib  chronic myeloid leukemia

 Run 3 completed | rows=6 | latency=16.626s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 7

               disease_name drug_name
0  chronic myeloid leukemia  imatinib

 Run 4 completed | rows=7 | latency=22.916s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name
0  chronic myeloid leukemia  imatinib

 Run 5 completed | rows=6 | latency=17.058s
------------------------------------------------------------


## Question 38

**What drugs are used in the treatment of Parkinson’s disease?**

In [147]:

question = 'What drugs are used in the treatment of Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 17

        disease_name drug_name
0  parkinson disease  levodopa

 Run 1 completed | rows=17 | latency=30.748s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 16

,disease_name,drug_name,approval_status,mechanism_of_action
0,parkinson's disease,levodopa/carbidopa,approved,combination therapy; dopamine precursor with p...

 Run 2 completed | rows=16 | latency=49.950s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 14

          disease_name drug_name
0  parkinson's disease  levodopa

 Run 3 completed | rows=14 | latency=36.673s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 17

          disease_name drug_name
0  parkinson's disease  levodopa

 Run 4 completed | rows=17 | latency=25.521s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 17

          disease_name drug_name
0  parkinson's disease  levodopa

 Run 5 completed | rows=17 | latency=35.945s
------------------------------------------------------------


## Question 39

**Which drugs are used for inflammatory bowel disease?**

In [148]:

question = 'Which drugs are used for inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 14

,drug_name,disease_name,approval_status,mechanism_of_action
0,sulfasalazine,inflammatory bowel disease,approved,5-aminosalicylic acid prodrug; anti-inflammato...

 Run 1 completed | rows=14 | latency=38.955s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 18

                 disease_name      drug_name
0  inflammatory bowel disease  sulfasalazine

 Run 2 completed | rows=18 | latency=35.261s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 25

    drug_name        disease_name
0  mesalamine  ulcerative colitis

 Run 3 completed | rows=25 | latency=45.963s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 19

                 disease_name      drug_name
0  inflammatory bowel disease  sulfasalazine

 Run 4 completed | rows=19 | latency=29.333s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 25

         disease_name   drug_name
0  ulcerative colitis  mesalamine

 Run 5 completed | rows=25 | latency=45.515s
------------------------------------------------------------


## Question 40

**What targets are acted on by imatinib?**

In [149]:

question = 'What targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,imatinib,bcr-abl1,abl1,inhibits bcr-abl1 tyrosine kinase activity,approved

 Run 1 completed | rows=4 | latency=20.171s
------------------------------------------------------------

 Starting run 2 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,imatinib,bcr-abl1,abl1,atp-competitive tyrosine kinase inhibitor of a...

 Run 2 completed | rows=4 | latency=28.379s
------------------------------------------------------------

 Starting run 3 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,imatinib,bcr-abl1,abl1,"tyrosine kinase inhibitor of bcr-abl1, kit, pd...",approved

 Run 3 completed | rows=4 | latency=26.415s
------------------------------------------------------------

 Starting run 4 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,imatinib,abl1,abl1,tyrosine kinase inhibitor of abl1 (including b...

 Run 4 completed | rows=4 | latency=27.918s
------------------------------------------------------------

 Starting run 5 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 6

,drug_name,target_name,gene_name,mechanism_of_action
0,imatinib,bcr-abl1,abl1,atp-competitive inhibition of bcr-abl1 kinase

 Run 5 completed | rows=6 | latency=28.089s
------------------------------------------------------------


## Question 41

**What biological targets does sorafenib interact with?**

In [150]:

question = 'What biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,sorafenib,braf,braf,inhibits braf kinase activity,approved

 Run 1 completed | rows=8 | latency=28.250s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,sorafenib,braf,braf,multi-kinase tyrosine kinase inhibitor; inhibi...,approved

 Run 2 completed | rows=8 | latency=56.149s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name mechanism_of_action
0  sorafenib        braf      braf   kinase_inhibition

 Run 3 completed | rows=8 | latency=24.922s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name               mechanism_of_action
0  sorafenib        braf      braf  inhibits raf kinases (craf/braf)

 Run 4 completed | rows=8 | latency=33.682s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action
0,sorafenib,craf (raf1),raf1,atp-competitive inhibition of raf kinases (cra...

 Run 5 completed | rows=8 | latency=34.663s
------------------------------------------------------------


## Question 42

**What biological targets does tofacitinib affect?**

In [151]:

question = 'What biological targets does tofacitinib affect?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action
0,tofacitinib,jak1,jak1,atp-competitive inhibitor of jak1; blocks jak-...

 Run 1 completed | rows=3 | latency=15.843s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,tofacitinib,jak1,jak1,jak1 inhibitor; inhibits jak-stat signaling

 Run 2 completed | rows=2 | latency=16.804s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action
0,tofacitinib,jak1,jak1,jak1 inhibition; reduces jak-stat signaling do...

 Run 3 completed | rows=3 | latency=21.636s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action
0,tofacitinib,janus kinase 1,jak1,inhibits jak1-mediated jak-stat signaling.

 Run 4 completed | rows=3 | latency=18.365s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name     target_name gene_name     mechanism_of_action
0  tofacitinib  janus kinase 1      jak1  inhibits jak1 activity

 Run 5 completed | rows=3 | latency=17.373s
------------------------------------------------------------


## Question 43

**Which drugs are known to target EGFR?**

In [152]:

question = 'Which drugs are known to target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,egfr,egfr,egfr tyrosine kinase inhibitor,approved

 Run 1 completed | rows=8 | latency=24.783s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are known to target EGFR?
  Attempt 1/3
 Attempt 1 failed after 31.251s: Error tokenizing data. C error: Expected 4 fields in line 9, saw 6

  Attempt 2/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,egfr,egfr,egfr tyrosine kinase inhibitor (reversible),approved

 Run 2 completed | rows=8 | latency=24.330s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,erlotinib,egfr,egfr,egfr tyrosine kinase inhibitor,approved

 Run 3 completed | rows=9 | latency=43.369s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 10

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,egfr,egfr,egfr tyrosine kinase inhibitor,approved

 Run 4 completed | rows=10 | latency=27.025s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 12

   drug_name target_name gene_name             mechanism_of_action
0  gefitinib        egfr      egfr  egfr tyrosine kinase inhibitor

 Run 5 completed | rows=12 | latency=30.878s
------------------------------------------------------------


## Question 44

**Which diseases are linked to the TP53?**

In [153]:

question = 'Which diseases are linked to the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 6

  gene_name          disease_name
0      tp53  li-fraumeni syndrome

 Run 1 completed | rows=6 | latency=17.304s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 2 completed | rows=1 | latency=12.450s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 7

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 3 completed | rows=7 | latency=16.779s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 4 completed | rows=6 | latency=17.038s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  li-fraumeni syndrome      tp53

 Run 5 completed | rows=6 | latency=13.369s
------------------------------------------------------------


## Question 45

**Which diseases are associated with FGFR2?**

In [154]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 1 completed | rows=9 | latency=30.813s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 6

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 2 completed | rows=6 | latency=19.056s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 3 completed | rows=8 | latency=20.613s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 6

  gene_name    disease_name
0     fgfr2  apert syndrome

 Run 4 completed | rows=6 | latency=20.164s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 5

     disease_name gene_name
0  apert syndrome     fgfr2

 Run 5 completed | rows=5 | latency=20.118s
------------------------------------------------------------


## Question 46

**Which diseases are linked to the HTT?**

In [155]:

question = 'Which diseases are linked to the HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  huntington disease       htt

 Run 1 completed | rows=1 | latency=7.943s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name   gene_name
0  huntington disease  huntingtin

 Run 2 completed | rows=1 | latency=14.244s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  huntington's disease       htt

 Run 3 completed | rows=1 | latency=9.517s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  huntington's disease       htt

 Run 4 completed | rows=1 | latency=7.935s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  huntington disease       htt

 Run 5 completed | rows=1 | latency=6.703s
------------------------------------------------------------


## Question 47

**Which genes are associated with breast cancer?**

In [156]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 19

    disease_name gene_name
0  breast cancer     brca1

 Run 1 completed | rows=19 | latency=16.015s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 17

    disease_name gene_name
0  breast cancer     brca1

 Run 2 completed | rows=17 | latency=16.963s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 17

    disease_name gene_name
0  breast cancer     brca1

 Run 3 completed | rows=17 | latency=14.283s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 14

    disease_name gene_name
0  breast cancer     brca1

 Run 4 completed | rows=14 | latency=13.075s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 16

    disease_name gene_name
0  breast cancer     brca1

 Run 5 completed | rows=16 | latency=16.152s
------------------------------------------------------------


## Question 48

**Which genes are associated with colorectal cancer?**

In [157]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 13

        disease_name gene_name
0  colorectal cancer       apc

 Run 1 completed | rows=13 | latency=17.115s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  colorectal cancer       apc

 Run 2 completed | rows=14 | latency=16.827s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 19

        disease_name gene_name
0  colorectal cancer       apc

 Run 3 completed | rows=19 | latency=15.173s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  colorectal cancer       apc

 Run 4 completed | rows=14 | latency=16.746s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 16

        disease_name gene_name
0  colorectal cancer       apc

 Run 5 completed | rows=16 | latency=12.362s
------------------------------------------------------------


## Question 49

**What genes are linked to cystic fibrosis?**

In [158]:

question = 'What genes are linked to cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 1 completed | rows=1 | latency=7.886s
------------------------------------------------------------

 Starting run 2 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 2 completed | rows=1 | latency=6.472s
------------------------------------------------------------

 Starting run 3 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 3 completed | rows=1 | latency=8.804s
------------------------------------------------------------

 Starting run 4 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 4 completed | rows=1 | latency=14.259s
------------------------------------------------------------

 Starting run 5 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 2

      disease_name gene_name
0  cystic fibrosis      cftr

 Run 5 completed | rows=2 | latency=13.365s
------------------------------------------------------------


## Question 50

**What drugs are used in glioblastoma?**

In [159]:

question = 'What drugs are used in glioblastoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 4

   disease_name     drug_name
0  glioblastoma  temozolomide

 Run 1 completed | rows=4 | latency=14.147s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 4

   disease_name     drug_name
0  glioblastoma  temozolomide

 Run 2 completed | rows=4 | latency=14.312s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 3

,drug_name,disease_name,approval_status,mechanism_of_action
0,temozolomide,glioblastoma,approved,alkylating agent; methylates dna at o6-guanine

 Run 3 completed | rows=3 | latency=15.116s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 4

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        approved

 Run 4 completed | rows=4 | latency=32.051s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 3

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        approved

 Run 5 completed | rows=3 | latency=20.496s
------------------------------------------------------------


## Question 51

**Which diseases are treated by metformin?**

In [160]:

question = 'Which diseases are treated by metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  type 2 diabetes mellitus        approved

 Run 1 completed | rows=1 | latency=9.275s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  type 2 diabetes mellitus        approved

 Run 2 completed | rows=1 | latency=10.529s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 2

               disease_name  drug_name
0  type 2 diabetes mellitus  metformin

 Run 3 completed | rows=2 | latency=7.170s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  type 2 diabetes mellitus        approved

 Run 4 completed | rows=1 | latency=13.270s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  type 2 diabetes mellitus        approved

 Run 5 completed | rows=1 | latency=8.499s
------------------------------------------------------------


## Question 52

**What conditions is adalimumab used for?**

In [161]:

question = 'What conditions is adalimumab used for?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

           disease_name   drug_name
0  rheumatoid arthritis  adalimumab

 Run 1 completed | rows=9 | latency=12.931s
------------------------------------------------------------

 Starting run 2 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name approval_status
0  adalimumab  rheumatoid arthritis        approved

 Run 2 completed | rows=9 | latency=14.967s
------------------------------------------------------------

 Starting run 3 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 3 completed | rows=9 | latency=13.125s
------------------------------------------------------------

 Starting run 4 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 4 completed | rows=9 | latency=16.859s
------------------------------------------------------------

 Starting run 5 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

           disease_name    drug_name
0  rheumatoid arthritis   adalimumab

 Run 5 completed | rows=9 | latency=14.243s
------------------------------------------------------------


## Question 53

**Which diseases are pembrolizumab used in?**

In [162]:

question = 'Which diseases are pembrolizumab used in?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 1 completed | rows=9 | latency=19.879s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 8

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 2 completed | rows=8 | latency=28.554s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name
0  pembrolizumab     melanoma

 Run 3 completed | rows=9 | latency=19.715s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 8

  disease_name      drug_name
0     melanoma  pembrolizumab

 Run 4 completed | rows=8 | latency=27.104s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name approval_status
0  pembrolizumab     melanoma        approved

 Run 5 completed | rows=9 | latency=24.694s
------------------------------------------------------------


## Question 54

**Which diseases are treated with sorafenib?**

In [163]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

           disease_name  drug_name
0  renal cell carcinoma  sorafenib

 Run 1 completed | rows=3 | latency=8.883s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name approval_status
0  hepatocellular carcinoma  sorafenib        approved

 Run 2 completed | rows=3 | latency=11.822s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name approval_status
0  hepatocellular carcinoma  sorafenib        approved

 Run 3 completed | rows=3 | latency=7.449s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name          disease_name approval_status
0  sorafenib  renal cell carcinoma        approved

 Run 4 completed | rows=3 | latency=8.493s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name          disease_name approval_status
0  sorafenib  renal cell carcinoma        approved

 Run 5 completed | rows=3 | latency=16.275s
------------------------------------------------------------


## Question 55

**What diseases are treated with nivolumab?**

In [164]:

question = 'What diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

   drug_name        disease_name
0  nivolumab  malignant melanoma

 Run 1 completed | rows=8 | latency=23.986s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

  disease_name  drug_name
0     melanoma  nivolumab

 Run 2 completed | rows=9 | latency=29.680s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     melanoma

 Run 3 completed | rows=6 | latency=18.147s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

  disease_name  drug_name
0     melanoma  nivolumab

 Run 4 completed | rows=9 | latency=26.158s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name
0  nivolumab     melanoma

 Run 5 completed | rows=7 | latency=16.150s
------------------------------------------------------------


## Question 56

**Genes linked to multiple sclerosis.**

In [165]:

question = 'Genes linked to multiple sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 8

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 1 completed | rows=8 | latency=16.052s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 2 completed | rows=5 | latency=16.739s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 3 completed | rows=5 | latency=15.459s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 4 completed | rows=5 | latency=11.453s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 7

         disease_name gene_name
0  multiple sclerosis  hla-drb1

 Run 5 completed | rows=7 | latency=13.027s
------------------------------------------------------------


## Question 57

**Provide target names for rheumatoid arthritis.**

In [166]:

question = 'Provide target names for rheumatoid arthritis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 11

  target_name
0         tnf

 Run 1 completed | rows=11 | latency=17.736s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 10

           disease_name target_name
0  rheumatoid arthritis         tnf

 Run 2 completed | rows=10 | latency=22.952s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 11

           disease_name target_name gene_name
0  rheumatoid arthritis         tnf       tnf

 Run 3 completed | rows=11 | latency=34.068s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 8

  target_name          disease_name gene_name
0         tnf  rheumatoid arthritis       tnf

 Run 4 completed | rows=8 | latency=22.128s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 9

  target_name
0         tnf

 Run 5 completed | rows=9 | latency=15.993s
------------------------------------------------------------


## Question 58

**What are the targets of abatacept?**

In [167]:

question = 'What are the targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,abatacept,cd80,cd80,binds cd80 to inhibit cd28-mediated t-cell cos...,approved

 Run 1 completed | rows=2 | latency=13.922s
------------------------------------------------------------

 Starting run 2 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,abatacept,cd80,cd80,binds cd80 and cd86 to inhibit cd28-mediated c...

 Run 2 completed | rows=2 | latency=9.646s
------------------------------------------------------------

 Starting run 3 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,abatacept,cd80,cd80,binds cd80 to inhibit cd28-mediated costimulation

 Run 3 completed | rows=2 | latency=12.786s
------------------------------------------------------------

 Starting run 4 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,abatacept,cd80,cd80,ctla-4ig binds cd80 to inhibit cd28 costimulation,approved

 Run 4 completed | rows=2 | latency=10.188s
------------------------------------------------------------

 Starting run 5 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,abatacept,cd80,cd80,binds cd80 and cd86; inhibits cd28-mediated t-...

 Run 5 completed | rows=2 | latency=14.601s
------------------------------------------------------------


## Question 59

**Provide target names for lung cancer.**

In [168]:

question = 'Provide target names for lung cancer.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 14

  target_name disease_name
0        egfr  lung cancer

 Run 1 completed | rows=14 | latency=22.589s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 14

  disease_name target_name
0  lung cancer        egfr

 Run 2 completed | rows=14 | latency=19.714s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 14

  target_name gene_name
0        egfr      egfr

 Run 3 completed | rows=14 | latency=20.877s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 13

                 disease_name target_name
0  non-small cell lung cancer        egfr

 Run 4 completed | rows=13 | latency=26.065s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 16

  disease_name target_name
0  lung cancer        egfr

 Run 5 completed | rows=16 | latency=25.177s
------------------------------------------------------------


## Question 60

**What are the known targets of ponatinib?**

In [169]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 16

   drug_name target_name gene_name         mechanism_of_action
0  ponatinib    bcr-abl1      abl1  tyrosine kinase inhibition

 Run 1 completed | rows=16 | latency=28.949s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 11

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ponatinib,bcr-abl1,abl1,inhibits bcr-abl1 tyrosine kinase,approved

 Run 2 completed | rows=11 | latency=33.968s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 14

   drug_name target_name gene_name                         mechanism_of_action
0  ponatinib    bcr-abl1      abl1  inhibits bcr-abl1 tyrosine kinase activity

 Run 3 completed | rows=14 | latency=48.432s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 13

   drug_name target_name gene_name                     mechanism_of_action
0  ponatinib    bcr-abl1      abl1  tyrosine kinase inhibition of bcr-abl1

 Run 4 completed | rows=13 | latency=24.267s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 12

   drug_name target_name gene_name        mechanism_of_action approval_status
0  ponatinib     bcr-abl      abl1  tyrosine kinase inhibitor        approved

 Run 5 completed | rows=12 | latency=24.733s
------------------------------------------------------------


## Question 61

**Which drugs are used for systemic lupus erythematosus?**

In [170]:

question = 'Which drugs are used for systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

                   disease_name           drug_name approval_status
0  systemic lupus erythematosus  hydroxychloroquine        approved

 Run 1 completed | rows=8 | latency=20.511s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 3

                   disease_name           drug_name approval_status
0  systemic lupus erythematosus  hydroxychloroquine        approved

 Run 2 completed | rows=3 | latency=22.962s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

                   disease_name           drug_name approval_status
0  systemic lupus erythematosus  hydroxychloroquine        approved

 Run 3 completed | rows=7 | latency=19.350s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 4 completed | rows=7 | latency=19.539s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name
0  hydroxychloroquine  systemic lupus erythematosus

 Run 5 completed | rows=7 | latency=18.792s
------------------------------------------------------------


## Question 62

**Genes associated with autism spectrum disorder.**

In [171]:

question = 'Genes associated with autism spectrum disorder.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 23

               disease_name gene_name
0  autism spectrum disorder    shank3

 Run 1 completed | rows=23 | latency=16.823s
------------------------------------------------------------

 Starting run 2 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 17

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 2 completed | rows=17 | latency=14.626s
------------------------------------------------------------

 Starting run 3 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 20

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 3 completed | rows=20 | latency=28.251s
------------------------------------------------------------

 Starting run 4 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 14

               disease_name gene_name
0  autism spectrum disorder      chd8

 Run 4 completed | rows=14 | latency=12.865s
------------------------------------------------------------

 Starting run 5 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 20

               disease_name gene_name
0  autism spectrum disorder    shank3

 Run 5 completed | rows=20 | latency=20.914s
------------------------------------------------------------


## Question 63

**Diseases associated with the gene ROS1.**

In [172]:

question = 'Diseases associated with the gene ROS1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 5

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 1 completed | rows=5 | latency=16.573s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 2 completed | rows=3 | latency=16.742s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 3 completed | rows=3 | latency=16.691s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 4 completed | rows=3 | latency=12.545s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  non-small cell lung cancer      ros1

 Run 5 completed | rows=4 | latency=13.573s
------------------------------------------------------------


## Question 64

**Diseases associated with the gene ALK.**

In [173]:

question = 'Diseases associated with the gene ALK.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  anaplastic large cell lymphoma       alk

 Run 1 completed | rows=4 | latency=13.030s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 6

                     disease_name gene_name
0  anaplastic large cell lymphoma       alk

 Run 2 completed | rows=6 | latency=20.680s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  non-small cell lung cancer       alk

 Run 3 completed | rows=4 | latency=12.321s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  anaplastic large cell lymphoma       alk

 Run 4 completed | rows=4 | latency=14.902s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 5

                 disease_name gene_name
0  non-small cell lung cancer       alk

 Run 5 completed | rows=5 | latency=20.274s
------------------------------------------------------------


## Question 65

**Diseases associated with the gene EGFR.**

In [174]:

question = 'Diseases associated with the gene EGFR.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

          disease_name gene_name
0  lung adenocarcinoma      egfr

 Run 1 completed | rows=4 | latency=21.953s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 6

                 disease_name gene_name
0  non-small cell lung cancer      egfr

 Run 2 completed | rows=6 | latency=14.906s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 6

   disease_name gene_name
0  glioblastoma      egfr

 Run 3 completed | rows=6 | latency=21.595s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  non-small cell lung cancer      egfr

 Run 4 completed | rows=4 | latency=12.227s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  non-small cell lung carcinoma      egfr

 Run 5 completed | rows=4 | latency=18.210s
------------------------------------------------------------


## Question 66

**Provide target names for psoriasis.**

In [175]:

question = 'Provide target names for psoriasis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  disease_name            target_name gene_name
0    psoriasis  tumor necrosis factor       tnf

 Run 1 completed | rows=5 | latency=30.183s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  disease_name target_name gene_name
0    psoriasis         tnf       tnf

 Run 2 completed | rows=5 | latency=25.183s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 8

  target_name
0         tnf

 Run 3 completed | rows=8 | latency=29.877s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 7

  target_name gene_name
0         tnf       tnf

 Run 4 completed | rows=7 | latency=27.037s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 7

  target_name
0       il17a

 Run 5 completed | rows=7 | latency=20.815s
------------------------------------------------------------


## Question 67

**Provide target names for ulcerative colitis.**

In [176]:

question = 'Provide target names for ulcerative colitis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 4

         disease_name target_name gene_name approval_status
0  ulcerative colitis         tnf       tnf        approved

 Run 1 completed | rows=4 | latency=35.897s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 8

             target_name gene_name
0  tumor necrosis factor       tnf

 Run 2 completed | rows=8 | latency=32.992s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 8

  target_name
0         tnf

 Run 3 completed | rows=8 | latency=30.437s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 4

         disease_name target_name
0  ulcerative colitis         tnf

 Run 4 completed | rows=4 | latency=33.787s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 6

    drug_name target_name gene_name             mechanism_of_action
0  infliximab         tnf       tnf  anti-tnf-α monoclonal antibody

 Run 5 completed | rows=6 | latency=43.889s
------------------------------------------------------------


## Question 68

**Provide target names for tuberculosis.**

In [177]:

question = 'Provide target names for tuberculosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 6

   disease_name                  target_name
0  tuberculosis  rna polymerase beta subunit

 Run 1 completed | rows=6 | latency=37.144s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 7

  target_name
0        inha

 Run 2 completed | rows=7 | latency=30.552s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 6

   disease_name                         target_name
0  tuberculosis  rna polymerase beta subunit (rpob)

 Run 3 completed | rows=6 | latency=40.710s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 5

                          target_name
0  rna polymerase beta subunit (rpob)

 Run 4 completed | rows=5 | latency=27.053s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 5

   disease_name target_name
0  tuberculosis        inha

 Run 5 completed | rows=5 | latency=29.375s
------------------------------------------------------------


## Question 69

**Provide target names for hepatitis C.**

In [178]:

question = 'Provide target names for hepatitis C.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 5

  disease_name      target_name
0  hepatitis c  ns3/4a protease

 Run 1 completed | rows=5 | latency=31.222s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 4

  disease_name      target_name
0  hepatitis c  ns3/4a protease

 Run 2 completed | rows=4 | latency=23.775s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  disease_name      target_name
0  hepatitis c  ns3/4a protease

 Run 3 completed | rows=3 | latency=33.886s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name
0  ns3/4a protease

 Run 4 completed | rows=3 | latency=23.490s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name
0  ns3/4a protease

 Run 5 completed | rows=3 | latency=15.063s
------------------------------------------------------------


## Question 70

**Provide target names for Hodgkin lymphoma.**

In [179]:

question = 'Provide target names for Hodgkin lymphoma.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

       disease_name target_name
0  hodgkin lymphoma       pdcd1

 Run 1 completed | rows=3 | latency=27.263s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name gene_name
0        cd30   tnfrsf8

 Run 2 completed | rows=3 | latency=21.706s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name gene_name      disease_name
0        cd30   tnfrsf8  hodgkin lymphoma

 Run 3 completed | rows=3 | latency=26.256s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 2

  target_name
0       pdcd1

 Run 4 completed | rows=2 | latency=14.351s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name
0     tnfrsf8

 Run 5 completed | rows=3 | latency=24.219s
------------------------------------------------------------


## Question 71

**Which pathways are associated with the TP53?**

In [180]:

question = 'Which pathways are associated with the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 2

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 1 completed | rows=2 | latency=16.992s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 2 completed | rows=3 | latency=17.456s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 3 completed | rows=3 | latency=14.195s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 4 completed | rows=3 | latency=18.080s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 5 completed | rows=4 | latency=14.690s
------------------------------------------------------------


## Question 72

**Which drugs are associated with the ERBB2?**

In [181]:

question = 'Which drugs are associated with the ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action
0,trastuzumab,erbb2,erbb2,monoclonal antibody against erbb2/her2; inhibi...

 Run 1 completed | rows=9 | latency=29.689s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action
0,trastuzumab,her2,erbb2,binds her2 extracellular domain; inhibits sign...

 Run 2 completed | rows=9 | latency=42.085s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action
0,trastuzumab,erbb2,erbb2,humanized monoclonal antibody against erbb2; i...

 Run 3 completed | rows=9 | latency=58.668s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action
0,trastuzumab,erbb2,erbb2,humanized monoclonal antibody targeting her2 r...

 Run 4 completed | rows=9 | latency=30.769s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 10

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,trastuzumab,erbb2,erbb2,her2-directed monoclonal antibody; inhibits he...,approved

 Run 5 completed | rows=10 | latency=36.280s
------------------------------------------------------------


## Question 73

**Which pathways are associated with the ADRB1 gene?**

In [182]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                                  pathway_name
0     adrb1  g protein-coupled receptor signaling pathway

 Run 1 completed | rows=3 | latency=23.294s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

                             pathway_name gene_name
0  adrenergic signaling in cardiomyocytes     adrb1

 Run 2 completed | rows=2 | latency=19.477s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                       pathway_name
0     adrb1  beta-adrenergic signaling pathway

 Run 3 completed | rows=3 | latency=14.705s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

             pathway_name gene_name
0  camp signaling pathway     adrb1

 Run 4 completed | rows=2 | latency=23.311s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                            pathway_name
0     adrb1  adrenergic signaling in cardiomyocytes

 Run 5 completed | rows=3 | latency=17.981s
------------------------------------------------------------


## Question 74

**Which pathways are associated with the DRD2 gene?**

In [183]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 1

           pathway_name gene_name
0  dopaminergic synapse      drd2

 Run 1 completed | rows=1 | latency=14.166s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name          pathway_name
0      drd2  dopaminergic synapse

 Run 2 completed | rows=4 | latency=13.198s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

           pathway_name gene_name
0  dopaminergic synapse      drd2

 Run 3 completed | rows=2 | latency=13.347s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

           pathway_name gene_name
0  dopaminergic synapse      drd2

 Run 4 completed | rows=4 | latency=13.203s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

           pathway_name gene_name
0  dopaminergic synapse      drd2

 Run 5 completed | rows=2 | latency=12.196s
------------------------------------------------------------


## Question 75

**Which pathways are associated with the HTR2A gene?**

In [184]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

                           pathway_name
0  serotonin receptor signaling pathway

 Run 1 completed | rows=2 | latency=31.584s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                 pathway_name
0     htr2a  serotonin signaling pathway

 Run 2 completed | rows=2 | latency=19.063s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name          pathway_name
0     htr2a  serotonergic synapse

 Run 3 completed | rows=2 | latency=20.809s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                                  pathway_name
0     htr2a  g protein-coupled receptor signaling pathway

 Run 4 completed | rows=2 | latency=19.144s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 5

                  pathway_name gene_name
0  serotonin signaling pathway     htr2a

 Run 5 completed | rows=5 | latency=14.835s
------------------------------------------------------------


## Question 76

**Which drugs are associated with the CD19 gene?**

In [185]:

question = 'Which drugs are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 6

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,tisagenlecleucel,cd19,cd19,cd19-directed car-t cell therapy,approved

 Run 1 completed | rows=6 | latency=22.298s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,target_name,gene_name,mechanism_of_action
0,blinatumomab,cd19,cd19,cd19-targeted bispecific t-cell engager (cd19/...

 Run 2 completed | rows=7 | latency=37.316s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,gene_name,target_name,mechanism_of_action
0,tisagenlecleucel,cd19,cd19,cd19-directed chimeric antigen receptor t-cell...

 Run 3 completed | rows=7 | latency=33.491s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,blinatumomab,cd19/cd3,cd19,cd19/cd3 bispecific t-cell engager; redirects ...,approved

 Run 4 completed | rows=8 | latency=51.062s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,tisagenlecleucel,cd19,cd19,cd19-directed car-t cell therapy,approved

 Run 5 completed | rows=7 | latency=30.395s
------------------------------------------------------------


## Question 77

**Which drugs are associated with the CTLA4 gene?**

In [186]:

question = 'Which drugs are associated with the CTLA4 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ipilimumab,ctla4,ctla4,monoclonal antibody against ctla-4; blocks ctl...,approved

 Run 1 completed | rows=3 | latency=25.600s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,ipilimumab,ctla-4,ctla4,monoclonal antibody against ctla-4; immune che...

 Run 2 completed | rows=4 | latency=24.669s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,ipilimumab,ctla-4,ctla4,human monoclonal antibody against ctla-4; bloc...

 Run 3 completed | rows=2 | latency=18.138s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ipilimumab,ctla-4,ctla4,anti-ctla-4 monoclonal antibody; immune checkp...,approved

 Run 4 completed | rows=2 | latency=17.386s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,ipilimumab,ctla4,ctla4,monoclonal antibody that blocks ctla-4 to enha...

 Run 5 completed | rows=2 | latency=22.612s
------------------------------------------------------------


## Question 78

**Which drugs are associated with the BTK gene?**

In [187]:

question = 'Which drugs are associated with the BTK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ibrutinib,bruton tyrosine kinase,btk,btk inhibition,approved

 Run 1 completed | rows=3 | latency=18.927s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 3

   drug_name gene_name target_name mechanism_of_action approval_status
0  ibrutinib       btk         btk      btk inhibition        approved

 Run 2 completed | rows=3 | latency=18.512s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,ibrutinib,bruton's tyrosine kinase,btk,irreversible covalent inhibitor of btk (c481)

 Run 3 completed | rows=4 | latency=23.244s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 6

,drug_name,target_name,gene_name,mechanism_of_action
0,ibrutinib,bruton tyrosine kinase,btk,covalent irreversible btk inhibitor

 Run 4 completed | rows=6 | latency=22.809s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 6

   drug_name               target_name gene_name mechanism_of_action
0  ibrutinib  bruton's tyrosine kinase       btk      btk inhibition

 Run 5 completed | rows=6 | latency=21.321s
------------------------------------------------------------


## Question 79

**Which drugs are associated with the SYK gene?**

In [188]:

question = 'Which drugs are associated with the SYK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

      drug_name target_name gene_name mechanism_of_action approval_status
0  fostamatinib         syk       syk       syk inhibitor        approved

 Run 1 completed | rows=2 | latency=27.949s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,fostamatinib,syk,syk,syk tyrosine kinase inhibitor,approved

 Run 2 completed | rows=2 | latency=14.251s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 3

      drug_name target_name gene_name mechanism_of_action approval_status
0  fostamatinib         syk       syk       syk inhibitor        approved

 Run 3 completed | rows=3 | latency=17.421s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

      drug_name target_name gene_name mechanism_of_action
0  fostamatinib         syk       syk       syk inhibitor

 Run 4 completed | rows=2 | latency=11.896s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,fostamatinib,spleen tyrosine kinase,syk,syk tyrosine kinase inhibition,approved

 Run 5 completed | rows=2 | latency=20.318s
------------------------------------------------------------


## Question 80

**Which pathways are associated with TP53?**

In [189]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_openai_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 1 completed | rows=3 | latency=11.065s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 2 completed | rows=3 | latency=10.658s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 3 completed | rows=3 | latency=15.210s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 4 completed | rows=3 | latency=10.226s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      tp53

 Run 5 completed | rows=3 | latency=15.685s
------------------------------------------------------------

##### Store as .pkl and json

In [191]:
# import pickle
# with open("OpenAI_same_question_response.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

# import json
# import pandas as pd

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("OpenAI_same_question_response.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )