In [4]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from opentarget_utility import retrieve_opentarget

from grok_utility import return_grok_answer

In [5]:



model = "grok-4-1-fast-non-reasoning-latest"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [6]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name           disease_name
0      BRAF  V600E mutant melanoma

 Run 1 completed | rows=4 | latency=1.403s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  gene_name           disease_name
0      BRAF  V600E-mutant melanoma

 Run 2 completed | rows=5 | latency=1.209s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 3

  gene_name           disease_name
0      BRAF  V600E-mutant melanoma

 Run 3 completed | rows=3 | latency=1.307s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0      BRAF  V600E melanoma

 Run 4 completed | rows=3 | latency=0.913s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 5

  gene_name           disease_name
0      BRAF  V600E-mutant melanoma

 Run 5 completed | rows=5 | latency=1.218s
------------------------------------------------------------


## Question 2

**List genes linked to amyotrophic lateral sclerosis.**

In [7]:

question = 'List genes linked to amyotrophic lateral sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 1 completed | rows=4 | latency=1.193s
------------------------------------------------------------

 Starting run 2 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 2 completed | rows=4 | latency=0.993s
------------------------------------------------------------

 Starting run 3 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 3 completed | rows=4 | latency=1.143s
------------------------------------------------------------

 Starting run 4 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 4 completed | rows=4 | latency=0.986s
------------------------------------------------------------

 Starting run 5 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 5 completed | rows=4 | latency=1.117s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [8]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 1 completed | rows=2 | latency=1.266s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 2 completed | rows=2 | latency=0.947s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 3 completed | rows=2 | latency=0.786s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 4 completed | rows=2 | latency=0.826s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 5 completed | rows=2 | latency=2.952s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [9]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 1 completed | rows=1 | latency=1.237s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 2 completed | rows=1 | latency=0.767s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name
0  JAK-STAT signaling pathway

 Run 3 completed | rows=1 | latency=0.774s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0      JAK2  JAK-STAT signaling pathway

 Run 4 completed | rows=1 | latency=0.751s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name
0  JAK-STAT signaling pathway

 Run 5 completed | rows=1 | latency=0.765s
------------------------------------------------------------


## Question 5

**Which drugs are used for treating rheumatoid arthritis?**

In [10]:

question = 'Which drugs are used for treating rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid arthritis        Approved

 Run 1 completed | rows=8 | latency=1.504s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid arthritis        Approved

 Run 2 completed | rows=8 | latency=1.543s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid arthritis        Approved

 Run 3 completed | rows=8 | latency=1.410s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 7

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid arthritis        Approved

 Run 4 completed | rows=7 | latency=1.320s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 6

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid arthritis        Approved

 Run 5 completed | rows=6 | latency=1.237s
------------------------------------------------------------


## Question 6

**What are the targets and mechanisms for dulaglutide?**

In [11]:

question = 'What are the targets and mechanisms for dulaglutide?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 1 completed | rows=1 | latency=1.265s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 2 completed | rows=1 | latency=0.885s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 3 completed | rows=1 | latency=1.070s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 4 completed | rows=1 | latency=0.895s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 5 completed | rows=1 | latency=0.786s
------------------------------------------------------------


## Question 7

**Provide target names for ovarian cancer?**

In [12]:

question = 'Provide target names for ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name    disease_name
0        EGFR      EGFR  Ovarian cancer

 Run 1 completed | rows=5 | latency=1.329s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name    disease_name
0       PARP1     PARP1  Ovarian cancer

 Run 2 completed | rows=4 | latency=1.036s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name    disease_name
0       PARP1     PARP1  Ovarian cancer

 Run 3 completed | rows=4 | latency=1.018s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

  target_name    disease_name
0       BRCA1  Ovarian cancer

 Run 4 completed | rows=3 | latency=0.818s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name    disease_name
0       PARP1       NaN  ovarian cancer

 Run 5 completed | rows=4 | latency=1.119s
------------------------------------------------------------


## Question 8

**What are the known targets of regorafenib?**

In [13]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name                  mechanism_of_action
0  regorafenib      VEGFR2   Receptor tyrosine kinase inhibitor

 Run 1 completed | rows=6 | latency=1.409s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name mechanism_of_action
0  regorafenib         RET    kinase inhibitor

 Run 2 completed | rows=11 | latency=1.632s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 8

                                                              drug
Assistant: <|control12|>drug_name target_name  mechanism_of_action

 Run 3 completed | rows=8 | latency=1.443s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name mechanism_of_action
0  regorafenib         RET    kinase inhibitor

 Run 4 completed | rows=11 | latency=1.488s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 10

     drug_name target_name mechanism_of_action
0  regorafenib       VGFR1                 TKI

 Run 5 completed | rows=10 | latency=1.516s
------------------------------------------------------------


## Question 9

**Which pathways are associated with the STAT3 gene?**

In [14]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 1 completed | rows=1 | latency=1.019s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 2 completed | rows=1 | latency=0.818s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 3 completed | rows=2 | latency=0.904s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 4 completed | rows=2 | latency=0.840s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 5 completed | rows=2 | latency=0.802s
------------------------------------------------------------


## Question 10

**Genes linked to fever.**

In [15]:

question = 'Genes linked to fever.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      IL1B        fever

 Run 1 completed | rows=3 | latency=0.850s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      IL1B        fever

 Run 2 completed | rows=3 | latency=1.153s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      IL1B        fever

 Run 3 completed | rows=3 | latency=0.895s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 4

  gene_name
0      IL1B

 Run 4 completed | rows=4 | latency=0.865s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      IL1B        fever

 Run 5 completed | rows=3 | latency=0.781s
------------------------------------------------------------


## Question 11

**List all drugs that target EGFR?**

In [16]:

question = 'List all drugs that target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 9

   drug_name target_name gene_name approval_status       mechanism_of_action
0  Cetuximab        EGFR      EGFR        Approved  EGFR monoclonal antibody

 Run 1 completed | rows=9 | latency=1.844s
------------------------------------------------------------

 Starting run 2 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name       mechanism_of_action approval_status
0  Cetuximab        EGFR      EGFR  EGFR monoclonal antibody        Approved

 Run 2 completed | rows=8 | latency=1.663s
------------------------------------------------------------

 Starting run 3 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 9

   drug_name target_name gene_name       mechanism_of_action approval_status
0  Cetuximab        EGFR      EGFR  EGFR monoclonal antibody        Approved

 Run 3 completed | rows=9 | latency=1.879s
------------------------------------------------------------

 Starting run 4 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 9

   drug_name target_name       mechanism_of_action approval_status
0  Cetuximab        EGFR  EGFR monoclonal antibody        Approved

 Run 4 completed | rows=9 | latency=1.667s
------------------------------------------------------------

 Starting run 5 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name gene_name approval_status       mechanism_of_action
0  Cetuximab        EGFR      EGFR        Approved  EGFR monoclonal antibody

 Run 5 completed | rows=7 | latency=1.658s
------------------------------------------------------------


## Question 12

**Show drugs that inhibit the FGFR2 gene?**

In [17]:

question = 'Show drugs that inhibit the FGFR2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Pemigatinib,FGFR2,FGFR2,FGFR2 tyrosine kinase inhibitor,Approved

 Run 1 completed | rows=2 | latency=1.311s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Pemigatinib,FGFR2,FGFR2,FGFR2 tyrosine kinase inhibitor,Approved

 Run 2 completed | rows=2 | latency=0.976s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name mechanism_of_action approval_status
0  Pemigatinib     FGFR2     FGFR2 inhibitor        Approved

 Run 3 completed | rows=2 | latency=0.927s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Pemigatinib,FGFR2,FGFR2,FGFR2 tyrosine kinase inhibitor,Approved

 Run 4 completed | rows=2 | latency=1.036s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Pemigatinib,FGFR2,FGFR2,FGFR2 tyrosine kinase inhibitor,Approved

 Run 5 completed | rows=2 | latency=1.633s
------------------------------------------------------------


## Question 13

**What diseases are treated with bevacizumab?**

In [18]:

question = 'What diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 9

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 1 completed | rows=9 | latency=1.771s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 2 completed | rows=7 | latency=1.196s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 3 completed | rows=6 | latency=0.897s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 4 completed | rows=6 | latency=0.921s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 5 completed | rows=7 | latency=1.016s
------------------------------------------------------------


## Question 14

**List treatments for plaque psoriasis and their mechanisms.**

In [19]:

question = 'List treatments for plaque psoriasis and their mechanisms.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 14

,drug_name,disease_name,mechanism_of_action,approval_status
0,Calcipotriol,Plaque psoriasis,Vitamin D analogue; promotes keratinocyte diff...,Approved

 Run 1 completed | rows=14 | latency=3.736s
------------------------------------------------------------

 Starting run 2 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 15

,drug_name,disease_name,mechanism_of_action,approval_status
0,Calcipotriol,Plaque psoriasis,Vitamin D analogue; inhibits keratinocyte prol...,Approved

 Run 2 completed | rows=15 | latency=3.429s
------------------------------------------------------------

 Starting run 3 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
 Attempt 1 failed after 4.114s: Error tokenizing data. C error: Expected 4 fields in line 19, saw 5

  Attempt 2/3
Entries retrieved: 16

,drug_name,disease_name,mechanism_of_action,approval_status
0,Calcipotriol,Plaque psoriasis,Vitamin D analogue; inhibits keratinocyte prol...,Approved

 Run 3 completed | rows=16 | latency=3.153s
------------------------------------------------------------

 Starting run 4 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 13

,drug_name,disease_name,mechanism_of_action,approval_status
0,Calcipotriol,Plaque psoriasis,Vitamin D analogue; inhibits keratinocyte prol...,Approved

 Run 4 completed | rows=13 | latency=3.085s
------------------------------------------------------------

 Starting run 5 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
 Attempt 1 failed after 3.282s: Error tokenizing data. C error: Expected 4 fields in line 13, saw 5

  Attempt 2/3
 Attempt 2 failed after 3.223s: Error tokenizing data. C error: Expected 4 fields in line 13, saw 5

  Attempt 3/3
 Attempt 3 failed after 3.316s: Error tokenizing data. C error: Expected 4 fields in line 14, saw 5

 Run 5 failed after 3 attempts
------------------------------------------------------------


## Question 15

**What are the known targets of cabozantinib?**

In [20]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 4

      drug_name target_name            mechanism_of_action
0  cabozantinib         RET  RET tyrosine kinase inhibitor

 Run 1 completed | rows=4 | latency=1.372s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 4

      drug_name target_name   mechanism_of_action
0  cabozantinib         RET  RET kinase inhibitor

 Run 2 completed | rows=4 | latency=1.031s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 4

      drug_name target_name   mechanism_of_action
0  cabozantinib         RET  RET kinase inhibitor

 Run 3 completed | rows=4 | latency=1.272s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name target_name mechanism_of_action
0  cabozantinib      VEGFR2                 TKI

 Run 4 completed | rows=5 | latency=1.739s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 4

      drug_name target_name mechanism_of_action
0  cabozantinib         RET                 TKI

 Run 5 completed | rows=4 | latency=1.494s
------------------------------------------------------------


## Question 16

**Show drugs that inhibit the RET gene?**

In [21]:

question = 'Show drugs that inhibit the RET gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Selpercatinib,RET,RET,RET tyrosine kinase inhibitor,Approved

 Run 1 completed | rows=2 | latency=1.211s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Selpercatinib,RET,RET,RET tyrosine kinase inhibitor,Approved

 Run 2 completed | rows=2 | latency=1.109s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 3

       drug_name gene_name            mechanism_of_action approval_status
0  Selpercatinib       RET  RET tyrosine kinase inhibitor        Approved

 Run 3 completed | rows=3 | latency=1.423s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

       drug_name approval_status   mechanism_of_action target_name gene_name
0  Selpercatinib        Approved  RET kinase inhibitor         RET       RET

 Run 4 completed | rows=2 | latency=1.024s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Selpercatinib,RET,RET,RET tyrosine kinase inhibitor,Approved

 Run 5 completed | rows=2 | latency=1.199s
------------------------------------------------------------


## Question 17

**Which pathways are associated with the TNF gene?**

In [22]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

            pathway_name
0  TNF signaling pathway

 Run 1 completed | rows=3 | latency=0.983s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                 pathway_name
0       TNF  NF-kappaB signaling pathway

 Run 2 completed | rows=3 | latency=0.966s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

            pathway_name
0  TNF signaling pathway

 Run 3 completed | rows=3 | latency=1.175s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                  pathway_name
0       TNF  NF-kappa B signaling pathway

 Run 4 completed | rows=3 | latency=0.896s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

            pathway_name
0  TNF signaling pathway

 Run 5 completed | rows=3 | latency=0.950s
------------------------------------------------------------


## Question 18

**Diseases associated with the gene NPM1.**

In [23]:

question = 'Diseases associated with the gene NPM1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

  gene_name            disease_name
0      NPM1  Acute myeloid leukemia

 Run 1 completed | rows=1 | latency=0.718s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

  gene_name            disease_name
0      NPM1  Acute myeloid leukemia

 Run 2 completed | rows=1 | latency=0.843s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

  gene_name            disease_name
0      NPM1  Acute myeloid leukemia

 Run 3 completed | rows=1 | latency=0.747s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

  gene_name            disease_name
0      NPM1  Acute myeloid leukemia

 Run 4 completed | rows=1 | latency=0.752s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

  gene_name            disease_name
0      NPM1  Acute myeloid leukemia

 Run 5 completed | rows=1 | latency=0.702s
------------------------------------------------------------


## Question 19

**Which pathways are associated with the CD19 gene?**

In [24]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 1 completed | rows=2 | latency=1.066s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 2 completed | rows=2 | latency=0.957s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 3 completed | rows=2 | latency=0.958s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 4 completed | rows=2 | latency=0.910s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 5 completed | rows=2 | latency=0.893s
------------------------------------------------------------


## Question 20

**Which drugs are used for treating migraine?**

In [25]:

question = 'Which drugs are used for treating migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 13

     drug_name disease_name approval_status
0  sumatriptan     migraine        Approved

 Run 1 completed | rows=13 | latency=2.061s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 13

     drug_name disease_name approval_status
0  sumatriptan     migraine        Approved

 Run 2 completed | rows=13 | latency=1.572s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 11

     drug_name disease_name approval_status
0  sumatriptan     migraine        Approved

 Run 3 completed | rows=11 | latency=1.289s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 10

     drug_name disease_name approval_status
0  sumatriptan     migraine        Approved

 Run 4 completed | rows=10 | latency=1.413s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 15

     drug_name disease_name approval_status
0  sumatriptan     migraine        Approved

 Run 5 completed | rows=15 | latency=2.354s
------------------------------------------------------------


## Question 21

**What are the targets and mechanisms for rituximab?**

In [26]:

question = 'What are the targets and mechanisms for rituximab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name                          mechanism_of_action
0  rituximab        CD20  CD20-directed cytolytic monoclonal antibody

 Run 1 completed | rows=1 | latency=0.901s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,CD20,MS4A1,monoclonal antibody that binds CD20 on B-cells...

 Run 2 completed | rows=1 | latency=1.303s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name                                mechanism_of_action
0  rituximab        CD20  chimeric monoclonal antibody targeting CD20, i...

 Run 3 completed | rows=1 | latency=1.083s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,CD20,MS4A1,anti-CD20 monoclonal antibody; CD20-directed c...

 Run 4 completed | rows=1 | latency=1.237s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,CD20,MS4A1,anti-CD20 monoclonal antibody; CD20-directed c...

 Run 5 completed | rows=1 | latency=1.252s
------------------------------------------------------------


## Question 22

**Provide target names for colorectal cancer?**

In [27]:

question = 'Provide target names for colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name       disease_name
0        EGFR      EGFR  colorectal cancer

 Run 1 completed | rows=4 | latency=1.041s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name       disease_name
0        EGFR      EGFR  colorectal cancer

 Run 2 completed | rows=5 | latency=1.271s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name       disease_name
0        EGFR      EGFR  colorectal cancer

 Run 3 completed | rows=4 | latency=1.083s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name       disease_name
0        EGFR      EGFR  colorectal cancer

 Run 4 completed | rows=5 | latency=1.273s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name
0        EGFR      EGFR

 Run 5 completed | rows=5 | latency=1.074s
------------------------------------------------------------


## Question 23

**Which are possible drugs against rickets?**

In [28]:

question = 'Which are possible drugs against rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 5

    drug_name disease_name approval_status
0  Calcitriol      Rickets        Approved

 Run 1 completed | rows=5 | latency=1.253s
------------------------------------------------------------

 Starting run 2 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 5

    drug_name disease_name approval_status
0  Calcitriol      Rickets        Approved

 Run 2 completed | rows=5 | latency=1.514s
------------------------------------------------------------

 Starting run 3 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

    drug_name disease_name approval_status
0  Calcitriol      Rickets        Approved

 Run 3 completed | rows=4 | latency=1.214s
------------------------------------------------------------

 Starting run 4 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

    drug_name disease_name approval_status
0  Calcitriol      Rickets        Approved

 Run 4 completed | rows=4 | latency=1.277s
------------------------------------------------------------

 Starting run 5 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

    drug_name disease_name approval_status
0  Calcitriol      Rickets        Approved

 Run 5 completed | rows=4 | latency=1.130s
------------------------------------------------------------


## Question 24

**Give me genes linked to epilepsy.**

In [29]:

question = 'Give me genes linked to epilepsy.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 8

  gene_name disease_name
0     SCN1A     epilepsy

 Run 1 completed | rows=8 | latency=1.472s
------------------------------------------------------------

 Starting run 2 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 8

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 2 completed | rows=8 | latency=1.395s
------------------------------------------------------------

 Starting run 3 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 8

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 3 completed | rows=8 | latency=1.220s
------------------------------------------------------------

 Starting run 4 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 8

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 4 completed | rows=8 | latency=1.324s
------------------------------------------------------------

 Starting run 5 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 8

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 5 completed | rows=8 | latency=1.397s
------------------------------------------------------------


## Question 25

**What diseases are treated with trastuzumab deruxtecan?**

In [30]:

question = 'What diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                 disease_name approval_status
0  trastuzumab deruxtecan  HER2-positive breast cancer        Approved

 Run 1 completed | rows=2 | latency=1.053s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name                 disease_name approval_status
0  trastuzumab deruxtecan  HER2-positive breast cancer        Approved

 Run 2 completed | rows=3 | latency=0.939s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

,drug_name,disease_name,approval_status
0,trastuzumab deruxtecan,HER2-positive metastatic breast cancer,Approved

 Run 3 completed | rows=3 | latency=1.186s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                 disease_name approval_status
0  trastuzumab deruxtecan  HER2-positive breast cancer        Approved

 Run 4 completed | rows=2 | latency=1.109s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

,drug_name,disease_name,approval_status
0,trastuzumab deruxtecan,HER2-positive metastatic breast cancer,Approved

 Run 5 completed | rows=3 | latency=1.248s
------------------------------------------------------------


## Question 26

**Genes linked to Alzheimer’s disease.**

In [31]:

question = 'Genes linked to Alzheimer’s disease.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer’s disease

 Run 1 completed | rows=4 | latency=0.954s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer’s disease

 Run 2 completed | rows=4 | latency=1.020s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer’s disease

 Run 3 completed | rows=4 | latency=1.076s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0      APOE  Alzheimer’s disease

 Run 4 completed | rows=4 | latency=0.943s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer’s disease

 Run 5 completed | rows=4 | latency=0.947s
------------------------------------------------------------


## Question 27

**For which disease is darolutamide used?**

In [32]:

question = 'For which disease is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name approval_status
0  darolutamide  prostate cancer        Approved

 Run 1 completed | rows=1 | latency=0.785s
------------------------------------------------------------

 Starting run 2 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name approval_status
0  darolutamide  prostate cancer        Approved

 Run 2 completed | rows=1 | latency=0.807s
------------------------------------------------------------

 Starting run 3 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name approval_status
0  darolutamide  prostate cancer        Approved

 Run 3 completed | rows=1 | latency=0.871s
------------------------------------------------------------

 Starting run 4 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name approval_status
0  darolutamide  prostate cancer        Approved

 Run 4 completed | rows=1 | latency=0.756s
------------------------------------------------------------

 Starting run 5 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name approval_status
0  darolutamide  prostate cancer        Approved

 Run 5 completed | rows=1 | latency=1.126s
------------------------------------------------------------


## Question 28

**Provide target names for renal cell carcinoma?**

In [33]:

question = 'Provide target names for renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name
0        VEGF         A

 Run 1 completed | rows=5 | latency=1.238s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  target_name          disease_name
0       VEGFA  Renal cell carcinoma

 Run 2 completed | rows=5 | latency=1.188s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 4

  target_name          disease_name
0       VEGFA  renal cell carcinoma

 Run 3 completed | rows=4 | latency=0.909s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 4

  target_name          disease_name
0       VEGFA  Renal cell carcinoma

 Run 4 completed | rows=4 | latency=1.041s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 3

  target_name          disease_name
0       VEGFA  renal cell carcinoma

 Run 5 completed | rows=3 | latency=1.006s
------------------------------------------------------------


## Question 29

**Diseases associated with the gene KRAS.**

In [34]:

question = 'Diseases associated with the gene KRAS.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

  gene_name     disease_name
0      KRAS  Noonan syndrome

 Run 1 completed | rows=5 | latency=0.927s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

  gene_name     disease_name
0      KRAS  Noonan syndrome

 Run 2 completed | rows=5 | latency=1.005s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

  gene_name     disease_name
0      KRAS  Noonan syndrome

 Run 3 completed | rows=5 | latency=1.209s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

  gene_name     disease_name
0      KRAS  Noonan syndrome

 Run 4 completed | rows=5 | latency=1.113s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

  gene_name     disease_name
0      KRAS  Noonan syndrome

 Run 5 completed | rows=5 | latency=0.989s
------------------------------------------------------------


## Question 30

**Which pathways are associated with the APP gene?**

In [35]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name         pathway_name
0       APP  Alzheimer's disease

 Run 1 completed | rows=3 | latency=0.823s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                 pathway_name
0       APP  Alzheimer's disease pathway

 Run 2 completed | rows=3 | latency=1.032s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                 pathway_name
0       APP  Alzheimer's disease pathway

 Run 3 completed | rows=2 | latency=0.840s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                 pathway_name
0       APP  Alzheimer's disease pathway

 Run 4 completed | rows=3 | latency=1.135s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name         pathway_name
0       APP  Alzheimer's disease

 Run 5 completed | rows=3 | latency=0.905s
------------------------------------------------------------


## Question 31

**Genes linked to schizophrenia.**

In [36]:

question = 'Genes linked to schizophrenia.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 6

  gene_name   disease_name
0     DISC1  schizophrenia

 Run 1 completed | rows=6 | latency=1.117s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     DISC1  schizophrenia

 Run 2 completed | rows=5 | latency=1.148s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 6

  gene_name   disease_name
0     DISC1  Schizophrenia

 Run 3 completed | rows=6 | latency=0.964s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     DISC1  schizophrenia

 Run 4 completed | rows=5 | latency=0.871s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     DISC1  schizophrenia

 Run 5 completed | rows=5 | latency=3.145s
------------------------------------------------------------


## Question 32

**What diseases are treated with valdecoxib?**

In [37]:

question = 'What diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name approval_status
0  valdecoxib  Osteoarthritis        Approved

 Run 1 completed | rows=2 | latency=0.915s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name approval_status
0  valdecoxib  Osteoarthritis        Approved

 Run 2 completed | rows=2 | latency=0.931s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name approval_status
0  valdecoxib  Osteoarthritis        Approved

 Run 3 completed | rows=2 | latency=0.854s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name approval_status
0  valdecoxib  Osteoarthritis        Approved

 Run 4 completed | rows=2 | latency=0.903s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name approval_status
0  valdecoxib  Osteoarthritis        Approved

 Run 5 completed | rows=2 | latency=0.956s
------------------------------------------------------------


## Question 33

**What are the known targets of vandetanib?**

In [38]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name gene_name        mechanism_of_action
0  vandetanib      VEGFR2       KDR  tyrosine kinase inhibitor

 Run 1 completed | rows=3 | latency=1.060s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name        mechanism_of_action
0  vandetanib      VEGFR2  tyrosine kinase inhibitor

 Run 2 completed | rows=4 | latency=1.209s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name        mechanism_of_action
0  vandetanib        EGFR  tyrosine kinase inhibitor

 Run 3 completed | rows=3 | latency=1.047s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name        mechanism_of_action
0  vandetanib        EGFR  tyrosine kinase inhibitor

 Run 4 completed | rows=3 | latency=1.063s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name        mechanism_of_action
0  vandetanib      VEGFR2  tyrosine kinase inhibitor

 Run 5 completed | rows=4 | latency=1.002s
------------------------------------------------------------


## Question 34

**Which pathways are associated with the CFTR gene?**

In [39]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name             pathway_name
0      CFTR  ABC transporter pathway

 Run 1 completed | rows=1 | latency=1.039s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name             pathway_name
0      CFTR  ABC transporter pathway

 Run 2 completed | rows=1 | latency=0.757s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name             pathway_name
0      CFTR  ABC transporter pathway

 Run 3 completed | rows=1 | latency=0.774s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name             pathway_name
0      CFTR  ABC transporter pathway

 Run 4 completed | rows=1 | latency=0.928s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name             pathway_name
0      CFTR  ABC transporter pathway

 Run 5 completed | rows=1 | latency=0.992s
------------------------------------------------------------


## Question 35

**Which drugs are used for TB?**

In [40]:

question = 'Which drugs are used for TB?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 1 completed | rows=5 | latency=1.166s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 2 completed | rows=4 | latency=1.021s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 3 completed | rows=4 | latency=1.039s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 4 completed | rows=4 | latency=1.203s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 5 completed | rows=4 | latency=0.998s
------------------------------------------------------------


## Question 36

**Which drugs are used for pancreatic adenocarcinoma?**

In [41]:

question = 'Which drugs are used for pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name approval_status
0  gemcitabine  pancreatic adenocarcinoma        Approved

 Run 1 completed | rows=6 | latency=1.273s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name approval_status
0  gemcitabine  pancreatic adenocarcinoma        Approved

 Run 2 completed | rows=5 | latency=1.166s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 7

     drug_name               disease_name approval_status
0  gemcitabine  pancreatic adenocarcinoma        Approved

 Run 3 completed | rows=7 | latency=1.203s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name approval_status
0  gemcitabine  pancreatic adenocarcinoma        Approved

 Run 4 completed | rows=6 | latency=1.166s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name approval_status
0  gemcitabine  pancreatic adenocarcinoma        Approved

 Run 5 completed | rows=5 | latency=1.295s
------------------------------------------------------------


## Question 37

**Which drugs are used in chronic myeloid leukemia?**

In [42]:

question = 'Which drugs are used in chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic myeloid leukemia        Approved

 Run 1 completed | rows=5 | latency=1.250s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic myeloid leukemia        Approved

 Run 2 completed | rows=5 | latency=1.110s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic myeloid leukemia        Approved

 Run 3 completed | rows=5 | latency=1.103s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

,drug_name,disease_name,approval_status,mechanism_of_action
0,Imatinib,Chronic myeloid leukemia,Approved,BCR-ABL tyrosine kinase inhibitor

 Run 4 completed | rows=5 | latency=1.395s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic myeloid leukemia        Approved

 Run 5 completed | rows=5 | latency=1.134s
------------------------------------------------------------


## Question 38

**What drugs are used in the treatment of Parkinson’s disease?**

In [43]:

question = 'What drugs are used in the treatment of Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 7

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 1 completed | rows=7 | latency=1.358s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 7

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 2 completed | rows=7 | latency=1.327s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 14

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 3 completed | rows=14 | latency=2.194s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 10

  drug_name         disease_name approval_status mechanism_of_action
0  Levodopa  Parkinson’s disease        Approved  Dopamine precursor

 Run 4 completed | rows=10 | latency=2.358s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 8

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 5 completed | rows=8 | latency=1.340s
------------------------------------------------------------


## Question 39

**Which drugs are used for inflammatory bowel disease?**

In [44]:

question = 'Which drugs are used for inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 10

    drug_name                disease_name approval_status
0  Mesalazine  Inflammatory bowel disease        Approved

 Run 1 completed | rows=10 | latency=1.485s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 7

    drug_name                disease_name approval_status
0  Infliximab  Inflammatory bowel disease        Approved

 Run 2 completed | rows=7 | latency=1.358s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 10

    drug_name                disease_name approval_status
0  Mesalazine  Inflammatory bowel disease        Approved

 Run 3 completed | rows=10 | latency=1.461s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 10

    drug_name                disease_name approval_status
0  Mesalazine  Inflammatory bowel disease        Approved

 Run 4 completed | rows=10 | latency=1.283s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 10

    drug_name                disease_name approval_status
0  Mesalazine  Inflammatory bowel disease        Approved

 Run 5 completed | rows=10 | latency=1.365s
------------------------------------------------------------


## Question 40

**What targets are acted on by imatinib?**

In [45]:

question = 'What targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name           target_name gene_name        mechanism_of_action
0  imatinib  ABL1 tyrosine kinase      ABL1  tyrosine kinase inhibitor

 Run 1 completed | rows=4 | latency=1.475s
------------------------------------------------------------

 Starting run 2 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name           target_name gene_name        mechanism_of_action
0  imatinib  ABL1 tyrosine kinase      ABL1  tyrosine kinase inhibitor

 Run 2 completed | rows=4 | latency=1.382s
------------------------------------------------------------

 Starting run 3 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name      target_name gene_name mechanism_of_action
0  imatinib  BCR-ABL1 kinase  BCR-ABL1                 TKI

 Run 3 completed | rows=4 | latency=1.341s
------------------------------------------------------------

 Starting run 4 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name           target_name gene_name        mechanism_of_action
0  imatinib  ABL1 tyrosine kinase      ABL1  tyrosine kinase inhibitor

 Run 4 completed | rows=4 | latency=1.395s
------------------------------------------------------------

 Starting run 5 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 3

  drug_name           target_name gene_name        mechanism_of_action
0  imatinib  ABL1 tyrosine kinase  BCR-ABL1  tyrosine kinase inhibitor

 Run 5 completed | rows=3 | latency=1.216s
------------------------------------------------------------


## Question 41

**What biological targets does sorafenib interact with?**

In [46]:

question = 'What biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 6

,drug_name,target_name,mechanism_of_action
0,sorafenib,RAF proto-oncogene serine/threonine-protein ki...,multikinase inhibitor

 Run 1 completed | rows=6 | latency=1.521s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name mechanism_of_action
0  sorafenib        RAF1       RAF inhibitor

 Run 2 completed | rows=5 | latency=1.387s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 4

   drug_name target_name mechanism_of_action
0  sorafenib         RAF       RAF inhibitor

 Run 3 completed | rows=4 | latency=2.239s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name mechanism_of_action
0  sorafenib        RAF1       RAF inhibitor

 Run 4 completed | rows=5 | latency=1.377s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name mechanism_of_action
0  sorafenib        RAF1       RAF inhibitor

 Run 5 completed | rows=6 | latency=1.178s
------------------------------------------------------------


## Question 42

**What biological targets does tofacitinib affect?**

In [47]:

question = 'What biological targets does tofacitinib affect?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name     target_name gene_name     mechanism_of_action
0  Tofacitinib  Janus kinase 1      JAK1  Janus kinase inhibitor

 Run 1 completed | rows=3 | latency=0.936s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 2

     drug_name     target_name gene_name     mechanism_of_action
0  Tofacitinib  Janus kinase 1      JAK1  Janus kinase inhibitor

 Run 2 completed | rows=2 | latency=1.212s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 2

     drug_name     target_name gene_name     mechanism_of_action
0  Tofacitinib  Janus kinase 1      JAK1  Janus kinase inhibitor

 Run 3 completed | rows=2 | latency=1.112s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name target_name gene_name     mechanism_of_action
0  tofacitinib        JAK1      JAK1  Janus kinase inhibitor

 Run 4 completed | rows=3 | latency=0.954s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 2

     drug_name     target_name gene_name     mechanism_of_action
0  Tofacitinib  Janus kinase 1      JAK1  Janus kinase inhibitor

 Run 5 completed | rows=2 | latency=0.939s
------------------------------------------------------------


## Question 43

**Which drugs are known to target EGFR?**

In [48]:

question = 'Which drugs are known to target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Gefitinib,EGFR,EGFR,Approved,EGFR tyrosine kinase inhibitor

 Run 1 completed | rows=6 | latency=1.747s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name gene_name approval_status       mechanism_of_action
0  Cetuximab        EGFR      EGFR        Approved  EGFR monoclonal antibody

 Run 2 completed | rows=7 | latency=2.021s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibitor,Approved

 Run 3 completed | rows=6 | latency=1.272s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name gene_name       mechanism_of_action approval_status
0  Cetuximab        EGFR      EGFR  EGFR monoclonal antibody        Approved

 Run 4 completed | rows=6 | latency=1.323s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name gene_name approval_status       mechanism_of_action
0  Cetuximab        EGFR      EGFR        Approved  EGFR monoclonal antibody

 Run 5 completed | rows=7 | latency=1.775s
------------------------------------------------------------


## Question 44

**Which diseases are linked to the TP53?**

In [49]:

question = 'Which diseases are linked to the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 1 completed | rows=3 | latency=0.872s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 2 completed | rows=5 | latency=0.916s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 3 completed | rows=5 | latency=1.084s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 4 completed | rows=5 | latency=1.206s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 5 completed | rows=5 | latency=0.835s
------------------------------------------------------------


## Question 45

**Which diseases are associated with FGFR2?**

In [50]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 1 completed | rows=3 | latency=0.855s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 2 completed | rows=3 | latency=1.353s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 3 completed | rows=3 | latency=0.812s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 4 completed | rows=3 | latency=1.054s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 5 completed | rows=3 | latency=0.893s
------------------------------------------------------------


## Question 46

**Which diseases are linked to the HTT?**

In [51]:

question = 'Which diseases are linked to the HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 1 completed | rows=1 | latency=0.837s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 2 completed | rows=1 | latency=0.794s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 3 completed | rows=1 | latency=0.774s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 4 completed | rows=1 | latency=0.755s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 5 completed | rows=1 | latency=0.712s
------------------------------------------------------------


## Question 47

**Which genes are associated with breast cancer?**

In [52]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     BRCA1  Breast cancer

 Run 1 completed | rows=5 | latency=0.918s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     BRCA1  Breast cancer

 Run 2 completed | rows=5 | latency=1.069s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     BRCA1  Breast cancer

 Run 3 completed | rows=5 | latency=1.011s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     BRCA1  Breast cancer

 Run 4 completed | rows=5 | latency=0.953s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0     BRCA1  Breast cancer

 Run 5 completed | rows=5 | latency=0.884s
------------------------------------------------------------


## Question 48

**Which genes are associated with colorectal cancer?**

In [53]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name       disease_name
0       APC  colorectal cancer

 Run 1 completed | rows=5 | latency=0.983s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 6

  gene_name       disease_name
0       APC  colorectal cancer

 Run 2 completed | rows=6 | latency=0.995s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 6

  gene_name       disease_name
0       APC  colorectal cancer

 Run 3 completed | rows=6 | latency=1.088s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name       disease_name
0       APC  colorectal cancer

 Run 4 completed | rows=5 | latency=1.035s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 6

  gene_name       disease_name
0       APC  colorectal cancer

 Run 5 completed | rows=6 | latency=1.040s
------------------------------------------------------------


## Question 49

**What genes are linked to cystic fibrosis?**

In [54]:

question = 'What genes are linked to cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 1 completed | rows=1 | latency=0.750s
------------------------------------------------------------

 Starting run 2 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 2 completed | rows=1 | latency=0.707s
------------------------------------------------------------

 Starting run 3 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 3 completed | rows=1 | latency=0.709s
------------------------------------------------------------

 Starting run 4 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 4 completed | rows=1 | latency=0.749s
------------------------------------------------------------

 Starting run 5 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 5 completed | rows=1 | latency=0.717s
------------------------------------------------------------


## Question 50

**What drugs are used in glioblastoma?**

In [55]:

question = 'What drugs are used in glioblastoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 2

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        Approved

 Run 1 completed | rows=2 | latency=0.879s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 2

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        Approved

 Run 2 completed | rows=2 | latency=0.973s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 2

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        Approved

 Run 3 completed | rows=2 | latency=0.912s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 2

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        Approved

 Run 4 completed | rows=2 | latency=0.866s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 2

      drug_name  disease_name approval_status
0  temozolomide  glioblastoma        Approved

 Run 5 completed | rows=2 | latency=0.916s
------------------------------------------------------------


## Question 51

**Which diseases are treated by metformin?**

In [56]:

question = 'Which diseases are treated by metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 1 completed | rows=1 | latency=0.774s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 2 completed | rows=1 | latency=0.858s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 3 completed | rows=1 | latency=0.821s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 4 completed | rows=1 | latency=0.849s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 5 completed | rows=1 | latency=0.865s
------------------------------------------------------------


## Question 52

**What conditions is adalimumab used for?**

In [57]:

question = 'What conditions is adalimumab used for?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name
0  Rheumatoid arthritis  adalimumab

 Run 1 completed | rows=8 | latency=1.360s
------------------------------------------------------------

 Starting run 2 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name
0  Rheumatoid arthritis  adalimumab

 Run 2 completed | rows=8 | latency=1.261s
------------------------------------------------------------

 Starting run 3 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name
0  Rheumatoid arthritis  adalimumab

 Run 3 completed | rows=8 | latency=1.175s
------------------------------------------------------------

 Starting run 4 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name
0  Rheumatoid arthritis  adalimumab

 Run 4 completed | rows=8 | latency=1.351s
------------------------------------------------------------

 Starting run 5 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name
0  Rheumatoid arthritis  adalimumab

 Run 5 completed | rows=8 | latency=1.131s
------------------------------------------------------------


## Question 53

**Which diseases are pembrolizumab used in?**

In [58]:

question = 'Which diseases are pembrolizumab used in?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 1 completed | rows=11 | latency=2.008s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 12

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 2 completed | rows=12 | latency=1.902s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 14

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 3 completed | rows=14 | latency=1.958s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 7

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 4 completed | rows=7 | latency=1.479s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 5 completed | rows=11 | latency=1.840s
------------------------------------------------------------


## Question 54

**Which diseases are treated with sorafenib?**

In [59]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name approval_status
0  sorafenib  hepatocellular carcinoma        Approved

 Run 1 completed | rows=3 | latency=0.954s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name approval_status
0  sorafenib  hepatocellular carcinoma        Approved

 Run 2 completed | rows=3 | latency=0.873s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name approval_status
0  sorafenib  hepatocellular carcinoma        Approved

 Run 3 completed | rows=3 | latency=1.013s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name approval_status
0  sorafenib  hepatocellular carcinoma        Approved

 Run 4 completed | rows=3 | latency=0.983s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 5 completed | rows=3 | latency=0.961s
------------------------------------------------------------


## Question 55

**What diseases are treated with nivolumab?**

In [60]:

question = 'What diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 11

  disease_name  drug_name
0     Melanoma  nivolumab

 Run 1 completed | rows=11 | latency=2.230s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

   drug_name disease_name
0  nivolumab     Melanoma

 Run 2 completed | rows=9 | latency=1.561s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 10

   drug_name disease_name approval_status
0  nivolumab     Melanoma        Approved

 Run 3 completed | rows=10 | latency=1.505s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

   drug_name        disease_name approval_status
0  nivolumab  Malignant melanoma        Approved

 Run 4 completed | rows=9 | latency=1.393s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 10

   drug_name disease_name approval_status
0  nivolumab     Melanoma        Approved

 Run 5 completed | rows=10 | latency=1.681s
------------------------------------------------------------


## Question 56

**Genes linked to multiple sclerosis.**

In [61]:

question = 'Genes linked to multiple sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 7

  gene_name        disease_name
0  HLA-DRB1  Multiple sclerosis

 Run 1 completed | rows=7 | latency=1.395s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 7

  gene_name        disease_name
0  HLA-DRB1  Multiple sclerosis

 Run 2 completed | rows=7 | latency=1.249s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

  gene_name        disease_name
0  HLA-DRB1  Multiple sclerosis

 Run 3 completed | rows=5 | latency=1.054s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

  gene_name        disease_name
0  HLA-DRB1  Multiple sclerosis

 Run 4 completed | rows=5 | latency=1.216s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

  gene_name        disease_name
0  HLA-DRB1  Multiple sclerosis

 Run 5 completed | rows=5 | latency=1.171s
------------------------------------------------------------


## Question 57

**Provide target names for rheumatoid arthritis.**

In [62]:

question = 'Provide target names for rheumatoid arthritis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 5

  target_name           disease_name
0         TNF  tumor necrosis factor

 Run 1 completed | rows=5 | latency=1.373s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 3

  target_name          disease_name
0         TNF  arthritis rheumatoid

 Run 2 completed | rows=3 | latency=1.223s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 5

           disease_name                  target_name
0  Rheumatoid arthritis  Tumor necrosis factor (TNF)

 Run 3 completed | rows=5 | latency=1.420s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 6

  target_name gene_name
0         TNF      TNFA

 Run 4 completed | rows=6 | latency=1.177s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 6

  target_name gene_name
0   TNF-alpha       TNF

 Run 5 completed | rows=6 | latency=1.191s
------------------------------------------------------------


## Question 58

**What are the targets of abatacept?**

In [63]:

question = 'What are the targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name                                mechanism_of_action
0  abatacept        CD80  CTLA-4 Ig fusion protein binding and inhibitio...

 Run 1 completed | rows=2 | latency=1.188s
------------------------------------------------------------

 Starting run 2 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name                                mechanism_of_action
0  abatacept        CD80  CTLA-4 Ig fusion protein inhibiting CD80/CD86-...

 Run 2 completed | rows=2 | latency=1.119s
------------------------------------------------------------

 Starting run 3 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name                                mechanism_of_action
0  Abatacept        CD80  CTLA-4 Ig fusion protein inhibiting CD80/CD86-...

 Run 3 completed | rows=2 | latency=1.155s
------------------------------------------------------------

 Starting run 4 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name                                mechanism_of_action
0  abatacept        CD80  CTLA-4 Ig fusion protein that binds CD80/CD86 ...

 Run 4 completed | rows=2 | latency=1.132s
------------------------------------------------------------

 Starting run 5 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name                                mechanism_of_action
0  Abatacept        CD80  CTLA-4 Ig fusion protein inhibiting CD80/CD86-...

 Run 5 completed | rows=2 | latency=1.130s
------------------------------------------------------------


## Question 59

**Provide target names for lung cancer.**

In [64]:

question = 'Provide target names for lung cancer.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 9

  target_name
0        EGFR

 Run 1 completed | rows=9 | latency=1.445s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 6

  target_name gene_name disease_name
0        EGFR      EGFR  Lung cancer

 Run 2 completed | rows=6 | latency=1.245s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 7

  target_name gene_name disease_name
0        EGFR      EGFR  Lung cancer

 Run 3 completed | rows=7 | latency=1.110s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 7

  target_name gene_name disease_name
0        EGFR      EGFR  Lung cancer

 Run 4 completed | rows=7 | latency=1.082s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 7

  target_name gene_name disease_name
0        EGFR      EGFR  Lung cancer

 Run 5 completed | rows=7 | latency=1.460s
------------------------------------------------------------


## Question 60

**What are the known targets of ponatinib?**

In [65]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name        mechanism_of_action
0  ponatinib        ABL1  tyrosine kinase inhibitor

 Run 1 completed | rows=8 | latency=1.493s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name target_name        mechanism_of_action
0  ponatinib        ABL1  tyrosine kinase inhibitor

 Run 2 completed | rows=10 | latency=1.358s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name target_name        mechanism_of_action
0  ponatinib        ABL1  tyrosine kinase inhibitor

 Run 3 completed | rows=10 | latency=1.796s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name target_name        mechanism_of_action
0  ponatinib        ABL1  tyrosine kinase inhibitor

 Run 4 completed | rows=10 | latency=1.287s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name target_name        mechanism_of_action
0  ponatinib        ABL1  tyrosine kinase inhibitor

 Run 5 completed | rows=10 | latency=1.509s
------------------------------------------------------------


## Question 61

**Which drugs are used for systemic lupus erythematosus?**

In [66]:

question = 'Which drugs are used for systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 5

            drug_name                  disease_name approval_status
0  Hydroxychloroquine  Systemic lupus erythematosus        Approved

 Run 1 completed | rows=5 | latency=1.688s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 5

            drug_name                  disease_name approval_status
0  Hydroxychloroquine  Systemic lupus erythematosus        Approved

 Run 2 completed | rows=5 | latency=1.331s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name approval_status
0  Hydroxychloroquine  Systemic lupus erythematosus        Approved

 Run 3 completed | rows=7 | latency=1.567s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 4

            drug_name                  disease_name approval_status
0  Hydroxychloroquine  Systemic lupus erythematosus        Approved

 Run 4 completed | rows=4 | latency=1.254s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 3

            drug_name                  disease_name approval_status
0  Hydroxychloroquine  Systemic lupus erythematosus        Approved

 Run 5 completed | rows=3 | latency=1.060s
------------------------------------------------------------


## Question 62

**Genes associated with autism spectrum disorder.**

In [67]:

question = 'Genes associated with autism spectrum disorder.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 5

  gene_name              disease_name
0    SHANK3  Autism spectrum disorder

 Run 1 completed | rows=5 | latency=1.158s
------------------------------------------------------------

 Starting run 2 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 4

  gene_name              disease_name
0    SHANK3  Autism spectrum disorder

 Run 2 completed | rows=4 | latency=1.027s
------------------------------------------------------------

 Starting run 3 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 5

  gene_name              disease_name
0    SHANK3  Autism spectrum disorder

 Run 3 completed | rows=5 | latency=1.048s
------------------------------------------------------------

 Starting run 4 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 5

  gene_name              disease_name
0    SHANK3  Autism spectrum disorder

 Run 4 completed | rows=5 | latency=1.221s
------------------------------------------------------------

 Starting run 5 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 5

  gene_name              disease_name
0    SHANK3  Autism spectrum disorder

 Run 5 completed | rows=5 | latency=1.235s
------------------------------------------------------------


## Question 63

**Diseases associated with the gene ROS1.**

In [68]:

question = 'Diseases associated with the gene ROS1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

  gene_name                disease_name
0      ROS1  Non-small cell lung cancer

 Run 1 completed | rows=2 | latency=0.917s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

  gene_name                   disease_name
0      ROS1  Non-small cell lung carcinoma

 Run 2 completed | rows=2 | latency=0.846s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

  gene_name                   disease_name
0      ROS1  Non-small cell lung carcinoma

 Run 3 completed | rows=2 | latency=0.846s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

  gene_name                   disease_name
0      ROS1  Non-small cell lung carcinoma

 Run 4 completed | rows=2 | latency=0.922s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

  gene_name                disease_name
0      ROS1  Non-small cell lung cancer

 Run 5 completed | rows=2 | latency=0.849s
------------------------------------------------------------


## Question 64

**Diseases associated with the gene ALK.**

In [69]:

question = 'Diseases associated with the gene ALK.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                disease_name
0       ALK  Non-small cell lung cancer

 Run 1 completed | rows=3 | latency=1.165s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                disease_name
0       ALK  Non-small cell lung cancer

 Run 2 completed | rows=3 | latency=1.123s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                   disease_name
0       ALK  Non-small cell lung carcinoma

 Run 3 completed | rows=3 | latency=1.147s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

  gene_name                disease_name
0       ALK  Non-small cell lung cancer

 Run 4 completed | rows=4 | latency=1.004s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                disease_name
0       ALK  Non-small cell lung cancer

 Run 5 completed | rows=3 | latency=0.960s
------------------------------------------------------------


## Question 65

**Diseases associated with the gene EGFR.**

In [70]:

question = 'Diseases associated with the gene EGFR.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 3

  gene_name         disease_name
0      EGFR  Lung adenocarcinoma

 Run 1 completed | rows=3 | latency=0.843s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 3

  gene_name         disease_name
0      EGFR  Lung adenocarcinoma

 Run 2 completed | rows=3 | latency=0.904s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      EGFR  Lung cancer

 Run 3 completed | rows=4 | latency=1.103s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 5

  gene_name disease_name
0      EGFR  Lung cancer

 Run 4 completed | rows=5 | latency=0.960s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 3

  gene_name         disease_name
0      EGFR  Lung adenocarcinoma

 Run 5 completed | rows=3 | latency=0.894s
------------------------------------------------------------


## Question 66

**Provide target names for psoriasis.**

In [71]:

question = 'Provide target names for psoriasis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0      IL-17A

 Run 1 completed | rows=5 | latency=1.466s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0      IL-17A

 Run 2 completed | rows=5 | latency=1.009s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0      IL-17A

 Run 3 completed | rows=5 | latency=0.991s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 6

  target_name
0      IL-17A

 Run 4 completed | rows=6 | latency=1.001s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 6

  target_name
0      IL-17A

 Run 5 completed | rows=6 | latency=1.063s
------------------------------------------------------------


## Question 67

**Provide target names for ulcerative colitis.**

In [72]:

question = 'Provide target names for ulcerative colitis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name        mechanism_of_action
0   TNF-alpha      TNFA  pro-inflammatory cytokine

 Run 1 completed | rows=5 | latency=1.635s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0         TNF

 Run 2 completed | rows=5 | latency=0.931s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 7

  target_name
0         TNF

 Run 3 completed | rows=7 | latency=1.076s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 7

  target_name
0         TNF

 Run 4 completed | rows=7 | latency=1.065s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 6

  target_name
0         TNF

 Run 5 completed | rows=6 | latency=1.086s
------------------------------------------------------------


## Question 68

**Provide target names for tuberculosis.**

In [73]:

question = 'Provide target names for tuberculosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for tuberculosis.
  Attempt 1/3
 Attempt 1 failed after 0.912s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 2/3
 Attempt 2 failed after 0.402s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 3/3
 Attempt 3 failed after 0.396s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
 Run 1 failed after 3 attempts
------------------------------------------------------------

 Starting run 2 for query: Provide target names for tuberculosis.
  Attempt 1/3
 Attempt 1 failed after 0.383s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 2/3
 Attempt 2 failed after 0.377s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 3/3
 Attempt 3 failed after 0.383s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
 Run 2 failed after 3 attempts
------------------------------------------------------------

 Starting run 3 for query: Provide target names for tuberculosis.
  Attempt 1/3
 Attempt 1 failed after 0.390s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 2/3
 Attempt 2 failed after 0.396s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 3/3
 Attempt 3 failed after 0.399s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Provide target names for tuberculosis.
  Attempt 1/3
 Attempt 1 failed after 0.480s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 2/3
 Attempt 2 failed after 0.431s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 3/3
 Attempt 3 failed after 0.431s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
 Run 4 failed after 3 attempts
------------------------------------------------------------

 Starting run 5 for query: Provide target names for tuberculosis.
  Attempt 1/3
 Attempt 1 failed after 0.400s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 2/3
 Attempt 2 failed after 0.425s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
  Attempt 3/3
 Attempt 3 failed after 0.454s: Error code: 403 - {'code': 'The caller does not have permission to execute the specified operation', 'error': 'Content violates usage guidelines. Team: 0e92388a-608b-4e2e-aac3-fc9704d65fa4, API key ID: 1c91a7f8-3eb9-4af5-bed4-b7858ffdfa1a, Model: grok-4-1-fast-non-reasoning, Failed check: SAFETY_CHECK_TYPE_BIO'}
 Run 5 failed after 3 attempts
------------------------------------------------------------


## Question 69

**Provide target names for hepatitis C.**

In [74]:

question = 'Provide target names for hepatitis C.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name gene_name
0  NS3-4A protease   HCV NS3

 Run 1 completed | rows=3 | latency=1.048s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name gene_name
0  NS3-4A protease   HCV NS3

 Run 2 completed | rows=3 | latency=1.069s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

    target_name  gene_name
0  NS3 protease        NaN

 Run 3 completed | rows=3 | latency=1.048s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name gene_name
0  NS3-4A protease       NS3

 Run 4 completed | rows=3 | latency=1.055s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name gene_name
0  NS3/4A protease   HCV NS3

 Run 5 completed | rows=3 | latency=0.986s
------------------------------------------------------------


## Question 70

**Provide target names for Hodgkin lymphoma.**

In [75]:

question = 'Provide target names for Hodgkin lymphoma.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 2

  target_name gene_name
0        CD30   TNFRSF8

 Run 1 completed | rows=2 | latency=1.052s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 2

  target_name gene_name
0        CD30   TNFRSF8

 Run 2 completed | rows=2 | latency=0.854s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 2

  target_name gene_name
0        CD30   TNFRSF8

 Run 3 completed | rows=2 | latency=0.850s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 2

  target_name
0        CD30

 Run 4 completed | rows=2 | latency=0.710s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 2

  target_name gene_name
0        CD30   TNFRSF8

 Run 5 completed | rows=2 | latency=0.959s
------------------------------------------------------------


## Question 71

**Which pathways are associated with the TP53?**

In [76]:

question = 'Which pathways are associated with the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 1 completed | rows=1 | latency=0.787s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 2 completed | rows=1 | latency=0.815s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 3 completed | rows=3 | latency=0.830s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 4 completed | rows=3 | latency=0.997s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 5 completed | rows=3 | latency=0.776s
------------------------------------------------------------


## Question 72

**Which drugs are associated with the ERBB2?**

In [77]:

question = 'Which drugs are associated with the ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name       mechanism_of_action approval_status
0  Trastuzumab       ERBB2  HER2 monoclonal antibody        Approved

 Run 1 completed | rows=6 | latency=1.596s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name gene_name approval_status       mechanism_of_action
0  Trastuzumab       ERBB2     ERBB2        Approved  HER2 monoclonal antibody

 Run 2 completed | rows=6 | latency=1.886s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 5

     drug_name target_name gene_name approval_status       mechanism_of_action
0  Trastuzumab       ERBB2     ERBB2        Approved  HER2 monoclonal antibody

 Run 3 completed | rows=5 | latency=1.667s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name       mechanism_of_action approval_status
0  Trastuzumab       ERBB2  HER2 monoclonal antibody        Approved

 Run 4 completed | rows=6 | latency=1.945s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name       mechanism_of_action approval_status
0  Trastuzumab       ERBB2  HER2 monoclonal antibody        Approved

 Run 5 completed | rows=6 | latency=1.669s
------------------------------------------------------------


## Question 73

**Which pathways are associated with the ADRB1 gene?**

In [78]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
 Attempt 1 failed after 1.262s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  Attempt 2/3
 Attempt 2 failed after 1.096s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  Attempt 3/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 1 completed | rows=3 | latency=1.274s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 2 completed | rows=3 | latency=1.178s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
 Attempt 1 failed after 1.145s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  Attempt 2/3
 Attempt 2 failed after 1.048s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  Attempt 3/3
 Attempt 3 failed after 1.143s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 4 completed | rows=3 | latency=1.123s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
 Attempt 1 failed after 1.090s: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  Attempt 2/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 5 completed | rows=3 | latency=1.202s
------------------------------------------------------------


## Question 74

**Which pathways are associated with the DRD2 gene?**

In [79]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                         pathway_name
0      DRD2  Dopamine receptor signaling pathway

 Run 1 completed | rows=3 | latency=1.080s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                         pathway_name
0      DRD2  Dopamine receptor signaling pathway

 Run 2 completed | rows=3 | latency=0.894s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                         pathway_name
0      DRD2  Dopamine receptor signaling pathway

 Run 3 completed | rows=4 | latency=0.938s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                         pathway_name
0      DRD2  Dopamine receptor signaling pathway

 Run 4 completed | rows=3 | latency=1.184s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0      DRD2  Dopamine receptor signaling

 Run 5 completed | rows=4 | latency=0.944s
------------------------------------------------------------


## Question 75

**Which pathways are associated with the HTR2A gene?**

In [80]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                  pathway_name
0     HTR2A  Serotonin receptor signaling

 Run 1 completed | rows=3 | latency=1.197s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                  pathway_name
0     HTR2A  Serotonin receptor signaling

 Run 2 completed | rows=3 | latency=1.064s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name               pathway_name
0     HTR2A  5-HT2A receptor signaling

 Run 3 completed | rows=4 | latency=1.306s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name               pathway_name
0     HTR2A  5-HT2A receptor signaling

 Run 4 completed | rows=4 | latency=1.017s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name               pathway_name
0     HTR2A  5-HT2A receptor signaling

 Run 5 completed | rows=4 | latency=1.228s
------------------------------------------------------------


## Question 76

**Which drugs are associated with the CD19 gene?**

In [81]:

question = 'Which drugs are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,Tisagenlecleucel,CD19,CD19,CAR-T cell therapy targeting CD19,Approved

 Run 1 completed | rows=5 | latency=1.940s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,Blinatumomab,CD19,CD19,CD19/CD3 bispecific T-cell engager,Approved

 Run 2 completed | rows=7 | latency=2.122s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name target_name                 mechanism_of_action
0  Blinatumomab      CD19        CD19  CD19/CD3 bispecific T-cell engager

 Run 3 completed | rows=7 | latency=2.119s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,gene_name,approval_status,mechanism_of_action
0,Tisagenlecleucel,CD19,Approved,CD19-directed CAR T-cell therapy

 Run 4 completed | rows=7 | latency=2.944s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 6

,drug_name,gene_name,approval_status,mechanism_of_action
0,Tisagenlecleucel,CD19,Approved,CD19-directed CAR T-cell therapy

 Run 5 completed | rows=6 | latency=2.835s
------------------------------------------------------------


## Question 77

**Which drugs are associated with the CTLA4 gene?**

In [82]:

question = 'Which drugs are associated with the CTLA4 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name mechanism_of_action approval_status
0  Ipilimumab     CTLA4   CTLA-4 antagonist        Approved

 Run 1 completed | rows=2 | latency=0.923s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,Ipilimumab,CTLA4,CTLA4,CTLA4 monoclonal antibody inhibitor,Approved

 Run 2 completed | rows=2 | latency=1.226s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name         mechanism_of_action approval_status
0  Ipilimumab     CTLA4  CTLA-4 monoclonal antibody        Approved

 Run 3 completed | rows=2 | latency=1.047s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name         mechanism_of_action approval_status
0  Ipilimumab     CTLA4  CTLA-4 monoclonal antibody        Approved

 Run 4 completed | rows=2 | latency=0.998s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name                   mechanism_of_action approval_status
0  Ipilimumab     CTLA4  CTLA-4 monoclonal antibody inhibitor        Approved

 Run 5 completed | rows=2 | latency=0.896s
------------------------------------------------------------


## Question 78

**Which drugs are associated with the BTK gene?**

In [83]:

question = 'Which drugs are associated with the BTK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

   drug_name gene_name target_name mechanism_of_action approval_status
0  Ibrutinib       BTK         BTK       BTK inhibitor        Approved

 Run 1 completed | rows=4 | latency=1.879s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ibrutinib,Bruton tyrosine kinase,BTK,BTK inhibitor,Approved

 Run 2 completed | rows=4 | latency=1.397s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

   drug_name  gene_name  target_name  mechanism_of_action  approval_status
0  Ibrutinib        BTK          BTK        BTK inhibitor         Approved

 Run 3 completed | rows=4 | latency=1.249s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ibrutinib,Bruton tyrosine kinase,BTK,BTK inhibitor,Approved

 Run 4 completed | rows=4 | latency=1.906s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

   drug_name gene_name target_name mechanism_of_action approval_status
0  Ibrutinib       BTK         BTK       BTK inhibitor        Approved

 Run 5 completed | rows=4 | latency=2.856s
------------------------------------------------------------


## Question 79

**Which drugs are associated with the SYK gene?**

In [84]:

question = 'Which drugs are associated with the SYK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 3

      drug_name gene_name target_name approval_status mechanism_of_action
0  Fostamatinib       SYK         SYK        Approved       SYK inhibitor

 Run 1 completed | rows=3 | latency=1.296s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

      drug_name    drug_name.1 mechanism_of_action target_name  gene_name
0  Fostamatinib  Syk inhibitor                 SYK         SYK        NaN

 Run 2 completed | rows=2 | latency=1.219s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 3

      drug_name gene_name mechanism_of_action approval_status
0  Fostamatinib       SYK       SYK inhibitor        Approved

 Run 3 completed | rows=3 | latency=1.091s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 3

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,Fostamatinib,SYK,SYK,tyrosine kinase inhibitor,Approved

 Run 4 completed | rows=3 | latency=1.295s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 1

      drug_name gene_name mechanism_of_action approval_status
0  Fostamatinib       SYK       SYK inhibitor        Approved

 Run 5 completed | rows=1 | latency=0.858s
------------------------------------------------------------


## Question 80

**Which pathways are associated with TP53?**

In [85]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 1 completed | rows=1 | latency=0.824s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 2 completed | rows=1 | latency=0.748s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 3 completed | rows=1 | latency=0.861s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 4 completed | rows=1 | latency=0.847s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 5 completed | rows=1 | latency=0.783s
------------------------------------------------------------

##### Save as .pkl and json

In [ ]:
# import pickle
# with open("Grok_same_question_response.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

# import json
# import pandas as pd

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("Grok_same_question_response.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )