In [ ]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from biochatter_utility import return_biochatter_answer

In [ ]:
model = "BioChatter"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [3]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3

/home/abhishekh/anaconda3/envs/biochirp/lib/python3.11/site-packages/biochatter/llm_connect/conversation.py:34: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  from biochatter.selector_agent import RagAgentSelector

Entries retrieved: 7

  disease_name gene_name
0     Melanoma      BRAF

 Run 1 completed | rows=7 | latency=23.869s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 6

  disease_name gene_name
0     Melanoma      BRAF

 Run 2 completed | rows=6 | latency=17.251s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 6

  disease_name gene_name
0     Melanoma      BRAF

 Run 3 completed | rows=6 | latency=15.748s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 9

  disease_name gene_name
0     Melanoma      BRAF

 Run 4 completed | rows=9 | latency=20.546s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 7

  disease_name gene_name
0     Melanoma      BRAF

 Run 5 completed | rows=7 | latency=16.845s
------------------------------------------------------------


## Question 2

**List genes linked to amyotrophic lateral sclerosis.**

In [4]:

question = 'List genes linked to amyotrophic lateral sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 18

                    disease_name gene_name
0  Amyotrophic lateral sclerosis      SOD1

 Run 1 completed | rows=18 | latency=30.683s
------------------------------------------------------------

 Starting run 2 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 20

                    disease_name gene_name
0  Amyotrophic lateral sclerosis      SOD1

 Run 2 completed | rows=20 | latency=24.191s
------------------------------------------------------------

 Starting run 3 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 15

                    disease_name gene_name
0  Amyotrophic lateral sclerosis   C9orf72

 Run 3 completed | rows=15 | latency=20.179s
------------------------------------------------------------

 Starting run 4 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 15

                    disease_name gene_name
0  amyotrophic lateral sclerosis      SOD1

 Run 4 completed | rows=15 | latency=17.644s
------------------------------------------------------------

 Starting run 5 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 18

                    disease_name gene_name
0  Amyotrophic lateral sclerosis      SOD1

 Run 5 completed | rows=18 | latency=23.853s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [5]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 4

                      disease_name gene_name
0  Well-differentiated liposarcoma      CDK4

 Run 1 completed | rows=4 | latency=19.581s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 1

  disease_name gene_name
0     Melanoma      CDK4

 Run 2 completed | rows=1 | latency=16.066s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     melanoma

 Run 3 completed | rows=2 | latency=20.536s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     Melanoma      CDK4

 Run 4 completed | rows=3 | latency=21.496s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0     Melanoma      CDK4

 Run 5 completed | rows=2 | latency=20.744s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [6]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 1 completed | rows=1 | latency=14.394s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 2 completed | rows=3 | latency=13.275s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 3 completed | rows=1 | latency=12.136s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 4 completed | rows=1 | latency=14.018s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 6

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 5 completed | rows=6 | latency=18.740s
------------------------------------------------------------


## Question 5

**Which drugs are used for treating rheumatoid arthritis?**

In [7]:

question = 'Which drugs are used for treating rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  Rheumatoid arthritis  Methotrexate

 Run 1 completed | rows=17 | latency=20.045s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 20

      drug_name          disease_name approval_status
0  methotrexate  Rheumatoid arthritis        Approved

 Run 2 completed | rows=20 | latency=26.439s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  Rheumatoid arthritis  Methotrexate

 Run 3 completed | rows=17 | latency=25.498s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  Rheumatoid arthritis  Methotrexate

 Run 4 completed | rows=17 | latency=20.319s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 17

           disease_name     drug_name
0  Rheumatoid arthritis  Methotrexate

 Run 5 completed | rows=17 | latency=19.679s
------------------------------------------------------------


## Question 6

**What are the targets and mechanisms for dulaglutide?**

In [8]:

question = 'What are the targets and mechanisms for dulaglutide?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,dulaglutide,GLP-1 receptor,GLP1R,GLP-1 receptor agonist; enhances glucose-depen...,Approved

 Run 1 completed | rows=1 | latency=17.016s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,dulaglutide,GLP-1 receptor,GLP1R,GLP-1 receptor agonist; increases glucose-depe...,Approved

 Run 2 completed | rows=1 | latency=20.608s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,dulaglutide,glucagon-like peptide-1 receptor,GLP1R,GLP-1 receptor agonist; increases glucose-depe...,Approved

 Run 3 completed | rows=1 | latency=15.826s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,dulaglutide,GLP-1 receptor,GLP1R,GLP-1 receptor agonist; increases glucose-depe...,Approved

 Run 4 completed | rows=1 | latency=20.097s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,dulaglutide,glucagon-like peptide-1 receptor,GLP1R,GLP-1 receptor agonist; increases insulin secr...

 Run 5 completed | rows=1 | latency=20.870s
------------------------------------------------------------


## Question 7

**Provide target names for ovarian cancer?**

In [9]:

question = 'Provide target names for ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 2

  target_name    disease_name
0       PARP1  Ovarian cancer

 Run 1 completed | rows=2 | latency=20.744s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 2

     disease_name target_name
0  Ovarian cancer       PARP1

 Run 2 completed | rows=2 | latency=19.746s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

     disease_name target_name
0  Ovarian cancer       VEGFA

 Run 3 completed | rows=3 | latency=23.184s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 8

,disease_name,target_name,gene_name,mechanism_of_action
0,Ovarian cancer,PARP1,PARP1,DNA damage repair; PARP inhibition induces syn...

 Run 4 completed | rows=8 | latency=38.588s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 2

  target_name    disease_name
0       VEGFA  Ovarian cancer

 Run 5 completed | rows=2 | latency=15.234s
------------------------------------------------------------


## Question 8

**What are the known targets of regorafenib?**

In [10]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 8

     drug_name target_name gene_name         mechanism_of_action
0  regorafenib     VEGFR-2       KDR  tyrosine kinase inhibition

 Run 1 completed | rows=8 | latency=38.132s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 8

,,,,,,,,drug_name,target_name,gene_name,mechanism_of_action,approval_status
regorafenib,VEGFR-2,KDR,multikinase inhibitor targeting angiogenic,stromal,and oncogenic RTKs including VEGFR-2 (KDR),VEGFR-3 (FLT4),TIE2 (TEK),PDGFR-β (PDGFRB),KIT (KIT),RET and RAF kinases (CRAF/RAF1,BRAF),Approved

 Run 2 completed | rows=8 | latency=47.696s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

,drug_name,target_name,gene_name,mechanism_of_action
0,regorafenib,VEGFR-2,KDR,inhibits VEGFR-2 (KDR) tyrosine kinase activity

 Run 3 completed | rows=11 | latency=34.315s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name gene_name mechanism_of_action
0  Regorafenib     VEGFR-2       KDR   Kinase inhibition

 Run 4 completed | rows=11 | latency=38.277s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name target_name gene_name    mechanism_of_action
0  Regorafenib     VEGFR-2       KDR  multikinase inhibitor

 Run 5 completed | rows=9 | latency=45.034s
------------------------------------------------------------


## Question 9

**Which pathways are associated with the STAT3 gene?**

In [11]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 1 completed | rows=1 | latency=13.688s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 2 completed | rows=1 | latency=12.613s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 3 completed | rows=2 | latency=17.428s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 4 completed | rows=2 | latency=11.067s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 5 completed | rows=1 | latency=17.459s
------------------------------------------------------------


## Question 10

**Genes linked to fever.**

In [12]:

question = 'Genes linked to fever.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name                                mechanism_of_action
0        Fever      IL1B  pyrogenic cytokine; induces fever via IL-1 sig...

 Run 1 completed | rows=5 | latency=18.199s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 4

                   disease_name gene_name
0  Familial Mediterranean fever      MEFV

 Run 2 completed | rows=4 | latency=13.058s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 9

                   disease_name gene_name
0  Familial Mediterranean fever      MEFV

 Run 3 completed | rows=9 | latency=29.244s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 7

                             disease_name gene_name
0  Cryopyrin-associated periodic syndrome     NLRP3

 Run 4 completed | rows=7 | latency=33.675s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 4

                   disease_name gene_name
0  Familial Mediterranean Fever      MEFV

 Run 5 completed | rows=4 | latency=19.907s
------------------------------------------------------------


## Question 11

**List all drugs that target EGFR?**

In [13]:

question = 'List all drugs that target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 12

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibition,Approved

 Run 1 completed | rows=12 | latency=40.590s
------------------------------------------------------------

 Starting run 2 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibitor,Approved

 Run 2 completed | rows=8 | latency=40.299s
------------------------------------------------------------

 Starting run 3 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 12

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibitor,Approved

 Run 3 completed | rows=12 | latency=44.148s
------------------------------------------------------------

 Starting run 4 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,cetuximab,EGFR,EGFR,EGFR antagonist monoclonal antibody,Approved

 Run 4 completed | rows=8 | latency=30.635s
------------------------------------------------------------

 Starting run 5 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibitor,Approved

 Run 5 completed | rows=9 | latency=35.718s
------------------------------------------------------------


## Question 12

**Show drugs that inhibit the FGFR2 gene?**

In [14]:

question = 'Show drugs that inhibit the FGFR2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Erdafitinib,FGFR2,FGFR2,FGFR2 tyrosine kinase inhibitor,Approved

 Run 1 completed | rows=8 | latency=44.108s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 5

     drug_name target_name gene_name                 mechanism_of_action
0  Erdafitinib       FGFR2     FGFR2  pan-FGFR tyrosine kinase inhibitor

 Run 2 completed | rows=5 | latency=30.154s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

     drug_name target_name gene_name mechanism_of_action approval_status
0  Erdafitinib     FGFR1-4     FGFR2  FGFR1-4 inhibition        Approved

 Run 3 completed | rows=4 | latency=42.806s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,erdafitinib,FGFR2,FGFR2,pan-FGFR tyrosine kinase inhibition (FGFR1-4),Approved

 Run 4 completed | rows=4 | latency=29.813s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Erdafitinib,FGFR2,FGFR2,pan-FGFR tyrosine kinase inhibitor,Approved

 Run 5 completed | rows=4 | latency=38.970s
------------------------------------------------------------


## Question 13

**What diseases are treated with bevacizumab?**

In [15]:

question = 'What diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 9

     drug_name                  disease_name
0  bevacizumab  metastatic colorectal cancer

 Run 1 completed | rows=9 | latency=31.611s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name                  disease_name
0  bevacizumab  Metastatic colorectal cancer

 Run 2 completed | rows=6 | latency=23.267s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 8

        disease_name    drug_name approval_status
0  Colorectal cancer  bevacizumab        Approved

 Run 3 completed | rows=8 | latency=26.347s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name                  disease_name approval_status
0  Bevacizumab  metastatic colorectal cancer        Approved

 Run 4 completed | rows=6 | latency=27.692s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
 Attempt 1 failed after 30.710s: Error tokenizing data. C error: Expected 3 fields in line 5, saw 5

  Attempt 2/3
Entries retrieved: 6

        disease_name    drug_name
0  Colorectal cancer  bevacizumab

 Run 5 completed | rows=6 | latency=24.169s
------------------------------------------------------------


## Question 14

**List treatments for plaque psoriasis and their mechanisms.**

In [16]:

question = 'List treatments for plaque psoriasis and their mechanisms.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 15

,drug_name,disease_name,mechanism_of_action,approval_status
0,Methotrexate,Plaque psoriasis,Inhibits dihydrofolate reductase; anti-prolife...,Approved

 Run 1 completed | rows=15 | latency=59.456s
------------------------------------------------------------

 Starting run 2 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 14

,drug_name,disease_name,target_name,gene_name,biomarker_name,pathway_name,approval_status,mechanism_of_action
0,methotrexate,Plaque psoriasis,DHFR,DHFR,NaN,Folate metabolism,Approved,folate antagonist; inhibits dihydrofolate redu...

 Run 2 completed | rows=14 | latency=46.586s
------------------------------------------------------------

 Starting run 3 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 16

,drug_name,disease_name,target_name,gene_name,approval_status,mechanism_of_action
0,Clobetasol propionate,plaque psoriasis,Glucocorticoid receptor,NR3C1,Approved,Activates glucocorticoid receptor; suppresses ...

 Run 3 completed | rows=16 | latency=60.066s
------------------------------------------------------------

 Starting run 4 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 15

    drug_name      disease_name  mechanism_of_action approval_status
0  etanercept  Plaque psoriasis      TNF-α inhibitor        Approved

 Run 4 completed | rows=15 | latency=30.028s
------------------------------------------------------------

 Starting run 5 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
 Attempt 1 failed after 39.509s: Error tokenizing data. C error: Expected 4 fields in line 8, saw 5

  Attempt 2/3
Entries retrieved: 14

,drug_name,disease_name,mechanism_of_action,approval_status
0,clobetasol propionate,Plaque psoriasis,Glucocorticoid receptor agonism; anti-inflamma...,Approved

 Run 5 completed | rows=14 | latency=53.527s
------------------------------------------------------------


## Question 15

**What are the known targets of cabozantinib?**

In [17]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action
0,cabozantinib,MET,MET,Inhibits MET receptor tyrosine kinase activity

 Run 1 completed | rows=5 | latency=25.199s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

,,,,drug_name,target_name,gene_name,mechanism_of_action
cabozantinib,MET,MET,Multikinase tyrosine kinase inhibitor targeting MET,VEGFR2,AXL,ROS1,and RET

 Run 2 completed | rows=5 | latency=21.469s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name target_name gene_name                     mechanism_of_action
0  cabozantinib         MET       MET  multi-kinase tyrosine kinase inhibitor

 Run 3 completed | rows=6 | latency=23.893s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,cabozantinib,MET,MET,MET tyrosine kinase inhibition,Approved

 Run 4 completed | rows=5 | latency=28.451s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name target_name gene_name        mechanism_of_action
0  cabozantinib         MET       MET  tyrosine kinase inhibitor

 Run 5 completed | rows=5 | latency=24.266s
------------------------------------------------------------


## Question 16

**Show drugs that inhibit the RET gene?**

In [18]:

question = 'Show drugs that inhibit the RET gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,selpercatinib,RET proto-oncogene,RET,RET tyrosine kinase inhibition,Approved

 Run 1 completed | rows=4 | latency=24.105s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Pralsetinib,RET tyrosine kinase,RET,RET tyrosine kinase inhibition,Approved

 Run 2 completed | rows=4 | latency=21.098s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
 Attempt 1 failed after 27.792s: Error tokenizing data. C error: Expected 6 fields in line 5, saw 7

  Attempt 2/3
 Attempt 2 failed after 25.960s: Error tokenizing data. C error: Expected 5 fields in line 4, saw 7

  Attempt 3/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Selpercatinib,RET tyrosine kinase,RET,Selective inhibition of RET tyrosine kinase,Approved

 Run 3 completed | rows=4 | latency=26.402s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,selpercatinib,RET,RET,Selective RET tyrosine kinase inhibitor,Approved

 Run 4 completed | rows=5 | latency=17.669s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Selpercatinib,RET tyrosine kinase,RET,selective RET kinase inhibitor,Approved

 Run 5 completed | rows=5 | latency=15.226s
------------------------------------------------------------


## Question 17

**Which pathways are associated with the TNF gene?**

In [19]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 1 completed | rows=4 | latency=13.646s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 2 completed | rows=3 | latency=17.676s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 3 completed | rows=5 | latency=13.406s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name           pathway_name
0       TNF  TNF signaling pathway

 Run 4 completed | rows=5 | latency=12.701s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name           pathway_name
0       TNF  TNF signaling pathway

 Run 5 completed | rows=6 | latency=15.863s
------------------------------------------------------------


## Question 18

**Diseases associated with the gene NPM1.**

In [20]:

question = 'Diseases associated with the gene NPM1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 1 completed | rows=1 | latency=14.630s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 2 completed | rows=1 | latency=10.162s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 3 completed | rows=1 | latency=12.972s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

                               disease_name gene_name
0  Acute myeloid leukemia with mutated NPM1      NPM1

 Run 4 completed | rows=1 | latency=11.920s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 5 completed | rows=1 | latency=10.742s
------------------------------------------------------------


## Question 19

**Which pathways are associated with the CD19 gene?**

In [21]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 1 completed | rows=2 | latency=13.303s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 2 completed | rows=2 | latency=13.130s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 3 completed | rows=2 | latency=11.826s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B-cell receptor signaling pathway      CD19

 Run 4 completed | rows=2 | latency=12.489s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 5 completed | rows=2 | latency=12.282s
------------------------------------------------------------


## Question 20

**Which drugs are used for treating migraine?**

In [22]:

question = 'Which drugs are used for treating migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 14

     drug_name disease_name
0  sumatriptan     Migraine

 Run 1 completed | rows=14 | latency=22.276s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 14

  disease_name    drug_name
0     Migraine  sumatriptan

 Run 2 completed | rows=14 | latency=33.191s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 12

     drug_name disease_name         mechanism_of_action approval_status
0  Sumatriptan     Migraine  5-HT1B/1D receptor agonist        Approved

 Run 3 completed | rows=12 | latency=26.638s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 21

     drug_name disease_name approval_status
0  sumatriptan     Migraine        Approved

 Run 4 completed | rows=21 | latency=37.819s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 21

  disease_name    drug_name
0     migraine  sumatriptan

 Run 5 completed | rows=21 | latency=35.820s
------------------------------------------------------------


## Question 21

**What are the targets and mechanisms for rituximab?**

In [23]:

question = 'What are the targets and mechanisms for rituximab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,rituximab,CD20,MS4A1,binds CD20 on B cells; mediates B-cell depleti...

 Run 1 completed | rows=1 | latency=12.742s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Rituximab,CD20,MS4A1,ADCC; CDC; induction of apoptosis,Approved

 Run 2 completed | rows=1 | latency=14.535s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,Rituximab,CD20,MS4A1,Binds CD20 on B cells; mediates depletion via ...

 Run 3 completed | rows=1 | latency=13.111s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Rituximab,CD20,MS4A1,B-cell depletion via complement-dependent cyto...,Approved

 Run 4 completed | rows=1 | latency=18.952s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Rituximab,CD20,MS4A1,binding CD20 on B cells; activates complement-...,Approved

 Run 5 completed | rows=1 | latency=19.472s
------------------------------------------------------------


## Question 22

**Provide target names for colorectal cancer?**

In [24]:

question = 'Provide target names for colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 4

        disease_name target_name
0  Colorectal cancer        EGFR

 Run 1 completed | rows=4 | latency=19.551s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action,disease_name,approval_status
0,Bevacizumab,VEGFA,VEGFA,Monoclonal antibody against VEGF-A; inhibits a...,Colorectal cancer,Approved

 Run 2 completed | rows=4 | latency=31.598s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name
0        EGFR

 Run 3 completed | rows=5 | latency=19.853s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 10

  target_name
0        EGFR

 Run 4 completed | rows=10 | latency=33.453s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name target_name gene_name
0  Colorectal cancer        EGFR      EGFR

 Run 5 completed | rows=5 | latency=23.745s
------------------------------------------------------------


## Question 23

**Which are possible drugs against rickets?**

In [25]:

question = 'Which are possible drugs against rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

  disease_name        drug_name
0      Rickets  cholecalciferol

 Run 1 completed | rows=4 | latency=17.299s
------------------------------------------------------------

 Starting run 2 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 6

,drug_name,disease_name,approval_status,mechanism_of_action
0,cholecalciferol,Rickets,Approved,Vitamin D receptor activation; increases intes...

 Run 2 completed | rows=6 | latency=38.975s
------------------------------------------------------------

 Starting run 3 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 2

  disease_name        drug_name
0      Rickets  Cholecalciferol

 Run 3 completed | rows=2 | latency=14.538s
------------------------------------------------------------

 Starting run 4 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

  disease_name        drug_name approval_status
0      rickets  cholecalciferol        Approved

 Run 4 completed | rows=4 | latency=25.816s
------------------------------------------------------------

 Starting run 5 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

,drug_name,disease_name,mechanism_of_action,approval_status
0,cholecalciferol,rickets,Vitamin D receptor activation; increases intes...,Approved

 Run 5 completed | rows=4 | latency=34.816s
------------------------------------------------------------


## Question 24

**Give me genes linked to epilepsy.**

In [26]:

question = 'Give me genes linked to epilepsy.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 26

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 1 completed | rows=26 | latency=21.481s
------------------------------------------------------------

 Starting run 2 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 24

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 2 completed | rows=24 | latency=28.110s
------------------------------------------------------------

 Starting run 3 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 19

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 3 completed | rows=19 | latency=14.810s
------------------------------------------------------------

 Starting run 4 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 20

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 4 completed | rows=20 | latency=17.329s
------------------------------------------------------------

 Starting run 5 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 19

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 5 completed | rows=19 | latency=19.709s
------------------------------------------------------------


## Question 25

**What diseases are treated with trastuzumab deruxtecan?**

In [27]:

question = 'What diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                  disease_name               drug_name approval_status
0  HER2-positive breast cancer  trastuzumab deruxtecan        Approved

 Run 1 completed | rows=2 | latency=10.830s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                            disease_name
0  trastuzumab deruxtecan  metastatic HER2-positive breast cancer

 Run 2 completed | rows=2 | latency=21.497s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                             disease_name               drug_name
0  Metastatic HER2-positive breast cancer  trastuzumab deruxtecan

 Run 3 completed | rows=2 | latency=14.582s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                             disease_name               drug_name
0  Metastatic HER2-positive breast cancer  trastuzumab deruxtecan

 Run 4 completed | rows=2 | latency=14.176s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name                 disease_name approval_status
0  trastuzumab deruxtecan  HER2-positive breast cancer        Approved

 Run 5 completed | rows=2 | latency=20.262s
------------------------------------------------------------


## Question 26

**Genes linked to Alzheimer’s disease.**

In [28]:

question = 'Genes linked to Alzheimer’s disease.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 11

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 1 completed | rows=11 | latency=13.530s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 14

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 2 completed | rows=14 | latency=15.442s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 12

          disease_name gene_name
0  Alzheimer's disease      APOE

 Run 3 completed | rows=12 | latency=13.682s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 19

          disease_name gene_name
0  Alzheimer's disease       APP

 Run 4 completed | rows=19 | latency=13.151s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 18

          disease_name gene_name
0  Alzheimer's disease      APOE

 Run 5 completed | rows=18 | latency=15.553s
------------------------------------------------------------


## Question 27

**For which disease is darolutamide used?**

In [29]:

question = 'For which disease is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  nonmetastatic castration-resistant prostate ca...

 Run 1 completed | rows=1 | latency=8.430s
------------------------------------------------------------

 Starting run 2 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

,drug_name,disease_name,approval_status
0,darolutamide,non-metastatic castration-resistant prostate c...,Approved

 Run 2 completed | rows=1 | latency=5.876s
------------------------------------------------------------

 Starting run 3 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  Nonmetastatic castration-resistant prostate ca...

 Run 3 completed | rows=1 | latency=7.478s
------------------------------------------------------------

 Starting run 4 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name                                       disease_name
0  darolutamide  non-metastatic castration-resistant prostate c...

 Run 4 completed | rows=1 | latency=8.533s
------------------------------------------------------------

 Starting run 5 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

,drug_name,disease_name,approval_status
0,darolutamide,Non-metastatic castration-resistant prostate c...,Approved

 Run 5 completed | rows=1 | latency=10.966s
------------------------------------------------------------


## Question 28

**Provide target names for renal cell carcinoma?**

In [30]:

question = 'Provide target names for renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 6

           disease_name target_name gene_name approval_status
0  Renal cell carcinoma     VEGFR-2       KDR        Approved

 Run 1 completed | rows=6 | latency=33.105s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 13

           disease_name target_name
0  Renal cell carcinoma         KDR

 Run 2 completed | rows=13 | latency=27.365s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 15

           disease_name target_name
0  Renal cell carcinoma         KDR

 Run 3 completed | rows=15 | latency=26.883s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 12

           disease_name target_name
0  Renal cell carcinoma         KDR

 Run 4 completed | rows=12 | latency=24.620s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 12

           disease_name target_name gene_name
0  Renal cell carcinoma       VEGFA     VEGFA

 Run 5 completed | rows=12 | latency=26.893s
------------------------------------------------------------


## Question 29

**Diseases associated with the gene KRAS.**

In [31]:

question = 'Diseases associated with the gene KRAS.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 9

      disease_name gene_name
0  Noonan syndrome      KRAS

 Run 1 completed | rows=9 | latency=23.654s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 6

      disease_name gene_name
0  Noonan syndrome      KRAS

 Run 2 completed | rows=6 | latency=16.829s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 5

                       disease_name gene_name
0  Pancreatic ductal adenocarcinoma      KRAS

 Run 3 completed | rows=5 | latency=12.335s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 6

                       disease_name gene_name
0  Pancreatic ductal adenocarcinoma      KRAS

 Run 4 completed | rows=6 | latency=19.170s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 4

                       disease_name gene_name
0  Pancreatic ductal adenocarcinoma      KRAS

 Run 5 completed | rows=4 | latency=13.574s
------------------------------------------------------------


## Question 30

**Which pathways are associated with the APP gene?**

In [32]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

,pathway_name,gene_name,mechanism_of_action
0,Amyloid precursor protein processing,APP,beta- and gamma-secretase-mediated proteolysis...

 Run 1 completed | rows=2 | latency=21.305s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

                pathway_name gene_name
0  Alzheimer disease pathway       APP

 Run 2 completed | rows=1 | latency=13.037s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name               pathway_name
0       APP  Alzheimer disease pathway

 Run 3 completed | rows=1 | latency=19.805s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

                pathway_name gene_name
0  Alzheimer disease pathway       APP

 Run 4 completed | rows=1 | latency=12.852s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name               pathway_name
0       APP  Alzheimer disease pathway

 Run 5 completed | rows=1 | latency=15.715s
------------------------------------------------------------


## Question 31

**Genes linked to schizophrenia.**

In [33]:

question = 'Genes linked to schizophrenia.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 14

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 1 completed | rows=14 | latency=14.214s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 8

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 2 completed | rows=8 | latency=13.428s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 16

    disease_name gene_name
0  schizophrenia     DISC1

 Run 3 completed | rows=16 | latency=17.438s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 8

    disease_name gene_name
0  Schizophrenia      COMT

 Run 4 completed | rows=8 | latency=12.273s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia   CACNA1C

 Run 5 completed | rows=5 | latency=15.303s
------------------------------------------------------------


## Question 32

**What diseases are treated with valdecoxib?**

In [34]:

question = 'What diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

     disease_name   drug_name
0  Osteoarthritis  Valdecoxib

 Run 1 completed | rows=2 | latency=18.550s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 1

     disease_name   drug_name
0  Osteoarthritis  valdecoxib

 Run 2 completed | rows=1 | latency=12.102s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 1

     disease_name   drug_name
0  osteoarthritis  valdecoxib

 Run 3 completed | rows=1 | latency=14.590s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

     disease_name   drug_name
0  Osteoarthritis  valdecoxib

 Run 4 completed | rows=2 | latency=17.529s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 3

    drug_name    disease_name approval_status
0  valdecoxib  osteoarthritis       Withdrawn

 Run 5 completed | rows=3 | latency=18.168s
------------------------------------------------------------


## Question 33

**What are the known targets of vandetanib?**

In [35]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,Vandetanib,Vascular endothelial growth factor receptor 2,KDR,Inhibits VEGFR-2 tyrosine kinase activity

 Run 1 completed | rows=4 | latency=20.877s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name gene_name        mechanism_of_action approval_status
0  vandetanib     VEGFR-2       KDR  tyrosine kinase inhibitor        Approved

 Run 2 completed | rows=4 | latency=22.199s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name gene_name                   mechanism_of_action
0  vandetanib     VEGFR-2       KDR  tyrosine kinase inhibitor of VEGFR-2

 Run 3 completed | rows=4 | latency=21.150s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name gene_name              mechanism_of_action
0  vandetanib        EGFR      EGFR  EGFR tyrosine kinase inhibition

 Run 4 completed | rows=3 | latency=22.098s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name gene_name                       mechanism_of_action
0  vandetanib      VEGFR2       KDR  Inhibits VEGFR2 tyrosine kinase activity

 Run 5 completed | rows=3 | latency=24.771s
------------------------------------------------------------


## Question 34

**Which pathways are associated with the CFTR gene?**

In [36]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 1 completed | rows=1 | latency=15.966s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 2

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 2 completed | rows=2 | latency=13.526s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 2

       pathway_name gene_name
0  ABC transporters      CFTR

 Run 3 completed | rows=2 | latency=21.182s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 4 completed | rows=2 | latency=18.526s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 3

             pathway_name gene_name
0  cAMP signaling pathway      CFTR

 Run 5 completed | rows=3 | latency=21.338s
------------------------------------------------------------


## Question 35

**Which drugs are used for TB?**

In [37]:

question = 'Which drugs are used for TB?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 21

   drug_name  disease_name
0  isoniazid  tuberculosis

 Run 1 completed | rows=21 | latency=30.091s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 4

   disease_name  drug_name
0  Tuberculosis  isoniazid

 Run 2 completed | rows=4 | latency=13.622s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 8

   disease_name  drug_name
0  Tuberculosis  Isoniazid

 Run 3 completed | rows=8 | latency=19.927s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 5

   drug_name  disease_name approval_status
0  isoniazid  Tuberculosis        Approved

 Run 4 completed | rows=5 | latency=11.876s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 21

   drug_name  disease_name
0  isoniazid  Tuberculosis

 Run 5 completed | rows=21 | latency=22.631s
------------------------------------------------------------


## Question 36

**Which drugs are used for pancreatic adenocarcinoma?**

In [38]:

question = 'Which drugs are used for pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 1 completed | rows=8 | latency=34.754s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name                      disease_name approval_status
0  gemcitabine  Pancreatic ductal adenocarcinoma        Approved

 Run 2 completed | rows=5 | latency=49.279s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 4

     drug_name               disease_name approval_status
0  gemcitabine  Pancreatic adenocarcinoma        Approved

 Run 3 completed | rows=4 | latency=43.334s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 4

     drug_name               disease_name approval_status
0  Gemcitabine  Pancreatic adenocarcinoma        Approved

 Run 4 completed | rows=4 | latency=50.908s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 8

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 5 completed | rows=8 | latency=39.572s
------------------------------------------------------------


## Question 37

**Which drugs are used in chronic myeloid leukemia?**

In [39]:

question = 'Which drugs are used in chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name
0  Chronic myeloid leukemia  imatinib

 Run 1 completed | rows=6 | latency=24.481s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name
0  Chronic myeloid leukemia  Imatinib

 Run 2 completed | rows=6 | latency=17.795s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
 Attempt 1 failed after 28.109s: Error tokenizing data. C error: Expected 4 fields in line 6, saw 8

  Attempt 2/3
Entries retrieved: 5

               disease_name drug_name approval_status
0  Chronic myeloid leukemia  Imatinib        Approved

 Run 3 completed | rows=5 | latency=18.486s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 6

               disease_name drug_name approval_status
0  Chronic myeloid leukemia  imatinib        Approved

 Run 4 completed | rows=6 | latency=14.312s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

               disease_name drug_name approval_status
0  Chronic myeloid leukemia  imatinib        Approved

 Run 5 completed | rows=5 | latency=12.852s
------------------------------------------------------------


## Question 38

**What drugs are used in the treatment of Parkinson’s disease?**

In [40]:

question = 'What drugs are used in the treatment of Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 17

          disease_name  drug_name
0  Parkinson's disease   Levodopa

 Run 1 completed | rows=17 | latency=26.461s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 13

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 2 completed | rows=13 | latency=32.658s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 19

          disease_name drug_name approval_status
0  Parkinson's disease  Levodopa        Approved

 Run 3 completed | rows=19 | latency=34.602s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 15

          disease_name drug_name
0  Parkinson's disease  Levodopa

 Run 4 completed | rows=15 | latency=21.695s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 18

          disease_name drug_name
0  Parkinson's disease  levodopa

 Run 5 completed | rows=18 | latency=34.750s
------------------------------------------------------------


## Question 39

**Which drugs are used for inflammatory bowel disease?**

In [41]:

question = 'Which drugs are used for inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 29

    drug_name        disease_name
0  Mesalamine  Ulcerative colitis

 Run 1 completed | rows=29 | latency=47.914s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 14

    drug_name                disease_name approval_status
0  mesalamine  Inflammatory bowel disease        Approved

 Run 2 completed | rows=14 | latency=35.435s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 26

         disease_name   drug_name
0  Ulcerative colitis  mesalamine

 Run 3 completed | rows=26 | latency=33.773s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 12

,drug_name,disease_name,approval_status,mechanism_of_action
0,mesalamine,Inflammatory bowel disease,Approved,5-aminosalicylic acid anti-inflammatory; reduc...

 Run 4 completed | rows=12 | latency=37.833s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 16

                 disease_name   drug_name
0  Inflammatory bowel disease  Mesalazine

 Run 5 completed | rows=16 | latency=40.625s
------------------------------------------------------------


## Question 40

**What targets are acted on by imatinib?**

In [42]:

question = 'What targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,gene_name,target_name,mechanism_of_action
0,imatinib,ABL1,ABL1,tyrosine kinase inhibitor of ABL1 (BCR-ABL1)

 Run 1 completed | rows=4 | latency=23.751s
------------------------------------------------------------

 Starting run 2 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 5

  drug_name target_name gene_name        mechanism_of_action
0  imatinib    BCR-ABL1      ABL1  tyrosine kinase inhibitor

 Run 2 completed | rows=5 | latency=21.383s
------------------------------------------------------------

 Starting run 3 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name target_name gene_name        mechanism_of_action approval_status
0  Imatinib    BCR-ABL1      ABL1  tyrosine kinase inhibitor        Approved

 Run 3 completed | rows=4 | latency=14.303s
------------------------------------------------------------

 Starting run 4 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,mechanism_of_action
0,imatinib,BCR-ABL1 fusion protein,ABL1,Tyrosine kinase inhibition of BCR-ABL1 fusion ...

 Run 4 completed | rows=4 | latency=22.447s
------------------------------------------------------------

 Starting run 5 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name target_name gene_name                         mechanism_of_action
0  imatinib    BCR-ABL1      ABL1  inhibits BCR-ABL1 tyrosine kinase activity

 Run 5 completed | rows=4 | latency=20.069s
------------------------------------------------------------


## Question 41

**What biological targets does sorafenib interact with?**

In [43]:

question = 'What biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 9

   drug_name target_name gene_name            mechanism_of_action
0  sorafenib        BRAF      BRAF  inhibits BRAF kinase activity

 Run 1 completed | rows=9 | latency=32.610s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name               mechanism_of_action
0  sorafenib        RAF1      RAF1  inhibits RAF kinases (CRAF/RAF1)

 Run 2 completed | rows=8 | latency=35.244s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,sorafenib,RAF1 (CRAF),RAF1,inhibits RAF1 kinase activity,Approved

 Run 3 completed | rows=8 | latency=45.045s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name                        mechanism_of_action
0  Sorafenib        BRAF      BRAF  inhibits RAF kinases (CRAF/RAF1 and BRAF)

 Run 4 completed | rows=8 | latency=38.505s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name     mechanism_of_action
0  sorafenib        RAF1      RAF1  RAF1 kinase inhibition

 Run 5 completed | rows=8 | latency=33.422s
------------------------------------------------------------


## Question 42

**What biological targets does tofacitinib affect?**

In [44]:

question = 'What biological targets does tofacitinib affect?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action
0,tofacitinib,Janus kinase 1,JAK1,inhibits JAK1; blocks JAK-STAT signaling

 Run 1 completed | rows=3 | latency=22.145s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name target_name gene_name                       mechanism_of_action
0  tofacitinib        JAK1      JAK1  Inhibits JAK1 signaling (JAK1 inhibitor)

 Run 2 completed | rows=3 | latency=23.790s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 2

     drug_name     target_name gene_name      mechanism_of_action
0  tofacitinib  Janus kinase 1      JAK1  inhibits JAK1 signaling

 Run 3 completed | rows=2 | latency=19.096s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 2

     drug_name target_name gene_name  mechanism_of_action approval_status
0  tofacitinib        JAK1      JAK1  JAK1/JAK3 inhibitor        Approved

 Run 4 completed | rows=2 | latency=18.620s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action
0,Tofacitinib,Janus kinase 1,JAK1,ATP-competitive inhibitor of JAK kinases with ...

 Run 5 completed | rows=3 | latency=25.488s
------------------------------------------------------------


## Question 43

**Which drugs are known to target EGFR?**

In [45]:

question = 'Which drugs are known to target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibitor,Approved

 Run 1 completed | rows=9 | latency=25.509s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 10

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Gefitinib,EGFR,EGFR,EGFR tyrosine kinase inhibition; selective for...,Approved

 Run 2 completed | rows=10 | latency=27.584s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 11

   drug_name target_name gene_name              mechanism_of_action
0  gefitinib        EGFR      EGFR  EGFR tyrosine kinase inhibition

 Run 3 completed | rows=11 | latency=27.483s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 8

   drug_name target_name gene_name             mechanism_of_action
0  gefitinib        EGFR      EGFR  EGFR tyrosine kinase inhibitor

 Run 4 completed | rows=8 | latency=28.504s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,cetuximab,EGFR,EGFR,monoclonal antibody targeting EGFR,Approved

 Run 5 completed | rows=9 | latency=30.381s
------------------------------------------------------------


## Question 44

**Which diseases are linked to the TP53?**

In [46]:

question = 'Which diseases are linked to the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 1 completed | rows=1 | latency=19.588s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 7

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 2 completed | rows=7 | latency=19.979s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 3 completed | rows=1 | latency=10.985s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 4 completed | rows=1 | latency=16.594s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 5 completed | rows=6 | latency=18.621s
------------------------------------------------------------


## Question 45

**Which diseases are associated with FGFR2?**

In [47]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 6

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 1 completed | rows=6 | latency=12.635s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 2 completed | rows=8 | latency=23.437s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 10

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 3 completed | rows=10 | latency=18.253s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 4 completed | rows=9 | latency=23.470s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 7

     disease_name gene_name
0  Apert syndrome     FGFR2

 Run 5 completed | rows=7 | latency=21.826s
------------------------------------------------------------


## Question 46

**Which diseases are linked to the HTT?**

In [48]:

question = 'Which diseases are linked to the HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 1 completed | rows=1 | latency=8.118s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 2 completed | rows=1 | latency=8.744s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 3 completed | rows=1 | latency=12.919s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 4 completed | rows=1 | latency=8.854s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

           disease_name gene_name
0  Huntington's disease       HTT

 Run 5 completed | rows=1 | latency=12.279s
------------------------------------------------------------


## Question 47

**Which genes are associated with breast cancer?**

In [49]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 10

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 1 completed | rows=10 | latency=10.922s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 11

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 2 completed | rows=11 | latency=12.751s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 18

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 3 completed | rows=18 | latency=14.651s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 16

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 4 completed | rows=16 | latency=14.313s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 14

    disease_name gene_name
0  Breast cancer     BRCA1

 Run 5 completed | rows=14 | latency=14.535s
------------------------------------------------------------


## Question 48

**Which genes are associated with colorectal cancer?**

In [50]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 16

        disease_name gene_name
0  Colorectal cancer       APC

 Run 1 completed | rows=16 | latency=10.306s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 16

        disease_name gene_name
0  Colorectal cancer       APC

 Run 2 completed | rows=16 | latency=15.949s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  Colorectal cancer       APC

 Run 3 completed | rows=14 | latency=14.988s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  Colorectal cancer       APC

 Run 4 completed | rows=14 | latency=17.659s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 14

        disease_name gene_name
0  Colorectal cancer       APC

 Run 5 completed | rows=14 | latency=11.854s
------------------------------------------------------------


## Question 49

**What genes are linked to cystic fibrosis?**

In [51]:

question = 'What genes are linked to cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 1 completed | rows=1 | latency=9.695s
------------------------------------------------------------

 Starting run 2 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 2 completed | rows=1 | latency=9.883s
------------------------------------------------------------

 Starting run 3 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 3 completed | rows=1 | latency=7.247s
------------------------------------------------------------

 Starting run 4 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 3

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 4 completed | rows=3 | latency=9.043s
------------------------------------------------------------

 Starting run 5 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 5 completed | rows=1 | latency=7.048s
------------------------------------------------------------


## Question 50

**What drugs are used in glioblastoma?**

In [52]:

question = 'What drugs are used in glioblastoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 4

   disease_name     drug_name
0  Glioblastoma  Temozolomide

 Run 1 completed | rows=4 | latency=11.103s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 3

      drug_name  disease_name
0  temozolomide  Glioblastoma

 Run 2 completed | rows=3 | latency=22.449s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 3

,drug_name,disease_name,mechanism_of_action,approval_status
0,Temozolomide,Glioblastoma,DNA alkylating agent; methylates DNA at O6-pos...,Approved

 Run 3 completed | rows=3 | latency=26.504s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 3

,drug_name,disease_name,approval_status,mechanism_of_action
0,temozolomide,glioblastoma,Approved,alkylating agent; methylates DNA at O6-guanine

 Run 4 completed | rows=3 | latency=29.212s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 3

      drug_name  disease_name
0  temozolomide  glioblastoma

 Run 5 completed | rows=3 | latency=30.155s
------------------------------------------------------------


## Question 51

**Which diseases are treated by metformin?**

In [53]:

question = 'Which diseases are treated by metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  Type 2 diabetes mellitus        Approved

 Run 1 completed | rows=1 | latency=22.506s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name approval_status
0  Type 2 diabetes mellitus  metformin        Approved

 Run 2 completed | rows=1 | latency=10.869s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  Type 2 diabetes mellitus        Approved

 Run 3 completed | rows=1 | latency=9.912s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name approval_status
0  metformin  Type 2 diabetes mellitus        Approved

 Run 4 completed | rows=1 | latency=9.891s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 1

               disease_name  drug_name
0  Type 2 diabetes mellitus  metformin

 Run 5 completed | rows=1 | latency=14.636s
------------------------------------------------------------


## Question 52

**What conditions is adalimumab used for?**

In [54]:

question = 'What conditions is adalimumab used for?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 1 completed | rows=9 | latency=18.311s
------------------------------------------------------------

 Starting run 2 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name approval_status
0  adalimumab  Rheumatoid arthritis        Approved

 Run 2 completed | rows=9 | latency=14.481s
------------------------------------------------------------

 Starting run 3 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name approval_status
0  adalimumab  Rheumatoid arthritis        Approved

 Run 3 completed | rows=9 | latency=19.562s
------------------------------------------------------------

 Starting run 4 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  rheumatoid arthritis

 Run 4 completed | rows=9 | latency=14.230s
------------------------------------------------------------

 Starting run 5 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name
0  adalimumab  Rheumatoid arthritis

 Run 5 completed | rows=9 | latency=14.304s
------------------------------------------------------------


## Question 53

**Which diseases are pembrolizumab used in?**

In [55]:

question = 'Which diseases are pembrolizumab used in?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 7

  disease_name      drug_name approval_status
0     Melanoma  pembrolizumab        Approved

 Run 1 completed | rows=7 | latency=17.681s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 2 completed | rows=9 | latency=24.946s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name approval_status
0  pembrolizumab     Melanoma        Approved

 Run 3 completed | rows=9 | latency=26.841s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 8

  disease_name      drug_name
0     Melanoma  pembrolizumab

 Run 4 completed | rows=8 | latency=24.499s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 7

  disease_name      drug_name
0     Melanoma  pembrolizumab

 Run 5 completed | rows=7 | latency=20.474s
------------------------------------------------------------


## Question 54

**Which diseases are treated with sorafenib?**

In [56]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name          disease_name
0  sorafenib  Renal cell carcinoma

 Run 1 completed | rows=3 | latency=9.729s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  sorafenib  Hepatocellular carcinoma

 Run 2 completed | rows=3 | latency=11.114s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  Hepatocellular carcinoma

 Run 3 completed | rows=3 | latency=7.988s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  hepatocellular carcinoma  sorafenib

 Run 4 completed | rows=3 | latency=8.450s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

               disease_name  drug_name
0  Hepatocellular carcinoma  sorafenib

 Run 5 completed | rows=3 | latency=8.652s
------------------------------------------------------------


## Question 55

**What diseases are treated with nivolumab?**

In [57]:

question = 'What diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

          disease_name  drug_name
0  Metastatic melanoma  nivolumab

 Run 1 completed | rows=8 | latency=22.586s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name disease_name approval_status
0  nivolumab     Melanoma        Approved

 Run 2 completed | rows=7 | latency=16.707s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 7

   drug_name        disease_name approval_status
0  nivolumab  Malignant melanoma        Approved

 Run 3 completed | rows=7 | latency=18.319s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

   drug_name disease_name approval_status
0  nivolumab     Melanoma        Approved

 Run 4 completed | rows=8 | latency=17.812s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

  disease_name  drug_name
0     Melanoma  nivolumab

 Run 5 completed | rows=8 | latency=11.275s
------------------------------------------------------------


## Question 56

**Genes linked to multiple sclerosis.**

In [58]:

question = 'Genes linked to multiple sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 1 completed | rows=4 | latency=10.885s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 2 completed | rows=5 | latency=20.429s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 8

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 3 completed | rows=8 | latency=16.454s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple sclerosis  HLA-DRB1

 Run 4 completed | rows=5 | latency=13.971s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 9

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 5 completed | rows=9 | latency=15.214s
------------------------------------------------------------


## Question 57

**Provide target names for rheumatoid arthritis.**

In [59]:

question = 'Provide target names for rheumatoid arthritis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 8

           disease_name target_name
0  Rheumatoid arthritis         TNF

 Run 1 completed | rows=8 | latency=18.171s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 8

  target_name
0         TNF

 Run 2 completed | rows=8 | latency=16.233s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 9

  target_name gene_name          disease_name
0         TNF       TNF  Rheumatoid arthritis

 Run 3 completed | rows=9 | latency=24.122s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 10

  target_name
0         TNF

 Run 4 completed | rows=10 | latency=33.991s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 17

    drug_name target_name gene_name       mechanism_of_action approval_status
0  infliximab         TNF       TNF  TNF-alpha neutralization        Approved

 Run 5 completed | rows=17 | latency=45.429s
------------------------------------------------------------


## Question 58

**What are the targets of abatacept?**

In [60]:

question = 'What are the targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,abatacept,CD80,CD80,binds CD80 and CD86 to inhibit CD28-mediated T...

 Run 1 completed | rows=2 | latency=14.481s
------------------------------------------------------------

 Starting run 2 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,abatacept,CD80,CD80,binds CD80 to inhibit CD28-mediated T-cell cos...

 Run 2 completed | rows=2 | latency=13.511s
------------------------------------------------------------

 Starting run 3 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,abatacept,CD80,CD80,CTLA-4–Ig fusion protein that binds CD80 to in...,Approved

 Run 3 completed | rows=2 | latency=16.977s
------------------------------------------------------------

 Starting run 4 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action
0,abatacept,CD80,CD80,"binds CD80 and CD86, inhibiting CD28-mediated ..."

 Run 4 completed | rows=2 | latency=14.132s
------------------------------------------------------------

 Starting run 5 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,abatacept,CD80,CD80,CTLA-4Ig fusion protein that binds CD80 (B7-1)...,Approved

 Run 5 completed | rows=2 | latency=12.745s
------------------------------------------------------------


## Question 59

**Provide target names for lung cancer.**

In [61]:

question = 'Provide target names for lung cancer.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 13

  disease_name target_name
0  Lung cancer        EGFR

 Run 1 completed | rows=13 | latency=21.378s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 16

  target_name gene_name
0        EGFR      EGFR

 Run 2 completed | rows=16 | latency=27.483s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 14

,target_name,disease_name,gene_name,mechanism_of_action,approval_status
0,EGFR,Lung cancer,EGFR,EGFR tyrosine kinase inhibition,Approved

 Run 3 completed | rows=14 | latency=31.476s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 13

  disease_name target_name
0  Lung cancer        EGFR

 Run 4 completed | rows=13 | latency=19.456s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 17

  target_name
0        EGFR

 Run 5 completed | rows=17 | latency=24.028s
------------------------------------------------------------


## Question 60

**What are the known targets of ponatinib?**

In [62]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 12

   drug_name target_name gene_name        mechanism_of_action
0  ponatinib        ABL1      ABL1  tyrosine kinase inhibitor

 Run 1 completed | rows=12 | latency=25.051s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 11

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ponatinib,BCR-ABL1,ABL1,tyrosine kinase inhibition of BCR-ABL1,Approved

 Run 2 completed | rows=11 | latency=28.040s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 11

,drug_name,target_name,gene_name,mechanism_of_action
0,ponatinib,BCR-ABL1,ABL1,ATP-competitive tyrosine kinase inhibitor of B...

 Run 3 completed | rows=11 | latency=32.671s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name target_name gene_name                       mechanism_of_action
0  ponatinib        ABL1      ABL1  tyrosine kinase inhibitor targeting ABL1

 Run 4 completed | rows=10 | latency=28.067s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name target_name gene_name                mechanism_of_action
0  ponatinib        ABL1      ABL1  inhibits BCR-ABL1 tyrosine kinase

 Run 5 completed | rows=10 | latency=35.245s
------------------------------------------------------------


## Question 61

**Which drugs are used for systemic lupus erythematosus?**

In [63]:

question = 'Which drugs are used for systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

                   disease_name           drug_name
0  systemic lupus erythematosus  hydroxychloroquine

 Run 1 completed | rows=8 | latency=18.817s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

                   disease_name           drug_name
0  systemic lupus erythematosus  hydroxychloroquine

 Run 2 completed | rows=7 | latency=17.747s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

                   disease_name           drug_name
0  Systemic lupus erythematosus  hydroxychloroquine

 Run 3 completed | rows=8 | latency=26.614s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 9

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 4 completed | rows=9 | latency=16.600s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 7

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 5 completed | rows=7 | latency=15.625s
------------------------------------------------------------


## Question 62

**Genes associated with autism spectrum disorder.**

In [64]:

question = 'Genes associated with autism spectrum disorder.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 17

               disease_name gene_name
0  Autism spectrum disorder      CHD8

 Run 1 completed | rows=17 | latency=19.437s
------------------------------------------------------------

 Starting run 2 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 20

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 2 completed | rows=20 | latency=16.550s
------------------------------------------------------------

 Starting run 3 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 20

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 3 completed | rows=20 | latency=18.584s
------------------------------------------------------------

 Starting run 4 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 26

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 4 completed | rows=26 | latency=19.711s
------------------------------------------------------------

 Starting run 5 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 14

               disease_name gene_name
0  Autism spectrum disorder      CHD8

 Run 5 completed | rows=14 | latency=15.374s
------------------------------------------------------------


## Question 63

**Diseases associated with the gene ROS1.**

In [65]:

question = 'Diseases associated with the gene ROS1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

          disease_name gene_name
0  Lung adenocarcinoma      ROS1

 Run 1 completed | rows=3 | latency=17.749s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 1

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 2 completed | rows=1 | latency=9.255s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 3 completed | rows=3 | latency=14.367s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 2

                 disease_name gene_name
0  Non-small cell lung cancer      ROS1

 Run 4 completed | rows=2 | latency=11.477s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

  gene_name                disease_name
0      ROS1  Non-small cell lung cancer

 Run 5 completed | rows=3 | latency=14.588s
------------------------------------------------------------


## Question 64

**Diseases associated with the gene ALK.**

In [66]:

question = 'Diseases associated with the gene ALK.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 6

                 disease_name gene_name
0  Non-small cell lung cancer       ALK

 Run 1 completed | rows=6 | latency=25.327s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

                     disease_name gene_name
0  Anaplastic large cell lymphoma       ALK

 Run 2 completed | rows=4 | latency=15.704s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

    disease_name gene_name
0  Neuroblastoma       ALK

 Run 3 completed | rows=4 | latency=12.232s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer       ALK

 Run 4 completed | rows=4 | latency=22.246s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer       ALK

 Run 5 completed | rows=4 | latency=13.805s
------------------------------------------------------------


## Question 65

**Diseases associated with the gene EGFR.**

In [67]:

question = 'Diseases associated with the gene EGFR.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer      EGFR

 Run 1 completed | rows=4 | latency=16.319s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

   disease_name gene_name
0  Glioblastoma      EGFR

 Run 2 completed | rows=4 | latency=13.140s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

          disease_name gene_name
0  Lung adenocarcinoma      EGFR

 Run 3 completed | rows=4 | latency=15.097s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

                 disease_name gene_name
0  Non-small cell lung cancer      EGFR

 Run 4 completed | rows=4 | latency=11.230s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 3

                 disease_name gene_name
0  Non-small cell lung cancer      EGFR

 Run 5 completed | rows=3 | latency=11.290s
------------------------------------------------------------


## Question 66

**Provide target names for psoriasis.**

In [68]:

question = 'Provide target names for psoriasis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 7

  target_name
0         TNF

 Run 1 completed | rows=7 | latency=19.620s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 6

  disease_name target_name gene_name
0    Psoriasis         TNF       TNF

 Run 2 completed | rows=6 | latency=20.235s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  disease_name target_name
0    Psoriasis         TNF

 Run 3 completed | rows=5 | latency=18.535s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 5

  disease_name target_name
0    Psoriasis         TNF

 Run 4 completed | rows=5 | latency=22.168s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 6

  target_name
0         TNF

 Run 5 completed | rows=6 | latency=27.245s
------------------------------------------------------------


## Question 67

**Provide target names for ulcerative colitis.**

In [69]:

question = 'Provide target names for ulcerative colitis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0         TNF

 Run 1 completed | rows=5 | latency=29.513s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 9

  target_name
0         TNF

 Run 2 completed | rows=9 | latency=25.032s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 6

  target_name gene_name
0         TNF       TNF

 Run 3 completed | rows=6 | latency=25.606s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name
0         TNF       TNF

 Run 4 completed | rows=4 | latency=21.647s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 7

  target_name        disease_name
0         TNF  Ulcerative colitis

 Run 5 completed | rows=7 | latency=29.146s
------------------------------------------------------------


## Question 68

**Provide target names for tuberculosis.**

In [70]:

question = 'Provide target names for tuberculosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 14

   disease_name target_name
0  Tuberculosis       DprE1

 Run 1 completed | rows=14 | latency=23.414s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 5

    target_name
0  ATP synthase

 Run 2 completed | rows=5 | latency=28.624s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 7

   disease_name target_name
0  Tuberculosis        InhA

 Run 3 completed | rows=7 | latency=32.404s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 7

                          target_name
0  RNA polymerase beta subunit (RpoB)

 Run 4 completed | rows=7 | latency=34.221s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 6

  target_name
0        RpoB

 Run 5 completed | rows=6 | latency=22.940s
------------------------------------------------------------


## Question 69

**Provide target names for hepatitis C.**

In [71]:

question = 'Provide target names for hepatitis C.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name
0  NS3/4A protease

 Run 1 completed | rows=3 | latency=22.774s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 4

           target_name
0  HCV NS3/4A protease

 Run 2 completed | rows=4 | latency=19.039s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name disease_name
0  NS3/4A protease  Hepatitis C

 Run 3 completed | rows=3 | latency=13.061s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 4

       target_name
0  NS3/4A protease

 Run 4 completed | rows=4 | latency=20.900s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

       target_name
0  NS3/4A protease

 Run 5 completed | rows=3 | latency=15.173s
------------------------------------------------------------


## Question 70

**Provide target names for Hodgkin lymphoma.**

In [72]:

question = 'Provide target names for Hodgkin lymphoma.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name      disease_name
0        CD30  Hodgkin lymphoma

 Run 1 completed | rows=3 | latency=19.270s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name
0     TNFRSF8

 Run 2 completed | rows=3 | latency=12.891s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name gene_name
0        PD-1     PDCD1

 Run 3 completed | rows=3 | latency=22.560s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 4

       disease_name target_name
0  Hodgkin lymphoma       PDCD1

 Run 4 completed | rows=4 | latency=18.230s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

,target_name,gene_name,disease_name,mechanism_of_action,drug_name,approval_status
0,CD30,TNFRSF8,Hodgkin lymphoma,Monoclonal antibody-drug conjugate targeting C...,Brentuximab vedotin,Approved

 Run 5 completed | rows=3 | latency=29.423s
------------------------------------------------------------


## Question 71

**Which pathways are associated with the TP53?**

In [73]:

question = 'Which pathways are associated with the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 5

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 1 completed | rows=5 | latency=14.566s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 6

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 2 completed | rows=6 | latency=19.271s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 3 completed | rows=4 | latency=17.395s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 4 completed | rows=4 | latency=14.313s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 6

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 5 completed | rows=6 | latency=16.879s
------------------------------------------------------------


## Question 72

**Which drugs are associated with the ERBB2?**

In [74]:

question = 'Which drugs are associated with the ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 10

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Trastuzumab,HER2,ERBB2,HER2-directed monoclonal antibody; inhibits HE...,Approved

 Run 1 completed | rows=10 | latency=39.134s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action
0,Trastuzumab,ERBB2,ERBB2,Anti-HER2 monoclonal antibody that inhibits HE...

 Run 2 completed | rows=8 | latency=30.022s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 8

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,trastuzumab,ERBB2,ERBB2,monoclonal antibody against ERBB2; inhibits HE...,Approved

 Run 3 completed | rows=8 | latency=46.963s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action
0,Trastuzumab,ERBB2,ERBB2,Monoclonal antibody targeting ERBB2; inhibits ...

 Run 4 completed | rows=9 | latency=35.797s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 9

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,trastuzumab,ERBB2,ERBB2,humanized anti-HER2 monoclonal antibody target...,Approved

 Run 5 completed | rows=9 | latency=43.925s
------------------------------------------------------------


## Question 73

**Which pathways are associated with the ADRB1 gene?**

In [75]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                            pathway_name
0     ADRB1  G protein-cated GPCR signaling pathway

 Run 1 completed | rows=4 | latency=13.226s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 2 completed | rows=3 | latency=20.047s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 3 completed | rows=3 | latency=20.450s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

                             pathway_name gene_name
0  Adrenergic signaling in cardiomyocytes     ADRB1

 Run 4 completed | rows=2 | latency=25.362s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 5 completed | rows=1 | latency=11.498s
------------------------------------------------------------


## Question 74

**Which pathways are associated with the DRD2 gene?**

In [76]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name          pathway_name
0      DRD2  Dopaminergic synapse

 Run 1 completed | rows=3 | latency=16.833s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

                          pathway_name gene_name
0  Dopamine receptor signaling pathway      DRD2

 Run 2 completed | rows=4 | latency=20.134s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                         pathway_name
0      DRD2  Dopamine receptor signaling pathway

 Run 3 completed | rows=3 | latency=14.344s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

           pathway_name gene_name
0  Dopaminergic synapse      DRD2

 Run 4 completed | rows=2 | latency=13.553s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

           pathway_name gene_name
0  Dopaminergic synapse      DRD2

 Run 5 completed | rows=3 | latency=9.897s
------------------------------------------------------------


## Question 75

**Which pathways are associated with the HTR2A gene?**

In [77]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                          pathway_name
0     HTR2A  Serotonin receptor signaling pathway

 Run 1 completed | rows=2 | latency=19.995s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

                           pathway_name gene_name
0  Serotonin receptor signaling pathway     HTR2A

 Run 2 completed | rows=3 | latency=19.206s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

                                   pathway_name gene_name
0  G protein-coupled receptor signaling pathway     HTR2A

 Run 3 completed | rows=4 | latency=15.989s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

                  pathway_name gene_name
0  Serotonin signaling pathway     HTR2A

 Run 4 completed | rows=2 | latency=14.724s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                          pathway_name
0     HTR2A  Serotonin receptor signaling pathway

 Run 5 completed | rows=5 | latency=17.905s
------------------------------------------------------------


## Question 76

**Which drugs are associated with the CD19 gene?**

In [78]:

question = 'Which drugs are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Tisagenlecleucel,CD19,CD19,CD19-directed CAR-T cell therapy,Approved

 Run 1 completed | rows=7 | latency=26.039s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,tisagenlecleucel,CD19,CD19,CD19-directed chimeric antigen receptor (CAR) ...,Approved

 Run 2 completed | rows=5 | latency=19.901s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 8

          drug_name target_name gene_name               mechanism_of_action
0  tisagenlecleucel        CD19      CD19  CD19-directed CAR-T cell therapy

 Run 3 completed | rows=8 | latency=25.698s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,blinatumomab,CD19,CD19,CD19-CD3 bispecific T-cell engager (BiTE),Approved

 Run 4 completed | rows=5 | latency=22.438s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

          drug_name target_name gene_name               mechanism_of_action
0  tisagenlecleucel        CD19      CD19  CD19-directed CAR-T cell therapy

 Run 5 completed | rows=7 | latency=35.575s
------------------------------------------------------------


## Question 77

**Which drugs are associated with the CTLA4 gene?**

In [79]:

question = 'Which drugs are associated with the CTLA4 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name target_name gene_name              mechanism_of_action
0  ipilimumab      CTLA-4     CTLA4  anti-CTLA-4 monoclonal antibody

 Run 1 completed | rows=2 | latency=29.449s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ipilimumab,CTLA-4,CTLA4,anti-CTLA-4 monoclonal antibody; blocks CTLA-4...,Approved

 Run 2 completed | rows=2 | latency=19.965s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ipilimumab,CTLA-4,CTLA4,anti-CTLA-4 monoclonal antibody inhibiting CTL...,Approved

 Run 3 completed | rows=2 | latency=18.146s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ipilimumab,CTLA4,CTLA4,Anti-CTLA-4 monoclonal antibody,Approved

 Run 4 completed | rows=3 | latency=26.164s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
ipilimumab,CTLA-4,CTLA4,anti-CTLA-4 monoclonal antibody; blocks CTLA-4...,enhancing T-cell activation,Approved

 Run 5 completed | rows=2 | latency=23.491s
------------------------------------------------------------


## Question 78

**Which drugs are associated with the BTK gene?**

In [80]:

question = 'Which drugs are associated with the BTK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 3

   drug_name target_name gene_name mechanism_of_action approval_status
0  Ibrutinib         BTK       BTK       BTK inhibitor        Approved

 Run 1 completed | rows=3 | latency=21.301s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 3

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,ibrutinib,Bruton tyrosine kinase,BTK,Irreversible BTK inhibitor,Approved

 Run 2 completed | rows=3 | latency=26.156s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 3

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,Ibrutinib,BTK,BTK,irreversible covalent BTK inhibition,Approved

 Run 3 completed | rows=3 | latency=21.226s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 6

   drug_name             target_name gene_name mechanism_of_action
0  ibrutinib  Bruton tyrosine kinase       BTK      BTK inhibition

 Run 4 completed | rows=6 | latency=31.341s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action
0,ibrutinib,BTK,BTK,irreversible Bruton tyrosine kinase inhibitor

 Run 5 completed | rows=5 | latency=25.185s
------------------------------------------------------------


## Question 79

**Which drugs are associated with the SYK gene?**

In [81]:

question = 'Which drugs are associated with the SYK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,fostamatinib,SYK,SYK,SYK tyrosine kinase inhibitor,Approved

 Run 1 completed | rows=2 | latency=20.515s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

      drug_name             target_name gene_name mechanism_of_action
0  fostamatinib  Spleen tyrosine kinase       SYK       SYK inhibitor

 Run 2 completed | rows=2 | latency=29.594s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

      drug_name             target_name gene_name mechanism_of_action
0  fostamatinib  Spleen tyrosine kinase       SYK       SYK inhibitor

 Run 3 completed | rows=2 | latency=25.907s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,fostamatinib,Spleen tyrosine kinase,SYK,SYK inhibitor; prodrug of R406.,Approved

 Run 4 completed | rows=2 | latency=29.382s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Fostamatinib,SYK,SYK,Spleen tyrosine kinase (SYK) inhibition,Approved

 Run 5 completed | rows=2 | latency=28.812s
------------------------------------------------------------


## Question 80

**Which pathways are associated with TP53?**

In [82]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_biochatter_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 1 completed | rows=4 | latency=16.268s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 2 completed | rows=3 | latency=16.287s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 3 completed | rows=3 | latency=21.234s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 4 completed | rows=4 | latency=14.744s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

            pathway_name gene_name
0  p53 signaling pathway      TP53

 Run 5 completed | rows=4 | latency=17.175s
------------------------------------------------------------

##### Store as .pkl

In [ ]:
# import pickle
# with open("Biochatter_same_question_response.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

##### Store as json

In [85]:
# import json
# import pandas as pd

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("Biochatter_same_question_response.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )

In [ ]:
# RUNS

range(1, 6)