In [36]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from opentarget_utility import retrieve_opentarget

In [37]:
model = "OpenTarget"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [38]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: The query aimed to explore associations related to the biological target BRAF. First, the system retrieved a set of known disease–drug associations for BRAF, resulting in 821 records. Next, to ensure uniqueness, duplicate entries were removed from this set, reducing the record count from 821 to 170.
[target_tool]: In summary, after retrieving the initial associations and removing duplicates, the final dataset included 170 unique records related to BRAF.
----------------------------------------
Entries retrieved: 170

         target_id target_name   disease_id disease_name  association_score
0  ENSG00000157764        braf  EFO_0000756     melanoma           0.808126

 Run 1 completed | rows=170 | latency=15.252s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: The intent of the query was to identify specific drug-disease associations with certain characteristics. However, in this case, the execution log contains no steps, meaning no processing or filtering was performed. Without any steps listed, the system did not retrieve data or apply any filters. Therefore, there are no results to report beyond the initial state. The final result set remains undefined due to the absence of any executed steps.
----------------------------------------
[disease_tool]: No resolved disease found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 20.572s: Returned object is not a DataFrame
  Attempt 2/3
[target_tool]: The query aims to find specific information related to the target BRAF. First, the system retrieved known disease–drug associations specific to BRAF, which resulted in a set of 821 entries. Next, the system performed deduplication to eliminate duplicate records, reducing the number from 821 to 170 unique associations. The final result is a set of 170 distinct disease–drug associations related to BRAF.
----------------------------------------
Entries retrieved: 170

         target_id target_name   disease_id disease_name  association_score
0  ENSG00000157764        braf  EFO_0000756     melanoma           0.808126

 Run 2 completed | rows=170 | latency=20.122s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: The goal of the query was to find information related to the target BRAF. Initially, the system retrieved all known disease–drug associations for BRAF, resulting in 821 entries. Then, to refine these results, duplicate records were removed, which reduced the number from 821 to 170. In total, the final result set included 170 unique associations related to BRAF.
----------------------------------------
Entries retrieved: 170

         target_id target_name   disease_id disease_name  association_score
0  ENSG00000157764        braf  EFO_0000756     melanoma           0.808126

 Run 3 completed | rows=170 | latency=14.076s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: The query aimed to find specific information related to the target BRAF. First, the system retrieved known disease–drug associations for BRAF, resulting in 821 entries. Then, it removed duplicate records from these associations, reducing the total number of entries from 821 to 170 to ensure each association was unique.
----------------------------------------
Entries retrieved: 170

         target_id target_name   disease_id disease_name  association_score
0  ENSG00000157764        braf  EFO_0000756     melanoma           0.808126

 Run 4 completed | rows=170 | latency=14.977s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
[target_tool]: The query aimed to find information about the target BRAF, including associated diseases and potential drugs.
[target_tool]: First, the system retrieved a set of known disease–drug associations related to BRAF. Initially, this retrieval produced 821 entries.
[target_tool]: Next, the system performed a deduplication step to remove any duplicate records from the retrieved data. This process reduced the total number of entries from 821 to 170, ensuring that each association was unique.
[target_tool]: In summary, after these steps, the final result consisted of 170 unique entries related to BRAF, covering its disease associations and related drug information as per the initial query.
----------------------------------------
Entries retrieved: 170

         target_id target_name   disease_id disease_name  association_score
0  ENSG00000157764        braf  EFO_0000756     melanoma           0.808126

 Run 5 completed | rows=170 | latency=15.613s
------------------------------------------------------------


## Question 2

**List genes linked to amyotrophic lateral sclerosis.**

In [39]:

question = 'List genes linked to amyotrophic lateral sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to amyotrophic lateral sclerosis (ALS).
[disease_tool]: Initially, the system retrieved known disease–drug associations related to this disease, which resulted in a raw set of 486 entries.
[disease_tool]: Next, the system performed a deduplication process to eliminate duplicate records from this set. After removing duplicates, the number of entries was reduced from 486 to 147.
[disease_tool]: In summary, the final result contains 147 unique entries associated with amyotrophic lateral sclerosis after filtering out duplicates.
----------------------------------------
Entries retrieved: 147

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142168,sod1,MONDO_0004976,amyotrophic lateral sclerosis,Oligonucleotide,0.883359

 Run 1 completed | rows=147 | latency=15.209s
------------------------------------------------------------

 Starting run 2 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
[disease_tool]: The query was designed to find information related to amyotrophic lateral sclerosis. First, the system retrieved known disease–drug associations for this disease, resulting in 486 entries. Next, the system removed duplicate records from this set, reducing the number of entries from 486 to 147. In the end, the process prevented duplicate data from influencing the final results. The final result consists of 147 unique records associated with amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 147

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142168,sod1,MONDO_0004976,amyotrophic lateral sclerosis,Oligonucleotide,0.883359

 Run 2 completed | rows=147 | latency=16.346s
------------------------------------------------------------

 Starting run 3 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
[disease_tool]: The query aimed to explore associations related to amyotrophic lateral sclerosis. The process began by retrieving known disease–drug associations specifically for amyotrophic lateral sclerosis. This initial retrieval produced 486 entries. To refine the results, any duplicate records within these associations were then removed, reducing the total number of rows from 486 to 147. In the end, the filtered set consisted of 147 unique disease–drug association records related to amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 147

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142168,sod1,MONDO_0004976,amyotrophic lateral sclerosis,Oligonucleotide,0.883359

 Run 3 completed | rows=147 | latency=16.173s
------------------------------------------------------------

 Starting run 4 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
[disease_tool]: The query aimed to find disease–drug associations related to amyotrophic lateral sclerosis.
[disease_tool]: First, the system retrieved all known associations between diseases and drugs specifically for amyotrophic lateral sclerosis. This process resulted in an initial list of 486 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records. This step reduced the total from 486 to 147 unique entries, removing 339 duplicates.
[disease_tool]: In summary, after retrieving and cleaning the data, there are 147 distinct disease–drug association records related to amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 147

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142168,sod1,MONDO_0004976,amyotrophic lateral sclerosis,Oligonucleotide,0.883359

 Run 4 completed | rows=147 | latency=16.322s
------------------------------------------------------------

 Starting run 5 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
[disease_tool]: The query aims to find information related to amyotrophic lateral sclerosis through known disease-drug associations. First, the system retrieved base disease associations related to amyotrophic lateral sclerosis, resulting in 486 entries. Next, the system removed duplicate rows from these associations, reducing the total number of entries from 486 to 147. This step ensured that each association was unique. In summary, the final result consists of 147 unique disease association entries related to amyotrophic lateral sclerosis.
----------------------------------------
Entries retrieved: 147

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142168,sod1,MONDO_0004976,amyotrophic lateral sclerosis,Oligonucleotide,0.883359

 Run 5 completed | rows=147 | latency=16.281s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [40]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target CDK4.
[target_tool]: First, the system retrieved the known disease–drug associations for CDK4, resulting in a total of 466 records.
[target_tool]: Next, the system performed deduplication to remove any duplicate entries, reducing the number of records from 466 to 160.
[target_tool]: In summary, after retrieving all initial associations and removing duplicates, the final set consists of 160 unique records related to CDK4.
----------------------------------------
Entries retrieved: 160

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000135446,cdk4,EFO_0000389,cutaneous melanoma,0.651722

 Run 1 completed | rows=160 | latency=16.156s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: The query was designed to identify relevant drug associations for the target CDK4. First, the system retrieved a set of 466 known disease-drug associations related to CDK4. Next, it removed duplicate entries from this set, which reduced the number of associations from 466 down to 160. This step helped ensure that the final results contained unique and non-redundant data. In the end, 160 distinct associations remained after deduplication.
----------------------------------------
Entries retrieved: 160

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000135446,cdk4,EFO_0000389,cutaneous melanoma,0.651722

 Run 2 completed | rows=160 | latency=14.531s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target, CDK4. First, the system retrieved known disease–drug associations related to CDK4, which resulted in 466 entries. Next, it removed duplicate records from these retrieved associations, reducing the total from 466 to 160 unique entries. In summary, the final result includes 160 distinct associations related to CDK4 after deduplication.
----------------------------------------
Entries retrieved: 160

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000135446,cdk4,EFO_0000389,cutaneous melanoma,0.651722

 Run 3 completed | rows=160 | latency=13.840s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: The query aims to find specific information related to the target CDK4.
[target_tool]: First, the system retrieved known disease–drug associations for CDK4, resulting in 466 records.
[target_tool]: Next, it performed deduplication to remove any duplicate entries, reducing the number of records from 466 to 160.
[target_tool]: In total, the process ended with 160 unique records related to CDK4.
----------------------------------------
Entries retrieved: 160

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000135446,cdk4,EFO_0000389,cutaneous melanoma,0.651722

 Run 4 completed | rows=160 | latency=18.585s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target gene CDK4.
[target_tool]: First, the system retrieved all known disease–drug associations for CDK4, resulting in a total of 466 entries. Next, it removed duplicate records from these results, reducing the number from 466 to 160 unique entries.
[target_tool]: In summary, after these steps, the final result consists of 160 distinct disease–drug associations related to CDK4.
----------------------------------------
Entries retrieved: 160

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000135446,cdk4,EFO_0000389,cutaneous melanoma,0.651722

 Run 5 completed | rows=160 | latency=15.529s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [41]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the biological pathways associated with the target JAK2.
[target_tool]: The first step involved retrieving pathways related to JAK2, which resulted in a total of 38 pathways identified.
[target_tool]: There are no other steps listed, so the process primarily focused on pathway retrieval.
[target_tool]: In summary, the process resulted in 38 pathways associated with JAK2.
----------------------------------------
Entries retrieved: 38

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 1 completed | rows=38 | latency=15.668s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to gather information related to the JAK2 target. The first step involved retrieving pathways associated with JAK2. This process identified 38 pathways, but the number of pathways before retrieval is not specified.
[target_tool]: Since the pathway retrieval only fetched related pathways without further filtering, the number of results was reduced to 38 entries for pathways connected to JAK2.
[target_tool]: In summary, the pathway retrieval step provided a set of 38 pathways linked to the JAK2 target, which is part of the overall process to analyze its biological associations.
----------------------------------------
Entries retrieved: 38

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 2 completed | rows=38 | latency=13.939s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve information related to the target JAK2, including associated pathways. First, the system retrieved pathways related to the target JAK2, resulting in 38 pathways. Since there was no prior set of pathways, the total increased to 38 after this step. In the end, 38 pathways associated with JAK2 were retrieved.
----------------------------------------
Entries retrieved: 38

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 3 completed | rows=38 | latency=14.870s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target, JAK2. In this step, the system retrieved pathways associated with JAK2, resulting in a total of 38 pathways. This step was focused solely on pathway retrieval and did not specify any filtering, so it expanded the information available about pathways linked to the target. The final result includes 38 pathways associated with JAK2.
----------------------------------------
Entries retrieved: 38

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 4 completed | rows=38 | latency=16.316s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify pathways associated with the biological target JAK2. The process began by retrieving pathway information related to JAK2, which resulted in a set of 38 pathways. Since this step involved only pathway retrieval, no prior result set was reduced at this point. The final step was simply to gather pathway data for the target, and the number of pathways retrieved was 38.
----------------------------------------
Entries retrieved: 38

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,JAK2,ENSG00000096968,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 5 completed | rows=38 | latency=14.566s
------------------------------------------------------------


## Question 5

**Which drugs are used for treating rheumatoid arthritis?**

In [42]:

question = 'Which drugs are used for treating rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aims to explore associations related to rheumatoid arthritis.
[disease_tool]: First, the system retrieved known disease–drug associations for rheumatoid arthritis, resulting in 1,365 entries.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate records from this set, reducing the total from 1,365 to 1,000.
[disease_tool]: In summary, after these steps, the final result set contains 1,000 unique disease–drug associations related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 1000

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2108730,sarilumab,EFO_0000685,rheumatoid arthritis,1.0,Terminated,Antibody,interleukin-6 receptor alpha subunit antagonist,0.735062

 Run 1 completed | rows=1000 | latency=15.457s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aims to find information related to rheumatoid arthritis, specifically focusing on disease–drug associations.
[disease_tool]: First, the system retrieved known disease associations for rheumatoid arthritis, resulting in 1,365 entries. This step gathered all the relevant data about the disease, without applying any filters yet.
[disease_tool]: Next, the system removed duplicate records to improve data quality, reducing the total from 1,365 to 1,000 entries. This process eliminated repetitive entries, leaving a cleaner dataset for further analysis.
[disease_tool]: In summary, after these steps, the dataset included 1,000 unique disease association records related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 1000

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2108730,sarilumab,EFO_0000685,rheumatoid arthritis,1.0,Terminated,Antibody,interleukin-6 receptor alpha subunit antagonist,0.735062

 Run 2 completed | rows=1000 | latency=16.882s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aims to find information related to rheumatoid arthritis.
[disease_tool]: First, the system retrieved known disease–drug associations related to rheumatoid arthritis, which initially resulted in 1,365 entries. This step gathered all the relevant associations without any filters applied.
[disease_tool]: Next, the system performed deduplication to eliminate duplicate records. This process reduced the number of entries from 1,365 to 1,000 by removing 365 duplicate rows, ensuring that the data set contained only unique associations.
[disease_tool]: In summary, after these steps, the system had 1,000 unique records related to disease–drug associations for rheumatoid arthritis.
----------------------------------------
Entries retrieved: 1000

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2108730,sarilumab,EFO_0000685,rheumatoid arthritis,1.0,Terminated,Antibody,interleukin-6 receptor alpha subunit antagonist,0.735062

 Run 3 completed | rows=1000 | latency=16.587s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aims to analyze data related to rheumatoid arthritis and associated drugs or pathways.
[disease_tool]: First, the system retrieved disease associations related to rheumatoid arthritis, which resulted in a total of 1,365 entries.
[disease_tool]: Next, the system performed a deduplication step to remove any duplicate records from this initial set. After this process, the number of entries was reduced to 1,000, eliminating 365 duplicate records.
[disease_tool]: In summary, starting with 1,365 disease association records, the system refined this to 1,000 unique entries for further analysis.
----------------------------------------
Entries retrieved: 1000

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2108730,sarilumab,EFO_0000685,rheumatoid arthritis,1.0,Terminated,Antibody,interleukin-6 receptor alpha subunit antagonist,0.735062

 Run 4 completed | rows=1000 | latency=16.362s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease-gene associations related to rheumatoid arthritis.
[disease_tool]: First, the system retrieved known disease associations for rheumatoid arthritis, resulting in a set of 1,365 records. This served as the initial dataset for further filtering.
[disease_tool]: Next, the system removed duplicate entries from this dataset. This deduplication process reduced the total number of records from 1,365 to 1,000, removing 365 duplicate rows to ensure each record was unique.
[disease_tool]: In summary, after these steps, there were 1,000 unique records related to disease associations with rheumatoid arthritis.
----------------------------------------
Entries retrieved: 1000

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2108730,sarilumab,EFO_0000685,rheumatoid arthritis,1.0,Terminated,Antibody,interleukin-6 receptor alpha subunit antagonist,0.735062

 Run 5 completed | rows=1000 | latency=15.191s
------------------------------------------------------------


## Question 6

**What are the targets and mechanisms for dulaglutide?**

In [43]:

question = 'What are the targets and mechanisms for dulaglutide?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
[drug_tool]: The query was designed to find drug associations related to dulaglutide.
[drug_tool]: First, the system retrieved known drug associations concerning dulaglutide. Initially, there was no specified number of entries before this step, but after the retrieval, 20 associations were identified.
[drug_tool]: Next, the data underwent a deduplication process to remove any duplicate entries. This step reduced the number of associations from 20 to just 1, eliminating 19 duplicate records in the process.
[drug_tool]: In summary, the final result contains a single unique drug association related to dulaglutide.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000112164,glp1r,CHEMBL2108027,dulaglutide,glucagon-like peptide 1 receptor agonist,DailyMed

 Run 1 completed | rows=1 | latency=14.709s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
[drug_tool]: The query aimed to identify specific drug associations related to dulaglutide.
[drug_tool]: Initially, the system retrieved known drug associations for dulaglutide, resulting in a list of 20 entries.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate records from this list, reducing the total to just 1 unique entry.
[drug_tool]: In summary, after filtering out duplicates, only one unique drug association remained in the final result.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000112164,glp1r,CHEMBL2108027,dulaglutide,glucagon-like peptide 1 receptor agonist,DailyMed

 Run 2 completed | rows=1 | latency=15.299s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
[drug_tool]: The goal of this query was to identify drug associations related to dulaglutide.
[drug_tool]: Initially, the system retrieved known drug associations for dulaglutide, resulting in 20 entries. There were duplicate records among these retrieved associations. The deduplication step then removed these duplicates, leaving only 1 unique association record.
[drug_tool]: In summary, after filtering for unique entries, the process resulted in a single distinct drug association for dulaglutide.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000112164,glp1r,CHEMBL2108027,dulaglutide,glucagon-like peptide 1 receptor agonist,DailyMed

 Run 3 completed | rows=1 | latency=16.562s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
[drug_tool]: This query aims to find drug associations related to dulaglutide.
[drug_tool]: First, the system retrieved known drug associations for dulaglutide, initially obtaining a certain number of entries. In this case, it resulted in 20 associations. Next, recognition of duplicate records occurred, which led to the removal of 19 duplicate rows, leaving only 1 unique association.
[drug_tool]: The final result after this process is a single, non-duplicate association for dulaglutide.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000112164,glp1r,CHEMBL2108027,dulaglutide,glucagon-like peptide 1 receptor agonist,DailyMed

 Run 4 completed | rows=1 | latency=15.531s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to dulaglutide. First, the system retrieved known drug associations for dulaglutide, resulting in 20 entries. Next, the system removed duplicate records from these associations, reducing the number to just 1 unique entry. The final result comprises a single, non-duplicate association for dulaglutide.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000112164,glp1r,CHEMBL2108027,dulaglutide,glucagon-like peptide 1 receptor agonist,DailyMed

 Run 5 completed | rows=1 | latency=16.286s
------------------------------------------------------------


## Question 7

**Provide target names for ovarian cancer?**

In [44]:

question = 'Provide target names for ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ovarian cancer?
  Attempt 1/3
[disease_tool]: The query aimed to find specific information related to ovarian cancer. First, the system retrieved known disease–drug associations related to ovarian cancer, resulting in a set of 4,185 entries. Next, to eliminate redundancy, it removed duplicate rows, reducing the dataset from 4,185 entries down to 376 entries. In summary, after these steps, there are 376 unique disease association records concerning ovarian cancer.
----------------------------------------
Entries retrieved: 376

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0008170,ovarian cancer,Small molecule,0.810501

 Run 1 completed | rows=376 | latency=17.077s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ovarian cancer?
  Attempt 1/3
[disease_tool]: The query aims to identify relationships involving ovarian cancer, focusing on specific disease associations.
[disease_tool]: The process began with the retrieval of known disease–drug associations related to ovarian cancer. Initially, the system gathered a comprehensive set of 4,185 entries, representing various associations linked to this disease.
[disease_tool]: Next, the dataset was cleaned through deduplication, which removed duplicate entries. This step reduced the number of records from 4,185 to 376, eliminating repeated information and ensuring the dataset contained unique entries only.
[disease_tool]: In summary, after applying these steps, the final dataset comprised 376 unique disease–drug association records related to ovarian cancer.
----------------------------------------
Entries retrieved: 376

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0008170,ovarian cancer,Small molecule,0.810501

 Run 2 completed | rows=376 | latency=18.514s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ovarian cancer?
  Attempt 1/3
[disease_tool]: The intent of the query was to find disease–drug associations related to ovarian cancer.
[disease_tool]: First, the system retrieved known disease associations for ovarian cancer, resulting in 4,185 entries. This step provided the initial set of data for further filtering.
[disease_tool]: Next, the system performed deduplication, which removed duplicate records from this set. After this process, the number of remaining entries was reduced to 376. This step ensured that only unique associations were retained in the final dataset.
[disease_tool]: In summary, the final result contains 376 unique disease–drug association entries related to ovarian cancer.
----------------------------------------
Entries retrieved: 376

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0008170,ovarian cancer,Small molecule,0.810501

 Run 3 completed | rows=376 | latency=17.777s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ovarian cancer?
  Attempt 1/3
[disease_tool]: The query was designed to identify associations related to ovarian cancer. Initially, the system retrieved 4,185 known disease–drug associations for ovarian cancer. Next, it performed deduplication to remove any duplicate records, which reduced the total from 4,185 to 376 unique entries.
[disease_tool]: In summary, after filtering out duplicates, the final result consisted of 376 distinct associations related to ovarian cancer.
----------------------------------------
Entries retrieved: 376

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0008170,ovarian cancer,Small molecule,0.810501

 Run 4 completed | rows=376 | latency=20.974s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ovarian cancer?
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to ovarian cancer.
[disease_tool]: First, the system retrieved known disease–drug associations for ovarian cancer, resulting in 4,185 records. This step gathered all the potential related association data before any filtering.
[disease_tool]: Next, duplicate records were removed from these associations, reducing the total from 4,185 to 376. This step eliminated redundant entries to ensure only unique associations remained.
[disease_tool]: The final result after these processing steps was 376 unique disease-drug associations related to ovarian cancer.
----------------------------------------
Entries retrieved: 376

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0008170,ovarian cancer,Small molecule,0.810501

 Run 5 completed | rows=376 | latency=20.724s
------------------------------------------------------------


## Question 8

**What are the known targets of regorafenib?**

In [45]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The goal of the query was to identify drug associations related to regorafenib.
[drug_tool]: First, the system retrieved the known associations between various drugs and diseases for regorafenib, resulting in 2,286 records. Then, to ensure the data was accurate and non-redundant, duplicate entries were removed, reducing the number of records significantly from 2,286 down to 18.
[drug_tool]: In the end, the process yielded a refined set of 18 unique drug association records related to regorafenib.
----------------------------------------
Entries retrieved: 18

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL1946170,regorafenib,vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 1 completed | rows=18 | latency=18.346s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The purpose of the query was to identify drug associations related to regorafenib.
[drug_tool]: First, the system retrieved known drug associations for regorafenib, resulting in 2,286 entries. This initial step gathered all potential connections without filtering or narrowing down.
[drug_tool]: Next, the system removed duplicate entries to ensure unique records. This deduplication process reduced the number of associations significantly, from 2,286 to 18.
[drug_tool]: In total, after removing duplicates, the final set of association records related to regorafenib consisted of 18 unique entries.
----------------------------------------
Entries retrieved: 18

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL1946170,regorafenib,vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 2 completed | rows=18 | latency=16.362s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The goal of the query was to find drug associations related to regorafenib. First, the system retrieved a broad set of 2,286 drug association records for regorafenib. Next, to refine the data, it removed duplicate entries, which significantly reduced the number of records from 2,286 down to 18. In the end, the query returned a total of 18 unique drug association records related to regorafenib.
----------------------------------------
Entries retrieved: 18

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL1946170,regorafenib,vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 3 completed | rows=18 | latency=16.599s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug regorafenib, focusing on its associations with diseases.
[drug_tool]: First, the system retrieved a set of known associations between diseases and drugs for regorafenib. Initially, this retrieval produced 2,286 records.
[drug_tool]: Next, the system performed deduplication to remove any duplicate entries from this set. After this step, the number of records was reduced dramatically from 2,286 to just 18.
[drug_tool]: Overall, the final result contains 18 unique records related to regorafenib's disease associations after filtering out duplicates.
----------------------------------------
Entries retrieved: 18

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL1946170,regorafenib,vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 4 completed | rows=18 | latency=16.735s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
[drug_tool]: The query aimed to find specific associations related to the drug regorafenib. The process began with retrieving known disease–drug associations for this drug. Initially, this step returned a large set of 2,286 entries. Next, duplicate records were removed from this set to ensure each association was unique. After deduplication, the number of entries was significantly reduced to 18. In conclusion, the final result contains 18 distinct associations related to regorafenib.
----------------------------------------
Entries retrieved: 18

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL1946170,regorafenib,vascular endothelial growth factor receptor in...,"Expert, FDA"

 Run 5 completed | rows=18 | latency=16.412s
------------------------------------------------------------


## Question 9

**Which pathways are associated with the STAT3 gene?**

In [46]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to explore information related to the target, STAT3.
[target_tool]: The process began with retrieving pathways associated with STAT3, resulting in a total of 39 pathways. This step provided pathway information relevant to the target.
[target_tool]: Since only the pathway retrieval step is documented, there are no further filters or reductions described in the provided log.
[target_tool]: In summary, the final result includes information on 39 pathways linked to STAT3.
----------------------------------------
Entries retrieved: 39

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 1 completed | rows=39 | latency=15.175s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query was aimed at understanding the biological pathways associated with the target STAT3. The first step involved retrieving pathways related to STAT3, resulting in 39 pathways being identified. This step provided the pathway information without further filtering or reduction, as it was the initial retrieval. In summary, 39 pathways associated with STAT3 were obtained, forming the basis for subsequent analysis if needed.
----------------------------------------
Entries retrieved: 39

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 2 completed | rows=39 | latency=15.165s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information about pathways associated with the target STAT3. First, the system performed pathway retrieval, during which it obtained pathway data related to this target. Prior to this step, there was no specified number of pathways, but after the retrieval, 39 pathways were identified. In summary, the final result includes 39 pathways associated with the target STAT3.
----------------------------------------
Entries retrieved: 39

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 3 completed | rows=39 | latency=15.195s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify relevant pathways associated with the target STAT3.
[target_tool]: Initially, the system retrieved pathway information related to STAT3 without any prior filtering. After this step, 39 pathways were identified as associated with the target.
[target_tool]: In summary, the system successfully retrieved 39 pathways linked to STAT3.
----------------------------------------
Entries retrieved: 39

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 4 completed | rows=39 | latency=13.429s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target STAT3, including associated pathways.
[target_tool]: The first step involved pathway retrieval, where the system retrieved pathway information related to STAT3. This step resulted in 39 pathways, although the exact number before retrieval was not specified.
[target_tool]: Since only this step is provided in the log, the process concluded after retrieving these pathways, giving a final count of 39 pathways associated with the target STAT3.
----------------------------------------
Entries retrieved: 39

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,STAT3,ENSG00000168610,R-HSA-1433557,Signaling by SCF-KIT,Signal Transduction

 Run 5 completed | rows=39 | latency=14.490s
------------------------------------------------------------


## Question 10

**Genes linked to fever.**

In [47]:

question = 'Genes linked to fever.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to fever.
  Attempt 1/3
[disease_tool]: This query aims to find disease-drug associations related to fever. First, the system retrieved known disease–drug associations for fever, which initially yielded 105 entries. Next, it performed deduplication to remove duplicate records, reducing the total from 105 to 38 unique associations. Therefore, the final result contains 38 distinct disease-drug association entries related to fever.
----------------------------------------
Entries retrieved: 38

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000073756,ptgs2,HP_0001945,fever,Small molecule,0.608161

 Run 1 completed | rows=38 | latency=15.226s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to fever.
  Attempt 1/3
[disease_tool]: The query's goal was to identify disease–drug associations related to fever.
[disease_tool]: Initially, the system retrieved all known disease–drug associations for fever, resulting in 105 entries. This step gathered a broad set of data without applying any filters.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the number of entries from 105 to 38. This step ensured that only unique associations were retained for further consideration.
[disease_tool]: In summary, after the retrieval and deduplication steps, the final dataset consisted of 38 unique associations related to fever.
----------------------------------------
Entries retrieved: 38

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000073756,ptgs2,HP_0001945,fever,Small molecule,0.608161

 Run 2 completed | rows=38 | latency=15.594s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to fever.
  Attempt 1/3
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The query aimed to identify specific drug-disease associations based on mechanisms of action and pathways. Since the execution log is empty, it indicates that no steps were taken to process the query. Consequently, there are no results or filters applied in this case. The final result count is zero due to the absence of executed steps.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: The query aimed to find specific information related to the disease "fever."
[disease_tool]: Initially, the system retrieved known associations between diseases and drugs for "fever," which resulted in a total of 105 entries. This step gathered all the possible related records before any filtering.
[disease_tool]: Next, duplicate entries within these associations were removed to ensure each record was unique. This deduplication process reduced the number of records from 105 to 38, eliminating 67 duplicate rows.
[disease_tool]: In the end, the system presented a refined set of 38 unique records related to "fever."
----------------------------------------
Entries retrieved: 38

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000073756,ptgs2,HP_0001945,fever,Small molecule,0.608161

 Run 3 completed | rows=38 | latency=15.573s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to fever.
  Attempt 1/3
[disease_tool]: The query aims to find information related to the disease "fever" by exploring associated drugs and mechanisms.
[disease_tool]: First, the system retrieved known disease-drug associations for fever, which initially listed 105 entries. These entries included different drugs and their related information connected to fever.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate records from this list. This step reduced the number of entries from 105 to 38, removing 67 duplicate rows to ensure that only unique associations remained.
[disease_tool]: In total, after these steps, the final result contains 38 unique entries related to fever.
----------------------------------------
Entries retrieved: 38

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000073756,ptgs2,HP_0001945,fever,Small molecule,0.608161

 Run 4 completed | rows=38 | latency=15.925s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to fever.
  Attempt 1/3
[disease_tool]: The query aims to identify drug targets associated with a specific disease, along with information on mechanisms of action and biological pathways.
[disease_tool]: Since the execution log contains no recorded steps, it indicates that no processes were performed to refine or filter the search results. As a result, no data was retrieved or narrowed down through disease, drug, or mechanism filters, and no pathway information was collected.
[disease_tool]: In summary, without any execution steps documented, the final result set remains empty, meaning no relevant associations or specific information were obtained during this process.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: The query was initially designed to retrieve information related to the disease "fever." First, the system retrieved known disease–drug associations for fever, resulting in a total of 105 records. Next, to ensure data accuracy and remove redundant entries, the system performed a deduplication process, which eliminated duplicate rows. This process reduced the number of records from 105 to 38, leaving a refined set of unique association data.
----------------------------------------
Entries retrieved: 38

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000073756,ptgs2,HP_0001945,fever,Small molecule,0.608161

 Run 5 completed | rows=38 | latency=16.135s
------------------------------------------------------------


## Question 11

**List all drugs that target EGFR?**

In [48]:

question = 'List all drugs that target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List all drugs that target EGFR?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target EGFR. First, the system retrieved a broad set of known disease–drug associations for EGFR, resulting in 1,870 entries. Next, the system performed deduplication to remove duplicate records, which reduced the number of entries from 1,870 to 510. This process ensured that only unique associations remained. In the end, the final dataset contained 510 distinct records related to EGFR associations.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 1 completed | rows=510 | latency=14.595s
------------------------------------------------------------

 Starting run 2 for query: List all drugs that target EGFR?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve information related to the target EGFR.
[target_tool]: First, the system retrieved known disease-drug associations involving EGFR, which resulted in 1,870 entries.
[target_tool]: Next, it removed duplicate records, decreasing the total from 1,870 to 510. This step ensured that only unique associations were kept for further consideration.
[target_tool]: Overall, the process narrowed down the associations to 510 distinct records, providing a more concise dataset for subsequent analysis.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 2 completed | rows=510 | latency=14.792s
------------------------------------------------------------

 Starting run 3 for query: List all drugs that target EGFR?
  Attempt 1/3
[target_tool]: The query aims to retrieve associations related to the target EGFR.
[target_tool]: Initially, the system performed an association retrieval step, where it gathered known disease-drug associations for EGFR, resulting in 1,870 records.
[target_tool]: Next, a deduplication process was applied to remove duplicate entries from these associations. This step reduced the number of records from 1,870 to 510, ensuring that only unique associations remained.
[target_tool]: In total, the process narrowed the initial set of associations down to 510 unique records related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 3 completed | rows=510 | latency=14.626s
------------------------------------------------------------

 Starting run 4 for query: List all drugs that target EGFR?
  Attempt 1/3
[target_tool]: The query aims to find associations related to the target EGFR.
[target_tool]: First, the system retrieved known disease–drug associations for EGFR, retrieving a total of 1,870 entries.
[target_tool]: Next, to ensure data quality and remove redundant information, the system performed deduplication, which reduced the number of records from 1,870 to 510. This step removed 1,360 duplicate entries, leaving a set of unique associations linked to the target.
[target_tool]: In summary, the process started with 1,870 associations and, after removing duplicates, resulted in 510 unique records related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 4 completed | rows=510 | latency=16.090s
------------------------------------------------------------

 Starting run 5 for query: List all drugs that target EGFR?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve information related to the target EGFR.
[target_tool]: The first step involved association retrieval, where the system fetched known disease–drug associations for EGFR, resulting in a total of 1,870 entries.
[target_tool]: Next, the system performed deduplication to remove duplicate entries. This process reduced the number of entries from 1,870 to 510, eliminating 1,360 duplicate records, to ensure the data was unique and easier to analyze.
[target_tool]: In summary, after these steps, there were 510 unique association records related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 5 completed | rows=510 | latency=18.129s
------------------------------------------------------------


## Question 12

**Show drugs that inhibit the FGFR2 gene?**

In [49]:

question = 'Show drugs that inhibit the FGFR2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
[target_tool]: The query aimed to find drug associations related to the target FGFR2, focusing on specific mechanisms of action.
[target_tool]: Initially, the system retrieved a set of 458 known disease-drug associations for FGFR2. This step provided a broad base of relationships involving this target.
[target_tool]: Next, the system applied a filter based on the mechanism of action, specifically looking for drugs described as inhibitors. After this filtering, the number of associations was reduced from 458 to 401. The system identified two relevant mechanism terms: "fibroblast growth factor receptor 2 inhibitor" and "fibroblast growth factor receptor inhibitor," which matched the filter criteria.
[target_tool]: Then, the process removed duplicate entries, decreasing the total from 401 to 137 associations.
[target_tool]: Overall, the final result includes 137 unique associations related to FGFR2 that involve inhibitory mechanisms.
----------------------------------------
Entries retrieved: 137

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000066468,fgfr2,CHEMBL3545376,erdafitinib,4.0,NaN,NaN,fibroblast growth factor receptor inhibitor

 Run 1 completed | rows=137 | latency=18.724s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
[target_tool]: The query aimed to find information related to the target FGFR2, focusing on its associations, mechanisms, and duplicates.
[target_tool]: Initially, the system retrieved a total of 458 disease–drug associations related to FGFR2. This step collected known links between FGFR2 and various drugs or conditions.
[target_tool]: Next, the system applied a mechanism-of-action filter using the term "inhibitor." This reduced the results from 458 to 401 associations. During this step, the system matched phrases like "fibroblast growth factor receptor 2 inhibitor" and "fibroblast growth factor receptor inhibitor," which are specific to inhibitors of FGFR2. This filtering narrowed the results to those relevant to FGFR2 inhibitors.
[target_tool]: Finally, the system performed deduplication to remove duplicate records. This process cut the number of entries from 401 down to 137 by eliminating repeated associations, ensuring that each record was unique.
[target_tool]: In total, the process refined the initial set of associations to a final count of 137 unique entries related to FGFR2 inhibitors.
----------------------------------------
Entries retrieved: 137

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000066468,fgfr2,CHEMBL3545376,erdafitinib,4.0,NaN,NaN,fibroblast growth factor receptor inhibitor

 Run 2 completed | rows=137 | latency=21.792s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target gene FGFR2 and filter those associations based on specific mechanisms of action, then remove duplicates to produce a refined list.
[target_tool]: First, the system retrieved 458 known disease-drug associations for FGFR2. This initial retrieval provided a broad set of data related to FGFR2, without any filters applied yet.
[target_tool]: Next, the system applied a mechanism of action filter. It kept only those associations where the mechanism involved an inhibitor. Specifically, it looked for terms like "fibroblast growth factor receptor 2 inhibitor" and "fibroblast growth factor receptor inhibitor," which matched two of the associated terms. This step reduced the number of records from 458 to 401, excluding associations that did not involve the specified mechanism.
[target_tool]: Finally, the system removed duplicate rows from the filtered data, decreasing the count from 401 to 137. This deduplication step ensured that only unique entries remained.
[target_tool]: In total, after these steps, 137 unique associations related to FGFR2 and its inhibition mechanism were identified.
----------------------------------------
Entries retrieved: 137

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000066468,fgfr2,CHEMBL3545376,erdafitinib,4.0,NaN,NaN,fibroblast growth factor receptor inhibitor

 Run 3 completed | rows=137 | latency=22.284s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve and refine information related to the target FGFR2, focusing on its associated drugs and mechanisms of action. First, the system retrieved known disease–drug associations for FGFR2, resulting in a set of 458 entries. Next, the data was filtered to include only those entries where the mechanism of action involved an inhibitor. This filtering narrowed down the list from 458 to 401, a reduction of 57, by selecting terms like "fibroblast growth factor receptor 2 inhibitor" and "fibroblast growth factor receptor inhibitor." Finally, duplicate rows were removed from this subset, reducing the count from 401 to 137, leaving a distinct set of associations. In total, the process concluded with 137 unique entries after applying the specified filters.
----------------------------------------
Entries retrieved: 137

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000066468,fgfr2,CHEMBL3545376,erdafitinib,4.0,NaN,NaN,fibroblast growth factor receptor inhibitor

 Run 4 completed | rows=137 | latency=19.707s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
[target_tool]: The query was designed to retrieve associations related to the target FGFR2 and to filter these based on specific mechanisms of action.
[target_tool]: Initially, the system retrieved a list of known disease-drug associations for FGFR2, resulting in a total of 458 entries.
[target_tool]: Next, the results were filtered based on the mechanism of action, specifically focusing on inhibitors. This step narrowed the list from 458 to 401 entries. The filtering involved selecting terms related to inhibitors, with examples including "fibroblast growth factor receptor 2 inhibitor" and "fibroblast growth factor receptor inhibitor," totaling two matched terms.
[target_tool]: Finally, duplicate records were removed from the filtered list, reducing the total from 401 entries to 137 unique associations.
[target_tool]: In total, the process ended with 137 unique disease-drug associations related to FGFR2 that involve inhibitory mechanisms of action.
----------------------------------------
Entries retrieved: 137

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000066468,fgfr2,CHEMBL3545376,erdafitinib,4.0,NaN,NaN,fibroblast growth factor receptor inhibitor

 Run 5 completed | rows=137 | latency=22.079s
------------------------------------------------------------


## Question 13

**What diseases are treated with bevacizumab?**

In [50]:

question = 'What diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aims to find drug associations related to bevacizumab.
[drug_tool]: The first step involved retrieving the initial set of drug associations for bevacizumab. This retrieval resulted in 857 records, establishing the initial dataset for further filtering.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,bevacizumab,MONDO_0005575,colorectal cancer,4.0,Completed,vascular endothelial growth factor a inhibitor,"DailyMed, PubMed"

 Run 1 completed | rows=857 | latency=16.222s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug bevacizumab, potentially including its associated diseases or biological pathways.
[drug_tool]: First, the system retrieved the known associations between bevacizumab and various diseases or biological entities. This step resulted in 857 entries, which formed the initial set of data to be further refined.
[drug_tool]: Since only this first step is shown, it appears that the process focused on collecting all known associations for bevacizumab. The total number of associations retrieved was 857, providing a comprehensive starting point for subsequent filtering if further steps are applied.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,bevacizumab,MONDO_0005575,colorectal cancer,4.0,Completed,vascular endothelial growth factor a inhibitor,"DailyMed, PubMed"

 Run 2 completed | rows=857 | latency=13.881s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aims to identify drugs associated with a specific disease or condition. The first step involved retrieving known associations between a drug and various diseases or targets, specifically focusing on bevacizumab. This retrieval resulted in 857 entries, establishing a base set of known associations for further filtering. Since no prior data existed for the number of associations, only the post-retrieval count was noted. This step sets the foundation for subsequent filtering based on disease, drug specificity, mechanism, or other criteria.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,bevacizumab,MONDO_0005575,colorectal cancer,4.0,Completed,vascular endothelial growth factor a inhibitor,"DailyMed, PubMed"

 Run 3 completed | rows=857 | latency=13.113s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aims to find drug associations related to bevacizumab.
[drug_tool]: Initially, the system retrieved known associations of drugs with diseases, focusing on bevacizumab. This step resulted in a set of 857 entries, providing a broad base of disease–drug relationships involving this medication.
[drug_tool]: No further steps are documented in the provided log, so the process concludes with 857 associations.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,bevacizumab,MONDO_0005575,colorectal cancer,4.0,Completed,vascular endothelial growth factor a inhibitor,"DailyMed, PubMed"

 Run 4 completed | rows=857 | latency=13.358s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to bevacizumab.
[drug_tool]: Initially, the system retrieved the basic set of known drug associations for the drug bevacizumab. This step resulted in a total of 857 associations, providing a broad dataset to work with.
[drug_tool]: Because no filters or further narrowing steps are indicated in this part of the log, the entire set of 857 associations remains available at this stage.
[drug_tool]: In summary, after the initial retrieval, there are 857 known associations for bevacizumab being considered for further analysis or filtering.
----------------------------------------
Entries retrieved: 857

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201583,bevacizumab,MONDO_0005575,colorectal cancer,4.0,Completed,vascular endothelial growth factor a inhibitor,"DailyMed, PubMed"

 Run 5 completed | rows=857 | latency=13.871s
------------------------------------------------------------


## Question 14

**List treatments for plaque psoriasis and their mechanisms.**

In [51]:

question = 'List treatments for plaque psoriasis and their mechanisms.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
[disease_tool]: The query aimed to identify disease–drug associations related to plaque psoriasis. The first step involved retrieving the known disease associations for this condition, resulting in a total of 126 entries. Next, the process included removing duplicate records to ensure unique data points, which reduced the number of entries from 126 to 109. In summary, after deduplication, there are 109 unique disease association entries related to plaque psoriasis.
----------------------------------------
Entries retrieved: 109

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL221959,tofacitinib,EFO_1001494,psoriasis vulgaris,2.0,Completed,Small molecule,janus kinase (jak) inhibitor,0.655861

 Run 1 completed | rows=109 | latency=15.534s
------------------------------------------------------------

 Starting run 2 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
[disease_tool]: The query aims to identify data related to plaque psoriasis by following a series of filtering steps.
[disease_tool]: Initially, the system retrieved known disease-drug associations specifically related to plaque psoriasis. This step resulted in a total of 126 records.
[disease_tool]: Next, a deduplication process was applied to remove duplicate entries from this set. After this filtering, the number of records was reduced from 126 to 109, meaning 17 duplicate records were eliminated to ensure each entry was unique.
[disease_tool]: In summary, the final dataset contains 109 unique records associated with plaque psoriasis, reflecting a cleaner and more precise collection of relevant data.
----------------------------------------
Entries retrieved: 109

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL221959,tofacitinib,EFO_1001494,psoriasis vulgaris,2.0,Completed,Small molecule,janus kinase (jak) inhibitor,0.655861

 Run 2 completed | rows=109 | latency=17.379s
------------------------------------------------------------

 Starting run 3 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
[disease_tool]: The query aimed to find information related to plaque psoriasis, including associated diseases, drugs, mechanisms, and pathways.
[disease_tool]: First, the system retrieved known disease–drug associations relevant to plaque psoriasis, which resulted in a total of 126 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the number of entries from 126 to 109. This step helped ensure that only unique associations were retained for further analysis.
[disease_tool]: In summary, after applying the disease association retrieval and removing duplicate entries, the process resulted in 109 unique records related to plaque psoriasis.
----------------------------------------
Entries retrieved: 109

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL221959,tofacitinib,EFO_1001494,psoriasis vulgaris,2.0,Completed,Small molecule,janus kinase (jak) inhibitor,0.655861

 Run 3 completed | rows=109 | latency=19.497s
------------------------------------------------------------

 Starting run 4 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
[disease_tool]: The purpose of the query was to find disease-drug associations related to plaque psoriasis. First, the system retrieved known disease associations, resulting in 126 entries. Next, it removed duplicate records, reducing the total number of entries from 126 to 109. In summary, the final result contains 109 unique disease association records for plaque psoriasis.
----------------------------------------
Entries retrieved: 109

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL221959,tofacitinib,EFO_1001494,psoriasis vulgaris,2.0,Completed,Small molecule,janus kinase (jak) inhibitor,0.655861

 Run 4 completed | rows=109 | latency=16.375s
------------------------------------------------------------

 Starting run 5 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
[disease_tool]: The query aimed to find information related to plaque psoriasis.
[disease_tool]: Initially, the system retrieved known disease–drug associations related to this disease, resulting in 126 entries. This step gathered all relevant associations from the underlying database.
[disease_tool]: Next, the system performed deduplication to remove duplicate records. As a result, the number of entries was reduced from 126 to 109, with 17 duplicates being eliminated.
[disease_tool]: In summary, after these steps, the resulting dataset contained 109 unique disease–drug association records related to plaque psoriasis.
----------------------------------------
Entries retrieved: 109

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL221959,tofacitinib,EFO_1001494,psoriasis vulgaris,2.0,Completed,Small molecule,janus kinase (jak) inhibitor,0.655861

 Run 5 completed | rows=109 | latency=16.996s
------------------------------------------------------------


## Question 15

**What are the known targets of cabozantinib?**

In [52]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The query is designed to retrieve information related to a specific drug, in this case, cabozantinib.
[drug_tool]: First, the system retrieved known disease–drug associations involving cabozantinib. This step resulted in 316 entries, which included various possible relationships between diseases and this drug.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries from the initial result set. This process significantly reduced the number of results from 316 to just 2 entries, ensuring that only unique associations remained.
[drug_tool]: In total, after completing these steps, the system provided 2 unique disease–drug association records related to cabozantinib.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,met,CHEMBL2105717,cabozantinib,hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 1 completed | rows=2 | latency=15.046s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The query aimed to find drug associations for cabozantinib. In the first step, the system retrieved all known disease–drug associations related to this drug, which resulted in 316 entries. Next, to ensure data quality, duplicate records were removed, which greatly reduced the number of entries from 316 to just 2. In total, the process narrowed down the associations to a final set of 2 unique records.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,met,CHEMBL2105717,cabozantinib,hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 2 completed | rows=2 | latency=14.079s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve information related to the drug cabozantinib and to refine this information to relevant, unique associations. First, the system retrieved known associations between drugs and diseases, resulting in 316 entries.
[drug_tool]: Next, the system performed deduplication to remove any duplicate records, which significantly reduced the dataset from 316 entries down to just 2. This step ensured that only unique associations remained for further analysis or review.
[drug_tool]: In summary, after filtering, only 2 distinct associations involving cabozantinib were retained in the final result.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,met,CHEMBL2105717,cabozantinib,hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 3 completed | rows=2 | latency=14.886s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The query aims to find specific drug associations related to cabozantinib.
[drug_tool]: First, the system retrieved known disease–drug associations for cabozantinib, resulting in 316 entries.
[drug_tool]: Next, it removed duplicate records from these results, reducing the number from 316 to just 2.
[drug_tool]: In summary, after filtering and deduplication, there are 2 unique associations remaining related to cabozantinib.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,met,CHEMBL2105717,cabozantinib,hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 4 completed | rows=2 | latency=14.266s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
[drug_tool]: The query appears to aim at identifying drugs associated with a specific target.
[drug_tool]: Initially, the system retrieved known associations between drugs and the disease or target of interest. In this step, it found 316 records related to cabozantinib.
[drug_tool]: Next, the system removed duplicate entries from this set to ensure each association was unique. This deduplication process reduced the total number of records from 316 down to 2, eliminating 314 duplicate entries.
[drug_tool]: In summary, the final result after all steps consisted of 2 unique drug association records related to cabozantinib.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105976,met,CHEMBL2105717,cabozantinib,hepatocyte growth factor receptor inhibitor,"DailyMed, PubMed"

 Run 5 completed | rows=2 | latency=13.707s
------------------------------------------------------------


## Question 16

**Show drugs that inhibit the RET gene?**

In [53]:

question = 'Show drugs that inhibit the RET gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
[target_tool]: The goal of this query was to identify associations related to the target RET.
[target_tool]: Initially, the system retrieved a total of 1,124 known disease–drug associations for RET. This set included all available data without any filters applied at this stage.
[target_tool]: Next, a filter based on the mechanism of action was applied. The filter focused specifically on inhibitors, leading to no change in the number of entries; the result still contained 1,124 associations. During this step, two specific mechanisms were matched based on terms like "coiled-coil domain-containing protein 6/tyrosine-protein kinase receptor ret inhibitor" and "kinesin-1 heavy chain/tyrosine-protein kinase receptor ret inhibitor," indicating the associations involve RET inhibitors.
[target_tool]: Finally, a deduplication process removed duplicate entries from the data set, drastically reducing the number of associations from 1,124 down to 166. No further filtering was applied beyond this step.
[target_tool]: In summary, after retrieving all initial associations and applying mechanism-of-action filtering, the list was condensed to 166 unique entries involving RET inhibitors.
----------------------------------------
Entries retrieved: 166

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165731,ret,CHEMBL24828,vandetanib,4.0,NaN,NaN,tyrosine-protein kinase receptor ret inhibitor

 Run 1 completed | rows=166 | latency=21.320s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target gene RET, specifically focusing on drugs that act as inhibitors. The first step involved retrieving all known disease–drug associations for this target, resulting in 1,124 entries.
[target_tool]: Next, the process applied a filter based on the mechanism of action. It specifically looked for inhibitors of the RET target. This filtering did not change the total number of entries, which remained at 1,124, indicating that all retrieved associations matched the specified mechanism involving inhibitors. During this step, two relevant terms were identified: "coiled-coil domain-containing protein 6/tyrosine-protein kinase receptor ret inhibitor" and "kinesin-1 heavy chain/tyrosine-protein kinase receptor ret inhibitor," both associated with RET inhibition.
[target_tool]: Subsequently, duplicate entries were removed through deduplication, reducing the number of entries from 1,124 to 166. This step eliminated repeated records, ensuring a unique set of associations.
[target_tool]: In summary, after retrieving the initial associations, filtering for inhibitors related to RET did not reduce the number of entries, but removing duplicates significantly narrowed the results to 166 unique entries.
----------------------------------------
Entries retrieved: 166

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165731,ret,CHEMBL24828,vandetanib,4.0,NaN,NaN,tyrosine-protein kinase receptor ret inhibitor

 Run 2 completed | rows=166 | latency=21.008s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target "RET" and filter these results based on specific mechanisms of action.
[target_tool]: Initially, the system retrieved 1,124 disease-drug association records for the target "RET." This step provided a comprehensive set of known associations relevant to "RET" before any further filtering.
[target_tool]: Next, the system applied a mechanism-of-action filter. It focused on associations where the mechanism was labeled as "inhibitor." Despite this filtering, the number of records remained the same, continuing with 1,124 entries. The system identified two matched terms related to "tyrosine-protein kinase receptor ret inhibitor" and similar inhibitors, indicating these were among the mechanisms considered.
[target_tool]: Finally, the system performed deduplication to remove duplicate records. This step reduced the total from 1,124 to 166 unique records, removing 958 duplicates and leaving a set of distinct disease-drug associations related to "RET" and its inhibitors.
[target_tool]: In summary, after the filtering and deduplication processes, the final dataset contained 166 unique associations.
----------------------------------------
Entries retrieved: 166

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165731,ret,CHEMBL24828,vandetanib,4.0,NaN,NaN,tyrosine-protein kinase receptor ret inhibitor

 Run 3 completed | rows=166 | latency=19.324s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
[target_tool]: The goal was to identify associations related to the target gene RET. The process started with retrieving known disease–drug associations for RET, which resulted in 1124 entries.
[target_tool]: Next, a filter was applied based on the mechanism of action, specifically focusing on inhibitors. This filtering did not change the number of entries, so the set remained at 1124 records. During this step, the system matched terms such as "coiled-coil domain-containing protein 6/tyrosine-protein kinase receptor ret inhibitor," "kinesin-1 heavy chain/tyrosine-protein kinase receptor ret inhibitor," and simply "tyrosine-protein kinase receptor ret inhibitor," indicating the focus on inhibitors of the RET receptor.
[target_tool]: Finally, the data underwent deduplication to remove duplicate entries, reducing the total from 1124 to 166 unique records. Overall, the process refined the initial broad set to a smaller, more specific group of 166 distinct entries related to RET inhibitors.
----------------------------------------
Entries retrieved: 166

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165731,ret,CHEMBL24828,vandetanib,4.0,NaN,NaN,tyrosine-protein kinase receptor ret inhibitor

 Run 4 completed | rows=166 | latency=20.063s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target "RET," focusing on known disease-drug relationships and mechanisms of action.
[target_tool]: First, the system retrieved all known associations for the target "RET," which resulted in a total of 1,124 records. This step gathered a broad dataset of potential related diseases and drugs linked to "RET."
[target_tool]: Next, the dataset was filtered based on the mechanism of action. The system specifically looked for associations involving the mechanism "inhibitor." This filtering retained only those records that described "RET" inhibitors, which matched terms such as "coiled-coil domain-containing protein 6/tyrosine-protein kinase receptor ret inhibitor" and "kinesin-1 heavy chain/tyrosine-protein kinase receptor ret inhibitor," resulting in the same number of 1,124 records. This indicates that all records already involved the specified mechanism, so the filtering did not reduce the dataset.
[target_tool]: Finally, the dataset was deduplicated to remove overlapping records, resulting in a reduced total from 1,124 to 166, meaning 958 duplicate entries were eliminated.
[target_tool]: In summary, after retrieving all associations, filtering for the "inhibitor" mechanism, and removing duplicates, the final dataset contains 166 unique records related to "RET" inhibitors.
----------------------------------------
Entries retrieved: 166

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165731,ret,CHEMBL24828,vandetanib,4.0,NaN,NaN,tyrosine-protein kinase receptor ret inhibitor

 Run 5 completed | rows=166 | latency=21.061s
------------------------------------------------------------


## Question 17

**Which pathways are associated with the TNF gene?**

In [54]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve information related to a specific target, which is TNF.
[target_tool]: First, the system retrieved pathways associated with TNF, which resulted in 10 pathways being identified. This step involved collecting pathway data linked to this target, with no previous number of rows provided for comparison.
[target_tool]: Since only pathway retrieval details are available in the log, it indicates that the pathway information was successfully collected for TNF, and the process ended with 10 pathways identified.
----------------------------------------
Entries retrieved: 10

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 1 completed | rows=10 | latency=15.994s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The query aimed to explore the biological pathways related to the target TNF. The first step involved retrieving pathways associated with TNF, which resulted in obtaining information for 10 pathways. As this was the initial retrieval step, there was no prior data to compare, but this provided a foundational set of pathways linked to the target. In summary, the final result included information on 10 pathways associated with TNF.
----------------------------------------
Entries retrieved: 10

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 2 completed | rows=10 | latency=14.312s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The query aims to explore pathways related to the target TNF. The process began with retrieving pathway information for TNF, resulting in a total of 10 pathways identified. This step did not specify a reduction in the number of pathways, but simply retrieved relevant pathway data associated with TNF. The final output includes information on these pathways, indicating that 10 pathways are linked to the target TNF.
----------------------------------------
Entries retrieved: 10

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 3 completed | rows=10 | latency=15.314s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The purpose of the query was to identify pathways associated with the target TNF. First, the system retrieved pathway information specifically related to TNF, resulting in 10 pathways. This step provided relevant biological pathways linked to the target. Since only pathway retrieval is recorded, no filtering steps are detailed. In summary, the final result includes information on 10 pathways associated with TNF.
----------------------------------------
Entries retrieved: 10

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 4 completed | rows=10 | latency=14.513s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve pathway information related to the target "TNF." In the initial step, the system retrieved pathways associated with this target. The number of pathways after this retrieval was 10. Since no previous number of pathways is provided, we understand that this was the first step in obtaining pathways related to "TNF."
[target_tool]: Overall, the final result includes 10 pathways associated with "TNF."
----------------------------------------
Entries retrieved: 10

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TNF,ENSG00000232810,R-HSA-5357786,TNFR1-induced proapoptotic signaling,Signal Transduction

 Run 5 completed | rows=10 | latency=14.558s
------------------------------------------------------------


## Question 18

**Diseases associated with the gene NPM1.**

In [55]:

question = 'Diseases associated with the gene NPM1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
[target_tool]: The query aimed to identify relevant associations related to the target NPM1.
[target_tool]: First, the system retrieved known disease–drug associations for NPM1, resulting in 85 records.
[target_tool]: Next, the system removed duplicate entries from this set, reducing the total from 85 to 36 entries.
[target_tool]: In summary, the processing resulted in 36 unique associations related to NPM1 after deduplication.
----------------------------------------
Entries retrieved: 36

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000181163        npm1  MONDO_0004992       cancer           0.708707

 Run 1 completed | rows=36 | latency=14.476s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
[target_tool]: The goal of the query was to find information related to the target "NPM1."
[target_tool]: First, the system retrieved known associations between "NPM1" and various drugs, resulting in 85 records.
[target_tool]: Next, the system removed duplicate entries from these records, reducing the total from 85 to 36. This deduplication step ensured that only unique associations remained.
[target_tool]: In summary, the final result contained 36 distinct records of associations for "NPM1" after removing duplicates.
----------------------------------------
Entries retrieved: 36

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000181163        npm1  MONDO_0004992       cancer           0.708707

 Run 2 completed | rows=36 | latency=15.946s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
[target_tool]: The query aims to find drug associations related to the target NPM1.
[target_tool]: First, the system retrieved known disease-drug associations for NPM1, resulting in 85 entries. Next, it removed duplicate records from these associations, reducing the number from 85 to 36. This deduplication step ensured that only unique associations remained.
[target_tool]: In total, after this process, the final set included 36 unique associations related to NPM1.
----------------------------------------
Entries retrieved: 36

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000181163        npm1  MONDO_0004992       cancer           0.708707

 Run 3 completed | rows=36 | latency=14.614s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target gene NPM1.
[target_tool]: First, the system retrieved known disease–drug associations for NPM1, which initially resulted in 85 entries.
[target_tool]: Next, duplicate entries within this dataset were removed to ensure each association was unique, reducing the number from 85 to 36 entries.
[target_tool]: A total of 49 duplicate records were eliminated during this deduplication step.
[target_tool]: In conclusion, the final dataset contains 36 unique disease–drug associations related to NPM1.
----------------------------------------
Entries retrieved: 36

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000181163        npm1  MONDO_0004992       cancer           0.708707

 Run 4 completed | rows=36 | latency=15.398s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
[target_tool]: The goal of this query was to find associations related to the target NPM1. The process began with retrieving baseline associations for NPM1, resulting in 85 entries. Next, the system performed deduplication to eliminate duplicate records, reducing the number of associations from 85 to 36. Overall, the final result consists of 36 unique associations linked to NPM1.
----------------------------------------
Entries retrieved: 36

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000181163        npm1  MONDO_0004992       cancer           0.708707

 Run 5 completed | rows=36 | latency=15.459s
------------------------------------------------------------


## Question 19

**Which pathways are associated with the CD19 gene?**

In [56]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target CD19, including associated pathways. In the first step, the system retrieved pathways linked to the target CD19. Since this was the initial pathway retrieval, there was no previous number of rows to compare, but after this step, six pathways were identified. This provided a set of pathway data relevant to CD19. Overall, the final result includes the six pathways associated with the target CD19.
----------------------------------------
Entries retrieved: 6

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 1 completed | rows=6 | latency=15.801s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to gather information related to pathways associated with the target CD19.
[target_tool]: The process started with retrieving pathways for the target CD19, leading to a total of 6 pathways being identified. Since this step was focused solely on retrieving pathway data, it did not reduce any previous result set but provided relevant pathway information for the target.
[target_tool]: The final result includes information on 6 pathways related to CD19.
----------------------------------------
Entries retrieved: 6

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 2 completed | rows=6 | latency=13.651s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target CD19.
[target_tool]: The only step in the execution involved pathway retrieval, where pathways associated with the target CD19 were retrieved. This step resulted in identifying 6 pathways linked to this target. No previous step or filtering was applied before this retrieval in the provided log.
[target_tool]: In total, this process brought back 6 pathways associated with CD19.
----------------------------------------
Entries retrieved: 6

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 3 completed | rows=6 | latency=14.347s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aims to gather pathway information related to the target CD19. First, the system retrieved pathways associated with CD19, resulting in a total of 6 pathways. Since no previous result count is provided, we only know the final number of pathways after retrieval. In summary, the process concluded with identifying 6 pathways linked to the target CD19.
----------------------------------------
Entries retrieved: 6

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 4 completed | rows=6 | latency=13.538s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target CD19. The first step involved retrieving pathway data associated with CD19, which resulted in six pathways being identified. This step did not involve filtering, so the number of pathways increased from an unspecified initial number to six. In summary, the pathway retrieval step provided six pathways related to CD19 for further analysis.
----------------------------------------
Entries retrieved: 6

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CD19,ENSG00000177455,R-HSA-977606,Regulation of Complement cascade,Immune System

 Run 5 completed | rows=6 | latency=13.308s
------------------------------------------------------------


## Question 20

**Which drugs are used for treating migraine?**

In [57]:

question = 'Which drugs are used for treating migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating migraine?
  Attempt 1/3
[disease_tool]: The query aimed to find associations related to migraine, specifically focusing on disease–drug relationships.
[disease_tool]: First, the system retrieved a set of 1,226 disease association records connected to migraine. This step gathered all known disease-related data relevant to the target condition.
[disease_tool]: Next, the system removed duplicate entries from this dataset. After deduplication, the number of records was reduced from 1,226 to 1,046, removing 180 duplicate rows to ensure more accurate results.
[disease_tool]: In total, the final result contains 1,046 unique disease association records related to migraine.
----------------------------------------
Entries retrieved: 1046

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL220492,topiramate,MONDO_0005277,migraine disorder,3.0,Completed,Small molecule,sodium channel alpha subunit blocker,0.868526

 Run 1 completed | rows=1046 | latency=16.085s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating migraine?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to the disease migraine.
[disease_tool]: First, the system retrieved known disease–drug associations for migraine, resulting in a set of 1,226 entries.
[disease_tool]: Next, to improve accuracy, it removed duplicate records from this set. This deduplication process reduced the number of entries from 1,226 to 1,046, by eliminating 180 duplicate rows.
[disease_tool]: In summary, the final result of the process is a refined set of 1,046 unique associations related to migraine.
----------------------------------------
Entries retrieved: 1046

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL220492,topiramate,MONDO_0005277,migraine disorder,3.0,Completed,Small molecule,sodium channel alpha subunit blocker,0.868526

 Run 2 completed | rows=1046 | latency=16.130s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating migraine?
  Attempt 1/3
[disease_tool]: This query aims to find associations related to migraine. First, the system retrieved a set of known disease-drug associations related to migraine, resulting in 1,226 entries. Then, to ensure the data was free of duplicates, the system performed deduplication, reducing the number of entries from 1,226 to 1,046. In summary, the final dataset contains 1,046 unique association records related to migraine.
----------------------------------------
Entries retrieved: 1046

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL220492,topiramate,MONDO_0005277,migraine disorder,3.0,Completed,Small molecule,sodium channel alpha subunit blocker,0.868526

 Run 3 completed | rows=1046 | latency=17.527s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating migraine?
  Attempt 1/3
[disease_tool]: The goal of the query was to find information related to migraine.
[disease_tool]: The first step retrieved known disease–drug associations related to migraine, resulting in 1,226 entries. This provided a broad set of data linking diseases and drugs associated with migraine.
[disease_tool]: Next, the system performed a deduplication process to remove any duplicate rows from the results. After this step, the number of entries was reduced from 1,226 to 1,046, removing 180 duplicate records to ensure the data was unique.
[disease_tool]: In total, this process resulted in 1,046 unique entries related to migraine after retrieving and filtering the initial data.
----------------------------------------
Entries retrieved: 1046

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL220492,topiramate,MONDO_0005277,migraine disorder,3.0,Completed,Small molecule,sodium channel alpha subunit blocker,0.868526

 Run 4 completed | rows=1046 | latency=18.344s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating migraine?
  Attempt 1/3
[disease_tool]: The query aimed to find related details connected to the disease migraine.
[disease_tool]: First, the system retrieved known disease-drug associations related to migraine, which resulted in 1,226 entries. This step involved obtaining all potential associations without filtering.
[disease_tool]: Next, the system removed duplicate entries from this initial set, reducing the number of results from 1,226 to 1,046. This duplication removal helped refine the list by eliminating overlapping records, resulting in a slightly smaller, more precise dataset.
[disease_tool]: In summary, after these steps, the final dataset contained 1,046 unique disease association entries related to migraine.
----------------------------------------
Entries retrieved: 1046

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL220492,topiramate,MONDO_0005277,migraine disorder,3.0,Completed,Small molecule,sodium channel alpha subunit blocker,0.868526

 Run 5 completed | rows=1046 | latency=16.605s
------------------------------------------------------------


## Question 21

**What are the targets and mechanisms for rituximab?**

In [58]:

question = 'What are the targets and mechanisms for rituximab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
[drug_tool]: The intent of the query was to retrieve associations of the drug rituximab with diseases or other biological entities.
[drug_tool]: First, the system retrieved the base drug associations for rituximab, which resulted in 599 records. This step involved gathering all related data points before any filtering.
[drug_tool]: Next, the system performed deduplication to remove duplicate entries, which greatly reduced the number of records from 599 down to just 1. This means all duplicate entries were identified and eliminated, leaving only unique association data.
[drug_tool]: In summary, the process resulted in a single unique association record for rituximab after filtering out duplicates.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000156738,ms4a1,CHEMBL1201576,rituximab,b-lymphocyte antigen cd20 binding agent,DailyMed

 Run 1 completed | rows=1 | latency=16.749s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
[drug_tool]: The query aims to find drug associations related to rituximab.
[drug_tool]: First, the system retrieved known drug associations for rituximab, resulting in a total of 599 entries.
[drug_tool]: Next, the data underwent deduplication to remove duplicate records, which reduced the list from 599 entries down to just 1.
[drug_tool]: In summary, after retrieving the association data and removing duplicates, only a single unique record remained.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000156738,ms4a1,CHEMBL1201576,rituximab,b-lymphocyte antigen cd20 binding agent,DailyMed

 Run 2 completed | rows=1 | latency=16.320s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
[drug_tool]: The goal of the query was to find drug associations related to rituximab.
[drug_tool]: First, the system retrieved known drug associations for rituximab, which resulted in 599 rows of data.
[drug_tool]: Next, the system performed a deduplication process to eliminate duplicate records, reducing the number of results significantly from 599 down to just 1 row.
[drug_tool]: In summary, after these steps, only one unique association related to rituximab remained.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000156738,ms4a1,CHEMBL1201576,rituximab,b-lymphocyte antigen cd20 binding agent,DailyMed

 Run 3 completed | rows=1 | latency=16.625s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve information about drugs, specifically focusing on rituximab.
[drug_tool]: First, the system retrieved the base drug associations related to rituximab. This initial step resulted in 599 records.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries from this set. As a result, only 1 unique record remained after eliminating the 598 duplicate rows.
[drug_tool]: In summary, the final data set contains a single, unique record related to rituximab after removing duplicates.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000156738,ms4a1,CHEMBL1201576,rituximab,b-lymphocyte antigen cd20 binding agent,DailyMed

 Run 4 completed | rows=1 | latency=15.595s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
[drug_tool]: The query aims to find information related to the drug rituximab in the context of its disease associations. Initially, the system retrieved known associations between drugs and diseases related to rituximab, resulting in 599 entries.
[drug_tool]: Next, the system performed deduplication to eliminate any duplicate records, which drastically reduced the list from 599 entries down to just 1. This step ensured that only unique associations remained for further analysis, if needed.
[drug_tool]: Overall, the final result counts a single unique association related to rituximab after filtering for duplicates.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000156738,ms4a1,CHEMBL1201576,rituximab,b-lymphocyte antigen cd20 binding agent,DailyMed

 Run 5 completed | rows=1 | latency=18.228s
------------------------------------------------------------


## Question 22

**Provide target names for colorectal cancer?**

In [59]:

question = 'Provide target names for colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aims to find detailed information related to colorectal cancer. First, the system retrieved known disease–drug associations for colorectal cancer, resulting in 4,922 entries.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate records, reducing the number of entries from 4,922 to 448. This step helped eliminate redundant information, ensuring the dataset contains unique records.
[disease_tool]: In summary, after filtering and deduplicating the data, the system has narrowed the result set down to 448 unique disease–drug association records related to colorectal cancer.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 1 completed | rows=448 | latency=18.660s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for colorectal cancer?
  Attempt 1/3
[disease_tool]: This query aimed to identify disease-associated data related to colorectal cancer.
[disease_tool]: First, the system retrieved a set of known disease–drug associations related to colorectal cancer, resulting in 4,922 rows of data. Next, the system removed duplicate entries from this set, which reduced the number of records from 4,922 to 448.
[disease_tool]: In summary, after filtering for unique disease–drug associations specifically associated with colorectal cancer, the final dataset contained 448 entries.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 2 completed | rows=448 | latency=19.369s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aimed to find information relating to colorectal cancer and its associated drugs or mechanisms.
[disease_tool]: First, the system retrieved known disease–drug association data for colorectal cancer, resulting in 4,922 entries. This step provided a broad set of potential associations related to the disease.
[disease_tool]: Next, the system performed a deduplication process to eliminate duplicate records from the dataset. After removing duplicates, the number of entries was reduced from 4,922 to 448. This significantly narrowed the dataset to unique records, making subsequent analysis more precise.
[disease_tool]: In summary, the process started with roughly 4,922 known associations and ended with 448 unique entries after removing duplicates, focusing the results on distinct disease-drug-related associations for colorectal cancer.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 3 completed | rows=448 | latency=19.471s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for colorectal cancer?
  Attempt 1/3
[disease_tool]: This query was designed to explore the associations related to colorectal cancer.
[disease_tool]: First, the system retrieved known disease–drug associations specifically for colorectal cancer. This initial retrieval produced a set of 4,922 entries.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate records from this set. After this process, the number of entries was reduced from 4,922 to 448, eliminating 4,474 duplicate records.
[disease_tool]: In summary, the final result contains 448 unique entries related to disease-drug associations for colorectal cancer.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 4 completed | rows=448 | latency=17.776s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aims to retrieve information related to colorectal cancer and its associated drugs and pathways.
[disease_tool]: Initially, the system retrieved known association data for the disease colorectal cancer, which resulted in 4,922 entries. This step collected all potential disease-related associations before any filtering.
[disease_tool]: Next, the system removed duplicate rows from this set to improve data clarity and accuracy. This deduplication process reduced the number of entries from 4,922 to 448, eliminating 4,474 duplicate records.
[disease_tool]: The final result after these steps is 448 unique entries related to colorectal cancer associations, providing a refined and more accurate dataset for further analysis.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 5 completed | rows=448 | latency=17.407s
------------------------------------------------------------


## Question 23

**Which are possible drugs against rickets?**

In [60]:

question = 'Which are possible drugs against rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which are possible drugs against rickets?
  Attempt 1/3
[disease_tool]: The query's goal was to find information related to the disease rickets. To start, the system retrieved known disease–drug associations for this disease. This initial step resulted in 15 associations being identified, reducing the dataset from an unspecified larger set to these 15 entries. No further filtering steps or additional details were provided, so the process focused on this initial retrieval. In summary, the final result included 15 associations related to rickets.
----------------------------------------
Entries retrieved: 15

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL3707326,burosumab,EFO_0005583,rickets,4.0,NaN,Antibody,fibroblast growth factor 23 inhibitor,0.787893

 Run 1 completed | rows=15 | latency=16.345s
------------------------------------------------------------

 Starting run 2 for query: Which are possible drugs against rickets?
  Attempt 1/3
[disease_tool]: The goal of the query was to retrieve information related to the disease rickets.
[disease_tool]: The first step involved retrieving known disease–drug associations for rickets. This step collected all the relevant associations, resulting in a set of 15 records.
[disease_tool]: No further filtering steps are listed in the provided log, so the final result consists of these 15 entries related to disease–drug associations for rickets.
----------------------------------------
Entries retrieved: 15

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL3707326,burosumab,EFO_0005583,rickets,4.0,NaN,Antibody,fibroblast growth factor 23 inhibitor,0.787893

 Run 2 completed | rows=15 | latency=16.593s
------------------------------------------------------------

 Starting run 3 for query: Which are possible drugs against rickets?
  Attempt 1/3
[disease_tool]: The query aimed to explore disease-related data about rickets, focusing on understanding its associations.
[disease_tool]: The first step involved retrieving known disease-drug associations related to rickets. This initial retrieval brought back a total of 15 entries. Since this was the first step, there was no reduction from a prior result set to mention.
[disease_tool]: Overall, the process resulted in a set of 15 disease association entries concerning rickets.
----------------------------------------
Entries retrieved: 15

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL3707326,burosumab,EFO_0005583,rickets,4.0,NaN,Antibody,fibroblast growth factor 23 inhibitor,0.787893

 Run 3 completed | rows=15 | latency=14.740s
------------------------------------------------------------

 Starting run 4 for query: Which are possible drugs against rickets?
  Attempt 1/3
[disease_tool]: The query aimed to identify information related to the disease rickets and its associated drugs or mechanisms. The first step involved retrieving known disease–drug associations related to the disease rickets. This initial retrieval provided 15 entries, focusing on the disease in question.
[disease_tool]: Since only one step is shown in the provided log, it appears that the process involved fetching associated data for rickets, resulting in a total of 15 records. This indicates that the system gathered all known associations related to rickets before further filtering or analysis.
----------------------------------------
Entries retrieved: 15

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL3707326,burosumab,EFO_0005583,rickets,4.0,NaN,Antibody,fibroblast growth factor 23 inhibitor,0.787893

 Run 4 completed | rows=15 | latency=16.258s
------------------------------------------------------------

 Starting run 5 for query: Which are possible drugs against rickets?
  Attempt 1/3
[disease_tool]: The query aimed to find drug associations related to the disease rickets.
[disease_tool]: Initially, the system retrieved known disease–drug associations specifically for rickets, which resulted in 15 associations being identified.
[disease_tool]: This was the first filtering step, establishing a base set of 15 potential drug relationships for further filtering or analysis.
[disease_tool]: Since only one step is documented in the provided log, the process concluded with 15 identified associations related to rickets.
----------------------------------------
Entries retrieved: 15

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL3707326,burosumab,EFO_0005583,rickets,4.0,NaN,Antibody,fibroblast growth factor 23 inhibitor,0.787893

 Run 5 completed | rows=15 | latency=14.812s
------------------------------------------------------------


## Question 24

**Give me genes linked to epilepsy.**

In [61]:

question = 'Give me genes linked to epilepsy.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Give me genes linked to epilepsy.
  Attempt 1/3
[disease_tool]: The purpose of the query was to explore associations related to epilepsy. First, the system retrieved known disease–drug associations for epilepsy, resulting in 2,908 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records. This step reduced the number of entries significantly from 2,908 down to 300. The overall process narrowed the initial set of data to a more concise list of unique records related to epilepsy.
----------------------------------------
Entries retrieved: 300

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000144285,scn1a,EFO_0000474,epilepsy,Small molecule,0.926469

 Run 1 completed | rows=300 | latency=16.268s
------------------------------------------------------------

 Starting run 2 for query: Give me genes linked to epilepsy.
  Attempt 1/3
[disease_tool]: This query aims to find associations related to epilepsy. First, the system retrieved a large set of disease–drug associations specifically linked to epilepsy, resulting in 2,908 records. Next, it removed duplicate entries from this set, reducing the total number of associations from 2,908 to 300. In summary, the final dataset contains 300 unique disease association records for epilepsy.
----------------------------------------
Entries retrieved: 300

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000144285,scn1a,EFO_0000474,epilepsy,Small molecule,0.926469

 Run 2 completed | rows=300 | latency=18.079s
------------------------------------------------------------

 Starting run 3 for query: Give me genes linked to epilepsy.
  Attempt 1/3
[disease_tool]: The goal of the query was to find drug associations related to the disease epilepsy.
[disease_tool]: Initially, the system retrieved a set of known disease-drug associations specific to epilepsy, resulting in 2,908 entries. This step gathered all relevant records linking epilepsy to various drugs.
[disease_tool]: Next, the system removed duplicate entries from this data, reducing the total from 2,908 to 300. This deduplication process eliminated 2,608 identical records, leaving a set of unique associations.
[disease_tool]: In summary, after these steps, the final result includes 300 distinct records associating drugs with epilepsy.
----------------------------------------
Entries retrieved: 300

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000144285,scn1a,EFO_0000474,epilepsy,Small molecule,0.926469

 Run 3 completed | rows=300 | latency=18.598s
------------------------------------------------------------

 Starting run 4 for query: Give me genes linked to epilepsy.
  Attempt 1/3
[disease_tool]: The query was designed to find associations related to epilepsy and then refine these results. First, the system retrieved known disease–drug associations related to epilepsy, resulting in a total of 2,908 entries. This initial retrieval gathered all known associations for the disease in question. Next, the system removed duplicate records from these 2,908 entries to ensure the final data was unique. After this deduplication step, the number of entries was reduced to 300. In summary, the process resulted in 300 unique disease–drug association records related to epilepsy.
----------------------------------------
Entries retrieved: 300

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000144285,scn1a,EFO_0000474,epilepsy,Small molecule,0.926469

 Run 4 completed | rows=300 | latency=18.089s
------------------------------------------------------------

 Starting run 5 for query: Give me genes linked to epilepsy.
  Attempt 1/3
[disease_tool]: The user query involves exploring biological data related to epilepsy. The process began by retrieving known disease–drug associations for epilepsy. This initial step resulted in 2,908 rows of data.
[disease_tool]: Next, the data underwent deduplication to remove any duplicate entries. This step significantly reduced the total number of records from 2,908 to 300. The deduplication process removed 2,608 duplicate rows, leaving a streamlined set of 300 unique entries for further analysis.
----------------------------------------
Entries retrieved: 300

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000144285,scn1a,EFO_0000474,epilepsy,Small molecule,0.926469

 Run 5 completed | rows=300 | latency=17.709s
------------------------------------------------------------


## Question 25

**What diseases are treated with trastuzumab deruxtecan?**

In [62]:

question = 'What diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to a specific drug. The first step involved retrieving known associations between diseases and drugs for trastuzumab deruxtecan. This retrieval process resulted in 92 associations, focusing on the target drug.
[drug_tool]: Next, the filtering process was applied based on specific diseases. However, the details for the disease filter and how many associations remained after this step are not provided in the log.
[drug_tool]: Following this, drug-specific filtering was conducted, potentially narrowing the list further by focusing on certain drugs or synonyms. Again, the exact number of remaining associations after this filter is not given.
[drug_tool]: Subsequently, a mechanism-of-action filter was applied to refine the results based on how the drug functions, but the specific impact on the association count is not detailed.
[drug_tool]: Deduplification was performed to remove any duplicate records, ensuring the results were unique.
[drug_tool]: Finally, pathway information related to the drug was retrieved, although the details of this step do not specify how many associations were affected.
[drug_tool]: In total, the process started with a set of known disease–drug associations for trastuzumab deruxtecan and, after various filtering and processing steps, the resulting dataset contained 92 entries.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,trastuzumab deruxtecan,MONDO_0007254,breast cancer,4,Not yet recruiting,dna topoisomerase i inhibitor,FDA

 Run 1 completed | rows=92 | latency=16.398s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug associations related to trastuzumab deruxtecan. First, the system retrieved known disease–drug associations for this drug, resulting in 92 entries. This initial step provided the foundational data for further filtering and analysis. Since no additional filters or steps are shown in the log, the process concludes with a dataset of 92 associations.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,trastuzumab deruxtecan,MONDO_0007254,breast cancer,4,Not yet recruiting,dna topoisomerase i inhibitor,FDA

 Run 2 completed | rows=92 | latency=17.516s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug trastuzumab deruxtecan, including its associations with diseases and mechanisms of action.
[drug_tool]: First, the system retrieved the known associations between drugs and diseases for trastuzumab deruxtecan, which resulted in 92 entries. This step gathered all the relevant known links involving this specific drug and diseases.
[drug_tool]: Since no further filtering steps are shown in the provided log, the process concluded with these 92 associated records.
[drug_tool]: Overall, the final result comprises 92 entries related to trastuzumab deruxtecan's known disease associations.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,trastuzumab deruxtecan,MONDO_0007254,breast cancer,4,Not yet recruiting,dna topoisomerase i inhibitor,FDA

 Run 3 completed | rows=92 | latency=15.185s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The process began with retrieving known disease–drug associations for the drug trastuzumab deruxtecan. This initial step resulted in 92 entries, which represent different disease associations related to this drug.
[drug_tool]: Next, the system applied a disease filter to narrow down these associations to specific diseases of interest. This step reduced the number of associations, although the exact new total is not specified in the log. The filter likely used particular disease terms or criteria to focus the results.
[drug_tool]: Following this, a drug filter was applied to select associations involving specific drugs. This filter further refined the dataset, although the exact number of remaining associations isn't provided. The filter would have considered drug synonyms or related terms to include all relevant entries.
[drug_tool]: Subsequently, a mechanism filter was used to narrow down associations based on the mechanism of action. This step limited the results to those matching particular mechanisms, helping to focus on specific biological pathways or effects.
[drug_tool]: The data then went through a deduplication process, which removed duplicate records to ensure each association was unique.
[drug_tool]: Finally, pathway retrieval was performed to gather information about biological pathways involved, although this step did not explicitly reduce the number of entries.
[drug_tool]: In total, the process began with 92 associations related to trastuzumab deruxtecan and was progressively filtered to arrive at a more focused set of results, though the exact final count after all filters is not specified in the provided details.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,trastuzumab deruxtecan,MONDO_0007254,breast cancer,4,Not yet recruiting,dna topoisomerase i inhibitor,FDA

 Run 4 completed | rows=92 | latency=16.431s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
[drug_tool]: The query aims to retrieve information related to the drug trastuzumab deruxtecan and its associations with diseases. The first step involved retrieving known associations between this drug and various diseases. After this retrieval, the total number of association records was 92. There were no prior rows mentioned, indicating this was the initial data collection. No further filtering steps are described, so the process concludes with 92 associations related to trastuzumab deruxtecan.
----------------------------------------
Entries retrieved: 92

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297844,trastuzumab deruxtecan,MONDO_0007254,breast cancer,4,Not yet recruiting,dna topoisomerase i inhibitor,FDA

 Run 5 completed | rows=92 | latency=15.750s
------------------------------------------------------------


## Question 26

**Genes linked to Alzheimer’s disease.**

In [63]:

question = 'Genes linked to Alzheimer’s disease.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
[disease_tool]: The query was designed to find information related to Alzheimer's disease and its associated drugs and mechanisms. First, the system retrieved known disease–drug associations for Alzheimer's disease, which resulted in 671 entries. Next, it removed duplicate records from this set, reducing the number of entries from 671 to 187. In summary, after these steps, 187 unique records remain that relate Alzheimer's disease to various drugs and mechanisms.
----------------------------------------
Entries retrieved: 187

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000080815,psen1,MONDO_0004975,alzheimer disease,Small molecule,0.867114

 Run 1 completed | rows=187 | latency=19.850s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
[disease_tool]: No resolved disease found.
----------------------------------------
[disease_tool]: The query appears to aim at retrieving specific biomedical information, but no execution steps or details were provided in the log. Consequently, I am unable to describe the processing steps or how filters were applied. Based on the information given, no further analysis or explanation can be provided.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 21.165s: Returned object is not a DataFrame
  Attempt 2/3
[disease_tool]: No resolved disease found.
----------------------------------------
[disease_tool]: The query aimed to identify associations between a specific disease and drugs, including their mechanisms and pathways.
[disease_tool]: Since the execution log is empty, no processing steps were performed. This means that no data was retrieved, filtered, or refined within the system.
[disease_tool]: Consequently, there are no results or further details to report.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: No resolved disease found.
----------------------------------------
 Attempt 2 failed after 30.005s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: No resolved disease found.
----------------------------------------
[disease_tool]: The query aims to identify disease–drug associations based on specific filtering criteria.
[disease_tool]: Since the execution log is empty, it indicates that no steps were performed during the process. Therefore, no associations, diseases, drugs, mechanisms, or pathways were retrieved or filtered.
[disease_tool]: In conclusion, the final result consists of zero records due to the absence of execution steps.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The goal of the query was to identify disease–drug associations related to Alzheimer's disease. First, the system retrieved known disease associations for Alzheimer's disease, resulting in 671 entries. Next, the system performed deduplication to remove duplicate records, reducing the total from 671 to 187 unique entries.
[disease_tool]: In total, after these steps, the resulting dataset contained 187 unique associations related to Alzheimer's disease.
----------------------------------------
 Attempt 3 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
 Run 2 failed after 3 attempts
------------------------------------------------------------

 Starting run 3 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
[disease_tool]: No resolved disease found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[disease_tool]: No resolved disease found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: This query was intended to explore the connections between specific diseases, drugs, and their mechanisms of action. However, the execution log provided shows no recorded steps. As a result, no retrievals, filters, or reductions occurred during processing. Since no steps were executed, there are no details to describe about how the data was narrowed down or processed. The final result would therefore be based on the initial dataset without any filtering.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 2 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: No resolved disease found.
----------------------------------------
[disease_tool]: The query aimed to identify specific biomedical insights, but the execution log provided does not include any recorded steps detailing how the data was processed. As a result, there is no information available to explain the step-by-step processing of the query or how filters and other procedures influenced the final set of results. Therefore, it is not possible to describe the data processing sequence or the final result count based on the provided information.
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The system was expected to process a biomedical query, but the execution log contains no steps. This means that no specific retrievals or filters were executed. As a result, there is no information available about how any data was gathered or narrowed down. Consequently, there is no count of results or further details to be provided.
----------------------------------------
[target_tool]: The query aims to find information related to a biomedical topic, but the execution log does not include any specific steps.
[target_tool]: Since no steps are provided, it appears that the system did not perform any data retrieval, filtering, or processing actions. As a result, there is no information on disease filters, drug filters, mechanism-of-action filters, deduplication, or pathway retrieval.
[target_tool]: In summary, without specific execution steps, no results were processed or refined, leaving the final count of data entries unspecified.
----------------------------------------
 Attempt 3 failed after 30.002s: OpenTargets query exceeded 30.0 seconds
 Run 3 failed after 3 attempts
------------------------------------------------------------

 Starting run 4 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
[disease_tool]: The query aimed to identify associations related to Alzheimer's disease. First, the system retrieved known disease–drug associations related to Alzheimer's disease, resulting in 671 entries. Next, it removed duplicate records, which reduced the total from 671 to 187 unique entries. In summary, after these steps, 187 unique disease–drug association entries for Alzheimer's disease remained.
----------------------------------------
Entries retrieved: 187

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000080815,psen1,MONDO_0004975,alzheimer disease,Small molecule,0.867114

 Run 4 completed | rows=187 | latency=15.459s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to Alzheimer's disease.
[disease_tool]: First, the system retrieved the known associations between diseases and drugs specifically for Alzheimer's disease. This step resulted in 671 rows of data.
[disease_tool]: Next, the system performed deduplication to remove any duplicate records from this dataset. After this process, the number of entries was reduced from 671 to 187, eliminating 484 duplicate rows.
[disease_tool]: In summary, the final result includes 187 unique associations related to Alzheimer's disease after filtering for duplicates.
----------------------------------------
Entries retrieved: 187

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000080815,psen1,MONDO_0004975,alzheimer disease,Small molecule,0.867114

 Run 5 completed | rows=187 | latency=15.537s
------------------------------------------------------------


## Question 27

**For which disease is darolutamide used?**

In [64]:

question = 'For which disease is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which disease is darolutamide used?
  Attempt 1/3
[drug_tool]: The query was designed to explore information related to the drug darolutamide. The first step retrieved known associations between drugs and diseases related to darolutamide. After this retrieval, the initial data was reduced to 39 entries from an unspecified larger set.
[drug_tool]: Since there was only one step shown, this indicates the system now has a list of 39 associations involving darolutamide to work with further. The process has successfully narrowed down the dataset to this specific number of associations for subsequent analysis or filtering.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,darolutamide,EFO_0000616,neoplasm,4.0,NaN,androgen receptor antagonist,"Other, PubMed"

 Run 1 completed | rows=39 | latency=14.598s
------------------------------------------------------------

 Starting run 2 for query: For which disease is darolutamide used?
  Attempt 1/3
[drug_tool]: The purpose of the query is to find relevant information related to the drug darolutamide.
[drug_tool]: Initially, the system retrieved known disease–drug associations related to darolutamide. This step resulted in a dataset of 39 association records.
[drug_tool]: Next, no additional filters or steps are detailed within this specific segment of the execution log. Therefore, the process concluded with 39 records related to darolutamide.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,darolutamide,EFO_0000616,neoplasm,4.0,NaN,androgen receptor antagonist,"Other, PubMed"

 Run 2 completed | rows=39 | latency=14.080s
------------------------------------------------------------

 Starting run 3 for query: For which disease is darolutamide used?
  Attempt 1/3
[drug_tool]: The query aims to find information related to the drug darolutamide.
[drug_tool]: Initially, the system retrieved known disease–drug associations for darolutamide, resulting in 39 entries. This step pulled all the initial data related to how darolutamide is associated with various diseases.
[drug_tool]: The next steps, such as filtering by disease, drug, mechanism, or pathway, are not shown in this snippet, so it appears that only the association retrieval was executed so far.
[drug_tool]: In total, 39 associations related to darolutamide were identified at this stage.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,darolutamide,EFO_0000616,neoplasm,4.0,NaN,androgen receptor antagonist,"Other, PubMed"

 Run 3 completed | rows=39 | latency=14.299s
------------------------------------------------------------

 Starting run 4 for query: For which disease is darolutamide used?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to darolutamide. The first step involved retrieving all known diseases and drugs associated with darolutamide, which initially resulted in a list of unknown size. After this retrieval, the dataset was limited to 39 entries, indicating that 39 disease–drug associations involving darolutamide were identified. No further filtering steps are detailed in this log, so the final result comprises these 39 associations.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,darolutamide,EFO_0000616,neoplasm,4.0,NaN,androgen receptor antagonist,"Other, PubMed"

 Run 4 completed | rows=39 | latency=15.840s
------------------------------------------------------------

 Starting run 5 for query: For which disease is darolutamide used?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug associations related to darolutamide. First, the system retrieved the known associations between the drug darolutamide and various disease targets. This initial retrieval resulted in a set of 39 association entries. No further filtering or refinement steps are shown in this part of the process, so the initial set remains at 39 entries. In summary, the process produced a final result set of 39 entries related to darolutamide.
----------------------------------------
Entries retrieved: 39

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL4297185,darolutamide,EFO_0000616,neoplasm,4.0,NaN,androgen receptor antagonist,"Other, PubMed"

 Run 5 completed | rows=39 | latency=15.203s
------------------------------------------------------------


## Question 28

**Provide target names for renal cell carcinoma?**

In [65]:

question = 'Provide target names for renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
[disease_tool]: The query aims to identify disease–drug associations related to renal cell carcinoma.
[disease_tool]: First, the system retrieved the known disease associations for renal cell carcinoma, resulting in a total of 2,163 entries. This step gathered all potential associations from the database relevant to the specified disease.
[disease_tool]: Next, the system performed deduplication to eliminate duplicate records from the retrieved data, reducing the total from 2,163 down to 232 entries. This step removed 1,931 duplicate records, leaving only unique association entries.
[disease_tool]: In summary, after retrieving and cleaning the data, the final set contains 232 unique disease–drug association records related to renal cell carcinoma.
----------------------------------------
Entries retrieved: 232

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000105976,met,EFO_0000681,renal cell carcinoma,Small molecule,0.888778

 Run 1 completed | rows=232 | latency=21.058s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
[disease_tool]: The query aims to identify associations related to renal cell carcinoma.
[disease_tool]: Initially, the system retrieved a broad set of known disease–drug associations related to renal cell carcinoma. This step resulted in 2,163 records, capturing various potential relationships involving this disease.
[disease_tool]: Next, the system performed a deduplication process to eliminate duplicate entries within the retrieved data. This step reduced the total number of records from 2,163 to 232, removing 1,931 duplicate entries to ensure the data set contained only unique association records.
[disease_tool]: In summary, after these steps, the final result consisted of 232 unique disease–drug association records related to renal cell carcinoma.
----------------------------------------
Entries retrieved: 232

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000105976,met,EFO_0000681,renal cell carcinoma,Small molecule,0.888778

 Run 2 completed | rows=232 | latency=15.145s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
[disease_tool]: The goal of this query was to identify disease and drug associations related to renal cell carcinoma.
[disease_tool]: First, the system retrieved known disease–drug associations for renal cell carcinoma, which initially resulted in 2,163 entries. This step pulled together all relevant data points connected to this specific disease.
[disease_tool]: Next, the system performed a deduplication step to remove duplicate entries, reducing the total from 2,163 to 232 unique records. This process filtered out repeated data, leaving a set of distinct association records.
[disease_tool]: In summary, after these steps, there are 232 unique disease–drug association entries pertaining to renal cell carcinoma.
----------------------------------------
Entries retrieved: 232

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000105976,met,EFO_0000681,renal cell carcinoma,Small molecule,0.888778

 Run 3 completed | rows=232 | latency=17.032s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
[disease_tool]: The query aims to identify relevant disease and drug associations related to renal cell carcinoma.
[disease_tool]: Initially, the system retrieved known disease–drug associations for renal cell carcinoma, resulting in a total of 2,163 entries. This step gathered all known links between the disease and various drugs from the database.
[disease_tool]: Next, the system performed a deduplication step to remove duplicate records from this set. After removing duplicates, the number of entries was reduced to 232, meaning 1,931 duplicate entries were eliminated. This ensures that each association is unique and prevents redundant data from affecting subsequent analysis.
[disease_tool]: In summary, after the initial retrieval and cleaning, there are 232 unique disease–drug association entries related to renal cell carcinoma.
----------------------------------------
Entries retrieved: 232

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000105976,met,EFO_0000681,renal cell carcinoma,Small molecule,0.888778

 Run 4 completed | rows=232 | latency=18.166s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease associations related to renal cell carcinoma. First, the system retrieved known disease–drug associations specifically for renal cell carcinoma, resulting in 2,163 records. Next, it performed deduplication to remove any duplicate entries, reducing the total number of records from 2,163 to 232. In the end, the final dataset contains 232 unique disease–drug association records related to renal cell carcinoma.
----------------------------------------
Entries retrieved: 232

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000105976,met,EFO_0000681,renal cell carcinoma,Small molecule,0.888778

 Run 5 completed | rows=232 | latency=16.881s
------------------------------------------------------------


## Question 29

**Diseases associated with the gene KRAS.**

In [66]:

question = 'Diseases associated with the gene KRAS.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
[target_tool]: The query aims to find associations related to the target "KRAS".
[target_tool]: Initially, the system retrieved known disease–drug associations for KRAS, which resulted in 35 entries. Then, to remove duplicate records, the system performed a deduplication step, reducing the number of entries from 35 to 11 distinct associations.
[target_tool]: In summary, the final result after deduplication includes 11 unique associations related to KRAS.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000133703,kras,EFO_0003060,non-small cell lung carcinoma,0.778862

 Run 1 completed | rows=11 | latency=15.506s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
[target_tool]: The query aimed to identify relevant drug associations for the target KRAS.
[target_tool]: First, the system retrieved known disease–drug associations related to KRAS, resulting in 35 records. Next, it performed deduplication to remove any duplicate entries, reducing the number of records from 35 to 11.
[target_tool]: Thus, the final result includes 11 unique association records for KRAS after filtering out duplicates.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000133703,kras,EFO_0003060,non-small cell lung carcinoma,0.778862

 Run 2 completed | rows=11 | latency=14.436s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
[target_tool]: The query aimed to find known associations related to the target gene KRAS.
[target_tool]: First, the system retrieved all known disease–drug associations for KRAS, which initially produced 35 entries.
[target_tool]: Next, the system removed duplicate records from these associations, reducing the total from 35 to 11 entries.
[target_tool]: In total, after these steps, there are 11 unique associations related to KRAS.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000133703,kras,EFO_0003060,non-small cell lung carcinoma,0.778862

 Run 3 completed | rows=11 | latency=16.723s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
[target_tool]: The query aims to find associations related to the target KRAS.
[target_tool]: First, the system retrieved known associations for the target KRAS. Initially, this step pulled a total of 35 records, which contained any known relationships involving KRAS.
[target_tool]: Next, the system performed a deduplication process to remove duplicate records, reducing the number of associations from 35 down to 11. This step helped ensure that only unique associations remained for further analysis.
[target_tool]: In summary, the final result consists of 11 distinct disease or drug associations related to KRAS after removing duplicates.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000133703,kras,EFO_0003060,non-small cell lung carcinoma,0.778862

 Run 4 completed | rows=11 | latency=16.100s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
[target_tool]: The query aimed to find relevant information related to the target KRAS.
[target_tool]: First, the system retrieved known disease-drug associations for KRAS, which initially resulted in 35 entries.
[target_tool]: Next, the system performed deduplication to remove duplicate records within these associations. This process reduced the number of entries from 35 to 11, leaving only unique records related to KRAS.
[target_tool]: In summary, after these steps, the final dataset consisted of 11 unique disease-drug association records for KRAS.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000133703,kras,EFO_0003060,non-small cell lung carcinoma,0.778862

 Run 5 completed | rows=11 | latency=16.976s
------------------------------------------------------------


## Question 30

**Which pathways are associated with the APP gene?**

In [67]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve pathway information associated with the target APP.
[target_tool]: First, the system retrieved pathway data related to APP, resulting in a total of 17 pathways identified. This step provided the pathway connections that are linked to the target.
[target_tool]: Next, no further filtering steps are described in the provided log, so the process ended with the retrieval of these 17 pathways.
[target_tool]: In summary, the final result includes 17 pathways associated with the target APP.
----------------------------------------
Entries retrieved: 17

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 1 completed | rows=17 | latency=16.833s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target 'APP'. In the pathway retrieval step, the system retrieved pathway data associated with this target, resulting in a total of 17 pathways. Since this step did not specify a reduction in the number of pathways, it indicates that the pathway information was collected without filtering. The final result includes these 17 pathways linked to 'APP'.
----------------------------------------
Entries retrieved: 17

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 2 completed | rows=17 | latency=19.346s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve pathway information related to the target APP. The first step involved retrieving pathways associated with this target. Before this step, there was no specified number of pathways, but after the retrieval, 17 pathways were identified.
[target_tool]: Since only one step is shown in the provided log, it indicates that pathways for APP were successfully retrieved, resulting in a set of 17 pathways.
----------------------------------------
Entries retrieved: 17

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 3 completed | rows=17 | latency=14.636s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the biological target 'APP'. The first step involved retrieving pathway data associated with this target. Initially, there was no previous count of pathways, but after this retrieval, 17 pathways related to 'APP' were identified. This step simply gathered pathway information without reducing or filtering the results further. The overall process resulted in identifying 17 pathways linked to the target.
----------------------------------------
Entries retrieved: 17

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 4 completed | rows=17 | latency=14.550s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
[target_tool]: The goal was to find pathways related to the biological target APP. Initially, the system retrieved pathway information associated with APP and identified a total of 17 pathways. This step involved gathering general pathway data without applying any filters at this stage. Since this was the first and only step shown in the log, no further filtering or reduction of pathways was performed beyond this retrieval. In the end, the process resulted in 17 pathways linked to the target APP.
----------------------------------------
Entries retrieved: 17

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,APP,ENSG00000142192,R-HSA-3000178,ECM proteoglycans,Extracellular matrix organization

 Run 5 completed | rows=17 | latency=15.670s
------------------------------------------------------------


## Question 31

**Genes linked to schizophrenia.**

In [68]:

question = 'Genes linked to schizophrenia.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to schizophrenia.
  Attempt 1/3
[disease_tool]: The query aimed to find data related to schizophrenia, focusing on disease and drug associations.
[disease_tool]: Initially, the system retrieved known disease–drug associations related to schizophrenia, resulting in 1,665 entries. This step collected all the relevant disease–drug links for the specified condition.
[disease_tool]: Next, the system performed deduplication to remove any duplicate records within those associations. This process reduced the total from 1,665 entries to 253, eliminating 1,412 duplicate records to ensure a more accurate and streamlined dataset.
[disease_tool]: In summary, after these steps, the system was left with 253 unique records related to disease–drug associations for schizophrenia.
----------------------------------------
Entries retrieved: 253

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,MONDO_0005090,schizophrenia,Small molecule,0.733924

 Run 1 completed | rows=253 | latency=15.284s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to schizophrenia.
  Attempt 1/3
[disease_tool]: The query aims to identify disease–drug associations related to schizophrenia.
[disease_tool]: First, the system retrieved known disease associations for schizophrenia, which resulted in 1,665 rows. This step gathered all initial data related to the condition.
[disease_tool]: Next, the system removed duplicate entries from these associations to ensure that each disease–drug link was unique. This deduplication process reduced the number of records from 1,665 to 253, removing 1,412 duplicate entries.
[disease_tool]: In total, the process ended with 253 unique disease–drug associations related to schizophrenia.
----------------------------------------
Entries retrieved: 253

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,MONDO_0005090,schizophrenia,Small molecule,0.733924

 Run 2 completed | rows=253 | latency=17.270s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to schizophrenia.
  Attempt 1/3
[disease_tool]: The query aims to explore disease–drug associations specifically related to schizophrenia.
[disease_tool]: Initially, the system retrieved a broad set of 1,665 known disease–drug associations related to schizophrenia. This initial step gathered all relevant entries without applying any filters.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from the dataset. This step reduced the number of associations from 1,665 to 253, eliminating 1,412 duplicate entries and resulting in a refined set of unique associations related to schizophrenia.
[disease_tool]: In summary, after these steps, the final result contains 253 distinct disease–drug association records linked to schizophrenia.
----------------------------------------
Entries retrieved: 253

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,MONDO_0005090,schizophrenia,Small molecule,0.733924

 Run 3 completed | rows=253 | latency=19.154s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to schizophrenia.
  Attempt 1/3
[disease_tool]: The goal of this query was to retrieve disease-drug associations related to schizophrenia and filter them down to unique entries.
[disease_tool]: Initially, the system retrieved a set of known associations for schizophrenia, resulting in 1,665 records. To ensure the data was free of duplicate entries, the system then removed any duplicate rows from this set. This deduplication process reduced the number of records from 1,665 to 253, meaning 1,412 duplicate records were eliminated. The final result contains 253 unique associations related to schizophrenia.
----------------------------------------
Entries retrieved: 253

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,MONDO_0005090,schizophrenia,Small molecule,0.733924

 Run 4 completed | rows=253 | latency=18.377s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to schizophrenia.
  Attempt 1/3
[disease_tool]: The query aims to find information related to schizophrenia, focusing on disease-drug associations.
[disease_tool]: First, the system retrieved known disease associations for schizophrenia, resulting in 1,665 entries. This initial step gathered a broad set of data related to various disease links.
[disease_tool]: Next, the system performed deduplication to remove any duplicate records from this set. After this process, the number of entries was reduced significantly from 1,665 to 253, removing 1,412 duplicate rows to ensure the data set was unique and more manageable.
[disease_tool]: Overall, the final result consisted of 253 unique disease association entries related to schizophrenia after filtering out duplicates.
----------------------------------------
Entries retrieved: 253

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,MONDO_0005090,schizophrenia,Small molecule,0.733924

 Run 5 completed | rows=253 | latency=16.051s
------------------------------------------------------------


## Question 32

**What diseases are treated with valdecoxib?**

In [69]:

question = 'What diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to find information about the drug valdecoxib and its associations.
[drug_tool]: First, the system retrieved known disease–drug associations related to valdecoxib, which resulted in a total of 13 entries.
[drug_tool]: Since the next steps are not provided, the current result set contains these 13 associations related to valdecoxib.
[drug_tool]: In summary, the final result includes 13 disease–drug association records for valdecoxib.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,valdecoxib,EFO_0000685,rheumatoid arthritis,4,NaN,cyclooxygenase-2 inhibitor,DailyMed

 Run 1 completed | rows=13 | latency=14.037s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The system aimed to explore information related to the drug valdecoxib. First, it retrieved known associations between diseases and this drug, which resulted in a total of 13 entries. This step established the initial set of relationships involving valdecoxib before any additional filtering.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,valdecoxib,EFO_0000685,rheumatoid arthritis,4,NaN,cyclooxygenase-2 inhibitor,DailyMed

 Run 2 completed | rows=13 | latency=13.113s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug valdecoxib and its associated diseases.
[drug_tool]: The first step was retrieving known associations between drugs and diseases specifically for valdecoxib. This association retrieval resulted in 13 entries, providing a foundational list of diseases potentially linked to this drug.
[drug_tool]: Following this, the system applied a filter based on diseases, which reduced the number of entries that matched certain criteria. The exact number of remaining entries after the disease filter is not specified, but this step narrowed down the list to more relevant disease associations. If expanded terms were used, examples like specific disease names may have been included to broaden the scope.
[drug_tool]: Next, a drug filter was applied to focus on particular drugs. This further reduced the number of associations, ensuring that only relationships involving specific drugs of interest were retained. This step also helped account for any synonyms or alternate names of drugs, which could overlap with other entries.
[drug_tool]: The system then applied a mechanism filter, which refined the list further by selecting associations involving specific mechanisms of action. This step ensured that the remaining entries involved particular biological mechanisms, thus narrowing down the results to more relevant interactions.
[drug_tool]: A deduplication process was then performed to remove any duplicate records from the list, ensuring that each association was unique.
[drug_tool]: Finally, pathway retrieval was conducted, collecting pathway information associated with the remaining entries, although this step did not change the number of entries.
[drug_tool]: In total, after executing all these steps, the final number of associations related to valdecoxib was 13.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,valdecoxib,EFO_0000685,rheumatoid arthritis,4,NaN,cyclooxygenase-2 inhibitor,DailyMed

 Run 3 completed | rows=13 | latency=16.562s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aims to retrieve information related to known drug associations for a specific drug, valdecoxib.
[drug_tool]: The process begins with an association retrieval step, where the system fetches the basic drug association data. This initial step resulted in 13 entries being retrieved.
[drug_tool]: No further filtering steps are detailed in the log, so the list remains at 13 entries after this stage.
[drug_tool]: In summary, the process resulted in 13 known drug association records for valdecoxib.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,valdecoxib,EFO_0000685,rheumatoid arthritis,4,NaN,cyclooxygenase-2 inhibitor,DailyMed

 Run 4 completed | rows=13 | latency=15.124s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
[drug_tool]: The query aimed to find relevant drug associations for the drug valdecoxib.
[drug_tool]: First, the system retrieved known associations related to valdecoxib, which resulted in a collection of 13 records.
[drug_tool]: Next, there was no explicit filtering or additional steps shown in the execution log, so this initial set of 13 associations likely includes all the retrieved data relevant to valdecoxib without further narrowing.
[drug_tool]: In summary, the process resulted in a total of 13 drug association records specific to valdecoxib.
----------------------------------------
Entries retrieved: 13

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL865,valdecoxib,EFO_0000685,rheumatoid arthritis,4,NaN,cyclooxygenase-2 inhibitor,DailyMed

 Run 5 completed | rows=13 | latency=15.290s
------------------------------------------------------------


## Question 33

**What are the known targets of vandetanib?**

In [70]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to vandetanib.
[drug_tool]: Initially, the system retrieved all known drug–disease association records for vandetanib, resulting in a total of 2,275 entries. This step gathered the relevant data set for further filtering.
[drug_tool]: Next, to refine the results, the system performed deduplication to remove any duplicate records. This process reduced the total number of entries from 2,275 to 25, effectively eliminating 2,250 duplicate rows.
[drug_tool]: In the end, the process produced a smaller, deduplicated dataset of 25 unique association records related to vandetanib.
----------------------------------------
Entries retrieved: 25

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL24828,vandetanib,vascular endothelial growth factor receptor in...,DailyMed

 Run 1 completed | rows=25 | latency=17.141s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to vandetanib.
[drug_tool]: First, the system retrieved known drug associations for vandetanib, resulting in 2,275 entries.
[drug_tool]: Next, the system removed duplicate records from this list, reducing the number of entries from 2,275 to 25.
[drug_tool]: Overall, the process narrowed down the initial set of known drug associations to 25 unique records related to vandetanib.
----------------------------------------
Entries retrieved: 25

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL24828,vandetanib,vascular endothelial growth factor receptor in...,DailyMed

 Run 2 completed | rows=25 | latency=15.914s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The query aimed to find information related to the drug vandetanib.
[drug_tool]: Initially, the system retrieved known associations between diseases and drugs for vandetanib, resulting in a total of 2,275 entries. This step gathered all relevant known associations before any filtering.
[drug_tool]: Next, a deduplication process was performed to remove duplicate records from this set. After removing duplicates, the number of entries was reduced to 25, leaving only unique records related to vandetanib.
[drug_tool]: In summary, the final result includes 25 distinct entries of disease–drug associations related to vandetanib after filtering for duplicates.
----------------------------------------
Entries retrieved: 25

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL24828,vandetanib,vascular endothelial growth factor receptor in...,DailyMed

 Run 3 completed | rows=25 | latency=15.636s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: This query aims to identify drugs associated with vandetanib.
[drug_tool]: First, the system retrieved known disease–drug associations related to vandetanib, resulting in a total of 2,275 entries. This step gathered all potentially related drug associations without applying any filters.
[drug_tool]: Next, the system performed deduplication to remove duplicate records from this list, reducing the total from 2,275 down to 25 unique entries. This step ensured that only distinct drug associations remained for further analysis or use.
[drug_tool]: In summary, the process started with a broad collection of 2,275 associations and was refined to 25 unique drug entries.
----------------------------------------
Entries retrieved: 25

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL24828,vandetanib,vascular endothelial growth factor receptor in...,DailyMed

 Run 4 completed | rows=25 | latency=15.176s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
[drug_tool]: The goal of the query was to identify drug associations related to vandetanib. First, the system retrieved a set of 2,275 known drug associations for vandetanib. Next, it applied a deduplication process to remove duplicate entries, reducing the result set from 2,275 to 25 unique associations. The final result contains 25 distinct drug association records related to vandetanib.
----------------------------------------
Entries retrieved: 25

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000037280,flt4,CHEMBL24828,vandetanib,vascular endothelial growth factor receptor in...,DailyMed

 Run 5 completed | rows=25 | latency=14.568s
------------------------------------------------------------


## Question 34

**Which pathways are associated with the CFTR gene?**

In [71]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The goal of the query was to identify pathways associated with the CFTR target. Initially, pathways related to CFTR were retrieved, resulting in 11 pathways. This step involved gathering all relevant pathway information without filtering or narrowing down the results. The final outcome was 11 pathways related to CFTR.
----------------------------------------
Entries retrieved: 11

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 1 completed | rows=11 | latency=15.266s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The query aimed to find information related to the target CFTR, including its associated pathways. In the first step, the system retrieved pathways associated with CFTR, resulting in a total of 11 pathways. There was no previous number of pathways since this was the initial retrieval. Overall, this step provided pathway information relevant to CFTR.
----------------------------------------
Entries retrieved: 11

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 2 completed | rows=11 | latency=13.550s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The query aimed to gather information related to the target CFTR. The first step was pathway retrieval, where the system accessed known biological pathways associated with CFTR. This process resulted in retrieving 11 pathways linked to CFTR. This step did not involve filtering or reducing the number of pathways; it simply provided relevant pathway information. In the end, a total of 11 pathways associated with CFTR were retrieved.
----------------------------------------
Entries retrieved: 11

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 3 completed | rows=11 | latency=17.362s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The goal of the query was to identify related pathways for the target CFTR. The first step involved retrieving pathway information associated with CFTR, which resulted in 11 pathways being identified. This step involved collecting relevant biological pathways linked to CFTR without reducing or filtering the initial set. The result shows that 11 pathways are associated with this target.
----------------------------------------
Entries retrieved: 11

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 4 completed | rows=11 | latency=14.505s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information about pathways related to the CFTR target. First, the system retrieved pathway data associated with CFTR, resulting in a set of 11 pathways. No previous number of pathways was given, so the total after retrieval is 11 pathways. The process concluded with these 11 pathways related to the target CFTR.
----------------------------------------
Entries retrieved: 11

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,CFTR,ENSG00000001626,R-HSA-5689880,Ub-specific processing proteases,Metabolism of proteins

 Run 5 completed | rows=11 | latency=15.183s
------------------------------------------------------------


## Question 35

**Which drugs are used for TB?**

In [72]:

question = 'Which drugs are used for TB?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for TB?
  Attempt 1/3
[disease_tool]: The query aims to retrieve information related to a specific disease, tuberculosis, and filter associated drugs based on certain criteria.
[disease_tool]: Initially, the system retrieved known disease–drug associations related to tuberculosis, resulting in 161 records. This step gathered all initial associations linked to tuberculosis before any filtering was applied.
[disease_tool]: Next, the results underwent deduplication to remove duplicate entries, reducing the result set from 161 to 84 records. This step cleaned the data to ensure each association was unique, removing 77 duplicate rows.
[disease_tool]: In summary, after completing all the filtering steps, the final dataset contained 84 unique associations related to tuberculosis.
----------------------------------------
Entries retrieved: 84

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2021430,dexamethasone sodium phosphate,MONDO_0018076,tuberculosis,4,NaN,Small molecule,glucocorticoid receptor agonist,0.590371

 Run 1 completed | rows=84 | latency=15.979s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for TB?
  Attempt 1/3
[disease_tool]: The query aimed to identify information related to tuberculosis.
[disease_tool]: First, the system retrieved known disease–drug associations for tuberculosis, which brought back 161 entries.
[disease_tool]: Next, the system removed duplicate records from this set to ensure each association was unique. This deduplication process reduced the number of entries from 161 to 84, removing 77 duplicate rows.
[disease_tool]: In summary, after filtering for unique associations related to tuberculosis, the final result included 84 distinct entries.
----------------------------------------
Entries retrieved: 84

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2021430,dexamethasone sodium phosphate,MONDO_0018076,tuberculosis,4,NaN,Small molecule,glucocorticoid receptor agonist,0.590371

 Run 2 completed | rows=84 | latency=17.699s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for TB?
  Attempt 1/3
[disease_tool]: The query aimed to explore disease–drug associations related to tuberculosis.
[disease_tool]: Initially, the system retrieved a set of 161 disease association records related to tuberculosis. This step provided all known linkages without filtering.
[disease_tool]: Next, the system performed a deduplication step to remove duplicate records. This process reduced the number of records from 161 to 84, ensuring that only unique entries remained.
[disease_tool]: In conclusion, after filtering out duplicates, there were 84 unique records associated with tuberculosis.
----------------------------------------
Entries retrieved: 84

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2021430,dexamethasone sodium phosphate,MONDO_0018076,tuberculosis,4,NaN,Small molecule,glucocorticoid receptor agonist,0.590371

 Run 3 completed | rows=84 | latency=15.527s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for TB?
  Attempt 1/3
[disease_tool]: The query aims to find specific information related to tuberculosis. Initially, the system retrieved known disease–drug associations for tuberculosis, resulting in 161 entries.
[disease_tool]: The first step was to eliminate duplicate records, which reduced the number of entries from 161 to 84. This deduplication step removed 77 duplicate rows to ensure the dataset contained unique association entries.
[disease_tool]: In total, the process resulted in 84 unique association records related to tuberculosis.
----------------------------------------
Entries retrieved: 84

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2021430,dexamethasone sodium phosphate,MONDO_0018076,tuberculosis,4,NaN,Small molecule,glucocorticoid receptor agonist,0.590371

 Run 4 completed | rows=84 | latency=15.895s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for TB?
  Attempt 1/3
[disease_tool]: The query aims to identify drug information related to tuberculosis.
[disease_tool]: First, the system retrieved known disease–drug associations for tuberculosis, resulting in 161 entries. These entries are records linking the disease tuberculosis to various drugs.
[disease_tool]: Next, the system performed deduplication to remove duplicate records. This process reduced the number of associations from 161 to 84, eliminating 77 duplicate entries to ensure the data set contained only unique records.
[disease_tool]: In total, the process ended with 84 unique disease–drug associations related to tuberculosis.
----------------------------------------
Entries retrieved: 84

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL2021430,dexamethasone sodium phosphate,MONDO_0018076,tuberculosis,4,NaN,Small molecule,glucocorticoid receptor agonist,0.590371

 Run 5 completed | rows=84 | latency=17.123s
------------------------------------------------------------


## Question 36

**Which drugs are used for pancreatic adenocarcinoma?**

In [73]:

question = 'Which drugs are used for pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aims to identify associations related to pancreatic adenocarcinoma, including potentially related drugs and mechanisms.
[disease_tool]: First, the system retrieved known disease–drug associations for pancreatic adenocarcinoma. This initial step fetched a total of 1918 associations, providing a broad base of information.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate entries from the retrieved data. This filtering step reduced the total number of associations from 1918 to 946, eliminating 972 duplicate rows and leaving a set of unique associations.
[disease_tool]: In summary, the final result, after filtering for unique associations, contains 946 entries related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 946

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1637,gemcitabine hydrochloride,EFO_1000044,pancreatic adenocarcinoma,1.0,Recruiting,Small molecule,dna polymerase (alpha/delta/epsilon) inhibitor,0.498912

 Run 1 completed | rows=946 | latency=18.326s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aimed to analyze information related to pancreatic adenocarcinoma.
[disease_tool]: First, the system retrieved known disease–drug associations for pancreatic adenocarcinoma, resulting in 1918 entries.
[disease_tool]: Next, to ensure data quality, duplicate entries were removed, which reduced the number of associations from 1918 to 946.
[disease_tool]: In total, the process narrowed down the data set to 946 unique disease–drug association records related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 946

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1637,gemcitabine hydrochloride,EFO_1000044,pancreatic adenocarcinoma,1.0,Recruiting,Small molecule,dna polymerase (alpha/delta/epsilon) inhibitor,0.498912

 Run 2 completed | rows=946 | latency=17.440s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to pancreatic adenocarcinoma, specifically focusing on disease associations. The first step involved retrieving known disease–drug associations for the disease of interest. Initially, this retrieval resulted in 1,918 entries, representing all the associations found for pancreatic adenocarcinoma.
[disease_tool]: In the next step, a deduplication process was performed to eliminate duplicate records within the results. This process reduced the number of entries from 1,918 to 946, removing 972 duplicate rows.
[disease_tool]: In summary, after these steps, the final set of data contained 946 unique disease association records for pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 946

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1637,gemcitabine hydrochloride,EFO_1000044,pancreatic adenocarcinoma,1.0,Recruiting,Small molecule,dna polymerase (alpha/delta/epsilon) inhibitor,0.498912

 Run 3 completed | rows=946 | latency=16.558s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aims to retrieve information relating to associations between a specific disease and drugs.
[disease_tool]: First, the system retrieved known disease–drug associations for the target disease, pancreatic adenocarcinoma, resulting in 1918 records.
[disease_tool]: Next, duplicates within these records were removed to ensure that each association was represented only once. This deduplication process reduced the total number of records from 1918 to 946, eliminating 972 duplicate entries.
[disease_tool]: In summary, after filtering out duplicates, the dataset contains 946 unique disease–drug association records related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 946

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1637,gemcitabine hydrochloride,EFO_1000044,pancreatic adenocarcinoma,1.0,Recruiting,Small molecule,dna polymerase (alpha/delta/epsilon) inhibitor,0.498912

 Run 4 completed | rows=946 | latency=16.342s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease–drug associations specifically related to pancreatic adenocarcinoma.
[disease_tool]: Initially, the system retrieved known disease associations for the target disease, resulting in 1,918 entries.
[disease_tool]: Next, the system removed duplicate rows from this set, reducing the total from 1,918 to 946 entries.
[disease_tool]: In summary, after filtering out duplicates, the final result contained 946 unique disease association records related to pancreatic adenocarcinoma.
----------------------------------------
Entries retrieved: 946

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1637,gemcitabine hydrochloride,EFO_1000044,pancreatic adenocarcinoma,1.0,Recruiting,Small molecule,dna polymerase (alpha/delta/epsilon) inhibitor,0.498912

 Run 5 completed | rows=946 | latency=16.284s
------------------------------------------------------------


## Question 37

**Which drugs are used in chronic myeloid leukemia?**

In [74]:

question = 'Which drugs are used in chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to chronic myeloid leukemia.
[disease_tool]: The first step involved retrieving known disease–drug associations for chronic myeloid leukemia, which initially returned 976 entries.
[disease_tool]: Next, the system removed duplicate records from this set, reducing the total from 976 to 836. This step ensured that each association was unique, eliminating 140 duplicate entries.
[disease_tool]: In summary, after these processing steps, there are 836 unique disease-drug association records related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 836

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1421,dasatinib anhydrous,EFO_0000339,chronic myelogenous leukemia,1.0,Withdrawn,Small molecule,tyrosine-protein kinase abl inhibitor,0.829035

 Run 1 completed | rows=836 | latency=14.505s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The query aimed to find disease-drug associations related to chronic myeloid leukemia.
[disease_tool]: The first step involved retrieving known disease associations, which initially resulted in 976 entries related to chronic myeloid leukemia. Then, a deduplication process was performed to remove duplicate records from this set. As a result, the number of entries was reduced from 976 to 836, removing 140 duplicate rows.
[disease_tool]: In summary, the final result after these steps included 836 unique disease association records related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 836

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1421,dasatinib anhydrous,EFO_0000339,chronic myelogenous leukemia,1.0,Withdrawn,Small molecule,tyrosine-protein kinase abl inhibitor,0.829035

 Run 2 completed | rows=836 | latency=20.571s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to chronic myeloid leukemia, focusing on disease associations.
[disease_tool]: The first step involved retrieving known disease–drug associations for the disease chronic myeloid leukemia. Initially, there was no specified number of entries, but after this retrieval, the system obtained 976 rows related to the disease.
[disease_tool]: Next, the process performed deduplication to remove duplicate records. This step reduced the number of entries from 976 to 836, removing a total of 140 duplicate rows.
[disease_tool]: In summary, after these steps, the system was left with 836 unique disease association records related to chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 836

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1421,dasatinib anhydrous,EFO_0000339,chronic myelogenous leukemia,1.0,Withdrawn,Small molecule,tyrosine-protein kinase abl inhibitor,0.829035

 Run 3 completed | rows=836 | latency=16.120s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The query aims to find information related to chronic myeloid leukemia, focusing on disease associations, drugs, mechanisms, and pathways.
[disease_tool]: Initially, the system retrieved a set of known disease–drug associations centered around the disease "chronic myeloid leukemia," resulting in 976 entries. This step identifies all potential relevant associations without filtering specific drugs or mechanisms at this point.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate entries from the initial set. This step reduced the number of rows from 976 to 836, eliminating 140 duplicate records. After this, the dataset contains unique entries related to the disease associations with no repeated information.
[disease_tool]: In summary, the process started with 976 disease–drug association records, which were then refined through deduplication to a final count of 836 unique entries.
----------------------------------------
Entries retrieved: 836

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1421,dasatinib anhydrous,EFO_0000339,chronic myelogenous leukemia,1.0,Withdrawn,Small molecule,tyrosine-protein kinase abl inhibitor,0.829035

 Run 4 completed | rows=836 | latency=15.404s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
[disease_tool]: The purpose of this query was to identify relevant associations related to chronic myeloid leukemia.
[disease_tool]: First, the system retrieved known disease associations related to this condition, resulting in 976 entries. This step provided the initial set of data before any filtering.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from this set. This process reduced the number of entries from 976 to 836, removing 140 duplicate rows to ensure the results are unique.
[disease_tool]: In summary, after retrieving and cleaning the data, the final count of relevant, unique disease association entries for chronic myeloid leukemia was 836.
----------------------------------------
Entries retrieved: 836

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1421,dasatinib anhydrous,EFO_0000339,chronic myelogenous leukemia,1.0,Withdrawn,Small molecule,tyrosine-protein kinase abl inhibitor,0.829035

 Run 5 completed | rows=836 | latency=15.647s
------------------------------------------------------------


## Question 38

**What drugs are used in the treatment of Parkinson’s disease?**

In [75]:

question = 'What drugs are used in the treatment of Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The query's goal was to find drug and pathway associations related to Parkinson disease. First, the system retrieved all known disease–drug associations related to Parkinson disease, resulting in 855 entries. Next, it removed duplicate records, which reduced the number of entries from 855 to 805. In summary, after these filtering steps, there are 805 unique records associated with Parkinson disease.
----------------------------------------
Entries retrieved: 805

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4298077,prasinezumab,MONDO_0005180,parkinson disease,2.0,"Active, not recruiting",Antibody,alpha-synuclein binding agent,0.871549

 Run 1 completed | rows=805 | latency=14.622s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The query aimed to identify information related to Parkinson disease.
[disease_tool]: Initially, the system retrieved known disease–drug associations specifically for this disease, resulting in 855 records. Next, the system applied a deduplication process to remove duplicate entries, which reduced the total from 855 to 805 records.
[disease_tool]: In summary, after these steps, 805 unique records remained that are associated with Parkinson disease.
----------------------------------------
Entries retrieved: 805

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4298077,prasinezumab,MONDO_0005180,parkinson disease,2.0,"Active, not recruiting",Antibody,alpha-synuclein binding agent,0.871549

 Run 2 completed | rows=805 | latency=16.046s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to Parkinson's disease, encompassing its known associations with drugs and mechanisms of action.
[disease_tool]: Initially, the system retrieved base disease associations for Parkinson's disease, resulting in 855 records. This step gathered all relevant known links between the disease and other biomedical entities.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate records from the retrieved data. After this step, the total number of records was reduced from 855 to 805, eliminating 50 duplicate entries to ensure data accuracy and simplicity.
[disease_tool]: In summary, after these steps, the relevant dataset contained 805 unique disease association records related to Parkinson's disease.
----------------------------------------
Entries retrieved: 805

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4298077,prasinezumab,MONDO_0005180,parkinson disease,2.0,"Active, not recruiting",Antibody,alpha-synuclein binding agent,0.871549

 Run 3 completed | rows=805 | latency=19.456s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The query aims to identify disease–drug associations related to Parkinson disease. First, the system retrieved known disease associations, resulting in a total of 855 entries. Next, to ensure the data accuracy and eliminate redundancy, duplicate records were removed, which reduced the number of entries from 855 to 805. In the end, the final result includes 805 unique entries associated with Parkinson disease.
----------------------------------------
Entries retrieved: 805

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4298077,prasinezumab,MONDO_0005180,parkinson disease,2.0,"Active, not recruiting",Antibody,alpha-synuclein binding agent,0.871549

 Run 4 completed | rows=805 | latency=12.946s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to Parkinson disease and its associated drugs.
[disease_tool]: Initially, the system retrieved a set of disease-related associations for Parkinson disease, resulting in 855 entries. This step gathered all known links between Parkinson disease and other entities.
[disease_tool]: Next, the system performed deduplication to eliminate repeated rows, reducing the total from 855 to 805 entries. This step helped ensure the results were unique and more manageable.
[disease_tool]: In total, the process ended with 805 unique association records for Parkinson disease, focusing on related disease-drug links.
----------------------------------------
Entries retrieved: 805

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4298077,prasinezumab,MONDO_0005180,parkinson disease,2.0,"Active, not recruiting",Antibody,alpha-synuclein binding agent,0.871549

 Run 5 completed | rows=805 | latency=14.971s
------------------------------------------------------------


## Question 39

**Which drugs are used for inflammatory bowel disease?**

In [76]:

question = 'Which drugs are used for inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease-drug associations related to inflammatory bowel disease.
[disease_tool]: First, the system retrieved known disease associations for inflammatory bowel disease, resulting in 1,282 records. This step involved gathering all relevant data related to this disease without applying any filters.
[disease_tool]: Next, the system removed duplicate entries from these records, reducing the total from 1,282 to 841. This deduplication step ensured that each association was unique, improving the clarity of the results.
[disease_tool]: In the end, the process yielded 841 unique disease association records for inflammatory bowel disease.
----------------------------------------
Entries retrieved: 841

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1743087,vedolizumab,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,integrin alpha-4/beta-7 inhibitor,0.736969

 Run 1 completed | rows=841 | latency=17.505s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The purpose of this query was to retrieve information related to inflammatory bowel disease.
[disease_tool]: First, the system retrieved known disease–drug associations for inflammatory bowel disease, which resulted in a total of 1,282 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the number of entries from 1,282 to 841. This step ensured that only unique associations remained for further analysis.
[disease_tool]: In summary, the final result contains 841 unique disease–drug association entries for inflammatory bowel disease.
----------------------------------------
Entries retrieved: 841

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1743087,vedolizumab,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,integrin alpha-4/beta-7 inhibitor,0.736969

 Run 2 completed | rows=841 | latency=16.658s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to inflammatory bowel disease, focusing on disease-drug associations.
[disease_tool]: Initially, the system retrieved known associations involving inflammatory bowel disease, resulting in a total of 1,282 entries.
[disease_tool]: Next, the data underwent a deduplication process to remove duplicate records, which reduced the number of entries from 1,282 to 841. This step helped ensure that each association was unique, eliminating redundancy in the dataset.
[disease_tool]: In the end, the process produced a filtered set of 841 unique associations related to inflammatory bowel disease.
----------------------------------------
Entries retrieved: 841

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1743087,vedolizumab,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,integrin alpha-4/beta-7 inhibitor,0.736969

 Run 3 completed | rows=841 | latency=13.927s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aimed to find relevant disease–drug associations related to inflammatory bowel disease.
[disease_tool]: First, the system retrieved the base disease associations for inflammatory bowel disease, which initially resulted in 1,282 entries.
[disease_tool]: Next, duplicate entries were removed from this set; this deduplication reduced the number of entries from 1,282 to 841, removing 441 duplicates.
[disease_tool]: In summary, the final dataset contains 841 unique associations related to inflammatory bowel disease after the initial retrieval and removal of duplicates.
----------------------------------------
Entries retrieved: 841

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1743087,vedolizumab,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,integrin alpha-4/beta-7 inhibitor,0.736969

 Run 4 completed | rows=841 | latency=14.603s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to inflammatory bowel disease. First, the system retrieved known associations between diseases and drugs for this condition, resulting in a total of 1,282 entries. Next, to ensure data quality and eliminate redundancy, the system removed duplicate records, reducing the number of association entries from 1,282 to 841. This process left a refined set of 841 unique disease-drug associations for further analysis or review.
----------------------------------------
Entries retrieved: 841

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL1743087,vedolizumab,EFO_0003767,inflammatory bowel disease,4.0,NaN,Antibody,integrin alpha-4/beta-7 inhibitor,0.736969

 Run 5 completed | rows=841 | latency=14.758s
------------------------------------------------------------


## Question 40

**What targets are acted on by imatinib?**

In [77]:

question = 'What targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve specific drug-related associations, focusing on the drug imatinib.
[drug_tool]: First, the system retrieved known associations between drugs and diseases related to imatinib. This initial retrieval yielded 920 rows of data.
[drug_tool]: Next, the system removed duplicate entries from these results, reducing the total number of rows from 920 to just 4. This deduplication step ensured that only unique association records remained.
[drug_tool]: In summary, after completing these steps, the final dataset consisted of 4 unique drug association entries for imatinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,kit,CHEMBL941,imatinib,stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 1 completed | rows=4 | latency=20.675s
------------------------------------------------------------

 Starting run 2 for query: What targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The goal of the query was to retrieve drug associations related to imatinib. Initially, the system retrieved known associations for this drug, resulting in 920 rows. Next, the system removed duplicate entries among these associations, which greatly reduced the number of results from 920 to just 4. Overall, the process filtered the data down to a small set of unique associations relevant to imatinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,kit,CHEMBL941,imatinib,stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 2 completed | rows=4 | latency=16.972s
------------------------------------------------------------

 Starting run 3 for query: What targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The purpose of the query was to find information related to the drug imatinib.
[drug_tool]: First, the system retrieved associations between diseases and drugs related to imatinib, collecting a total of 920 records. This step involved gathering known links between imatinib and various diseases, which served as the initial dataset.
[drug_tool]: Next, the system performed deduplication to eliminate duplicate entries from the retrieved data. This process reduced the number of records dramatically from 920 to just 4, removing redundant information and leaving only unique associations.
[drug_tool]: In summary, after these steps, the final dataset consisted of 4 unique records related to imatinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,kit,CHEMBL941,imatinib,stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 3 completed | rows=4 | latency=15.238s
------------------------------------------------------------

 Starting run 4 for query: What targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The intent of the query was to identify drug associations related to imatinib.
[drug_tool]: First, the system retrieved known drug associations related to imatinib, which resulted in 920 entries.
[drug_tool]: Next, the system removed duplicate records from these associations. This deduplication process reduced the number of entries from 920 to 4, leaving only the unique association records.
[drug_tool]: In summary, after these steps, there were 4 unique drug association entries related to imatinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,kit,CHEMBL941,imatinib,stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 4 completed | rows=4 | latency=17.222s
------------------------------------------------------------

 Starting run 5 for query: What targets are acted on by imatinib?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve drug associations related to imatinib.
[drug_tool]: Initially, the system retrieved known disease–drug associations for imatinib, resulting in 920 entries. Next, the system removed duplicate records from this set, which significantly reduced the number of entries from 920 down to just 4.
[drug_tool]: In total, after the deduplication process, the result set contained 4 unique records.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000157404,kit,CHEMBL941,imatinib,stem cell growth factor receptor inhibitor,"DailyMed, FDA, Wikipedia"

 Run 5 completed | rows=4 | latency=17.823s
------------------------------------------------------------


## Question 41

**What biological targets does sorafenib interact with?**

In [78]:

question = 'What biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The query aimed to retrieve drug associations for sorafenib and filter these results based on specific criteria.
[drug_tool]: First, the system retrieved the known disease-drug associations for sorafenib, resulting in a total of 2,799 entries. This initial retrieval gathered all the associations without any filtering.
[drug_tool]: Next, the system performed a deduplication step to remove any duplicate records from this set. This process reduced the number of entries drastically from 2,799 down to 9, leaving only unique associations.
[drug_tool]: In total, after these steps, the process resulted in 9 unique disease-drug association records for sorafenib.
----------------------------------------
Entries retrieved: 9

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,pdgfrb,CHEMBL1336,sorafenib,platelet-derived growth factor receptor beta i...,FDA

 Run 1 completed | rows=9 | latency=16.862s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The query aimed to examine drug associations related to sorafenib. First, the system retrieved known drug associations for sorafenib, resulting in a total of 2,799 entries. Next, it removed duplicate records from this set, reducing the number of entries from 2,799 to just 9. Overall, the final result included 9 unique drug association records for sorafenib.
----------------------------------------
Entries retrieved: 9

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,pdgfrb,CHEMBL1336,sorafenib,platelet-derived growth factor receptor beta i...,FDA

 Run 2 completed | rows=9 | latency=15.815s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The goal of this query was to retrieve and process information related to the drug sorafenib.
[drug_tool]: First, the system retrieved known drug associations for sorafenib, which resulted in a collection of 2799 entries. This step was based on a database of existing associations involving the drug.
[drug_tool]: Next, the system performed deduplication to eliminate duplicate records that appeared multiple times within this set. After removing these duplicates, only 9 unique entries remained, significantly reducing the dataset.
[drug_tool]: In summary, the final result includes 9 unique drug association records related to sorafenib, after initial retrieval and removal of duplicate information.
----------------------------------------
Entries retrieved: 9

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,pdgfrb,CHEMBL1336,sorafenib,platelet-derived growth factor receptor beta i...,FDA

 Run 3 completed | rows=9 | latency=16.348s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The intent of the query was to find information related to the drug sorafenib, specifically its disease associations and related drug data.
[drug_tool]: The first step was association retrieval, where the system retrieved known disease–drug associations for sorafenib. This initial process produced a total of 2799 rows of data, capturing various associations linked to the drug.
[drug_tool]: Next, the data underwent deduplication, where duplicate entries were removed to ensure only unique records remained. This step drastically reduced the number of entries from 2799 to just 9, eliminating 2790 duplicate rows.
[drug_tool]: In summary, after filtering for unique disease and drug associations related to sorafenib, the system resulted in a final set of 9 relevant records.
----------------------------------------
Entries retrieved: 9

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,pdgfrb,CHEMBL1336,sorafenib,platelet-derived growth factor receptor beta i...,FDA

 Run 4 completed | rows=9 | latency=17.696s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
[drug_tool]: The goal of the query was to retrieve and refine drug association data related to sorafenib.
[drug_tool]: First, the system retrieved known drug associations for sorafenib, resulting in an initial set of 2,799 records.
[drug_tool]: Next, the system performed deduplication to remove duplicate entries, reducing the number of records from 2,799 to 9. This step eliminated redundant information to provide a more accurate and concise data set.
[drug_tool]: In total, the process narrowed down the initial broad collection of association data to just 9 unique records.
----------------------------------------
Entries retrieved: 9

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000113721,pdgfrb,CHEMBL1336,sorafenib,platelet-derived growth factor receptor beta i...,FDA

 Run 5 completed | rows=9 | latency=17.616s
------------------------------------------------------------


## Question 42

**What biological targets does tofacitinib affect?**

In [79]:

question = 'What biological targets does tofacitinib affect?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to tofacitinib. First, the system retrieved known disease-drug associations for tofacitinib, resulting in 280 entries. This step brought together all potential relationships involving the drug before filtering.
[drug_tool]: Next, the system removed duplicate rows from these 280 entries, reducing the number to 4 unique associations. This deduplication process helped ensure that only distinct records remained for further analysis.
[drug_tool]: In summary, after retrieving all initial associations and removing duplicates, the final result includes 4 unique entries related to tofacitinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,tyk2,CHEMBL221959,tofacitinib,janus kinase (jak) inhibitor,Expert

 Run 1 completed | rows=4 | latency=16.376s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
[drug_tool]: The goal of the query was to find relevant drug associations for tofacitinib.
[drug_tool]: First, the system retrieved known associations related to tofacitinib, resulting in 280 rows. This initial retrieval gathered all known data linked to this drug.
[drug_tool]: Next, the system removed duplicate entries from the retrieved data, reducing the total from 280 to just 4 unique records. This step ensured that each association was only counted once, providing a cleaner and more accurate set of results.
[drug_tool]: In summary, after these steps, the final number of unique drug association records for tofacitinib is 4.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,tyk2,CHEMBL221959,tofacitinib,janus kinase (jak) inhibitor,Expert

 Run 2 completed | rows=4 | latency=13.973s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
[drug_tool]: The query aims to identify drugs associated with a specific target.
[drug_tool]: Initially, the system retrieved known drug associations for tofacitinib, resulting in 280 entries. This step gathers all previously recorded links between tofacitinib and various biological entities.
[drug_tool]: Next, the system performed a deduplication process to remove any duplicate entries in the retrieved data. This step reduced the number of records significantly from 280 to just 4 unique entries, ensuring only distinct associations remained.
[drug_tool]: In summary, the final result consisted of 4 unique drug association records related to tofacitinib after eliminating duplicates.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,tyk2,CHEMBL221959,tofacitinib,janus kinase (jak) inhibitor,Expert

 Run 3 completed | rows=4 | latency=16.982s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to tofacitinib.
[drug_tool]: Initially, the system retrieved known disease–drug associations involving tofacitinib, resulting in 280 entries.
[drug_tool]: Next, the system performed deduplication to remove duplicate records from this set. As a result, the data was reduced significantly from 280 entries to just 4 unique records.
[drug_tool]: In summary, the final result contains 4 non-duplicate associations for tofacitinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,tyk2,CHEMBL221959,tofacitinib,janus kinase (jak) inhibitor,Expert

 Run 4 completed | rows=4 | latency=14.188s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
[drug_tool]: The user's query aimed to find drug associations related to tofacitinib.
[drug_tool]: The first step involved retrieving known drug associations specifically for tofacitinib. This process initially gathered a broad set of data, resulting in 280 entries.
[drug_tool]: Next, the system applied deduplication to remove duplicate records from this set. After this step, only 4 unique entries remained, significantly reducing the number of results.
[drug_tool]: In summary, by retrieving relevant associations and removing duplicates, the final result consists of 4 unique data entries related to tofacitinib.
----------------------------------------
Entries retrieved: 4

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000105397,tyk2,CHEMBL221959,tofacitinib,janus kinase (jak) inhibitor,Expert

 Run 5 completed | rows=4 | latency=14.524s
------------------------------------------------------------


## Question 43

**Which drugs are known to target EGFR?**

In [80]:

question = 'Which drugs are known to target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are known to target EGFR?
  Attempt 1/3
[target_tool]: The query aimed to find associations related to the target EGFR and then narrow down the results.
[target_tool]: First, the system retrieved known disease–drug associations for EGFR, which resulted in 1,870 entries. This initial retrieval included all associated data without filtering.
[target_tool]: Next, the system performed deduplication to remove duplicate entries, reducing the result set from 1,870 to 510 unique records. This step helped ensure that only distinct associations were considered henceforth.
[target_tool]: In summary, after these processing steps, the system had 510 unique disease–drug associations related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 1 completed | rows=510 | latency=14.656s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are known to target EGFR?
  Attempt 1/3
[target_tool]: The purpose of the query was to identify associations related to the target EGFR.
[target_tool]: First, the system retrieved all known disease–drug associations for EGFR, resulting in 1,870 entries. Next, it removed duplicate records to ensure each association was unique, reducing the number of results from 1,870 to 510.
[target_tool]: In summary, after filtering out duplicates, there are now 510 unique disease–drug associations associated with EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 2 completed | rows=510 | latency=16.334s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are known to target EGFR?
  Attempt 1/3
[target_tool]: The query aims to identify entities associated with the target EGFR.
[target_tool]: Initially, the system retrieved known disease–drug associations for EGFR, resulting in a total of 1,870 entries.
[target_tool]: Next, the system removed duplicate records from these associations to ensure only unique entries remained. This deduplication process reduced the number of associations from 1,870 to 510.
[target_tool]: In summary, after these steps, there are 510 unique associations related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 3 completed | rows=510 | latency=18.483s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are known to target EGFR?
  Attempt 1/3
[target_tool]: The goal of the query was to identify disease–drug associations related to the target EGFR.
[target_tool]: First, the system retrieved known associations between diseases and drugs for EGFR, resulting in a total of 1,870 entries. Next, to ensure the results were unique, the system removed duplicate records, which reduced the number of associations from 1,870 to 510.
[target_tool]: In summary, after retrieving the initial associations and removing duplicates, the final set contains 510 unique disease–drug associations related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 4 completed | rows=510 | latency=16.030s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are known to target EGFR?
  Attempt 1/3
[target_tool]: The goal was to identify associations related to the target EGFR. First, the system retrieved known disease-drug associations for EGFR, resulting in 1,870 records. Next, it performed deduplication to remove duplicate entries, which reduced the total from 1,870 to 510 unique associations. In summary, the final result comprises 510 non-duplicate associations related to EGFR.
----------------------------------------
Entries retrieved: 510

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000146648,egfr,CHEMBL1201179,lapatinib ditosylate,4.0,NaN,NaN,epidermal growth factor receptor erbb1 inhibitor

 Run 5 completed | rows=510 | latency=15.601s
------------------------------------------------------------


## Question 44

**Which diseases are linked to the TP53?**

In [81]:

question = 'Which diseases are linked to the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the TP53?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target TP53.
[target_tool]: First, the system retrieved known disease–drug associations for TP53, resulting in 79 entries. Next, it removed duplicate records, reducing the number of entries from 79 to 45.
[target_tool]: Overall, after these steps, there were 45 unique associations remaining.
----------------------------------------
Entries retrieved: 45

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,0.736214

 Run 1 completed | rows=45 | latency=14.805s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the TP53?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target TP53.
[target_tool]: First, the system retrieved known disease–drug associations related to TP53, resulting in a total of 79 entries.
[target_tool]: Next, the process involved removing duplicate records from the retrieved data, which reduced the number of entries from 79 to 45. This deduplication step ensured that only unique associations remained for further analysis.
[target_tool]: In summary, the process narrowed down the data to 45 unique disease–drug associations related to TP53 after removing duplicate entries.
----------------------------------------
Entries retrieved: 45

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,0.736214

 Run 2 completed | rows=45 | latency=17.529s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the TP53?
  Attempt 1/3
[target_tool]: The query aims to find information related to the target gene TP53.
[target_tool]: First, the system retrieved known disease–drug associations involving TP53, which initially returned 79 entries.
[target_tool]: Next, the system removed duplicate records from this list, reducing the total from 79 to 45. This step ensured that each association was unique, eliminating repeated entries.
[target_tool]: The final result after these steps is 45 unique disease–drug association entries related to TP53.
----------------------------------------
Entries retrieved: 45

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,0.736214

 Run 3 completed | rows=45 | latency=14.532s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the TP53?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target TP53.
[target_tool]: Initially, the system retrieved a set of 79 known disease–drug associations for TP53. Next, to ensure the data was unique and free of duplicate entries, the system performed deduplication. This process reduced the number of records from 79 to 45 by removing 34 duplicate rows.
[target_tool]: In summary, the final result contains 45 unique disease–drug associations related to TP53 after the deduplication step.
----------------------------------------
Entries retrieved: 45

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,0.736214

 Run 4 completed | rows=45 | latency=15.721s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the TP53?
  Attempt 1/3
[target_tool]: The goal of this query was to identify relevant disease–drug associations for the target TP53.
[target_tool]: First, the system retrieved all known associations related to TP53, resulting in 79 records.
[target_tool]: Next, the system removed duplicate records, which reduced the total from 79 to 45 entries.
[target_tool]: In summary, the process started with retrieving all associations linked to TP53, then filtering out duplicate records to provide a set of 45 unique disease–drug associations.
----------------------------------------
Entries retrieved: 45

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,0.736214

 Run 5 completed | rows=45 | latency=14.607s
------------------------------------------------------------


## Question 45

**Which diseases are associated with FGFR2?**

In [82]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve information related to the target FGFR2.
[target_tool]: The first step, association retrieval, involved collecting known disease–drug associations for FGFR2. This process initially resulted in 458 records.
[target_tool]: Next, deduplication was performed to remove any duplicated entries. After this step, the number of records was reduced from 458 to 143, leaving a set of unique associations related to FGFR2.
[target_tool]: In summary, the final result contains 143 unique association records for FGFR2 after filtering out duplicate entries.
----------------------------------------
Entries retrieved: 143

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000066468       fgfr2  MONDO_0004992       cancer           0.768086

 Run 1 completed | rows=143 | latency=16.280s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: The query was designed to identify targets associated with a specific disease or condition.
[target_tool]: Initially, the system retrieved known associations related to the target "FGFR2," resulting in 458 entries. After this, the system performed a deduplication step, removing duplicate records to ensure the data was unique. This process reduced the number of entries from 458 to 143, leaving only unique association records related to FGFR2.
[target_tool]: In summary, the final result includes 143 unique associations for FGFR2 after filtering out duplicates.
----------------------------------------
Entries retrieved: 143

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000066468       fgfr2  MONDO_0004992       cancer           0.768086

 Run 2 completed | rows=143 | latency=14.206s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target FGFR2.
[target_tool]: Initially, the system retrieves the base known disease–drug associations for FGFR2, resulting in 458 entries. This step gathers all potential related records without any filtering.
[target_tool]: Next, the system performs a deduplication process to remove duplicate entries from the retrieved data. This process reduces the number of records from 458 down to 143, eliminating 315 duplicates to ensure each association is unique.
[target_tool]: In total, the process starts with 458 associations and, after removing duplicates, concludes with 143 distinct records related to FGFR2.
----------------------------------------
Entries retrieved: 143

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000066468       fgfr2  MONDO_0004992       cancer           0.768086

 Run 3 completed | rows=143 | latency=14.768s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: The goal of the query was to find relevant drug associations for the target gene FGFR2.
[target_tool]: First, the system retrieved known disease–drug associations for FGFR2, resulting in 458 entries. This step provided a broad pool of data related to the target.
[target_tool]: Next, the system removed duplicate entries from this set, reducing the number of entries from 458 to 143. This step helped eliminate redundant information and clean the dataset, leaving only unique associations.
[target_tool]: In total, after these filtering steps, the result included 143 distinct disease–drug association records.
----------------------------------------
Entries retrieved: 143

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000066468       fgfr2  MONDO_0004992       cancer           0.768086

 Run 4 completed | rows=143 | latency=17.317s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
[target_tool]: The goal of the query was to identify relevant associations for the target FGFR2 and then refine those results further.
[target_tool]: First, the system retrieved known disease–drug associations related to FGFR2, resulting in a total of 458 entries. This step gathered all preliminary data without filtering.
[target_tool]: Next, the system performed deduplication to remove duplicate records from this dataset. This step reduced the number of entries from 458 to 143, leaving only unique records.
[target_tool]: In summary, the final dataset contains 143 unique associations related to FGFR2 after initial retrieval and deduplication steps.
----------------------------------------
Entries retrieved: 143

         target_id target_name     disease_id disease_name  association_score
0  ENSG00000066468       fgfr2  MONDO_0004992       cancer           0.768086

 Run 5 completed | rows=143 | latency=14.072s
------------------------------------------------------------


## Question 46

**Which diseases are linked to the HTT?**

In [83]:

question = 'Which diseases are linked to the HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the HTT?
  Attempt 1/3
[target_tool]: The intent of the query was to identify associations related to the biological target HTT.
[target_tool]: First, the system retrieved the base associations for HTT, which initially resulted in 3 records.
[target_tool]: Next, the system performed deduplication to remove any duplicate entries among these associations, reducing the number of records from 3 to 1.
[target_tool]: In summary, the final result contained a single, unique association related to HTT after all filtering steps.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000197386,htt,MONDO_0007739,huntington disease,0.708144

 Run 1 completed | rows=1 | latency=14.254s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the HTT?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target HTT.
[target_tool]: First, the system retrieved known disease–drug associations for HTT, which initially resulted in 3 entries.
[target_tool]: Next, any duplicate records among these associations were removed, reducing the number of entries from 3 to 1.
[target_tool]: In summary, after these steps, the system finalized a single unique association related to HTT.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000197386,htt,MONDO_0007739,huntington disease,0.708144

 Run 2 completed | rows=1 | latency=14.891s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the HTT?
  Attempt 1/3
[target_tool]: The query appears to aim at identifying associations related to a specific target, in this case, HTT. First, the system retrieved the known disease–drug associations for this target, which initially resulted in three entries. Then, to eliminate any redundancy, duplicate rows among these associations were removed. After deduplication, only one unique entry remained. Overall, the process filtered down the initial data to a single, distinct association record.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000197386,htt,MONDO_0007739,huntington disease,0.708144

 Run 3 completed | rows=1 | latency=13.845s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the HTT?
  Attempt 1/3
[target_tool]: The query was designed to identify associations related to the target HTT. The first step involved retrieving all known disease–drug associations for this target, which initially resulted in three entries. Subsequently, the system performed deduplication to remove any duplicate records, reducing the number of entries from three to one. In total, the final result includes a single unique association related to HTT.
----------------------------------------
Entries retrieved: 1

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000197386,htt,MONDO_0007739,huntington disease,0.708144

 Run 4 completed | rows=1 | latency=14.509s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the HTT?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target "HTT." First, the system retrieved the initial known associations for this target, which resulted in 3 entries. Next, the system performed deduplication to remove any duplicate associations, reducing the total from 3 to 1 entry. In the end, the process yielded a single, unique association related to "HTT."
----------------------------------------
Entries retrieved: 1

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000197386,htt,MONDO_0007739,huntington disease,0.708144

 Run 5 completed | rows=1 | latency=16.474s
------------------------------------------------------------


## Question 47

**Which genes are associated with breast cancer?**

In [84]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease-drug associations related to breast cancer. First, the system retrieved known associations between breast cancer and drugs, resulting in a total of 9,866 entries. Next, it applied deduplication to remove any duplicate records, reducing the number of entries from 9,866 to 571. In summary, after filtering, there are 571 unique disease-drug association entries related to breast cancer.
----------------------------------------
Entries retrieved: 571

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000121879,pik3ca,MONDO_0007254,breast cancer,Small molecule,0.878849

 Run 1 completed | rows=571 | latency=24.660s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease–drug associations related to breast cancer. First, the system retrieved a list of known disease associations, which initially included a large number of 9,866 entries. This step provided a broad set of data connecting various diseases and drugs.
[disease_tool]: Next, the system performed deduplication to remove any duplicate records within that list. After this filtering, the number of association entries was reduced from 9,866 to 571. This step eliminated redundant information, leaving a set of unique disease–drug association records.
[disease_tool]: In conclusion, the final data set consists of 571 unique disease–drug associations linked to breast cancer.
----------------------------------------
Entries retrieved: 571

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000121879,pik3ca,MONDO_0007254,breast cancer,Small molecule,0.878849

 Run 2 completed | rows=571 | latency=24.613s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: The goal of the query was to retrieve detailed information related to breast cancer and associated drugs.
[disease_tool]: First, the system retrieved known disease–drug associations relevant to breast cancer, which resulted in an initial set of 9,866 entries. This step collected possible links between breast cancer and various drugs from the database.
[disease_tool]: Next, the system removed duplicate entries to ensure that each association was listed only once. This deduplication reduced the number of entries from 9,866 to 571, eliminating 9,295 duplicate records and resulting in a cleaner, more accurate dataset.
[disease_tool]: In total, after these steps, the final result contains 571 unique associations related to breast cancer.
----------------------------------------
Entries retrieved: 571

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000121879,pik3ca,MONDO_0007254,breast cancer,Small molecule,0.878849

 Run 3 completed | rows=571 | latency=20.905s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: The query aims to find information related to breast cancer. First, the system retrieved known disease–drug associations for breast cancer, which initially yielded 9,866 entries. Next, the system performed deduplication to remove duplicate records, reducing the number of associations from 9,866 to 571.
[disease_tool]: In summary, the process started with a broad retrieval of associations related to breast cancer and was then refined by removing duplicates, resulting in a final set of 571 unique associations.
----------------------------------------
Entries retrieved: 571

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000121879,pik3ca,MONDO_0007254,breast cancer,Small molecule,0.878849

 Run 4 completed | rows=571 | latency=23.644s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
[disease_tool]: The query aimed to identify disease-drug associations related to breast cancer. First, the system retrieved a large set of known disease associations for breast cancer, resulting in 9,866 entries. Next, to improve data quality, it removed duplicate records, which reduced the result set from 9,866 to 571 entries. Finally, the process concluded with these 571 unique associations related to breast cancer.
----------------------------------------
Entries retrieved: 571

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000121879,pik3ca,MONDO_0007254,breast cancer,Small molecule,0.878849

 Run 5 completed | rows=571 | latency=19.409s
------------------------------------------------------------


## Question 48

**Which genes are associated with colorectal cancer?**

In [85]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aims to find information related to colorectal cancer.
[disease_tool]: First, the system retrieved known disease–drug associations for colorectal cancer, resulting in 4,922 entries. This initial retrieval brought back a large set of data related to the disease.
[disease_tool]: Next, the system performed a deduplication step to remove redundant records. After this process, the number of entries was reduced to 448, removing 4,474 duplicate rows and leaving only unique records.
[disease_tool]: In summary, the process started with 4,922 disease association entries, which were then refined to 448 unique records.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 1 completed | rows=448 | latency=19.330s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to colorectal cancer, focusing on the disease and its associated data.
[disease_tool]: Initially, the system retrieved known associations between colorectal cancer and various drugs, resulting in 4,922 entries. This step provided a broad set of data linking the disease with different biological entities.
[disease_tool]: Next, the process applied deduplication to remove redundant records. This step reduced the number of entries from 4,922 to 448, by eliminating duplicate rows. As a result, the dataset became more concise and manageable for further analysis.
[disease_tool]: In summary, after these steps, there are 448 unique association records related to colorectal cancer.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 2 completed | rows=448 | latency=18.411s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to colorectal cancer.
[disease_tool]: In the first step, the system retrieved known disease–drug associations for colorectal cancer, resulting in 4,922 records. This retrieval pulled all entries associated with the disease from the database.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, which reduced the number of records from 4,922 to 448. This step eliminated 4,474 duplicate rows, leaving a set of unique records related to colorectal cancer associations.
[disease_tool]: In total, the final result contains 448 distinct entries after removing duplicates.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 3 completed | rows=448 | latency=23.552s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: The goal of the query was to identify associations related to colorectal cancer.
[disease_tool]: First, the system retrieved known disease–drug associations specifically for colorectal cancer, resulting in a total of 4,922 records.
[disease_tool]: Next, the system removed duplicate entries from this set, reducing the number of records from 4,922 down to 448. This step eliminated 4,474 duplicate rows, ensuring that only unique associations remained.
[disease_tool]: In summary, the final result consists of 448 unique disease–drug association records related to colorectal cancer.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 4 completed | rows=448 | latency=19.119s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to colorectal cancer, focusing on known disease–drug associations.
[disease_tool]: Initially, the system retrieved a large set of known disease–drug associations for colorectal cancer, resulting in 4,922 entries. This step identified all possible links related to the disease without any filters applied.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate records within this data set. This process reduced the total from 4,922 entries to 448 unique records, eliminating 4,474 duplicate rows to ensure the results were distinct.
[disease_tool]: In summary, the process started with a broad collection of associated data and then narrowed it down to 448 unique entries relevant to colorectal cancer.
----------------------------------------
Entries retrieved: 448

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000141510,tp53,MONDO_0005575,colorectal cancer,Small molecule,0.833255

 Run 5 completed | rows=448 | latency=17.424s
------------------------------------------------------------


## Question 49

**What genes are linked to cystic fibrosis?**

In [86]:

question = 'What genes are linked to cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
[disease_tool]: The goal of the query was to identify disease-related information specifically related to cystic fibrosis. The process began with retrieving known disease associations for cystic fibrosis, resulting in an initial set of 484 entries. Next, to ensure accuracy and eliminate redundancies, duplicate records were removed from this set. This deduplication step reduced the number of entries from 484 to 227, leaving a refined list of unique disease association records related to cystic fibrosis.
----------------------------------------
Entries retrieved: 227

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000001626,cftr,MONDO_0009061,cystic fibrosis,Small molecule,0.913383

 Run 1 completed | rows=227 | latency=14.921s
------------------------------------------------------------

 Starting run 2 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
[disease_tool]: The query aimed to find information related to cystic fibrosis, including associated drugs and mechanisms.
[disease_tool]: First, the system retrieved known disease–drug associations specific to cystic fibrosis. Initially, this step retrieved 484 rows of data.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, which reduced the dataset from 484 to 227 rows. This process removed 257 duplicate records, leaving a cleaner set of unique associations for further analysis.
[disease_tool]: In total, the final result after these steps included 227 unique entries related to cystic fibrosis.
----------------------------------------
Entries retrieved: 227

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000001626,cftr,MONDO_0009061,cystic fibrosis,Small molecule,0.913383

 Run 2 completed | rows=227 | latency=17.281s
------------------------------------------------------------

 Starting run 3 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
[disease_tool]: The query aims to find associations related to cystic fibrosis.
[disease_tool]: First, the system retrieved known disease–drug associations for cystic fibrosis. Initially, 484 records were obtained containing these associations. Then, the system removed duplicate entries from these records, reducing the total from 484 to 227.
[disease_tool]: In total, the process resulted in 227 unique association records for further analysis or review.
----------------------------------------
Entries retrieved: 227

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000001626,cftr,MONDO_0009061,cystic fibrosis,Small molecule,0.913383

 Run 3 completed | rows=227 | latency=17.004s
------------------------------------------------------------

 Starting run 4 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
[disease_tool]: The purpose of the query was to explore information related to cystic fibrosis. First, the system retrieved known disease–drug associations for cystic fibrosis, resulting in 484 entries.
[disease_tool]: Next, the system removed duplicate entries from this list, reducing the number of associations from 484 to 227.
[disease_tool]: In summary, after filtering duplicates, there are 227 unique associations related to cystic fibrosis.
----------------------------------------
Entries retrieved: 227

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000001626,cftr,MONDO_0009061,cystic fibrosis,Small molecule,0.913383

 Run 4 completed | rows=227 | latency=15.064s
------------------------------------------------------------

 Starting run 5 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
[disease_tool]: The intent of the query was to find information related to cystic fibrosis from known disease-drug associations.
[disease_tool]: First, the system retrieved all known disease–drug associations related to cystic fibrosis, which initially resulted in 484 entries.
[disease_tool]: Next, duplicate records were removed to ensure each association was unique, reducing the set from 484 to 227 entries.
[disease_tool]: In summary, after applying the duplication removal step, there are 227 unique associations related to cystic fibrosis remaining in the result set.
----------------------------------------
Entries retrieved: 227

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000001626,cftr,MONDO_0009061,cystic fibrosis,Small molecule,0.913383

 Run 5 completed | rows=227 | latency=16.157s
------------------------------------------------------------


## Question 50

**What drugs are used in glioblastoma?**

In [87]:

question = 'What drugs are used in glioblastoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in glioblastoma?
  Attempt 1/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 16.836s: Returned object is not a DataFrame
  Attempt 2/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 2 failed after 16.440s: Returned object is not a DataFrame
  Attempt 3/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 3 failed after 13.690s: Returned object is not a DataFrame
 Run 1 failed after 3 attempts
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in glioblastoma?
  Attempt 1/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[target_tool]: No resolved target found.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 1 failed after 30.005s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
[disease_tool]: The query was intended to identify disease-drug associations involving specific mechanisms of action.
[disease_tool]: However, the execution log provided is empty, indicating that no processing steps were performed. As a result, there was no retrieval or filtering of associations, diseases, or drugs, and no pathway or mechanism information was retrieved or filtered. No duplicate removal steps took place, and no results were narrowed down through any filters.
[disease_tool]: Because there are no detailed steps in the log to describe, the final result returned is an empty set.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
 Attempt 2 failed after 30.004s: OpenTargets query exceeded 30.0 seconds
  Attempt 3/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"
[readme_tool]: "What is the target of Aspirin?"
[readme_tool]: What drugs are used to treat TB?
----------------------------------------
 Attempt 3 failed after 15.126s: Returned object is not a DataFrame
 Run 2 failed after 3 attempts
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in glioblastoma?
  Attempt 1/3
[disease_tool]: No associations found for this disease.
----------------------------------------
[drug_tool]: No resolved drug found.
----------------------------------------
[readme_tool]: # BioChirp OpenTargets Guide
[readme_tool]: ## Tools
[readme_tool]: **Disease Tool** - Drugs & targets for diseases
[readme_tool]: Returns: Drugs, targets, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Give list of Breast cancer drugs"
[readme_tool]: **Drug Tool** - Indications & targets for drugs
[readme_tool]: Returns: Diseases, targets, mechanisms, phases, synonyms, description, CSV download
[readme_tool]: Example: "What does aspirin treat?"
[readme_tool]: **Target Tool** - Diseases & drugs for genes/proteins
[readme_tool]: Returns: Diseases, drugs, association scores, phases, synonyms, description, CSV download
[readme_tool]: Example: "Disease associated with TP53"
[readme_tool]: **Web Search** - Current info beyond database
[readme_tool]: ## Entities Supported
[readme_tool]: **Diseases:** Medical names → EFO IDs
[readme_tool]: **Drugs:** Generic/brand names → ChEMBL IDs
[readme_tool]: **Targets:** Gene symbols → Ensembl IDs
[readme_tool]: **Mechanisms:** inhibitor, antagonist, modulator, agonist, blocker, activator
[readme_tool]: **Pathways:** PI3K/AKT pathway, MAPK signaling, etc.
[readme_tool]: ## Resolution Methods
[readme_tool]: **OpenTargets mapping:** Direct match (fast, accurate)
[readme_tool]: **Web search:** Fallback when not in mapping
[readme_tool]: You'll see: "matched in OpenTargets" or "found via web search"
[readme_tool]: ## Query Patterns
[readme_tool]: **Single:** "Melanoma drugs" "What does metformin treat?"
[readme_tool]: **Filtered:** "Give drug that target TP53 in breast cancer treatment."
[readme_tool]: ## Output
[readme_tool]: - Entity IDs with resolution method
[readme_tool]: - Entity synonyms and descriptions
[readme_tool]: - Preview (50 rows) + full CSV download
[readme_tool]: - Smart column filtering based on query
[readme_tool]: ## Tips
[readme_tool]: ✓ Specific names, standard terms, combine entities ("X for Y")
[readme_tool]: ✗ Single vague words, colloquial-only terms
[readme_tool]: ## Examples
[readme_tool]: "What does aspirin treat?"


## Question 51

**Which diseases are treated by metformin?**

In [88]:

question = 'Which diseases are treated by metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated by metformin?
  Attempt 1/3
[drug_tool]: The query aims to identify drugs associated with a particular disease and then narrow down these findings based on specific filters.
[drug_tool]: First, the system retrieved known drug associations related to the drug "metformin," resulting in a total of 20,298 entries. This initial step gathered all the known relationships for this medication without filtering.
[drug_tool]: Next, the system performed a deduplication process to remove any duplicate records, which reduced the number of entries from 20,298 to 796. This step eliminated repeated records, leaving a cleaner set of unique associations for further analysis.
[drug_tool]: In summary, the process started with over twenty thousand associations and was refined to just under a thousand unique entries.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,metformin,EFO_0000400,diabetes mellitus,4.0,Recruiting,mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 1 completed | rows=796 | latency=25.867s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated by metformin?
  Attempt 1/3
[drug_tool]: The query aimed to find drug associations related to metformin.
[drug_tool]: First, the system retrieved known drug associations for metformin, resulting in 20,298 entries.
[drug_tool]: Next, the system removed duplicate records from this set, reducing the number of entries from 20,298 to 796.
[drug_tool]: In summary, after deduplication, the final result contains 796 unique association records related to metformin.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,metformin,EFO_0000400,diabetes mellitus,4.0,Recruiting,mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 2 completed | rows=796 | latency=22.763s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated by metformin?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to metformin.
[drug_tool]: First, the system retrieved all known drug associations for metformin, resulting in 20,298 entries. This initial step fetched broad data on drugs linked to this compound.
[drug_tool]: Next, duplicate records were removed from this set of associations to ensure each entry was unique. After this deduplication process, the number of entries was reduced from 20,298 to 796.
[drug_tool]: In summary, the final result contains 796 unique drug association records for metformin after removing duplicates.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,metformin,EFO_0000400,diabetes mellitus,4.0,Recruiting,mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 3 completed | rows=796 | latency=24.227s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated by metformin?
  Attempt 1/3
[drug_tool]: The query aimed to identify drug associations related to metformin.
[drug_tool]: First, the system retrieved the base drug associations for metformin, resulting in a total of 20,298 entries. This step gathered all known associations without applying any filters initially.
[drug_tool]: Next, the system performed deduplication to remove duplicate records from the dataset. After this process, the number of association records was reduced from 20,298 to 796, eliminating 19,502 duplicate entries.
[drug_tool]: In summary, the process started with a broad set of over twenty thousand associations and was narrowed down to 796 unique entries by removing duplicates.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,metformin,EFO_0000400,diabetes mellitus,4.0,Recruiting,mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 4 completed | rows=796 | latency=23.099s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated by metformin?
  Attempt 1/3
[drug_tool]: The intent of the query was to identify drug associations related to a specific drug, in this case, metformin.
[drug_tool]: Initially, the system retrieved all known disease–drug associations for metformin, resulting in 20,298 entries.
[drug_tool]: Next, the process involved deduplicating these entries to remove any duplicate records, which reduced the total from 20,298 to 796 unique associations.
[drug_tool]: Overall, after applying all steps, the resulting dataset contained 796 unique associations linked to metformin.
----------------------------------------
Entries retrieved: 796

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1431,metformin,EFO_0000400,diabetes mellitus,4.0,Recruiting,mitochondrial glycerol-3-phosphate dehydrogena...,PubMed

 Run 5 completed | rows=796 | latency=22.519s
------------------------------------------------------------


## Question 52

**What conditions is adalimumab used for?**

In [89]:

question = 'What conditions is adalimumab used for?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What conditions is adalimumab used for?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug associations related to a specific drug.
[drug_tool]: The first step involved retrieving known disease–drug associations for adalimumab. This search yielded 131 entries, providing a base set of associations involving this drug.
[drug_tool]: No further filtering steps are shown in this log segment, so the total number of associations related to adalimumab remains at 131.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,adalimumab,EFO_0000384,crohn's disease,4.0,Enrolling by invitation,tnf-alpha inhibitor,DailyMed

 Run 1 completed | rows=131 | latency=15.271s
------------------------------------------------------------

 Starting run 2 for query: What conditions is adalimumab used for?
  Attempt 1/3
[drug_tool]: The query was aimed at understanding the associations between a specific drug and diseases. The process started with retrieving known disease-drug associations related to adalimumab. This initial retrieval resulted in 131 associations, establishing a basis for further filtering and analysis.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,adalimumab,EFO_0000384,crohn's disease,4.0,Enrolling by invitation,tnf-alpha inhibitor,DailyMed

 Run 2 completed | rows=131 | latency=13.957s
------------------------------------------------------------

 Starting run 3 for query: What conditions is adalimumab used for?
  Attempt 1/3
[drug_tool]: The query aims to explore the relationships between a specific drug and related biological entities.
[drug_tool]: Initially, the system retrieved known associations involving the drug adalimumab, resulting in a data set of 131 records.
[drug_tool]: Next, further steps would typically involve applying disease, drug, or mechanism filters, retrieving pathway information, or removing duplicates to refine the results. However, based on the provided log, only the first step of association retrieval has been detailed.
[drug_tool]: In summary, the final count of associations involving adalimumab at this stage is 131, representing the initial set of known drug-related associations retrieved during the process.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,adalimumab,EFO_0000384,crohn's disease,4.0,Enrolling by invitation,tnf-alpha inhibitor,DailyMed

 Run 3 completed | rows=131 | latency=13.471s
------------------------------------------------------------

 Starting run 4 for query: What conditions is adalimumab used for?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug associations related to adalimumab. First, the system retrieved known disease-drug associations for adalimumab, resulting in a total of 131 entries. This step gathered all potential related associations before applying further filters. Since there were no additional filtering steps shown in the log, the initial retrieval provided the full set of associations for adalimumab. Therefore, the final result consists of 131 entries related to adalimumab.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,adalimumab,EFO_0000384,crohn's disease,4.0,Enrolling by invitation,tnf-alpha inhibitor,DailyMed

 Run 4 completed | rows=131 | latency=13.529s
------------------------------------------------------------

 Starting run 5 for query: What conditions is adalimumab used for?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug associations related to adalimumab. The first step involved retrieving known disease–drug associations for adalimumab, which resulted in 131 entries. This initial retrieval set the foundation for further filtering. Since no previous number of rows is provided, the total of 131 entries reflects the starting dataset after association retrieval. This step helped gather a broad set of potential disease connections involving adalimumab for subsequent analysis.
----------------------------------------
Entries retrieved: 131

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1201580,adalimumab,EFO_0000384,crohn's disease,4.0,Enrolling by invitation,tnf-alpha inhibitor,DailyMed

 Run 5 completed | rows=131 | latency=14.986s
------------------------------------------------------------


## Question 53

**Which diseases are pembrolizumab used in?**

In [90]:

question = 'Which diseases are pembrolizumab used in?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
[drug_tool]: The query's goal was to find related drugs and their mechanisms of action for pembrolizumab. First, the system retrieved known disease-drug associations for pembrolizumab, resulting in 815 records. This step established a broad set of associations involving the drug, serving as the foundation for further filtering. Since there are no additional filters or narrowing steps shown in this part of the log, the initial retrieval was the primary step. The total number of associations at this stage remained 815.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,pembrolizumab,MONDO_0021251,endometrium neoplasm,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 1 completed | rows=815 | latency=16.015s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
[drug_tool]: The intent of the query was to explore drug associations related to pembrolizumab.
[drug_tool]: The first step retrieved known disease–drug associations for pembrolizumab, resulting in 815 entries. This initial retrieval provided a broad set of data connecting pembrolizumab with various diseases or conditions.
[drug_tool]: There were no further filtering steps shown in the provided log, so the result remains at 815 entries.
[drug_tool]: In summary, the process resulted in a total of 815 drug association records for pembrolizumab.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,pembrolizumab,MONDO_0021251,endometrium neoplasm,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 2 completed | rows=815 | latency=14.516s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
[drug_tool]: The query aims to identify relevant drug-disease associations for pembrolizumab.
[drug_tool]: First, the system retrieved the base drug associations for pembrolizumab, resulting in a total of 815 entries.
[drug_tool]: This initial retrieval provides the foundation for further filtering based on specific diseases or mechanisms, but no additional filtering steps are shown in the provided log.
[drug_tool]: In summary, the process started with 815 associations related to pembrolizumab, establishing the initial dataset for further analysis.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,pembrolizumab,MONDO_0021251,endometrium neoplasm,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 3 completed | rows=815 | latency=14.423s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
[drug_tool]: The query aimed to explore drug and disease associations related to pembrolizumab.
[drug_tool]: First, the system retrieved the base associations for pembrolizumab, which initially resulted in 815 entries. This step involved gathering known links between pembrolizumab and various diseases or conditions.
[drug_tool]: Since only this initial step is recorded in the provided log, no further filtering or narrowing of results is detailed. Therefore, the process at this stage focused on establishing the full set of known associations for pembrolizumab.
[drug_tool]: In summary, the result after retrieval consisted of 815 associations linked to pembrolizumab.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,pembrolizumab,MONDO_0021251,endometrium neoplasm,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 4 completed | rows=815 | latency=16.244s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
[drug_tool]: The query aims to find detailed information related to pembrolizumab in the context of drug associations. First, the system retrieved known associations between pembrolizumab and various diseases or biological mechanisms. This initial retrieval resulted in 815 associated records. Since this was the initial step, no prior row count is available. This step sets the foundation for further filtering based on specific diseases, drugs, mechanisms, or pathways.
----------------------------------------
Entries retrieved: 815

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL3137343,pembrolizumab,MONDO_0021251,endometrium neoplasm,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 5 completed | rows=815 | latency=15.092s
------------------------------------------------------------


## Question 54

**Which diseases are treated with sorafenib?**

In [91]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The intent of the query was to explore associations related to the drug sorafenib. First, the system retrieved a set of 2,799 known associations involving sorafenib. Then, to ensure the results were unique and eliminate any duplicate entries, the system performed a deduplication step. This filtering reduced the number of associations from 2,799 to 2,177, removing 622 duplicate rows. The final result consists of 2,177 unique associations involving sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,sorafenib,MONDO_0002691,liver cancer,3.0,Recruiting,serine/threonine-protein kinase raf inhibitor,FDA

 Run 1 completed | rows=2177 | latency=18.559s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: This query aimed to identify drugs associated with a specific disease or condition, focusing on sorafenib.
[drug_tool]: First, the system retrieved known disease–drug associations for sorafenib, which resulted in 2,799 records. This step involved gathering all known relationships involving sorafenib without initial filters.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries from the retrieved associations. This reduced the number of records from 2,799 to 2,177, eliminating 622 duplicate rows to produce a cleaner set of unique associations.
[drug_tool]: In total, after these steps, the final result includes 2,177 unique drug associations related to sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,sorafenib,MONDO_0002691,liver cancer,3.0,Recruiting,serine/threonine-protein kinase raf inhibitor,FDA

 Run 2 completed | rows=2177 | latency=16.576s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The query aims to find drug associations related to sorafenib and refine these results.
[drug_tool]: Initially, the system retrieved the known drug associations for sorafenib, resulting in 2,799 records.
[drug_tool]: Next, the system removed duplicate entries from these results to ensure each association was unique, reducing the total from 2,799 to 2,177 records. This deduplication step eliminated 622 duplicate rows for a cleaner, more accurate set of data.
[drug_tool]: The final result contains 2,177 unique drug association records related to sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,sorafenib,MONDO_0002691,liver cancer,3.0,Recruiting,serine/threonine-protein kinase raf inhibitor,FDA

 Run 3 completed | rows=2177 | latency=14.939s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to sorafenib.
[drug_tool]: Initially, the system retrieved known drug associations for sorafenib, which resulted in a total of 2,799 records. This step gathered all potential data points related to the drug before applying any filters.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries from the dataset. This step reduced the number of associations from 2,799 down to 2,177, eliminating 622 duplicate rows.
[drug_tool]: In total, the final dataset after filtering contains 2,177 unique drug association records for sorafenib.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,sorafenib,MONDO_0002691,liver cancer,3.0,Recruiting,serine/threonine-protein kinase raf inhibitor,FDA

 Run 4 completed | rows=2177 | latency=15.041s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
[drug_tool]: The query aims to analyze drug associations related to sorafenib.
[drug_tool]: First, the system retrieved all known drug associations for sorafenib, resulting in a total of 2799 entries. This step gathered a broad set of potential data points related to the drug without applying any filters initially.
[drug_tool]: Next, the system removed duplicate entries from this set. This deduplication reduced the number of entries from 2799 to 2177, eliminating 622 repeated records to ensure that each association is unique.
[drug_tool]: In summary, the process started with a comprehensive collection of associations for sorafenib and then refined this data by removing duplicates, ending with 2177 unique drug association records.
----------------------------------------
Entries retrieved: 2177

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL1336,sorafenib,MONDO_0002691,liver cancer,3.0,Recruiting,serine/threonine-protein kinase raf inhibitor,FDA

 Run 5 completed | rows=2177 | latency=16.988s
------------------------------------------------------------


## Question 55

**What diseases are treated with nivolumab?**

In [92]:

question = 'What diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aims to identify drug associations related to nivolumab. The process started with retrieving all known disease–drug associations specifically for nivolumab. Initially, there was no prior row count provided, but after this retrieval step, the number of associations increased to 655. This step gathered a broad set of potential disease links for nivolumab, forming the initial dataset for further filtering.
[drug_tool]: In summary, the final result includes 655 associations related to nivolumab.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,nivolumab,MONDO_0009348,classic hodgkin lymphoma,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 1 completed | rows=655 | latency=15.491s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aims to explore the associations between the drug nivolumab and various disease conditions or mechanisms.
[drug_tool]: Initially, the system retrieved known associations between nivolumab and different diseases, resulting in a total of 655 entries. This step provided the foundational set of data linking the drug to multiple health conditions.
[drug_tool]: Next, the process would typically involve applying further filters such as specific diseases, drugs, or mechanisms of action to narrow down the results. Since no additional filtering steps are shown in the provided log, it appears this was either not performed or not recorded here.
[drug_tool]: Finally, the total number of associations retrieved for nivolumab at this stage was 655.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,nivolumab,MONDO_0009348,classic hodgkin lymphoma,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 2 completed | rows=655 | latency=16.239s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The query aimed to find drug associations related to nivolumab. The first step involved retrieving known associations between drugs and diseases, starting with an initial set of 655 entries after the retrieval process. This step established a database of existing links between various drugs and health conditions for analysis.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,nivolumab,MONDO_0009348,classic hodgkin lymphoma,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 3 completed | rows=655 | latency=13.175s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The intent of the query was to identify drug associations related to nivolumab.
[drug_tool]: The first step involved retrieving known drug associations for nivolumab. This step resulted in 655 entries, providing a broad collection of potential related drugs.
[drug_tool]: Since no further steps are provided in the log, the process concludes with these 655 associations.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,nivolumab,MONDO_0009348,classic hodgkin lymphoma,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 4 completed | rows=655 | latency=12.665s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with nivolumab?
  Attempt 1/3
[drug_tool]: The purpose of the query was to explore biomedical information related to the drug nivolumab.
[drug_tool]: The first step involved retrieving known disease–drug associations for nivolumab. This added 655 data entries, providing a foundation of existing associations between the drug and various diseases.
[drug_tool]: As the only step shown in the provided log, no additional filtering or processing was performed.
[drug_tool]: In total, the process resulted in a set of 655 associations related to nivolumab.
----------------------------------------
Entries retrieved: 655

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL2108738,nivolumab,MONDO_0009348,classic hodgkin lymphoma,4.0,NaN,programmed cell death protein 1 inhibitor,FDA

 Run 5 completed | rows=655 | latency=15.331s
------------------------------------------------------------


## Question 56

**Genes linked to multiple sclerosis.**

In [93]:

question = 'Genes linked to multiple sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
[disease_tool]: The query aims to find relevant information related to multiple sclerosis by first retrieving known disease-drug associations. Initially, 1,988 associations were retrieved for the disease multiple sclerosis. Then, to improve data quality, the system removed duplicate entries, reducing the list from 1,988 to 290. After these steps, the system has a refined set of 290 unique disease association records related to multiple sclerosis.
----------------------------------------
Entries retrieved: 290

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0005301,multiple sclerosis,Small molecule,0.684313

 Run 1 completed | rows=290 | latency=17.585s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
[disease_tool]: The query aimed to find relevant information concerning multiple sclerosis, a specific disease.
[disease_tool]: Initially, the system retrieved a set of relationships between multiple sclerosis and various drugs, resulting in 1988 entries. This step involved gathering all known disease–drug associations relevant to multiple sclerosis.
[disease_tool]: Next, the system performed a deduplication process to remove any duplicate records from the initial set. After this step, the number of entries was reduced from 1988 to 290, meaning 1698 duplicate records were eliminated, leaving a cleaner, non-redundant dataset.
[disease_tool]: In summary, after these steps, the dataset was narrowed down to 290 unique associations related to multiple sclerosis.
----------------------------------------
Entries retrieved: 290

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0005301,multiple sclerosis,Small molecule,0.684313

 Run 2 completed | rows=290 | latency=17.673s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
[disease_tool]: The query aimed to find disease–drug associations related to multiple sclerosis.
[disease_tool]: Initially, the system retrieved a set of associations related to multiple sclerosis, which resulted in 1988 entries.
[disease_tool]: Next, to refine this data, the system removed duplicate records. This deduplication process reduced the number of entries from 1988 to 290, eliminating 1698 duplicate rows.
[disease_tool]: In the end, the result set contained 290 unique disease–drug association entries associated with multiple sclerosis.
----------------------------------------
Entries retrieved: 290

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0005301,multiple sclerosis,Small molecule,0.684313

 Run 3 completed | rows=290 | latency=15.859s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
[disease_tool]: The query aimed to find information related to multiple sclerosis, focusing on disease associations.
[disease_tool]: First, the system retrieved known disease–drug associations related to multiple sclerosis. Initially, this retrieval produced 1,988 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records. This process reduced the number of entries from 1,988 to 290, eliminating 1,698 duplicate records, resulting in a set of unique association data.
[disease_tool]: In summary, after these steps, 290 unique disease association records for multiple sclerosis remained.
----------------------------------------
Entries retrieved: 290

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0005301,multiple sclerosis,Small molecule,0.684313

 Run 4 completed | rows=290 | latency=17.660s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
[disease_tool]: The query aims to identify disease and drug associations related to multiple sclerosis.
[disease_tool]: Initially, the system retrieved known disease associations related to multiple sclerosis. This step returned 1,988 records.
[disease_tool]: Next, the system removed duplicate rows from these retrieved associations, reducing the total from 1,988 to 290 unique entries.
[disease_tool]: In total, the process resulted in 290 distinct disease association records related to multiple sclerosis.
----------------------------------------
Entries retrieved: 290

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0005301,multiple sclerosis,Small molecule,0.684313

 Run 5 completed | rows=290 | latency=16.864s
------------------------------------------------------------


## Question 57

**Provide target names for rheumatoid arthritis.**

In [94]:

question = 'Provide target names for rheumatoid arthritis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
[disease_tool]: The query aimed to find information related to rheumatoid arthritis. First, the system retrieved known disease–drug associations for rheumatoid arthritis, resulting in 1,365 entries. Next, it removed duplicate records, which reduced the number of entries from 1,365 to 258, eliminating 1,107 duplicate records. In the end, the filtered set contained 258 unique disease–drug association entries related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 258

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000160712,il6r,EFO_0000685,rheumatoid arthritis,Antibody,0.735062

 Run 1 completed | rows=258 | latency=18.872s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to rheumatoid arthritis, focusing on associated diseases and drugs.
[disease_tool]: First, the system retrieved disease–drug association data for rheumatoid arthritis, resulting in a total of 1,365 records. This step identified known relationships between rheumatoid arthritis and various drugs or related conditions.
[disease_tool]: Next, the system performed a deduplication process to remove duplicate entries within this dataset. This step reduced the number of records from 1,365 to 258, eliminating 1,107 duplicate rows and leaving a set of unique association records.
[disease_tool]: In summary, after these steps, there are 258 distinct association records related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 258

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000160712,il6r,EFO_0000685,rheumatoid arthritis,Antibody,0.735062

 Run 2 completed | rows=258 | latency=15.941s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
[disease_tool]: The query aimed to find specific associations related to rheumatoid arthritis.
[disease_tool]: First, the system retrieved known disease–drug associations for rheumatoid arthritis, which initially returned 1,365 records.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, reducing the total from 1,365 to 258 unique entries. This step eliminated 1,107 duplicate rows.
[disease_tool]: In summary, the final result consists of 258 unique disease–drug association records related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 258

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000160712,il6r,EFO_0000685,rheumatoid arthritis,Antibody,0.735062

 Run 3 completed | rows=258 | latency=18.755s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
[disease_tool]: The query aims to explore disease-drug associations related to rheumatoid arthritis. First, the system retrieved known associations between rheumatoid arthritis and various diseases or drugs, resulting in a total of 1,365 entries. Next, the system performed deduplication to remove duplicate records, which reduced the number of entries from 1,365 to 258. This step ensured that only unique associations remained. In total, the process resulted in 258 distinct disease-related associations connected to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 258

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000160712,il6r,EFO_0000685,rheumatoid arthritis,Antibody,0.735062

 Run 4 completed | rows=258 | latency=16.914s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
[disease_tool]: The query aims to identify potential drug associations related to rheumatoid arthritis.
[disease_tool]: Initially, the system retrieved known disease–drug associations for rheumatoid arthritis, which resulted in 1,365 entries. This step provided a broad collection of data linking drugs to the disease.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from the dataset. This process reduced the number of entries from 1,365 to 258, eliminating 1,107 duplicate rows to ensure the results were unique and more accurate.
[disease_tool]: In summary, after these steps, the final set contains 258 unique disease–drug associations specifically related to rheumatoid arthritis.
----------------------------------------
Entries retrieved: 258

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000160712,il6r,EFO_0000685,rheumatoid arthritis,Antibody,0.735062

 Run 5 completed | rows=258 | latency=20.255s
------------------------------------------------------------


## Question 58

**What are the targets of abatacept?**

In [95]:

question = 'What are the targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets of abatacept?
  Attempt 1/3
[drug_tool]: The query aims to identify specific drug associations related to abatacept.
[drug_tool]: Initially, the system retrieved known disease–drug associations for abatacept, resulting in 182 records being gathered.
[drug_tool]: Next, the system removed duplicate records from this set, reducing the total from 182 to just 2 unique entries.
[drug_tool]: In summary, after filtering for unique associations involving abatacept, the final result count was 2.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,cd86,CHEMBL1201823,abatacept,t-lymphocyte activation antigen cd86 inhibitor,DailyMed

 Run 1 completed | rows=2 | latency=14.554s
------------------------------------------------------------

 Starting run 2 for query: What are the targets of abatacept?
  Attempt 1/3
[drug_tool]: The goal of the query was to retrieve and process information related to the drug abatacept.
[drug_tool]: First, the system retrieved known associations between diseases and drugs related to abatacept. This step resulted in 182 rows of data containing various disease-drug links.
[drug_tool]: Next, the system performed deduplication to remove duplicate entries from this set of associations. This process reduced the number of entries dramatically from 182 to just 2, leaving only unique records.
[drug_tool]: In summary, after these steps, the final result contains 2 unique disease-drug association entries for abatacept.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,cd86,CHEMBL1201823,abatacept,t-lymphocyte activation antigen cd86 inhibitor,DailyMed

 Run 2 completed | rows=2 | latency=16.441s
------------------------------------------------------------

 Starting run 3 for query: What are the targets of abatacept?
  Attempt 1/3
[drug_tool]: The purpose of this query was to find drug associations related to the drug abatacept.
[drug_tool]: First, the system retrieved a set of known drug associations for abatacept, resulting in 182 records. This step gathered all the initial relations for the specified drug.
[drug_tool]: Next, the system performed deduplication to remove any duplicate entries, reducing the number of records from 182 to just 2. This filtering process ensured only unique associations remained.
[drug_tool]: In total, the final result contains 2 unique drug association records for abatacept.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,cd86,CHEMBL1201823,abatacept,t-lymphocyte activation antigen cd86 inhibitor,DailyMed

 Run 3 completed | rows=2 | latency=14.292s
------------------------------------------------------------

 Starting run 4 for query: What are the targets of abatacept?
  Attempt 1/3
[drug_tool]: The query was designed to identify information related to the drug abatacept.
[drug_tool]: First, the system retrieved all known associations between the disease and drugs related to abatacept. This initial retrieval brought up 182 records.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries, reducing the number of records from 182 to just 2.
[drug_tool]: In summary, after these steps, only 2 unique records remained that are associated with abatacept.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,cd86,CHEMBL1201823,abatacept,t-lymphocyte activation antigen cd86 inhibitor,DailyMed

 Run 4 completed | rows=2 | latency=14.306s
------------------------------------------------------------

 Starting run 5 for query: What are the targets of abatacept?
  Attempt 1/3
[drug_tool]: This query aimed to retrieve drug associations related to the drug abatacept.
[drug_tool]: Initially, the system retrieved known disease–drug associations for abatacept, which resulted in 182 entries.
[drug_tool]: Next, the system performed deduplication to remove duplicate records from this set. This step significantly reduced the number of entries from 182 to just 2, by eliminating redundant rows.
[drug_tool]: In total, the process ended with 2 unique association records for abatacept.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000114013,cd86,CHEMBL1201823,abatacept,t-lymphocyte activation antigen cd86 inhibitor,DailyMed

 Run 5 completed | rows=2 | latency=13.735s
------------------------------------------------------------


## Question 59

**Provide target names for lung cancer.**

In [96]:

question = 'Provide target names for lung cancer.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for lung cancer.
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to lung cancer.
[disease_tool]: Initially, the system retrieved a large set of known disease–drug associations related to lung cancer, resulting in 10,423 entries. This step involved collecting all potential associations before any filtering.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries from the dataset. As a result, the number of unique associations was reduced from 10,423 to 614 entries, eliminating 9,809 redundant rows.
[disease_tool]: In summary, the final result includes 614 unique disease–drug association entries for lung cancer after applying association retrieval and deduplication steps.
----------------------------------------
Entries retrieved: 614

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000146648,egfr,MONDO_0008903,lung cancer,Antibody,0.897761

 Run 1 completed | rows=614 | latency=23.769s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for lung cancer.
  Attempt 1/3
[disease_tool]: The query aims to identify potential disease-related associations, specifically focusing on lung cancer.
[disease_tool]: Initially, the system retrieved a broad set of known disease–drug associations related to lung cancer, which resulted in a total of 10,423 entries.
[disease_tool]: Next, to ensure the quality and uniqueness of the data, the system performed deduplication. This process removed duplicate entries, reducing the number of associations from 10,423 to 614.
[disease_tool]: In total, the process started with a large set of data and refined it to a smaller, more precise collection of 614 unique associations related to lung cancer.
----------------------------------------
Entries retrieved: 614

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000146648,egfr,MONDO_0008903,lung cancer,Antibody,0.897761

 Run 2 completed | rows=614 | latency=21.782s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for lung cancer.
  Attempt 1/3
[disease_tool]: The query's aim was to explore disease-related associations, focusing on lung cancer.
[disease_tool]: First, the system retrieved known disease associations related to lung cancer, resulting in a total of 10,423 entries. This initial step involved gathering all relevant data links before any filtering.
[disease_tool]: Next, to ensure data quality and eliminate redundancy, the system removed duplicate records. This deduplication process reduced the number of entries from 10,423 to 614.
[disease_tool]: In conclusion, after filtering out duplicates, 614 unique disease association entries related to lung cancer remained.
----------------------------------------
Entries retrieved: 614

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000146648,egfr,MONDO_0008903,lung cancer,Antibody,0.897761

 Run 3 completed | rows=614 | latency=21.055s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for lung cancer.
  Attempt 1/3
[disease_tool]: The user's query aimed to retrieve information related to lung cancer.
[disease_tool]: First, the system retrieved known disease–drug associations for lung cancer, resulting in 10,423 entries. These entries represented the initial set of data associated with the disease.
[disease_tool]: Next, the system performed deduplication to remove duplicate records within this dataset. This process reduced the number of entries from 10,423 to 614, eliminating all duplicate rows and leaving only unique records.
[disease_tool]: In summary, after retrieving the initial associations and removing duplicates, the final result consisted of 614 unique entries related to lung cancer.
----------------------------------------
Entries retrieved: 614

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000146648,egfr,MONDO_0008903,lung cancer,Antibody,0.897761

 Run 4 completed | rows=614 | latency=22.515s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for lung cancer.
  Attempt 1/3
[disease_tool]: The query aims to explore disease-drug associations related to lung cancer. The first step retrieved base disease associations for lung cancer, resulting in a total of 10,423 entries.
[disease_tool]: Next, the data underwent deduplication to remove duplicate records. This process reduced the number of entries from 10,423 to 614, removing 9,809 duplicate rows. The overall result is a refined set of 614 unique disease association records for lung cancer.
----------------------------------------
Entries retrieved: 614

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000146648,egfr,MONDO_0008903,lung cancer,Antibody,0.897761

 Run 5 completed | rows=614 | latency=22.258s
------------------------------------------------------------


## Question 60

**What are the known targets of ponatinib?**

In [97]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The goal of the query was to examine drug associations related to ponatinib.
[drug_tool]: Initially, the system retrieved all known associations for ponatinib, resulting in a total of 76 entries. This set included multiple records, some of which may have been duplicates.
[drug_tool]: Next, the system performed deduplication to remove redundant entries, reducing the number of results from 76 down to 2. This process ensured that only unique association records remained, providing a concise set of distinct drug association data for ponatinib.
[drug_tool]: In summary, the final output contains 2 unique drug association records for ponatinib after filtering out duplicates.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,abl1,CHEMBL1171837,ponatinib,bcr/abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 1 completed | rows=2 | latency=15.156s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The goal of the query was to identify drugs associated with a specific disease or condition.
[drug_tool]: First, the system retrieved known drug associations related to "ponatinib." This step initially gathered 76 associations, but it did not specify the starting number of associations before this retrieval.
[drug_tool]: Next, to ensure the results were unique, the system removed duplicate records, reducing the total from 76 to just 2. This step eliminated 74 duplicate entries, leaving only the distinct associations.
[drug_tool]: In summary, the final result contains 2 unique drug associations related to "ponatinib."
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,abl1,CHEMBL1171837,ponatinib,bcr/abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 2 completed | rows=2 | latency=15.158s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The intent of the query was to find information related to the drug ponatinib, specifically focusing on its known associations with diseases and other biological entities.
[drug_tool]: The first step involved retrieving known drug associations for ponatinib. This step resulted in 76 entries, which included various connections or relationships identified in the database.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries. This step reduced the number of entries from 76 down to just 2, leaving only unique records related to ponatinib.
[drug_tool]: In summary, after applying all steps, the final result consisted of 2 unique association records related to ponatinib.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,abl1,CHEMBL1171837,ponatinib,bcr/abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 3 completed | rows=2 | latency=15.244s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The goal of the query was to find information related to drugs associated with a specific disease.
[drug_tool]: Initially, the system retrieved known drug associations for ponatinib, resulting in a total of 76 entries. This step gathered all relevant drug-disease association data without filtering.
[drug_tool]: Next, the system performed a deduplication process to remove duplicate entries within these 76 associations. After this step, only 2 unique association records remained, effectively reducing the initial set by 74 entries to ensure the data was not redundant.
[drug_tool]: In summary, the final result consists of 2 distinct disease–drug association records for ponatinib.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,abl1,CHEMBL1171837,ponatinib,bcr/abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 4 completed | rows=2 | latency=18.120s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
[drug_tool]: The system aimed to identify drug associations related to ponatinib. First, it retrieved known drug associations for ponatinib, starting with a set of 76 rows. After this initial retrieval, the system performed deduplication to remove any duplicate entries, which reduced the data set significantly from 76 to just 2 unique rows. In the end, the process resulted in 2 distinct drug association records for ponatinib.
----------------------------------------
Entries retrieved: 2

,target_id,target_name,drug_id,drug_name,mechanism_of_action,references
0,ENSG00000097007,abl1,CHEMBL1171837,ponatinib,bcr/abl fusion protein inhibitor,"DailyMed, PubMed"

 Run 5 completed | rows=2 | latency=17.807s
------------------------------------------------------------


## Question 61

**Which drugs are used for systemic lupus erythematosus?**

In [98]:

question = 'Which drugs are used for systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to systemic lupus erythematosus and associated drugs or mechanisms.
[disease_tool]: First, the system retrieved known disease–drug associations specifically for systemic lupus erythematosus, resulting in 352 entries.
[disease_tool]: Next, the system removed duplicate records from this set, reducing the total from 352 to 269 entries.
[disease_tool]: In summary, the final result contains 269 unique entries related to systemic lupus erythematosus associations.
----------------------------------------
Entries retrieved: 269

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4802159,enpatoran,MONDO_0007915,systemic lupus erythematosus,1.0,Completed,Small molecule,toll-like receptor 7 antagonist,0.7315

 Run 1 completed | rows=269 | latency=17.808s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The query aims to identify disease associations related to systemic lupus erythematosus.
[disease_tool]: First, the system retrieved the initial set of disease–drug associations for this disease, resulting in 352 rows of data. Then, to ensure the data was free of redundant information, the system performed a deduplication step. This process removed 83 duplicate rows, reducing the total to 269 unique associations.
[disease_tool]: Overall, the final dataset contains 269 distinct disease–drug associations for systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 269

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4802159,enpatoran,MONDO_0007915,systemic lupus erythematosus,1.0,Completed,Small molecule,toll-like receptor 7 antagonist,0.7315

 Run 2 completed | rows=269 | latency=16.839s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: The intent of the query was to identify drugs associated with systemic lupus erythematosus.
[disease_tool]: First, the system retrieved known disease–drug associations related to systemic lupus erythematosus. This initial retrieval resulted in 352 entries.
[disease_tool]: Next, the system performed a deduplication step to remove duplicate records, which reduced the number of entries from 352 to 269. This step ensured that only unique associations remained.
[disease_tool]: In summary, after these steps, there were a total of 269 unique records of disease–drug associations for systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 269

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4802159,enpatoran,MONDO_0007915,systemic lupus erythematosus,1.0,Completed,Small molecule,toll-like receptor 7 antagonist,0.7315

 Run 3 completed | rows=269 | latency=16.862s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: This query aims to identify information related to systemic lupus erythematosus. First, the system retrieved a set of known disease associations related to this disease, resulting in 352 rows. Next, the process removed duplicate entries from this list, reducing the number of records from 352 to 269. Overall, the final result contains 269 unique disease association records for systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 269

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4802159,enpatoran,MONDO_0007915,systemic lupus erythematosus,1.0,Completed,Small molecule,toll-like receptor 7 antagonist,0.7315

 Run 4 completed | rows=269 | latency=17.008s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
[disease_tool]: This query aims to retrieve information related to systemic lupus erythematosus and its associated drugs and mechanisms.
[disease_tool]: First, the system retrieved known disease–drug associations for systemic lupus erythematosus, resulting in 352 initial entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, reducing the number of associations from 352 to 269. This step ensured that each association was unique.
[disease_tool]: In total, the process ended with 269 unique entries related to systemic lupus erythematosus.
----------------------------------------
Entries retrieved: 269

,drug_id,drug_name,disease_id,disease_name,phase,status,drug_type,mechanism_of_action,association_score
0,CHEMBL4802159,enpatoran,MONDO_0007915,systemic lupus erythematosus,1.0,Completed,Small molecule,toll-like receptor 7 antagonist,0.7315

 Run 5 completed | rows=269 | latency=17.184s
------------------------------------------------------------


## Question 62

**Genes associated with autism spectrum disorder.**

In [99]:

question = 'Genes associated with autism spectrum disorder.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
[disease_tool]: The query was designed to find information related to autism spectrum disorder.
[disease_tool]: Firstly, the system retrieved known disease–drug associations related to autism spectrum disorder, resulting in 372 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, which reduced the number of entries from 372 to 86.
[disease_tool]: The final result after these steps is 86 unique entries associated with autism spectrum disorder.
----------------------------------------
Entries retrieved: 86

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,EFO_0003756,autism spectrum disorder,Small molecule,0.703799

 Run 1 completed | rows=86 | latency=16.167s
------------------------------------------------------------

 Starting run 2 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
[disease_tool]: The goal of this query is to find relevant disease associations related to autism spectrum disorder.
[disease_tool]: Initially, the system retrieved all known disease–drug associations for this disease, resulting in a total of 372 entries.
[disease_tool]: Next, the system applied deduplication to remove any duplicate records from this set. This process reduced the number of entries dramatically from 372 down to 86, eliminating 286 duplicate rows.
[disease_tool]: In total, the process started with 372 associations and, after filtering out duplicates, concluded with 86 unique disease association records.
----------------------------------------
Entries retrieved: 86

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,EFO_0003756,autism spectrum disorder,Small molecule,0.703799

 Run 2 completed | rows=86 | latency=15.908s
------------------------------------------------------------

 Starting run 3 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
[disease_tool]: The goal of the query was to identify information related to autism spectrum disorder.
[disease_tool]: First, the system retrieved known associations between diseases and drugs related to autism spectrum disorder. This initial retrieval resulted in 372 entries.
[disease_tool]: Next, the system performed a deduplication step to remove duplicate records, which reduced the number of entries from 372 to 86. This process eliminated redundant records to ensure the remaining data was unique and more manageable.
[disease_tool]: Overall, the final result consists of 86 distinct entries associated with autism spectrum disorder after removing duplicates.
----------------------------------------
Entries retrieved: 86

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,EFO_0003756,autism spectrum disorder,Small molecule,0.703799

 Run 3 completed | rows=86 | latency=14.947s
------------------------------------------------------------

 Starting run 4 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
[disease_tool]: This query aims to explore associations related to autism spectrum disorder.
[disease_tool]: First, the system retrieved all known disease–drug associations for autism spectrum disorder. Initially, this step gathered all related records without any filtering, resulting in an unspecified number of entries.
[disease_tool]: Next, the system performed deduplication on this set of data, which reduced the number of records from 372 down to 86. This process removed duplicate entries to ensure each association was unique.
[disease_tool]: In total, the final result included 86 unique disease–drug association entries related to autism spectrum disorder.
----------------------------------------
Entries retrieved: 86

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,EFO_0003756,autism spectrum disorder,Small molecule,0.703799

 Run 4 completed | rows=86 | latency=16.615s
------------------------------------------------------------

 Starting run 5 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
[disease_tool]: The goal of the query was to identify disease-drug associations related to autism spectrum disorder.
[disease_tool]: First, the system retrieved known disease associations for autism spectrum disorder, which initially returned 372 entries. Next, it removed duplicate records from this set, reducing the total distinct entries from 372 to 86.
[disease_tool]: In summary, the process narrowed down the data from an initial retrieval of 372 associations to a final set of 86 unique associations.
----------------------------------------
Entries retrieved: 86

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000149295,drd2,EFO_0003756,autism spectrum disorder,Small molecule,0.703799

 Run 5 completed | rows=86 | latency=16.003s
------------------------------------------------------------


## Question 63

**Diseases associated with the gene ROS1.**

In [100]:

question = 'Diseases associated with the gene ROS1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
[target_tool]: The intent of the query was to find specific associations related to the target disease or gene, specifically ROS1.
[target_tool]: The first step, association retrieval, involved collecting known disease–drug associations for ROS1. This retrieved 30 associations, forming the initial dataset for further filtering.
[target_tool]: Next, the system performed deduplication to remove redundant entries. This process reduced the number of associations from 30 down to 11 unique records, eliminating 19 duplicate entries.
[target_tool]: In total, after these steps, the refined result consisted of 11 unique associations related to ROS1.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000047936,ros1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 1 completed | rows=11 | latency=14.873s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
[target_tool]: The goal of this query was to find associations related to the target ROS1.
[target_tool]: The first step involved retrieving all known disease–drug associations for ROS1, which initially returned 30 entries.
[target_tool]: Next, the system removed duplicate records from these entries, reducing the total from 30 to 11 unique associations.
[target_tool]: In summary, after these steps, the final result included 11 distinct disease–drug associations related to ROS1.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000047936,ros1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 2 completed | rows=11 | latency=14.646s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
[target_tool]: The query aimed to identify relevant disease–drug associations related to the target ROS1.
[target_tool]: Initially, the system retrieved all known associations for ROS1, resulting in 30 entries. Next, it performed a deduplication process to eliminate duplicate records, which reduced the total from 30 entries down to 11 unique associations.
[target_tool]: In summary, after these steps, the system retained 11 distinct disease–drug associations related to ROS1.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000047936,ros1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 3 completed | rows=11 | latency=16.893s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
[target_tool]: The query aims to retrieve information related to the target ROS1, including associated drugs and pathways.
[target_tool]: Initially, the system retrieves known disease-drug associations for ROS1. This step resulted in 30 entries, which represent different disease associations linked to ROS1.
[target_tool]: Next, the system removes duplicate records from these 30 entries to ensure each association is unique. After deduplication, the number of entries is reduced from 30 to 11.
[target_tool]: In summary, the process provided a refined list of 11 unique disease associations related to ROS1 after removing duplicates from the initial 30 entries.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000047936,ros1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 4 completed | rows=11 | latency=16.990s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
[target_tool]: The query aims to identify relevant associations related to the target "ROS1."
[target_tool]: First, the system retrieved a set of known disease–drug associations for ROS1. This initial step resulted in 30 entries. Next, the system performed a deduplication process to remove any duplicate records from this set. After removing duplicates, the number of associations was reduced from 30 to 11.
[target_tool]: In summary, after these steps, 11 unique disease–drug associations related to ROS1 remained.
----------------------------------------
Entries retrieved: 11

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000047936,ros1,EFO_0003060,non-small cell lung carcinoma,0.661713

 Run 5 completed | rows=11 | latency=17.847s
------------------------------------------------------------


## Question 64

**Diseases associated with the gene ALK.**

In [101]:

question = 'Diseases associated with the gene ALK.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ALK.
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target "ALK." Firstly, the system retrieved known disease–drug associations relevant to this target, resulting in a total of 207 entries. Next, it removed duplicate records from this set to ensure unique data. After deduplication, the number of entries was reduced to 61. Overall, the process narrowed down the initial associations to a set of 61 unique entries related to "ALK."
----------------------------------------
Entries retrieved: 61

         target_id target_name   disease_id   disease_name  association_score
0  ENSG00000171094         alk  EFO_0000621  neuroblastoma           0.807305

 Run 1 completed | rows=61 | latency=18.614s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ALK.
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target ALK. The process began with the retrieval of known disease–drug associations for ALK, which initially yielded 207 entries. Then, to ensure unique results, duplicate records were removed, reducing the total from 207 to 61 entries. Overall, the final result contains 61 unique entries linked to ALK.
----------------------------------------
Entries retrieved: 61

         target_id target_name   disease_id   disease_name  association_score
0  ENSG00000171094         alk  EFO_0000621  neuroblastoma           0.807305

 Run 2 completed | rows=61 | latency=19.491s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ALK.
  Attempt 1/3
[target_tool]: The query aimed to find information related to the target ALK. The first step involved retrieving known disease–drug associations for ALK, which initially resulted in 207 entries. Next, the system removed duplicate records from this set, reducing the number of entries from 207 to 61. Overall, the process refined the dataset to 61 unique associations related to ALK.
----------------------------------------
Entries retrieved: 61

         target_id target_name   disease_id   disease_name  association_score
0  ENSG00000171094         alk  EFO_0000621  neuroblastoma           0.807305

 Run 3 completed | rows=61 | latency=14.520s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ALK.
  Attempt 1/3
[target_tool]: The query aimed to find disease–drug associations related to the target "ALK".
[target_tool]: First, the system retrieved known disease–drug associations for ALK, resulting in a total of 207 entries.
[target_tool]: Next, to ensure the result set contained only unique records, the system removed duplicate rows. This deduplication process reduced the number of entries from 207 to 61, leaving 61 unique disease–drug association entries related to ALK.
[target_tool]: In the end, the process provided a refined list of 61 unique associations involving ALK.
----------------------------------------
Entries retrieved: 61

         target_id target_name   disease_id   disease_name  association_score
0  ENSG00000171094         alk  EFO_0000621  neuroblastoma           0.807305

 Run 4 completed | rows=61 | latency=15.344s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ALK.
  Attempt 1/3
[target_tool]: The query aimed to identify disease and drug associations related to the target ALK.
[target_tool]: First, the system retrieved known disease–drug associations for ALK, which resulted in 207 associations.
[target_tool]: Next, the system removed duplicate records, reducing the total from 207 to 61 unique associations.
[target_tool]: In summary, after filtering for uniqueness, the number of relevant disease–drug associations for ALK was 61.
----------------------------------------
Entries retrieved: 61

         target_id target_name   disease_id   disease_name  association_score
0  ENSG00000171094         alk  EFO_0000621  neuroblastoma           0.807305

 Run 5 completed | rows=61 | latency=15.754s
------------------------------------------------------------


## Question 65

**Diseases associated with the gene EGFR.**

In [102]:

question = 'Diseases associated with the gene EGFR.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
[target_tool]: The query aimed to identify relevant drug associations for the target EGFR.
[target_tool]: First, the system retrieved known disease–drug associations related to EGFR, resulting in a total of 1,870 entries.
[target_tool]: Next, it performed deduplication to remove any duplicate records within this set, reducing the number from 1,870 down to 219 unique entries.
[target_tool]: In the end, the final number of associations remaining after deduplication is 219.
----------------------------------------
Entries retrieved: 219

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000146648,egfr,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 1 completed | rows=219 | latency=16.627s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target EGFR.
[target_tool]: Initially, the system retrieved known disease–drug associations for EGFR, resulting in 1870 entries. This step set the foundation for further filtering and refinement.
[target_tool]: Next, the system performed deduplication to remove duplicate records. This process reduced the number of entries from 1870 to 219, removing 1651 duplicate rows to leave a set of unique associations.
[target_tool]: In summary, after these steps, the system had a refined set of 219 unique disease–drug associations related to EGFR.
----------------------------------------
Entries retrieved: 219

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000146648,egfr,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 2 completed | rows=219 | latency=14.154s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
[target_tool]: The query aimed to find information related to the target "EGFR" and its associations.
[target_tool]: First, the system retrieved all known associations related to "EGFR," which resulted in 1,870 entries. This step gathered a broad set of data points linking "EGFR" to various entities.
[target_tool]: Next, the system performed deduplication to remove duplicate records from this set. This process reduced the number of entries from 1,870 down to 219, eliminating 1,651 repeated entries and leaving a cleaner, more unique dataset.
[target_tool]: In total, the final result after these steps contained 219 unique associations related to "EGFR."
----------------------------------------
Entries retrieved: 219

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000146648,egfr,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 3 completed | rows=219 | latency=14.853s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
[target_tool]: The query aimed to explore known associations related to the target EGFR.
[target_tool]: First, the system retrieved all the known disease–drug associations for EGFR, which resulted in 1,870 entries. This step gathered a broad set of data related to the target.
[target_tool]: Next, the system performed deduplication to remove duplicate records from this dataset. This process reduced the total from 1,870 entries to 219 unique associations, eliminating 1,651 duplicates and ensuring the data was more accurate and manageable.
[target_tool]: In summary, after these steps, the final dataset consisted of 219 unique associations related to EGFR.
----------------------------------------
Entries retrieved: 219

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000146648,egfr,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 4 completed | rows=219 | latency=16.211s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
[target_tool]: The user's query aimed to identify associations related to the target "EGFR." The process began with the retrieval of known disease-drug associations for EGFR. At this stage, a total of 1,870 entries were fetched. Next, the data underwent a deduplication process to remove duplicate records, which reduced the number of entries from 1,870 to 219. In summary, the final result consists of 219 unique associations related to EGFR after removing duplicates.
----------------------------------------
Entries retrieved: 219

,target_id,target_name,disease_id,disease_name,association_score
0,ENSG00000146648,egfr,EFO_0003060,non-small cell lung carcinoma,0.84951

 Run 5 completed | rows=219 | latency=16.594s
------------------------------------------------------------


## Question 66

**Provide target names for psoriasis.**

In [103]:

question = 'Provide target names for psoriasis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for psoriasis.
  Attempt 1/3
[disease_tool]: The query aimed to explore disease-drug associations related to psoriasis. First, the system retrieved known disease associations for psoriasis, resulting in 872 records. Next, it performed de-duplication to remove duplicate entries, reducing the number of records from 872 to 221. The final result includes 221 unique records related to psoriasis.
----------------------------------------
Entries retrieved: 221

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113302,il12b,EFO_0000676,psoriasis,Antibody,0.776649

 Run 1 completed | rows=221 | latency=19.832s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for psoriasis.
  Attempt 1/3
[disease_tool]: The query appears to aim at identifying information related to psoriasis, focusing on disease and drug associations.
[disease_tool]: Initially, the system retrieved known disease–drug associations related to psoriasis, resulting in a total of 872 entries.
[disease_tool]: Next, the system removed duplicate records from this dataset, reducing the number of entries from 872 to 221. This step eliminated redundant data to ensure that only unique disease–drug associations remained.
[disease_tool]: In summary, after retrieving the initial association data and removing duplicates, the final dataset contains 221 unique entries related to psoriasis.
----------------------------------------
Entries retrieved: 221

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113302,il12b,EFO_0000676,psoriasis,Antibody,0.776649

 Run 2 completed | rows=221 | latency=17.663s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for psoriasis.
  Attempt 1/3
[disease_tool]: The query aims to identify disease–drug associations for psoriasis. The first step retrieved known associations related to psoriasis, resulting in a collection of 872 records. To ensure data quality, duplicate entries were then removed, reducing the number of records from 872 to 221. This final set of 221 unique entries represents the refined data related to psoriasis associations.
----------------------------------------
Entries retrieved: 221

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113302,il12b,EFO_0000676,psoriasis,Antibody,0.776649

 Run 3 completed | rows=221 | latency=16.546s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for psoriasis.
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to psoriasis.
[disease_tool]: Initially, the system retrieved a set of 872 known disease associations for psoriasis. This step gathered all potentially relevant disease links before filtering.
[disease_tool]: Next, the system performed deduplication to remove duplicate records from this set. This process reduced the number of entries from 872 to 221, ensuring that each disease association was unique.
[disease_tool]: In summary, after these steps, the final result consisted of 221 distinct disease associations related to psoriasis.
----------------------------------------
Entries retrieved: 221

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113302,il12b,EFO_0000676,psoriasis,Antibody,0.776649

 Run 4 completed | rows=221 | latency=18.212s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for psoriasis.
  Attempt 1/3
[disease_tool]: The query aimed to identify disease-drug associations related to psoriasis. First, the system retrieved known disease associations for psoriasis, resulting in 872 records. Next, to eliminate redundant information, it removed duplicate entries, reducing the number of records from 872 to 221. In the end, the process yielded 221 unique disease association records related to psoriasis.
----------------------------------------
Entries retrieved: 221

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113302,il12b,EFO_0000676,psoriasis,Antibody,0.776649

 Run 5 completed | rows=221 | latency=20.375s
------------------------------------------------------------


## Question 67

**Provide target names for ulcerative colitis.**

In [104]:

question = 'Provide target names for ulcerative colitis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
[disease_tool]: The query aimed to identify information related to ulcerative colitis by retrieving related disease associations.
[disease_tool]: Initially, the system retrieved all known disease–drug associations for ulcerative colitis, resulting in 523 entries. This step collected a broad set of relationships relevant to the disease.
[disease_tool]: Next, the system removed duplicate records from this set of associations. This deduplication process reduced the total number of entries from 523 down to 173, eliminating 350 duplicate rows to focus on unique associations.
[disease_tool]: In summary, after retrieving all initial associations and removing duplicates, the final dataset contained 173 unique disease–drug associations related to ulcerative colitis.
----------------------------------------
Entries retrieved: 173

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000232810,tnf,EFO_0000729,ulcerative colitis,Antibody,0.637689

 Run 1 completed | rows=173 | latency=18.054s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
[disease_tool]: The goal of the query was to retrieve associations between a specific disease and relevant drugs or mechanisms.
[disease_tool]: First, the system retrieved known disease–drug associations related to ulcerative colitis, which initially resulted in 523 entries.
[disease_tool]: Next, to ensure the data was unique and free of duplicates, the system performed a deduplication process. This process reduced the number of entries from 523 to 173 by removing duplicate rows, leaving a streamlined set of unique disease association data.
[disease_tool]: In summary, after these steps, the result set consisted of 173 unique disease association entries related to ulcerative colitis.
----------------------------------------
Entries retrieved: 173

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000232810,tnf,EFO_0000729,ulcerative colitis,Antibody,0.637689

 Run 2 completed | rows=173 | latency=18.786s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
[disease_tool]: The query was designed to find disease-related information, specifically related to ulcerative colitis. The process began with retrieving known disease–drug associations for ulcerative colitis. After this initial retrieval, there were 523 entries.
[disease_tool]: Next, deduplication was performed to remove duplicate entries from the data set. This step reduced the number of entries from 523 to 173, effectively eliminating 350 duplicate rows. The final result set contains 173 unique disease association records related to ulcerative colitis.
----------------------------------------
Entries retrieved: 173

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000232810,tnf,EFO_0000729,ulcerative colitis,Antibody,0.637689

 Run 3 completed | rows=173 | latency=17.559s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
[disease_tool]: The purpose of the query was to find information related to ulcerative colitis and its associated drugs or mechanisms.
[disease_tool]: First, the system retrieved the known disease–drug associations for ulcerative colitis. This step resulted in 523 entries being selected for further analysis.
[disease_tool]: Next, duplicate entries within these associations were removed to ensure each record was unique. This deduplication step reduced the number of entries from 523 down to 173, eliminating redundancies and leaving a set of 173 unique associations.
[disease_tool]: In summary, the final result after applying these steps is 173 distinct disease–drug associations related to ulcerative colitis.
----------------------------------------
Entries retrieved: 173

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000232810,tnf,EFO_0000729,ulcerative colitis,Antibody,0.637689

 Run 4 completed | rows=173 | latency=20.929s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
[disease_tool]: The goal of the query was to find specific associations related to ulcerative colitis.
[disease_tool]: Initially, the system retrieved disease–drug associations related to ulcerative colitis. After this step, there were 523 entries.
[disease_tool]: Next, the system performed deduplication to remove duplicate records, which reduced the total from 523 to 173.
[disease_tool]: In summary, after this sequence of steps, the procedure resulted in 173 unique records associated with ulcerative colitis.
----------------------------------------
Entries retrieved: 173

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000232810,tnf,EFO_0000729,ulcerative colitis,Antibody,0.637689

 Run 5 completed | rows=173 | latency=16.595s
------------------------------------------------------------


## Question 68

**Provide target names for tuberculosis.**

In [105]:

question = 'Provide target names for tuberculosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for tuberculosis.
  Attempt 1/3
[disease_tool]: The intent of the query was to retrieve disease associations related to tuberculosis.
[disease_tool]: Initially, the system retrieved known associations for tuberculosis, resulting in a total of 161 entries.
[disease_tool]: Next, a deduplication step was performed to eliminate duplicate records, reducing the number of entries from 161 to 92.
[disease_tool]: The final result included 92 unique disease associations related to tuberculosis.
----------------------------------------
Entries retrieved: 92

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0018076,tuberculosis,Small molecule,0.590371

 Run 1 completed | rows=92 | latency=16.742s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for tuberculosis.
  Attempt 1/3
[disease_tool]: The query aimed to identify information related to tuberculosis.
[disease_tool]: First, the system retrieved known disease–drug associations related to tuberculosis, which resulted in a total of 161 records.
[disease_tool]: Next, the system removed duplicate records from this set to ensure each association was unique, reducing the total from 161 to 92.
[disease_tool]: In summary, the final result contains 92 distinct disease–drug associations related to tuberculosis.
----------------------------------------
Entries retrieved: 92

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0018076,tuberculosis,Small molecule,0.590371

 Run 2 completed | rows=92 | latency=16.576s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for tuberculosis.
  Attempt 1/3
[disease_tool]: The user's query aimed to explore associations related to tuberculosis. The process began with the retrieval of known disease–drug associations specifically for tuberculosis, resulting in 161 entries. Next, duplicate entries were removed from this dataset, reducing the number of results from 161 to 92. This step helped eliminate redundant data, leaving a cleaned set of 92 unique associations. In summary, the final result contains 92 unique disease–drug associations related to tuberculosis.
----------------------------------------
Entries retrieved: 92

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0018076,tuberculosis,Small molecule,0.590371

 Run 3 completed | rows=92 | latency=15.237s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for tuberculosis.
  Attempt 1/3
[disease_tool]: The query aimed to find information related to tuberculosis, starting with retrieving known disease–drug associations for this disease. Initially, the system retrieved 161 rows of data related to disease associations. Next, to ensure the data was unique, it performed deduplication, which removed duplicate rows. After this process, the data was reduced from 161 to 92 unique entries. The final result includes 92 distinct entries associated with tuberculosis.
----------------------------------------
Entries retrieved: 92

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0018076,tuberculosis,Small molecule,0.590371

 Run 4 completed | rows=92 | latency=16.215s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for tuberculosis.
  Attempt 1/3
[disease_tool]: This query aims to find disease–drug associations related to tuberculosis. The first step involved retrieving known disease associations for tuberculosis, which initially resulted in 161 entries. This means the system identified all known relationships involving this disease.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, reducing the number of records from 161 to 92. This step ensured that each association was unique, eliminating redundancy and clarifying the dataset.
[disease_tool]: In total, the process refined the initial list to 92 unique disease–drug association records related to tuberculosis.
----------------------------------------
Entries retrieved: 92

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000113580,nr3c1,MONDO_0018076,tuberculosis,Small molecule,0.590371

 Run 5 completed | rows=92 | latency=19.748s
------------------------------------------------------------


## Question 69

**Provide target names for hepatitis C.**

In [106]:

question = 'Provide target names for hepatitis C.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for hepatitis C.
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to hepatitis C. Initially, the system retrieved a set of known disease–drug associations related to hepatitis C. This step produced 452 rows of data. Next, the system performed a deduplication process to remove any duplicate records from the dataset. Following this deduplication, the number of rows was reduced from 452 to 110, resulting in a refined set of unique associations related to hepatitis C.
----------------------------------------
Entries retrieved: 110

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142166,ifnar1,EFO_0003047,hepatitis c virus infection,Unknown,0.613074

 Run 1 completed | rows=110 | latency=15.964s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for hepatitis C.
  Attempt 1/3
[disease_tool]: The query aims to identify disease-drug associations related to hepatitis C. First, the system retrieved known disease associations for hepatitis C, resulting in 452 entries. Next, to remove any duplicate records, the system applied deduplication, which reduced the number of entries from 452 to 110. In summary, the final result contains 110 unique associations related to hepatitis C.
----------------------------------------
Entries retrieved: 110

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142166,ifnar1,EFO_0003047,hepatitis c virus infection,Unknown,0.613074

 Run 2 completed | rows=110 | latency=16.229s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for hepatitis C.
  Attempt 1/3
[disease_tool]: The query aims to identify data related to hepatitis C.
[disease_tool]: Initially, the system retrieved known disease–drug associations for hepatitis C. This step resulted in a set of 452 entries.
[disease_tool]: Next, the system performed a deduplication process, which removed duplicate records from the retrieved data. After this step, the number of entries was reduced from 452 to 110, leaving only unique associations.
[disease_tool]: In summary, the final result consists of 110 unique disease–drug association records related to hepatitis C.
----------------------------------------
Entries retrieved: 110

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142166,ifnar1,EFO_0003047,hepatitis c virus infection,Unknown,0.613074

 Run 3 completed | rows=110 | latency=17.714s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for hepatitis C.
  Attempt 1/3
[disease_tool]: The query aimed to identify specific disease-associated data related to hepatitis C. First, the system retrieved known disease–drug associations related to hepatitis C, resulting in a total of 452 entries initially. Next, to improve data quality, duplicate records were removed, which reduced the number of entries from 452 to 110. In summary, the final dataset contains 110 unique entries related to hepatitis C.
----------------------------------------
Entries retrieved: 110

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142166,ifnar1,EFO_0003047,hepatitis c virus infection,Unknown,0.613074

 Run 4 completed | rows=110 | latency=15.154s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for hepatitis C.
  Attempt 1/3
[disease_tool]: The query is designed to find information related to hepatitis C. The process begins with retrieving all known disease–drug associations for hepatitis C, which resulted in 452 entries. Next, any duplicate records within this set were removed, reducing the total number of entries from 452 to 110. This final count reflects the unique associations related to hepatitis C after removing duplicates.
----------------------------------------
Entries retrieved: 110

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000142166,ifnar1,EFO_0003047,hepatitis c virus infection,Unknown,0.613074

 Run 5 completed | rows=110 | latency=15.606s
------------------------------------------------------------


## Question 70

**Provide target names for Hodgkin lymphoma.**

In [107]:

question = 'Provide target names for Hodgkin lymphoma.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
[disease_tool]: The query aimed to identify relevant drug associations related to Hodgkin lymphoma. First, the system retrieved known disease–drug associations for Hodgkin lymphoma, resulting in 1,821 entries. Next, to ensure the data was unique, the system removed duplicate rows, reducing the number of entries from 1,821 to 151. In total, the final result set contains 151 unique entries related to Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 151

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000188389,pdcd1,EFO_0000183,hodgkins lymphoma,Antibody,0.596561

 Run 1 completed | rows=151 | latency=15.595s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
[disease_tool]: The purpose of the query was to find information related to Hodgkin lymphoma. The process began with retrieving known disease–drug associations for Hodgkin lymphoma, which initially resulted in 1,821 entries. To improve the quality of the results, duplicate records were then removed, reducing the total from 1,821 to 151 entries. Therefore, the final set of data consisted of 151 unique association records related to Hodgkin lymphoma.
----------------------------------------
 Attempt 1 failed after 30.003s: OpenTargets query exceeded 30.0 seconds
  Attempt 2/3
[disease_tool]: The goal of the query was to retrieve relevant disease–drug associations for Hodgkin lymphoma.
[disease_tool]: First, the system retrieved the base data of known disease associations related to Hodgkin lymphoma, which initially included 1,821 entries.
[disease_tool]: Next, the system performed a deduplication process to eliminate duplicate records, reducing the total from 1,821 to 151 entries. This step ensured that only unique associations remained, removing 1,670 duplicates in the process.
[disease_tool]: In summary, after filtering and removing duplicates, the final result consists of 151 unique disease–drug association entries related to Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 151

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000188389,pdcd1,EFO_0000183,hodgkins lymphoma,Antibody,0.596561

 Run 2 completed | rows=151 | latency=16.479s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
[disease_tool]: This query was designed to explore information related to Hodgkin lymphoma, specifically focusing on disease associations.
[disease_tool]: First, the system retrieved known disease associations for Hodgkin lymphoma, resulting in 1,821 entries. This initial step collected all potential related data without any filtering.
[disease_tool]: Next, the system performed deduplication to remove duplicate entries, which reduced the number of records from 1,821 to 151. This step ensured that each association was unique, eliminating 1,670 duplicate rows from the dataset.
[disease_tool]: In summary, the final dataset contains 151 unique disease association records related to Hodgkin lymphoma after filtering out duplicates.
----------------------------------------
Entries retrieved: 151

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000188389,pdcd1,EFO_0000183,hodgkins lymphoma,Antibody,0.596561

 Run 3 completed | rows=151 | latency=14.785s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
[disease_tool]: The query aimed to retrieve information related to Hodgkin lymphoma. First, the system retrieved known disease–drug associations for Hodgkin lymphoma, resulting in a total of 1,821 entries. Next, the data was processed to remove duplicate rows, reducing the number of entries from 1,821 to 151. In conclusion, the final result after filtering for unique associations contains 151 entries.
----------------------------------------
Entries retrieved: 151

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000188389,pdcd1,EFO_0000183,hodgkins lymphoma,Antibody,0.596561

 Run 4 completed | rows=151 | latency=16.112s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
[disease_tool]: The query aims to identify disease associations related to Hodgkin lymphoma. Initially, the system retrieved a set of known disease–drug associations for this disease, resulting in 1,821 entries.
[disease_tool]: Next, the system performed a deduplication step to remove redundant records. This process reduced the number of entries from 1,821 to 151 by eliminating duplicate rows.
[disease_tool]: In summary, after these steps, the process concluded with 151 unique associations related to Hodgkin lymphoma.
----------------------------------------
Entries retrieved: 151

,target_id,target_name,disease_id,disease_name,drug_type,association_score
0,ENSG00000188389,pdcd1,EFO_0000183,hodgkins lymphoma,Antibody,0.596561

 Run 5 completed | rows=151 | latency=18.934s
------------------------------------------------------------


## Question 71

**Which pathways are associated with the TP53?**

In [108]:

question = 'Which pathways are associated with the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TP53?
  Attempt 1/3
[target_tool]: The goal of the query was to find pathway information related to the target TP53. Initially, the system retrieved pathway data for this specific target. This retrieval resulted in a total of 45 pathways associated with TP53. Since no previous number of rows was recorded before this retrieval, the focus is on the pathway data obtained. In the end, the pathway retrieval provided 45 pathways linked to TP53, which would be used in further analysis or filtering steps.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 1 completed | rows=45 | latency=14.692s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TP53?
  Attempt 1/3
[target_tool]: The intent of the query was to find relevant pathways associated with the target gene TP53.
[target_tool]: The first step involved retrieving pathways related to TP53, which resulted in a total of 45 pathways being identified. There were no previous rows to compare with, as this was the initial retrieval step.
[target_tool]: In summary, the pathway retrieval step provided 45 pathways connected to TP53, forming the basis for further filtering or analysis.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 2 completed | rows=45 | latency=14.609s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TP53?
  Attempt 1/3
[target_tool]: The query aims to retrieve information related to pathways associated with the target gene TP53.
[target_tool]: The first step involved retrieving pathways related to TP53. Before this step, there were no pathway records considered, and after the retrieval, a total of 45 pathway entries were found. This step provided the pathway information for further analysis but did not apply any filters or reductions beyond the initial retrieval.
[target_tool]: Overall, the process resulted in 45 pathway entries associated with TP53.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 3 completed | rows=45 | latency=14.515s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TP53?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target TP53. The first step involved retrieving known biological pathways associated with TP53, resulting in 45 pathway entries being identified. This step provided a pathway-based context for understanding the target's role in biological processes. Since there are no prior steps listed, the overall result after pathway retrieval remains at 45 entries related to the pathways involving TP53.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 4 completed | rows=45 | latency=13.884s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TP53?
  Attempt 1/3
[target_tool]: The query aims to identify pathways associated with the target, TP53. The process begins with retrieving pathway information related to TP53, which resulted in 45 pathways being identified. Since there were no previous step results to compare, it is only noted that pathway data was retrieved for TP53. In the end, the system provided information on 45 pathways associated with the target.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 5 completed | rows=45 | latency=15.969s
------------------------------------------------------------


## Question 72

**Which drugs are associated with the ERBB2?**

In [109]:

question = 'Which drugs are associated with the ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
[target_tool]: The query aimed to find specific information related to the target ERBB2. The first step involved retrieving known disease-drug associations for ERBB2, resulting in a total of 1,048 records. Next, the data underwent deduplication to eliminate duplicate entries, reducing the number of records from 1,048 to 299. In the end, the process produced a refined set of 299 unique records related to ERBB2.
----------------------------------------
Entries retrieved: 299

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,erbb2,CHEMBL1201585,trastuzumab,4.0,NaN,NaN,receptor protein-tyrosine kinase erbb-2 inhibitor

 Run 1 completed | rows=299 | latency=15.269s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
[target_tool]: This query aims to retrieve information related to the target ERBB2. Initially, the system retrieved the base associations for ERBB2, resulting in 1,048 entries. Next, it performed a deduplication step, removing duplicate records. This process reduced the total number of entries from 1,048 to 299. The final result consists of 299 unique associations related to ERBB2.
----------------------------------------
Entries retrieved: 299

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,erbb2,CHEMBL1201585,trastuzumab,4.0,NaN,NaN,receptor protein-tyrosine kinase erbb-2 inhibitor

 Run 2 completed | rows=299 | latency=16.278s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
[target_tool]: The query aimed to find specific associations related to the target ERBB2. First, the system retrieved a set of 1,048 known disease–drug associations linked to ERBB2. Next, it removed duplicate records from this set, reducing the number of associations from 1,048 to 299. In conclusion, the final result included 299 unique associations related to ERBB2.
----------------------------------------
Entries retrieved: 299

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,erbb2,CHEMBL1201585,trastuzumab,4.0,NaN,NaN,receptor protein-tyrosine kinase erbb-2 inhibitor

 Run 3 completed | rows=299 | latency=15.384s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
[target_tool]: The goal of the query was to find complex associations related to the target ERBB2. First, the system retrieved known disease-drug associations for ERBB2, resulting in a set of 1,048 records. Next, the system removed duplicate entries from this set, which reduced the number of results from 1,048 to 299. In total, the process narrowed down the initial association data to a more concise set of 299 unique records.
----------------------------------------
Entries retrieved: 299

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,erbb2,CHEMBL1201585,trastuzumab,4.0,NaN,NaN,receptor protein-tyrosine kinase erbb-2 inhibitor

 Run 4 completed | rows=299 | latency=16.491s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target ERBB2.
[target_tool]: First, the system retrieved known disease–drug associations for ERBB2, which resulted in 1,048 entries. This was the initial dataset generated based on existing association data.
[target_tool]: Next, the system removed duplicate records from this dataset to produce a cleaner set of unique association entries. This deduplication process reduced the total from 1,048 entries down to 299 entries, removing 749 duplicate rows.
[target_tool]: In summary, after retrieving and filtering the data, the final set contained 299 unique associations related to ERBB2.
----------------------------------------
Entries retrieved: 299

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000141736,erbb2,CHEMBL1201585,trastuzumab,4.0,NaN,NaN,receptor protein-tyrosine kinase erbb-2 inhibitor

 Run 5 completed | rows=299 | latency=20.672s
------------------------------------------------------------


## Question 73

**Which pathways are associated with the ADRB1 gene?**

In [110]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to pathways associated with the target ADRB1.
[target_tool]: The first step in processing was pathway retrieval, where the system fetched pathways linked to ADRB1. This step resulted in identifying 2 pathways related to the target, although the initial number of pathways found before retrieval is not provided.
[target_tool]: In summary, the system successfully retrieved 2 pathways associated with ADRB1, providing a foundation for further analysis or filtering.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 1 completed | rows=2 | latency=14.111s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve pathways associated with the target ADRB1.
[target_tool]: First, the system retrieved pathway information related to ADRB1. This step resulted in 2 pathways being identified.
[target_tool]: Since there was only one significant step recorded, the process involved retrieving pathway data, and no additional filters or deduplication steps are shown.
[target_tool]: In the end, the system provided information about 2 pathways related to ADRB1.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 2 completed | rows=2 | latency=14.127s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve pathways related to the target ADRB1.
[target_tool]: First, the system retrieved pathway information associated with the target ADRB1. This step involved gathering relevant pathways, which initially resulted in a certain number of entries, though the exact number before retrieval is not specified.
[target_tool]: Since only pathway retrieval is shown in the log, it indicates the pathways for ADRB1 were obtained without further filtering. This step resulted in 2 pathways being associated with the target.
[target_tool]: In summary, the final result consists of 2 pathways linked to ADRB1.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 3 completed | rows=2 | latency=14.643s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target ADRB1. In this step, the system retrieved pathway data for ADRB1, ending up with 2 pathways. Since no prior pathway data was noted, the total pathways obtained was 2. The final result reflects these pathways associated with the target ADRB1.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 4 completed | rows=2 | latency=12.847s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target ADRB1. In this step, the system retrieved pathways associated with ADRB1, ending up with 2 pathways. There is no previous number of pathways given, but after this step, 2 pathways were identified for further analysis.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,ADRB1,ENSG00000043591,R-HSA-418555,G alpha (s) signalling events,Signal Transduction

 Run 5 completed | rows=2 | latency=13.542s
------------------------------------------------------------


## Question 74

**Which pathways are associated with the DRD2 gene?**

In [111]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target DRD2 and its associated pathways. The first step in the process was pathway retrieval, where the system fetched pathway data linked to DRD2. This step resulted in one pathway being retrieved, with no initial number of pathways specified before the retrieval. Overall, the final result includes information on one pathway associated with DRD2.
----------------------------------------
Entries retrieved: 1

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 1 completed | rows=1 | latency=14.198s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify pathways associated with the target gene DRD2. First, the system retrieved pathway information related to this target, which resulted in one pathway being identified. Since only a single pathway was found, the pathway retrieval step did not further narrow down the results. The process concluded with one pathway linked to DRD2.
----------------------------------------
Entries retrieved: 1

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 2 completed | rows=1 | latency=16.009s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aims to retrieve information related to the target, which in this case is the DRD2 gene or protein.
[target_tool]: Firstly, the system retrieved pathway information associated with DRD2, resulting in a total of 1 pathway after the retrieval process. Since no prior result count was specified, this was a straightforward step that brought back pathway data linked to DRD2.
[target_tool]: There were no additional filtering or deduplication steps shown in this log, so this was primarily a pathway retrieval action.
[target_tool]: In conclusion, the process ended with a single pathway related to DRD2 being obtained.
----------------------------------------
Entries retrieved: 1

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 3 completed | rows=1 | latency=13.632s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aimed to find pathways related to the drug target DRD2. The process began with retrieving relevant pathway information specific to this target. This step resulted in obtaining one pathway entry, although the total number of pathways initially retrieved is not specified. The pathway retrieval provided a pathway linked to DRD2, but no further reduction or filtering steps are detailed after this. In the end, the process identified one pathway associated with the target DRD2.
----------------------------------------
Entries retrieved: 1

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 4 completed | rows=1 | latency=14.532s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
[target_tool]: The query aimed to find pathways related to the target DRD2. The system first retrieved pathway information associated with DRD2. After this step, one pathway was identified. This indicates that the pathway retrieval process resulted in a single relevant pathway for DRD2.
----------------------------------------
Entries retrieved: 1

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,DRD2,ENSG00000149295,R-HSA-390651,Dopamine receptors,Signal Transduction

 Run 5 completed | rows=1 | latency=13.797s
------------------------------------------------------------


## Question 75

**Which pathways are associated with the HTR2A gene?**

In [112]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve pathway information related to the target HTR2A.
[target_tool]: First, the system retrieved pathways associated with HTR2A, resulting in two pathways being identified. This step provided the pathway details connected to the target.
[target_tool]: Since pathway retrieval was the only step recorded, the process concluded with two pathways linked to HTR2A.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 1 completed | rows=2 | latency=13.968s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target HTR2A to understand its pathways. First, the system retrieved pathways associated with HTR2A. Initially, there was no specified number of pathways before retrieval, but after the retrieval, 2 pathways were identified for this target. In summary, the process resulted in finding 2 pathways linked to HTR2A.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 2 completed | rows=2 | latency=14.922s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aimed to explore biological pathways related to the target HTR2A.
[target_tool]: First, the system retrieved pathways associated with HTR2A, resulting in two entries. This step involved accessing pathway information linked to the target gene or protein but did not reduce or filter the results further.
[target_tool]: Since only pathway retrieval was performed, no subsequent filtering or deduplication steps are shown in the log.
[target_tool]: In summary, the final result included two pathways associated with HTR2A.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 3 completed | rows=2 | latency=18.064s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the target HTR2A.
[target_tool]: First, the system retrieved pathway information associated with HTR2A, resulting in a total of two pathways. This step involved gathering all relevant pathway data linked to the target without prior filtering or reduction.
[target_tool]: Since this execution log only details the pathway retrieval step, the process concludes with the identification of these two pathways. Overall, the final result includes information on two pathways related to HTR2A.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 4 completed | rows=2 | latency=14.694s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
[target_tool]: The intent of the query was to retrieve pathway information related to the target HTR2A.
[target_tool]: The first step involved pathway retrieval, where the system gathered relevant biological pathways associated with HTR2A. This step did not specify the number of pathways retrieved before, but it resulted in acquiring 2 pathway entries related to this target.
[target_tool]: Since only this step is provided in the log, the process concluded with the retrieval of 2 pathways.
----------------------------------------
Entries retrieved: 2

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,HTR2A,ENSG00000102468,R-HSA-416476,G alpha (q) signalling events,Signal Transduction

 Run 5 completed | rows=2 | latency=15.538s
------------------------------------------------------------


## Question 76

**Which drugs are associated with the CD19 gene?**

In [113]:

question = 'Which drugs are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aims to find associations related to the target CD19.
[target_tool]: First, the system retrieved known disease–drug associations associated with CD19, which resulted in 248 entries.
[target_tool]: Next, it performed a deduplication process to remove duplicate records, reducing the number of entries from 248 down to 112.
[target_tool]: In total, the process ended with 112 unique association records for CD19.
----------------------------------------
Entries retrieved: 112

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,cd19,CHEMBL3301574,tisagenlecleucel,4.0,NaN,NaN,b-lymphocyte antigen cd19 binding agent

 Run 1 completed | rows=112 | latency=15.017s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify associations relevant to the target CD19. Initially, the system retrieved a set of 248 known disease-drug associations related to CD19. Next, it removed duplicate entries among these associations to refine the data; this process reduced the total from 248 to 112 unique records. In the end, the process resulted in 112 distinct disease-drug association entries for CD19.
----------------------------------------
Entries retrieved: 112

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,cd19,CHEMBL3301574,tisagenlecleucel,4.0,NaN,NaN,b-lymphocyte antigen cd19 binding agent

 Run 2 completed | rows=112 | latency=28.362s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify relevant drugs and mechanisms associated with the target CD19.
[target_tool]: Initially, the system retrieved a set of 248 known disease–drug associations related to CD19. This step gathered all the initial data before filtering. Next, the system performed a deduplication process to remove duplicate records from this set. After this process, the total number of associations was reduced from 248 to 112, meaning 136 duplicate entries were eliminated.
[target_tool]: In summary, the process resulted in 112 unique associations related to CD19 after filtering and deduplication.
----------------------------------------
Entries retrieved: 112

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,cd19,CHEMBL3301574,tisagenlecleucel,4.0,NaN,NaN,b-lymphocyte antigen cd19 binding agent

 Run 3 completed | rows=112 | latency=19.093s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The system aimed to identify associations related to the target CD19. First, it retrieved a set of known disease–drug associations for CD19, resulting in a list of 248 entries. Next, it performed deduplication to eliminate duplicate records from this list, reducing the total from 248 to 112 unique entries. Overall, the final result comprised 112 distinct disease–drug association records for CD19.
----------------------------------------
Entries retrieved: 112

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,cd19,CHEMBL3301574,tisagenlecleucel,4.0,NaN,NaN,b-lymphocyte antigen cd19 binding agent

 Run 4 completed | rows=112 | latency=14.516s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
[target_tool]: The intent of the query was to identify relevant associations for the target CD19.
[target_tool]: Initially, the system retrieved known disease–drug associations related to CD19, resulting in a total of 248 entries.
[target_tool]: Following this, the system performed a deduplication step to remove duplicate records. This process reduced the total number of entries from 248 to 112, eliminating 136 duplicate rows.
[target_tool]: In the end, there are 112 unique association records related to CD19.
----------------------------------------
Entries retrieved: 112

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000177455,cd19,CHEMBL3301574,tisagenlecleucel,4.0,NaN,NaN,b-lymphocyte antigen cd19 binding agent

 Run 5 completed | rows=112 | latency=14.232s
------------------------------------------------------------


## Question 77

**Which drugs are associated with the CTLA4 gene?**

In [114]:

question = 'Which drugs are associated with the CTLA4 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
[target_tool]: The query aims to find disease–drug associations related to the target CTLA4.
[target_tool]: Initially, the system retrieved known disease–drug associations for CTLA4, resulting in 607 entries. This step involved collecting all existing associations linked to CTLA4 without applying any filters.
[target_tool]: Next, the system performed deduplication to remove duplicate records among the 607 entries. After this process, the number of unique associations was reduced to 84, eliminating 523 duplicate entries.
[target_tool]: In summary, the final result includes 84 unique disease–drug associations for CTLA4 after removing duplicates.
----------------------------------------
Entries retrieved: 84

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,ctla4,CHEMBL2108658,tremelimumab,4.0,NaN,NaN,cytotoxic t-lymphocyte protein 4 inhibitor

 Run 1 completed | rows=84 | latency=17.560s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
[target_tool]: The query appears to be focused on retrieving and refining data related to the biological target CTLA4.
[target_tool]: Initially, the system retrieved known disease–drug associations for CTLA4, resulting in a total of 607 entries. This step gathered a broad set of possible associations relevant to the target.
[target_tool]: Next, the system performed deduplication to remove any duplicate records within the dataset. This process reduced the number of entries from 607 down to 84, removing 523 duplicate rows to ensure data accuracy and uniqueness.
[target_tool]: In summary, after these steps, there are 84 unique association records for CTLA4.
----------------------------------------
Entries retrieved: 84

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,ctla4,CHEMBL2108658,tremelimumab,4.0,NaN,NaN,cytotoxic t-lymphocyte protein 4 inhibitor

 Run 2 completed | rows=84 | latency=24.994s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
[target_tool]: The query aims to find associated disease and drug information for the target CTLA4.
[target_tool]: First, the system retrieved known disease–drug associations related to CTLA4, resulting in 607 entries.
[target_tool]: Next, the process removed duplicate records from this set, reducing the number of associations from 607 to 84.
[target_tool]: In summary, after filtering for unique records, there are 84 distinct associations related to CTLA4.
----------------------------------------
Entries retrieved: 84

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,ctla4,CHEMBL2108658,tremelimumab,4.0,NaN,NaN,cytotoxic t-lymphocyte protein 4 inhibitor

 Run 3 completed | rows=84 | latency=15.466s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
[target_tool]: The aim was to find information related to the target CTLA4. The process started by retrieving known disease–drug associations related to CTLA4, resulting in 607 entries. This initial retrieval gathered all associated disease-drug pairs linked to CTLA4. Next, duplicate entries were removed from this set to ensure unique records. After this deduplication step, the number of entries was reduced to 84. In summary, the process narrowed down from 607 associations to 84 unique records involving CTLA4.
----------------------------------------
Entries retrieved: 84

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,ctla4,CHEMBL2108658,tremelimumab,4.0,NaN,NaN,cytotoxic t-lymphocyte protein 4 inhibitor

 Run 4 completed | rows=84 | latency=14.038s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
[target_tool]: The query aimed to identify associations related to the target CTLA4.
[target_tool]: First, the system retrieved known disease-drug associations for CTLA4, resulting in 607 entries. Then, to ensure the data was unique and free of duplicates, a deduplication process was applied, which removed 523 duplicate rows. This process left 84 unique association entries remaining.
[target_tool]: In summary, the final result contains 84 unique disease-drug associations related to CTLA4 after filtering out duplicates.
----------------------------------------
Entries retrieved: 84

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000163599,ctla4,CHEMBL2108658,tremelimumab,4.0,NaN,NaN,cytotoxic t-lymphocyte protein 4 inhibitor

 Run 5 completed | rows=84 | latency=15.451s
------------------------------------------------------------


## Question 78

**Which drugs are associated with the BTK gene?**

In [115]:

question = 'Which drugs are associated with the BTK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target BTK.
[target_tool]: First, the system retrieved 447 known disease–drug association records for BTK. Then, to improve data quality and avoid redundancy, it removed duplicate entries, which reduced the total from 447 to 139 unique records.
[target_tool]: The final result includes 139 distinct disease–drug association records related to BTK.
----------------------------------------
Entries retrieved: 139

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000010671,btk,CHEMBL3707348,acalabrutinib,4.0,NaN,NaN,tyrosine-protein kinase btk inhibitor

 Run 1 completed | rows=139 | latency=17.070s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
[target_tool]: This query was aimed at finding associations related to the biological target BTK. First, the system retrieved 447 known disease-drug associations for BTK. Next, it removed duplicate entries from this set, reducing the number of results from 447 to 139.
[target_tool]: In summary, after applying these steps, the final result consists of 139 unique disease-drug association records related to BTK.
----------------------------------------
Entries retrieved: 139

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000010671,btk,CHEMBL3707348,acalabrutinib,4.0,NaN,NaN,tyrosine-protein kinase btk inhibitor

 Run 2 completed | rows=139 | latency=15.054s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
[target_tool]: The query aimed to identify information related to the target BTK. First, the system retrieved the base associations for BTK, resulting in 447 entries. Next, it removed duplicate records from these associations, reducing the number of entries from 447 to 139. In the end, the process yielded 139 unique association records for BTK.
----------------------------------------
Entries retrieved: 139

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000010671,btk,CHEMBL3707348,acalabrutinib,4.0,NaN,NaN,tyrosine-protein kinase btk inhibitor

 Run 3 completed | rows=139 | latency=15.586s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
[target_tool]: The purpose of the query was to identify associations related to the target BTK.
[target_tool]: First, the system retrieved all known disease–drug associations for BTK, resulting in 447 entries. Then, to ensure data quality, it removed duplicate records, which reduced the total from 447 to 139 entries.
[target_tool]: Overall, the final result contains 139 unique associations related to BTK.
----------------------------------------
Entries retrieved: 139

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000010671,btk,CHEMBL3707348,acalabrutinib,4.0,NaN,NaN,tyrosine-protein kinase btk inhibitor

 Run 4 completed | rows=139 | latency=13.723s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to a specific target, BTK.
[target_tool]: Initially, the system retrieved all known disease–drug associations associated with BTK, resulting in 447 entries.
[target_tool]: Next, to ensure the data's accuracy and eliminate redundancy, the system removed duplicate records. This deduplication process reduced the number of entries from 447 to 139.
[target_tool]: In summary, after these steps, there are 139 unique disease–drug associations related to BTK.
----------------------------------------
Entries retrieved: 139

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000010671,btk,CHEMBL3707348,acalabrutinib,4.0,NaN,NaN,tyrosine-protein kinase btk inhibitor

 Run 5 completed | rows=139 | latency=14.912s
------------------------------------------------------------


## Question 79

**Which drugs are associated with the SYK gene?**

In [116]:

question = 'Which drugs are associated with the SYK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
[target_tool]: The query's goal was to find disease and drug associations related to the target SYK.
[target_tool]: First, the system retrieved known disease-drug associations for SYK, resulting in 108 entries. This initial retrieval brought together various potential links related to SYK.
[target_tool]: Next, the process included a deduplication step, where duplicate entries were removed to ensure each association was unique. This step reduced the total from 108 to 53 entries, removing 55 duplicate records.
[target_tool]: In summary, after retrieving the initial associations and removing duplicates, the system produced a final set of 53 unique associations related to the target SYK.
----------------------------------------
Entries retrieved: 53

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165025,syk,CHEMBL3989516,fostamatinib disodium,4,NaN,NaN,tyrosine-protein kinase syk inhibitor

 Run 1 completed | rows=53 | latency=15.660s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
[target_tool]: The query aimed to explore associations related to the target SYK.
[target_tool]: First, the system retrieved known disease–drug associations for SYK, which initially yielded 108 entries.
[target_tool]: Next, the system performed deduplication to eliminate duplicate records, reducing the total from 108 to 53 entries. This step ensured that only unique associations remained.
[target_tool]: In summary, after retrieving all known associations and removing duplicates, there are 53 unique records remaining related to SYK.
----------------------------------------
Entries retrieved: 53

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165025,syk,CHEMBL3989516,fostamatinib disodium,4,NaN,NaN,tyrosine-protein kinase syk inhibitor

 Run 2 completed | rows=53 | latency=15.362s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
[target_tool]: The query aims to identify associations related to the target "SYK" and filter these to specific relationships of interest.
[target_tool]: First, the system retrieved known disease–drug associations for "SYK," resulting in 108 entries. This initial retrieval gathered all the related association records without applying any filters at this stage.
[target_tool]: Next, the process involved removing duplicate records from these 108 entries. After deduplication, 55 unique associations remained, indicating that 53 duplicate entries were eliminated to obtain a set of distinct records.
[target_tool]: In summary, the final dataset contains 55 unique disease–drug association records related to "SYK," after the duplicate removal step.
----------------------------------------
Entries retrieved: 53

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165025,syk,CHEMBL3989516,fostamatinib disodium,4,NaN,NaN,tyrosine-protein kinase syk inhibitor

 Run 3 completed | rows=53 | latency=14.367s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
[target_tool]: The query was designed to explore disease-drug associations related to the target SYK.
[target_tool]: Initially, the system retrieved a total of 108 associations involving SYK.
[target_tool]: Then, it performed deduplication to eliminate duplicate rows, which reduced the count from 108 to 53.
[target_tool]: In the end, the final set contains 53 unique associations connected to SYK.
----------------------------------------
Entries retrieved: 53

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165025,syk,CHEMBL3989516,fostamatinib disodium,4,NaN,NaN,tyrosine-protein kinase syk inhibitor

 Run 4 completed | rows=53 | latency=14.563s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
[target_tool]: The query aims to analyze known drug associations related to a specific target, SYK. First, the system retrieved known disease-drug associations for SYK, resulting in a total of 108 entries. Next, the system removed duplicate records from this set, reducing the number from 108 to 53 entries. This deduplication step ensured that only unique associations were retained. The final result includes 53 distinct disease-drug associations related to SYK.
----------------------------------------
Entries retrieved: 53

,target_id,target_name,drug_id,drug_name,phase,status,action_types,mechanism_of_action
0,ENSG00000165025,syk,CHEMBL3989516,fostamatinib disodium,4,NaN,NaN,tyrosine-protein kinase syk inhibitor

 Run 5 completed | rows=53 | latency=14.137s
------------------------------------------------------------


## Question 80

**Which pathways are associated with TP53?**

In [117]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The query aimed to retrieve information related to the biological pathways associated with the target TP53.
[target_tool]: In the first step, the system retrieved pathways related to TP53, resulting in a total of 45 pathway entries. This step involved accessing pathway data linked to TP53 but did not specify an initial number of entries before retrieval.
[target_tool]: The final result after this step was 45 pathways associated with the target TP53.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 1 completed | rows=45 | latency=14.152s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The query was intended to identify biological pathways associated with the target TP53.
[target_tool]: The first step involved retrieving information related to pathways connected to TP53. This action resulted in 45 pathways being identified, although the exact number of pathways before this retrieval is not specified in the log.
[target_tool]: Since there is only one step detailed in the provided log, the process concluded after retrieving these pathway associations.
[target_tool]: The final result includes information on 45 pathways related to TP53.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 2 completed | rows=45 | latency=14.501s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The goal of the query was to retrieve pathway information related to the target TP53. First, the system retrieved pathways associated with TP53, resulting in 45 entries. This step involved collecting all relevant pathways linked to this specific target. Since only the retrieval step is shown, it indicates that 45 pathways were identified for TP53. Therefore, the final result consisted of 45 pathway records related to TP53.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 3 completed | rows=45 | latency=15.246s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The goal of the query was to gather information related to the target gene TP53.
[target_tool]: First, the system retrieved pathway information associated with TP53, which resulted in a total of 45 pathways. This step involved extracting pathways that are related to the target gene to provide context about its biological roles.
[target_tool]: Because only the pathway retrieval step is shown in the provided log, no further filtering or reduction of data is detailed beyond this point.
[target_tool]: In summary, the final result includes pathways linked to TP53, with a total of 45 pathways retrieved.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 4 completed | rows=45 | latency=16.175s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
[target_tool]: The purpose of the query was to find pathways associated with the target, TP53.
[target_tool]: First, the system retrieved pathway information related to TP53, resulting in 45 pathways. This step involved accessing pathway data specifically linked to the target gene or protein TP53.
[target_tool]: Overall, the final result included information about 45 pathways associated with TP53.
----------------------------------------
Entries retrieved: 45

,target_name,target_id,pathway_id,pathway_name,top_level_term
0,TP53,ENSG00000141510,R-HSA-3232118,SUMOylation of transcription factors,Metabolism of proteins

 Run 5 completed | rows=45 | latency=14.944s
------------------------------------------------------------

##### Store as .pkl

In [121]:
import pickle
with open("Opentarget_same_question_response.pkl", "wb") as f:
    pickle.dump(dct_result, f)

##### Store as json

In [122]:
import json
import pandas as pd

def make_json_safe(obj):
    if isinstance(obj, pd.DataFrame):
        return {
            "__type__": "dataframe",
            "columns": obj.columns.tolist(),
            "rows": obj.to_dict(orient="records")
        }
    elif isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    else:
        return obj


json_safe_result = make_json_safe(dct_result)

with open("Opentarget_same_question_response.json", "w", encoding="utf-8") as f:
    json.dump(
        json_safe_result,
        f,
        indent=2,
        ensure_ascii=False
    )