In [107]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from llama_utility import return_llama_answer

In [108]:



model = "llama-3.3-70b-versatile"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [109]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      BRAF     Melanoma

 Run 1 completed | rows=4 | latency=0.390s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     Melanoma      BRAF

 Run 2 completed | rows=3 | latency=0.381s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

        disease_name gene_name
0  Colorectal cancer      BRAF

 Run 3 completed | rows=4 | latency=0.382s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 6

  gene_name         disease_name
0      BRAF  Hairy Cell Leukemia

 Run 4 completed | rows=6 | latency=0.429s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      BRAF     Melanoma

 Run 5 completed | rows=4 | latency=0.408s
------------------------------------------------------------


## Question 2

**List genes linked to amyotrophic lateral sclerosis.**

In [110]:

question = 'List genes linked to amyotrophic lateral sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 24

  gene_name
0      ALS2

 Run 1 completed | rows=24 | latency=2.425s
------------------------------------------------------------

 Starting run 2 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 8

  gene_name
0      SOD1

 Run 2 completed | rows=8 | latency=0.407s
------------------------------------------------------------

 Starting run 3 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 9

  gene_name
0      SOD1

 Run 3 completed | rows=9 | latency=0.392s
------------------------------------------------------------

 Starting run 4 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 1

                                                                                                                                                                                      gene_name
ALS2 ANG AOPEP ARHGEF28 ATXN2 ATXN3 C21orf2 C9orf72 CCNF CHCHD10 CHMP2B DAO DCTN1 ERBB4 FIG4 FUS GRN HNRNPA1 HNRNPA2B1 IFITM3 OPTN PFN1 SETX SOD1 SQSTM1 TARDBP TIA1 TBK1 UBQLN2 VAPB       VCP

 Run 4 completed | rows=1 | latency=0.948s
------------------------------------------------------------

 Starting run 5 for query: List genes linked to amyotrophic lateral sclerosis.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0      SOD1

 Run 5 completed | rows=5 | latency=0.375s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [111]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 1 completed | rows=3 | latency=0.368s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0     Melanoma      CDK4

 Run 2 completed | rows=3 | latency=0.345s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 3 completed | rows=3 | latency=0.356s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 4 completed | rows=3 | latency=0.370s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      CDK4     Melanoma

 Run 5 completed | rows=3 | latency=0.342s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [112]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 1 completed | rows=3 | latency=1.524s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 2 completed | rows=3 | latency=0.364s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 3 completed | rows=3 | latency=0.442s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 4 completed | rows=3 | latency=0.432s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      JAK2  JAK/STAT signaling pathway

 Run 5 completed | rows=3 | latency=0.420s
------------------------------------------------------------


## Question 5

**Which drugs are used for treating rheumatoid arthritis?**

In [113]:

question = 'Which drugs are used for treating rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 9

    drug_name          disease_name approval_status
0  Adalimumab  Rheumatoid Arthritis        Approved

 Run 1 completed | rows=9 | latency=0.536s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid Arthritis        Approved

 Run 2 completed | rows=8 | latency=0.501s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 9

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid Arthritis        Approved

 Run 3 completed | rows=9 | latency=0.579s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 12

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid Arthritis        Approved

 Run 4 completed | rows=12 | latency=0.629s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 12

      drug_name          disease_name approval_status
0  Methotrexate  Rheumatoid Arthritis        Approved

 Run 5 completed | rows=12 | latency=0.652s
------------------------------------------------------------


## Question 6

**What are the targets and mechanisms for dulaglutide?**

In [114]:

question = 'What are the targets and mechanisms for dulaglutide?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action approval_status
0  Dulaglutide  GLP-1 receptor  GLP-1 receptor agonist        Approved

 Run 1 completed | rows=1 | latency=0.518s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,mechanism_of_action,approval_status
0,Dulaglutide,GLP-1 receptor,"Increases insulin secretion, decreases glucago...",Approved

 Run 2 completed | rows=1 | latency=0.387s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  Dulaglutide  GLP-1 receptor  GLP-1 receptor agonism

 Run 3 completed | rows=1 | latency=0.340s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name target_name     mechanism_of_action
0  Dulaglutide      GLP-1R  GLP-1 receptor agonism

 Run 4 completed | rows=1 | latency=0.371s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for dulaglutide?
  Attempt 1/3
Entries retrieved: 1

     drug_name     target_name     mechanism_of_action
0  Dulaglutide  GLP-1 receptor  GLP-1 receptor agonist

 Run 5 completed | rows=1 | latency=0.755s
------------------------------------------------------------


## Question 7

**Provide target names for ovarian cancer?**

In [115]:

question = 'Provide target names for ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name    disease_name
0       BRCA1  Ovarian Cancer

 Run 1 completed | rows=4 | latency=0.362s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name
0       BRCA1

 Run 2 completed | rows=5 | latency=0.357s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name    disease_name
0       BRCA1  Ovarian Cancer

 Run 3 completed | rows=5 | latency=0.413s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 4

  target_name    disease_name
0       BRCA1  Ovarian Cancer

 Run 4 completed | rows=4 | latency=0.489s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ovarian cancer?
  Attempt 1/3
Entries retrieved: 6

  target_name    disease_name
0       BRCA1  Ovarian Cancer

 Run 5 completed | rows=6 | latency=0.495s
------------------------------------------------------------


## Question 8

**What are the known targets of regorafenib?**

In [116]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 10

     drug_name target_name gene_name      mechanism_of_action
0  regorafenib      VEGFR1      FLT1  angiogenesis inhibition

 Run 1 completed | rows=10 | latency=0.670s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name gene_name         mechanism_of_action
0  Regorafenib      VEGFR1      FLT1  Tyrosine kinase inhibition

 Run 2 completed | rows=11 | latency=0.772s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 10

     drug_name target_name gene_name      mechanism_of_action
0  Regorafenib      VEGFR1      FLT1  Angiogenesis inhibition

 Run 3 completed | rows=10 | latency=0.733s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name target_name gene_name      mechanism_of_action
0  Regorafenib      VEGFR2      KGDR  Angiogenesis inhibition

 Run 4 completed | rows=9 | latency=0.744s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 11

     drug_name target_name mechanism_of_action
0  Regorafenib      VEGFR1          Inhibition

 Run 5 completed | rows=11 | latency=0.612s
------------------------------------------------------------


## Question 9

**Which pathways are associated with the STAT3 gene?**

In [117]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 1 completed | rows=4 | latency=0.406s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 2 completed | rows=4 | latency=0.364s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 3 completed | rows=4 | latency=0.378s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 4 completed | rows=5 | latency=0.405s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0     STAT3  JAK/STAT signaling pathway

 Run 5 completed | rows=4 | latency=0.377s
------------------------------------------------------------


## Question 10

**Genes linked to fever.**

In [118]:

question = 'Genes linked to fever.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 1

                  gene_name
TNF TLR4 IL1B IL6    PYCARD

 Run 1 completed | rows=1 | latency=0.375s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 1

         gene_name
TNF IL1B       IL6

 Run 2 completed | rows=1 | latency=60.856s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  gene_name
0       TNF

 Run 3 completed | rows=3 | latency=0.281s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 3

  gene_name
0       TNF

 Run 4 completed | rows=3 | latency=0.289s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to fever.
  Attempt 1/3
Entries retrieved: 4

  gene_name
0      TLR4

 Run 5 completed | rows=4 | latency=0.281s
------------------------------------------------------------


## Question 11

**List all drugs that target EGFR?**

In [119]:

question = 'List all drugs that target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name approval_status         mechanism_of_action
0  Erlotinib        EGFR        Approved  Tyrosine kinase inhibition

 Run 1 completed | rows=7 | latency=0.595s
------------------------------------------------------------

 Starting run 2 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name approval_status mechanism_of_action
0  Cetuximab        EGFR        Approved     EGFR inhibition

 Run 2 completed | rows=7 | latency=0.596s
------------------------------------------------------------

 Starting run 3 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name approval_status
0  Cetuximab        EGFR        Approved

 Run 3 completed | rows=6 | latency=0.502s
------------------------------------------------------------

 Starting run 4 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name approval_status mechanism_of_action
0  Cetuximab        EGFR        Approved     EGFR inhibition

 Run 4 completed | rows=7 | latency=0.560s
------------------------------------------------------------

 Starting run 5 for query: List all drugs that target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name approval_status         mechanism_of_action
0  Erlotinib        EGFR        Approved  Tyrosine kinase inhibition

 Run 5 completed | rows=7 | latency=0.588s
------------------------------------------------------------


## Question 12

**Show drugs that inhibit the FGFR2 gene?**

In [120]:

question = 'Show drugs that inhibit the FGFR2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name gene_name  approval_status mechanism_of_action
0  Pertuzumab       FGFR2     FGFR2  Investigational     FGFR inhibition

 Run 1 completed | rows=4 | latency=0.525s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 3

     drug_name target_name gene_name mechanism_of_action approval_status
0  Erdafitinib       FGFR2     FGFR2     FGFR inhibition        Approved

 Run 2 completed | rows=3 | latency=0.507s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 3

     drug_name target_name gene_name mechanism_of_action approval_status
0  Pemigatinib       FGFR2     FGFR2     FGFR inhibition        Approved

 Run 3 completed | rows=3 | latency=0.464s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 4

    drug_name gene_name mechanism_of_action  approval_status
0  Pertuzumab     FGFR2     FGFR inhibition  Investigational

 Run 4 completed | rows=4 | latency=0.513s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the FGFR2 gene?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name gene_name         mechanism_of_action approval_status
0  Erlotinib       FGFR2     FGFR2  Tyrosine kinase inhibition        Approved

 Run 5 completed | rows=5 | latency=0.653s
------------------------------------------------------------


## Question 13

**What diseases are treated with bevacizumab?**

In [121]:

question = 'What diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name approval_status
0  Bevacizumab  Colorectal Cancer        Approved

 Run 1 completed | rows=6 | latency=0.437s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 2 completed | rows=6 | latency=0.477s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

        disease_name    drug_name approval_status
0  Colorectal Cancer  Bevacizumab        Approved

 Run 3 completed | rows=7 | latency=0.531s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 6

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 4 completed | rows=6 | latency=0.417s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name approval_status
0  Bevacizumab  Colorectal cancer        Approved

 Run 5 completed | rows=7 | latency=0.519s
------------------------------------------------------------


## Question 14

**List treatments for plaque psoriasis and their mechanisms.**

In [122]:

question = 'List treatments for plaque psoriasis and their mechanisms.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 6

    drug_name      disease_name   mechanism_of_action
0  Adalimumab  Plaque Psoriasis  TNF-alpha inhibition

 Run 1 completed | rows=6 | latency=0.512s
------------------------------------------------------------

 Starting run 2 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 9

,drug_name,disease_name,mechanism_of_action
0,Adalimumab,Plaque Psoriasis,Tumor Necrosis Factor-alpha (TNF-alpha) Inhibi...

 Run 2 completed | rows=9 | latency=0.798s
------------------------------------------------------------

 Starting run 3 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 10

,drug_name,disease_name,target_name,mechanism_of_action,approval_status
0,Adalimumab,Plaque Psoriasis,TNF-alpha,TNF-alpha inhibition,Approved

 Run 3 completed | rows=10 | latency=0.880s
------------------------------------------------------------

 Starting run 4 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 9

    drug_name      disease_name   mechanism_of_action
0  Adalimumab  Plaque Psoriasis  TNF-alpha inhibition

 Run 4 completed | rows=9 | latency=0.690s
------------------------------------------------------------

 Starting run 5 for query: List treatments for plaque psoriasis and their mechanisms.
  Attempt 1/3
Entries retrieved: 6

    drug_name      disease_name target_name   mechanism_of_action
0  Etanercept  Plaque Psoriasis   TNF-alpha  TNF-alpha inhibition

 Run 5 completed | rows=6 | latency=0.599s
------------------------------------------------------------


## Question 15

**What are the known targets of cabozantinib?**

In [123]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name target_name gene_name mechanism_of_action
0  Cabozantinib      VEGFR2    VEGFR2          Inhibition

 Run 1 completed | rows=7 | latency=0.543s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name target_name         mechanism_of_action
0  cabozantinib      VEGFR2  tyrosine kinase inhibition

 Run 2 completed | rows=7 | latency=0.505s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name target_name         mechanism_of_action approval_status
0  cabozantinib         MET  tyrosine kinase inhibition        Approved

 Run 3 completed | rows=6 | latency=0.499s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name target_name gene_name         mechanism_of_action
0  Cabozantinib      VEGFR2       KDR  Tyrosine kinase inhibition

 Run 4 completed | rows=7 | latency=0.598s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

  target_name     drug_name mechanism_of_action
0         MET  cabozantinib          inhibition

 Run 5 completed | rows=6 | latency=0.522s
------------------------------------------------------------


## Question 16

**Show drugs that inhibit the RET gene?**

In [124]:

question = 'Show drugs that inhibit the RET gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name gene_name         mechanism_of_action approval_status
0  Sunitinib         RET       RET  Tyrosine kinase inhibition        Approved

 Run 1 completed | rows=5 | latency=0.586s
------------------------------------------------------------

 Starting run 2 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name gene_name         mechanism_of_action approval_status
0  Sunitinib         RET       RET  Tyrosine kinase inhibition        Approved

 Run 2 completed | rows=5 | latency=0.564s
------------------------------------------------------------

 Starting run 3 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 8

    drug_name target_name approval_status         mechanism_of_action
0  Vandetanib         RET        Approved  Tyrosine kinase inhibition

 Run 3 completed | rows=8 | latency=0.601s
------------------------------------------------------------

 Starting run 4 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name gene_name         mechanism_of_action approval_status
0  Sunitinib         RET       RET  Tyrosine kinase inhibition        Approved

 Run 4 completed | rows=6 | latency=0.574s
------------------------------------------------------------

 Starting run 5 for query: Show drugs that inhibit the RET gene?
  Attempt 1/3
Entries retrieved: 5

       drug_name target_name approval_status mechanism_of_action
0  Selpercatinib         RET        Approved   Kinase inhibition

 Run 5 completed | rows=5 | latency=0.486s
------------------------------------------------------------


## Question 17

**Which pathways are associated with the TNF gene?**

In [125]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

               gene_name pathway_name
0  Tumor Necrosis Factor    Apoptosis

 Run 1 completed | rows=4 | latency=0.402s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name pathway_name
0       TNF    Apoptosis

 Run 2 completed | rows=3 | latency=0.395s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0       TNF    Apoptosis

 Run 3 completed | rows=5 | latency=0.393s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 6

  gene_name pathway_name
0       TNF    Apoptosis

 Run 4 completed | rows=6 | latency=0.452s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0       TNF    Apoptosis

 Run 5 completed | rows=5 | latency=0.403s
------------------------------------------------------------


## Question 18

**Diseases associated with the gene NPM1.**

In [126]:

question = 'Diseases associated with the gene NPM1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 3

  gene_name            disease_name
0      NPM1  Acute Myeloid Leukemia

 Run 1 completed | rows=3 | latency=0.366s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 5

  gene_name             disease_name
0      NPM1  Acute Myeloid Leukemia

 Run 2 completed | rows=5 | latency=0.454s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 3

  gene_name            disease_name
0      NPM1  Acute Myeloid Leukemia

 Run 3 completed | rows=3 | latency=0.349s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 1

  gene_name            disease_name
0      NPM1  Acute Myeloid Leukemia

 Run 4 completed | rows=1 | latency=0.450s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene NPM1.
  Attempt 1/3
Entries retrieved: 4

  gene_name             disease_name
0      NPM1  Acute Myeloid Leukemia

 Run 5 completed | rows=4 | latency=0.506s
------------------------------------------------------------


## Question 19

**Which pathways are associated with the CD19 gene?**

In [127]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 1 completed | rows=3 | latency=0.410s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 2 completed | rows=3 | latency=0.387s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 3 completed | rows=2 | latency=0.340s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 4 completed | rows=3 | latency=0.397s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 5 completed | rows=2 | latency=0.346s
------------------------------------------------------------


## Question 20

**Which drugs are used for treating migraine?**

In [128]:

question = 'Which drugs are used for treating migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 7

     drug_name disease_name approval_status
0  Sumatriptan     Migraine        Approved

 Run 1 completed | rows=7 | latency=0.505s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 9

     drug_name disease_name approval_status
0  Sumatriptan     Migraine        Approved

 Run 2 completed | rows=9 | latency=0.491s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 5

     drug_name disease_name approval_status
0  Sumatriptan     Migraine        Approved

 Run 3 completed | rows=5 | latency=0.437s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 9

     drug_name approval_status disease_name
0  Sumatriptan        Approved     Migraine

 Run 4 completed | rows=9 | latency=0.498s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for treating migraine?
  Attempt 1/3
Entries retrieved: 5

     drug_name disease_name approval_status
0  Sumatriptan     Migraine        Approved

 Run 5 completed | rows=5 | latency=0.413s
------------------------------------------------------------


## Question 21

**What are the targets and mechanisms for rituximab?**

In [129]:

question = 'What are the targets and mechanisms for rituximab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name                                mechanism_of_action
0  Rituximab        CD20  Antibody-dependent cellular cytotoxicity, comp...

 Run 1 completed | rows=1 | latency=0.443s
------------------------------------------------------------

 Starting run 2 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name                                mechanism_of_action
0  Rituximab        CD20  Antibody-dependent cellular cytotoxicity, Comp...

 Run 2 completed | rows=1 | latency=0.449s
------------------------------------------------------------

 Starting run 3 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name gene_name                       mechanism_of_action
0  Rituximab        CD20     MS4A1  Antibody-dependent cellular cytotoxicity

 Run 3 completed | rows=1 | latency=0.353s
------------------------------------------------------------

 Starting run 4 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,mechanism_of_action
0,Rituximab,CD20,MS4A1,"Antibody-dependent cellular cytotoxicity, Comp..."

 Run 4 completed | rows=1 | latency=0.401s
------------------------------------------------------------

 Starting run 5 for query: What are the targets and mechanisms for rituximab?
  Attempt 1/3
Entries retrieved: 1

   drug_name target_name                                mechanism_of_action
0  Rituximab        CD20  Antibody-dependent cellular cytotoxicity, Comp...

 Run 5 completed | rows=1 | latency=0.370s
------------------------------------------------------------


## Question 22

**Provide target names for colorectal cancer?**

In [130]:

question = 'Provide target names for colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name gene_name       disease_name
0        EGFR      EGFR  Colorectal Cancer

 Run 1 completed | rows=5 | latency=0.433s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 6

  target_name
0        EGFR

 Run 2 completed | rows=6 | latency=0.394s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name
0        EGFR

 Run 3 completed | rows=5 | latency=0.335s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name
0        EGFR

 Run 4 completed | rows=5 | latency=0.451s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  target_name       disease_name
0        EGFR  Colorectal Cancer

 Run 5 completed | rows=5 | latency=0.381s
------------------------------------------------------------


## Question 23

**Which are possible drugs against rickets?**

In [131]:

question = 'Which are possible drugs against rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

        drug_name approval_status
0  Ergocalciferol        Approved

 Run 1 completed | rows=4 | latency=1.786s
------------------------------------------------------------

 Starting run 2 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 3

        drug_name approval_status disease_name
0  Ergocalciferol        Approved      Rickets

 Run 2 completed | rows=3 | latency=0.422s
------------------------------------------------------------

 Starting run 3 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 5

        drug_name approval_status
0  Ergocalciferol        Approved

 Run 3 completed | rows=5 | latency=0.361s
------------------------------------------------------------

 Starting run 4 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 5

        drug_name approval_status
0  Ergocalciferol        Approved

 Run 4 completed | rows=5 | latency=0.372s
------------------------------------------------------------

 Starting run 5 for query: Which are possible drugs against rickets?
  Attempt 1/3
Entries retrieved: 4

        drug_name approval_status disease_name
0  Ergocalciferol        Approved      Rickets

 Run 5 completed | rows=4 | latency=0.395s
------------------------------------------------------------


## Question 24

**Give me genes linked to epilepsy.**

In [132]:

question = 'Give me genes linked to epilepsy.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 7

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 1 completed | rows=7 | latency=0.424s
------------------------------------------------------------

 Starting run 2 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 10

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 2 completed | rows=10 | latency=0.505s
------------------------------------------------------------

 Starting run 3 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 10

  gene_name
0     SCN1A

 Run 3 completed | rows=10 | latency=0.401s
------------------------------------------------------------

 Starting run 4 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0     SCN1A

 Run 4 completed | rows=5 | latency=61.006s
------------------------------------------------------------

 Starting run 5 for query: Give me genes linked to epilepsy.
  Attempt 1/3
Entries retrieved: 5

  gene_name disease_name
0     SCN1A     Epilepsy

 Run 5 completed | rows=5 | latency=0.512s
------------------------------------------------------------


## Question 25

**What diseases are treated with trastuzumab deruxtecan?**

In [133]:

question = 'What diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name   disease_name approval_status
0  trastuzumab deruxtecan  Breast Cancer        Approved

 Run 1 completed | rows=3 | latency=0.447s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 3

                drug_name target_name   disease_name approval_status
0  Trastuzumab deruxtecan        HER2  Breast cancer        Approved

 Run 2 completed | rows=3 | latency=0.483s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name
0  Trastuzumab deruxtecan  Breast cancer

 Run 3 completed | rows=2 | latency=0.342s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name approval_status
0  Trastuzumab deruxtecan  Breast cancer        Approved

 Run 4 completed | rows=2 | latency=0.373s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 2

                drug_name   disease_name approval_status
0  Trastuzumab deruxtecan  Breast cancer        Approved

 Run 5 completed | rows=2 | latency=0.401s
------------------------------------------------------------


## Question 26

**Genes linked to Alzheimer’s disease.**

In [134]:

question = 'Genes linked to Alzheimer’s disease.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 8

  gene_name
0       APP

 Run 1 completed | rows=8 | latency=0.474s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 2 completed | rows=4 | latency=0.376s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 5

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 3 completed | rows=5 | latency=0.389s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 5

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 4 completed | rows=5 | latency=0.383s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to Alzheimer’s disease.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0       APP

 Run 5 completed | rows=5 | latency=0.326s
------------------------------------------------------------


## Question 27

**For which disease is darolutamide used?**

In [135]:

question = 'For which disease is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name approval_status
0  darolutamide  Prostate Cancer        Approved

 Run 1 completed | rows=1 | latency=0.438s
------------------------------------------------------------

 Starting run 2 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 2 completed | rows=1 | latency=0.296s
------------------------------------------------------------

 Starting run 3 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  Prostate Cancer  darolutamide

 Run 3 completed | rows=1 | latency=0.352s
------------------------------------------------------------

 Starting run 4 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      disease_name     drug_name
0  Prostate Cancer  Darolutamide

 Run 4 completed | rows=1 | latency=0.406s
------------------------------------------------------------

 Starting run 5 for query: For which disease is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  Darolutamide  Prostate Cancer

 Run 5 completed | rows=1 | latency=0.306s
------------------------------------------------------------


## Question 28

**Provide target names for renal cell carcinoma?**

In [136]:

question = 'Provide target names for renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  target_name
0       VEGFR

 Run 1 completed | rows=5 | latency=0.374s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 4

  target_name
0       VEGFR

 Run 2 completed | rows=4 | latency=0.451s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 8

  target_name
0       VEGFR

 Run 3 completed | rows=8 | latency=0.391s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 4

  target_name
0       VEGFR

 Run 4 completed | rows=4 | latency=0.318s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  target_name          disease_name
0       VEGFR  Renal Cell Carcinoma

 Run 5 completed | rows=5 | latency=0.392s
------------------------------------------------------------


## Question 29

**Diseases associated with the gene KRAS.**

In [137]:

question = 'Diseases associated with the gene KRAS.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

  gene_name       disease_name
0      KRAS  Pancreatic Cancer

 Run 1 completed | rows=3 | latency=0.329s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 2 completed | rows=3 | latency=0.342s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 3 completed | rows=3 | latency=0.336s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 4 completed | rows=3 | latency=0.327s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene KRAS.
  Attempt 1/3
Entries retrieved: 3

  gene_name disease_name
0      KRAS  Lung Cancer

 Run 5 completed | rows=3 | latency=0.326s
------------------------------------------------------------


## Question 30

**Which pathways are associated with the APP gene?**

In [138]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 1 completed | rows=5 | latency=0.458s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 2 completed | rows=5 | latency=0.445s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 3 completed | rows=4 | latency=0.435s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 4 completed | rows=5 | latency=0.415s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name             pathway_name
0       APP  Notch signaling pathway

 Run 5 completed | rows=4 | latency=0.422s
------------------------------------------------------------


## Question 31

**Genes linked to schizophrenia.**

In [139]:

question = 'Genes linked to schizophrenia.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0      DRD2

 Run 1 completed | rows=5 | latency=0.424s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 8

  gene_name
0      DRD2

 Run 2 completed | rows=8 | latency=0.440s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0      DRD2

 Run 3 completed | rows=5 | latency=0.382s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 9

  gene_name
0      DRD2

 Run 4 completed | rows=9 | latency=0.475s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to schizophrenia.
  Attempt 1/3
Entries retrieved: 5

  gene_name   disease_name
0      DRD2  Schizophrenia

 Run 5 completed | rows=5 | latency=0.446s
------------------------------------------------------------


## Question 32

**What diseases are treated with valdecoxib?**

In [140]:

question = 'What diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

     disease_name   drug_name
0  Osteoarthritis  valdecoxib

 Run 1 completed | rows=4 | latency=0.427s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 4

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 2 completed | rows=4 | latency=0.369s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 5

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 3 completed | rows=5 | latency=0.410s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 5

  disease_name   drug_name
0         Pain  Valdecoxib

 Run 4 completed | rows=5 | latency=0.405s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 3

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 5 completed | rows=3 | latency=0.354s
------------------------------------------------------------


## Question 33

**What are the known targets of vandetanib?**

In [141]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name mechanism_of_action
0  Vandetanib         RET          inhibition

 Run 1 completed | rows=4 | latency=0.425s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

  target_name gene_name         mechanism_of_action
0         RET       RET  tyrosine kinase inhibition

 Run 2 completed | rows=4 | latency=0.484s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name gene_name         mechanism_of_action
0  Vandetanib       VEGFR    VEGFR2  Tyrosine kinase inhibition

 Run 3 completed | rows=3 | latency=0.413s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name target_name         mechanism_of_action
0  Vandetanib        EGFR  tyrosine kinase inhibition

 Run 4 completed | rows=3 | latency=0.413s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 4

    drug_name target_name mechanism_of_action approval_status
0  Vandetanib         RET          inhibition        Approved

 Run 5 completed | rows=4 | latency=0.457s
------------------------------------------------------------


## Question 34

**Which pathways are associated with the CFTR gene?**

In [142]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                                       pathway_name
0      CFTR  Epithelial cell signaling in Helicobacter pylo...

 Run 1 completed | rows=5 | latency=0.530s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name pathway_name
0      CFTR    Apoptosis

 Run 2 completed | rows=5 | latency=0.466s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 3 completed | rows=4 | latency=0.427s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 4 completed | rows=3 | latency=0.380s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0      CFTR  cAMP signaling pathway

 Run 5 completed | rows=3 | latency=0.498s
------------------------------------------------------------


## Question 35

**Which drugs are used for TB?**

In [143]:

question = 'Which drugs are used for TB?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 7

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 1 completed | rows=7 | latency=0.412s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 11

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 2 completed | rows=11 | latency=0.511s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 3 completed | rows=4 | latency=0.411s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 11

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 4 completed | rows=11 | latency=0.537s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for TB?
  Attempt 1/3
Entries retrieved: 11

   drug_name  disease_name approval_status
0  Isoniazid  Tuberculosis        Approved

 Run 5 completed | rows=11 | latency=0.647s
------------------------------------------------------------


## Question 36

**Which drugs are used for pancreatic adenocarcinoma?**

In [144]:

question = 'Which drugs are used for pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name approval_status
0  Gemcitabine  Pancreatic adenocarcinoma        Approved

 Run 1 completed | rows=5 | latency=0.565s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name approval_status
0  Gemcitabine  Pancreatic Adenocarcinoma        Approved

 Run 2 completed | rows=6 | latency=0.514s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name approval_status
0  Gemcitabine  Pancreatic Adenocarcinoma        Approved

 Run 3 completed | rows=6 | latency=0.614s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name approval_status
0  Gemcitabine  Pancreatic Adenocarcinoma        Approved

 Run 4 completed | rows=5 | latency=0.486s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name approval_status
0  Gemcitabine  Pancreatic Adenocarcinoma        Approved

 Run 5 completed | rows=6 | latency=0.524s
------------------------------------------------------------


## Question 37

**Which drugs are used in chronic myeloid leukemia?**

In [145]:

question = 'Which drugs are used in chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic Myeloid Leukemia        Approved

 Run 1 completed | rows=5 | latency=0.466s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic Myeloid Leukemia        Approved

 Run 2 completed | rows=5 | latency=0.447s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic Myeloid Leukemia        Approved

 Run 3 completed | rows=5 | latency=0.448s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic Myeloid Leukemia        Approved

 Run 4 completed | rows=5 | latency=0.445s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used in chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name approval_status
0  Imatinib  Chronic Myeloid Leukemia        Approved

 Run 5 completed | rows=5 | latency=0.514s
------------------------------------------------------------


## Question 38

**What drugs are used in the treatment of Parkinson’s disease?**

In [146]:

question = 'What drugs are used in the treatment of Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 9

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 1 completed | rows=9 | latency=0.479s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 9

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 2 completed | rows=9 | latency=0.550s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 7

  drug_name         disease_name   mechanism_of_action
0  Levodopa  Parkinson's disease  Dopamine replacement

 Run 3 completed | rows=7 | latency=0.490s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 8

  drug_name         disease_name   mechanism_of_action approval_status
0  Levodopa  Parkinson’s disease  Dopamine replacement        Approved

 Run 4 completed | rows=8 | latency=0.573s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in the treatment of Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 9

  drug_name         disease_name approval_status
0  Levodopa  Parkinson’s disease        Approved

 Run 5 completed | rows=9 | latency=0.517s
------------------------------------------------------------


## Question 39

**Which drugs are used for inflammatory bowel disease?**

In [147]:

question = 'Which drugs are used for inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 7

          drug_name                disease_name approval_status
0  Aminosalicylates  Inflammatory Bowel Disease        Approved

 Run 1 completed | rows=7 | latency=0.548s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 10

          drug_name                disease_name approval_status
0  Aminosalicylates  Inflammatory Bowel Disease        Approved

 Run 2 completed | rows=10 | latency=0.606s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 9

          drug_name                disease_name approval_status
0  Aminosalicylates  Inflammatory Bowel Disease        Approved

 Run 3 completed | rows=9 | latency=0.622s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 5

    drug_name                disease_name approval_status
0  Infliximab  Inflammatory Bowel Disease        Approved

 Run 4 completed | rows=5 | latency=0.582s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 8

          drug_name                disease_name approval_status
0  Aminosalicylates  Inflammatory Bowel Disease        Approved

 Run 5 completed | rows=8 | latency=0.531s
------------------------------------------------------------


## Question 40

**What targets are acted on by imatinib?**

In [148]:

question = 'What targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 3

  drug_name target_name         mechanism_of_action
0  Imatinib     BCR-ABL  tyrosine kinase inhibition

 Run 1 completed | rows=3 | latency=0.412s
------------------------------------------------------------

 Starting run 2 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 3

  drug_name target_name gene_name         mechanism_of_action
0  Imatinib     BCR-ABL      ABL1  Tyrosine kinase inhibition

 Run 2 completed | rows=3 | latency=0.467s
------------------------------------------------------------

 Starting run 3 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 3

  drug_name target_name         mechanism_of_action
0  Imatinib     BCR-ABL  Tyrosine kinase inhibition

 Run 3 completed | rows=3 | latency=0.375s
------------------------------------------------------------

 Starting run 4 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 3

  drug_name target_name         mechanism_of_action
0  Imatinib     BCR-ABL  Tyrosine kinase inhibition

 Run 4 completed | rows=3 | latency=1.697s
------------------------------------------------------------

 Starting run 5 for query: What targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 3

  drug_name target_name gene_name         mechanism_of_action
0  Imatinib     BCR-ABL       BCR  Tyrosine kinase inhibition

 Run 5 completed | rows=3 | latency=0.435s
------------------------------------------------------------


## Question 41

**What biological targets does sorafenib interact with?**

In [149]:

question = 'What biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name gene_name      mechanism_of_action
0  Sorafenib       VEGFR    VEGFR2  Angiogenesis inhibition

 Run 1 completed | rows=7 | latency=0.528s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name gene_name mechanism_of_action
0  Sorafenib  Raf kinase      RAF1          Inhibition

 Run 2 completed | rows=5 | latency=0.520s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name mechanism_of_action
0  Sorafenib  RAF kinase          inhibition

 Run 3 completed | rows=5 | latency=0.431s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 8

  target_name gene_name         mechanism_of_action
0      VEGFR2       KDR  tyrosine kinase inhibition

 Run 4 completed | rows=8 | latency=0.605s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name gene_name         mechanism_of_action
0  Sorafenib       VEGFR    VEGFR2  Tyrosine kinase inhibition

 Run 5 completed | rows=5 | latency=0.440s
------------------------------------------------------------


## Question 42

**What biological targets does tofacitinib affect?**

In [150]:

question = 'What biological targets does tofacitinib affect?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 4

     drug_name target_name mechanism_of_action
0  Tofacitinib        JAK1          inhibition

 Run 1 completed | rows=4 | latency=0.419s
------------------------------------------------------------

 Starting run 2 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name            target_name mechanism_of_action
0  Tofacitinib  Janus kinase 1 (JAK1)          inhibition

 Run 2 completed | rows=3 | latency=0.407s
------------------------------------------------------------

 Starting run 3 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 4

     drug_name target_name mechanism_of_action
0  Tofacitinib        JAK1          inhibition

 Run 3 completed | rows=4 | latency=0.385s
------------------------------------------------------------

 Starting run 4 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 4

      target_name gene_name mechanism_of_action
0  Janus kinase 1      JAK1          inhibition

 Run 4 completed | rows=4 | latency=0.439s
------------------------------------------------------------

 Starting run 5 for query: What biological targets does tofacitinib affect?
  Attempt 1/3
Entries retrieved: 3

     drug_name            target_name mechanism_of_action
0  Tofacitinib  Janus kinase 1 (JAK1)          inhibition

 Run 5 completed | rows=3 | latency=0.421s
------------------------------------------------------------


## Question 43

**Which drugs are known to target EGFR?**

In [151]:

question = 'Which drugs are known to target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 7

   drug_name target_name approval_status         mechanism_of_action
0  Erlotinib        EGFR        Approved  Tyrosine kinase inhibition

 Run 1 completed | rows=7 | latency=0.559s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name approval_status         mechanism_of_action
0  Erlotinib        EGFR        Approved  Tyrosine kinase inhibition

 Run 2 completed | rows=6 | latency=0.572s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name approval_status
0  Cetuximab        EGFR        Approved

 Run 3 completed | rows=5 | latency=0.467s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 5

    drug_name target_name approval_status         mechanism_of_action
0  Erilotinib        EGFR        Approved  Tyrosine kinase inhibition

 Run 4 completed | rows=5 | latency=0.530s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are known to target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name target_name approval_status
0  Erlotinib        EGFR        Approved

 Run 5 completed | rows=6 | latency=0.476s
------------------------------------------------------------


## Question 44

**Which diseases are linked to the TP53?**

In [152]:

question = 'Which diseases are linked to the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 6

  gene_name          disease_name
0      TP53  Li-Fraumeni Syndrome

 Run 1 completed | rows=6 | latency=0.395s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 2 completed | rows=5 | latency=0.394s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 3 completed | rows=5 | latency=0.372s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 6

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 4 completed | rows=6 | latency=0.382s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the TP53?
  Attempt 1/3
Entries retrieved: 7

  gene_name          disease_name
0      TP53  Li-Fraumeni syndrome

 Run 5 completed | rows=7 | latency=0.410s
------------------------------------------------------------


## Question 45

**Which diseases are associated with FGFR2?**

In [153]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 1 completed | rows=8 | latency=0.562s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 2 completed | rows=8 | latency=0.551s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 3 completed | rows=8 | latency=0.499s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 8

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 4 completed | rows=8 | latency=0.494s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 9

  gene_name      disease_name
0     FGFR2  Crouzon Syndrome

 Run 5 completed | rows=9 | latency=0.695s
------------------------------------------------------------


## Question 46

**Which diseases are linked to the HTT?**

In [154]:

question = 'Which diseases are linked to the HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 1 completed | rows=1 | latency=0.319s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 2 completed | rows=1 | latency=0.352s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 3 completed | rows=1 | latency=0.314s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 4 completed | rows=1 | latency=0.317s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are linked to the HTT?
  Attempt 1/3
Entries retrieved: 1

  gene_name          disease_name
0       HTT  Huntington's disease

 Run 5 completed | rows=1 | latency=0.313s
------------------------------------------------------------


## Question 47

**Which genes are associated with breast cancer?**

In [155]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 6

  gene_name
0     BRCA1

 Run 1 completed | rows=6 | latency=0.330s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 6

  gene_name
0     BRCA1

 Run 2 completed | rows=6 | latency=0.347s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 7

  gene_name
0     BRCA1

 Run 3 completed | rows=7 | latency=0.332s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name
0     BRCA1

 Run 4 completed | rows=5 | latency=0.350s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name
0     BRCA1

 Run 5 completed | rows=5 | latency=0.339s
------------------------------------------------------------


## Question 48

**Which genes are associated with colorectal cancer?**

In [156]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name       disease_name
0      TP53  Colorectal Cancer

 Run 1 completed | rows=5 | latency=0.355s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

  gene_name
0      TP53

 Run 2 completed | rows=5 | latency=0.330s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 7

  gene_name
0      TP53

 Run 3 completed | rows=7 | latency=0.329s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 1

                               gene_name
TP53 APC KRAS NRAS BRAF PIK3CA     SMAD4

 Run 4 completed | rows=1 | latency=0.363s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 6

  gene_name
0      TP53

 Run 5 completed | rows=6 | latency=0.346s
------------------------------------------------------------


## Question 49

**What genes are linked to cystic fibrosis?**

In [157]:

question = 'What genes are linked to cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name
0      CFTR

 Run 1 completed | rows=1 | latency=0.381s
------------------------------------------------------------

 Starting run 2 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic Fibrosis

 Run 2 completed | rows=1 | latency=0.316s
------------------------------------------------------------

 Starting run 3 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name
0      CFTR

 Run 3 completed | rows=1 | latency=0.281s
------------------------------------------------------------

 Starting run 4 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      Cftr  Cystic Fibrosis

 Run 4 completed | rows=1 | latency=0.336s
------------------------------------------------------------

 Starting run 5 for query: What genes are linked to cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name
0      CFTR

 Run 5 completed | rows=1 | latency=0.278s
------------------------------------------------------------


## Question 50

**What drugs are used in glioblastoma?**

In [158]:

question = 'What drugs are used in glioblastoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 4

      drug_name  disease_name approval_status
0  Temozolomide  Glioblastoma        Approved

 Run 1 completed | rows=4 | latency=0.444s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 5

      drug_name  disease_name approval_status
0  Temozolomide  Glioblastoma        Approved

 Run 2 completed | rows=5 | latency=0.463s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 5

      drug_name  disease_name approval_status
0  Temozolomide  Glioblastoma        Approved

 Run 3 completed | rows=5 | latency=0.455s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 6

      drug_name  disease_name approval_status
0  Temozolomide  Glioblastoma        Approved

 Run 4 completed | rows=6 | latency=0.513s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used in glioblastoma?
  Attempt 1/3
Entries retrieved: 5

      drug_name  disease_name approval_status
0  Temozolomide  Glioblastoma        Approved

 Run 5 completed | rows=5 | latency=0.488s
------------------------------------------------------------


## Question 51

**Which diseases are treated by metformin?**

In [159]:

question = 'Which diseases are treated by metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name     disease_name approval_status
0  Metformin  Type 2 Diabetes        Approved

 Run 1 completed | rows=2 | latency=0.365s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 3

   drug_name     disease_name approval_status
0  Metformin  Type 2 Diabetes        Approved

 Run 2 completed | rows=3 | latency=0.392s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 3

   drug_name     disease_name approval_status
0  Metformin  Type 2 Diabetes        Approved

 Run 3 completed | rows=3 | latency=0.376s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 2

   drug_name     disease_name
0  Metformin  Type 2 Diabetes

 Run 4 completed | rows=2 | latency=0.350s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated by metformin?
  Attempt 1/3
Entries retrieved: 3

   drug_name     disease_name approval_status
0  Metformin  Type 2 Diabetes        Approved

 Run 5 completed | rows=3 | latency=0.360s
------------------------------------------------------------


## Question 52

**What conditions is adalimumab used for?**

In [160]:

question = 'What conditions is adalimumab used for?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 1 completed | rows=8 | latency=0.481s
------------------------------------------------------------

 Starting run 2 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name approval_status
0  Adalimumab  Rheumatoid Arthritis        Approved

 Run 2 completed | rows=8 | latency=0.577s
------------------------------------------------------------

 Starting run 3 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name approval_status
0  Adalimumab  Rheumatoid Arthritis        Approved

 Run 3 completed | rows=8 | latency=0.535s
------------------------------------------------------------

 Starting run 4 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

           disease_name   drug_name approval_status
0  Rheumatoid Arthritis  Adalimumab        Approved

 Run 4 completed | rows=8 | latency=0.488s
------------------------------------------------------------

 Starting run 5 for query: What conditions is adalimumab used for?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid Arthritis

 Run 5 completed | rows=8 | latency=0.468s
------------------------------------------------------------


## Question 53

**Which diseases are pembrolizumab used in?**

In [161]:

question = 'Which diseases are pembrolizumab used in?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 12

       drug_name disease_name approval_status
0  Pembrolizumab     Melanoma        Approved

 Run 1 completed | rows=12 | latency=0.598s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name approval_status
0  Pembrolizumab     Melanoma        Approved

 Run 2 completed | rows=11 | latency=0.598s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 9

       drug_name disease_name approval_status
0  Pembrolizumab     Melanoma        Approved

 Run 3 completed | rows=9 | latency=0.509s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 11

  disease_name      drug_name approval_status
0     Melanoma  Pembrolizumab        Approved

 Run 4 completed | rows=11 | latency=0.717s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are pembrolizumab used in?
  Attempt 1/3
Entries retrieved: 11

       drug_name disease_name approval_status
0  Pembrolizumab     Melanoma        Approved

 Run 5 completed | rows=11 | latency=0.590s
------------------------------------------------------------


## Question 54

**Which diseases are treated with sorafenib?**

In [162]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name          disease_name approval_status
0  Sorafenib  Renal Cell Carcinoma        Approved

 Run 1 completed | rows=3 | latency=0.433s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name approval_status
0  Sorafenib  Hepatocellular Carcinoma        Approved

 Run 2 completed | rows=3 | latency=0.421s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name approval_status
0  Sorafenib  Hepatocellular Carcinoma        Approved

 Run 3 completed | rows=3 | latency=0.386s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name          disease_name approval_status
0  Sorafenib  Renal Cell Carcinoma        Approved

 Run 4 completed | rows=3 | latency=0.383s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

           disease_name  drug_name approval_status
0  Renal Cell Carcinoma  Sorafenib        Approved

 Run 5 completed | rows=3 | latency=0.422s
------------------------------------------------------------


## Question 55

**What diseases are treated with nivolumab?**

In [163]:

question = 'What diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

  disease_name  drug_name approval_status
0     Melanoma  Nivolumab        Approved

 Run 1 completed | rows=9 | latency=0.583s
------------------------------------------------------------

 Starting run 2 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 10

   drug_name disease_name approval_status
0  Nivolumab     Melanoma        Approved

 Run 2 completed | rows=10 | latency=0.630s
------------------------------------------------------------

 Starting run 3 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

   drug_name disease_name approval_status
0  Nivolumab     Melanoma        Approved

 Run 3 completed | rows=9 | latency=0.539s
------------------------------------------------------------

 Starting run 4 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

  disease_name  drug_name approval_status
0     Melanoma  Nivolumab        Approved

 Run 4 completed | rows=8 | latency=0.518s
------------------------------------------------------------

 Starting run 5 for query: What diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 9

   drug_name disease_name approval_status
0  Nivolumab     Melanoma        Approved

 Run 5 completed | rows=9 | latency=0.582s
------------------------------------------------------------


## Question 56

**Genes linked to multiple sclerosis.**

In [164]:

question = 'Genes linked to multiple sclerosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 7

  gene_name
0  HLA-DRB1

 Run 1 completed | rows=7 | latency=0.396s
------------------------------------------------------------

 Starting run 2 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 9

  gene_name
0     IL2RA

 Run 2 completed | rows=9 | latency=0.453s
------------------------------------------------------------

 Starting run 3 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0     IL2RA

 Run 3 completed | rows=5 | latency=0.369s
------------------------------------------------------------

 Starting run 4 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 1

                                                                            gene_name
IL2RA IL7R TNF TBX21 CD6 PTPRC CD40 IL12B IL12RB1 CTLA4 STAT3 CLEC16A tagap      RGS1

 Run 4 completed | rows=1 | latency=0.576s
------------------------------------------------------------

 Starting run 5 for query: Genes linked to multiple sclerosis.
  Attempt 1/3
Entries retrieved: 5

  gene_name
0  HLA-DRB1

 Run 5 completed | rows=5 | latency=60.918s
------------------------------------------------------------


## Question 57

**Provide target names for rheumatoid arthritis.**

In [165]:

question = 'Provide target names for rheumatoid arthritis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 3

  target_name
0   TNF-alpha

 Run 1 completed | rows=3 | latency=0.315s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 4

  target_name
0   TNF-alpha

 Run 2 completed | rows=4 | latency=0.333s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 4

  target_name
0   TNF-alpha

 Run 3 completed | rows=4 | latency=0.361s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0   TNF-alpha

 Run 4 completed | rows=5 | latency=0.355s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for rheumatoid arthritis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0       TNF-α

 Run 5 completed | rows=5 | latency=0.367s
------------------------------------------------------------


## Question 58

**What are the targets of abatacept?**

In [166]:

question = 'What are the targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name
0  Abatacept        CD80

 Run 1 completed | rows=2 | latency=0.290s
------------------------------------------------------------

 Starting run 2 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name              mechanism_of_action
0  Abatacept        CD80  Inhibition of T-cell activation

 Run 2 completed | rows=2 | latency=0.470s
------------------------------------------------------------

 Starting run 3 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name              mechanism_of_action
0  abatacept        CD80  Inhibition of T-cell activation

 Run 3 completed | rows=2 | latency=0.344s
------------------------------------------------------------

 Starting run 4 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name              mechanism_of_action
0  Abatacept        CD80  Inhibition of T-cell activation

 Run 4 completed | rows=2 | latency=0.387s
------------------------------------------------------------

 Starting run 5 for query: What are the targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name target_name         mechanism_of_action
0  abatacept        CD80  inhibits T-cell activation

 Run 5 completed | rows=2 | latency=0.368s
------------------------------------------------------------


## Question 59

**Provide target names for lung cancer.**

In [167]:

question = 'Provide target names for lung cancer.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 6

  target_name
0        EGFR

 Run 1 completed | rows=6 | latency=0.370s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 6

  target_name
0        EGFR

 Run 2 completed | rows=6 | latency=0.356s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 7

  target_name
0        EGFR

 Run 3 completed | rows=7 | latency=0.373s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 6

  target_name
0        EGFR

 Run 4 completed | rows=6 | latency=0.354s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for lung cancer.
  Attempt 1/3
Entries retrieved: 5

  target_name
0        EGFR

 Run 5 completed | rows=5 | latency=0.315s
------------------------------------------------------------


## Question 60

**What are the known targets of ponatinib?**

In [168]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 5

   drug_name target_name         mechanism_of_action
0  Ponatinib        ABL1  Tyrosine kinase inhibition

 Run 1 completed | rows=5 | latency=0.427s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 11

   drug_name target_name         mechanism_of_action
0  Ponatinib        ABL1  Tyrosine kinase inhibition

 Run 2 completed | rows=11 | latency=0.589s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 16

   drug_name target_name
0  Ponatinib        ABL1

 Run 3 completed | rows=16 | latency=0.553s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 12

   drug_name target_name         mechanism_of_action
0  Ponatinib        ABL1  Tyrosine kinase inhibition

 Run 4 completed | rows=12 | latency=0.675s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 14

   drug_name target_name gene_name         mechanism_of_action
0  Ponatinib        ABL1      ABL1  Tyrosine kinase inhibition

 Run 5 completed | rows=14 | latency=0.817s
------------------------------------------------------------


## Question 61

**Which drugs are used for systemic lupus erythematosus?**

In [169]:

question = 'Which drugs are used for systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

   drug_name                  disease_name approval_status
0  Belimumab  Systemic Lupus Erythematosus        Approved

 Run 1 completed | rows=6 | latency=0.489s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 3

            drug_name                  disease_name approval_status
0  Hydroxychloroquine  Systemic Lupus Erythematosus        Approved

 Run 2 completed | rows=3 | latency=0.413s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 3

   drug_name                  disease_name approval_status
0  Belimumab  Systemic Lupus Erythematosus        Approved

 Run 3 completed | rows=3 | latency=0.405s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

   drug_name approval_status                  disease_name
0  Belimumab        Approved  Systemic Lupus Erythematosus

 Run 4 completed | rows=6 | latency=0.497s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used for systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

   drug_name                  disease_name approval_status
0  Belimumab  Systemic Lupus Erythematosus        Approved

 Run 5 completed | rows=6 | latency=0.497s
------------------------------------------------------------


## Question 62

**Genes associated with autism spectrum disorder.**

In [170]:

question = 'Genes associated with autism spectrum disorder.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 10

  gene_name              disease_name
0    SHANK3  Autism Spectrum Disorder

 Run 1 completed | rows=10 | latency=0.507s
------------------------------------------------------------

 Starting run 2 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 10

  gene_name              disease_name
0    SHANK3  Autism Spectrum Disorder

 Run 2 completed | rows=10 | latency=0.559s
------------------------------------------------------------

 Starting run 3 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 79

  gene_name
0    SHANK3

 Run 3 completed | rows=79 | latency=1.845s
------------------------------------------------------------

 Starting run 4 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 10

  gene_name              disease_name
0    SHANK3  Autism Spectrum Disorder

 Run 4 completed | rows=10 | latency=0.509s
------------------------------------------------------------

 Starting run 5 for query: Genes associated with autism spectrum disorder.
  Attempt 1/3
Entries retrieved: 6

  gene_name              disease_name
0    SHANK3  Autism Spectrum Disorder

 Run 5 completed | rows=6 | latency=0.397s
------------------------------------------------------------


## Question 63

**Diseases associated with the gene ROS1.**

In [171]:

question = 'Diseases associated with the gene ROS1.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 3

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 1 completed | rows=3 | latency=0.346s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 2 completed | rows=5 | latency=0.425s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 6

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 3 completed | rows=6 | latency=0.484s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 5

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 4 completed | rows=5 | latency=0.425s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ROS1.
  Attempt 1/3
Entries retrieved: 6

  gene_name                disease_name
0      ROS1  Non-Small Cell Lung Cancer

 Run 5 completed | rows=6 | latency=0.436s
------------------------------------------------------------


## Question 64

**Diseases associated with the gene ALK.**

In [172]:

question = 'Diseases associated with the gene ALK.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 1 completed | rows=3 | latency=0.367s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 2 completed | rows=3 | latency=0.329s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 3 completed | rows=3 | latency=0.370s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 4 completed | rows=3 | latency=0.353s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene ALK.
  Attempt 1/3
Entries retrieved: 3

  gene_name                    disease_name
0       ALK  Anaplastic Large Cell Lymphoma

 Run 5 completed | rows=3 | latency=0.350s
------------------------------------------------------------


## Question 65

**Diseases associated with the gene EGFR.**

In [173]:

question = 'Diseases associated with the gene EGFR.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      EGFR  Lung Cancer

 Run 1 completed | rows=4 | latency=0.355s
------------------------------------------------------------

 Starting run 2 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      EGFR  Lung Cancer

 Run 2 completed | rows=4 | latency=0.411s
------------------------------------------------------------

 Starting run 3 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      EGFR  Lung Cancer

 Run 3 completed | rows=4 | latency=0.344s
------------------------------------------------------------

 Starting run 4 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

  gene_name                disease_name
0      EGFR  Non-Small Cell Lung Cancer

 Run 4 completed | rows=4 | latency=0.422s
------------------------------------------------------------

 Starting run 5 for query: Diseases associated with the gene EGFR.
  Attempt 1/3
Entries retrieved: 4

  gene_name                disease_name
0      EGFR  Non-Small Cell Lung Cancer

 Run 5 completed | rows=4 | latency=0.375s
------------------------------------------------------------


## Question 66

**Provide target names for psoriasis.**

In [174]:

question = 'Provide target names for psoriasis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 3

  target_name
0   TNF-alpha

 Run 1 completed | rows=3 | latency=0.308s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 3

  target_name
0   TNF-alpha

 Run 2 completed | rows=3 | latency=0.325s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 4

  target_name
0      IL-17A

 Run 3 completed | rows=4 | latency=0.337s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 3

  target_name
0   TNF-alpha

 Run 4 completed | rows=3 | latency=0.286s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for psoriasis.
  Attempt 1/3
Entries retrieved: 3

  target_name
0   TNF-alpha

 Run 5 completed | rows=3 | latency=0.273s
------------------------------------------------------------


## Question 67

**Provide target names for ulcerative colitis.**

In [175]:

question = 'Provide target names for ulcerative colitis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 5

                   target_name        disease_name
0  Tumor Necrosis Factor-alpha  Ulcerative Colitis

 Run 1 completed | rows=5 | latency=0.455s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 4

                   target_name        disease_name
0  Tumor Necrosis Factor Alpha  Ulcerative Colitis

 Run 2 completed | rows=4 | latency=0.453s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 4

                   target_name        disease_name
0  Tumor Necrosis Factor-alpha  Ulcerative Colitis

 Run 3 completed | rows=4 | latency=0.446s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 5

                   target_name
0  Tumor Necrosis Factor Alpha

 Run 4 completed | rows=5 | latency=0.433s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for ulcerative colitis.
  Attempt 1/3
Entries retrieved: 5

  target_name        disease_name
0   TNF-alpha  Ulcerative Colitis

 Run 5 completed | rows=5 | latency=0.460s
------------------------------------------------------------


## Question 68

**Provide target names for tuberculosis.**

In [176]:

question = 'Provide target names for tuberculosis.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 4

  target_name
0      ESAT-6

 Run 1 completed | rows=4 | latency=0.358s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 7

  target_name
0        dnaG

 Run 2 completed | rows=7 | latency=0.483s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 8

  target_name
0  DNA gyrase

 Run 3 completed | rows=8 | latency=0.580s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 5

  target_name
0  DNA gyrase

 Run 4 completed | rows=5 | latency=0.524s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for tuberculosis.
  Attempt 1/3
Entries retrieved: 6

  target_name
0  DNA gyrase

 Run 5 completed | rows=6 | latency=0.381s
------------------------------------------------------------


## Question 69

**Provide target names for hepatitis C.**

In [177]:

question = 'Provide target names for hepatitis C.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  target_name
0         NS3

 Run 1 completed | rows=3 | latency=0.323s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 4

  target_name
0         NS3

 Run 2 completed | rows=4 | latency=0.357s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 3

  target_name
0      NS3/4A

 Run 3 completed | rows=3 | latency=0.404s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 4

  target_name
0         NS3

 Run 4 completed | rows=4 | latency=0.354s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for hepatitis C.
  Attempt 1/3
Entries retrieved: 4

  target_name
0         NS3

 Run 5 completed | rows=4 | latency=0.319s
------------------------------------------------------------


## Question 70

**Provide target names for Hodgkin lymphoma.**

In [178]:

question = 'Provide target names for Hodgkin lymphoma.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name
0        CD30

 Run 1 completed | rows=3 | latency=0.300s
------------------------------------------------------------

 Starting run 2 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 4

  target_name
0        CD30

 Run 2 completed | rows=4 | latency=0.332s
------------------------------------------------------------

 Starting run 3 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 4

  target_name
0        CD30

 Run 3 completed | rows=4 | latency=0.358s
------------------------------------------------------------

 Starting run 4 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name
0        CD30

 Run 4 completed | rows=3 | latency=0.328s
------------------------------------------------------------

 Starting run 5 for query: Provide target names for Hodgkin lymphoma.
  Attempt 1/3
Entries retrieved: 3

  target_name
0        CD30

 Run 5 completed | rows=3 | latency=0.284s
------------------------------------------------------------


## Question 71

**Which pathways are associated with the TP53?**

In [179]:

question = 'Which pathways are associated with the TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 1 completed | rows=4 | latency=0.371s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name pathway_name
0      TP53   cell cycle

 Run 2 completed | rows=3 | latency=0.378s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 3 completed | rows=4 | latency=0.368s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 4 completed | rows=4 | latency=0.369s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name pathway_name
0      TP53    Apoptosis

 Run 5 completed | rows=3 | latency=0.341s
------------------------------------------------------------


## Question 72

**Which drugs are associated with the ERBB2?**

In [180]:

question = 'Which drugs are associated with the ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 3

     drug_name target_name approval_status
0  Trastuzumab       ERBB2        Approved

 Run 1 completed | rows=3 | latency=0.401s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name approval_status
0  Trastuzumab       ERBB2        Approved

 Run 2 completed | rows=6 | latency=0.529s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name approval_status
0  Trastuzumab       ERBB2        Approved

 Run 3 completed | rows=6 | latency=0.514s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name approval_status
0  Trastuzumab       ERBB2        Approved

 Run 4 completed | rows=6 | latency=0.504s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name target_name approval_status
0  Trastuzumab       ERBB2        Approved

 Run 5 completed | rows=6 | latency=0.528s
------------------------------------------------------------


## Question 73

**Which pathways are associated with the ADRB1 gene?**

In [181]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 1 completed | rows=4 | latency=0.436s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 2 completed | rows=2 | latency=0.374s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 5

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 3 completed | rows=5 | latency=0.454s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 4 completed | rows=3 | latency=0.435s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                            pathway_name
0     ADRB1  Adrenergic signaling in cardiomyocytes

 Run 5 completed | rows=3 | latency=0.384s
------------------------------------------------------------


## Question 74

**Which pathways are associated with the DRD2 gene?**

In [182]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 1 completed | rows=4 | latency=0.421s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 2 completed | rows=3 | latency=0.428s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 3 completed | rows=4 | latency=0.436s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                pathway_name
0      DRD2  Dopamine signaling pathway

 Run 4 completed | rows=4 | latency=0.450s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name          pathway_name
0      DRD2  Dopaminergic synapse

 Run 5 completed | rows=4 | latency=0.420s
------------------------------------------------------------


## Question 75

**Which pathways are associated with the HTR2A gene?**

In [183]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name          pathway_name
0     HTR2A  Serotonergic synapse

 Run 1 completed | rows=4 | latency=0.468s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 2 completed | rows=3 | latency=0.395s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 3 completed | rows=2 | latency=0.337s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name         pathway_name
0     HTR2A  Serotonin Signaling

 Run 4 completed | rows=3 | latency=0.384s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0     HTR2A  Serotonin signaling pathway

 Run 5 completed | rows=4 | latency=0.400s
------------------------------------------------------------


## Question 76

**Which drugs are associated with the CD19 gene?**

In [184]:

question = 'Which drugs are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 7

          drug_name target_name gene_name approval_status mechanism_of_action
0  Tisagenlecleucel        CD19      CD19        Approved  CAR T cell therapy

 Run 1 completed | rows=7 | latency=0.720s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 4

          drug_name gene_name                       mechanism_of_action
0  Tisagenlecleucel      CD19  Antibody-dependent cellular cytotoxicity

 Run 2 completed | rows=4 | latency=0.596s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 5

          drug_name gene_name mechanism_of_action approval_status
0  Tisagenlecleucel      CD19  CAR T-cell therapy        Approved

 Run 3 completed | rows=5 | latency=0.594s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 4

          drug_name target_name gene_name approval_status
0  Tisagenlecleucel        CD19      CD19        Approved

 Run 4 completed | rows=4 | latency=0.540s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 3

          drug_name target_name gene_name approval_status mechanism_of_action
0  Tisagenlecleucel        CD19      CD19        Approved  CAR T cell therapy

 Run 5 completed | rows=3 | latency=0.498s
------------------------------------------------------------


## Question 77

**Which drugs are associated with the CTLA4 gene?**

In [185]:

question = 'Which drugs are associated with the CTLA4 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ipilimumab,CTLA-4,CTLA4,inhibition of T-cell activation,Approved

 Run 1 completed | rows=2 | latency=0.422s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ipilimumab,CTLA-4,CTLA4,Inhibition of T-cell activation,Approved

 Run 2 completed | rows=2 | latency=0.492s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Ipilimumab,CTLA-4,CTLA4,Approved,Inhibition of T-cell activation

 Run 3 completed | rows=2 | latency=1.807s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ipilimumab,CTLA-4,CTLA4,Immune checkpoint inhibition,Approved

 Run 4 completed | rows=2 | latency=0.410s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the CTLA4 gene?
  Attempt 1/3
Entries retrieved: 2

    drug_name target_name gene_name           mechanism_of_action
0  Ipilimumab      CTLA-4     CTLA4  Immune checkpoint inhibition

 Run 5 completed | rows=2 | latency=0.382s
------------------------------------------------------------


## Question 78

**Which drugs are associated with the BTK gene?**

In [186]:

question = 'Which drugs are associated with the BTK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ibrutinib,Bruton's tyrosine kinase,BTK,Covalent inhibition,Approved

 Run 1 completed | rows=5 | latency=0.693s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Ibrutinib,Bruton's Tyrosine Kinase,BTK,Approved,Covalent inhibition

 Run 2 completed | rows=5 | latency=0.595s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Ibrutinib,Bruton's Tyrosine Kinase,BTK,Approved,Covalent inhibition

 Run 3 completed | rows=4 | latency=0.587s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,mechanism_of_action,approval_status
0,Ibrutinib,Bruton's tyrosine kinase,BTK,Covalent inhibition,Approved

 Run 4 completed | rows=5 | latency=1.711s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the BTK gene?
  Attempt 1/3
Entries retrieved: 5

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Ibrutinib,Bruton's Tyrosine Kinase,BTK,Approved,Covalent inhibition

 Run 5 completed | rows=5 | latency=0.639s
------------------------------------------------------------


## Question 79

**Which drugs are associated with the SYK gene?**

In [187]:

question = 'Which drugs are associated with the SYK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Fostamatinib,Spleen Tyrosine Kinase,SYK,Approved,Tyrosine kinase inhibition

 Run 1 completed | rows=4 | latency=0.622s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 4

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Fostamatinib,SYK,SYK,Approved,Spleen tyrosine kinase inhibition

 Run 2 completed | rows=4 | latency=0.713s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 2

,drug_name,gene_name,target_name,mechanism_of_action,approval_status
0,Fostamatinib,SYK,Spleen tyrosine kinase,Inhibition,Approved

 Run 3 completed | rows=2 | latency=0.474s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 3

      drug_name gene_name approval_status
0  Fostamatinib       SYK        Approved

 Run 4 completed | rows=3 | latency=0.448s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are associated with the SYK gene?
  Attempt 1/3
Entries retrieved: 1

,drug_name,target_name,gene_name,approval_status,mechanism_of_action
0,Fostamatinib,SYK,SYK,Approved,Spleen tyrosine kinase inhibition

 Run 5 completed | rows=1 | latency=0.395s
------------------------------------------------------------


## Question 80

**Which pathways are associated with TP53?**

In [188]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await return_llama_answer(question)
            latency = time.perf_counter() - start_time

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 1 completed | rows=4 | latency=0.363s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 2 completed | rows=4 | latency=0.425s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 3 completed | rows=4 | latency=0.397s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 4 completed | rows=4 | latency=0.390s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 4

  gene_name pathway_name
0      TP53    Apoptosis

 Run 5 completed | rows=4 | latency=0.389s
------------------------------------------------------------

##### Store as .pkl and json

In [ ]:
# import pickle
# with open("Llama_same_question_response.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

# import json
# import pandas as pd

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("Llama_same_question_response.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )