In [1]:
import sys
sys.path.append("../")

##### import library

In [2]:
from typing import List, Optional
import requests
import pandas as pd
import mygene
import utility
import importlib
importlib.reload(utility)
from utility import resolve_ensembl_ids_with_fallback, get_chembl_ids_fast,  get_disease_ids_fast, validate_id_dataframe
import pickle

In [3]:
dct_result = dict()

##### Read pickle

In [4]:
with open("TTD_same_question_response_final.pkl", "rb") as f:
    TTD_same_question_response = pickle.load(f)

In [5]:
for model in ['llama-3.3-70b-versatile', 'gpt-5-nano', 'grok-4-1-fast-non-reasoning-latest', "gemini-2.5-flash-lite", "OpenTarget", "BioChatter", "ctd", "ttd", "hcdt"]:

    
    # if model=="llama-3.3-70b-versatile":
    #     dct_result[model] = Llama_same_question_response[model]

    # if model=="gpt-5-nano":
    #     dct_result[model] = OpenAI_same_question_response[model]

    # if model=='grok-4-1-fast-non-reasoning-latest':
    #     dct_result[model] = Grok_same_question_response[model]

    # if model=="gemini-2.5-flash-lite":
    #     dct_result[model] = Gemini_same_question_response[model]

    # if model=="OpenTarget":
    #     dct_result[model] = Opentarget_same_question_response[model]

    # if model=="BioChatter":
    #     dct_result[model] = Biochatter_same_question_response[model]

    # if model=="ctd":
    #     dct_result[model] = CTD_same_question_response[model]

    # if model=="hcdt":
    #     dct_result[model] = HCDT_same_question_response[model]

    if model=="ttd":
        dct_result[model] = TTD_same_question_response[model]

##### Verify if only valid columns are present

In [6]:
allowed = {"gene_name", "drug_name", "disease_name", "pathway_name", "target_name"}

missing_df = []
not_dataframe = []
empty_df = []
bad_columns = []

total_payloads = 0

for model, queries in dct_result.items():
    if not isinstance(queries, dict):
        continue

    for question, runs in queries.items():
        if not isinstance(runs, dict):
            continue

        for run_id, payload in runs.items():
            total_payloads += 1

            if not isinstance(payload, dict) or "dataframe" not in payload:
                missing_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "payload_type": type(payload).__name__
                })
                continue

            df = payload.get("dataframe")

            if not isinstance(df, pd.DataFrame):
                not_dataframe.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "df_type": type(df).__name__
                })
                continue

            if df.empty:
                empty_df.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns)
                })

            cols = {str(c) for c in df.columns}
            extra = sorted(cols - allowed)

            if extra:
                bad_columns.append({
                    "model": model,
                    "question": question,
                    "run_id": run_id,
                    "columns": list(df.columns),
                    "extra_columns": extra
                })

print(f"Total payloads checked: {total_payloads}")
print(f"Missing dataframe key: {len(missing_df)}")
print(f"Dataframe is not pd.DataFrame: {len(not_dataframe)}")
print(f"Empty dataframes: {len(empty_df)}")
print(f"Dataframes with disallowed columns: {len(bad_columns)}")

bad_columns_df = pd.DataFrame(bad_columns)
missing_df_df = pd.DataFrame(missing_df)
not_dataframe_df = pd.DataFrame(not_dataframe)
empty_df_df = pd.DataFrame(empty_df)

display(bad_columns_df)
display(missing_df_df)
display(not_dataframe_df)
display(empty_df_df)

Total payloads checked: 324
Missing dataframe key: 0
Dataframe is not pd.DataFrame: 0
Empty dataframes: 0
Dataframes with disallowed columns: 0

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [7]:
# rows_missing_parentheses = []

# dct_jaccard = dict()

# for model, queries in dct_result.items():
#     dct_jaccard[model] = {}
#     print(f"\nWorking for model: {model}")

#     for question, runs in queries.items():

#         for run_id, payload in runs.items():
#             df = payload.get("dataframe")

#             # ---- validation ----
#             if not isinstance(df, pd.DataFrame) or df.empty:
#                 continue

#             # ---- skip pathway outputs ----
#             if "pathway_name" in df.columns:
#                 continue

#             # ---- column sanity ----
#             # if not set(df.columns).issubset(allowed_cols):
#             #     continue

#             # ======================================================
#             # CHECK ONLY target_name COLUMN
#             # ======================================================
#             if "target_name" in df.columns:

#                 mask = ~df["target_name"].astype(str).str.contains(
#                     r"\(.*\)", regex=True, na=False
#                 )

#                 if mask.any():
#                     bad_rows = df.loc[mask, "gene_name"]

#                     for idx, value in bad_rows.items():
#                         rows_missing_parentheses.append({
#                             "model": model,
#                             "question": question,
#                             "run_id": run_id,
#                             "row_index": idx,
#                             "value": value,
#                         })

In [8]:
rows_missing_parentheses = []

question_entities = {
    "gene_name": set(),
    "drug_name": set(),
    "disease_name": set(),
    "target_name": set(),
}

allowed_cols = {"gene_name", "drug_name", "disease_name", "target_name"}

for model, queries in dct_result.items():
    print(f"\nWorking for model: {model}")

    for question, runs in queries.items():
        for run_id, payload in runs.items():
            df = payload.get("dataframe")

            if not isinstance(df, pd.DataFrame) or df.empty:
                continue
            if "pathway_name" in df.columns:
                continue
            if not set(df.columns).issubset(allowed_cols):
                continue

            if "target_name" in df.columns:
                t = df["target_name"].astype("string")

                # validate only non-null rows
                bad_mask = t.notna() & ~t.str.contains(r"\([^()]+\)", regex=True)
                if bad_mask.any():
                    bad_rows = t[bad_mask].tolist()
                    raise ValueError(
                        f"target_name rows without parentheses: {bad_rows}"
                    )

                extracted_gene = t.str.extract(r"\(([^()]+)\)", expand=False).str.strip()

                # mutate original df in dict
                if "gene_name" in df.columns:
                    df["gene_name"] = df["gene_name"].astype("string").fillna(extracted_gene)
                else:
                    df["gene_name"] = extracted_gene

                if "gene_name" not in df.columns:
                    print("Issue found")

                # optional: if you want only normalized gene_name
                # df.drop(columns=["target_name"], inplace=True)

            for col in allowed_cols:
                if col in df.columns:
                    vals = df[col].dropna().astype(str).str.strip()
                    question_entities[col].update(v for v in vals if v)

# sets -> sorted lists
for k in question_entities:
    question_entities[k] = sorted(question_entities[k])

Working for model: ttd

##### Associate id with all gene entry

In [9]:
# Resolve unique gene symbols to IDs (MyGene -> OpenTargets fallback).
df_gene = resolve_ensembl_ids_with_fallback(
    list(question_entities["gene_name"]),
    use_opentargets_fallback=True,
)
df_gene = df_gene.drop_duplicates(subset=["gene_name", "gene_id"]).reset_index(drop=True)
df_gene

2026-02-27 18:50:55,679 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:50:55,680 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:50:55,681 [INFO] querying 1-757 ...
2026-02-27 18:50:57,820 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 18:50:58,824 [INFO] Finished.
2026-02-27 18:50:58,924 [WARNING] 1 input query terms found dup hits:	[('GLRA4', 2)]
2026-02-27 18:50:58,924 [WARNING] 53 input query terms found no hit:	['ABL', 'APH1A-APH1B', 'BCR-ABL1', 'BACT FIMH', 'BACT FOLK', 'BACT FOLP', 'BACT GYRA', 'BACT GYRB',
2026-02-27 18:50:58,930 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:50:58,931 [WARNING] Input sequence provided is already in string format. No operation performed
2026-02-27 18:50:58,931 [INFO] querying 1-32 ...
2026-02-27 18:50:59,228 [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-02-27 18:51:00,230 [INFO] Finished.
2026-02-27 18:51:00,233 [WARNING] 1 input query terms found dup hits:	[('HIV TAT', 10)]
2026-02-27 18:51:00,234 [WARNING] 31 input query terms found no hit:	['BACT FIMH', 'BACT FOLK', 'BACT FOLP', 'BACT GYRA', 'BACT GYRB', 'BACT INHA', 'CANDI TMP1', 'DENV E

[warn] Could not resolve 'APH1A-APH1B' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'BCR-ABL1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Bact FimH' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Bact folK' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Bact folP' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Bact gyrA' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Bact gyrB' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Bact inhA' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'CHRNA4-CHRNB2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Candi TMP1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'DENV E' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'EGFR Exon20ins' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'EGFR T790M' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'EGFR vIII' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'FUN1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Fung GSC2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'HER2 mRNA' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'HIV RT' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Hepatitis A virus HAVCR2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ITGA2-ITGB1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ITGA4-ITGB1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ITGA4-ITGB7' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ITGA5-ITGB1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'ITGAV-ITGB3' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MTOR-RPTORA-MLST8-KT1S1-DEPTOR' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Malaria DHOdehase' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'McyB dprE1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MeV F' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB alr' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB antigens' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB cmaA1' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB cmaA2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB ddl' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB embC' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB leuS' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB mmpL3' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB pcaA' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'MycB pssA' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'NIE' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Pseudo pcrV' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Stap-coc parC' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'Stap-coc pbp2' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.
[warn] Could not resolve 'qcrB' via MyGene or OpenTargets. Possible typo or ambiguous gene-family prefix.

    gene_name          gene_id  source
0       AADAT  ENSG00000109576  mygene
1        ABAT  ENSG00000183044  mygene
2       ABCB1  ENSG00000085563  mygene
3       ABCB4  ENSG00000005471  mygene
4       ABCC9  ENSG00000069431  mygene
..        ...              ...     ...
752      WEE1  ENSG00000166483  mygene
753       WT1  ENSG00000184937  mygene
754      XIAP  ENSG00000101966  mygene
755      XPO1  ENSG00000082898  mygene
756      qcrB              NaN    None

[757 rows x 3 columns]

In [10]:
df_gene[df_gene.isna().any(axis=1)]

                          gene_name gene_id source
37                      APH1A-APH1B     NaN   None
56                         BCR-ABL1     NaN   None
67                        Bact FimH     NaN   None
68                        Bact folK     NaN   None
69                        Bact folP     NaN   None
70                        Bact gyrA     NaN   None
71                        Bact gyrB     NaN   None
72                        Bact inhA     NaN   None
146                   CHRNA4-CHRNB2     NaN   None
185                      Candi TMP1     NaN   None
188                          DENV E     NaN   None
210                  EGFR Exon20ins     NaN   None
211                      EGFR T790M     NaN   None
212                       EGFR vIII     NaN   None
268                            FUN1     NaN   None
269                       Fung GSC2     NaN   None
316                       HER2 mRNA     NaN   None
318                          HIV RT     NaN   None
343        Hepatitis A virus HAVCR2     NaN   None
397                     ITGA2-ITGB1     NaN   None
399                     ITGA4-ITGB1     NaN   None
400                     ITGA4-ITGB7     NaN   None
402                     ITGA5-ITGB1     NaN   None
405                     ITGAV-ITGB3     NaN   None
499  MTOR-RPTORA-MLST8-KT1S1-DEPTOR     NaN   None
502               Malaria DHOdehase     NaN   None
503                      McyB dprE1     NaN   None
504                           MeV F     NaN   None
505                        MycB alr     NaN   None
506                   MycB antigens     NaN   None
507                      MycB cmaA1     NaN   None
508                      MycB cmaA2     NaN   None
509                        MycB ddl     NaN   None
510                       MycB embC     NaN   None
511                       MycB leuS     NaN   None
512                      MycB mmpL3     NaN   None
513                       MycB pcaA     NaN   None
514                       MycB pssA     NaN   None
524                             NIE     NaN   None
611                     Pseudo pcrV     NaN   None
694                   Stap-coc parC     NaN   None
695                   Stap-coc pbp2     NaN   None
756                            qcrB     NaN   None

##### Associate id with all drug entry

In [11]:
# Resolve unique drug surface forms to IDs.
# This keeps original raw names as rows and writes mapped ID + source.
df_drug = await get_chembl_ids_fast(list(question_entities["drug_name"]))
df_drug = df_drug.drop_duplicates(subset=["drug_name", "drug_id"]).reset_index(drop=True)
df_drug

2026-02-27 18:51:41,010 [INFO] [LLM] Total 845 names split into 11 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:51:41,012 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,053 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,058 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,061 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,061 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,062 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,062 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,063 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,063 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,063 [INFO] [LLM] Batch size: 80
2026-02-27 18:51:41,064 [INFO] [LLM] Batch size: 45

[map][drug][OpenTargets] raw='ABBV-154' -> id='CHEMBL5314652'
[map][drug][OpenTargets] raw='ABBV-257' -> id='CHEMBL4297682'
[map][drug][OpenTargets] raw='ABBV-323' -> id='CHEMBL4298212'
[map][drug][OpenTargets] raw='ABBV-951' -> id='CHEMBL4594379'
[map][drug][OpenTargets] raw='ABT-122' -> id='CHEMBL4297863'
[map][drug][OpenTargets] raw='ABT-874' -> id='CHEMBL1742995'
[map][drug][OpenTargets] raw='ADG116' -> id='CHEMBL5315007'
[map][drug][OpenTargets] raw='ADL-5859' -> id='CHEMBL494480'
[map][drug][OpenTargets] raw='ADX-48621' -> id='CHEMBL2346738'
[map][drug][OpenTargets] raw='AFM11' -> id='CHEMBL4297874'
[map][drug][OpenTargets] raw='AG-221' -> id='CHEMBL3989908'
[map][drug][OpenTargets] raw='AGEN1181' -> id='CHEMBL4650435'
[map][drug][OpenTargets] raw='AGEN1884' -> id='CHEMBL4297876'
[map][drug][OpenTargets] raw='AK104' -> id='CHEMBL4594456'
[map][drug][OpenTargets] raw='AKST4290' -> id='CHEMBL3670800'
[map][drug][OpenTargets] raw='ALD-403' -> id='CHEMBL3833320'
[map][drug][OpenTargets] raw='ALD-518' -> id='CHEMBL2108589'
[map][drug][OpenTargets] raw='ALPN-202' -> id='CHEMBL5095305'
[map][drug][OpenTargets] raw='ALX-0061' -> id='CHEMBL3833343'
[map][drug][OpenTargets] raw='AM0010' -> id='CHEMBL3989992'
[map][drug][OpenTargets] raw='AMG 334' -> id='CHEMBL3833329'
[map][drug][OpenTargets] raw='AMG 570' -> id='CHEMBL4650245'
[map][drug][OpenTargets] raw='AMG-139' -> id='CHEMBL3833372'
[map][drug][OpenTargets] raw='AMG-181' -> id='CHEMBL3137351'
[map][drug][OpenTargets] raw='AMG-714' -> id='CHEMBL2109467'
[map][drug][OpenTargets] raw='ANAVEX 2-73' -> id='CHEMBL4297224'
[map][drug][OpenTargets] raw='AP32788' -> id='CHEMBL4650319'
[map][drug][OpenTargets] raw='APD371' -> id='CHEMBL4175981'
[map][drug][OpenTargets] raw='ARRY-380' -> id='CHEMBL3989868'
[map][drug][OpenTargets] raw='ARRY-614' -> id='CHEMBL3991932'
[map][drug][OpenTargets] raw='ART621' -> id='CHEMBL2108739'
[map][drug][OpenTargets] raw='ASP-015K' -> id='CHEMBL3137308'
[map][drug][OpenTargets] raw='ASP8273' -> id='CHEMBL3663929'
[map][drug][OpenTargets] raw='AST-1306' -> id='CHEMBL1947204'
[map][drug][OpenTargets] raw='AVE-9940' -> id='CHEMBL3545117'
[map][drug][OpenTargets] raw='AVT02' -> id='CHEMBL1201580'
[map][drug][OpenTargets] raw='AZD-3241' -> id='CHEMBL4297594'
[map][drug][OpenTargets] raw='AZD-6703' -> id='CHEMBL2031465'
[map][drug][OpenTargets] raw='AZD4769' -> id='CHEMBL422872'
[map][drug][OpenTargets] raw='AZD5672' -> id='CHEMBL1951914'
[map][drug][OpenTargets] raw='AZD8931' -> id='CHEMBL2408045'
[map][drug][OpenTargets] raw='AZD9567' -> id='CHEMBL4207852'
[map][drug][OpenTargets] raw='Abatacept' -> id='CHEMBL1201823'
[map][drug][OpenTargets] raw='Abetimus sodium' -> id='CHEMBL2108835'
[map][drug][OpenTargets] raw='Abrocitinib' -> id='CHEMBL3655081'
[map][drug][OpenTargets] raw='Adalimumab' -> id='CHEMBL1201580'
[map][drug][OpenTargets] raw='Afimetoran' -> id='CHEMBL4650329'
[map][drug][OpenTargets] raw='Aldoxorubicin' -> id='CHEMBL2107818'
[map][drug][OpenTargets] raw='Alicaforsen' -> id='CHEMBL2108326'
[map][drug][OpenTargets] raw='Almogran' -> id='CHEMBL1200521'
[map][drug][OpenTargets] raw='Almonertinib' -> id='CHEMBL4761468'
[map][drug][OpenTargets] raw='Amfepramone' -> id='CHEMBL1194666'
[map][drug][OpenTargets] raw='Amikacin' -> id='CHEMBL177'
[map][drug][OpenTargets] raw='Aminoguanidine' -> id='CHEMBL225304'
[map][drug][OpenTargets] raw='Aminosalicylic Acid' -> id='CHEMBL1169'
[map][drug][OpenTargets] raw='Amiselimod' -> id='CHEMBL3707375'
[map][drug][OpenTargets] raw='Amivantamab' -> id='CHEMBL4297774'
[map][drug][OpenTargets] raw='Anakinra' -> id='CHEMBL1201570'
[map][drug][OpenTargets] raw='Andolast' -> id='CHEMBL119549'
[map][drug][OpenTargets] raw='Anifrolumab' -> id='CHEMBL2364653'
[map][drug][OpenTargets] raw='Anle138b' -> id='CHEMBL4748063'
[map][drug][OpenTargets] raw='Anrukinzumab' -> id='CHEMBL1742985'
[map][drug][OpenTargets] raw='Apomorphine' -> id='CHEMBL53'
[map][drug][OpenTargets] raw='Apratastat' -> id='CHEMBL206815'
[map][drug][OpenTargets] raw='Apricoxib' -> id='CHEMBL1835207'
[map][drug][OpenTargets] raw='Arecoline' -> id='CHEMBL7303'
[map][drug][OpenTargets] raw='Atacicept' -> id='CHEMBL1742986'
[map][drug][OpenTargets] raw='Atogepant' -> id='CHEMBL3991065'
[map][drug][OpenTargets] raw='Axicabtagene ciloleucel' -> id='CHEMBL3989989'
[map][drug][OpenTargets] raw='BCA101' -> id='CHEMBL5095314'
[map][drug][OpenTargets] raw='BDTX-189' -> id='CHEMBL4650279'
[map][drug][OpenTargets] raw='BGC-20-1531' -> id='CHEMBL3260771'
[map][drug][OpenTargets] raw='BI-44370' -> id='CHEMBL3334624'
[map][drug][OpenTargets] raw='BIBW 2992' -> id='CHEMBL1173655'
[map][drug][OpenTargets] raw='BIBX-1382' -> id='CHEMBL258940'
[map][drug][OpenTargets] raw='BIIB014' -> id='CHEMBL447664'
[map][drug][OpenTargets] raw='BIIB054' -> id='CHEMBL3833330'
[map][drug][OpenTargets] raw='BIIB068' -> id='CHEMBL4650450'
[map][drug][OpenTargets] raw='BL-7040' -> id='CHEMBL6068601'
[map][drug][OpenTargets] raw='BMS-599626' -> id='CHEMBL1645462'
[map][drug][OpenTargets] raw='BMS-690514' -> id='CHEMBL3545396'
[map][drug][OpenTargets] raw='BMS-817399' -> id='CHEMBL3334824'
[map][drug][OpenTargets] raw='BMS-986104' -> id='CHEMBL3806158'
[map][drug][OpenTargets] raw='BMS-986142' -> id='CHEMBL3900554'
[map][drug][OpenTargets] raw='BR3-Fc' -> id='CHEMBL2107844'
[map][drug][OpenTargets] raw='BTZ-043' -> id='CHEMBL1822872'
[map][drug][OpenTargets] raw='Balsalazide' -> id='CHEMBL1201346'
[map][drug][OpenTargets] raw='Baminercept' -> id='CHEMBL1742988'
[map][drug][OpenTargets] raw='Baricitinib' -> id='CHEMBL2105759'
[map][drug][OpenTargets] raw='Bedaquiline' -> id='CHEMBL376488'
[map][drug][OpenTargets] raw='Belimumab' -> id='CHEMBL1789843'
[map][drug][OpenTargets] raw='Belumosudil' -> id='CHEMBL2005186'
[map][drug][OpenTargets] raw='Benztropine' -> id='CHEMBL1201203'
[map][drug][OpenTargets] raw='Bertilimumab' -> id='CHEMBL2109103'
[map][drug][OpenTargets] raw='Bevacizumab' -> id='CHEMBL1201583'
[map][drug][OpenTargets] raw='Biperiden' -> id='CHEMBL1101'
[map][drug][OpenTargets] raw='Blinatumomab' -> id='CHEMBL1742992'
[map][drug][OpenTargets] raw='Blisibimod' -> id='CHEMBL2107877'
[map][drug][OpenTargets] raw='Botulinum Toxin Type B' -> id='CHEMBL1201569'
[map][drug][OpenTargets] raw='Branebrutinib' -> id='CHEMBL4297674'
[map][drug][OpenTargets] raw='Brasofensine' -> id='CHEMBL2104184'
[map][drug][OpenTargets] raw='Brazikumab' -> id='CHEMBL3833372'
[map][drug][OpenTargets] raw='Bromocriptine' -> id='CHEMBL493'
[map][drug][OpenTargets] raw='Budipine' -> id='CHEMBL334491'
[map][drug][OpenTargets] raw='Buprenorphine' -> id='CHEMBL511142'
[map][drug][OpenTargets] raw='CART-19' -> id='CHEMBL3301574'
[map][drug][OpenTargets] raw='CC-1088' -> id='CHEMBL88153'
[map][drug][OpenTargets] raw='CC-220' -> id='CHEMBL3989912'
[map][drug][OpenTargets] raw='CC-930' -> id='CHEMBL1950289'
[map][drug][OpenTargets] raw='CCX-354' -> id='CHEMBL4444976'
[map][drug][OpenTargets] raw='CDP-6038' -> id='CHEMBL1743050'
[map][drug][OpenTargets] raw='CDP-7657' -> id='CHEMBL2109478'
[map][drug][OpenTargets] raw='CDP323' -> id='CHEMBL4297363'
[map][drug][OpenTargets] raw='CFZ533' -> id='CHEMBL4298210'
[map][drug][OpenTargets] raw='CG-100649' -> id='CHEMBL166863'
[map][drug][OpenTargets] raw='CH-4051' -> id='CHEMBL4802147'
[map][drug][OpenTargets] raw='CI-1033' -> id='CHEMBL545315'
[map][drug][OpenTargets] raw='CLN-081' -> id='CHEMBL4650281'
[map][drug][OpenTargets] raw='CO-1686' -> id='CHEMBL3545308'
[map][drug][OpenTargets] raw='CP-195543' -> id='CHEMBL301829'
[map][drug][OpenTargets] raw='CP-461' -> id='CHEMBL4243974'
[map][drug][OpenTargets] raw='CP-724714' -> id='CHEMBL483321'
[map][drug][OpenTargets] raw='CP-868596' -> id='CHEMBL2105728'
[map][drug][OpenTargets] raw='CPHPC' -> id='CHEMBL25263'
[map][drug][OpenTargets] raw='CPL-7075' -> id='CHEMBL456341'
[map][drug][OpenTargets] raw='CTL019' -> id='CHEMBL3301574'
[map][drug][OpenTargets] raw='CUDC-101' -> id='CHEMBL598797'
[map][drug][OpenTargets] raw='CUDC-907' -> id='CHEMBL3622533'
[map][drug][OpenTargets] raw='CVN424' -> id='CHEMBL4802203'
[map][drug][OpenTargets] raw='CX-8998' -> id='CHEMBL1684950'
[map][drug][OpenTargets] raw='Cabozantinib' -> id='CHEMBL2105717'
[map][drug][OpenTargets] raw='Canakinumab' -> id='CHEMBL1201834'
[map][drug][OpenTargets] raw='Capreomycin Sulfate' -> id='CHEMBL2218913'
[map][drug][OpenTargets] raw='Carbidopa' -> id='CHEMBL1200748'
[map][drug][OpenTargets] raw='Celecoxib' -> id='CHEMBL118'
[map][drug][OpenTargets] raw='Cenerimod' -> id='CHEMBL4297505'
[map][drug][OpenTargets] raw='Certolizumab' -> id='CHEMBL4297565'
[map][drug][OpenTargets] raw='Cilengitide' -> id='CHEMBL429876'
[map][drug][OpenTargets] raw='Clazakizumab' -> id='CHEMBL2108589'
[map][drug][OpenTargets] raw='Clofazimine' -> id='CHEMBL1292'
[map][drug][OpenTargets] raw='Coltuximab ravtansine' -> id='CHEMBL2109286'
[map][drug][OpenTargets] raw='Cycloserine' -> id='CHEMBL771'
[map][drug][OpenTargets] raw='Cycrimine' -> id='CHEMBL1201227'
[map][drug][OpenTargets] raw='Cyproheptadine' -> id='CHEMBL516'
[map][drug][OpenTargets] raw='DIMS-0150' -> id='CHEMBL5095448'
[map][drug][OpenTargets] raw='DN24-02' -> id='CHEMBL2108615'
[map][drug][OpenTargets] raw='DNL201' -> id='CHEMBL3122113'
[map][drug][OpenTargets] raw='DNL758' -> id='CHEMBL4861471'
[map][drug][OpenTargets] raw='DT-1687' -> id='CHEMBL4089083'
[map][drug][OpenTargets] raw='DZD9008' -> id='CHEMBL5314564'
[map][drug][OpenTargets] raw='Dacomitinib' -> id='CHEMBL2105719'
[map][drug][OpenTargets] raw='Dapirolizumab pegol' -> id='CHEMBL2109478'
[map][drug][OpenTargets] raw='Darolutamide' -> id='CHEMBL4297185'
[map][drug][OpenTargets] raw='Dasatinib' -> id='CHEMBL5416410'
[map][drug][OpenTargets] raw='Daxdilimab' -> id='CHEMBL4594330'
[map][drug][OpenTargets] raw='Dazodalibep' -> id='CHEMBL4594331'
[map][drug][OpenTargets] raw='Declopramide' -> id='CHEMBL1618378'
[map][drug][OpenTargets] raw='Delamanid' -> id='CHEMBL218650'
[map][drug][OpenTargets] raw='Deligoparin sodium' -> id='CHEMBL2109081'
[map][drug][OpenTargets] raw='Denosumab' -> id='CHEMBL1237023'
[map][drug][OpenTargets] raw='Depatuxizumab' -> id='CHEMBL3707294'
[map][drug][OpenTargets] raw='Dersalazine' -> id='CHEMBL2106406'
[map][drug][OpenTargets] raw='Dexamethasone' -> id='CHEMBL384467'
[map][drug][OpenTargets] raw='Dexchlorpheniramine Maleate' -> id='CHEMBL1200927'
[map][drug][OpenTargets] raw='Dihydroergotamine' -> id='CHEMBL1732'
[map][drug][OpenTargets] raw='Donitriptan' -> id='CHEMBL1742428'
[map][drug][OpenTargets] raw='Dopamine' -> id='CHEMBL59'
[map][drug][OpenTargets] raw='Doramapimod' -> id='CHEMBL103667'
[map][drug][OpenTargets] raw='Dotarizine' -> id='CHEMBL2106316'
[map][drug][OpenTargets] raw='Durvalumab' -> id='CHEMBL3301587'
[map][drug][OpenTargets] raw='E-2007' -> id='CHEMBL1214124'
[map][drug][OpenTargets] raw='E2027' -> id='CHEMBL4650368'
[map][drug][OpenTargets] raw='EB8018' -> id='CHEMBL4594305'
[map][drug][OpenTargets] raw='EGF816' -> id='CHEMBL3787344'
[map][drug][OpenTargets] raw='EMB-01' -> id='CHEMBL4594472'
[map][drug][OpenTargets] raw='ERB-041' -> id='CHEMBL450940'
[map][drug][OpenTargets] raw='ETIPREDNOL DICLOACETATE' -> id='CHEMBL2107614'
[map][drug][OpenTargets] raw='Eclitasertib' -> id='CHEMBL4861471'
[map][drug][OpenTargets] raw='Eletriptan' -> id='CHEMBL1510'
[map][drug][OpenTargets] raw='Eltoprazine' -> id='CHEMBL282614'
[map][drug][OpenTargets] raw='Enbrel' -> id='CHEMBL1201572'
[map][drug][OpenTargets] raw='Entacapone' -> id='CHEMBL953'
[map][drug][OpenTargets] raw='Epidermal growth factor' -> id='CHEMBL2108314'
[map][drug][OpenTargets] raw='Epitinib' -> id='CHEMBL5314411'
[map][drug][OpenTargets] raw='Epratuzumab' -> id='CHEMBL2108404'
[map][drug][OpenTargets] raw='Eptinezumab' -> id='CHEMBL3833320'
[map][drug][OpenTargets] raw='Erlotinib' -> id='CHEMBL553'
[map][drug][OpenTargets] raw='Etanercept' -> id='CHEMBL1201572'
[map][drug][OpenTargets] raw='Ethambutol' -> id='CHEMBL44884'
[map][drug][OpenTargets] raw='Ethionamide' -> id='CHEMBL1441'
[map][drug][OpenTargets] raw='Ethopropazine' -> id='CHEMBL1206'
[map][drug][OpenTargets] raw='Ethylene diamine' -> id='CHEMBL816'
[map][drug][OpenTargets] raw='Etoricoxib' -> id='CHEMBL416146'
[map][drug][OpenTargets] raw='Etrasimod' -> id='CHEMBL3358920'
[map][drug][OpenTargets] raw='FENBUFEN' -> id='CHEMBL277522'
[map][drug][OpenTargets] raw='FKB238' -> id='CHEMBL1201583'
[map][drug][OpenTargets] raw='Felbinac' -> id='CHEMBL413965'
[map][drug][OpenTargets] raw='Fenoprofen' -> id='CHEMBL1297'
[map][drug][OpenTargets] raw='Flumatinib' -> id='CHEMBL3545413'
[map][drug][OpenTargets] raw='Flunarizine' -> id='CHEMBL30008'
[map][drug][OpenTargets] raw='Flurbiprofen' -> id='CHEMBL563'
[map][drug][OpenTargets] raw='Fontolizumab' -> id='CHEMBL2108459'
[map][drug][OpenTargets] raw='Forigerimod' -> id='CHEMBL3989409'
[map][drug][OpenTargets] raw='Fosgonimeton' -> id='CHEMBL5095419'
[map][drug][OpenTargets] raw='Fostamatinib' -> id='CHEMBL2103830'
[map][drug][OpenTargets] raw='Frexalimab' -> id='CHEMBL5095122'
[map][drug][OpenTargets] raw='Frovatriptan' -> id='CHEMBL1279'
[map][drug][OpenTargets] raw='Fucose' -> id='CHEMBL6067643'
[map][drug][OpenTargets] raw='GED-0301' -> id='CHEMBL3707383'
[map][drug][OpenTargets] raw='GLPG-0259' -> id='CHEMBL5095028'
[map][drug][OpenTargets] raw='GLPG-0634' -> id='CHEMBL3301607'
[map][drug][OpenTargets] raw='GPI-1485' -> id='CHEMBL4297382'
[map][drug][OpenTargets] raw='GS-4059' -> id='CHEMBL4071161'
[map][drug][OpenTargets] raw='GS-5745' -> id='CHEMBL3833374'
[map][drug][OpenTargets] raw='GSK2330811' -> id='CHEMBL6068608'
[map][drug][OpenTargets] raw='GSK2982772' -> id='CHEMBL4071864'
[map][drug][OpenTargets] raw='GSK3117391' -> id='CHEMBL4297494'
[map][drug][OpenTargets] raw='GSK3179106' -> id='CHEMBL3355009'
[map][drug][OpenTargets] raw='GSK3196165' -> id='CHEMBL2109433'
[map][drug][OpenTargets] raw='GTS-21' -> id='CHEMBL134713'
[map][drug][OpenTargets] raw='Gefitinib' -> id='CHEMBL939'
[map][drug][OpenTargets] raw='Golimumab' -> id='CHEMBL1201833'
[map][drug][OpenTargets] raw='Gpi-1046' -> id='CHEMBL6367'
[map][drug][OpenTargets] raw='HKI-272' -> id='CHEMBL180022'
[map][drug][OpenTargets] raw='HM71224' -> id='CHEMBL4163691'
[map][drug][OpenTargets] raw='HMPL-004' -> id='CHEMBL186141'
[map][drug][OpenTargets] raw='Hydroxyurea' -> id='CHEMBL467'
[map][drug][OpenTargets] raw='IB-MECA' -> id='CHEMBL3989873'
[map][drug][OpenTargets] raw='ICLUSIG' -> id='CHEMBL1171837'
[map][drug][OpenTargets] raw='IDEC-151' -> id='CHEMBL2108187'
[map][drug][OpenTargets] raw='IL-18BP' -> id='CHEMBL2108054'
[map][drug][OpenTargets] raw='IMO-8400' -> id='CHEMBL4297995'
[map][drug][OpenTargets] raw='IPI-145' -> id='CHEMBL3039502'
[map][drug][OpenTargets] raw='ITI-214' -> id='CHEMBL3769414'
[map][drug][OpenTargets] raw='IkT-148009' -> id='CHEMBL5314481'
[map][drug][OpenTargets] raw='Imatinib' -> id='CHEMBL941'
[map][drug][OpenTargets] raw='Indomethacin' -> id='CHEMBL6'
[map][drug][OpenTargets] raw='Inebilizumab' -> id='CHEMBL2109334'
[map][drug][OpenTargets] raw='Infliximab' -> id='CHEMBL1201581'
[map][drug][OpenTargets] raw='Interferon alfa-n1' -> id='CHEMBL2108509'
[map][drug][OpenTargets] raw='Ioflupane i-123' -> id='CHEMBL3989517'
[map][drug][OpenTargets] raw='Isoniazid' -> id='CHEMBL64'
[map][drug][OpenTargets] raw='Istradefylline' -> id='CHEMBL431770'
[map][drug][OpenTargets] raw='JCAR015' -> id='CHEMBL3990020'
[map][drug][OpenTargets] raw='JCAR017' -> id='CHEMBL4297236'
[map][drug][OpenTargets] raw='JNJ 63723283' -> id='CHEMBL4298001'
[map][drug][OpenTargets] raw='JNJ-26483327' -> id='CHEMBL3109738'
[map][drug][OpenTargets] raw='JNJ-38518168' -> id='CHEMBL3301609'
[map][drug][OpenTargets] raw='KC706' -> id='CHEMBL3402567'
[map][drug][OpenTargets] raw='KN026' -> id='CHEMBL4594568'
[map][drug][OpenTargets] raw='KN046' -> id='CHEMBL4650483'
[map][drug][OpenTargets] raw='KPS-0373' -> id='CHEMBL4297622'
[map][drug][OpenTargets] raw='KRP-203' -> id='CHEMBL2137148'
[map][drug][OpenTargets] raw='KYMRIAH' -> id='CHEMBL3301574'
[map][drug][OpenTargets] raw='Ketoprofen' -> id='CHEMBL571'
[map][drug][OpenTargets] raw='Kevzara' -> id='CHEMBL2108730'
[map][drug][OpenTargets] raw='LBR-101' -> id='CHEMBL4297756'
[map][drug][OpenTargets] raw='LOMERIZINE' -> id='CHEMBL29188'
[map][drug][OpenTargets] raw='LX2931' -> id='CHEMBL1852164'
[map][drug][OpenTargets] raw='LY-2300559' -> id='CHEMBL4297398'
[map][drug][OpenTargets] raw='LY3164530' -> id='CHEMBL4298018'
[map][drug][OpenTargets] raw='LY3361237' -> id='CHEMBL5314624'
[map][drug][OpenTargets] raw='Lapatinib' -> id='CHEMBL554'
[map][drug][OpenTargets] raw='Laquinimod' -> id='CHEMBL66092'
[map][drug][OpenTargets] raw='Lasmiditan' -> id='CHEMBL3039520'
[map][drug][OpenTargets] raw='Leflunomide' -> id='CHEMBL960'
[map][drug][OpenTargets] raw='Lenzilumab' -> id='CHEMBL3707325'
[map][drug][OpenTargets] raw='Levodopa' -> id='CHEMBL1009'
[map][drug][OpenTargets] raw='Lisocabtagene maraleucel' -> id='CHEMBL4297236'
[map][drug][OpenTargets] raw='Lisuride' -> id='CHEMBL157138'
[map][drug][OpenTargets] raw='Litifilimab' -> id='CHEMBL3833308'
[map][drug][OpenTargets] raw='Loncastuximab tesirine' -> id='CHEMBL4297778'
[map][drug][OpenTargets] raw='Lornoxicam' -> id='CHEMBL1569487'
[map][drug][OpenTargets] raw='Lulizumab pegol' -> id='CHEMBL3137354'
[map][drug][OpenTargets] raw='M2951' -> id='CHEMBL4072833'
[map][drug][OpenTargets] raw='MCLA-128' -> id='CHEMBL4298025'
[map][drug][OpenTargets] raw='MCLA-158' -> id='CHEMBL4297781'
[map][drug][OpenTargets] raw='MDX-1100' -> id='CHEMBL2109664'
[map][drug][OpenTargets] raw='MEDI-570' -> id='CHEMBL2109449'
[map][drug][OpenTargets] raw='MEDI1341' -> id='CHEMBL6068461'
[map][drug][OpenTargets] raw='MEDI4920' -> id='CHEMBL4594331'
[map][drug][OpenTargets] raw='MEDI5117' -> id='CHEMBL4297732'
[map][drug][OpenTargets] raw='MEDI5752' -> id='CHEMBL5095362'
[map][drug][OpenTargets] raw='MEHD-7945A' -> id='CHEMBL3137345'
[map][drug][OpenTargets] raw='MGAH22' -> id='CHEMBL2364649'
[map][drug][OpenTargets] raw='MGD019' -> id='CHEMBL5095278'
[map][drug][OpenTargets] raw='MK-1308' -> id='CHEMBL4650419'
[map][drug][OpenTargets] raw='MK-3207' -> id='CHEMBL1910936'
[map][drug][OpenTargets] raw='MK-3475' -> id='CHEMBL3137343'
[map][drug][OpenTargets] raw='MK-8808' -> id='CHEMBL1201576'
[map][drug][OpenTargets] raw='MLN0002' -> id='CHEMBL1743087'
[map][drug][OpenTargets] raw='MLN4924' -> id='CHEMBL1231160'
[map][drug][OpenTargets] raw='MM-111' -> id='CHEMBL4297556'
[map][drug][OpenTargets] raw='MM-302' -> id='CHEMBL3833344'
[map][drug][OpenTargets] raw='MORAb-022' -> id='CHEMBL2109430'
[map][drug][OpenTargets] raw='MT-1303' -> id='CHEMBL3707374'
[map][drug][OpenTargets] raw='Masoprocol' -> id='CHEMBL313972'
[map][drug][OpenTargets] raw='Mavrilimumab' -> id='CHEMBL1743039'
[map][drug][OpenTargets] raw='Meclinertant' -> id='CHEMBL506981'
[map][drug][OpenTargets] raw='Meclofenamate Sodium' -> id='CHEMBL1562610'
[map][drug][OpenTargets] raw='Meloxicam' -> id='CHEMBL599'
[map][drug][OpenTargets] raw='Mercaptopurine' -> id='CHEMBL1200751'
[map][drug][OpenTargets] raw='Merimepodib' -> id='CHEMBL304087'
[map][drug][OpenTargets] raw='Mesalazine' -> id='CHEMBL704'
[map][drug][OpenTargets] raw='Metformin' -> id='CHEMBL1431'
[map][drug][OpenTargets] raw='Metformin glycinate' -> id='CHEMBL2108299'
[map][drug][OpenTargets] raw='Methotrexate' -> id='CHEMBL34259'
[map][drug][OpenTargets] raw='Methysergide' -> id='CHEMBL1065'
[map][drug][OpenTargets] raw='Metixene' -> id='CHEMBL1201342'
[map][drug][OpenTargets] raw='Metronidazole' -> id='CHEMBL137'
[map][drug][OpenTargets] raw='Milatuzumab' -> id='CHEMBL1743040'
[map][drug][OpenTargets] raw='Mirikizumab' -> id='CHEMBL3990014'
[map][drug][OpenTargets] raw='Mobocertinib' -> id='CHEMBL4650319'
[map][drug][OpenTargets] raw='NE3107' -> id='CHEMBL4297284'
[map][drug][OpenTargets] raw='NERATINIB MALEATE' -> id='CHEMBL3989921'
[map][drug][OpenTargets] raw='NIS793' -> id='CHEMBL4298057'
[map][drug][OpenTargets] raw='NLY01' -> id='CHEMBL4650495'

2026-02-27 18:51:42,637 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:42,663 [INFO] [LLM] Batch done in 1.61s
2026-02-27 18:51:42,665 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:42,671 [INFO] [LLM] Batch done in 1.61s
2026-02-27 18:51:43,469 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:43,472 [INFO] [LLM] Batch done in 2.46s
2026-02-27 18:51:44,101 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:44,103 [INFO] [LLM] Batch done in 3.04s
2026-02-27 18:51:44,419 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:44,421 [INFO] [LLM] Batch done in 3.36s
2026-02-27 18:51:44,939 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:44,941 [INFO] [LLM] Batch done in 3.88s
2026-02-27 18:51:45,275 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:45,277 [INFO] [LLM] Batch done in 4.21s
2026-02-27 18:51:45,938 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:45,941 [INFO] [LLM] Batch done in 4.88s
2026-02-27 18:51:46,655 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:46,657 [INFO] [LLM] Batch done in 5.59s
2026-02-27 18:51:46,703 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:46,705 [INFO] [LLM] Batch done in 5.64s
2026-02-27 18:51:46,832 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:46,834 [INFO] [LLM] Batch done in 5.77s
2026-02-27 18:51:46,835 [INFO] [OT] Verifying 2 unique drug suggestions...
2026-02-27 18:51:47,233 [INFO] [OT] 'icotinib' → 'ICOTINIB' (CHEMBL2087361)
2026-02-27 18:51:47,236 [INFO] Done: 1 / 845 confirmed | 844 → None

[map][drug][Llama] raw='Icotinib hydrochloride' -> canonical='ICOTINIB' -> id='CHEMBL2087361'

,drug_name,drug_id,source
0,(1-Benzyl-1H-indazol-5-yl)-quinazolin-4-yl-amine,None,None
1,(1-Benzyl-1H-indol-5-yl)-quinazolin-4-yl-amine,None,None
2,(3-Bromo-phenyl)-(5-nitro-quinazolin-4-yl)-amine,None,None
3,(3-Bromo-phenyl)-quinazolin-4-yl-amine,None,None
4,(E)-5-(4-Hydroxybenzylidene)-1-phenethylhydantoin,None,None
...,...,...,...
1344,Zavegepant,CHEMBL2397415,OpenTargets
1345,Zenocutuzomab,None,None
1346,Zolmitriptan,CHEMBL1185,OpenTargets
1347,Zunsemetinib,CHEMBL3704901,OpenTargets
1348,Zuranolone,CHEMBL4105630,OpenTargets

In [12]:
df_drug["source"].value_counts()

source
OpenTargets    504
Llama            1
Name: count, dtype: int64

In [13]:
# df_drug[df_drug["source"]=="Llama"]

In [14]:
df_drug[df_drug.isna().any(axis=1)]

                                              drug_name drug_id source
0      (1-Benzyl-1H-indazol-5-yl)-quinazolin-4-yl-amine    None   None
1        (1-Benzyl-1H-indol-5-yl)-quinazolin-4-yl-amine    None   None
2      (3-Bromo-phenyl)-(5-nitro-quinazolin-4-yl)-amine    None   None
3                (3-Bromo-phenyl)-quinazolin-4-yl-amine    None   None
4     (E)-5-(4-Hydroxybenzylidene)-1-phenethylhydantoin    None   None
...                                                 ...     ...    ...
1338                                              Z-321    None   None
1339                                              ZN-e4    None   None
1341                                               ZT-1    None   None
1342                                               ZW49    None   None
1345                                      Zenocutuzomab    None   None

[844 rows x 3 columns]

##### Associate id with all disease entry

In [15]:
# Resolve unique disease surface forms to IDs.
# Canonical fallback is internal; returned rows remain keyed by raw input disease_name.
df_disease = await get_disease_ids_fast(list(question_entities["disease_name"]))
df_disease = df_disease.drop_duplicates(subset=["disease_name", "disease_id"]).reset_index(drop=True)
df_disease

2026-02-27 18:51:48,434 [INFO] [LLM] Total 34 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:51:48,435 [INFO] [LLM] Batch size: 34

[map][disease][OpenTargets] raw='Acute myeloid leukaemia' -> id='MONDO_0015667'
[map][disease][OpenTargets] raw='Adrenal cancer' -> id='EFO_0003850'
[map][disease][OpenTargets] raw='Alzheimer disease' -> id='MONDO_0007088'
[map][disease][OpenTargets] raw='Angina pectoris' -> id='EFO_0003913'
[map][disease][OpenTargets] raw='Anxiety disorder' -> id='EFO_0006788'
[map][disease][OpenTargets] raw='Arterial occlusive disease' -> id='EFO_0003875'
[map][disease][OpenTargets] raw='Attention deficit hyperactivity disorder' -> id='EFO_0003888'
[map][disease][OpenTargets] raw='Autism spectrum disorder' -> id='EFO_0003756'
[map][disease][OpenTargets] raw='Binge eating disorder' -> id='EFO_0005924'
[map][disease][OpenTargets] raw='Bladder cancer' -> id='MONDO_0004986'
[map][disease][OpenTargets] raw='Brain cancer' -> id='MONDO_0001657'
[map][disease][OpenTargets] raw='Breast cancer' -> id='EFO_0000305'
[map][disease][OpenTargets] raw='Breast in situ carcinoma' -> id='MONDO_0004658'
[map][disease][OpenTargets] raw='Bronchioalveolar carcinoma' -> id='MONDO_0000503'
[map][disease][OpenTargets] raw='Cervical cancer' -> id='EFO_0001061'
[map][disease][OpenTargets] raw='Chronic myelogenous leukaemia' -> id='EFO_0000339'
[map][disease][OpenTargets] raw='Chronic pain' -> id='HP_0012532'
[map][disease][OpenTargets] raw='Cocaine use disorder' -> id='EFO_0010445'
[map][disease][OpenTargets] raw='Colon cancer' -> id='EFO_1001950'
[map][disease][OpenTargets] raw='Colorectal cancer' -> id='EFO_1001951'
[map][disease][OpenTargets] raw='Corneal disease' -> id='EFO_0009464'
[map][disease][OpenTargets] raw='Cough' -> id='HP_0012735'
[map][disease][OpenTargets] raw='Crohn disease' -> id='EFO_0000384'
[map][disease][OpenTargets] raw='Cryptosporidiosis' -> id='MONDO_0015474'
[map][disease][OpenTargets] raw='Cutaneous lupus erythematosus' -> id='EFO_0003834'
[map][disease][OpenTargets] raw='Cystic fibrosis' -> id='MONDO_0009061'
[map][disease][OpenTargets] raw='Dengue fever' -> id='EFO_0005547'
[map][disease][OpenTargets] raw='Depression' -> id='MONDO_0002050'
[map][disease][OpenTargets] raw='Diabetic foot ulcer' -> id='EFO_1001459'
[map][disease][OpenTargets] raw='Diffuse large B-cell lymphoma' -> id='EFO_0000403'
[map][disease][OpenTargets] raw='Digestive system disease' -> id='HP_0011024'
[map][disease][OpenTargets] raw='Discoid lupus erythematosus' -> id='MONDO_0019558'
[map][disease][OpenTargets] raw='Endometrial cancer' -> id='EFO_0007532'
[map][disease][OpenTargets] raw='Epileptic encephalopathy' -> id='HP_0200134'
[map][disease][OpenTargets] raw='Esophageal cancer' -> id='EFO_0002916'
[map][disease][OpenTargets] raw='Fallopian tube cancer' -> id='EFO_1000251'
[map][disease][OpenTargets] raw='Fever' -> id='HP_0001945'
[map][disease][OpenTargets] raw='Follicular lymphoma' -> id='MONDO_0018906'
[map][disease][OpenTargets] raw='Gram-positive bacterial infection' -> id='MONDO_0021679'
[map][disease][OpenTargets] raw='Head and neck cancer' -> id='EFO_0006859'
[map][disease][OpenTargets] raw='Hearing disorder' -> id='MONDO_0021945'
[map][disease][OpenTargets] raw='Hepatocellular carcinoma' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Hodgkin lymphoma' -> id='EFO_0000183'
[map][disease][OpenTargets] raw='Hypopharyngeal cancer' -> id='EFO_0002938'
[map][disease][OpenTargets] raw='Indeterminate colitis' -> id='EFO_1000034'
[map][disease][OpenTargets] raw='Insomnia' -> id='EFO_0004698'
[map][disease][OpenTargets] raw='Ischemia' -> id='EFO_0000556'
[map][disease][OpenTargets] raw='Kidney failure' -> id='EFO_1002048'
[map][disease][OpenTargets] raw='Liposarcoma' -> id='EFO_0000569'
[map][disease][OpenTargets] raw='Liver cancer' -> id='EFO_0000182'
[map][disease][OpenTargets] raw='Lung cancer' -> id='EFO_0001071'
[map][disease][OpenTargets] raw='Lupus erythematosus' -> id='MONDO_0004670'
[map][disease][OpenTargets] raw='Lupus nephritis' -> id='EFO_0005761'
[map][disease][OpenTargets] raw='Lymphoma' -> id='EFO_0000574'
[map][disease][OpenTargets] raw='Malignant haematopoietic neoplasm' -> id='MONDO_0044881'
[map][disease][OpenTargets] raw='Malignant pleural mesothelioma' -> id='EFO_0000770'
[map][disease][OpenTargets] raw='Mature T-cell lymphoma' -> id='MONDO_0000430'
[map][disease][OpenTargets] raw='Melanoma' -> id='EFO_0000756'
[map][disease][OpenTargets] raw='Metastatic tumour' -> id='EFO_0009709'
[map][disease][OpenTargets] raw='Migraine' -> id='MONDO_0005277'
[map][disease][OpenTargets] raw='Mood disorder' -> id='EFO_0004247'
[map][disease][OpenTargets] raw='Multiple myeloma' -> id='EFO_0001378'
[map][disease][OpenTargets] raw='Multiple sclerosis' -> id='MONDO_0005301'
[map][disease][OpenTargets] raw='Myelodysplastic syndrome' -> id='EFO_0000198'
[map][disease][OpenTargets] raw='Myeloproliferative neoplasm' -> id='EFO_0002428'
[map][disease][OpenTargets] raw='Nasopharyngeal cancer' -> id='MONDO_0011775'
[map][disease][OpenTargets] raw='Nicotine use disorder' -> id='EFO_0003768'
[map][disease][OpenTargets] raw='Non-hodgkin lymphoma' -> id='EFO_0005952'
[map][disease][OpenTargets] raw='Obesity' -> id='EFO_0001073'
[map][disease][OpenTargets] raw='Oral mucositis' -> id='EFO_0009688'
[map][disease][OpenTargets] raw='Orthostatic hypotension' -> id='EFO_0005252'
[map][disease][OpenTargets] raw='Osteoarthritis' -> id='MONDO_0005178'
[map][disease][OpenTargets] raw='Ovarian cancer' -> id='EFO_0001075'
[map][disease][OpenTargets] raw='Ovarian dysfunction' -> id='EFO_0009003'
[map][disease][OpenTargets] raw='Pain' -> id='HP_0012531'
[map][disease][OpenTargets] raw='Pancreatic cancer' -> id='EFO_0002618'
[map][disease][OpenTargets] raw='Pancreatic ductal carcinoma' -> id='MONDO_0005184'
[map][disease][OpenTargets] raw='Parkinson disease' -> id='MONDO_0005180'
[map][disease][OpenTargets] raw='Parkinsonism' -> id='HP_0001300'
[map][disease][OpenTargets] raw='Perianal crohn disease' -> id='EFO_0005627'
[map][disease][OpenTargets] raw='Periodontal disease' -> id='MONDO_0002635'
[map][disease][OpenTargets] raw='Peritoneal cancer' -> id='MONDO_0002087'
[map][disease][OpenTargets] raw='Plaque psoriasis' -> id='EFO_1001494'
[map][disease][OpenTargets] raw='Prostate cancer' -> id='EFO_0001663'
[map][disease][OpenTargets] raw='Psoriasis' -> id='EFO_0000676'
[map][disease][OpenTargets] raw='Psoriatic arthritis' -> id='EFO_0003778'
[map][disease][OpenTargets] raw='Pulmonary tuberculosis' -> id='EFO_1000049'
[map][disease][OpenTargets] raw='Rectum cancer' -> id='EFO_1000657'
[map][disease][OpenTargets] raw='Renal cell carcinoma' -> id='EFO_0000681'
[map][disease][OpenTargets] raw='Retina cancer' -> id='EFO_0005716'
[map][disease][OpenTargets] raw='Rheumatic fever' -> id='EFO_1001160'
[map][disease][OpenTargets] raw='Rheumatoid arthritis' -> id='EFO_0000685'
[map][disease][OpenTargets] raw='Schizoaffective disorder' -> id='EFO_0005411'
[map][disease][OpenTargets] raw='Schizophrenia' -> id='MONDO_0005090'
[map][disease][OpenTargets] raw='Status epilepticus' -> id='EFO_0008526'
[map][disease][OpenTargets] raw='Stomach cancer' -> id='EFO_0003897'
[map][disease][OpenTargets] raw='Substance abuse' -> id='MONDO_0002491'
[map][disease][OpenTargets] raw='Systemic lupus erythematosus' -> id='MONDO_0007915'
[map][disease][OpenTargets] raw='Testicular cancer' -> id='EFO_0004281'
[map][disease][OpenTargets] raw='Toxicity' -> id='EFO_0011061'
[map][disease][OpenTargets] raw='Tuberculosis' -> id='MONDO_0018076'
[map][disease][OpenTargets] raw='Type 2 diabetes mellitus' -> id='MONDO_0005148'
[map][disease][OpenTargets] raw='Ulcerative colitis' -> id='EFO_0000729'
[map][disease][OpenTargets] raw='Urethral cancer' -> id='EFO_0003846'

2026-02-27 18:51:49,403 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:49,406 [INFO] [LLM] Batch done in 0.97s
2026-02-27 18:51:49,406 [INFO] [LLM] 'BCR-ABL1-negative chronic myeloid leukaemia' → 'chronic myeloid leukemia'
2026-02-27 18:51:49,407 [INFO] [LLM] 'Bone metastases' → None
2026-02-27 18:51:49,407 [INFO] [LLM] 'Cerebral ischaemia' → 'cerebral ischemia'
2026-02-27 18:51:49,408 [INFO] [LLM] 'Choreiform disorder' → None
2026-02-27 18:51:49,409 [INFO] [LLM] 'Dissociative neurological symptom disorder' → None
2026-02-27 18:51:49,409 [INFO] [LLM] 'Ejaculatory dysfunction' → None
2026-02-27 18:51:49,410 [INFO] [LLM] 'Epilepsy/seizure' → 'epilepsy'
2026-02-27 18:51:49,411 [INFO] [LLM] 'General pain disorder' → None
2026-02-27 18:51:49,411 [INFO] [LLM] 'HIV-infected patients with tuberculosis' → 'tuberculosis'
2026-02-27 18:51:49,411 [INFO] [LLM] 'Hepatitis virus infection' → 'hepatitis'
2026-02-27 18:51:49,412 [INFO] [LLM] 'Idiopathic parkinson disease' → 'parkinson disease'
2026-02-27 18:51:49,412 [INFO] [LLM] 'Intracerebral haemorrhage' → 'intracerebral hemorrhage'
2026-02-27 18:51:49,413 [INFO] [LLM] 'Lip/oral cavity/pharynx neoplasm' → None
2026-02-27 18:51:49,413 [INFO] [LLM] 'Malignant mesenchymal neoplasm' → None
2026-02-27 18:51:49,413 [INFO] [LLM] 'Mature B-cell leukaemia' → 'leukemia, b-cell'
2026-02-27 18:51:49,414 [INFO] [LLM] 'Mature B-cell lymphoma' → 'lymphoma, b-cell'
2026-02-27 18:51:49,414 [INFO] [LLM] 'Menopausal disorder' → None
2026-02-27 18:51:49,414 [INFO] [LLM] 'Metastatic biliary tract neoplasms' → None
2026-02-27 18:51:49,415 [INFO] [LLM] 'Metastatic liver/bile duct neoplasm' → None
2026-02-27 18:51:49,416 [INFO] [LLM] 'Metastatic lymph node neoplasm' → None
2026-02-27 18:51:49,416 [INFO] [LLM] 'Multi-drug resistant tuberculosis' → 'tuberculosis'
2026-02-27 18:51:49,417 [INFO] [LLM] 'Nausea/vomiting' → None
2026-02-27 18:51:49,417 [INFO] [LLM] 'Neurobehavioral disorder' → None
2026-02-27 18:51:49,417 [INFO] [LLM] 'Non-small-cell lung cancer' → 'lung cancer, non-small cell'
2026-02-27 18:51:49,418 [INFO] [LLM] 'Postoperative inflammation' → None
2026-02-27 18:51:49,419 [INFO] [LLM] 'Recurrent glioblastoma' → 'glioblastoma'
2026-02-27 18:51:49,420 [INFO] [LLM] 'Skin postprocedural disorder' → None
2026-02-27 18:51:49,420 [INFO] [LLM] 'Soft tissue disorder' → None
2026-02-27 18:51:49,420 [INFO] [LLM] 'Solid tumour/cancer' → None
2026-02-27 18:51:49,421 [INFO] [LLM] 'Spinal cord/cranial nerve neoplasm' → None
2026-02-27 18:51:49,421 [INFO] [LLM] 'Subacute cutaneous lupus erythematosus' → 'lupus erythematosus, cutaneous'
2026-02-27 18:51:49,421 [INFO] [LLM] 'Transplant rejection' → None
2026-02-27 18:51:49,422 [INFO] [LLM] 'Unspecific body region injury' → None
2026-02-27 18:51:49,423 [INFO] [LLM] 'concerning food/fluid intake symptom' → None
2026-02-27 18:51:49,424 [INFO] [OT] Verifying 12 unique suggestions...
2026-02-27 18:51:49,860 [INFO] [OT] 'chronic myeloid leukemia' → 'chronic myelogenous leukemia' (EFO_0000339)
2026-02-27 18:51:49,861 [INFO] [OT] 'parkinson disease' → 'Parkinson disease' (MONDO_0005180)
2026-02-27 18:51:49,862 [INFO] [OT] 'cerebral ischemia' → 'cerebral infarction' (MONDO_0002679)
2026-02-27 18:51:49,862 [INFO] [OT] 'epilepsy' → 'epilepsy' (EFO_0000474)
2026-02-27 18:51:49,862 [INFO] [OT] 'hepatitis' → 'Hepatitis' (HP_0012115)
2026-02-27 18:51:49,863 [INFO] [OT] 'glioblastoma' → 'glioblastoma multiforme' (EFO_0000519)
2026-02-27 18:51:49,863 [INFO] [OT] 'intracerebral hemorrhage' → 'intracerebral hemorrhage' (EFO_0005669)
2026-02-27 18:51:49,865 [INFO] [OT] 'tuberculosis' → 'tuberculosis' (MONDO_0018076)
2026-02-27 18:51:49,867 [INFO] Done: 9 / 34 confirmed | 25 → None

[map][disease][Llama] raw='BCR-ABL1-negative chronic myeloid leukaemia' -> canonical='chronic myelogenous leukemia' -> id='EFO_0000339'
[map][disease][Llama] raw='Cerebral ischaemia' -> canonical='cerebral infarction' -> id='EFO_0000712'
[map][disease][Llama] raw='Epilepsy/seizure' -> canonical='epilepsy' -> id='EFO_0000474'
[map][disease][Llama] raw='HIV-infected patients with tuberculosis' -> canonical='tuberculosis' -> id='MONDO_0018076'
[map][disease][Llama] raw='Hepatitis virus infection' -> canonical='Hepatitis' -> id='HP_0012115'
[map][disease][Llama] raw='Idiopathic parkinson disease' -> canonical='Parkinson disease' -> id='MONDO_0005180'
[map][disease][Llama] raw='Intracerebral haemorrhage' -> canonical='intracerebral hemorrhage' -> id='EFO_0005669'
[map][disease][Llama] raw='Multi-drug resistant tuberculosis' -> canonical='tuberculosis' -> id='MONDO_0018076'
[map][disease][Llama] raw='Recurrent glioblastoma' -> canonical='glioblastoma multiforme' -> id='EFO_0000519'
[warn] Unresolved diseases after OpenTargets/Llama/OLS: ['Bone metastases', 'Choreiform disorder', 'Dissociative neurological symptom disorder', 'Ejaculatory dysfunction', 'General pain disorder', 'Lip/oral cavity/pharynx neoplasm', 'Malignant mesenchymal neoplasm', 'Mature B-cell leukaemia', 'Mature B-cell lymphoma', 'Menopausal disorder', 'Metastatic biliary tract neoplasms', 'Metastatic liver/bile duct neoplasm', 'Metastatic lymph node neoplasm', 'Nausea/vomiting', 'Neurobehavioral disorder', 'Non-small-cell lung cancer', 'Postoperative inflammation', 'Skin postprocedural disorder', 'Soft tissue disorder', 'Solid tumour/cancer', 'Spinal cord/cranial nerve neoplasm', 'Subacute cutaneous lupus erythematosus', 'Transplant rejection', 'Unspecific body region injury', 'concerning food/fluid intake symptom']

                             disease_name     disease_id       source
0                 Acute myeloid leukaemia  MONDO_0015667  OpenTargets
1                          Adrenal cancer    EFO_0003850  OpenTargets
2                       Alzheimer disease  MONDO_0007088  OpenTargets
3                         Angina pectoris    EFO_0003913  OpenTargets
4                        Anxiety disorder    EFO_0006788  OpenTargets
..                                    ...            ...          ...
133              Type 2 diabetes mellitus  MONDO_0005148  OpenTargets
134                    Ulcerative colitis    EFO_0000729  OpenTargets
135         Unspecific body region injury           None         None
136                       Urethral cancer    EFO_0003846  OpenTargets
137  concerning food/fluid intake symptom           None         None

[138 rows x 3 columns]

In [16]:
df_disease["source"].value_counts()

source
OpenTargets    104
Llama            9
Name: count, dtype: int64

In [17]:
df_disease[df_disease.isna().any(axis=1)]

                                   disease_name disease_id source
11                              Bone metastases       None   None
18                          Choreiform disorder       None   None
36   Dissociative neurological symptom disorder       None   None
37                      Ejaculatory dysfunction       None   None
45                        General pain disorder       None   None
60             Lip/oral cavity/pharynx neoplasm       None   None
68               Malignant mesenchymal neoplasm       None   None
70                      Mature B-cell leukaemia       None   None
71                       Mature B-cell lymphoma       None   None
74                          Menopausal disorder       None   None
75           Metastatic biliary tract neoplasms       None   None
76          Metastatic liver/bile duct neoplasm       None   None
77               Metastatic lymph node neoplasm       None   None
87                              Nausea/vomiting       None   None
88                     Neurobehavioral disorder       None   None
91                   Non-small-cell lung cancer       None   None
107                  Postoperative inflammation       None   None
120                Skin postprocedural disorder       None   None
121                        Soft tissue disorder       None   None
122                         Solid tumour/cancer       None   None
123          Spinal cord/cranial nerve neoplasm       None   None
126      Subacute cutaneous lupus erythematosus       None   None
131                        Transplant rejection       None   None
135               Unspecific body region injury       None   None
137        concerning food/fluid intake symptom       None   None

In [18]:
# ------------------------------------------------------------------
# Disease canonical audit (OpenTargets-strict IDs only)
# ------------------------------------------------------------------
# IMPORTANT:
# - This cell runs an additional Llama canonicalization pass over unresolved rows.
# - IDs are still resolved ONLY via OpenTargets mapIds (score==1).
# - To avoid changing the baseline resolver output, writeback is OFF by default.
APPLY_AUDIT_MAPPINGS = False

# 1) Rows unresolved after primary resolver
unresolved_rows = df_disease[df_disease["disease_id"].isna()].reset_index(drop=True)
unresolved_raw_names = list(
    dict.fromkeys(
        str(name).strip()
        for name in unresolved_rows["disease_name"].dropna().astype(str).tolist()
        if str(name).strip()
    )
)

# 2) Llama canonicalization suggestions
disease_input_map = {name: None for name in unresolved_raw_names}
canonicalisation_map = await utility.canonicalise_disease_dict(disease_input_map)

# 3) OpenTargets strict verification (score==1 only)
canonical_terms_norm = list(
    dict.fromkeys(
        utility._normalize_disease_term(v)
        for v in canonicalisation_map.values()
        if isinstance(v, str) and v.strip()
    )
)
canonical_to_id = utility.resolve_diseases_opentargets_bulk(
    canonical_terms_norm,
    strict_score_one=True,
)

# 4) Build persistent audit table
audit_rows = []
applied_count = 0
candidate_count = 0

for raw_disease_name in unresolved_raw_names:
    canonical_name = canonicalisation_map.get(raw_disease_name)
    if isinstance(canonical_name, str) and canonical_name.strip():
        canonical_name = canonical_name.strip()
        canonical_norm = utility._normalize_disease_term(canonical_name)
        resolved_id = canonical_to_id.get(canonical_norm)
    else:
        canonical_name = None
        canonical_norm = None
        resolved_id = None

    can_apply = bool(resolved_id)
    if can_apply:
        candidate_count += 1
        print(f"[audit][disease][Llama->OT] raw='{raw_disease_name}' -> canonical='{canonical_name}' -> id='{resolved_id}'")

    if can_apply and APPLY_AUDIT_MAPPINGS:
        mask = df_disease["disease_name"].astype(str).str.strip() == raw_disease_name
        df_disease.loc[mask, "disease_id"] = resolved_id
        df_disease.loc[mask, "source"] = "Llama"
        applied_count += 1

    status = (
        "mappable_ot_exact" if can_apply else
        ("no_canonical" if canonical_name is None else "canonical_not_in_ot")
    )
    audit_rows.append({
        "raw_disease_name": raw_disease_name,
        "canonical_name": canonical_name,
        "canonical_norm": canonical_norm,
        "resolved_disease_id": resolved_id,
        "status": status,
        "can_apply": can_apply,
        "applied": bool(can_apply and APPLY_AUDIT_MAPPINGS),
    })

disease_canonical_audit_df = pd.DataFrame(audit_rows)
if not disease_canonical_audit_df.empty:
    disease_canonical_audit_df = disease_canonical_audit_df.sort_values(
        ["status", "raw_disease_name"],
        ascending=[True, True],
    ).reset_index(drop=True)

print(f"[summary][disease][audit] OT-mappable candidates: {candidate_count}")
print(f"[summary][disease][audit] applied to df_disease: {applied_count} (APPLY_AUDIT_MAPPINGS={APPLY_AUDIT_MAPPINGS})")
if not disease_canonical_audit_df.empty:
    print("[summary][disease][audit] status counts:")
    print(disease_canonical_audit_df["status"].value_counts(dropna=False))

disease_canonical_audit_df

2026-02-27 18:51:50,388 [INFO] [LLM] Total 25 names split into 1 batches (max_batch_chars=6000, max_batch_items=80, model=llama-3.3-70b-versatile).
2026-02-27 18:51:50,390 [INFO] [LLM] Batch size: 25
2026-02-27 18:51:51,335 [INFO] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-27 18:51:51,338 [INFO] [LLM] Batch done in 0.95s
2026-02-27 18:51:51,339 [INFO] [LLM] 'Bone metastases' → None
2026-02-27 18:51:51,340 [INFO] [LLM] 'Choreiform disorder' → None
2026-02-27 18:51:51,340 [INFO] [LLM] 'Dissociative neurological symptom disorder' → None
2026-02-27 18:51:51,341 [INFO] [LLM] 'Ejaculatory dysfunction' → None
2026-02-27 18:51:51,341 [INFO] [LLM] 'General pain disorder' → None
2026-02-27 18:51:51,342 [INFO] [LLM] 'Lip/oral cavity/pharynx neoplasm' → None
2026-02-27 18:51:51,342 [INFO] [LLM] 'Malignant mesenchymal neoplasm' → None
2026-02-27 18:51:51,343 [INFO] [LLM] 'Mature B-cell leukaemia' → 'leukaemia'
2026-02-27 18:51:51,343 [INFO] [LLM] 'Mature B-cell lymphoma' → 'lymphoma'
2026-02-27 18:51:51,344 [INFO] [LLM] 'Menopausal disorder' → None
2026-02-27 18:51:51,344 [INFO] [LLM] 'Metastatic biliary tract neoplasms' → None
2026-02-27 18:51:51,344 [INFO] [LLM] 'Metastatic liver/bile duct neoplasm' → None
2026-02-27 18:51:51,345 [INFO] [LLM] 'Metastatic lymph node neoplasm' → None
2026-02-27 18:51:51,345 [INFO] [LLM] 'Nausea/vomiting' → None
2026-02-27 18:51:51,346 [INFO] [LLM] 'Neurobehavioral disorder' → None
2026-02-27 18:51:51,347 [INFO] [LLM] 'Non-small-cell lung cancer' → 'non-small cell lung cancer'
2026-02-27 18:51:51,347 [INFO] [LLM] 'Postoperative inflammation' → None
2026-02-27 18:51:51,348 [INFO] [LLM] 'Skin postprocedural disorder' → None
2026-02-27 18:51:51,348 [INFO] [LLM] 'Soft tissue disorder' → None
2026-02-27 18:51:51,348 [INFO] [LLM] 'Solid tumour/cancer' → None
2026-02-27 18:51:51,349 [INFO] [LLM] 'Spinal cord/cranial nerve neoplasm' → None
2026-02-27 18:51:51,350 [INFO] [LLM] 'Subacute cutaneous lupus erythematosus' → 'lupus erythematosus'
2026-02-27 18:51:51,350 [INFO] [LLM] 'Transplant rejection' → None
2026-02-27 18:51:51,351 [INFO] [LLM] 'Unspecific body region injury' → None
2026-02-27 18:51:51,351 [INFO] [LLM] 'concerning food/fluid intake symptom' → None
2026-02-27 18:51:51,352 [INFO] [OT] Verifying 4 unique suggestions...
2026-02-27 18:51:51,766 [INFO] [OT] 'non-small cell lung cancer' → 'non-small cell lung carcinoma' (EFO_0003060)
2026-02-27 18:51:51,767 [INFO] [OT] 'lupus erythematosus' → 'lupus erythematosus' (MONDO_0004670)
2026-02-27 18:51:51,768 [INFO] [OT] 'lymphoma' → 'lymphoma' (EFO_0000574)
2026-02-27 18:51:51,768 [INFO] [OT] 'leukaemia' → 'childhood leukemia' (MONDO_0004355)
2026-02-27 18:51:51,770 [INFO] Done: 4 / 25 confirmed | 21 → None

[audit][disease][Llama->OT] raw='Mature B-cell leukaemia' -> canonical='childhood leukemia' -> id='MONDO_0004355'
[audit][disease][Llama->OT] raw='Mature B-cell lymphoma' -> canonical='lymphoma' -> id='EFO_0000574'
[audit][disease][Llama->OT] raw='Non-small-cell lung cancer' -> canonical='non-small cell lung carcinoma' -> id='EFO_0003060'
[audit][disease][Llama->OT] raw='Subacute cutaneous lupus erythematosus' -> canonical='lupus erythematosus' -> id='MONDO_0004670'
[summary][disease][audit] OT-mappable candidates: 4
[summary][disease][audit] applied to df_disease: 0 (APPLY_AUDIT_MAPPINGS=False)
[summary][disease][audit] status counts:
status
no_canonical         21
mappable_ot_exact     4
Name: count, dtype: int64

,raw_disease_name,canonical_name,canonical_norm,resolved_disease_id,status,can_apply,applied
0,Mature B-cell leukaemia,childhood leukemia,childhood leukemia,MONDO_0004355,mappable_ot_exact,True,False
1,Mature B-cell lymphoma,lymphoma,lymphoma,EFO_0000574,mappable_ot_exact,True,False
2,Non-small-cell lung cancer,non-small cell lung carcinoma,non-small cell lung carcinoma,EFO_0003060,mappable_ot_exact,True,False
3,Subacute cutaneous lupus erythematosus,lupus erythematosus,lupus erythematosus,MONDO_0004670,mappable_ot_exact,True,False
4,Bone metastases,None,None,None,no_canonical,False,False
5,Choreiform disorder,None,None,None,no_canonical,False,False
6,Dissociative neurological symptom disorder,None,None,None,no_canonical,False,False
7,Ejaculatory dysfunction,None,None,None,no_canonical,False,False
8,General pain disorder,None,None,None,no_canonical,False,False
9,Lip/oral cavity/pharynx neoplasm,None,None,None,no_canonical,False,False
10,Malignant mesenchymal neoplasm,None,None,None,no_canonical,False,False
11,Menopausal disorder,None,None,None,no_canonical,False,False
12,Metastatic biliary tract neoplasms,None,None,None,no_canonical,False,False
13,Metastatic liver/bile duct neoplasm,None,None,None,no_canonical,False,False
14,Metastatic lymph node neoplasm,None,None,None,no_canonical,False,False
15,Nausea/vomiting,None,None,None,no_canonical,False,False
16,Neurobehavioral disorder,None,None,None,no_canonical,False,False
17,Postoperative inflammation,None,None,None,no_canonical,False,False
18,Skin postprocedural disorder,None,None,None,no_canonical,False,False
19,Soft tissue disorder,None,None,None,no_canonical,False,False
20,Solid tumour/cancer,None,None,None,no_canonical,False,False
21,Spinal cord/cranial nerve neoplasm,None,None,None,no_canonical,False,False
22,Transplant rejection,None,None,None,no_canonical,False,False
23,Unspecific body region injury,None,None,None,no_canonical,False,False
24,concerning food/fluid intake symptom,None,None,None,no_canonical,False,False

In [19]:
# disease_canonical_audit_df

In [20]:
df_disease[df_disease["source"]=='Llama']

                                    disease_name     disease_id source
8    BCR-ABL1-negative chronic myeloid leukaemia    EFO_0000339  Llama
16                            Cerebral ischaemia    EFO_0000712  Llama
39                              Epilepsy/seizure    EFO_0000474  Llama
47       HIV-infected patients with tuberculosis  MONDO_0018076  Llama
50                     Hepatitis virus infection     HP_0012115  Llama
54                  Idiopathic parkinson disease  MONDO_0005180  Llama
57                     Intracerebral haemorrhage    EFO_0005669  Llama
81             Multi-drug resistant tuberculosis  MONDO_0018076  Llama
113                       Recurrent glioblastoma    EFO_0000519  Llama

In [21]:
df_disease["source"].value_counts()

source
OpenTargets    104
Llama            9
Name: count, dtype: int64

In [22]:
df_disease

                             disease_name     disease_id       source
0                 Acute myeloid leukaemia  MONDO_0015667  OpenTargets
1                          Adrenal cancer    EFO_0003850  OpenTargets
2                       Alzheimer disease  MONDO_0007088  OpenTargets
3                         Angina pectoris    EFO_0003913  OpenTargets
4                        Anxiety disorder    EFO_0006788  OpenTargets
..                                    ...            ...          ...
133              Type 2 diabetes mellitus  MONDO_0005148  OpenTargets
134                    Ulcerative colitis    EFO_0000729  OpenTargets
135         Unspecific body region injury           None         None
136                       Urethral cancer    EFO_0003846  OpenTargets
137  concerning food/fluid intake symptom           None         None

[138 rows x 3 columns]

In [23]:
# df_disease[df_disease["source"]=="Llama"]

In [24]:
def compute_jaccard_from_run_dataframes(dct_result, df_gene, df_disease, df_drug):
    """
    Compute per-question cross-run Jaccard consistency after mapping entities to IDs.

    For each (model, question):
    - intersection: entries present in ALL valid runs
    - union: entries present in ANY valid run
    - jaccard = |intersection| / |union|

    All comparisons are CASE-INDEPENDENT and ID-based.

    Side effects:
    - Stores per-run mapped dataframe in:
        dct_result[model][question][run]['dataframe_id']

    Returns:
    - dct_jaccard[model][question] = {
          'jaccard': float,
          'n_valid_runs': int,
          'intersection': set[tuple],
          'union': set[tuple],
      }
    """

    dct_jaccard = {}

    # ------------------------------------------------------------------
    # Build deterministic one-to-one mapping tables
    # ------------------------------------------------------------------
    gene_map = (
        df_gene.assign(_gene_norm=df_gene["gene_name"].astype(str).str.strip().str.upper())
        [["_gene_norm", "gene_id"]]
        .dropna(subset=["gene_id"])
        .drop_duplicates("_gene_norm", keep="first")
    )

    disease_map = (
        df_disease.assign(_disease_norm=df_disease["disease_name"].astype(str).str.strip().str.upper())
        [["_disease_norm", "disease_id"]]
        .dropna(subset=["disease_id"])
        .drop_duplicates("_disease_norm", keep="first")
    )

    drug_map = (
        df_drug.assign(_drug_norm=df_drug["drug_name"].astype(str).str.strip().str.upper())
        [["_drug_norm", "drug_id"]]
        .dropna(subset=["drug_id"])
        .drop_duplicates("_drug_norm", keep="first")
    )

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    for model, model_payload in dct_result.items():
        dct_jaccard[model] = {}
        print(f"\nWorking for model: {model}")

        for question_key, runs_dict in model_payload.items():
            run_sets = {}

            for run_number, run_payload in runs_dict.items():
                df = run_payload.get("dataframe")

                # ---- basic validity ----
                if not isinstance(df, pd.DataFrame) or df.empty:
                    continue

                if "pathway_name" in df.columns:
                    continue

                work_df = df.copy()

                # print(work_df.head())

                final_cols = []

                # ---- gene ----
                if "gene_name" in work_df.columns:
                    work_df["_gene_norm"] = (
                        work_df["gene_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(gene_map, on="_gene_norm", how="left")
                    final_cols.append("gene_id")

                # ---- disease ----
                if "disease_name" in work_df.columns:
                    work_df["_disease_norm"] = (
                        work_df["disease_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(disease_map, on="_disease_norm", how="left")
                    final_cols.append("disease_id")

                # ---- drug ----
                if "drug_name" in work_df.columns:
                    work_df["_drug_norm"] = (
                        work_df["drug_name"].astype(str).str.strip().str.upper()
                    )
                    work_df = work_df.merge(drug_map, on="_drug_norm", how="left")
                    final_cols.append("drug_id")

                if not final_cols:
                    continue

                # ---- canonical ID dataframe ----
                id_df = (
                    work_df[final_cols]
                    .dropna(how="any")
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

                dct_result[model][question_key][run_number]["dataframe_id"] = id_df

                if id_df.empty:
                    continue

                # ---- CASE-INDEPENDENT tuple set ----
                run_set = {
                    tuple(str(v).strip().upper() for v in row)
                    for row in id_df.itertuples(index=False, name=None)
                }

                if run_set:
                    run_sets[run_number] = run_set

            # ------------------------------------------------------------------
            # Compute intersection / union
            # ------------------------------------------------------------------
            n_valid_runs = len(run_sets)

            if n_valid_runs < 2:
                print(
                    f"Not enough valid runs for '{question_key}' "
                    f"({n_valid_runs}/{len(runs_dict)}). Skipping."
                )
                continue

            sets = list(run_sets.values())
            intersection = set.intersection(*sets)
            union = set.union(*sets)

            if not union:
                print(f"Empty union for '{question_key}', skipping.")
                continue

            jaccard = len(intersection) / len(union)

            dct_jaccard[model][question_key] = {
                "jaccard": jaccard,
                "n_valid_runs": n_valid_runs,
                "intersection": intersection,
                "union": union,
            }

            print(
                f"'{question_key}': "
                f"J={jaccard:.4f}, "
                f"|∩|={len(intersection)}, "
                f"|∪|={len(union)}, "
                f"runs={n_valid_runs}"
            )

    return dct_jaccard


dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

Working for model: ttd
'Which diseases are associated with BRAF?': J=1.0000, |∩|=4, |∪|=4, runs=5
Not enough valid runs for 'Which genes are associated with amyotrophic lateral sclerosis?' (0/0). Skipping.
'Which diseases are associated with CDK4?': J=1.0000, |∩|=9, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=1.0000, |∩|=140, |∪|=140, runs=5
'Which genes are associated with ovarian cancer?': J=1.0000, |∩|=83, |∪|=83, runs=5
'What are the known targets of regorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=4
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
'Which genes are associated with fever (pyrexia)?': J=0.2857, |∩|=2, |∪|=7, runs=5
'Which diseases are treated with bevacizumab?': J=1.0000, |∩|=3, |∪|=3, runs=5
'What are the known targets of cabozantinib?': J=1.0000, |∩|=2, |∪|=2, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
Not enough valid runs for 'Which diseases are associated with the NPM1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=1.0000, |∩|=35, |∪|=35, runs=5
Not enough valid runs for 'What drugs are used to treat rickets?' (0/0). Skipping.
'Which genes are associated with epilepsy?': J=1.0000, |∩|=52, |∪|=52, runs=5
Not enough valid runs for 'Which diseases are treated with trastuzumab deruxtecan?' (0/0). Skipping.
'Which genes are associated with Alzheimer’s disease?': J=1.0000, |∩|=144, |∪|=144, runs=5
'For which diseases is darolutamide used?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with renal cell carcinoma?': J=1.0000, |∩|=46, |∪|=46, runs=5
'Which diseases are associated with the KRAS gene?': J=1.0000, |∩|=2, |∪|=2, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=1.0000, |∩|=55, |∪|=55, runs=5
'Which diseases are treated with valdecoxib?': J=1.0000, |∩|=1, |∪|=1, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=3, |∪|=3, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.7000, |∩|=14, |∪|=20, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which drugs are used to treat chronic myeloid leukemia?': J=1.0000, |∩|=13, |∪|=13, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=1.0000, |∩|=78, |∪|=78, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=1.0000, |∩|=90, |∪|=90, runs=5
'Which targets are acted on by imatinib?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which biological targets does sorafenib interact with?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which biological targets does tofacitinib interact with?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which drugs target EGFR?': J=1.0000, |∩|=50, |∪|=50, runs=5
'Which diseases are associated with TP53?': J=1.0000, |∩|=21, |∪|=21, runs=5
'Which diseases are associated with FGFR2?': J=1.0000, |∩|=10, |∪|=10, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=19, |∪|=19, runs=5
'Which genes are associated with breast cancer?': J=1.0000, |∩|=157, |∪|=157, runs=5
'Which genes are associated with colorectal cancer?': J=1.0000, |∩|=114, |∪|=114, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=26, |∪|=26, runs=5
Not enough valid runs for 'Which drugs are used to treat TNBC?' (0/0). Skipping.
'Which diseases are treated with metformin?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which diseases are treated with adalimumab?': J=1.0000, |∩|=2, |∪|=2, runs=5
'For which diseases is pembrolizumab used?': J=1.0000, |∩|=9, |∪|=9, runs=5
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which diseases are treated with nivolumab?': J=1.0000, |∩|=15, |∪|=15, runs=5
'Which genes are associated with multiple sclerosis?': J=1.0000, |∩|=78, |∪|=78, runs=5
'Which genes are associated with rheumatoid arthritis?': J=1.0000, |∩|=151, |∪|=151, runs=5
'What are the known targets of abatacept?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with lung cancer?': J=1.0000, |∩|=159, |∪|=159, runs=5
'What are the known targets of ponatinib?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.8261, |∩|=38, |∪|=46, runs=5
'Which genes are associated with autism spectrum disorder?': J=1.0000, |∩|=11, |∪|=11, runs=5
'Which diseases are associated with the ROS1 gene?': J=1.0000, |∩|=5, |∪|=5, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=8, |∪|=8, runs=5
'Which diseases are associated with the EGFR gene?': J=1.0000, |∩|=30, |∪|=30, runs=5
'Which genes are associated with psoriasis?': J=0.8880, |∩|=111, |∪|=125, runs=5
'Which genes are associated with ulcerative colitis?': J=1.0000, |∩|=43, |∪|=43, runs=5
'Which genes are associated with tuberculosis?': J=0.5000, |∩|=3, |∪|=6, runs=5
Not enough valid runs for 'Which genes are associated with hepatitis C?' (0/0). Skipping.
'Which genes are associated with Hodgkin lymphoma?': J=1.0000, |∩|=11, |∪|=11, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=1.0000, |∩|=28, |∪|=28, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
'Which drugs target CD19?': J=1.0000, |∩|=10, |∪|=10, runs=5
'Which drugs target CTLA4?': J=1.0000, |∩|=12, |∪|=12, runs=5

In [25]:
# Run Jaccard consistency computation across runs after ID grounding.
dct_jaccard = compute_jaccard_from_run_dataframes(
    dct_result=dct_result,
    df_gene=df_gene,
    df_disease=df_disease,
    df_drug=df_drug,
)

# Flatten into a quick summary table for inspection.
rows = [
    {
        "model": model,
        "question": question,
        "jaccard": payload["jaccard"],
        "n_valid_runs": payload["n_valid_runs"],
        "intersection_size": len(payload["intersection"]),
        "union_size": len(payload["union"]),
    }
    for model, qmap in dct_jaccard.items()
    for question, payload in qmap.items()
]

jaccard_summary = pd.DataFrame(rows)
if jaccard_summary.empty:
    print("No valid Jaccard entries were produced. Check input runs and validation filters.")
else:
    display(jaccard_summary.sort_values(["model", "jaccard"], ascending=[True, False]).head(20))

Working for model: ttd
'Which diseases are associated with BRAF?': J=1.0000, |∩|=4, |∪|=4, runs=5
Not enough valid runs for 'Which genes are associated with amyotrophic lateral sclerosis?' (0/0). Skipping.
'Which diseases are associated with CDK4?': J=1.0000, |∩|=9, |∪|=9, runs=5
Not enough valid runs for 'Which pathways are associated with the JAK2 gene?' (0/5). Skipping.
'Which drugs are used to treat rheumatoid arthritis?': J=1.0000, |∩|=140, |∪|=140, runs=5
'Which genes are associated with ovarian cancer?': J=1.0000, |∩|=83, |∪|=83, runs=5
'What are the known targets of regorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=4
Not enough valid runs for 'Which pathways are associated with the STAT3 gene?' (0/5). Skipping.
'Which genes are associated with fever (pyrexia)?': J=0.2857, |∩|=2, |∪|=7, runs=5
'Which diseases are treated with bevacizumab?': J=1.0000, |∩|=3, |∪|=3, runs=5
'What are the known targets of cabozantinib?': J=1.0000, |∩|=2, |∪|=2, runs=5
Not enough valid runs for 'Which pathways are associated with the TNF gene?' (0/5). Skipping.
Not enough valid runs for 'Which diseases are associated with the NPM1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the CD19 gene?' (0/5). Skipping.
'Which drugs are used to treat migraine?': J=1.0000, |∩|=35, |∪|=35, runs=5
Not enough valid runs for 'What drugs are used to treat rickets?' (0/0). Skipping.
'Which genes are associated with epilepsy?': J=1.0000, |∩|=52, |∪|=52, runs=5
Not enough valid runs for 'Which diseases are treated with trastuzumab deruxtecan?' (0/0). Skipping.
'Which genes are associated with Alzheimer’s disease?': J=1.0000, |∩|=144, |∪|=144, runs=5
'For which diseases is darolutamide used?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with renal cell carcinoma?': J=1.0000, |∩|=46, |∪|=46, runs=5
'Which diseases are associated with the KRAS gene?': J=1.0000, |∩|=2, |∪|=2, runs=5
Not enough valid runs for 'Which pathways are associated with the APP gene?' (0/5). Skipping.
'Which genes are associated with schizophrenia?': J=1.0000, |∩|=55, |∪|=55, runs=5
'Which diseases are treated with valdecoxib?': J=1.0000, |∩|=1, |∪|=1, runs=5
'What are the known targets of vandetanib?': J=1.0000, |∩|=3, |∪|=3, runs=5
Not enough valid runs for 'Which pathways are associated with the CFTR gene?' (0/5). Skipping.
'Which drugs are used to treat tuberculosis?': J=0.7000, |∩|=14, |∪|=20, runs=5
'Which drugs are used to treat pancreatic adenocarcinoma?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which drugs are used to treat chronic myeloid leukemia?': J=1.0000, |∩|=13, |∪|=13, runs=5
'Which drugs are used to treat Parkinson’s disease?': J=1.0000, |∩|=78, |∪|=78, runs=5
'Which drugs are used to treat inflammatory bowel disease?': J=1.0000, |∩|=90, |∪|=90, runs=5
'Which targets are acted on by imatinib?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which biological targets does sorafenib interact with?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which biological targets does tofacitinib interact with?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which drugs target EGFR?': J=1.0000, |∩|=50, |∪|=50, runs=5
'Which diseases are associated with TP53?': J=1.0000, |∩|=21, |∪|=21, runs=5
'Which diseases are associated with FGFR2?': J=1.0000, |∩|=10, |∪|=10, runs=5
'Which diseases are associated with HTT?': J=1.0000, |∩|=19, |∪|=19, runs=5
'Which genes are associated with breast cancer?': J=1.0000, |∩|=157, |∪|=157, runs=5
'Which genes are associated with colorectal cancer?': J=1.0000, |∩|=114, |∪|=114, runs=5
'Which genes are associated with cystic fibrosis?': J=1.0000, |∩|=26, |∪|=26, runs=5
Not enough valid runs for 'Which drugs are used to treat TNBC?' (0/0). Skipping.
'Which diseases are treated with metformin?': J=1.0000, |∩|=2, |∪|=2, runs=5
'Which diseases are treated with adalimumab?': J=1.0000, |∩|=2, |∪|=2, runs=5
'For which diseases is pembrolizumab used?': J=1.0000, |∩|=9, |∪|=9, runs=5
'Which diseases are treated with sorafenib?': J=1.0000, |∩|=3, |∪|=3, runs=5
'Which diseases are treated with nivolumab?': J=1.0000, |∩|=15, |∪|=15, runs=5
'Which genes are associated with multiple sclerosis?': J=1.0000, |∩|=78, |∪|=78, runs=5
'Which genes are associated with rheumatoid arthritis?': J=1.0000, |∩|=151, |∪|=151, runs=5
'What are the known targets of abatacept?': J=1.0000, |∩|=1, |∪|=1, runs=5
'Which genes are associated with lung cancer?': J=1.0000, |∩|=159, |∪|=159, runs=5
'What are the known targets of ponatinib?': J=1.0000, |∩|=4, |∪|=4, runs=5
'Which drugs are used to treat systemic lupus erythematosus?': J=0.8261, |∩|=38, |∪|=46, runs=5
'Which genes are associated with autism spectrum disorder?': J=1.0000, |∩|=11, |∪|=11, runs=5
'Which diseases are associated with the ROS1 gene?': J=1.0000, |∩|=5, |∪|=5, runs=5
'Which diseases are associated with the ALK gene?': J=1.0000, |∩|=8, |∪|=8, runs=5
'Which diseases are associated with the EGFR gene?': J=1.0000, |∩|=30, |∪|=30, runs=5
'Which genes are associated with psoriasis?': J=0.8880, |∩|=111, |∪|=125, runs=5
'Which genes are associated with ulcerative colitis?': J=1.0000, |∩|=43, |∪|=43, runs=5
'Which genes are associated with tuberculosis?': J=0.5000, |∩|=3, |∪|=6, runs=5
Not enough valid runs for 'Which genes are associated with hepatitis C?' (0/0). Skipping.
'Which genes are associated with Hodgkin lymphoma?': J=1.0000, |∩|=11, |∪|=11, runs=5
Not enough valid runs for 'Which pathways are associated with TP53?' (0/5). Skipping.
'Which drugs target ERBB2?': J=1.0000, |∩|=28, |∪|=28, runs=5
Not enough valid runs for 'Which pathways are associated with the ADRB1 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the DRD2 gene?' (0/5). Skipping.
Not enough valid runs for 'Which pathways are associated with the HTR2A gene?' (0/5). Skipping.
'Which drugs target CD19?': J=1.0000, |∩|=10, |∪|=10, runs=5
'Which drugs target CTLA4?': J=1.0000, |∩|=12, |∪|=12, runs=5

,model,question,jaccard,n_valid_runs,intersection_size,union_size
0,ttd,Which diseases are associated with BRAF?,1.0,5,4,4
1,ttd,Which diseases are associated with CDK4?,1.0,5,9,9
2,ttd,Which drugs are used to treat rheumatoid arthr...,1.0,5,140,140
3,ttd,Which genes are associated with ovarian cancer?,1.0,5,83,83
4,ttd,What are the known targets of regorafenib?,1.0,4,3,3
6,ttd,Which diseases are treated with bevacizumab?,1.0,5,3,3
7,ttd,What are the known targets of cabozantinib?,1.0,5,2,2
8,ttd,Which drugs are used to treat migraine?,1.0,5,35,35
9,ttd,Which genes are associated with epilepsy?,1.0,5,52,52
10,ttd,Which genes are associated with Alzheimer’s di...,1.0,5,144,144
11,ttd,For which diseases is darolutamide used?,1.0,5,1,1
12,ttd,Which genes are associated with renal cell car...,1.0,5,46,46
13,ttd,Which diseases are associated with the KRAS gene?,1.0,5,2,2
14,ttd,Which genes are associated with schizophrenia?,1.0,5,55,55
15,ttd,Which diseases are treated with valdecoxib?,1.0,5,1,1
16,ttd,What are the known targets of vandetanib?,1.0,5,3,3
18,ttd,Which drugs are used to treat pancreatic adeno...,1.0,5,4,4
19,ttd,Which drugs are used to treat chronic myeloid ...,1.0,5,13,13
20,ttd,Which drugs are used to treat Parkinson’s dise...,1.0,5,78,78
21,ttd,Which drugs are used to treat inflammatory bow...,1.0,5,90,90

In [26]:
# Persist enriched run payloads with dataframe_id attached for each run.
with open("TTD_same_question_response_with_id.pkl", "wb") as f:
    pickle.dump(dct_result, f)