In [2]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
from opentarget_utility import retrieve_opentarget

In [3]:
model = "OpenTargets"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 3)


## Question 1

**Provide the complete list of molecular targets associated with chronic myeloid leukemia (CML) in Open Targets**

In [4]:

question = 'Provide the complete list of molecular targets associated with chronic myeloid leukemia (CML) in Open Targets'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide the complete list of molecular targets associated with chronic myeloid leukemia (CML) in Open Targets
  Attempt 1/3
[disease_tool]: Retrieved 4916 targets for disease chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 4916

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000339,chronic myelogenous leukemia,ENSG00000097007,ABL1,"ABL proto-oncogene 1, non-receptor tyrosine ki...",0.829035

 Run 1 completed | rows=4916 | latency=21.220s
------------------------------------------------------------

 Starting run 2 for query: Provide the complete list of molecular targets associated with chronic myeloid leukemia (CML) in Open Targets
  Attempt 1/3
[disease_tool]: Retrieved 4916 targets for disease chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 4916

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000339,chronic myelogenous leukemia,ENSG00000097007,ABL1,"ABL proto-oncogene 1, non-receptor tyrosine ki...",0.829035

 Run 2 completed | rows=4916 | latency=17.828s
------------------------------------------------------------


## Question 2

**Provide the top-ranked molecular targets associated with chronic myeloid leukemia (CML) in Open Targets.**

In [5]:

question = 'Provide the top-ranked molecular targets associated with chronic myeloid leukemia (CML) in Open Targets.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide the top-ranked molecular targets associated with chronic myeloid leukemia (CML) in Open Targets.
  Attempt 1/3
[disease_tool]: Retrieved 4916 targets for disease chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 4916

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000339,chronic myelogenous leukemia,ENSG00000097007,ABL1,"ABL proto-oncogene 1, non-receptor tyrosine ki...",0.829035

 Run 1 completed | rows=4916 | latency=18.115s
------------------------------------------------------------

 Starting run 2 for query: Provide the top-ranked molecular targets associated with chronic myeloid leukemia (CML) in Open Targets.
  Attempt 1/3
[disease_tool]: Retrieved 4916 targets for disease chronic myeloid leukemia.
----------------------------------------
Entries retrieved: 4916

,disease_id,disease_name,gene_id,gene_symbol,target_name,association_score
0,EFO_0000339,chronic myelogenous leukemia,ENSG00000097007,ABL1,"ABL proto-oncogene 1, non-receptor tyrosine ki...",0.829035

 Run 2 completed | rows=4916 | latency=15.587s
------------------------------------------------------------


## Question 3

**List the top diseases treated with aspirin according to Open Targets.**

In [6]:

question = 'List the top diseases treated with aspirin according to Open Targets.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List the top diseases treated with aspirin according to Open Targets.
  Attempt 1/3
[drug_tool]: The intent of the query was to find specific drug associations related to aspirin.
[drug_tool]: First, the system retrieved known disease-drug associations for aspirin, resulting in a total of 726 rows.
[drug_tool]: Next, the system performed a deduplication step to remove any duplicate entries, reducing the number of rows from 726 to 363. This step ensured that only unique associations remained in the dataset.
[drug_tool]: In summary, the process narrowed down the initial set of associations to 363 unique entries related to aspirin.
----------------------------------------
Entries retrieved: 363

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL25,ASPIRIN,EFO_0008583,acute myocardial infarction,4.0,Completed,Cyclooxygenase inhibitor,"PubMed, Wikipedia"

 Run 1 completed | rows=363 | latency=14.566s
------------------------------------------------------------

 Starting run 2 for query: List the top diseases treated with aspirin according to Open Targets.
  Attempt 1/3
[drug_tool]: The goal of the query was to identify drug associations related to aspirin. First, the system retrieved known drug associations for aspirin, resulting in 726 entries. Next, it performed a deduplication process to remove duplicate records, which reduced the number of entries from 726 to 363. In total, the process ended with 363 unique associations related to aspirin.
----------------------------------------
Entries retrieved: 363

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL25,ASPIRIN,EFO_0008583,acute myocardial infarction,4.0,Completed,Cyclooxygenase inhibitor,"PubMed, Wikipedia"

 Run 2 completed | rows=363 | latency=12.766s
------------------------------------------------------------


## Question 4

**Provide the complete list of diseases treated with aspirin according to Open Targets.**

In [7]:

question = 'Provide the complete list of diseases treated with aspirin according to Open Targets.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide the complete list of diseases treated with aspirin according to Open Targets.
  Attempt 1/3
[drug_tool]: The query aimed to find drug associations related to aspirin. Initially, the system retrieved a set of associations for aspirin, resulting in 726 records. Next, it removed duplicate entries from this set, reducing the number of associations to 363. In the end, the final result contains 363 unique drug association entries related to aspirin.
----------------------------------------
Entries retrieved: 363

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL25,ASPIRIN,EFO_0008583,acute myocardial infarction,4.0,Completed,Cyclooxygenase inhibitor,"PubMed, Wikipedia"

 Run 1 completed | rows=363 | latency=14.504s
------------------------------------------------------------

 Starting run 2 for query: Provide the complete list of diseases treated with aspirin according to Open Targets.
  Attempt 1/3
[drug_tool]: The goal of the query was to identify drugs associated with the term "aspirin."
[drug_tool]: First, the system retrieved known drug associations related to aspirin, which resulted in a list of 726 entries.
[drug_tool]: Next, it performed deduplication to remove duplicate records from this list, reducing the number to 363 entries.
[drug_tool]: Overall, after these steps, the final result consists of 363 unique drug association records related to aspirin.
----------------------------------------
Entries retrieved: 363

,drug_id,drug_name,disease_id,disease_name,phase,status,mechanism_of_action,references
0,CHEMBL25,ASPIRIN,EFO_0008583,acute myocardial infarction,4.0,Completed,Cyclooxygenase inhibitor,"PubMed, Wikipedia"

 Run 2 completed | rows=363 | latency=14.317s
------------------------------------------------------------


## Question 5

**List the top diseases associated with the TP53 gene in Open Targets.**

In [8]:

question = 'List the top diseases associated with the TP53 gene in Open Targets.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: List the top diseases associated with the TP53 gene in Open Targets.
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 1 completed | rows=3258 | latency=16.816s
------------------------------------------------------------

 Starting run 2 for query: List the top diseases associated with the TP53 gene in Open Targets.
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 2 completed | rows=3258 | latency=18.038s
------------------------------------------------------------


## Question 6

**Provide the complete list of diseases associated with the TP53 gene in Open Targets.**

In [9]:

question = 'Provide the complete list of diseases associated with the TP53 gene in Open Targets.'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            start_time = time.perf_counter()
            df = await retrieve_opentarget(question)
            latency = time.perf_counter() - start_time
            
            # if latency>40:
            #     continue

            if len(df.columns)<2:
                continue

            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Provide the complete list of diseases associated with the TP53 gene in Open Targets.
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 1 completed | rows=3258 | latency=14.116s
------------------------------------------------------------

 Starting run 2 for query: Provide the complete list of diseases associated with the TP53 gene in Open Targets.
  Attempt 1/3
[target_tool]: Retrieved 3258 diseases for target TP53.
----------------------------------------
Entries retrieved: 3258

,gene_id,gene_name,disease_id,disease_name,association_score
0,ENSG00000141510,TP53,MONDO_0018875,Li-Fraumeni syndrome,0.876057

 Run 2 completed | rows=3258 | latency=13.791s
------------------------------------------------------------

In [10]:
# import pickle
# with open("Opentargets_same_question_response.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

# import json
# import pandas as pd

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("Opentargets_same_question_response.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )