In [2]:

import asyncio
import time
import json
import websockets
import requests
import pandas as pd
from pathlib import Path
# from opentarget_utility import retrieve_opentarget

from grok_utility import return_grok_answer

In [3]:



model = "grok-4-1-fast-non-reasoning-latest"
dct_result = {}
dct_result[model] = {}

MAX_RETRIES = 3
RUNS = range(1, 6)


## Question 1

**Which diseases are associated with BRAF?**

In [3]:

question = 'Which diseases are associated with BRAF?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0     Melanoma      BRAF

 Run 1 completed | rows=4 | latency=1.800s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0     Melanoma      BRAF

 Run 2 completed | rows=4 | latency=0.873s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0     Melanoma      BRAF

 Run 3 completed | rows=4 | latency=1.351s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  gene_name disease_name
0      BRAF     Melanoma

 Run 4 completed | rows=4 | latency=0.783s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with BRAF?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0     Melanoma      BRAF

 Run 5 completed | rows=4 | latency=0.878s
------------------------------------------------------------


## Question 2

**Which genes are associated with amyotrophic lateral sclerosis?**

In [4]:

question = 'Which genes are associated with amyotrophic lateral sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 1 completed | rows=4 | latency=0.818s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 2 completed | rows=4 | latency=0.905s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 3 completed | rows=4 | latency=0.844s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 4

  gene_name                   disease_name
0      SOD1  amyotrophic lateral sclerosis

 Run 4 completed | rows=4 | latency=1.137s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with amyotrophic lateral sclerosis?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Amyotrophic lateral sclerosis      SOD1

 Run 5 completed | rows=4 | latency=0.876s
------------------------------------------------------------


## Question 3

**Which diseases are associated with CDK4?**

In [5]:

question = 'Which diseases are associated with CDK4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 1 completed | rows=2 | latency=0.820s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 2 completed | rows=2 | latency=0.702s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 3 completed | rows=2 | latency=0.946s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  gene_name disease_name
0      CDK4     Melanoma

 Run 4 completed | rows=2 | latency=0.945s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with CDK4?
  Attempt 1/3
Entries retrieved: 2

  disease_name gene_name
0     Melanoma      CDK4

 Run 5 completed | rows=2 | latency=1.104s
------------------------------------------------------------


## Question 4

**Which pathways are associated with the JAK2 gene?**

In [6]:

question = 'Which pathways are associated with the JAK2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 1 completed | rows=1 | latency=0.758s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 2 completed | rows=1 | latency=0.736s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 3 completed | rows=1 | latency=0.641s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 4 completed | rows=1 | latency=0.702s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the JAK2 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway      JAK2

 Run 5 completed | rows=1 | latency=0.648s
------------------------------------------------------------


## Question 5

**Which drugs are used to treat rheumatoid arthritis?**

In [7]:

question = 'Which drugs are used to treat rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

      drug_name          disease_name
0  Methotrexate  rheumatoid arthritis

 Run 1 completed | rows=8 | latency=1.091s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 6

      drug_name          disease_name
0  Methotrexate  rheumatoid arthritis

 Run 2 completed | rows=6 | latency=0.960s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 6

      drug_name          disease_name
0  Methotrexate  rheumatoid arthritis

 Run 3 completed | rows=6 | latency=1.238s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 8

      drug_name          disease_name
0  Methotrexate  rheumatoid arthritis

 Run 4 completed | rows=8 | latency=1.285s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 7

      drug_name          disease_name
0  Methotrexate  rheumatoid arthritis

 Run 5 completed | rows=7 | latency=1.125s
------------------------------------------------------------


## Question 6

**Which genes are associated with ovarian cancer?**

In [8]:

question = 'Which genes are associated with ovarian cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 1 completed | rows=3 | latency=0.944s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

     disease_name gene_name
0  ovarian cancer     BRCA1

 Run 2 completed | rows=3 | latency=0.839s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

     disease_name gene_name
0  ovarian cancer     BRCA1

 Run 3 completed | rows=3 | latency=0.771s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

     disease_name gene_name
0  ovarian cancer     BRCA1

 Run 4 completed | rows=3 | latency=0.815s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ovarian cancer?
  Attempt 1/3
Entries retrieved: 3

     disease_name gene_name
0  Ovarian cancer     BRCA1

 Run 5 completed | rows=3 | latency=0.758s
------------------------------------------------------------


## Question 7

**What are the known targets of regorafenib?**

In [9]:

question = 'What are the known targets of regorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 7

     drug_name gene_name
0  regorafenib      FLT3

 Run 1 completed | rows=7 | latency=1.416s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name gene_name
0  regorafenib       KIT

 Run 2 completed | rows=9 | latency=1.195s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 7

     drug_name gene_name
0  regorafenib      FLT3

 Run 3 completed | rows=7 | latency=0.838s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 7

     drug_name gene_name
0  regorafenib       RET

 Run 4 completed | rows=7 | latency=0.932s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of regorafenib?
  Attempt 1/3
Entries retrieved: 9

     drug_name gene_name
0  regorafenib       RET

 Run 5 completed | rows=9 | latency=1.157s
------------------------------------------------------------


## Question 8

**Which pathways are associated with the STAT3 gene?**

In [10]:

question = 'Which pathways are associated with the STAT3 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 1 completed | rows=2 | latency=0.912s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 2 completed | rows=2 | latency=0.848s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 2

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 3 completed | rows=2 | latency=0.923s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

                 pathway_name gene_name
0  JAK-STAT signaling pathway     STAT3

 Run 4 completed | rows=1 | latency=0.766s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the STAT3 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                pathway_name
0     STAT3  JAK-STAT signaling pathway

 Run 5 completed | rows=1 | latency=0.925s
------------------------------------------------------------


## Question 9

**Which genes are associated with fever (pyrexia)?**

In [11]:

question = 'Which genes are associated with fever (pyrexia)?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0        Fever      IL1B

 Run 1 completed | rows=4 | latency=1.079s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0        Fever      IL1B

 Run 2 completed | rows=3 | latency=0.822s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0        Fever      IL1B

 Run 3 completed | rows=3 | latency=0.871s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0        Fever      IL1B

 Run 4 completed | rows=4 | latency=0.945s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with fever (pyrexia)?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0      Pyrexia      IL1B

 Run 5 completed | rows=4 | latency=0.803s
------------------------------------------------------------


## Question 10

**Which diseases are treated with bevacizumab?**

In [12]:

question = 'Which diseases are treated with bevacizumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  bevacizumab  Colorectal cancer

  Attempt 2/3
Entries retrieved: 7

     drug_name       disease_name
0  Bevacizumab  Colorectal cancer

 Run 1 completed | rows=7 | latency=0.950s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  bevacizumab  Colorectal cancer

 Run 2 completed | rows=7 | latency=1.110s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  bevacizumab  colorectal cancer

 Run 3 completed | rows=7 | latency=0.993s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  bevacizumab  Colorectal cancer

 Run 4 completed | rows=7 | latency=1.055s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with bevacizumab?
  Attempt 1/3
Entries retrieved: 7

     drug_name       disease_name
0  bevacizumab  Colorectal cancer

 Run 5 completed | rows=7 | latency=1.048s
------------------------------------------------------------


## Question 11

**What are the known targets of cabozantinib?**

In [13]:

question = 'What are the known targets of cabozantinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 6

      drug_name gene_name
0  cabozantinib      FLT3

 Run 1 completed | rows=6 | latency=1.006s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 5

      drug_name gene_name
0  cabozantinib       KIT

 Run 2 completed | rows=5 | latency=0.919s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 8

      drug_name gene_name
0  cabozantinib      FLT3

 Run 3 completed | rows=8 | latency=1.169s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 4

      drug_name gene_name
0  cabozantinib       RET

 Run 4 completed | rows=4 | latency=1.051s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of cabozantinib?
  Attempt 1/3
Entries retrieved: 7

      drug_name gene_name
0  cabozantinib      FLT3

 Run 5 completed | rows=7 | latency=1.118s
------------------------------------------------------------


## Question 12

**Which pathways are associated with the TNF gene?**

In [14]:

question = 'Which pathways are associated with the TNF gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

                  pathway_name gene_name
0  NF-kappaB signaling pathway       TNF

 Run 1 completed | rows=3 | latency=0.861s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

                  pathway_name gene_name
0  NF-kappaB signaling pathway       TNF

 Run 2 completed | rows=4 | latency=0.975s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

            pathway_name gene_name
0  TNF signaling pathway       TNF

 Run 3 completed | rows=3 | latency=0.907s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 3

                  pathway_name gene_name
0  NF-kappaB signaling pathway       TNF

 Run 4 completed | rows=3 | latency=0.811s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the TNF gene?
  Attempt 1/3
Entries retrieved: 4

                  pathway_name gene_name
0  NF-kappaB signaling pathway       TNF

 Run 5 completed | rows=4 | latency=0.999s
------------------------------------------------------------


## Question 13

**Which diseases are associated with the NPM1 gene?**

In [15]:

question = 'Which diseases are associated with the NPM1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 1 completed | rows=1 | latency=0.917s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 2 completed | rows=1 | latency=0.726s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 3 completed | rows=1 | latency=0.697s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 4 completed | rows=1 | latency=0.791s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the NPM1 gene?
  Attempt 1/3
Entries retrieved: 1

             disease_name gene_name
0  Acute myeloid leukemia      NPM1

 Run 5 completed | rows=1 | latency=0.683s
------------------------------------------------------------


## Question 14

**Which pathways are associated with the CD19 gene?**

In [16]:

question = 'Which pathways are associated with the CD19 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                       pathway_name
0      CD19  B_cell_receptor_signaling_pathway

 Run 1 completed | rows=1 | latency=1.369s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 2 completed | rows=2 | latency=0.912s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 3 completed | rows=2 | latency=0.795s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 2

                        pathway_name gene_name
0  B cell receptor signaling pathway      CD19

 Run 4 completed | rows=2 | latency=0.887s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CD19 gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name                       pathway_name
0      CD19  B cell receptor signaling pathway

 Run 5 completed | rows=1 | latency=0.715s
------------------------------------------------------------


## Question 15

**Which drugs are used to treat migraine?**

In [17]:

question = 'Which drugs are used to treat migraine?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 10

     drug_name disease_name
0  sumatriptan     migraine

 Run 1 completed | rows=10 | latency=1.326s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 12

     drug_name disease_name
0  sumatriptan     migraine

 Run 2 completed | rows=12 | latency=1.246s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 10

     drug_name disease_name
0  sumatriptan     migraine

 Run 3 completed | rows=10 | latency=1.158s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 9

     drug_name disease_name
0  sumatriptan     migraine

 Run 4 completed | rows=9 | latency=1.494s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat migraine?
  Attempt 1/3
Entries retrieved: 10

     drug_name disease_name
0  sumatriptan     migraine

 Run 5 completed | rows=10 | latency=1.361s
------------------------------------------------------------


## Question 16

**What drugs are used to treat rickets?**

In [6]:

question = 'What drugs are used to treat rickets?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 2

        drug_name disease_name
0  Colecalciferol      rickets

 Run 1 completed | rows=2 | latency=1.780s
------------------------------------------------------------

 Starting run 2 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 2

        drug_name disease_name
0  Colecalciferol      rickets

 Run 2 completed | rows=2 | latency=0.843s
------------------------------------------------------------

 Starting run 3 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

    drug_name disease_name
0  Calcitriol      rickets

 Run 3 completed | rows=3 | latency=0.985s
------------------------------------------------------------

 Starting run 4 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 3

        drug_name disease_name
0  colecalciferol      rickets

 Run 4 completed | rows=3 | latency=0.873s
------------------------------------------------------------

 Starting run 5 for query: What drugs are used to treat rickets?
  Attempt 1/3
Entries retrieved: 2

        drug_name disease_name
0  Colecalciferol      rickets

 Run 5 completed | rows=2 | latency=1.257s
------------------------------------------------------------


## Question 17

**Which genes are associated with epilepsy?**

In [19]:

question = 'Which genes are associated with epilepsy?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 1 completed | rows=5 | latency=1.313s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 2 completed | rows=5 | latency=0.843s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 3 completed | rows=5 | latency=1.010s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 4 completed | rows=5 | latency=0.865s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with epilepsy?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0     Epilepsy     SCN1A

 Run 5 completed | rows=5 | latency=0.917s
------------------------------------------------------------


## Question 18

**Which diseases are treated with trastuzumab deruxtecan?**

In [20]:

question = 'Which diseases are treated with trastuzumab deruxtecan?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 1

                drug_name                 disease_name
0  Trastuzumab deruxtecan  HER2-positive breast cancer

 Run 1 completed | rows=1 | latency=0.905s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 1

                drug_name      disease_name
0  Trastuzumab deruxtecan  Breast carcinoma

 Run 2 completed | rows=1 | latency=0.780s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 1

                drug_name      disease_name
0  Trastuzumab deruxtecan  Breast carcinoma

 Run 3 completed | rows=1 | latency=0.652s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 1

                drug_name   disease_name
0  Trastuzumab deruxtecan  Breast cancer

 Run 4 completed | rows=1 | latency=0.735s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with trastuzumab deruxtecan?
  Attempt 1/3
Entries retrieved: 1

                drug_name   disease_name
0  Trastuzumab deruxtecan  Breast cancer

 Run 5 completed | rows=1 | latency=0.825s
------------------------------------------------------------


## Question 19

**Which genes are associated with Alzheimer’s disease?**

In [21]:

question = 'Which genes are associated with Alzheimer’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer’s disease

 Run 1 completed | rows=4 | latency=0.860s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 2 completed | rows=4 | latency=0.887s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 3 completed | rows=4 | latency=0.806s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 4 completed | rows=4 | latency=0.838s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Alzheimer’s disease?
  Attempt 1/3
Entries retrieved: 4

  gene_name         disease_name
0       APP  Alzheimer's disease

 Run 5 completed | rows=4 | latency=0.879s
------------------------------------------------------------


## Question 20

**For which diseases is darolutamide used?**

In [22]:

question = 'For which diseases is darolutamide used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  darolutamide  Prostate cancer

 Run 1 completed | rows=1 | latency=0.798s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  darolutamide  Prostate cancer

 Run 2 completed | rows=1 | latency=0.920s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  darolutamide  Prostate cancer

 Run 3 completed | rows=1 | latency=0.616s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  darolutamide  Prostate cancer

 Run 4 completed | rows=1 | latency=0.756s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is darolutamide used?
  Attempt 1/3
Entries retrieved: 1

      drug_name     disease_name
0  darolutamide  Prostate cancer

 Run 5 completed | rows=1 | latency=0.722s
------------------------------------------------------------


## Question 21

**Which genes are associated with renal cell carcinoma?**

In [23]:

question = 'Which genes are associated with renal cell carcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 1 completed | rows=5 | latency=1.008s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 2 completed | rows=5 | latency=1.037s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 3 completed | rows=5 | latency=0.877s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 4 completed | rows=5 | latency=0.834s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with renal cell carcinoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0       VHL  renal cell carcinoma

 Run 5 completed | rows=5 | latency=1.018s
------------------------------------------------------------


## Question 22

**Which diseases are associated with the KRAS gene?**

In [24]:

question = 'Which diseases are associated with the KRAS gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

          disease_name gene_name
0  Lung adenocarcinoma      KRAS

 Run 1 completed | rows=3 | latency=1.270s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

                    disease_name gene_name
0  Non-small cell lung carcinoma      KRAS

 Run 2 completed | rows=3 | latency=0.934s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

                    disease_name gene_name
0  Non-small cell lung carcinoma      KRAS

 Run 3 completed | rows=3 | latency=0.741s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

          disease_name gene_name
0  Lung adenocarcinoma      KRAS

 Run 4 completed | rows=3 | latency=0.812s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the KRAS gene?
  Attempt 1/3
Entries retrieved: 3

                    disease_name gene_name
0  Non-small cell lung carcinoma      KRAS

 Run 5 completed | rows=3 | latency=1.049s
------------------------------------------------------------


## Question 23

**Which pathways are associated with the APP gene?**

In [25]:

question = 'Which pathways are associated with the APP gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

          pathway_name gene_name
0  Alzheimer's disease       APP

 Run 1 completed | rows=2 | latency=0.887s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

          pathway_name gene_name
0  Alzheimer's disease       APP

 Run 2 completed | rows=2 | latency=0.740s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name         pathway_name
0       APP  Alzheimer's disease

 Run 3 completed | rows=2 | latency=0.869s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name         pathway_name
0       APP  Alzheimer's disease

 Run 4 completed | rows=2 | latency=0.704s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the APP gene?
  Attempt 1/3
Entries retrieved: 2

          pathway_name gene_name
0  Alzheimer's disease       APP

 Run 5 completed | rows=2 | latency=0.880s
------------------------------------------------------------


## Question 24

**Which genes are associated with schizophrenia?**

In [26]:

question = 'Which genes are associated with schizophrenia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 1 completed | rows=5 | latency=1.278s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 2 completed | rows=5 | latency=0.814s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 3 completed | rows=5 | latency=0.925s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 4 completed | rows=5 | latency=0.809s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with schizophrenia?
  Attempt 1/3
Entries retrieved: 5

    disease_name gene_name
0  Schizophrenia      DRD2

 Run 5 completed | rows=5 | latency=0.824s
------------------------------------------------------------


## Question 25

**Which diseases are treated with valdecoxib?**

In [27]:

question = 'Which diseases are treated with valdecoxib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 1 completed | rows=2 | latency=1.087s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  Osteoarthritis

 Run 2 completed | rows=2 | latency=0.690s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  Valdecoxib  osteoarthritis

 Run 3 completed | rows=2 | latency=0.752s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  Valdecoxib  Osteoarthritis

 Run 4 completed | rows=2 | latency=0.698s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with valdecoxib?
  Attempt 1/3
Entries retrieved: 2

    drug_name    disease_name
0  valdecoxib  Osteoarthritis

 Run 5 completed | rows=2 | latency=0.650s
------------------------------------------------------------


## Question 26

**What are the known targets of vandetanib?**

In [28]:

question = 'What are the known targets of vandetanib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       RET

 Run 1 completed | rows=3 | latency=0.806s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       RET

 Run 2 completed | rows=3 | latency=0.712s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       RET

 Run 3 completed | rows=3 | latency=0.839s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       RET

 Run 4 completed | rows=3 | latency=0.768s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of vandetanib?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  vandetanib       RET

 Run 5 completed | rows=3 | latency=0.800s
------------------------------------------------------------


## Question 27

**Which pathways are associated with the CFTR gene?**

In [29]:

question = 'Which pathways are associated with the CFTR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name      pathway_name
0      CFTR  ABC transporters

 Run 1 completed | rows=1 | latency=0.802s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

      pathway_name gene_name
0  CFTR regulation      CFTR

 Run 2 completed | rows=1 | latency=0.674s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

       pathway_name gene_name
0  ABC transporters      CFTR

 Run 3 completed | rows=1 | latency=0.892s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name      pathway_name
0      CFTR  ABC transporters

 Run 4 completed | rows=1 | latency=0.780s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the CFTR gene?
  Attempt 1/3
Entries retrieved: 1

  gene_name      pathway_name
0      CFTR  ABC transporters

 Run 5 completed | rows=1 | latency=0.787s
------------------------------------------------------------


## Question 28

**Which drugs are used to treat tuberculosis?**

In [30]:

question = 'Which drugs are used to treat tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 1 completed | rows=4 | latency=0.779s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 2 completed | rows=4 | latency=0.895s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 3 completed | rows=4 | latency=0.828s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 4 completed | rows=4 | latency=0.789s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   drug_name  disease_name
0  Isoniazid  Tuberculosis

 Run 5 completed | rows=4 | latency=0.959s
------------------------------------------------------------


## Question 29

**Which drugs are used to treat pancreatic adenocarcinoma?**

In [31]:

question = 'Which drugs are used to treat pancreatic adenocarcinoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 1 completed | rows=5 | latency=1.216s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 2 completed | rows=5 | latency=0.943s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 3 completed | rows=6 | latency=1.174s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 6

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 4 completed | rows=6 | latency=0.868s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat pancreatic adenocarcinoma?
  Attempt 1/3
Entries retrieved: 5

     drug_name               disease_name
0  gemcitabine  pancreatic adenocarcinoma

 Run 5 completed | rows=5 | latency=1.237s
------------------------------------------------------------


## Question 30

**Which drugs are used to treat chronic myeloid leukemia?**

In [32]:

question = 'Which drugs are used to treat chronic myeloid leukemia?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  chronic myeloid leukemia

 Run 1 completed | rows=5 | latency=0.827s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  chronic myeloid leukemia

 Run 2 completed | rows=5 | latency=0.929s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  chronic myeloid leukemia

 Run 3 completed | rows=5 | latency=0.777s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  chronic myeloid leukemia

 Run 4 completed | rows=5 | latency=0.754s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat chronic myeloid leukemia?
  Attempt 1/3
Entries retrieved: 5

  drug_name              disease_name
0  Imatinib  chronic myeloid leukemia

 Run 5 completed | rows=5 | latency=0.890s
------------------------------------------------------------


## Question 31

**Which drugs are used to treat Parkinson’s disease?**

In [33]:

question = 'Which drugs are used to treat Parkinson’s disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 11

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 1 completed | rows=11 | latency=1.143s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 12

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 2 completed | rows=12 | latency=1.376s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 8

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 3 completed | rows=8 | latency=0.981s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 16

                 ```csv
drug_name  disease_name

  Attempt 2/3
Entries retrieved: 12

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 4 completed | rows=12 | latency=1.238s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat Parkinson’s disease?
  Attempt 1/3
Entries retrieved: 9

  drug_name         disease_name
0  Levodopa  Parkinson's disease

 Run 5 completed | rows=9 | latency=0.998s
------------------------------------------------------------


## Question 32

**Which drugs are used to treat inflammatory bowel disease?**

In [34]:

question = 'Which drugs are used to treat inflammatory bowel disease?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 8

    drug_name                disease_name
0  Infliximab  Inflammatory bowel disease

 Run 1 completed | rows=8 | latency=1.247s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 9

    drug_name                disease_name
0  Infliximab  Inflammatory bowel disease

 Run 2 completed | rows=9 | latency=1.120s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 8

    drug_name                disease_name
0  Infliximab  Inflammatory bowel disease

 Run 3 completed | rows=8 | latency=1.152s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 7

    drug_name                disease_name
0  Adalimumab  Inflammatory bowel disease

 Run 4 completed | rows=7 | latency=1.291s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat inflammatory bowel disease?
  Attempt 1/3
Entries retrieved: 8

    drug_name                disease_name
0  Adalimumab  Inflammatory bowel disease

 Run 5 completed | rows=8 | latency=1.386s
------------------------------------------------------------


## Question 33

**Which targets are acted on by imatinib?**

In [35]:

question = 'Which targets are acted on by imatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      ABL1

 Run 1 completed | rows=4 | latency=0.921s
------------------------------------------------------------

 Starting run 2 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      ABL1

 Run 2 completed | rows=4 | latency=0.882s
------------------------------------------------------------

 Starting run 3 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      ABL1

 Run 3 completed | rows=4 | latency=1.042s
------------------------------------------------------------

 Starting run 4 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      ABL1

 Run 4 completed | rows=4 | latency=0.912s
------------------------------------------------------------

 Starting run 5 for query: Which targets are acted on by imatinib?
  Attempt 1/3
Entries retrieved: 4

  drug_name gene_name
0  imatinib      ABL1

 Run 5 completed | rows=4 | latency=0.980s
------------------------------------------------------------


## Question 34

**Which biological targets does sorafenib interact with?**

In [36]:

question = 'Which biological targets does sorafenib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 4

   drug_name gene_name
0  sorafenib      RAF1

 Run 1 completed | rows=4 | latency=0.953s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  sorafenib      RAF1

 Run 2 completed | rows=5 | latency=0.928s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 4

   drug_name gene_name
0  sorafenib      RAF1

 Run 3 completed | rows=4 | latency=0.905s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 4

   drug_name gene_name
0  sorafenib      RAF1

 Run 4 completed | rows=4 | latency=0.938s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does sorafenib interact with?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  sorafenib      RAF1

 Run 5 completed | rows=5 | latency=0.931s
------------------------------------------------------------


## Question 35

**Which biological targets does tofacitinib interact with?**

In [37]:

question = 'Which biological targets does tofacitinib interact with?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 1 completed | rows=2 | latency=0.845s
------------------------------------------------------------

 Starting run 2 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 2 completed | rows=2 | latency=0.837s
------------------------------------------------------------

 Starting run 3 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 3 completed | rows=2 | latency=0.774s
------------------------------------------------------------

 Starting run 4 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 4 completed | rows=2 | latency=0.759s
------------------------------------------------------------

 Starting run 5 for query: Which biological targets does tofacitinib interact with?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  Tofacitinib      JAK1

 Run 5 completed | rows=2 | latency=0.814s
------------------------------------------------------------


## Question 36

**Which drugs target EGFR?**

In [38]:

question = 'Which drugs target EGFR?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 8

  drug_name gene_name
0  Afatinib      EGFR

 Run 1 completed | rows=8 | latency=0.894s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Cetuximab      EGFR

 Run 2 completed | rows=6 | latency=0.920s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Gefitinib      EGFR

 Run 3 completed | rows=6 | latency=1.105s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  Cetuximab      EGFR

 Run 4 completed | rows=6 | latency=0.842s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target EGFR?
  Attempt 1/3
Entries retrieved: 8

   drug_name gene_name
0  Cetuximab      EGFR

 Run 5 completed | rows=8 | latency=1.200s
------------------------------------------------------------


## Question 37

**Which diseases are associated with TP53?**

In [39]:

question = 'Which diseases are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 1 completed | rows=5 | latency=1.150s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 2 completed | rows=5 | latency=0.982s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 3 completed | rows=5 | latency=1.033s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 4 completed | rows=5 | latency=0.904s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with TP53?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Li-Fraumeni syndrome      TP53

 Run 5 completed | rows=5 | latency=0.838s
------------------------------------------------------------


## Question 38

**Which diseases are associated with FGFR2?**

In [40]:

question = 'Which diseases are associated with FGFR2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 1 completed | rows=3 | latency=0.908s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 2 completed | rows=3 | latency=0.911s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 3 completed | rows=3 | latency=0.818s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 4

     disease_name gene_name
0  Gastric cancer     FGFR2

 Run 4 completed | rows=4 | latency=0.886s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with FGFR2?
  Attempt 1/3
Entries retrieved: 3

  gene_name    disease_name
0     FGFR2  Gastric cancer

 Run 5 completed | rows=3 | latency=0.852s
------------------------------------------------------------


## Question 39

**Which diseases are associated with HTT?**

In [41]:

question = 'Which diseases are associated with HTT?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 1 completed | rows=1 | latency=0.875s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 2 completed | rows=1 | latency=0.692s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 3 completed | rows=1 | latency=0.803s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 4 completed | rows=1 | latency=0.740s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with HTT?
  Attempt 1/3
Entries retrieved: 1

         disease_name gene_name
0  Huntington disease       HTT

 Run 5 completed | rows=1 | latency=0.712s
------------------------------------------------------------


## Question 40

**Which genes are associated with breast cancer?**

In [42]:

question = 'Which genes are associated with breast cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  breast cancer     BRCA1

 Run 1 completed | rows=3 | latency=0.759s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  breast cancer     BRCA1

 Run 2 completed | rows=3 | latency=1.103s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  breast cancer     BRCA1

 Run 3 completed | rows=3 | latency=0.723s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  breast cancer     BRCA1

 Run 4 completed | rows=3 | latency=0.674s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with breast cancer?
  Attempt 1/3
Entries retrieved: 3

    disease_name gene_name
0  breast cancer     BRCA1

 Run 5 completed | rows=3 | latency=0.700s
------------------------------------------------------------


## Question 41

**Which genes are associated with colorectal cancer?**

In [43]:

question = 'Which genes are associated with colorectal cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal cancer       APC

 Run 1 completed | rows=5 | latency=0.846s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal cancer       APC

 Run 2 completed | rows=5 | latency=0.873s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal cancer       APC

 Run 3 completed | rows=5 | latency=0.940s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal cancer       APC

 Run 4 completed | rows=5 | latency=1.044s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with colorectal cancer?
  Attempt 1/3
Entries retrieved: 5

        disease_name gene_name
0  Colorectal cancer       APC

 Run 5 completed | rows=5 | latency=0.897s
------------------------------------------------------------


## Question 42

**Which genes are associated with cystic fibrosis?**

In [44]:

question = 'Which genes are associated with cystic fibrosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 1 completed | rows=1 | latency=0.703s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 2 completed | rows=1 | latency=0.720s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 3 completed | rows=1 | latency=0.688s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

      disease_name gene_name
0  Cystic fibrosis      CFTR

 Run 4 completed | rows=1 | latency=0.798s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with cystic fibrosis?
  Attempt 1/3
Entries retrieved: 1

  gene_name     disease_name
0      CFTR  Cystic fibrosis

 Run 5 completed | rows=1 | latency=1.077s
------------------------------------------------------------


## Question 43

**Which drugs are used to treat TNBC?**

In [45]:

question = 'Which drugs are used to treat TNBC?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 8

     drug_name                   disease_name
0  Doxorubicin  triple-negative breast cancer

 Run 1 completed | rows=8 | latency=1.213s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 12

     drug_name disease_name
0  Doxorubicin         TNBC

 Run 2 completed | rows=12 | latency=1.162s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 10

     drug_name disease_name
0  Doxorubicin         TNBC

 Run 3 completed | rows=10 | latency=1.036s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 7

     drug_name disease_name
0  Doxorubicin         TNBC

 Run 4 completed | rows=7 | latency=0.886s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat TNBC?
  Attempt 1/3
Entries retrieved: 7

     drug_name disease_name
0  Doxorubicin         TNBC

 Run 5 completed | rows=7 | latency=0.954s
------------------------------------------------------------


## Question 44

**Which diseases are treated with metformin?**

In [46]:

question = 'Which diseases are treated with metformin?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  Metformin  Type 2 diabetes mellitus

 Run 1 completed | rows=1 | latency=0.784s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  Metformin  Type 2 diabetes mellitus

 Run 2 completed | rows=1 | latency=0.670s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  Metformin  Type 2 diabetes mellitus

 Run 3 completed | rows=1 | latency=0.715s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  metformin  type 2 diabetes mellitus

 Run 4 completed | rows=1 | latency=0.853s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with metformin?
  Attempt 1/3
Entries retrieved: 1

   drug_name              disease_name
0  Metformin  type 2 diabetes mellitus

 Run 5 completed | rows=1 | latency=0.655s
------------------------------------------------------------


## Question 45

**Which diseases are treated with adalimumab?**

In [47]:

question = 'Which diseases are treated with adalimumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid arthritis

 Run 1 completed | rows=8 | latency=1.034s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 8

    drug_name          disease_name
0  Adalimumab  Rheumatoid arthritis

 Run 2 completed | rows=8 | latency=1.004s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 7

    drug_name          disease_name
0  Adalimumab  Rheumatoid arthritis

 Run 3 completed | rows=7 | latency=1.438s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 7

    drug_name          disease_name
0  Adalimumab  Rheumatoid arthritis

 Run 4 completed | rows=7 | latency=1.299s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with adalimumab?
  Attempt 1/3
Entries retrieved: 7

    drug_name          disease_name
0  Adalimumab  Rheumatoid arthritis

 Run 5 completed | rows=7 | latency=0.937s
------------------------------------------------------------


## Question 46

**For which diseases is pembrolizumab used?**

In [48]:

question = 'For which diseases is pembrolizumab used?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 14

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 1 completed | rows=14 | latency=1.400s
------------------------------------------------------------

 Starting run 2 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 15

       drug_name disease_name
0  pembrolizumab     Melanoma

 Run 2 completed | rows=15 | latency=1.363s
------------------------------------------------------------

 Starting run 3 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 15

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 3 completed | rows=15 | latency=1.352s
------------------------------------------------------------

 Starting run 4 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 10

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 4 completed | rows=10 | latency=1.219s
------------------------------------------------------------

 Starting run 5 for query: For which diseases is pembrolizumab used?
  Attempt 1/3
Entries retrieved: 10

       drug_name disease_name
0  Pembrolizumab     Melanoma

 Run 5 completed | rows=10 | latency=1.303s
------------------------------------------------------------


## Question 47

**Which diseases are treated with sorafenib?**

In [49]:

question = 'Which diseases are treated with sorafenib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  hepatocellular carcinoma

 Run 1 completed | rows=3 | latency=0.773s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  hepatocellular carcinoma

 Run 2 completed | rows=3 | latency=0.692s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  Hepatocellular carcinoma

 Run 3 completed | rows=3 | latency=0.858s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  hepatocellular carcinoma

 Run 4 completed | rows=3 | latency=0.770s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with sorafenib?
  Attempt 1/3
Entries retrieved: 3

   drug_name              disease_name
0  Sorafenib  hepatocellular carcinoma

 Run 5 completed | rows=3 | latency=0.720s
------------------------------------------------------------


## Question 48

**Which diseases are treated with nivolumab?**

In [50]:

question = 'Which diseases are treated with nivolumab?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     Melanoma

 Run 1 completed | rows=6 | latency=0.972s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     Melanoma

 Run 2 completed | rows=6 | latency=0.914s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     Melanoma

 Run 3 completed | rows=6 | latency=0.895s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 8

   drug_name disease_name
0  nivolumab     Melanoma

 Run 4 completed | rows=8 | latency=0.989s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are treated with nivolumab?
  Attempt 1/3
Entries retrieved: 6

   drug_name disease_name
0  nivolumab     Melanoma

 Run 5 completed | rows=6 | latency=0.862s
------------------------------------------------------------


## Question 49

**Which genes are associated with multiple sclerosis?**

In [51]:

question = 'Which genes are associated with multiple sclerosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 1 completed | rows=5 | latency=0.871s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 2 completed | rows=5 | latency=0.855s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 3 completed | rows=5 | latency=0.833s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 4 completed | rows=4 | latency=0.806s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with multiple sclerosis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Multiple Sclerosis  HLA-DRB1

 Run 5 completed | rows=4 | latency=0.925s
------------------------------------------------------------


## Question 50

**Which genes are associated with rheumatoid arthritis?**

In [52]:

question = 'Which genes are associated with rheumatoid arthritis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0  HLA-DRB1  Rheumatoid arthritis

 Run 1 completed | rows=5 | latency=0.809s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0  HLA-DRB1  Rheumatoid arthritis

 Run 2 completed | rows=5 | latency=0.842s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 3 completed | rows=5 | latency=0.936s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 5

  gene_name          disease_name
0  HLA-DRB1  Rheumatoid arthritis

 Run 4 completed | rows=5 | latency=0.841s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with rheumatoid arthritis?
  Attempt 1/3
Entries retrieved: 6

           disease_name gene_name
0  Rheumatoid arthritis  HLA-DRB1

 Run 5 completed | rows=6 | latency=0.975s
------------------------------------------------------------


## Question 51

**What are the known targets of abatacept?**

In [53]:

question = 'What are the known targets of abatacept?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 1 completed | rows=2 | latency=0.745s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 2 completed | rows=2 | latency=1.035s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 3 completed | rows=2 | latency=0.691s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 4 completed | rows=2 | latency=0.718s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of abatacept?
  Attempt 1/3
Entries retrieved: 2

   drug_name gene_name
0  abatacept      CD80

 Run 5 completed | rows=2 | latency=0.721s
------------------------------------------------------------


## Question 52

**Which genes are associated with lung cancer?**

In [54]:

question = 'Which genes are associated with lung cancer?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Lung cancer      EGFR

 Run 1 completed | rows=3 | latency=0.856s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0  Lung cancer      EGFR

 Run 2 completed | rows=4 | latency=0.746s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Lung cancer      EGFR

 Run 3 completed | rows=3 | latency=0.838s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Lung cancer      EGFR

 Run 4 completed | rows=3 | latency=0.776s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with lung cancer?
  Attempt 1/3
Entries retrieved: 4

  disease_name gene_name
0  Lung cancer      EGFR

 Run 5 completed | rows=4 | latency=1.030s
------------------------------------------------------------


## Question 53

**What are the known targets of ponatinib?**

In [55]:

question = 'What are the known targets of ponatinib?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  ponatinib      ABL1

 Run 1 completed | rows=10 | latency=0.898s
------------------------------------------------------------

 Starting run 2 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 11

   drug_name gene_name
0  ponatinib      ABL1

 Run 2 completed | rows=11 | latency=0.960s
------------------------------------------------------------

 Starting run 3 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 6

   drug_name gene_name
0  ponatinib      ABL1

 Run 3 completed | rows=6 | latency=0.791s
------------------------------------------------------------

 Starting run 4 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 5

   drug_name gene_name
0  ponatinib      ABL1

 Run 4 completed | rows=5 | latency=0.933s
------------------------------------------------------------

 Starting run 5 for query: What are the known targets of ponatinib?
  Attempt 1/3
Entries retrieved: 10

   drug_name gene_name
0  ponatinib      ABL1

 Run 5 completed | rows=10 | latency=0.919s
------------------------------------------------------------


## Question 54

**Which drugs are used to treat systemic lupus erythematosus?**

In [56]:

question = 'Which drugs are used to treat systemic lupus erythematosus?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 1 completed | rows=6 | latency=0.940s
------------------------------------------------------------

 Starting run 2 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 8

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 2 completed | rows=8 | latency=1.314s
------------------------------------------------------------

 Starting run 3 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 3 completed | rows=6 | latency=0.965s
------------------------------------------------------------

 Starting run 4 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 5

            drug_name                  disease_name
0  Hydroxychloroquine  Systemic lupus erythematosus

 Run 4 completed | rows=5 | latency=0.980s
------------------------------------------------------------

 Starting run 5 for query: Which drugs are used to treat systemic lupus erythematosus?
  Attempt 1/3
Entries retrieved: 6

            drug_name                  disease_name
0  Hydroxychloroquine  systemic lupus erythematosus

 Run 5 completed | rows=6 | latency=1.134s
------------------------------------------------------------


## Question 55

**Which genes are associated with autism spectrum disorder?**

In [57]:

question = 'Which genes are associated with autism spectrum disorder?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 4

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 1 completed | rows=4 | latency=0.951s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 4

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 2 completed | rows=4 | latency=0.859s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 4

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 3 completed | rows=4 | latency=1.024s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 5

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 4 completed | rows=5 | latency=0.903s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with autism spectrum disorder?
  Attempt 1/3
Entries retrieved: 5

               disease_name gene_name
0  Autism spectrum disorder    SHANK3

 Run 5 completed | rows=5 | latency=0.938s
------------------------------------------------------------


## Question 56

**Which diseases are associated with the ROS1 gene?**

In [58]:

question = 'Which diseases are associated with the ROS1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                    disease_name gene_name
0  Non-small cell lung carcinoma      ROS1

 Run 1 completed | rows=2 | latency=0.788s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 3

                    disease_name gene_name
0  Non-small cell lung carcinoma      ROS1

 Run 2 completed | rows=3 | latency=1.103s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                    disease_name gene_name
0  Non-small cell lung carcinoma      ROS1

 Run 3 completed | rows=2 | latency=0.759s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 2

                    disease_name gene_name
0  Non-small cell lung carcinoma      ROS1

 Run 4 completed | rows=2 | latency=1.212s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ROS1 gene?
  Attempt 1/3
Entries retrieved: 3

                    disease_name gene_name
0  Non-small cell lung carcinoma      ROS1

 Run 5 completed | rows=3 | latency=0.879s
------------------------------------------------------------


## Question 57

**Which diseases are associated with the ALK gene?**

In [59]:

question = 'Which diseases are associated with the ALK gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma       ALK

 Run 1 completed | rows=4 | latency=0.980s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma       ALK

 Run 2 completed | rows=4 | latency=0.914s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma       ALK

 Run 3 completed | rows=4 | latency=0.969s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma       ALK

 Run 4 completed | rows=4 | latency=0.976s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the ALK gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma       ALK

 Run 5 completed | rows=4 | latency=1.054s
------------------------------------------------------------


## Question 58

**Which diseases are associated with the EGFR gene?**

In [60]:

question = 'Which diseases are associated with the EGFR gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma      EGFR

 Run 1 completed | rows=4 | latency=0.834s
------------------------------------------------------------

 Starting run 2 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma      EGFR

 Run 2 completed | rows=4 | latency=0.775s
------------------------------------------------------------

 Starting run 3 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma      EGFR

 Run 3 completed | rows=4 | latency=0.848s
------------------------------------------------------------

 Starting run 4 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma      EGFR

 Run 4 completed | rows=4 | latency=0.820s
------------------------------------------------------------

 Starting run 5 for query: Which diseases are associated with the EGFR gene?
  Attempt 1/3
Entries retrieved: 4

                    disease_name gene_name
0  Non-small cell lung carcinoma      EGFR

 Run 5 completed | rows=4 | latency=0.756s
------------------------------------------------------------


## Question 59

**Which genes are associated with psoriasis?**

In [61]:

question = 'Which genes are associated with psoriasis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0    Psoriasis     IL23R

 Run 1 completed | rows=5 | latency=1.004s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0    Psoriasis     IL23R

 Run 2 completed | rows=5 | latency=0.899s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0    Psoriasis     HLA-C

 Run 3 completed | rows=3 | latency=1.575s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 5

  disease_name gene_name
0    Psoriasis     IL23R

 Run 4 completed | rows=5 | latency=0.947s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with psoriasis?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0    Psoriasis     HLA-C

 Run 5 completed | rows=3 | latency=0.939s
------------------------------------------------------------


## Question 60

**Which genes are associated with ulcerative colitis?**

In [62]:

question = 'Which genes are associated with ulcerative colitis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 1 completed | rows=4 | latency=0.937s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 2 completed | rows=5 | latency=1.580s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 6

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 3 completed | rows=6 | latency=0.915s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 4

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 4 completed | rows=4 | latency=0.942s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with ulcerative colitis?
  Attempt 1/3
Entries retrieved: 5

         disease_name gene_name
0  Ulcerative colitis     IL23R

 Run 5 completed | rows=5 | latency=1.006s
------------------------------------------------------------


## Question 61

**Which genes are associated with tuberculosis?**

In [7]:

question = 'Which genes are associated with tuberculosis?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 3

   disease_name gene_name
0  Tuberculosis      IFNG

 Run 1 completed | rows=3 | latency=0.808s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 5

   disease_name gene_name
0  Tuberculosis  HLA-DRB1

 Run 2 completed | rows=5 | latency=1.033s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 3

   disease_name gene_name
0  Tuberculosis      IFNG

 Run 3 completed | rows=3 | latency=1.014s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 3

   disease_name gene_name
0  Tuberculosis      IFNG

 Run 4 completed | rows=3 | latency=0.868s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with tuberculosis?
  Attempt 1/3
Entries retrieved: 4

   disease_name gene_name
0  Tuberculosis      IFNG

 Run 5 completed | rows=4 | latency=0.990s
------------------------------------------------------------


## Question 62

**Which genes are associated with hepatitis C?**

In [64]:

question = 'Which genes are associated with hepatitis C?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Hepatitis C     IL28B

 Run 1 completed | rows=3 | latency=0.936s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Hepatitis C     IL28B

 Run 2 completed | rows=3 | latency=0.971s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Hepatitis C     IL28B

 Run 3 completed | rows=3 | latency=1.100s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Hepatitis C     IL28B

 Run 4 completed | rows=3 | latency=0.948s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with hepatitis C?
  Attempt 1/3
Entries retrieved: 3

  disease_name gene_name
0  Hepatitis C     IL28B

 Run 5 completed | rows=3 | latency=0.846s
------------------------------------------------------------


## Question 63

**Which genes are associated with Hodgkin lymphoma?**

In [65]:

question = 'Which genes are associated with Hodgkin lymphoma?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 3

       disease_name gene_name
0  Hodgkin lymphoma      TP53

 Run 1 completed | rows=3 | latency=1.057s
------------------------------------------------------------

 Starting run 2 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 4

       disease_name gene_name
0  Hodgkin lymphoma      TP53

 Run 2 completed | rows=4 | latency=0.891s
------------------------------------------------------------

 Starting run 3 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name      disease_name
0      JAK2  Hodgkin lymphoma

 Run 3 completed | rows=5 | latency=0.929s
------------------------------------------------------------

 Starting run 4 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 5

  gene_name      disease_name
0      JAK2  Hodgkin lymphoma

 Run 4 completed | rows=5 | latency=0.961s
------------------------------------------------------------

 Starting run 5 for query: Which genes are associated with Hodgkin lymphoma?
  Attempt 1/3
Entries retrieved: 4

       disease_name gene_name
0  Hodgkin lymphoma      TP53

 Run 5 completed | rows=4 | latency=0.900s
------------------------------------------------------------


## Question 64

**Which pathways are associated with TP53?**

In [66]:

question = 'Which pathways are associated with TP53?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 1 completed | rows=3 | latency=0.817s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 2 completed | rows=3 | latency=1.009s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 3 completed | rows=3 | latency=0.812s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 4 completed | rows=3 | latency=0.770s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with TP53?
  Attempt 1/3
Entries retrieved: 3

  gene_name           pathway_name
0      TP53  p53 signaling pathway

 Run 5 completed | rows=3 | latency=1.028s
------------------------------------------------------------


## Question 65

**Which drugs target ERBB2?**

In [67]:

question = 'Which drugs target ERBB2?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 5

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 1 completed | rows=5 | latency=1.000s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 5

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 2 completed | rows=5 | latency=1.425s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 5

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 3 completed | rows=5 | latency=0.951s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 5

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 4 completed | rows=5 | latency=0.951s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target ERBB2?
  Attempt 1/3
Entries retrieved: 6

     drug_name gene_name
0  Trastuzumab     ERBB2

 Run 5 completed | rows=6 | latency=1.080s
------------------------------------------------------------


## Question 66

**Which pathways are associated with the ADRB1 gene?**

In [68]:

question = 'Which pathways are associated with the ADRB1 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name            pathway_name
0     ADRB1  cAMP signaling pathway

 Run 1 completed | rows=3 | latency=0.861s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                                       pathway_name
0     ADRB1  Adenylate cyclase-activating G protein-coupled...

 Run 2 completed | rows=3 | latency=0.858s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 4

                                   pathway_name gene_name
0  Catecholamine biosynthesis-signaling pathway     ADRB1

 Run 3 completed | rows=4 | latency=0.860s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 5

             pathway_name gene_name
0  cAMP signaling pathway     ADRB1

 Run 4 completed | rows=5 | latency=1.047s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the ADRB1 gene?
  Attempt 1/3
Entries retrieved: 3

      pathway_name gene_name
0  Renin secretion     ADRB1

 Run 5 completed | rows=3 | latency=0.700s
------------------------------------------------------------


## Question 67

**Which pathways are associated with the DRD2 gene?**

In [69]:

question = 'Which pathways are associated with the DRD2 gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 2

  gene_name                 pathway_name
0      DRD2  Dopamine receptor signaling

 Run 1 completed | rows=2 | latency=0.911s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 5

           pathway_name gene_name
0  Dopaminergic synapse      DRD2

 Run 2 completed | rows=5 | latency=1.054s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0      DRD2  Dopamine receptor signaling

 Run 3 completed | rows=4 | latency=0.984s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                 pathway_name
0      DRD2  Dopamine receptor signaling

 Run 4 completed | rows=4 | latency=1.056s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the DRD2 gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                 pathway_name
0      DRD2  Dopamine receptor signaling

 Run 5 completed | rows=3 | latency=0.930s
------------------------------------------------------------


## Question 68

**Which pathways are associated with the HTR2A gene?**

In [70]:

question = 'Which pathways are associated with the HTR2A gene?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                  pathway_name
0     HTR2A  Serotonin receptor signaling

 Run 1 completed | rows=3 | latency=0.857s
------------------------------------------------------------

 Starting run 2 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 2

               pathway_name gene_name
0  5-HT2 receptor signaling     HTR2A

 Run 2 completed | rows=2 | latency=0.847s
------------------------------------------------------------

 Starting run 3 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                  pathway_name
0     HTR2A  Serotonin receptor signaling

 Run 3 completed | rows=4 | latency=0.933s
------------------------------------------------------------

 Starting run 4 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 3

  gene_name                       pathway_name
0     HTR2A  5-HT2A receptor signaling pathway

 Run 4 completed | rows=3 | latency=0.816s
------------------------------------------------------------

 Starting run 5 for query: Which pathways are associated with the HTR2A gene?
  Attempt 1/3
Entries retrieved: 4

  gene_name                  pathway_name
0     HTR2A  Serotonin receptor signaling

 Run 5 completed | rows=4 | latency=0.950s
------------------------------------------------------------


## Question 69

**Which drugs target CD19?**

In [71]:

question = 'Which drugs target CD19?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 5

    drug_name gene_name
0  Tafluprost      CD19

 Run 1 completed | rows=5 | latency=1.157s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 3

     drug_name gene_name
0  Tafasitamab      CD19

 Run 2 completed | rows=3 | latency=1.137s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 3

    drug_name gene_name
0  Tafluprost      CD19

 Run 3 completed | rows=3 | latency=1.172s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 6

    drug_name gene_name
0  Tafluprost      CD19

 Run 4 completed | rows=6 | latency=1.349s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CD19?
  Attempt 1/3
Entries retrieved: 2

     drug_name gene_name
0  Tafasitamab      CD19

 Run 5 completed | rows=2 | latency=0.870s
------------------------------------------------------------


## Question 70

**Which drugs target CTLA4?**

In [72]:

question = 'Which drugs target CTLA4?'


dct_result[model].setdefault(question, {})



for run_number in RUNS:
    print(f"\n Starting run {run_number} for query: {question}")

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Attempt {attempt}/{MAX_RETRIES}")

        

        try:
            df=None
            latency=None
            start_time = time.perf_counter()
            df = await return_grok_answer(question)
            latency = time.perf_counter() - start_time

            if latency>3:
                continue

            if len(df.columns)<2:
                continue


            if not isinstance(df, pd.DataFrame):
                raise ValueError("Returned object is not a DataFrame")
            if df.empty:
                raise ValueError("Returned DataFrame is empty")

            dct_result[model][question][run_number] = {
                "rows": df.shape[0],
                "latency": latency,
                "dataframe": df,
            }

            print(
                f" Run {run_number} completed | "
                f"rows={df.shape[0]} | latency={latency:.3f}s"
            )
            break

        except Exception as e:
            latency = time.perf_counter() - start_time
            print(f" Attempt {attempt} failed after {latency:.3f}s: {e}")

            if attempt == MAX_RETRIES:
                print(f" Run {run_number} failed after {MAX_RETRIES} attempts")

    print("-" * 60)

 Starting run 1 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 1 completed | rows=2 | latency=0.758s
------------------------------------------------------------

 Starting run 2 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 2 completed | rows=2 | latency=0.840s
------------------------------------------------------------

 Starting run 3 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 3 completed | rows=2 | latency=0.792s
------------------------------------------------------------

 Starting run 4 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 4 completed | rows=2 | latency=0.833s
------------------------------------------------------------

 Starting run 5 for query: Which drugs target CTLA4?
  Attempt 1/3
Entries retrieved: 2

    drug_name gene_name
0  Ipilimumab     CTLA4

 Run 5 completed | rows=2 | latency=0.828s
------------------------------------------------------------

In [ ]:
# import pickle
# with open("Grok_same_question_response_final.pkl", "wb") as f:
#     pickle.dump(dct_result, f)

# def make_json_safe(obj):
#     if isinstance(obj, pd.DataFrame):
#         return {
#             "__type__": "dataframe",
#             "columns": obj.columns.tolist(),
#             "rows": obj.to_dict(orient="records")
#         }
#     elif isinstance(obj, dict):
#         return {k: make_json_safe(v) for k, v in obj.items()}
#     elif isinstance(obj, list):
#         return [make_json_safe(v) for v in obj]
#     else:
#         return obj


# json_safe_result = make_json_safe(dct_result)

# with open("Grok_same_question_response_final.json", "w", encoding="utf-8") as f:
#     json.dump(
#         json_safe_result,
#         f,
#         indent=2,
#         ensure_ascii=False
#     )